Repository Automattic/woocommerce-payments, pull requests merged in 2020-11, with the labels that each got.

#1077 Update @woocommerce/components dependency to 5.1.2
  babel.config.js
  client/components/horizontal-list/test/__snapshots__/index.js.snap
  client/deposits/list/test/__snapshots__/index.js.snap
  client/deposits/overview/test/__snapshots__/index.js.snap
  client/deposits/overview/test/index.js
  client/disputes/test/__snapshots__/index.js.snap
  client/payment-details/summary/test/__snapshots__/index.js.snap
  client/transactions/list/test/__snapshots__/index.js.snap
  package-lock.json
  package.json
  tests/js/jest.config.js
  tests/js/jest.config.json
Labels: [Status] Needs Review

#1078 Optimize the size of the SVG credit card images and the wp.org banners
  assets/images/cards/amex.svg
  assets/images/cards/diners.svg
  assets/images/cards/discover.svg
  assets/images/cards/jcb.svg
  assets/images/cards/mastercard.svg
  assets/images/cards/unionpay.svg
  assets/images/cards/unknown.svg
  assets/images/cards/visa.svg
  wordpress-org-assets/banner-1544x500.png
  wordpress-org-assets/banner-772x250.png
  wordpress-org-assets/icon-128x128.png
  wordpress-org-assets/icon-256x256.png
Labels: [Status] Ready to Merge

#1093 Include WPCOM in the jetpack version check
  woocommerce-payments.php
Labels: [Status] Needs Review

#993 Connect the TOS modal
  client/tos.js
  client/tos/disabled-notice.js
  client/tos/index.js
  client/tos/modal/index.js
  client/tos/modal/style.scss
  client/tos/modal/test/__snapshots__/index.js.snap
  client/tos/modal/test/index.js
  client/tos/request.js
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-tos-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  webpack.config.js
Labels: [Status] Ready to Merge

#983 Add ToS modal
  client/tos/disabled-notice.js
  client/tos/index.js
  client/tos/modal/index.js
  client/tos/modal/style.scss
  client/tos/modal/test/__snapshots__/index.js.snap
  client/tos/modal/test/index.js
  client/tos/request.js
  client/utils/index.js
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-tos-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  package-lock.json
  package.json
  tests/admin/test-class-wc-rest-payments-tos-controller.php
  tests/bootstrap.php
  webpack.config.js
Labels: [Status] Blocked

#1107 Revert Composer to 2.0.6 before install on Travis jobs
  .travis.yml
Labels: [Status] Needs Review

#1101 Update copy of set up page
  client/connect-account-page/strings.js
  client/connect-account-page/test/__snapshots__/index.js.snap
  client/tos/modal/index.js
  client/tos/modal/test/__snapshots__/index.js.snap
Labels: [Status] Needs Review

#1073 Added link to bank statements requirements in payments settings
  includes/class-wc-payment-gateway-wcpay.php
Labels: [Status] Needs Review

#1106 Add details about the current fees in the Settings screen
  changelog.txt
  client/account-fees/index.js
  client/account-fees/test/__snapshots__/index.js.snap
  client/account-fees/test/index.js
  client/components/progress-bar/index.js
  client/components/progress-bar/style.scss
  client/components/progress-bar/test/__snapshots__/index.js.snap
  client/components/progress-bar/test/index.js
  client/settings.js
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  readme.txt
Labels: [Status] Needs Review

#1044 Detect actioned notes and pass additional parameters to onboarding URL
  includes/class-wc-payments-account.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/wc-payment-api/test-class-wc-payments-api-client.php
Labels: [Feature] Account Based Pricing, [Status] Needs Review

#1111 Remove user_ip and user_agent info from ToS acceptance
  includes/admin/class-wc-rest-payments-tos-controller.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: [Status] Ready to Merge

#1115 Set max compression level for zip file produced by build:release.
  tasks/release.js
Labels: [Status] Ready to Merge

#1103 Added order note when payment fails mentioning the failure reason.
  changelog.txt
  includes/admin/class-wc-rest-payments-webhook-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php
  readme.txt
  tests/test-class-wc-payment-gateway-wcpay-process-payment.php
Labels: [Status] Ready to Merge

#1121 Group all compatibility Travis jobs in one section for faster builds
  .travis.yml
Labels: [Status] Ready to Merge

#1119 Disable automerging for minor updates (renovate bot)
  renovate.json
Labels: [Status] Ready to Merge

#1097 Fix infinite recursion when having more than 10 saved cards
  changelog.txt
  includes/class-wc-payments-token-service.php
  readme.txt
Labels: [Status] Ready to Merge

#1129 Catch exceptions in the get_latest_tos_agreement function
  changelog.txt
  includes/class-wc-payments-account.php
  readme.txt
Labels: [Status] Ready to Merge

#972 Decouple test and live customers
  changelog.txt
  includes/class-wc-payments-account.php
  includes/class-wc-payments-customer-service.php
  includes/class-wc-payments.php
  readme.txt
  tests/admin/test-class-wc-rest-payments-tos-controller.php
  tests/test-class-wc-payments-customer-service.php
Labels: [Status] Ready to Merge

#1132 Update .org assests screenshots
  wordpress-org-assets/screenshot-1.jpg
  wordpress-org-assets/screenshot-2.jpg
  wordpress-org-assets/screenshot-3.jpg
  wordpress-org-assets/screenshot-4.jpg
Labels: [Status] Ready to Merge

#1128 Turn xdebug off by default
  README.md
  docker/wordpress_xdebug/Dockerfile
  tests/e2e/env/wordpress-xdebug/Dockerfile
Labels: [Status] Ready to Merge
