Repository Automattic/woocommerce-payments, pull requests merged in 2020-09, with the labels that each got.

#760 Prevent plugin initialization if Jetpack 8.1 or earlier is installed
  woocommerce-payments.php
Labels: [Status] Ready to Merge

#875 Add subscriptions unit tests
  includes/class-wc-payment-gateway-wcpay.php
  includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php
  includes/data-types/class-payment-information.php
  tests/bootstrap.php
  tests/data-types/test-class-payment-information.php
  tests/helpers/class-wc-helper-order.php
  tests/helpers/class-wc-helper-subscriptions.php
  tests/helpers/class-wc-helper-token.php
  tests/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/test-class-wc-payment-gateway-wcpay-subscriptions-process-payment.php
  tests/test-class-wc-payment-gateway-wcpay-subscriptions.php
  tests/test-class-wc-payments-token-service.php
Labels: [Status] Ready to Merge

#888 Fix settings UI in dev mode
  includes/class-wc-payment-gateway-wcpay.php
Labels: [Status] Ready to Merge

#883 Move PaymentInformation to WCPay namespace
  includes/class-payment-information.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments.php
  includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php
  tests/test-class-payment-information.php
  tests/test-class-wc-payment-gateway-wcpay-process-payment.php
Labels: [Feature] Saved Cards and Subscriptions, [Status] Ready to Merge

#893 Add payment method details to My Account > Subscriptions pages
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php
  readme.txt
  tests/test-class-wc-payment-gateway-wcpay-subscriptions.php
Labels: [Status] Ready to Merge

#902 Fix the checkout in IE11
  changelog.txt
  client/checkout/index.js
  client/checkout/style.scss
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payment-gateway-wcpay.php
  readme.txt
  webpack.config.js
Labels: [Status] Needs Author Reply

#906 Add the order object and the "manual capture" setting to the Payment_Information class
  includes/class-payment-information.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php
  tests/test-class-payment-information.php
  tests/test-class-wc-payment-gateway-wcpay-process-payment.php
Labels: [Feature] Saved Cards and Subscriptions, [Status] Ready to Merge

#907 Docker Env: Removing the recursive `docker` directory from the plugin directory
  .gitignore
  docker-compose.yml
Labels: [Status] Needs Review, [Type] Enhancement

#890 Always load Tracker class at plugin init
  includes/class-wc-payments.php
Labels: [Status] Ready to Merge

#895 Add SSH client to our docker file
  docker/wordpress_xdebug/Dockerfile
Labels: Engineering, [Status] Needs Review

#905 Fix save payment method checkbox for Subscriptions payment method update
  changelog.txt
  includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php
  readme.txt
  tests/helpers/class-wc-helper-subscriptions-cart.php
  tests/helpers/class-wc-helper-subscriptions.php
  tests/test-class-wc-payment-gateway-wcpay-subscriptions-process-payment.php
  tests/test-class-wc-payment-gateway-wcpay-subscriptions.php
Labels: [Status] Ready to Merge

#872 Update Jetpack dependencies, including the autoloader
  changelog.txt
  composer.json
  composer.lock
  readme.txt
  woocommerce-payments.php
Labels: [Status] Needs Author Reply

#892 Add support for subscriptions admin payment method changes
  changelog.txt
  client/subscription-edit-page.js
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments.php
  includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php
  readme.txt
  tests/helpers/class-wc-helper-subscriptions.php
  tests/test-class-wc-payment-gateway-wcpay-subscriptions-process-payment.php
  tests/test-class-wc-payment-gateway-wcpay-subscriptions.php
  webpack.config.js
Labels: [Status] Ready to Merge

#925 Add Transactions list column with Subscription link
  client/transactions/list/index.js
  client/transactions/list/test/__snapshots__/index.js.snap
  client/transactions/list/test/index.js
  includes/admin/class-wc-payments-admin.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: [Feature] Saved Cards and Subscriptions, [Status] Needs Review

#899 Fix checkout broken when user has bad account details store in meta.
  changelog.txt
  includes/class-wc-payments-customer-service.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  readme.txt
  tests/test-class-wc-payments-customer-service.php
Labels: [Status] Ready to Merge

#898 Add constants for payment information constructor
  composer.json
  composer.lock
  includes/class-payment-information.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments.php
  includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php
  includes/constants/class-payment-capture-type.php
  includes/constants/class-payment-initiated-by.php
  tests/test-class-payment-information.php
  tests/test-class-wc-payment-gateway-wcpay-process-payment.php
Labels: [Status] Ready to Merge

#932 Add subscription link into payment details view
  changelog.txt
  client/components/horizontal-list/style.scss
  client/payment-details/summary/index.js
  client/payment-details/summary/style.scss
  client/payment-details/summary/test/__snapshots__/index.js.snap
  client/payment-details/summary/test/index.js
  readme.txt
Labels: [Feature] Saved Cards and Subscriptions, [Status] Ready to Merge

#945 Adjust minimum compatible version to WC Subscriptions 2.2
  includes/class-wc-payments.php
Labels: [Status] Needs Review

#936 Support transaction search by Subscription number
  changelog.txt
  client/transactions/list/index.js
  includes/class-wc-payments-utils.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  readme.txt
  tests/helpers/class-wc-helper-subscription.php
  tests/helpers/class-wc-helper-subscriptions.php
  tests/test-class-wc-payments-utils.php
Labels: [Feature] Saved Cards and Subscriptions, [Status] Ready to Merge

#723 Initial checkout block support
  changelog.txt
  client/checkout/api/index.js
  client/checkout/blocks/confirm-card-payment.js
  client/checkout/blocks/fields.js
  client/checkout/blocks/generate-payment-method.js
  client/checkout/blocks/index.js
  client/checkout/blocks/request.js
  client/checkout/classic/index.js
  client/checkout/classic/style.scss
  client/checkout/constants.js
  client/checkout/index.js
  client/checkout/utils.js
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-blocks-payment-method.php
  includes/class-wc-payments.php
  package-lock.json
  package.json
  readme.txt
  webpack.config.js
Labels: [Status] Ready to Merge
