Repository Automattic/woocommerce-payments, pull requests merged in 2020-12, with the labels that each got.

#1134 Migrate from Travis to GitHub actions
  .github/e2e-test.yml
  .github/workflows/compatibility.yml
  .github/workflows/js-lint-test.yml
  .github/workflows/php-lint-test.yml
  .travis.yml
  bin/install-wp-tests.sh
  bin/phpunit.sh
  bin/run-ci-tests.bash
  tests/e2e/env/setup.sh
  tests/e2e/env/shared.sh
Labels: [Status] Needs Review

#1102 Display transaction fee structure in timeline
  changelog.txt
  client/payment-details/timeline/map-events.js
  client/payment-details/timeline/test/__snapshots__/map-events.js.snap
  client/payment-details/timeline/test/map-events.js
  readme.txt
Labels: [Status] Ready to Merge

#1146 Convert all moment objects to ISO strings before formatting
  client/account-fees/index.js
  client/account-status/index.js
  client/deposits/details/index.js
  client/deposits/list/index.js
  client/deposits/overview/index.js
  client/disputes/index.js
  client/disputes/info/index.js
  client/payment-details/summary/index.js
  client/payment-details/timeline/map-events.js
  client/transactions/list/deposit.js
  client/transactions/list/index.js
  client/utils/index.js
Labels: [Status] Ready to Merge

#1144 Add action hooks to allow custom webhook handling
  includes/admin/class-wc-rest-payments-webhook-controller.php
  tests/admin/test-class-wc-rest-payments-webhook.php
Labels: [Status] Ready to Merge

#1067 Register WC Pay nav items in WC navigation
  client/index.js
  client/settings.js
  includes/admin/class-wc-payments-admin.php
  webpack.config.js
Labels: [Status] Needs Design Review, [Status] Needs Review

#1156 Sync v1.7.1 changes with master
  changelog.txt
  client/settings.js
  package-lock.json
  package.json
  readme.txt
  woocommerce-payments.php
Labels: [Status] Needs Review

#1161 update tables to be fluid width
  client/components/page/style.scss
Labels: [Status] Ready to Merge

#1133 Prevent exceptions from WC_Payments_Account::get_cached_account_data
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-account.php
  tests/test-class-wc-payment-gateway-wcpay.php
  tests/test-class-wc-payments-account.php
Labels: [Status] Needs Review

#1165 Add changelog entry for PR#1133
  changelog.txt
  readme.txt
Labels: [Status] Ready to Merge

#1168 Fix undefined variable error
  includes/admin/class-wc-payments-admin.php
Labels: [Status] Ready to Merge

#1158 Resolve composer v2.0.8 compatibility issues with Jetpack Autoloader
  composer.json
  composer.lock
Labels: [Status] Needs Review

#1169 Add site username to OAuth data
  changelog.txt
  includes/class-wc-payments-account.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  readme.txt
  tests/wc-payment-api/test-class-wc-payments-api-client.php
Labels: [Status] Ready to Merge

#1170 Bump WP and WC tested to versions
  readme.txt
  woocommerce-payments.php
Labels: [Status] Needs Review

#1172 Prep for 1.8.0
  changelog.txt
  readme.txt
Labels: [Status] Ready to Merge

#1173 Install a specific version of xdebug (2.9.8)
  docker/wordpress_xdebug/Dockerfile
Labels: [Status] Ready to Merge

#1167 Fixes PHP 8 build failures in GitHub actions
  .github/workflows/compatibility.yml
  .travis.yml
  bin/install-wp-tests.sh
Labels: [Status] Ready to Merge

#1166 Second attempt migrating E2E tests to GH actions
  .github/workflows/e2e-test.yml
Labels: [Status] Ready to Merge

#1174 Moves all unit test files to single folder under '/tests'
  phpunit.xml.dist
  tests/unit/admin/test-class-wc-rest-payments-tos-controller.php
  tests/unit/admin/test-class-wc-rest-payments-webhook.php
  tests/unit/bootstrap.php
  tests/unit/helpers/class-wc-helper-order.php
  tests/unit/helpers/class-wc-helper-product.php
  tests/unit/helpers/class-wc-helper-shipping.php
  tests/unit/helpers/class-wc-helper-subscription.php
  tests/unit/helpers/class-wc-helper-subscriptions-cart.php
  tests/unit/helpers/class-wc-helper-subscriptions.php
  tests/unit/helpers/class-wc-helper-token.php
  tests/unit/notes/test-class-wc-payments-notes-set-up-refund-policy.php
  tests/unit/notes/test-class-wc-payments-remote-note-service.php
  tests/unit/test-class-payment-information.php
  tests/unit/test-class-wc-payment-gateway-wcpay-payment-types.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-account.php
  tests/unit/test-class-wc-payments-customer-service.php
  tests/unit/test-class-wc-payments-token-service.php
  tests/unit/test-class-wc-payments-utils.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: [Status] Ready to Merge

#1177 Fixed typo puppeter to puppeteer in e2e test's readme.
  tests/e2e/README.md
Labels: [Status] Ready to Merge

#1179 Testing: bug-fix db flags generation when waiting for DB
  bin/install-wp-tests.sh
Labels: [Status] Ready to Merge

#1180 Update to add setting to enable/disable saving cards
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  readme.txt
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: [Status] Ready to Merge

#1183 Update docs and CI due to default branch switch
  .github/workflows/e2e-test.yml
  CONTRIBUTING.md
  README.md
  tests/e2e/env/setup.sh
Labels: [Status] Needs Review

#1184 Fix v1.9.0 changelog header
  changelog.txt
Labels: [Status] Ready to Merge

#1182 Add login credentials to wp-admin and instruction to connect to MySQL.
  .github/workflows/js-lint-test.yml
  docker/README.md
  package.json
  tests/README.md
Labels: [Status] Ready to Merge
