Repository Automattic/woocommerce-payments, pull requests merged in 2020-07, with the labels that each got.

#725 Add/js/tracking
  client/connect-account-page/index.js
  client/data/disputes/actions.js
  client/disputes/details/actions.js
  client/disputes/evidence/index.js
Labels: [Status] Needs Author Reply

#756 Remove redundant code now that WCPay requires WC 4.0+
  includes/class-wc-payments.php
Labels: [Status] Ready to Merge

#745 Add 3DS support for pay for order page
  assets/js/wcpay-checkout.js
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments.php
  includes/exceptions/class-wc-payments-intent-authentication-exception.php
Labels: [Status] Ready to Merge

#772 Remove horizontal list items top border
  client/components/horizontal-list/style.scss
Labels: [Status] Ready to Merge

#628 Add test for payment complete
  includes/class-wc-payment-gateway-wcpay.php
  tests/test-class-wc-payment-gateway-wcpay-process-payment.php
Labels: [Status] Ready to Merge

#746 Run E2E tests with Travis
  .babelrc
  .eslintignore
  .eslintrc
  .gitignore
  .travis.yml
  bin/docker-setup.sh
  jsconfig.json
  package-lock.json
  package.json
  tests/e2e/README.md
  tests/e2e/config/.env
  tests/e2e/config/jest.config.js
  tests/e2e/config/test.json
  tests/e2e/env/default.env
  tests/e2e/env/docker-compose.yml
  tests/e2e/env/setup.sh
  tests/e2e/env/wordpress-xdebug/Dockerfile
  tests/e2e/setup/jest-setup.js
  tests/e2e/specs/purchase.spec.js
  tests/e2e/utils/flows.js
  tests/e2e/utils/index.js
Labels: [Status] Ready to Merge

#787 add composer install to readme
  README.md
Labels: [Status] Ready to Merge

#724 Add/php/tracking
  includes/admin/tracks/class-tracker.php
  includes/admin/tracks/tracks-loader.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments.php
  tests/bootstrap.php
Labels: [Status] Needs Review

#539 Experiment: add/e2e tests
  .babelrc
  .eslintignore
  .eslintrc
  .gitignore
  .travis.yml
  bin/docker-setup.sh
  jsconfig.json
  package-lock.json
  package.json
  tests/e2e/README.md
  tests/e2e/config/jest-puppeteer.config.js
  tests/e2e/config/jest.config.js
  tests/e2e/config/test.json
  tests/e2e/env/cleanup.sh
  tests/e2e/env/default.env
  tests/e2e/env/docker-compose.yml
  tests/e2e/env/down.sh
  tests/e2e/env/setup.sh
  tests/e2e/env/shared.sh
  tests/e2e/env/wordpress-xdebug/Dockerfile
  tests/e2e/setup/jest-setup.js
  tests/e2e/specs/purchase.spec.js
  tests/e2e/utils/debug.js
  tests/e2e/utils/flows.js
  tests/e2e/utils/index.js
  tests/e2e/utils/payments.js
  tests/js/jest.config.json
Labels: Engineering, Size M, [Status] Ready to Merge

#792 Bump WC tested version to 4.3
  woocommerce-payments.php
Labels: [Status] Ready to Merge

#764 Migrate remaining UI tests to RTL
  client/components/clickable-cell/test/__snapshots__/index.js.snap
  client/components/clickable-cell/test/index.js
  client/deposits/details/test/__snapshots__/index.js.snap
  client/deposits/details/test/index.js
  client/disputes/evidence/file-upload.js
  client/disputes/evidence/test/__snapshots__/file-upload.js.snap
  client/disputes/evidence/test/file-upload.js
  client/disputes/info/test/__snapshots__/index.js.snap
  client/disputes/info/test/index.js
  client/disputes/test/__snapshots__/index.js.snap
  client/disputes/test/index.js
  client/payment-details/summary/test/__snapshots__/index.js.snap
  client/payment-details/summary/test/index.js
  client/transactions/list/test/__snapshots__/deposit.js.snap
  client/transactions/list/test/deposit.js
  package.json
  tests/js/jest-test-file-setup.js
Labels: [Status] Ready to Merge

#786 Add npm script for running php unit tests
  package.json
Labels: Engineering, [Status] Ready to Merge

#793 Update changelog for the 1.2.0 release
  changelog.txt
  readme.txt
Labels: [Status] Ready to Merge

#795 Fix typo in Tracks event name
  client/disputes/evidence/index.js
Labels: [Status] Ready to Merge

#796 Bump versions for 1.2.0 release
  changelog.txt
  package-lock.json
  package.json
  readme.txt
  woocommerce-payments.php
Labels: [Status] Ready to Merge

#779 Include the selected date on transactions before or after filters
  client/data/transactions/resolvers.js
  client/data/transactions/test/resolvers.js
Labels: [Status] Ready to Merge

#631 Run wp-prettier in pre-commit hook
  .prettierignore
  .prettierrc
  package-lock.json
  package.json
Labels: Engineering, Size M, [Status] Ready to Merge, [Type] Try

#738 Fix missing payment status for disputes
  client/components/payment-status-chip/index.js
  client/components/payment-status-chip/mappings.js
  client/components/payment-status-chip/test/__snapshots__/index.js.snap
  client/components/payment-status-chip/test/index.js
  client/payment-details/summary/index.js
  client/payment-details/summary/test/__snapshots__/index.js.snap
  client/payment-details/summary/test/index.js
  client/utils/charge/index.js
  client/utils/charge/test/index.js
Labels: [Status] Ready to Merge

#712 Add transactions search bar
  client/data/transactions/hooks.js
  client/data/transactions/resolvers.js
  client/data/transactions/test/resolvers.js
  client/transactions/autocompleter.js
  client/transactions/filters/config.js
  client/transactions/list/index.js
  client/transactions/list/style.scss
  client/transactions/list/test/index.js
  client/utils/compute-suggestion-match.js
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-transactions-controller.php
  includes/class-wc-payments-utils.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/test-class-wc-payments-utils.php
Labels: [Status] Ready to Merge

#801 Fixes and adds missing translators comments in JS
  client/components/payment-status-chip/mappings.js
  client/data/disputes/actions.js
  client/disputes/details/index.js
  client/payment-details/timeline/map-events.js
Labels: [Status] Needs Review

#758 Add saved cards support
  assets/js/wcpay-checkout.js
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-customer-service.php
  includes/class-wc-payments-token-service.php
  includes/class-wc-payments-utils.php
  includes/class-wc-payments.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/test-class-wc-payment-gateway-wcpay.php
  tests/test-class-wc-payments-customer-service.php
  tests/test-class-wc-payments-token-service.php
  tests/wc-payment-api/test-class-wc-payments-api-client.php
Labels: [Status] Ready to Merge
