Repository Automattic/woocommerce-payments, pull requests merged in 2020-08, with the labels that each got.

#807 Remove out dated TODO comment
  includes/class-wc-payment-gateway-wcpay.php
Labels: [Status] Ready to Merge

#812 Fix Docker image name and tests
  docker-compose.yml
  docker/wordpress_xdebug/Dockerfile
  docker/wordpress_xdebug/custom.ini
  package.json
  phpunit.xml.dist
  tests/e2e/env/docker-compose.yml
Labels: [Status] Ready to Merge

#804 Don't redirect to the WCPay onboarding page if the WC core wizard should open instead
  includes/class-wc-payments-account.php
Labels: [Status] Ready to Merge

#805 Remove WooCommerce Admin from Docker setup
  bin/docker-setup.sh
Labels: [Status] Needs Review

#820 Fix e2e setup script
  tests/e2e/env/setup.sh
Labels: [Status] Needs Review

#816 Add saved cards E2E tests
  package.json
  tests/e2e/config/test.json
  tests/e2e/setup/jest-setup.js
  tests/e2e/specs/purchase.spec.js
  tests/e2e/specs/saved-cards/saved-cards-checkout.spec.js
  tests/e2e/specs/saved-cards/saved-cards-my-account.spec.js
  tests/e2e/utils/flows.js
  tests/e2e/utils/payments.js
Labels: [Status] Ready to Merge

#819 Fix checkout when creating an account and using 3DS cards
  assets/js/wcpay-checkout.js
  includes/class-wc-payment-gateway-wcpay.php
  tests/e2e/config/test.json
  tests/e2e/env/setup.sh
  tests/e2e/setup/jest-setup.js
  tests/e2e/specs/purchase.spec.js
  tests/e2e/specs/saved-cards/saved-cards-checkout.spec.js
  tests/e2e/specs/saved-cards/saved-cards-my-account.spec.js
  tests/e2e/utils/flows.js
  tests/e2e/utils/payments.js
  tests/test-class-wc-payment-gateway-wcpay-process-payment.php
Labels: [Status] Ready to Merge

#822 Add changelog entries for release
  changelog.txt
  readme.txt
Labels: [Status] Ready to Merge

#773 For 3DS flows, set charge id metadata before payment_complete()
  includes/class-wc-payment-gateway-wcpay.php
Labels: Size S, [Status] Ready to Merge

#788 Add/407 merchant descriptor
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/test-class-wc-payment-gateway-wcpay.php
  tests/test-class-wc-payments-account.php
Labels: Needs docs, [Status] Ready to Merge

#837 Direct link to the transaction detail view from the admin order detail page
  includes/class-wc-payment-gateway-wcpay.php
  readme.txt
Labels: [Status] Ready to Merge

#852 Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: [Status] Needs Review

#803 Implement Jetpack connection "soft disconnect"
  composer.json
  composer.lock
  includes/wc-payment-api/class-wc-payments-http.php
Labels: [Status] Ready to Merge

#829 Install WPCLI with docker and add the command to npm scripts
  docker/README.md
  docker/wordpress_xdebug/Dockerfile
  package.json
Labels: Engineering, [Status] Ready to Merge

#858 Update Contributors
  readme.txt
Labels: [Status] Ready to Merge

#826 Subscriptions integration step 1
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-token-service.php
  includes/class-wc-payments.php
  includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php
  includes/data-types/class-payment-information.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/test-class-wc-payments-token-service.php
Labels: [Status] Ready to Merge

#832 Add subscriber payment method changes
  includes/class-wc-payment-gateway-wcpay.php
  includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: [Status] Ready to Merge

#813 Remove WooCommerce as a composer dependency
  .travis.yml
  bin/install-wp-tests.sh
  composer.json
  composer.lock
  tests/bootstrap.php
Labels: [Status] Ready to Merge
