Repository Automattic/woocommerce-payments, pull requests merged in 2021-09, with the labels that each got.

#2812 Fix multi currency analytics leaderboard wrong currency
  changelog.txt
  includes/multi-currency/FrontendCurrencies.php
  includes/multi-currency/FrontendPrices.php
  includes/multi-currency/Utils.php
  readme.txt
  tests/unit/multi-currency/test-class-utils.php
Labels: pr: needs review

#2729 Add card declined rate limiter in card checkout
  includes/class-session-rate-limiter.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-customer-service.php
  includes/class-wc-payments.php
  includes/payment-methods/class-upe-payment-gateway.php
  tests/e2e/env/setup.sh
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
  tests/unit/test-class-session-rate-limiter.php
  tests/unit/test-class-wc-payment-gateway-wcpay-payment-types.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: needs review

#2779 E2E test for "Merchant / Order / Manual capture" flow
  tests/e2e/specs/merchant/merchant-orders-manual-capture.spec.js
  tests/e2e/utils/flows.js
Labels: pr: ready to merge, category: E2E

#2810 Adding Debug Logs to Multi-Currency
  includes/multi-currency/Analytics.php
  includes/multi-currency/MultiCurrency.php
  includes/multi-currency/Settings.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: ready to merge, needs feedback

#2807 Add DownloadButton component
  client/components/download-button/index.js
  client/components/download-button/style.scss
  client/components/download-button/test/__snapshots__/index.js.snap
  client/components/download-button/test/index.js
  client/deposits/list/index.js
  client/transactions/list/index.tsx
  client/transactions/list/style.scss
Labels: pr: ready to merge

#2795 Adds Tax calculations to WCPay Subscriptions and Invoices
  includes/subscriptions/class-wc-payments-invoice-service.php
  includes/subscriptions/class-wc-payments-product-service.php
  includes/subscriptions/class-wc-payments-subscription-service.php
  includes/subscriptions/class-wc-payments-subscriptions.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  psalm-baseline.xml
  tests/unit/helpers/class-wc-helper-subscription.php
  tests/unit/subscriptions/test-class-wc-payments-invoice-service.php
  tests/unit/subscriptions/test-class-wc-payments-product-service.php
  tests/unit/subscriptions/test-class-wc-payments-subscription-service.php
Labels: pr: ready to merge, component: stripe billing

#2834 E2E test for "Shopper / Subscriptions / Purchase subscription product" flow
  tests/e2e/specs/shopper/shopper-subscriptions-purchase-subscription-product.spec.js
  tests/e2e/utils/flows.js
Labels: pr: ready to merge, category: E2E

#2796 Fix currency formatter fallback exception on Safari < 14.1.2
  client/multi-currency/index.js
  client/utils/currency/index.js
  includes/multi-currency/Settings.php
Labels: type: bug, pr: ready to merge, component: customer multi-currency

#2856 Bump the Preview Mode experiment version number
  client/deposits/index.js
  client/transactions/index.tsx
  includes/admin/class-wc-payments-admin.php
Labels: pr: ready to merge

#2840 Fix Add enabled currencies modal UI bug
  changelog.txt
  client/components/confirmation-modal/styles.scss
  client/multi-currency/enabled-currencies-list/style.scss
  readme.txt
Labels: pr: ready to merge

#2824 Add checks for get_*_currencies methods in Multi-Currency
  includes/multi-currency/MultiCurrency.php
Labels: pr: ready to merge

#2853 Fix - error while checking out with UPE when fields are hidden
  changelog.txt
  client/checkout/classic/upe.js
  readme.txt
Labels: pr: ready to merge

#2811 Adds WCPay Subscriptions event/webhook handling code
  includes/admin/class-wc-rest-payments-webhook-controller.php
  includes/subscriptions/class-wc-payments-subscription-service.php
  includes/subscriptions/class-wc-payments-subscriptions-event-handler.php
  includes/subscriptions/class-wc-payments-subscriptions.php
  psalm-baseline.xml
  tests/unit/helpers/class-wc-helper-subscription.php
  tests/unit/helpers/class-wc-helper-subscriptions.php
  tests/unit/subscriptions/test-class-wc-payments-subscriptions-event-handler.php
  tests/unit/subscriptions/test-class-wc-payments-subscriptions.php
Labels: pr: ready to merge, component: stripe billing

#2839 Fix blank connect page when in treatment mode
  includes/admin/class-wc-payments-admin.php
Labels: type: bug, pr: ready to merge

#2850 Fix currency format in admin refund button
  changelog.txt
  includes/multi-currency/MultiCurrency.php
  readme.txt
Labels: pr: needs review

#2857 Clear selected currencies when closing modal for adding currencies
  changelog.txt
  client/multi-currency/enabled-currencies-list/modal.js
  readme.txt
Labels: pr: ready to merge

#2845 Add stub WP_UnitTestCase
  tests/WP_UnitTestCase.php
Labels: type: enhancement, pr: ready to merge

#2788 Add a class to handle updating the payment method after a billing invoice failure
  includes/class-wc-payment-gateway-wcpay.php
  includes/subscriptions/class-wc-payments-invoice-service.php
  includes/subscriptions/class-wc-payments-subscription-change-payment-method-handler.php
  includes/subscriptions/class-wc-payments-subscription-service.php
  includes/subscriptions/class-wc-payments-subscriptions-event-handler.php
  includes/subscriptions/class-wc-payments-subscriptions.php
  includes/subscriptions/subscriptions-base/includes/class-wc-subscriptions-cart.php
  includes/subscriptions/subscriptions-base/includes/class-wc-subscriptions-change-payment-gateway.php
  includes/subscriptions/subscriptions-base/includes/class-wc-subscriptions-coupon.php
  psalm-baseline.xml
  tests/unit/helpers/class-wc-helper-subscription.php
  tests/unit/subscriptions/test-class-wc-payments-subscription-change-payment-method.php
  tests/unit/subscriptions/test-class-wc-payments-subscription-service.php
Labels: pr: ready to merge, component: stripe billing

#2843 Only update the order status on failure outside of change payment requests
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge

#2879 Add changelog entry from #2843 to readme.txt
  readme.txt
Labels: pr: ready to merge

#2849 Add API to expose Multi-Currency widget to theme/plugin developers for easy integration
  changelog.txt
  includes/multi-currency/MultiCurrency.php
  includes/multi-currency/StorefrontIntegration.php
  includes/multi-currency/wc-payments-multi-currency.php
  readme.txt
  tests/unit/multi-currency/test-class-compatibility.php
  tests/unit/multi-currency/test-class-multi-currency.php
Labels: pr: needs review

#2886 Update MC tracking to include single currency settings usage.
  includes/multi-currency/Tracking.php
  tests/unit/multi-currency/test-class-tracking.php
Labels: pr: needs review

#2790 Split translations workflow
  .editorconfig
  .github/workflows/pre-release-publish-on-tag.yaml
Labels: pr: needs review

#2867 Fix duplicate account onboarding requests
  changelog.txt
  includes/class-wc-payments-account.php
  readme.txt
Labels: pr: ready to merge

#2502 Filter out error messages that shouldn't be displayed to customers
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-utils.php
  includes/exceptions/class-api-exception.php
  includes/payment-methods/class-giropay-payment-gateway.php
  includes/payment-methods/class-sofort-payment-gateway.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  readme.txt
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
Labels: pr: ready to merge

#2870 Create WC Pay customer on subscription creation
  includes/subscriptions/class-wc-payments-subscription-service.php
  tests/unit/subscriptions/test-class-wc-payments-subscription-service.php
Labels: pr: ready to merge, component: stripe billing

#2901 Fix Multi-Currency not showing converted prices with admin as referer
  includes/multi-currency/FrontendCurrencies.php
  includes/multi-currency/FrontendPrices.php
  includes/multi-currency/Utils.php
  tests/unit/multi-currency/test-class-utils.php
Labels: pr: needs review

#2830 Add Terminal Locations REST API
  includes/admin/class-wc-rest-payments-terminal-locations-controller.php
  includes/class-wc-payments.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/admin/test-class-wc-rest-payments-terminal-locations-controller.php
  tests/unit/bootstrap.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: ready to merge

#2902 Add order data to Multi-Currency tracking.
  includes/multi-currency/Tracking.php
  tests/unit/multi-currency/test-class-tracking.php
Labels: pr: ready to merge

#2786 Customer Multi-Currency Onboarding
  changelog.txt
  client/data/multi-currency/action-types.js
  client/data/multi-currency/actions.js
  client/data/multi-currency/hooks.js
  client/data/multi-currency/reducer.js
  client/data/multi-currency/resolvers.js
  client/data/multi-currency/selectors.js
  client/index.js
  client/multi-currency-setup/task.js
  client/multi-currency-setup/tasks/add-currencies-task/constants.js
  client/multi-currency-setup/tasks/add-currencies-task/index.js
  client/multi-currency-setup/tasks/add-currencies-task/index.scss
  client/multi-currency-setup/tasks/add-currencies-task/test/__snapshots__/index.test.js.snap
  client/multi-currency-setup/tasks/add-currencies-task/test/index.test.js
  client/multi-currency-setup/tasks/add-currencies-task/utils.js
  client/multi-currency-setup/tasks/multi-currency-setup.js
  client/multi-currency-setup/tasks/multi-currency-setup.scss
  client/multi-currency-setup/tasks/setup-complete-task/index.js
  client/multi-currency-setup/tasks/setup-complete-task/index.scss
  client/multi-currency-setup/tasks/setup-complete-task/test/index.test.js
  client/multi-currency-setup/tasks/store-settings-task/index.js
  client/multi-currency-setup/tasks/store-settings-task/index.scss
  client/multi-currency-setup/tasks/store-settings-task/test/__snapshots__/index.test.js.snap
  client/multi-currency-setup/tasks/store-settings-task/test/index.test.js
  client/multi-currency-setup/tasks/test/__snapshots__/multi-currency-setup.test.js.snap
  client/multi-currency-setup/tasks/test/multi-currency-setup.test.js
  client/multi-currency-setup/test/task.test.js
  client/multi-currency-setup/wizard/task-item.js
  client/multi-currency-setup/wizard/task-item.scss
  client/overview/index.js
  client/overview/task-list/tasks.js
  includes/admin/class-wc-payments-admin.php
  includes/multi-currency/MultiCurrency.php
  includes/multi-currency/Notes/NoteMultiCurrencyAvailable.php
  includes/multi-currency/RestController.php
  includes/multi-currency/StorefrontIntegration.php
  readme.txt
Labels: pr: needs review, pr: needs design review, component: customer multi-currency

#2910 Add setting to disable customer multi currency feature
  changelog.txt
  client/data/settings/actions.js
  client/data/settings/hooks.js
  client/data/settings/selectors.js
  client/settings/advanced-settings/index.js
  client/settings/advanced-settings/multi-currency-toggle.js
  client/settings/advanced-settings/test/multi-currency-toggle.test.js
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-settings-controller.php
  readme.txt
Labels: type: enhancement, pr: ready to merge, component: customer multi-currency

#2924 MC Onboarding: Enabled currencies missing currency bug
  client/multi-currency-setup/tasks/add-currencies-task/test/utils.test.js
  client/multi-currency-setup/tasks/add-currencies-task/utils.js
Labels: type: bug, pr: needs review, component: customer multi-currency

#2854 Add SEPA payment method.
  assets/css/admin.css
  assets/images/payment-methods/sepa_debit.svg
  client/additional-methods-setup/constants.js
  client/additional-methods-setup/methods-selector/add-payment-methods-task.js
  client/additional-methods-setup/methods-selector/test/add-payment-methods-task.test.js
  client/additional-methods-setup/upe-preview-methods-selector/add-payment-methods-task.js
  client/additional-methods-setup/upe-preview-methods-selector/test/add-payment-methods-task.test.js
  client/additional-methods-setup/upe-preview-methods-selector/test/setup-complete-task.test.js
  client/components/currency-information-for-methods/test/index.test.js
  client/components/payment-method-details/index.js
  client/payment-methods-map.js
  client/payment-methods/test/index.js
  client/settings/payment-method-icon/test/index.js
  client/settings/payment-methods-selector/test/index.js
  includes/class-wc-payments.php
  includes/payment-methods/class-sepa-payment-method.php
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
  tests/unit/multi-currency/test-class-payment-methods-compatibility.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
Labels: pr: ready to merge

#2832 Make MC Settings screen to use a 2 column layout
  changelog.txt
  client/multi-currency/enabled-currencies-list/index.js
  client/multi-currency/enabled-currencies-list/style.scss
  client/multi-currency/enabled-currencies-list/test/__snapshots__/index.js.snap
  client/multi-currency/index.js
  client/multi-currency/single-currency-settings/index.js
  client/multi-currency/single-currency-settings/style.scss
  client/multi-currency/single-currency-settings/test/__snapshots__/index.test.js.snap
  client/multi-currency/store-settings/index.js
  client/multi-currency/store-settings/style.scss
  client/settings/settings-layout/index.js
  client/settings/settings-section.scss
  includes/multi-currency/Settings.php
  includes/multi-currency/StorefrontIntegration.php
  readme.txt
Labels: component: customer multi-currency

#2787 Add dispute resolution task
  client/overview/index.js
  client/overview/task-list/index.js
  client/overview/task-list/tasks.js
  client/overview/task-list/test/index.js
  client/overview/task-list/test/tasks.js
  includes/admin/class-wc-payments-admin.php
  package-lock.json
  package.json
  readme.txt
Labels: pr: ready to merge, component: disputes

#2826 Add new E2E tests Shopper / WC Blocks / Checkout with normal and SCA cards
  .github/workflows/e2e-test.yml
  tests/e2e/README.md
  tests/e2e/config/test.json
  tests/e2e/env/docker-compose.yml
  tests/e2e/env/setup.sh
  tests/e2e/specs/README.md
  tests/e2e/specs/shopper/shopper-wc-blocks-checkout-purchase.spec.js
  tests/e2e/utils/flows.js
  tests/e2e/utils/payments.js
Labels: pr: ready to merge, category: E2E

#2916 Add light `npm run up` for quickly starting up docker environment with any config changes
  docker/README.md
  package.json
Labels: pr: ready to merge, type: task, category: engineering

#2933 Trigger an event to init the tokenization-form.js script
  client/checkout/classic/index.js
  client/checkout/classic/upe.js
  includes/class-wc-payment-gateway-wcpay.php
  includes/payment-methods/class-upe-payment-gateway.php
Labels: pr: ready to merge

#2909 Create Stripe products when attempting to get product and price IDs
  includes/subscriptions/class-wc-payments-product-service.php
  psalm-baseline.xml
  tests/unit/subscriptions/test-class-wc-payments-product-service.php
Labels: pr: ready to merge, component: stripe billing

#2920 String-handling improvements to pre-release publishing workflow
  .github/workflows/pre-release-publish-on-tag.yaml
Labels: pr: ready to merge

#2858 Add/e2e shopper subscriptions change pay method
  tests/e2e/config/test.json
  tests/e2e/specs/shopper/shopper-subscriptions-change-payment-method.spec.js
Labels: pr: ready to merge, category: E2E

#2881 Update webpack to v5
  package-lock.json
  package.json
  webpack.config.js
Labels: pr: ready to merge, type: technical debt

#2855 Add e2e test for "Shopper / Subscriptions / Purchase multiple subscriptions" flow
  tests/e2e/specs/shopper/shopper-subscriptions-purchase-multiple-subscriptions.spec.js
Labels: pr: ready to merge, category: E2E

#2884 Return upstream HTTP error code from terminal payment endpoint
  includes/admin/class-wc-rest-payments-orders-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  tests/unit/admin/test-class-wc-rest-payments-orders-controller.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: needs review

#2929 Show notices on currencies that are bound to an UPE method
  changelog.txt
  client/components/currency-delete-illustration/index.js
  client/components/currency-delete-illustration/styles.scss
  client/multi-currency/enabled-currencies-list/delete-button.js
  client/multi-currency/enabled-currencies-list/list-item.js
  client/multi-currency/enabled-currencies-list/style.scss
  client/multi-currency/enabled-currencies-list/test/__snapshots__/index.js.snap
  client/multi-currency/enabled-currencies-list/test/index.js
  includes/multi-currency/MultiCurrency.php
  includes/multi-currency/PaymentMethodsCompatibility.php
  includes/payment-methods/class-upe-payment-method.php
  readme.txt
  tests/unit/multi-currency/test-class-payment-methods-compatibility.php
Labels: pr: needs review, pr: needs design review, component: customer multi-currency

#2862 Currency switcher shouldn't affect Order confirmation screen prices
  changelog.txt
  includes/multi-currency/FrontendCurrencies.php
  includes/multi-currency/MultiCurrency.php
  readme.txt
  tests/unit/multi-currency/test-class-frontend-currencies.php
Labels: pr: ready to merge

#2966 Set plugin version to match tag name
  .github/workflows/pre-release-publish-on-tag.yaml
Labels: pr: ready to merge

#2951 Do not set UPE billing details when changing a subscription payment method
  changelog.txt
  client/checkout/classic/upe.js
  readme.txt
Labels: pr: needs author reply, component: stripe billing

#2899 Add order items directly to Stripe subscription
  includes/subscriptions/class-wc-payments-invoice-service.php
  includes/subscriptions/class-wc-payments-product-service.php
  includes/subscriptions/class-wc-payments-subscription-service.php
  includes/subscriptions/class-wc-payments-subscriptions-event-handler.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  psalm-baseline.xml
  tests/unit/helpers/class-wc-helper-subscription.php
  tests/unit/helpers/class-wc-helper-subscriptions-product.php
  tests/unit/subscriptions/test-class-wc-payments-invoice-service.php
  tests/unit/subscriptions/test-class-wc-payments-product-service.php
  tests/unit/subscriptions/test-class-wc-payments-subscription-service.php
  tests/unit/subscriptions/test-class-wc-payments-subscriptions-event-handler.php
Labels: pr: ready to merge, component: stripe billing

#2831 Multi-Currency track enabled currencies update
  changelog.txt
  client/data/multi-currency/actions.js
  client/tracks/index.js
  readme.txt
Labels: pr: ready to merge, component: customer multi-currency

#2934 Fix to an issue with attaching exchange rates for zero-decimal currencies
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-utils.php
  readme.txt
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-utils.php
Labels: pr: ready to merge

#2980 Bump supported versions for CI
  .github/workflows/compatibility.yml
  composer.json
  composer.lock
Labels: pr: ready to merge, type: task

#2936 Fix bug with adding order metadata fails and refund is not possible
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  readme.txt
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge

#2922 Add primary action to high priority tasks
  changelog.txt
  client/overview/task-list/tasks.js
Labels: pr: ready to merge

#2883 Gutenberg Block Widget for Currency Switcher
  changelog.txt
  client/multi-currency/blocks/currency-switcher.js
  includes/multi-currency/Analytics.php
  includes/multi-currency/CurrencySwitcherBlock.php
  includes/multi-currency/CurrencySwitcherWidget.php
  includes/multi-currency/MultiCurrency.php
  package-lock.json
  package.json
  readme.txt
  tests/unit/multi-currency/test-class-currency-switcher-block.php
  webpack.config.js
Labels: pr: ready to merge, component: customer multi-currency

#2955 Convert MC Settings page to React
  client/data/multi-currency/hooks.js
  client/multi-currency-setup/tasks/add-currencies-task/index.js
  client/multi-currency/enabled-currencies-list/index.js
  client/multi-currency/index.js
  client/multi-currency/multi-currency-settings/enabled-currencies-list/delete-button.js
  client/multi-currency/multi-currency-settings/enabled-currencies-list/index.js
  client/multi-currency/multi-currency-settings/enabled-currencies-list/list-item-placeholder.js
  client/multi-currency/multi-currency-settings/enabled-currencies-list/list-item.js
  client/multi-currency/multi-currency-settings/enabled-currencies-list/list.js
  client/multi-currency/multi-currency-settings/enabled-currencies-list/modal-checkbox-list.js
  client/multi-currency/multi-currency-settings/enabled-currencies-list/modal-checkbox.js
  client/multi-currency/multi-currency-settings/enabled-currencies-list/modal.js
  client/multi-currency/multi-currency-settings/enabled-currencies-list/style.scss
  client/multi-currency/multi-currency-settings/enabled-currencies-list/test/__snapshots__/index.js.snap
  client/multi-currency/multi-currency-settings/enabled-currencies-list/test/index.js
  client/multi-currency/multi-currency-settings/index.js
  client/multi-currency/multi-currency-settings/store-settings/index.js
  client/multi-currency/multi-currency-settings/store-settings/style.scss
  client/multi-currency/multi-currency-settings/store-settings/test/__snapshots__/index.test.js.snap
  client/multi-currency/multi-currency-settings/store-settings/test/index.test.js
  client/multi-currency/multi-currency-settings/style.scss
  client/multi-currency/multi-currency-settings/test/__snapshots__/index.test.js.snap
  client/multi-currency/multi-currency-settings/test/index.test.js
  client/multi-currency/single-currency-settings/constants.js
  client/multi-currency/single-currency-settings/currency-preview.js
  client/multi-currency/single-currency-settings/index.js
  client/multi-currency/single-currency-settings/style.scss
  client/multi-currency/single-currency-settings/test/__snapshots__/index.test.js.snap
  client/multi-currency/single-currency-settings/test/index.test.js
  client/multi-currency/store-settings/index.js
  client/multi-currency/store-settings/style.scss
  includes/multi-currency/MultiCurrency.php
  includes/multi-currency/Settings.php
  includes/multi-currency/StorefrontIntegration.php
  tests/unit/multi-currency/test-class-settings.php
  tests/unit/multi-currency/test-class-storefront-integration.php
Labels: pr: needs review, category: refactor, component: customer multi-currency

#2923 Add preview pane to auto currency switch feature
  client/data/multi-currency/reducer.js
  client/multi-currency-setup/tasks/add-currencies-task/index.js
  client/multi-currency-setup/tasks/add-currencies-task/test/__snapshots__/index.test.js.snap
  client/multi-currency-setup/tasks/store-settings-task/index.js
  client/multi-currency-setup/tasks/store-settings-task/index.scss
  client/multi-currency-setup/tasks/store-settings-task/test/index.test.js
  client/multi-currency/multi-currency-settings/store-settings/index.js
  client/multi-currency/multi-currency-settings/store-settings/test/__snapshots__/index.test.js.snap
  client/multi-currency/preview-modal/index.js
  client/multi-currency/preview-modal/index.scss
  client/multi-currency/single-currency-settings/index.js
  client/multi-currency/single-currency-settings/test/index.test.js
  includes/multi-currency/MultiCurrency.php
  includes/multi-currency/Settings.php
  tests/unit/multi-currency/test-class-multi-currency.php
Labels: pr: needs design review, pr: ready to merge, component: customer multi-currency

#2889 Update WCPay logo
  changelog.txt
  client/banner/wcpay-logo.js
  client/connect-account-page/test/__snapshots__/index.js.snap
  readme.txt
Labels: pr: needs review

#2996 Fix Shipping Cost not updating in Google Pay' payment sheet when changing payment method
  changelog.txt
  client/payment-request/event-handlers.js
  readme.txt
Labels: pr: ready to merge

#2992 Fix some of the flaky e2e tests
  tests/e2e/specs/merchant/merchant-orders-manual-capture.spec.js
  tests/e2e/specs/merchant/merchant-orders-partial-refund.spec.js
  tests/e2e/utils/flows.js
  tests/e2e/utils/payments.js
Labels: pr: needs review, category: E2E

#2990 Terminal locations: handle unpopulated store address gracefully
  includes/admin/class-wc-rest-payments-terminal-locations-controller.php
  tests/unit/admin/test-class-wc-rest-payments-terminal-locations-controller.php
Labels: pr: ready to merge

#2993 Fix translations in transaction/deposit exports
  changelog.txt
  client/deposits/list/index.js
  client/deposits/list/test/index.js
  client/transactions/list/index.tsx
  client/transactions/list/test/index.tsx
  readme.txt
Labels: pr: ready to merge

#2956 Fix transaction search with translated terms
  changelog.txt
  includes/class-wc-payments-utils.php
  readme.txt
Labels: pr: ready to merge

#2989 Add disount functionality and validation on invoice.upcoming
  includes/subscriptions/class-wc-payments-invoice-service.php
  includes/subscriptions/class-wc-payments-subscription-service.php
  includes/subscriptions/class-wc-payments-subscriptions-event-handler.php
  tests/unit/helpers/class-wc-helper-subscription.php
  tests/unit/subscriptions/test-class-wc-payments-invoice-service.php
  tests/unit/subscriptions/test-class-wc-payments-subscription-service.php
Labels: pr: ready to merge, component: stripe billing

#2485 Replace OAuth instances from the code with new connect onboarding flow
  changelog.txt
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-tos-controller.php
  includes/class-wc-payments-account.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  readme.txt
  tests/unit/admin/test-class-wc-rest-payments-tos-controller.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: ready to merge, component: onboarding
