Repository Automattic/woocommerce-payments, pull requests merged in 2021-10, with the labels that each got.

#2945 Bump supported versions for 3.1 release
  .github/workflows/compatibility.yml
  .github/workflows/coverage.yml
  .github/workflows/e2e-test.yml
  .github/workflows/php-lint-test.yml
  changelog.txt
  readme.txt
  tests/unit/bootstrap.php
  woocommerce-payments.php
Labels: pr: ready to merge, priority: high

#3008 fixed error when running e2e tests inside a folder with white spaces in the name
  tests/e2e/env/setup.sh
Labels: pr: ready to merge

#3006 Fix error message when adding new credit card
  changelog.txt
  client/checkout/classic/index.js
  client/checkout/classic/upe.js
  tests/e2e/specs/shopper/shopper-myaccount-payment-methods-add-fail.spec.js
Labels: pr: ready to merge

#3016 Fix 2 E2E tests Shopper Checkout Failures/Subscriptions Purchasing
  tests/e2e/specs/merchant/merchant-subscriptions-purchase-no-sign-up.spec.js
  tests/e2e/specs/merchant/merchant-subscriptions-purchase-sign-up-fee.spec.js
  tests/e2e/specs/merchant/merchant-subscriptions-renew-action-scheduler.spec.js
  tests/e2e/specs/merchant/merchant-subscriptions-renew-subscription.spec.js
  tests/e2e/specs/shopper/shopper-checkout-failures.spec.js
  tests/e2e/specs/shopper/shopper-myaccount-renew-subscription.spec.js
  tests/e2e/specs/shopper/shopper-subscriptions-change-payment-method.spec.js
  tests/e2e/specs/shopper/shopper-subscriptions-free-trial.spec.js
  tests/e2e/specs/shopper/shopper-subscriptions-manage-payments.spec.js
  tests/e2e/specs/shopper/shopper-subscriptions-purchase-multiple-subscriptions.spec.js
  tests/e2e/specs/shopper/shopper-subscriptions-purchase-subscription-product.spec.js
  tests/e2e/utils/flows.js
  tests/e2e/utils/payments.js
Labels: pr: needs review, priority: high, impact: high, category: E2E

#3010 Old WC versions: try loading WCPay if the account is connected
  changelog.txt
  includes/class-wc-payments.php
  readme.txt
Labels: pr: ready to merge, priority: high

#3019 Adds logging for checkout errors while using UPE
  changelog.txt
  client/checkout/api/index.js
  client/checkout/classic/upe.js
  includes/payment-methods/class-upe-payment-gateway.php
  readme.txt
Labels: pr: ready to merge

#2997 Fix capture payments later
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  readme.txt
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
Labels: pr: needs review, component: UPE

#3014 Add a command to toggle xdebug extension in WordPress container
  bin/xdebug-toggle.sh
  package.json
Labels: type: enhancement, pr: ready to merge, priority: low, category: engineering

#2882 Add new E2E test Shopper / WC Blocks / Checkout Failures
  tests/e2e/specs/shopper/shopper-wc-blocks-checkout-failures.spec.js
  tests/e2e/specs/shopper/shopper-wc-blocks-checkout-purchase.spec.js
  tests/e2e/utils/flows.js
Labels: pr: needs review, category: E2E

#3040 Fix fatal error when WooCommerce is not active
  includes/class-wc-payments.php
Labels: pr: ready to merge, priority: high, impact: high

#3013 Add: proxy endpoints for terminal locations API
  includes/admin/class-wc-rest-payments-terminal-locations-controller.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/admin/test-class-wc-rest-payments-terminal-locations-controller.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: needs review

#3051 Add changelog entries for `automattic/jetpack-connection` update
  changelog.txt
  readme.txt
Labels: pr: ready to merge

#3053 Create changelog entry for v3.2.0.
  changelog.txt
  readme.txt
Labels: pr: needs review

#3039 Fix track 'wcpay_payment_request_settings_change' not being recorded
  changelog.txt
  client/additional-methods-setup/methods-selector/add-payment-methods-task.js
  client/settings/save-settings-section/index.js
  client/tracks/index.js
  includes/class-wc-payments-payment-request-button-handler.php
Labels: pr: ready to merge

#3036 Added a filter to disable caching when in a development environment
  includes/multi-currency/Analytics.php
Labels: pr: ready to merge

#3061 Add admin notice to warn about deactivating WC Subscriptions
  includes/subscriptions/assets/css/plugin-page.css
  includes/subscriptions/assets/js/plugin-page.js
  includes/subscriptions/class-wc-payments-subscriptions-plugin-notice-manager.php
  includes/subscriptions/class-wc-payments-subscriptions.php
  includes/subscriptions/templates/html-subscriptions-plugin-notice.php
Labels: pr: needs review, component: WCPay Subscriptions

#3035 add position absolute to popup
  assets/css/admin.css
Labels: pr: ready to merge

#3030 Fix missing customer information after guest checkout via Checkout Block
  changelog.txt
  client/checkout/blocks/fields.js
  readme.txt
Labels: pr: ready to merge

#3065 Add callback to create new wcpay subscription on manual renewal
  includes/subscriptions/class-wc-payments-invoice-service.php
  includes/subscriptions/class-wc-payments-subscription-service.php
  psalm-baseline.xml
  tests/unit/helpers/class-wc-helper-subscription.php
  tests/unit/helpers/class-wc-helper-subscriptions.php
  tests/unit/subscriptions/test-class-wc-payments-invoice-service.php
  tests/unit/subscriptions/test-class-wc-payments-subscription-service.php
Labels: pr: needs review, component: WCPay Subscriptions

#3120 Only allow Renovate to run at the weekends
  renovate.json
Labels: pr: needs review, category: engineering

#3113 Attach the payment intent data to renewal orders
  includes/class-wc-payments.php
  includes/subscriptions/class-wc-payments-invoice-service.php
  includes/subscriptions/class-wc-payments-subscriptions-event-handler.php
  includes/subscriptions/class-wc-payments-subscriptions.php
  tests/unit/subscriptions/test-class-wc-payments-invoice-service.php
  tests/unit/subscriptions/test-class-wc-payments-subscriptions-event-handler.php
Labels: pr: ready to merge, component: WCPay Subscriptions

#3140 Pass parameters to the wc_get_template() function in the correct order
  includes/subscriptions/class-wc-payments-subscriptions-plugin-notice-manager.php
Labels: pr: ready to merge, component: WCPay Subscriptions

#3059 Fix payment failure when phone number is hidden
  changelog.txt
  client/checkout/blocks/confirm-upe-payment.js
  readme.txt
Labels: pr: ready to merge

#3145 Update the composer.lock to pull the latest WCS Core 1.0.0 changes
  composer.lock
Labels: pr: ready to merge

#3148 Enable the WCPay Subscriptions feature on eligible stores
  includes/class-wc-payments-features.php
Labels: pr: needs review, size: small, component: WCPay Subscriptions

#3133 Add compatibility for Multi-Currency and UPS plugin.
  changelog.txt
  includes/multi-currency/Compatibility.php
  includes/multi-currency/Compatibility/WooCommerceUPS.php
  includes/multi-currency/FrontendCurrencies.php
  includes/multi-currency/MultiCurrency.php
  readme.txt
  tests/unit/multi-currency/compatibility/test-class-woocommerce-ups.php
  tests/unit/multi-currency/test-class-frontend-currencies.php
Labels: pr: ready to merge

#3176 Use price_data exclusively when creating WCPay subscriptions
  includes/subscriptions/class-wc-payments-product-service.php
  includes/subscriptions/class-wc-payments-subscription-service.php
  tests/unit/subscriptions/test-class-wc-payments-product-service.php
  tests/unit/subscriptions/test-class-wc-payments-subscription-service.php
Labels: pr: ready to merge, component: WCPay Subscriptions

#3112 Add provision to display the capped fee in the breakdown
  client/payment-details/timeline/map-events.js
Labels: pr: ready to merge

#3080 Add documentation on handling Renovate PRs
  docs/renovate.md
Labels: pr: ready to merge

#3118 Allow payment_intent_succeeded webhook to handle orders without intent_id attached
  changelog.txt
  includes/admin/class-wc-rest-payments-webhook-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-db.php
  readme.txt
  tests/unit/admin/test-class-wc-rest-payments-webhook.php
Labels: pr: ready to merge, status: has PR

#3185 Always get the discounts from the subscription, not the parent order
  includes/subscriptions/class-wc-payments-subscription-service.php
Labels: pr: needs review

#3190 Update Subscriptions Core to v1.0.1
  composer.json
  composer.lock
Labels: pr: ready to merge, component: WCPay Subscriptions
