Repository Automattic/woocommerce-payments, pull requests merged in 2021-11, with the labels that each got.

#3264 Conditionally add woocommerce-tokenization-form as a checkout script dependency
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  includes/payment-methods/class-upe-payment-gateway.php
  readme.txt
Labels: pr: needs review

#3272 Fix typo in payment collected notice
  includes/subscriptions/class-wc-payments-subscription-service.php
Labels: pr: needs review

#3130 Add Dependency Service class
  includes/class-wc-payments-dependency-service.php
  includes/class-wc-payments.php
  tests/unit/test-class-wc-payments-dependency-service.php
Labels: pr: ready to merge, category: refactor

#3242 Fix incorrect calculated cost of booking via Multi-Currency
  changelog.txt
  includes/multi-currency/Compatibility.php
  includes/multi-currency/Compatibility/WooCommerceBookings.php
  readme.txt
  tests/unit/multi-currency/compatibility/test-class-woocommerce-bookings.php
Labels: pr: ready to merge

#3243 Move compatibility for Product Add Ons to its own class.
  changelog.txt
  includes/multi-currency/Compatibility.php
  includes/multi-currency/Compatibility/WooCommerceProductAddOns.php
  tests/unit/multi-currency/compatibility/test-class-woocommerce-product-add-ons.php
  tests/unit/multi-currency/test-class-compatibility.php
Labels: pr: ready to merge

#3284 Display risk for payment methods without risk assessment
  changelog.txt
  client/components/risk-level/index.js
  client/components/risk-level/strings.js
  client/components/risk-level/test/__snapshots__/index.js.snap
  client/components/risk-level/test/index.js
  readme.txt
Labels: pr: ready to merge, component: UPE

#3267 Limit period intervals in yearly subscription products
  changelog.txt
  includes/subscriptions/class-wc-payments-product-service.php
Labels: pr: ready to merge, component: WCPay Subscriptions

#3286 Add filters to disable or modify sql queries for Multi-Currency analytics
  changelog.txt
  includes/multi-currency/Analytics.php
  includes/multi-currency/Compatibility.php
  includes/multi-currency/Compatibility/WooCommerceBookings.php
  includes/multi-currency/Compatibility/WooCommerceFedEx.php
  includes/multi-currency/Compatibility/WooCommerceProductAddOns.php
  includes/multi-currency/Compatibility/WooCommerceUPS.php
  includes/multi-currency/MultiCurrency.php
  readme.txt
  tests/unit/multi-currency/test-class-analytics.php
Labels: pr: needs review

#3253 Limit amount of Apple Pay verification requests
  changelog.txt
  includes/class-wc-payments-apple-pay-registration.php
  readme.txt
  tests/unit/test-class-wc-payments-apple-pay-registration.php
Labels: pr: needs review

#3291 Schedule E2E Tests to run every 6 hours instead of every PR
  .github/workflows/e2e-test.yml
Labels: pr: ready to merge, category: engineering, category: e2e

#3296 Changed documentation links from docs.woocommerce.com to woocommerce.com
  README.md
  client/account-status-settings/test/__snapshots__/index.js.snap
  client/additional-methods-setup/upe-preview-methods-selector/add-payment-methods-task.js
  client/additional-methods-setup/upe-preview-methods-selector/enable-upe-preview-task.js
  client/components/account-status/account-fees/index.js
  client/components/account-status/account-fees/test/__snapshots__/index.js.snap
  client/components/account-status/test/__snapshots__/index.js.snap
  client/components/deposits-status/index.js
  client/components/deposits-status/test/__snapshots__/index.js.snap
  client/connect-account-page/modal/index.js
  client/connect-account-page/modal/test/__snapshots__/index.js.snap
  client/deposits/instant-deposits/modal.js
  client/deposits/instant-deposits/test/__snapshots__/index.js.snap
  client/deposits/utils/index.js
  client/multi-currency/multi-currency-settings/enabled-currencies-list/index.js
  client/multi-currency/multi-currency-settings/enabled-currencies-list/test/__snapshots__/index.js.snap
  client/multi-currency/multi-currency-settings/store-settings/index.js
  client/multi-currency/multi-currency-settings/store-settings/test/__snapshots__/index.test.js.snap
  client/multi-currency/single-currency-settings/index.js
  client/overview/task-list/tasks.js
  client/payment-gateways/disable-confirmation-modal.js
  client/payment-methods/index.js
  client/settings/advanced-settings/multi-currency-toggle.js
  client/settings/advanced-settings/wcpay-subscriptions-toggle.js
  client/settings/disable-upe-modal/index.js
  client/settings/general-settings/index.js
  client/settings/settings-manager/index.js
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-utils.php
  includes/multi-currency/SettingsOnboardCta.php
  includes/notes/class-wc-payments-notes-additional-payment-methods.php
  includes/notes/class-wc-payments-notes-instant-deposits-eligible.php
  includes/notes/class-wc-payments-notes-set-https-for-checkout.php
  includes/notes/class-wc-payments-notes-set-up-refund-policy.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/subscriptions/templates/html-subscriptions-plugin-notice.php
  readme.txt
  tests/unit/notes/test-class-wc-payments-notes-additional-payment-methods.php
Labels: pr: needs review

#3271 Don't try load Subscriptions Core when WooCommerce isn't active
  changelog.txt
  readme.txt
  woocommerce-payments.php
Labels: pr: ready to merge, component: WCPay Subscriptions

#3307 Run E2E Tests with every push to trunk/develop + manual trigger
  .github/workflows/e2e-test.yml
Labels: pr: ready to merge, category: engineering, category: e2e

#3188 Add in person text for US based stores
  client/connect-account-page/index.js
  client/connect-account-page/strings.js
  client/connect-account-page/test/__snapshots__/index.js.snap
Labels: pr: ready to merge

#3308 Do not create WCPay Subscriptions when using payment methods other than WCPay
  changelog.txt
  includes/subscriptions/class-wc-payments-subscription-service.php
  readme.txt
  tests/unit/subscriptions/test-class-wc-payments-subscription-service.php
Labels: pr: ready to merge, component: WCPay Subscriptions

#3259 Create BaseCompatibility class and extend compatibility classes from it.
  includes/multi-currency/Compatibility.php
  includes/multi-currency/Compatibility/BaseCompatibility.php
  includes/multi-currency/Compatibility/WooCommerceBookings.php
  includes/multi-currency/Compatibility/WooCommerceFedEx.php
  includes/multi-currency/Compatibility/WooCommerceProductAddOns.php
  includes/multi-currency/Compatibility/WooCommerceSubscriptions.php
  includes/multi-currency/Compatibility/WooCommerceUPS.php
  tests/unit/multi-currency/test-class-compatibility.php
Labels: pr: needs review

#3323 Fix currency format on order-pay page if currency was changed via switcher
  changelog.txt
  includes/multi-currency/FrontendCurrencies.php
  includes/payment-methods/class-upe-payment-gateway.php
  readme.txt
Labels: pr: needs review

#3287 Fix race conditions leading to duplicate order status transitions and invoice already paid errors
  changelog.txt
  includes/admin/class-wc-rest-payments-webhook-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/subscriptions/class-wc-payments-invoice-service.php
  includes/subscriptions/class-wc-payments-subscriptions-event-handler.php
  readme.txt
  tests/unit/admin/test-class-wc-rest-payments-webhook.php
  tests/unit/payment-methods/test-class-sepa-payment-gateway.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge

#3338 Update the subscription fee label in the transaction timeline.
  changelog.txt
  client/payment-details/timeline/map-events.js
  client/payment-details/timeline/test/__snapshots__/index.js.snap
  readme.txt
Labels: pr: ready to merge, component: WCPay Subscriptions

#3331 Fix UPE gateway remount
  changelog.txt
  client/checkout/classic/upe.js
  readme.txt
Labels: pr: ready to merge

#3288 Change payment method title for In Person Card Payment
  includes/admin/class-wc-rest-payments-orders-controller.php
  tests/unit/admin/test-class-wc-rest-payments-orders-controller.php
Labels: pr: ready to merge

#3276 Add compatibility between Multi-Currency and WooCommerce Pre-Orders.
  changelog.txt
  includes/multi-currency/Compatibility.php
  includes/multi-currency/Compatibility/WooCommercePreOrders.php
  readme.txt
  tests/unit/multi-currency/compatibility/test-class-woocommerce-pre-orders.php
Labels: pr: ready to merge

#3341 Validate product data and subscription price data before sending requests to server
  changelog.txt
  includes/subscriptions/class-wc-payments-product-service.php
  includes/subscriptions/class-wc-payments-subscription-service.php
  readme.txt
  tests/unit/subscriptions/test-class-wc-payments-product-service.php
  tests/unit/subscriptions/test-class-wc-payments-subscription-service.php
Labels: pr: ready to merge

#3319 Display UPE fields in checkout with less than 50 cents in the cart
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-utils.php
  includes/class-wc-payments.php
  includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php
  includes/exceptions/class-amount-too-small-exception.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  readme.txt
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-utils.php
Labels: pr: ready to merge

#2978 Unifying README.md files within E2E test suite
  tests/e2e/README.md
  tests/e2e/specs/README.md
Labels: pr: needs review, category: e2e

#3336 Display an admin notice when assets have not been built
  includes/class-wc-payments-dependency-service.php
  includes/class-wc-payments.php
  tests/unit/test-class-wc-payments-dependency-service.php
Labels: pr: ready to merge

#3295 Adds order notes for dispute events
  changelog.txt
  includes/admin/class-wc-rest-payments-webhook-controller.php
  tests/unit/admin/test-class-wc-rest-payments-webhook.php
Labels: pr: needs review

#3355 Update woocommerce-subscriptions-core to version 1.1.0
  changelog.txt
  composer.json
  composer.lock
  readme.txt
Labels: component: WCPay Subscriptions

#3282 Incorrect error message when card ZIP validation fails
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-utils.php
  readme.txt
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
Labels: pr: ready to merge

#3369 Move Analytics constructor outside of Multi Currency
  includes/multi-currency/MultiCurrency.php
Labels: pr: ready to merge

#3351 Bump WC tested up to attribute to 5.9
  .github/workflows/compatibility.yml
  .github/workflows/coverage.yml
  .github/workflows/e2e-test.yml
  woocommerce-payments.php
Labels: pr: ready to merge

#3303 Add idempotency key to post requests
  changelog.txt
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: needs review

#3260 Display specific error message instead of a generic one in the checkout block when payments fail
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  includes/payment-methods/class-upe-payment-gateway.php
  tests/e2e/specs/shopper/shopper-wc-blocks-checkout-failures.spec.js
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
Labels: pr: needs review

#3370 Revert "Remove ' in front of negative values on csv files"
  .eslintrc
  client/components/horizontal-list/index.js
  client/components/horizontal-list/style.scss
  client/components/horizontal-list/test/__snapshots__/index.js.snap
  client/connect-account-page/modal/index.js
  client/connect-account-page/modal/style.scss
  client/connect-account-page/modal/test/__snapshots__/index.js.snap
  client/deposits/list/test/__snapshots__/index.js.snap
  client/disputes/test/__snapshots__/index.js.snap
  client/payment-details/summary/test/__snapshots__/index.js.snap
  client/transactions/list/test/__snapshots__/index.tsx.snap
  package-lock.json
  package.json
Labels: pr: needs review

#3041 WooCommerce Deposits Multi Currency compatibility
  includes/multi-currency/Compatibility.php
  includes/multi-currency/Compatibility/WooCommerceDeposits.php
  tests/unit/helpers/class-wc-helper-deposit-product-manager.php
  tests/unit/multi-currency/compatibility/test-class-woocommerce-deposits.php
Labels: pr: ready to merge, component: customer multi-currency

#3357 Add `Requires PHP` and `Requires at least` to the main plugin file
  changelog.txt
  includes/class-wc-payments.php
  readme.txt
  woocommerce-payments.php
Labels: pr: ready to merge

#3344 Update `$this->id` prefixes for filters to use `MultiCurrency::FILTER_PREFIX`
  includes/multi-currency/MultiCurrency.php
  includes/multi-currency/StorefrontIntegration.php
Labels: pr: needs review

#3335 Fix flash of WooCommerce Payments gateway title name.
  changelog.txt
  includes/payment-methods/class-upe-payment-gateway.php
  readme.txt
  tests/unit/admin/test-class-wc-payments-admin.php
  tests/unit/admin/test-class-wc-rest-payments-webhook.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
Labels: pr: needs review

#3149 Display hardware costs in the transaction list and details page
  changelog.txt
  client/data/card-readers/action-types.js
  client/data/card-readers/actions.js
  client/data/card-readers/hooks.js
  client/data/card-readers/index.js
  client/data/card-readers/reducer.js
  client/data/card-readers/resolvers.js
  client/data/card-readers/selectors.js
  client/data/index.ts
  client/data/store.js
  client/data/transactions/hooks.ts
  client/payment-details/index.js
  client/payment-details/readers/index.js
  client/payment-details/readers/test/__snapshots__/index.js.snap
  client/payment-details/readers/test/index.js
  client/transactions/filters/config.ts
  client/transactions/list/index.tsx
  client/transactions/list/test/__snapshots__/index.tsx.snap
  client/transactions/strings.ts
  includes/admin/class-wc-rest-payments-reader-controller.php
  includes/class-wc-payments.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  readme.txt
  tests/unit/admin/test-class-wc-rest-payments-reader-charges-controller.php
  tests/unit/bootstrap.php
Labels: pr: ready to merge

#3115 Display red badge after 3 days
  changelog.txt
  includes/admin/class-wc-payments-admin.php
  tests/unit/admin/test-class-wc-payments-admin.php
Labels: pr: ready to merge

#3374 Allow UI Customizations on WCPay, UPE, & Other Checkout Payment Fields
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  includes/payment-methods/class-giropay-payment-gateway.php
  includes/payment-methods/class-sepa-payment-gateway.php
  includes/payment-methods/class-sofort-payment-gateway.php
  includes/payment-methods/class-upe-payment-gateway.php
  readme.txt
Labels: pr: ready to merge

#3349 Toggle terms for save payments in UPE block checkout
  client/checkout/blocks/upe-fields.js
  client/checkout/blocks/upe.js
Labels: pr: ready to merge

#3315 Fix the link to customers table
  changelog.txt
  client/transactions/list/index.tsx
  includes/wc-payment-api/class-wc-payments-api-client.php
  readme.txt
Labels: pr: ready to merge

#3395 Add change log header for 3.4.0
  changelog.txt
  readme.txt
Labels: pr: needs review

#3304 Update payment method selection UI and fee display
  client/additional-methods-setup/methods-selector/add-payment-methods-task.js
  client/additional-methods-setup/methods-selector/test/add-payment-methods-task.test.js
  client/additional-methods-setup/upe-preview-methods-selector/add-payment-methods-task.js
  client/additional-methods-setup/upe-preview-methods-selector/test/add-payment-methods-task.test.js
  client/components/currency-information-for-methods/index.js
  client/components/loadable-checkbox/index.js
  client/components/loadable-checkbox/style.scss
  client/components/loadable-checkbox/test/__snapshots__/index.test.js.snap
  client/components/loadable-checkbox/test/index.test.js
  client/components/payment-methods-checkboxes/payment-method-checkbox.js
  client/components/payment-methods-checkboxes/payment-method-checkbox.scss
  client/components/payment-methods-checkboxes/test/index.js
  client/components/payment-methods-list/delete-button.js
  client/components/payment-methods-list/payment-method.js
  client/components/payment-methods-list/payment-method.scss
  client/components/payment-methods-list/test/payment-method.js
  client/components/tooltip/index.js
  client/payment-methods/activation-modal.js
  client/payment-methods/activation-modal.scss
  client/payment-methods/delete-modal.js
  client/payment-methods/index.js
  client/payment-methods/style.scss
  client/payment-methods/test/__snapshots__/activation-modal.test.js.snap
  client/payment-methods/test/__snapshots__/delete-modal.test.js.snap
  client/payment-methods/test/activation-modal.test.js
  client/payment-methods/test/delete-modal.test.js
  client/payment-methods/test/index.js
  client/settings/payment-methods-selector/index.js
  client/settings/payment-methods-selector/style.scss
  client/settings/payment-methods-selector/test/index.js
  client/utils/account-fees.js
  client/utils/account-fees.scss
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-account.php
Labels: pr: needs review, component: upe

#3381 Fix incorrect amounts on payment request button for zero decimal currencies
  changelog.txt
  includes/class-wc-payments-payment-request-button-handler.php
  readme.txt
Labels: pr: needs review

#3400 Mention specific files for changelog entries
  .github/PULL_REQUEST_TEMPLATE.md
Labels: pr: ready to merge

#3340 Update Jetpack packages to latest versions
  composer.json
  composer.lock
  includes/wc-payment-api/class-wc-payments-http.php
Labels: pr: needs review

#3201 Update elligibility flag worflows
  includes/admin/class-wc-rest-payments-accounts-controller.php
  tests/unit/admin/test-class-wc-rest-payments-accounts-controller.php
Labels: pr: ready to merge

#3239 Fix display of multiple payment method fees
  client/components/account-status/account-fees/index.js
  client/components/account-status/account-fees/test/__snapshots__/index.js.snap
  client/components/account-status/account-fees/test/index.js
  client/components/account-status/index.js
  client/components/account-status/test/__snapshots__/index.js.snap
  client/components/account-status/test/index.js
  client/overview/index.js
  client/utils/account-fees.js
Labels: pr: ready to merge

#3391 Remove all references to Forter in the client
  changelog.txt
  client/fraud-scripts/forter.js
  client/fraud-scripts/index.js
  includes/admin/class-wc-rest-payments-fraud-controller.php
  includes/class-wc-payments-fraud-service.php
  includes/class-wc-payments.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  readme.txt
  tests/unit/test-class-wc-payments-fraud-service.php
Labels: pr: ready to merge

#3325 add wcpay_payment_request_is_product_supported filter
  changelog.txt
  includes/class-wc-payments-payment-request-button-handler.php
  readme.txt
Labels: pr: ready to merge

#3353 Update `@woocommerce/experimental` package to v2.1.0
  changelog.txt
  client/overview/task-list/index.js
  client/overview/task-list/tasks.js
  package-lock.json
  package.json
Labels: pr: needs review

#3314 Remove reference to subscriptions-base in phpunit.xml.dist.
  phpunit.xml.dist
Labels: pr: ready to merge, priority: low, size: small, component: wcpay subscriptions

#3414 WCPay Subscriptions empty state tweaks
  client/subscriptions-empty-state/index.js
  client/subscriptions-empty-state/style.scss
Labels: component: wcpay subscriptions

#3387 Fix Composite product-type check in `WC_Payments_Payment_Request_Button_Handler ::is_product_supported()`
  changelog.txt
  includes/class-wc-payments-payment-request-button-handler.php
  readme.txt
Labels: pr: ready to merge

#3409 Add internationalization to Credit Card payment method title for UPE
  includes/payment-methods/class-cc-payment-method.php
Labels: pr: ready to merge

#3332 Update E2E test config to improve performance
  tests/e2e/config/jest-puppeteer.config.js
  tests/e2e/setup/jest-setup.js
Labels: pr: needs review

#3403 Add WCPay Subscriptions empty state screens
  assets/images/subscriptions-empty-state-connected.svg
  assets/images/subscriptions-empty-state-unconnected.svg
  changelog.txt
  client/subscriptions-empty-state/index.js
  client/subscriptions-empty-state/style.scss
  includes/class-wc-payments-account.php
  includes/class-wc-payments.php
  includes/subscriptions/class-wc-payments-subscriptions-empty-state-manager.php
  includes/subscriptions/class-wc-payments-subscriptions.php
  psalm-baseline.xml
  readme.txt
  webpack.config.js
Labels: pr: ready to merge, component: wcpay subscriptions

#3416 Add admin link generator utility
  client/components/customer-link/index.js
  client/components/details-link/index.js
  client/data/deposits/actions.js
  client/data/disputes/actions.js
  client/disputes/details/actions.js
  client/disputes/evidence/index.js
  client/overview/task-list/tasks.js
  client/payment-details/timeline/map-events.js
  client/payment-methods/index.js
  client/transactions/list/deposit.tsx
  client/utils/index.js
Labels: pr: needs review, category: refactor

#3343 Migrate Node SASS to Dart SASS
  client/stylesheets/abstracts/_mixins.scss
  package-lock.json
  package.json
Labels: pr: ready to merge

#3424 Minor tweak to logic, and add tests for init_order_currency.
  includes/multi-currency/FrontendCurrencies.php
  tests/unit/multi-currency/test-class-frontend-currencies.php
Labels: pr: needs review

#3423 Fix fatal error on thank you page
  changelog.txt
  includes/multi-currency/FrontendCurrencies.php
  readme.txt
  tests/unit/multi-currency/test-class-frontend-currencies.php
Labels: pr: ready to merge

#3428 Fix payment intent having unsupported payment methods
  includes/class-wc-payment-gateway-wcpay.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: ready to merge

#3079 Enforce maximum dispute evidence text length
  changelog.txt
  client/disputes/evidence/fields.js
  client/disputes/evidence/index.js
  client/disputes/evidence/test/index.js
  readme.txt
Labels: pr: ready to merge

#3383 Replace E2E Server docker instance with live
  .github/workflows/e2e-test.yml
  tests/e2e/README.md
  tests/e2e/env/down.sh
  tests/e2e/env/setup.sh
  tests/e2e/env/up.sh
Labels: pr: needs review, category: engineering, category: e2e, category: devops

#3418 Add Download CSV button to Disputes
  changelog.txt
  client/deposits/list/test/index.js
  client/disputes/index.js
  client/disputes/test/__snapshots__/index.js.snap
  client/disputes/test/index.js
  client/utils/test-utils.js
Labels: pr: ready to merge

#3134 Remove the 'add new payment methods' item from the tasks list
  changelog.txt
  client/additional-methods-setup/index.js
  client/additional-methods-setup/task.js
  client/additional-methods-setup/test/index.js
  client/additional-methods-setup/test/task.test.js
  client/index.js
  client/overview/index.js
  client/overview/task-list/tasks.js
  client/overview/task-list/test/tasks.js
  client/payment-methods/index.js
  client/payment-methods/test/index.js
  includes/admin/class-wc-payments-admin.php
  includes/notes/class-wc-payments-notes-additional-payment-methods.php
Labels: pr: needs review

#3437 Add tracking events to the subscriptions empty state
  client/subscriptions-empty-state/index.js
  client/tracks/index.js
Labels: pr: ready to merge, component: wcpay subscriptions, category: projects

#3421 Set newly created subscriptions to draft if onboarding is not complete.
  changelog.txt
  includes/subscriptions/class-wc-payments-subscriptions-onboarding-handler.php
  includes/subscriptions/class-wc-payments-subscriptions.php
  psalm-baseline.xml
  readme.txt
  tests/unit/admin/test-class-wc-rest-payments-accounts-controller.php
Labels: pr: ready to merge

#3211 Add merchant branding settings to the Settings API
  changelog.txt
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  readme.txt
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
Labels: pr: needs review
