Repository Automattic/woocommerce-payments, pull requests merged in 2021-08, with the labels that each got.

#2387 Fix handling of null response in ExPlat client
  includes/class-experimental-abtest.php
Labels: pr: needs review

#2555 Show empty state treatment only when WCPay not connected
  client/deposits/index.js
  client/empty-state-table/list.js
  client/globals.d.ts
  client/transactions/index.tsx
  includes/admin/class-wc-payments-admin.php
Labels: pr: ready to merge

#2632 Update Escaping for A/B Test Cookie
  changelog.txt
  includes/admin/class-wc-payments-admin.php
  readme.txt
Labels: pr: ready to merge

#2634 Fix explat not caching when no variation is returned
  changelog.txt
  includes/class-experimental-abtest.php
  readme.txt
Labels: pr: ready to merge

#2615 Use the Stripe Exchange Rate in Analytics
  includes/multi-currency/Analytics.php
  includes/multi-currency/MultiCurrency.php
  tests/unit/multi-currency/test-class-analytics.php
  tests/unit/multi-currency/test-class-multi-currency.php
Labels: component: customer multi-currency, pr: ready to merge

#2637 Display Storefront Widget option when settings loaded with 1 currency
  includes/multi-currency/MultiCurrency.php
  includes/multi-currency/StorefrontIntegration.php
  tests/unit/multi-currency/test-class-storefront-integration.php
Labels: component: customer multi-currency, pr: needs review

#2597 Hook into the Best Sales Day Notification to convert order totals
  includes/multi-currency/Compatibility.php
  tests/unit/multi-currency/test-class-compatibility.php
  tests/unit/multi-currency/test-class-multi-currency.php
Labels: pr: needs review

#2633 Change check to enable subscriptions column
  includes/admin/class-wc-payments-admin.php
  tests/e2e/specs/merchant/merchant-admin-transactions.spec.js
Labels: component: transactions, pr: needs review

#2644 CI: move coverage collection to separe flow, so other flows running fast
  .github/workflows/compatibility.yml
  .github/workflows/coverage.yml
  .github/workflows/e2e-test.yml
  .github/workflows/js-lint-test.yml
  .github/workflows/php-lint-test.yml
Labels: pr: needs review

#2655 Add changelog entry headers for 2.9.0
  changelog.txt
  readme.txt
Labels: pr: ready to merge

#2606 Update license to GPLv3 or later
  license.txt
  package.json
  readme.txt
Labels: pr: needs author reply

#2661 Initial fix for disabling Multi-Currency if there is not a connected account
  changelog.txt
  client/multi-currency/index.js
  includes/multi-currency/MultiCurrency.php
  includes/multi-currency/Settings.php
  readme.txt
  tests/unit/multi-currency/test-class-settings.php
Labels: component: customer multi-currency, pr: ready to merge

#2662 Prep 2.8.1 Release
  changelog.txt
  client/multi-currency/index.js
  includes/multi-currency/MultiCurrency.php
  includes/multi-currency/Settings.php
  readme.txt
  tests/unit/multi-currency/test-class-settings.php
Labels: pr: needs review

#2663 feat: maybe go to connect page when onboarding
  changelog.txt
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments.php
  includes/notes/class-wc-payments-notes-additional-payment-methods.php
  readme.txt
  tests/unit/admin/test-class-wc-payments-admin.php
  tests/unit/notes/test-class-wc-payments-notes-additional-payment-methods.php
Labels: pr: needs review, component: grouped-settings

#2679 Adding changelog entries for 2.9.0
  changelog.txt
  readme.txt
Labels: pr: ready to merge

#2646 In-person payments: return non-empty account structures only
  includes/admin/class-wc-rest-payments-accounts-controller.php
  tests/unit/admin/test-class-wc-rest-payments-accounts-controller.php
  tests/unit/bootstrap.php
Labels: pr: ready to merge

#2670 Remove duplicate symbols from currency switcher widget
  includes/multi-currency/CurrencySwitcherWidget.php
  tests/unit/multi-currency/test-class-currency-switcher-widget.php
Labels: type: bug, pr: needs review, component: customer multi-currency

#2660 Customizable frontend currencies
  includes/multi-currency/FrontendCurrencies.php
  tests/unit/multi-currency/test-class-frontend-currencies.php
Labels: type: bug, pr: ready to merge, component: customer multi-currency

#2673 Remove explicit prices where a single currency is active
  includes/class-wc-payments-explicit-price-formatter.php
  includes/multi-currency/MultiCurrency.php
  tests/unit/test-class-wc-payments-explicit-price-formatter.php
Labels: type: bug, pr: ready to merge, component: customer multi-currency

#2689 In-person payments: account endpoint now provides test_mode property
  includes/admin/class-wc-rest-payments-accounts-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  tests/unit/admin/test-class-wc-rest-payments-accounts-controller.php
Labels: pr: in progress

#2668 Improve explicit currency code check
  includes/class-wc-payments-explicit-price-formatter.php
  tests/unit/test-class-wc-payments-explicit-price-formatter.php
Labels: type: bug, pr: needs review, component: customer multi-currency

#2681 Add iDEAL payment method to UPE
  assets/css/admin.css
  assets/images/payment-methods/ideal.svg
  changelog.txt
  client/additional-methods-setup/methods-selector/add-payment-methods-task.js
  client/additional-methods-setup/upe-preview-methods-selector/add-payment-methods-task.js
  client/additional-methods-setup/upe-preview-methods-selector/test/add-payment-methods-task.test.js
  client/additional-methods-setup/upe-preview-methods-selector/test/setup-complete-task.test.js
  client/components/currency-information-for-methods/index.js
  client/components/currency-information-for-methods/test/index.test.js
  client/components/payment-method-details/index.js
  client/components/payment-methods-checkboxes/test/index.js
  client/gateway-icons/ideal.js
  client/payment-details/payment-method/ideal/index.js
  client/payment-details/payment-method/index.js
  client/payment-methods-map.js
  client/payment-methods/test/index.js
  client/settings/payment-method-icon/test/index.js
  client/settings/payment-methods-selector/test/index.js
  includes/class-wc-payments.php
  includes/multi-currency/PaymentMethodsCompatibility.php
  includes/payment-methods/class-ideal-payment-method.php
  includes/payment-methods/class-upe-payment-gateway.php
  readme.txt
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
Labels: pr: ready to merge, component: UPE

#2684 Add - split discount line into variable and fixed fee
  changelog.txt
  client/payment-details/timeline/map-events.js
  client/payment-details/timeline/style.scss
  client/payment-details/timeline/test/__snapshots__/map-events.js.snap
  readme.txt
Labels: pr: ready to merge

#2589 Fix: align table items in screens: Deposits, Transactions, and Disputes
  changelog.txt
  client/deposits/list/index.js
  client/deposits/list/style.scss
  client/deposits/list/test/__snapshots__/index.js.snap
  client/disputes/index.js
  client/disputes/style.scss
  client/disputes/test/__snapshots__/index.js.snap
  client/transactions/list/index.tsx
  client/transactions/list/style.scss
  client/transactions/list/test/__snapshots__/index.tsx.snap
  readme.txt
Labels: pr: ready to merge

#2518 Add new E2E test Shopper / Subscriptions / Manage Payment Methods
  tests/e2e/config/test.json
  tests/e2e/specs/merchant/merchant-orders-full-refund.spec.js
  tests/e2e/specs/shopper/shopper-subscriptions-manage-payments.spec.js
Labels: pr: ready to merge, category: E2E

#2392 Add/e2e add delete payment methods
  tests/e2e/config/test.json
  tests/e2e/specs/shopper/shopper-myaccount-payment-methods-add-delete-success.spec.js
  tests/e2e/specs/shopper/shopper-myaccount-payment-methods-add-fail.spec.js
  tests/e2e/specs/shopper/shopper-myaccount-save-card-and-checkout.spec.js
  tests/e2e/utils/flows.js
  tests/e2e/utils/payments.js
Labels: pr: ready to merge, category: E2E

#2534 Add e2e test for 'Merchant / Order / Refund failure' critical flow
  tests/e2e/specs/merchant/merchant-orders-refund-failures.spec.js
Labels: pr: ready to merge, category: E2E

#2624 Add/e2e shopper subscriptions free trial
  tests/e2e/config/test.json
  tests/e2e/specs/shopper/shopper-subscriptions-free-trial.spec.js
  tests/e2e/utils/flows.js
Labels: pr: ready to merge, category: E2E

#2705 Show the estimated deposit date in the transactions CSV export rather than the deposit ID
  changelog.txt
  client/transactions/list/index.tsx
  client/transactions/list/test/__snapshots__/index.tsx.snap
  client/transactions/list/test/index.tsx
  readme.txt
Labels: pr: ready to merge

#2336 Add new E2E test Shopper / Checkout / Checkout failures (with various cards)
  tests/e2e/config/test.json
  tests/e2e/specs/shopper/shopper-checkout-failures.spec.js
Labels: pr: ready to merge, category: E2E

#2721 Make iDEAL icon to look like the other payment methods
  assets/images/payment-methods/ideal.svg
  client/gateway-icons/ideal.js
Labels: pr: needs review

#2711 Fix fatal issue if enabled currencies db option is set as string.
  changelog.txt
  includes/multi-currency/MultiCurrency.php
  readme.txt
  tests/unit/multi-currency/test-class-multi-currency.php
Labels: pr: needs review, component: customer multi-currency

#2652 Add P24 as an UPE payment method
  assets/css/admin.css
  assets/images/payment-methods/przelewy24.svg
  changelog.txt
  client/additional-methods-setup/methods-selector/add-payment-methods-task.js
  client/additional-methods-setup/upe-preview-methods-selector/add-payment-methods-task.js
  client/additional-methods-setup/upe-preview-methods-selector/test/add-payment-methods-task.test.js
  client/additional-methods-setup/upe-preview-methods-selector/test/setup-complete-task.test.js
  client/additional-methods-setup/wizard/collapsible-body.scss
  client/components/currency-information-for-methods/index.js
  client/components/currency-information-for-methods/test/index.test.js
  client/components/payment-method-details/index.js
  client/components/payment-methods-checkboxes/test/index.js
  client/gateway-icons/p24.js
  client/payment-details/payment-method/index.js
  client/payment-details/payment-method/p24/bank-list.js
  client/payment-details/payment-method/p24/index.js
  client/payment-methods-map.js
  client/payment-methods/test/index.js
  client/settings/payment-method-icon/test/index.js
  client/settings/payment-methods-selector/test/index.js
  includes/class-wc-payments.php
  includes/migrations/class-update-service-data-from-server.php
  includes/multi-currency/PaymentMethodsCompatibility.php
  includes/payment-methods/class-p24-payment-method.php
  includes/payment-methods/class-upe-payment-gateway.php
  readme.txt
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
Labels: pr: needs review, component: UPE

#2532 refactor: move account overview task list to feature class
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-features.php
Labels: pr: needs review, needs feedback

#2614 Add filter to force decimal points in refund form
  includes/multi-currency/MultiCurrency.php
Labels: type: bug, pr: needs review, component: customer multi-currency

#2706 Load subscriptions base and update `is_subscriptions_enabled()` to check for either subscription version
  .stylelintignore
  includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php
  includes/compat/subscriptions/trait-wc-payments-subscriptions-utilities.php
  phpcs.xml.dist
  phpunit.xml.dist
  psalm-baseline.xml
  psalm.xml
  tests/unit/bootstrap.php
  woocommerce-payments.php
Labels: pr: ready to merge, component: stripe billing

#2717 Save the generated customer id using session cookie for non logged in users
  changelog.txt
  includes/class-wc-payments-customer-service.php
  readme.txt
  tests/unit/test-class-wc-payments-customer-service.php
Labels: pr: needs review

#2719 Update Forter JS implementation
  client/fraud-scripts/forter.js
  includes/admin/class-wc-rest-payments-fraud-controller.php
  includes/class-wc-payments-fraud-service.php
  includes/class-wc-payments.php
  tests/unit/test-class-wc-payments-fraud-service.php
Labels: pr: needs review

#2709 Pin development PHP dependencies to specific versions
  composer.json
  composer.lock
Labels: pr: ready to merge

#2519 E2E Test for Partial Refunds
  tests/e2e/specs/merchant/merchant-orders-partial-refund.spec.js
  tests/e2e/utils/payments.js
Labels: pr: ready to merge, category: E2E

#2733 Remove connected email from account overview page
  client/components/account-status/index.js
Labels: pr: ready to merge

#2669 Adds subscription product service
  includes/class-wc-payments.php
  includes/subscriptions/class-wc-payments-product-service.php
  includes/subscriptions/class-wc-payments-subscriptions.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  psalm-baseline.xml
  tests/unit/helpers/class-wc-helper-subscriptions-product.php
  tests/unit/subscriptions/test-class-wc-payments-product-service.php
Labels: pr: needs review, component: stripe billing

#2737 Add price hash to only update relevant prod data
  includes/subscriptions/class-wc-payments-product-service.php
Labels: component: stripe billing

#2650 Add Bancontact as an UPE payment method
  assets/css/admin.css
  assets/images/payment-methods/bancontact.svg
  changelog.txt
  client/additional-methods-setup/methods-selector/add-payment-methods-task.js
  client/additional-methods-setup/methods-selector/test/add-payment-methods-task.test.js
  client/additional-methods-setup/upe-preview-methods-selector/add-payment-methods-task.js
  client/additional-methods-setup/upe-preview-methods-selector/test/add-payment-methods-task.test.js
  client/additional-methods-setup/upe-preview-methods-selector/test/setup-complete-task.test.js
  client/components/currency-information-for-methods/index.js
  client/components/currency-information-for-methods/test/index.test.js
  client/components/payment-method-details/index.js
  client/components/payment-methods-checkboxes/test/index.js
  client/gateway-icons/bancontact.js
  client/payment-details/payment-method/bancontact/index.js
  client/payment-details/payment-method/index.js
  client/payment-methods-map.js
  client/payment-methods/test/index.js
  client/settings/payment-method-icon/test/index.js
  client/settings/payment-methods-selector/test/index.js
  includes/class-wc-payments.php
  includes/multi-currency/PaymentMethodsCompatibility.php
  includes/payment-methods/class-bancontact-payment-method.php
  includes/payment-methods/class-upe-payment-gateway.php
  readme.txt
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
  tests/unit/multi-currency/test-class-payment-methods-compatibility.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
Labels: pr: needs review, component: UPE

#2725 Fix phrasing UPE missing currencies notice text
  client/components/currency-information-for-methods/index.js
Labels: pr: needs review, component: UPE

#2738 Add subscriptions webhook event handler stubs
  includes/admin/class-wc-rest-payments-webhook-controller.php
  tests/unit/admin/test-class-wc-rest-payments-webhook.php
Labels: component: stripe billing

#2736 Added a task to the PR template to add instructions to the release testing doc
  .github/PULL_REQUEST_TEMPLATE.md
Labels: pr: ready to merge

#2741 Update subscription variations on variable product name changes
  includes/subscriptions/class-wc-payments-product-service.php
Labels: pr: needs review, component: stripe billing

#2610 Fire a new action when payment request is ready
  changelog.txt
  client/payment-request/index.js
  package-lock.json
  package.json
Labels: pr: ready to merge

#2754 Remove an extra period in changelog and add a missing changelog line to readme.
  changelog.txt
  readme.txt
Labels: pr: ready to merge

#2626 Validate order's status for create customer API.
  changelog.txt
  includes/admin/class-wc-rest-payments-orders-controller.php
  readme.txt
  tests/unit/admin/test-class-wc-rest-payments-orders-controller.php
Labels: pr: ready to merge, [Feature] Card Present

#2770 Disable Bancontact, iDEAL, and P24 as UPE payment methods.
  changelog.txt
  includes/payment-methods/class-upe-payment-gateway.php
  readme.txt
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
Labels: pr: needs review

#2759 Bump the version of ExPlat package to 1.1.1
  package-lock.json
  package.json
Labels: pr: ready to merge

#2771 Revert "Bump the version of ExPlat package to 1.1.1"
  package-lock.json
  package.json
Labels: pr: ready to merge

#2772 Bump Preview Mode Experiment Version to v4
  client/deposits/index.js
  client/transactions/index.tsx
  includes/admin/class-wc-payments-admin.php
Labels: pr: needs review

#2557 Only add deposits and transactions for the treatment group of Empty State Preview experiment
  assets/css/admin.css
  includes/admin/class-wc-payments-admin.php
Labels: pr: ready to merge

#2758 Adds subscription invoice service
  includes/subscriptions/class-wc-payments-invoice-service.php
  includes/subscriptions/class-wc-payments-subscriptions.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  psalm-baseline.xml
  tests/unit/helpers/class-wc-helper-subscription.php
  tests/unit/subscriptions/test-class-wc-payments-invoice-service.php
Labels: pr: needs review, component: stripe billing

#2777 Bump Supported Versions for 2.9 Release
  changelog.txt
  readme.txt
  woocommerce-payments.php
Labels: pr: ready to merge

#2774 Adds the WCPay subscriptions service class
  includes/class-wc-payments-customer-service.php
  includes/class-wc-payments.php
  includes/subscriptions/class-wc-payments-invoice-service.php
  includes/subscriptions/class-wc-payments-product-service.php
  includes/subscriptions/class-wc-payments-subscription-service.php
  includes/subscriptions/class-wc-payments-subscriptions.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  psalm-baseline.xml
  tests/unit/helpers/class-wc-helper-subscription.php
  tests/unit/helpers/class-wc-helper-subscriptions-product.php
  tests/unit/helpers/class-wc-helper-subscriptions-synchroniser.php
  tests/unit/subscriptions/test-class-wc-payments-invoice-service.php
  tests/unit/subscriptions/test-class-wc-payments-product-service.php
  tests/unit/subscriptions/test-class-wc-payments-subscription-service.php
  tests/unit/test-class-wc-payments-customer-service.php
Labels: component: stripe billing

#2381 Add new E2E test Merchant / Onboarding / Setup & Task List
  tests/e2e/config/jest-custom-sequencer.js
  tests/e2e/config/jest.config.js
  tests/e2e/config/test.json
  tests/e2e/specs/merchant/merchant-a-onboarding-setup.spec.js
  tests/e2e/specs/merchant/merchant-a-onboarding-task-list.spec.js
Labels: pr: ready to merge, category: E2E

#2781 Add GitHub issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature.md
Labels: pr: ready to merge

#2789 Fix payment method checkbox mobile view
  client/additional-methods-setup/upe-preview-methods-selector/index.scss
  client/components/confirmation-modal/styles.scss
  client/components/payment-methods-checkboxes/payment-method-checkbox.scss
Labels: pr: needs review

#2801 gitignore docker compose override file
  .gitignore
Labels: pr: ready to merge

#2778 Add button to download deposits as CSV
  changelog.txt
  client/deposits/list/index.js
  client/deposits/list/test/__snapshots__/index.js.snap
  client/deposits/list/test/index.js
  readme.txt
Labels: pr: ready to merge

#2809 unit tests - remove add_token_to_order mock
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-process-payment.php
Labels: pr: ready to merge
