Repository Automattic/woocommerce-payments, pull requests merged in 2021-12, with the labels that each got.

#2014 Add onboarding payment gateway setup methods
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  readme.txt
Labels: pr: ready to merge

#3429 Modal is displayed when publishing subscription products before onboarding
  assets/images/subscriptions-onboarding-modal.svg
  client/subscription-product-onboarding/modal.js
  client/subscription-product-onboarding/style.scss
  client/subscription-product-onboarding/toast.js
  includes/class-wc-payments-account.php
  includes/subscriptions/class-wc-payments-subscriptions-onboarding-handler.php
  package-lock.json
  package.json
  webpack.config.js
Labels: component: wcpay subscriptions

#3330 Add PHP compatibility checks to PRs
  .github/workflows/php-compatibility.yml
  .gitignore
  bin/phpcs-compat.sh
  phpcs-compat.xml.dist
  phpcs.xml.dist
Labels: pr: ready to merge

#3452 Add test to confirm `payment_complete` is triggered when `attach_intent_info_to_order` is successful
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge

#3462 Use the project's pinned Node.js version for JS linting and tests
  .github/workflows/js-lint-test.yml
Labels: category: devops

#3449 Tracks for subscriptions product creation flow when not connected to Stripe yet.
  client/subscription-product-onboarding/modal.js
  client/tracks/index.js
  includes/subscriptions/class-wc-payments-subscriptions-onboarding-handler.php
Labels: pr: ready to merge

#3342 Add order metadata to intent before IPP capture
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  includes/wc-payment-api/models/class-wc-payments-api-intention.php
  readme.txt
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge

#3371 Compatibility with Payment Gateway Based Fees during checkout
  includes/class-wc-payments-payment-request-button-handler.php
Labels: pr: needs review

#2939 Initiate transactions export in server via download button
  changelog.txt
  client/data/transactions/resolvers.js
  client/transactions/list/index.tsx
  client/transactions/list/test/index.tsx
  includes/admin/class-wc-rest-payments-transactions-controller.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: ready to merge

#3433 IPP Styled Receipts: Print receipt
  changelog.txt
  includes/admin/class-wc-rest-payments-reader-controller.php
  includes/class-wc-payments.php
  includes/in-person-payments/class-wc-payments-in-person-payments-receipts-service.php
  includes/in-person-payments/templates/html-in-person-payment-receipt.php
  psalm-baseline.xml
  readme.txt
  tests/unit/admin/test-class-wc-rest-payments-reader-charges-controller.php
  tests/unit/in-person-payments/test-class-wc-payments-in-person-payments-receipts-service.php
Labels: pr: needs author reply

#3444 Make sure the WC session is initialized before checking what currency should the user see.
  changelog.txt
  includes/multi-currency/MultiCurrency.php
  readme.txt
Labels: pr: needs review, component: customer multi-currency

#1591 Fix - Jurassic Tube Setup Script Directory Creation
  bin/jurassic-tube-setup.sh
Labels: pr: ready to merge, category: engineering

#3464 Use the project's pinned Node.js version for e2e workflows
  .github/workflows/e2e-test.yml
Labels: pr: ready to merge, category: engineering, category: e2e, category: devops

#3410 IPP Styled Receipts: Merchant brand settings (front-end)
  changelog.txt
  client/card-readers/index.js
  client/card-readers/list/index.js
  client/card-readers/list/list-item.js
  client/card-readers/list/test/index.test.js
  client/card-readers/settings/file-upload.js
  client/card-readers/settings/index.js
  client/card-readers/settings/sections/address-details.js
  client/card-readers/settings/sections/branding-details.js
  client/card-readers/settings/sections/business-details.js
  client/card-readers/settings/sections/contacts-details.js
  client/card-readers/settings/sections/test/index.test.js
  client/card-readers/settings/test/__snapshots__/index.test.js.snap
  client/card-readers/settings/test/index.test.js
  client/card-readers/style.scss
  client/card-readers/test/index.test.js
  client/data/card-readers/action-types.js
  client/data/card-readers/actions.js
  client/data/card-readers/hooks.js
  client/data/card-readers/reducer.js
  client/data/card-readers/resolvers.js
  client/data/card-readers/selectors.js
  client/data/settings/actions.js
  client/data/settings/hooks.js
  client/data/settings/selectors.js
  client/data/settings/test/reducer.js
  client/data/settings/test/selectors.js
  client/index.js
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-reader-controller.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  readme.txt
  tests/unit/admin/test-class-wc-rest-payments-reader-charges-controller.php
Labels: pr: ready to merge

#3474 HACK week: code base tweaks (housekeeping)
  includes/admin/class-wc-rest-payments-charges-controller.php
  includes/admin/class-wc-rest-payments-timeline-controller.php
  includes/class-experimental-abtest.php
  includes/class-session-rate-limiter.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-apple-pay-registration.php
  includes/class-wc-payments-explicit-price-formatter.php
  includes/class-wc-payments-payment-request-button-handler.php
  includes/class-wc-payments-token-service.php
  includes/class-wc-payments-utils.php
  includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php
  includes/constants/class-payment-method.php
  includes/constants/class-payment-type.php
  includes/in-person-payments/class-wc-payments-in-person-payments-receipts-service.php
  includes/multi-currency/Analytics.php
  includes/multi-currency/BackendCurrencies.php
  includes/multi-currency/Compatibility/WooCommerceDeposits.php
  includes/multi-currency/CurrencySwitcherBlock.php
  includes/multi-currency/FrontendPrices.php
  includes/multi-currency/Geolocation.php
  includes/multi-currency/MultiCurrency.php
  includes/multi-currency/RestController.php
  includes/multi-currency/StorefrontIntegration.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/subscriptions/class-wc-payments-invoice-service.php
  includes/subscriptions/class-wc-payments-product-service.php
  includes/subscriptions/class-wc-payments-subscription-service.php
Labels: pr: needs review, pr: ready to merge

#3480 Fix Card readers page checks causing account cached data missing
  includes/admin/class-wc-payments-admin.php
Labels: pr: needs review

#3479 HACK week: run WCPay tests on PHP 8.1
  .github/workflows/compatibility.yml
  bin/install-wp-tests.sh
  bin/run-ci-tests-check-coverage.bash
  composer.json
  composer.lock
  tests/phpunit-patches/globals-usage-compatibility.diff
  tests/unit/bootstrap.php
Labels: pr: ready to merge

#3484 HACK week: Psalm level 6
  composer.json
  composer.lock
  includes/admin/class-wc-rest-payments-reader-controller.php
  includes/admin/class-wc-rest-payments-terminal-locations-controller.php
  includes/admin/class-wc-rest-payments-webhook-controller.php
  includes/class-experimental-abtest.php
  includes/class-payment-information.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-action-scheduler-service.php
  includes/class-wc-payments-blocks-payment-method.php
  includes/class-wc-payments-customer-service.php
  includes/class-wc-payments-db.php
  includes/class-wc-payments-payment-request-button-handler.php
  includes/class-wc-payments-token-service.php
  includes/class-wc-payments-translations-loader.php
  includes/class-wc-payments-utils.php
  includes/class-wc-payments.php
  includes/compat/subscriptions/class-wc-payments-email-failed-renewal-authentication.php
  includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php
  includes/exceptions/class-amount-too-small-exception.php
  includes/multi-currency/Compatibility/WooCommerceBookings.php
  includes/multi-currency/Compatibility/WooCommerceDeposits.php
  includes/multi-currency/Compatibility/WooCommerceProductAddOns.php
  includes/multi-currency/Currency.php
  includes/multi-currency/CurrencySwitcherBlock.php
  includes/multi-currency/FrontendCurrencies.php
  includes/multi-currency/MultiCurrency.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/subscriptions/class-wc-payments-product-service.php
  includes/subscriptions/class-wc-payments-subscription-service.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  includes/wc-payment-api/class-wc-payments-http-interface.php
  includes/wc-payment-api/class-wc-payments-http.php
  psalm-baseline.xml
  psalm-loader.php
  psalm.xml
Labels: pr: ready to merge

#3481 Add platform checkout prototype
  client/checkout/api/index.js
  client/checkout/api/test/index.test.js
  client/checkout/blocks/index.js
  client/checkout/blocks/test/index.test.js
  client/checkout/blocks/test/upe.test.js
  client/checkout/blocks/upe.js
  client/components/platform-checkout/index.tsx
  client/components/platform-checkout/test/index.test.js
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-features.php
  includes/class-wc-payments.php
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
  tests/unit/helpers/class-wc-blocks-rest-api-registration-preventer.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-features.php
  tests/unit/test-class-wc-payments.php
Labels: type: enhancement, pr: needs review, category: projects

#3487 Always save subscriptions payment methods when using UPE
  changelog.txt
  includes/payment-methods/class-upe-payment-gateway.php
  readme.txt
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
Labels: pr: ready to merge

#3492 HACK week: bumped Psalm level to 5
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-customer-service.php
  includes/class-wc-payments-payment-request-button-handler.php
  includes/multi-currency/MultiCurrency.php
  includes/multi-currency/SettingsOnboardCta.php
  includes/notes/class-wc-payments-notes-set-https-for-checkout.php
  psalm-loader.php
  psalm.xml
Labels: pr: ready to merge

#3465 Add an endpoint to create a terminal intent
  includes/admin/class-wc-rest-payments-orders-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/constants/class-payment-method.php
  tests/unit/admin/test-class-wc-rest-payments-orders-controller.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge, component: card present

#3499 HACK week: migrate empty state table component to TS
  client/empty-state-table/index.tsx
  client/empty-state-table/list.tsx
  client/empty-state-table/test/__snapshots__/index.tsx.snap
  client/empty-state-table/test/index.tsx
  client/globals.d.ts
  package-lock.json
  package.json
Labels: pr: ready to merge

#3501 HACK week: TypeScript migration: client/disputes/evidence
  client/disputes/evidence/file-upload.tsx
  client/disputes/evidence/test/__snapshots__/file-upload.tsx.snap
  client/disputes/evidence/test/file-upload.tsx
  client/types/disputes.d.ts
Labels: pr: ready to merge

#3491 [WIP] Hackweek move disputes info component to TypeScript
  client/data/disputes/hooks.ts
  client/disputes/info/index.tsx
  client/disputes/info/test/__snapshots__/index.tsx.snap
  client/disputes/info/test/index.tsx
  client/disputes/strings.ts
  package-lock.json
Labels: pr: needs review

#3498 TypeScript migration: client/utils/charge
  client/types/balance-transactions.d.ts
  client/types/charges.d.ts
  client/types/disputes.d.ts
  client/utils/charge/index.ts
Labels: pr: needs review

#3034 Add JS error boundaries
  changelog.txt
  client/components/error-boundary/index.js
  client/components/page/index.tsx
  client/deposits/details/index.js
  client/disputes/details/index.js
  client/disputes/evidence/index.js
  client/overview/index.js
  client/payment-details/index.js
  client/settings/advanced-settings/index.js
  client/settings/index.js
  client/settings/payment-method-settings/index.js
  client/settings/settings-manager/index.js
Labels: pr: ready to merge

#3505 Update Github workflows to use node version in .nvmrc
  .github/workflows/i18n-weekly-release.yml
  .github/workflows/pre-release-publish-on-tag.yaml
Labels: category: engineering, category: devops

#3494 Add platform checkout iframe and listen to "redirect" JS message
  client/checkout/blocks/style.scss
  client/components/platform-checkout/index.tsx
  includes/class-wc-payments-blocks-payment-method.php
Labels: type: enhancement, pr: needs review, category: projects

#3466 Continue optimization work for Frontend Currencies.
  includes/multi-currency/Compatibility.php
  includes/multi-currency/FrontendCurrencies.php
  includes/multi-currency/MultiCurrency.php
  includes/multi-currency/Utils.php
  tests/unit/multi-currency/test-class-compatibility.php
  tests/unit/multi-currency/test-class-frontend-currencies.php
  tests/unit/multi-currency/test-class-utils.php
Labels: pr: ready to merge, component: customer multi-currency

#3439 Aligned CodeSniffer doc block related configs on Client
  phpcs.xml.dist
Labels: pr: ready to merge

#3511 Use WC Admin package for merchant onboarding tests, fix merchant E2E tests
  .gitignore
  package-lock.json
  package.json
  tests/e2e/config/test.json
  tests/e2e/setup/jest-setup.js
  tests/e2e/specs/merchant/merchant-a-onboarding-setup.spec.js
  tests/e2e/specs/merchant/merchant-a-onboarding-task-list.spec.js
  tests/e2e/specs/merchant/merchant-orders-full-refund.spec.js
  tests/e2e/specs/merchant/merchant-orders-manual-capture.spec.js
  tests/e2e/specs/merchant/merchant-orders-partial-refund.spec.js
Labels: pr: ready to merge

#3277 Fix e2e tests related to the WooCommerce blocks' checkout
  tests/e2e/config/jest-puppeteer.config.js
  tests/e2e/specs/shopper/shopper-wc-blocks-checkout-failures.spec.js
  tests/e2e/specs/shopper/shopper-wc-blocks-checkout-purchase.spec.js
Labels: pr: ready to merge

#3500 HACK week: Migration of client/utils/account-fees to TS
  client/globals.d.ts
  client/types/fees.d.ts
  client/types/payment-methods.d.ts
  client/utils/account-fees.tsx
  client/utils/test/account-fees.tsx
Labels: pr: ready to merge

#3528 Do not override WCA Inbox note CSS
  client/overview/style.scss
Labels: pr: ready to merge

#3486 Add a reference to the transpiled JS file in POT file comments
  bin/combine-pot-files.php
  tasks/release.js
  webpack.config.js
Labels: pr: ready to merge

#3531 Rename payment identifier parameter in generate_print_receipt of \WC_REST_Payments_Reader_Controller
  includes/admin/class-wc-rest-payments-reader-controller.php
  tests/unit/admin/test-class-wc-rest-payments-reader-charges-controller.php
Labels: pr: ready to merge

#3518 Update notes about the dependency extraction plugin
  docs/renovate.md
Labels: type: enhancement, pr: ready to merge, type: documentation

#3503 HACK week: Migration of client/disputes/details
  client/components/loadable/index.tsx
  client/components/loadable/test/__snapshots__/index.tsx.snap
  client/components/loadable/test/index.js
  client/components/loadable/test/index.tsx
  client/components/paragraphs/index.js
  client/components/paragraphs/index.tsx
  client/components/paragraphs/test/__snapshots__/index.tsx.snap
  client/components/paragraphs/test/index.tsx
  client/data/disputes/hooks.ts
  client/disputes/details/actions.tsx
  client/disputes/details/index.tsx
  client/disputes/details/test/__snapshots__/actions.tsx.snap
  client/disputes/details/test/__snapshots__/index.tsx.snap
  client/disputes/details/test/actions.tsx
  client/disputes/details/test/index.tsx
  client/disputes/info/index.tsx
  client/disputes/info/test/index.tsx
  client/types/disputes.d.ts
Labels: pr: ready to merge

#3539 Hide explicit currency formatting from customer-facing emails
  changelog.txt
  includes/class-wc-payments-explicit-price-formatter.php
  readme.txt
Labels: pr: needs review

#3473 Include deposit status in Transaction exports
  changelog.txt
  client/data/transactions/hooks.ts
  client/deposits/strings.ts
  client/transactions/list/index.tsx
  client/transactions/list/test/index.tsx
  readme.txt
Labels: pr: ready to merge

#3556 Fix all tests using more than one `expectOutputRegex`
  tests/unit/multi-currency/test-class-currency-switcher-widget.php
  tests/unit/multi-currency/test-class-multi-currency.php
  tests/unit/multi-currency/test-class-user-settings.php
Labels: pr: ready to merge

#3530 Bump @woocommerce/e2e-utils to v0.1.6
  .github/workflows/e2e-test.yml
  package-lock.json
  package.json
  tests/e2e/config/test.json
  tests/e2e/specs/merchant/merchant-a-onboarding-setup.spec.js
  tests/e2e/specs/merchant/merchant-a-onboarding-task-list.spec.js
Labels: pr: ready to merge

#3553 Tidy tracks events for "create subscription product" flow
  client/subscription-product-onboarding/modal.js
  client/tracks/index.js
  includes/subscriptions/class-wc-payments-subscriptions-onboarding-handler.php
Labels: pr: ready to merge, type: task, size: small, component: wcpay subscriptions

#3520 Fix race condition when processing webhooks
  changelog.txt
  includes/admin/class-wc-rest-payments-webhook-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-utils.php
  readme.txt
Labels: pr: needs review

#3550 Load woocommerce-subscriptions-core 1.3.0
  changelog.txt
  composer.json
  composer.lock
  readme.txt
Labels: pr: ready to merge, component: wcpay subscriptions, needs subscriptions core update

#3549 Return correct product prices datatype in WCPay
  changelog.txt
  includes/multi-currency/FrontendPrices.php
  readme.txt
  tests/unit/multi-currency/test-class-frontend-prices.php
Labels: pr: needs review

#3568 Fix: Unable to access Subscription details when purchased via SEPA Direct Debit
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  readme.txt
Labels: pr: ready to merge

#3562 Move E2E user account management to setup script
  tests/e2e/env/setup.sh
  tests/e2e/setup/jest-setup.js
Labels: pr: needs review, category: engineering, category: e2e, category: devops

#3571 Add an endpoint to register a terminal card reader
  includes/admin/class-wc-rest-payments-reader-controller.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/admin/test-class-wc-rest-payments-readers-controller.php
Labels: pr: ready to merge, component: card present

#3570 Skip flaky shopper E2E tests
  tests/e2e/specs/blocks/shopper/shopper-wc-blocks-checkout-failures.spec.js
  tests/e2e/specs/blocks/shopper/shopper-wc-blocks-checkout-purchase.spec.js
  tests/e2e/specs/wcpay/shopper/shopper-checkout-failures.spec.js
  tests/e2e/specs/wcpay/shopper/shopper-checkout-save-card-and-purchase.spec.js
  tests/e2e/specs/wcpay/shopper/shopper-myaccount-payment-methods-add-delete-success.spec.js
  tests/e2e/specs/wcpay/shopper/shopper-myaccount-payment-methods-add-fail.spec.js
  tests/e2e/specs/wcpay/shopper/shopper-myaccount-save-card-and-checkout-upe.spec.js
  tests/e2e/specs/wcpay/shopper/shopper-myaccount-save-card-and-checkout.spec.js
Labels: pr: ready to merge

#3575 Resume sending E2E test failures to slack
  .github/workflows/e2e-test.yml
  tests/e2e/config/jest.config.js
  tests/e2e/config/jest.setup.js
Labels: pr: ready to merge

#3577 Skip account check before MC init event on CLI
  includes/multi-currency/MultiCurrency.php
Labels: type: bug, pr: needs review, priority: high, category: performance, component: customer multi-currency

#3579 Bump WP & WC tested up to versions for v3.5.0
  .github/workflows/compatibility.yml
  .github/workflows/coverage.yml
  .github/workflows/e2e-test.yml
  changelog.txt
  readme.txt
  woocommerce-payments.php
Labels: pr: ready to merge

#3582 Force currency check when creating payment intents
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  includes/payment-methods/class-upe-payment-gateway.php
Labels: type: bug, pr: needs review, component: upe, category: projects

#3583 Add changelog about forcing currency check when creating a payment intent to readme
  readme.txt
Labels: pr: needs review

#3585 Add new changelog header for 3.6.0
  changelog.txt
  readme.txt
Labels: pr: ready to merge
