Repository Automattic/woocommerce-payments, pull requests merged in 2021-01, with the labels that each got.

#1007 Accept charges in multiple currencies
  client/payment-details/summary/index.js
  client/payment-details/summary/test/index.js
  client/payment-details/timeline/map-events.js
  client/payment-details/timeline/test/index.js
  client/payment-details/timeline/test/map-events.js
  client/transactions/list/index.js
  client/transactions/list/test/index.js
  client/utils/currency/index.js
  client/utils/currency/test/index.js
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-utils.php
  includes/class-wc-payments.php
  readme.txt
Labels: [Status] Needs Review

#1163 Linking customer name from transaction detail page to filtered list page
  changelog.txt
  client/components/customer-link/index.js
  client/components/customer-link/test/__snapshots__/index.js.snap
  client/components/customer-link/test/index.js
  client/payment-details/summary/index.js
  client/payment-details/summary/test/__snapshots__/index.js.snap
  readme.txt
Labels: [Status] Ready to Merge

#1187 CI: evaluate WC beta jobs failures
  bin/install-wp-tests.sh
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: [Status] Ready to Merge

#1151 Denote "sign in" action in dashboard link setting description
  includes/class-wc-payment-gateway-wcpay.php
Labels: [Status] Needs Review

#1189 Fixed a JS error causing empty transactions list
  client/transactions/list/index.js
Labels: [Status] Ready to Merge

#1192 Fixes Empty Alert When Refunding Authorization Charge
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  package-lock.json
  readme.txt
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: [Status] Needs Review, [Type] Bug

#1201 Format dispute amount with proper currency
  client/disputes/details/test/__snapshots__/index.js.snap
  client/disputes/details/test/index.js
  client/disputes/evidence/test/__snapshots__/index.js.snap
  client/disputes/evidence/test/index.js
  client/disputes/index.js
  client/disputes/info/index.js
  client/disputes/info/test/__snapshots__/index.js.snap
  client/disputes/info/test/index.js
  client/disputes/test/index.js
Labels: [Feature] Countries Currencies Localization, [Status] Ready to Merge

#1194 Bump automattic/jetpack-autoloader version to fix failing builds with upcoming WC 4.9
  .github/workflows/compatibility.yml
  .github/workflows/e2e-test.yml
  bin/install-wp-tests.sh
  composer.json
  composer.lock
  woocommerce-payments.php
Labels: [Status] Ready to Merge

#1074 Adds eslint-plugin-jsdoc-alignment and @woocommerce/eslint-plugin packages to JS dev-dependecies
  .eslintrc
  client/checkout/api/index.js
  client/checkout/blocks/confirm-card-payment.js
  client/checkout/blocks/fields.js
  client/checkout/blocks/generate-payment-method.js
  client/checkout/blocks/index.js
  client/checkout/classic/index.js
  client/components/customer-link/index.js
  client/components/loadable/index.js
  client/components/paragraphs/index.js
  client/components/progress-bar/index.js
  client/components/test-mode-notice/index.js
  client/connect-account-page/strings.js
  client/data/deposits/resolvers.js
  client/data/deposits/selectors.js
  client/data/disputes/selectors.js
  client/data/transactions/selectors.js
  client/disputes/details/index.js
  client/disputes/evidence/fields.js
  client/disputes/evidence/file-upload.js
  client/disputes/evidence/index.js
  client/disputes/info/index.js
  client/index.js
  client/payment-details/payment-method/index.js
  client/payment-details/timeline/map-events.js
  client/tos/modal/test/index.js
  client/tracks/index.js
  client/transactions/list/deposit.js
  client/transactions/list/index.js
  client/transactions/list/test/index.js
  client/utils/charge/index.js
  client/utils/checkout.js
  client/utils/currency/index.js
  client/utils/index.js
  package-lock.json
  package.json
  tests/e2e/specs/purchase.spec.js
  tests/e2e/utils/flows.js
  tests/e2e/utils/index.js
Labels: [Status] Ready to Merge

#1204 Fix test mode notice to match Page width
  changelog.txt
  client/components/test-mode-notice/index.js
  client/components/test-mode-notice/test/__snapshots__/index.js.snap
  client/components/test-mode-notice/test/index.js
  client/deposits/details/index.js
  client/deposits/index.js
  client/disputes/details/index.js
  client/disputes/evidence/index.js
  client/disputes/index.js
  client/index.js
  client/payment-details/index.js
  client/transactions/index.js
Labels: [Status] Ready to Merge

#1196 Added Jurassic Tube setup script
  bin/jurassic-tube-setup.sh
  package.json
Labels: [Status] Needs Review

#1205 Server API: override additional timeout settings
  changelog.txt
  includes/wc-payment-api/class-wc-payments-api-client.php
  readme.txt
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: [Status] Ready to Merge

#1244 Specify error code when refund fails in admin to prevent blank alert
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  readme.txt
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: [Status] Ready to Merge

#1197 Update to fix JS error when 100% off coupon is applied
  changelog.txt
  client/checkout/classic/index.js
  readme.txt
Labels: [Status] Ready to Merge

#1247 Temporarily restore USD currency check on payment gateway
  includes/class-wc-payment-gateway-wcpay.php
Labels: [Status] Ready to Merge

#1246 Add fees as line items sent to Stripe to prevent Level 3 errors
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  readme.txt
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: [Status] Needs Review
