Repository Automattic/woocommerce-payments, pull requests merged in 2021-03, with the labels that each got.

#1334 Support multiple customer currencies in live mode
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  readme.txt
Labels: pr: ready to merge

#1371 Define constant for the group to be used for scheduled actions
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-action-scheduler-service.php
  readme.txt
Labels: pr: needs review

#1335 Added styling for instant deposit button and modal
  changelog.txt
  client/deposits/instant-deposits/index.js
  client/deposits/instant-deposits/modal.js
  client/deposits/instant-deposits/notice.js
  client/deposits/instant-deposits/style.scss
  client/deposits/overview/index.js
  client/deposits/overview/instant-deposit-button.js
  client/deposits/overview/test/__snapshots__/index.js.snap
  readme.txt
Labels: pr: needs review

#1372 Tweak the "link_session" SIFT logic so it only fetches the WCPay account info when needed
  includes/class-wc-payments-fraud-service.php
Labels: pr: ready to merge

#1366 Support non-USD base fee currency on settings screen
  changelog.txt
  client/account-fees/index.js
  client/account-fees/test/__snapshots__/index.js.snap
  client/account-fees/test/index.js
  readme.txt
Labels: pr: ready to merge

#1382 Add/apple pay domain registration tracks event
  includes/class-wc-payments-apple-pay-registration.php
  includes/class-wc-payments.php
  tests/unit/test-class-wc-payments-apple-pay-registration.php
Labels: pr: ready to merge

#1175 Integrate product and cart pages with Payment Request Button
  changelog.txt
  client/payment-request/index.js
  client/payment-request/style.scss
  client/settings.js
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-payment-request-button-handler.php
  includes/class-wc-payments.php
  readme.txt
  tests/unit/test-class-wc-payments-payment-request-button-handler.php
  webpack.config.js
Labels: pr: ready to merge, status: blocked

#1239 Apple Pay domain verification
  apple-developer-merchantid-domain-association
  includes/class-wc-payments-apple-pay-registration.php
  includes/class-wc-payments-payment-request-button-handler.php
  includes/class-wc-payments.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tasks/release.js
  tests/unit/test-class-wc-payments-apple-pay-registration.php
Labels: pr: ready to merge

#1384 Fix the build for IE11
  .browserslistrc
  package-lock.json
  package.json
  webpack.config.js
Labels: pr: needs review

#1396 Fix console error on the settings screen.
  webpack.config.js
Labels: pr: ready to merge

#1387 Apple Pay / Payment Request Buttons Integration - Disable feature
  changelog.txt
  client/settings.js
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-apple-pay-registration.php
  includes/class-wc-payments-payment-request-button-handler.php
  includes/class-wc-payments.php
  readme.txt
Labels: pr: ready to merge

#1397 Run E2E tests for develop branch
  .github/workflows/e2e-test.yml
Labels: pr: ready to merge

#1398 Prepare for release 2.1.0
  .github/workflows/e2e-test.yml
  readme.txt
  webpack.config.js
  woocommerce-payments.php
Labels: pr: ready to merge

#1413 Fix reference to phpcbf executable in `lint:php-fix` npm script
  package.json
Labels: pr: ready to merge

#1404 Enable the Payment Request feature by default for new merchants only
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-apple-pay-registration.php
  includes/class-wc-payments-payment-request-button-handler.php
  includes/class-wc-payments.php
  tests/unit/test-class-wc-payments-apple-pay-registration.php
Labels: pr: needs review

#1406 Add option wcpay_is_apple_pay_enabled via filter
  includes/class-wc-payments-payment-request-button-handler.php
Labels: pr: ready to merge

#1393 Disable Payment Request buttons when authentication is required
  includes/class-wc-payments-apple-pay-registration.php
  includes/class-wc-payments-payment-request-button-handler.php
Labels: pr: ready to merge

#1407 Payment Request Button: Handle Puerto Rico country as United States
  client/payment-request/index.js
Labels: pr: needs review

#1424 Fix a critical error when a subscription renewal runs
  changelog.txt
  includes/class-wc-payments-fraud-service.php
  readme.txt
Labels: pr: ready to merge

#1368 Account overview page
  client/index.js
  client/overview/index.js
  includes/admin/class-wc-payments-admin.php
Labels: pr: ready to merge

#1428 `npm run up`: Provide default.env file to docker run command
  bin/docker-setup.sh
Labels: pr: ready to merge

#1423 Map WooCommerce states and Payment Request states
  includes/class-wc-payments-payment-request-button-handler.php
  includes/constants/class-payment-request-button-states.php
Labels: pr: ready to merge

#1378 Use card component from wordpress/components and fix misc related styling issues
  client/components/card-footer/index.js
  client/components/card-footer/style.scss
  client/components/horizontal-list/style.scss
  client/deposits/details/index.js
  client/deposits/details/style.scss
  client/deposits/details/test/__snapshots__/index.js.snap
  client/disputes/details/actions.js
  client/disputes/details/index.js
  client/disputes/details/test/__snapshots__/actions.js.snap
  client/disputes/details/test/__snapshots__/index.js.snap
  client/disputes/evidence/index.js
  client/disputes/evidence/test/__snapshots__/index.js.snap
  client/disputes/style.scss
  client/payment-details/payment-method/index.js
  client/payment-details/summary/index.js
  client/payment-details/summary/style.scss
  client/payment-details/summary/test/__snapshots__/index.js.snap
  client/payment-details/timeline/index.js
  client/payment-details/timeline/test/__snapshots__/index.js.snap
  client/style.scss
Labels: category: trash pickup, pr: needs review, pr: ready to merge

#1418 Fix missing payment token for free trial paid for with a previously saved card
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-process-payment.php
Labels: pr: ready to merge

#1421 Remove feature flag and allow Payment Request feature for US merchants only
  changelog.txt
  client/settings.js
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-apple-pay-registration.php
  includes/class-wc-payments-payment-request-button-handler.php
  includes/class-wc-payments.php
  readme.txt
Labels: pr: ready to merge, status: blocked

#1400 If store's country is not US, return empty level3 data.
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  readme.txt
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge

#1403 [Card Present Payments] Add accounts endpoint
  includes/admin/class-wc-rest-payments-accounts-controller.php
  includes/class-wc-payments.php
Labels: component: card present, pr: needs review

#1230 Add Deposits list pagination and sorting
  client/data/deposits/action-types.js
  client/data/deposits/actions.js
  client/data/deposits/hooks.js
  client/data/deposits/reducer.js
  client/data/deposits/resolvers.js
  client/data/deposits/selectors.js
  client/data/deposits/test/reducer.js
  client/data/deposits/test/resolvers.js
  client/deposits/list/index.js
  client/deposits/list/test/__snapshots__/index.js.snap
  client/deposits/list/test/index.js
  client/transactions/list/index.js
  includes/admin/class-wc-rest-payments-deposits-controller.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: ready to merge

#1442 Fix husky pre-commit hook
  .husky/.gitignore
  .husky/pre-commit
  package-lock.json
  package.json
Labels: pr: ready to merge
