Repository Automattic/woocommerce-payments, pull requests merged in 2021-04, with the labels that each got.

#1375 Introduced deposit currency filter for transactions overview
  changelog.txt
  client/data/transactions/hooks.js
  client/data/transactions/resolvers.js
  client/transactions/filters/config.js
  client/transactions/filters/index.js
  client/transactions/filters/test/index.js
  client/transactions/index.js
  client/transactions/list/index.js
  client/transactions/list/test/__snapshots__/index.js.snap
  client/transactions/list/test/index.js
  client/utils/currency/index.js
  client/utils/currency/test/index.js
  includes/admin/class-wc-rest-payments-transactions-controller.php
  readme.txt
Labels: pr: ready to merge

#1479 Add download transactions in CSV format
  changelog.txt
  client/transactions/list/index.js
  client/transactions/list/style.scss
  client/transactions/list/test/__snapshots__/index.js.snap
  readme.txt
Labels: pr: ready to merge

#1497 Add E2E to make sure each admin page loads
  tests/e2e/specs/admin/deposits.spec.js
  tests/e2e/specs/admin/disputes.spec.js
  tests/e2e/specs/admin/transactions.spec.js
  tests/e2e/utils/flows.js
  tests/e2e/utils/helpers.js
  tests/e2e/utils/index.js
Labels: pr: ready to merge

#1467 feat: add grouped settings flag
  includes/admin/class-wc-payments-admin.php
Labels: component: grouped-settings, pr: needs review

#1431 Set script translations so js files can be translated
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-blocks-payment-method.php
Labels: pr: needs review

#1498 Add red notification badge next to payments menu item
  changelog.txt
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-account.php
  readme.txt
Labels: pr: ready to merge

#985 Spike: Network-wide saved cards
  client/checkout/api/index.js
  client/checkout/blocks/index.js
  client/checkout/classic/index.js
  includes/class-payment-information.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-customer-service.php
  includes/class-wc-payments-token-service.php
  includes/class-wc-payments.php
  includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php
Labels: pr: needs review

#1530 Fix "Maximum update depth exceeded" error when filtering transactions
  changelog.txt
  client/data/transactions/hooks.js
  readme.txt
Labels: pr: ready to merge

#1520 Change the default track `recordEvent` to use @woocommerce/tracks
  changelog.txt
  client/data/disputes/actions.js
  client/disputes/details/actions.js
  client/disputes/evidence/index.js
  client/tracks/index.js
  client/transactions/list/index.js
  readme.txt
Labels: pr: ready to merge

#1528 Payment Request: Fix shipping calculation for UK and CA postal codes with Apple Pay
  includes/class-wc-payments-payment-request-button-handler.php
Labels: pr: ready to merge

#1519 Add WPCOM connection status to `wcpay_connect_account_clicked` track
  changelog.txt
  client/connect-account-page/index.js
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments.php
  readme.txt
Labels: pr: ready to merge

#1546 Allow users to clear the account cache
  changelog.txt
  includes/class-wc-payments-account.php
  readme.txt
Labels: pr: needs author reply

#1551 Display empty page for the new settings
  client/settings/index.js
  client/settings/settings-manager/index.js
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payment-gateway-wcpay.php
  webpack.config.js
Labels: pr: needs review

#1561 Allow to run `docker-setup.sh` in non-tty envs
  bin/docker-setup.sh
Labels: pr: needs review

#1569 CI: new build environment for E2E tests - lowest supported deps
  .github/workflows/e2e-test.yml
Labels: pr: ready to merge

#1549 Bump minimum WP version to 5.4
  .github/workflows/compatibility.yml
  changelog.txt
  phpcs.xml.dist
  readme.txt
  woocommerce-payments.php
Labels: pr: ready to merge

#1556 Fix order and subscription numbers on transaction list report
  client/transactions/list/index.js
Labels: pr: ready to merge

#1571 Added doc url and updated content for instant deposits eligibility note
  includes/notes/class-wc-payments-notes-instant-deposits-eligible.php
Labels: pr: needs review

#1537 Add SEPA Direct Debit payment method.
  assets/css/admin.css
  client/checkout/api/index.js
  client/checkout/blocks/fields.js
  client/checkout/blocks/generate-payment-method.js
  client/checkout/blocks/index.js
  client/checkout/classic/index.js
  client/checkout/classic/style.scss
  client/checkout/constants.js
  includes/class-payment-information.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments.php
  includes/payment-method/class-card.php
  includes/payment-method/class-sepa.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/e2e/utils/payments.js
  tests/unit/bootstrap.php
  tests/unit/payment-method/test-class-sepa.php
Labels: pr: ready to merge

#1541 Add/1444 new inbox msg qualitative feedback
  changelog.txt
  includes/class-wc-payments.php
  includes/notes/class-wc-payments-notes-qualitative-feedback.php
  readme.txt
Labels: needs feedback

#1531 Introduced currency filter on deposits list page
  changelog.txt
  client/data/deposits/action-types.js
  client/data/deposits/actions.js
  client/data/deposits/hooks.js
  client/data/deposits/reducer.js
  client/data/deposits/resolvers.js
  client/data/deposits/selectors.js
  client/deposits/filters/config.js
  client/deposits/filters/index.js
  client/deposits/index.js
  client/deposits/list/index.js
  client/deposits/list/test/__snapshots__/index.js.snap
  client/deposits/list/test/index.js
  client/transactions/filters/config.js
  includes/admin/class-wc-rest-payments-charges-controller.php
  includes/admin/class-wc-rest-payments-deposits-controller.php
  includes/admin/class-wc-rest-payments-disputes-controller.php
  includes/admin/class-wc-rest-payments-timeline-controller.php
  includes/admin/class-wc-rest-payments-transactions-controller.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  readme.txt
Labels: pr: ready to merge

#1437 Submitting instant deposits using wp.data
  client/data/deposits/action-types.js
  client/data/deposits/actions.js
  client/data/deposits/hooks.js
  client/data/deposits/reducer.js
  client/data/deposits/selectors.js
  client/data/deposits/test/reducer.js
  client/data/deposits/test/selectors.js
  client/deposits/instant-deposits/index.js
  client/deposits/instant-deposits/modal.js
  client/deposits/instant-deposits/notice.js
  client/deposits/instant-deposits/style.scss
  client/deposits/instant-deposits/test/__snapshots__/index.js.snap
  client/deposits/instant-deposits/test/index.js
  client/deposits/overview/index.js
  client/deposits/overview/test/index.js
Labels: pr: ready to merge

#1567 Make Payment Request buttons available for merchants in all countries
  changelog.txt
  client/settings/index.js
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-apple-pay-registration.php
  includes/class-wc-payments-payment-request-button-handler.php
  includes/class-wc-payments.php
  readme.txt
Labels: pr: ready to merge, status: blocked

#1584 Configurable payment request button locations
  changelog.txt
  client/settings/index.js
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-payment-request-button-handler.php
  readme.txt
Labels: pr: ready to merge

#1597 Fix instant deposits modal not working after error
  client/data/deposits/actions.js
  client/deposits/instant-deposits/index.js
  client/deposits/instant-deposits/modal.js
Labels: pr: ready to merge

#1601 Fix lint and test errors after conflict fix
  client/data/deposits/action-types.js
  client/data/deposits/test/reducer.js
  client/deposits/overview/test/__snapshots__/index.js.snap
  includes/admin/class-wc-rest-payments-deposits-controller.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-action-scheduler-service.php
Labels: pr: ready to merge

#1593 Add Tracks event for Payment Request Button activation/deactivation
  includes/class-wc-payments-payment-request-button-handler.php
Labels: pr: ready to merge

#1578 Package.json: add script to start and stop jurassic tube
  README.md
  bin/jurassic-tube-setup.sh
  package.json
Labels: pr: ready to merge

#1606 Use dispatch from wordpress/data instead of from wordpress/data-controls
  client/data/deposits/actions.js
Labels: pr: needs review

#1135 Instant deposits functionality
  changelog.txt
  client/components/progress-bar/style.scss
  client/data/deposits/action-types.js
  client/data/deposits/actions.js
  client/data/deposits/hooks.js
  client/data/deposits/reducer.js
  client/data/deposits/selectors.js
  client/data/deposits/test/reducer.js
  client/data/deposits/test/selectors.js
  client/deposits/instant-deposits/index.js
  client/deposits/instant-deposits/modal.js
  client/deposits/instant-deposits/style.scss
  client/deposits/instant-deposits/test/__snapshots__/index.js.snap
  client/deposits/instant-deposits/test/index.js
  client/deposits/overview/index.js
  client/deposits/overview/style.scss
  client/deposits/overview/test/__snapshots__/index.js.snap
  client/deposits/overview/test/index.js
  includes/admin/class-wc-rest-payments-deposits-controller.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-action-scheduler-service.php
  includes/class-wc-payments-fraud-service.php
  includes/class-wc-payments.php
  includes/notes/class-wc-payments-notes-instant-deposits-eligible.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  readme.txt
  tests/unit/notes/test-class-wc-payments-notes-instant-deposits-eligible.php
  tests/unit/test-class-wc-payments-account.php
Labels: pr: ready to merge

#1540 Enable the use of saved SEPA payments
  client/checkout/classic/index.js
  includes/class-payment-information.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payment-token-sepa.php
  includes/class-wc-payments-token-service.php
  includes/class-wc-payments.php
  includes/constants/class-payment-method.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/helpers/class-wc-helper-token.php
  tests/unit/payment-method/test-class-sepa.php
  tests/unit/test-class-payment-information.php
  tests/unit/test-class-wc-payment-token-sepa.php
  tests/unit/test-class-wc-payments-token-service.php
Labels: pr: ready to merge, type: good for architectural review

#1582 fix: payment sections settings sorting
  assets/css/admin.css
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-features.php
  includes/class-wc-payments.php
Labels: component: grouped-settings, component: sepa, pr: needs review

#1577 Add Giropay Payment Method
  client/checkout/classic/index.js
  client/checkout/constants.js
  includes/class-payment-information.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-token-service.php
  includes/class-wc-payments.php
  includes/payment-methods/class-cc-payment-gateway.php
  includes/payment-methods/class-giropay-payment-gateway.php
  includes/payment-methods/class-sepa-payment-gateway.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  includes/wc-payment-api/models/class-wc-payments-api-intention.php
  tests/unit/helpers/class-wc-helper-token.php
  tests/unit/payment-methods/test-class-giropay-payment-gateway.php
  tests/unit/payment-methods/test-class-sepa-payment-gateway.php
  tests/unit/test-class-payment-information.php
  tests/unit/test-class-wc-payment-token-sepa.php
Labels: pr: needs review

#1617 refactor: add Sepa to features class
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-features.php
  includes/class-wc-payments.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: component: sepa, pr: needs review

#1619 fix: naming in filter
  includes/class-wc-payments.php
Labels: pr: needs review

#1620 refactor: add Giropay to features class
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-features.php
  includes/class-wc-payments.php
Labels: pr: needs review

#1600 Update Connect Page
  changelog.txt
  client/checkout/classic/style.scss
  client/connect-account-page/cards/amex.js
  client/connect-account-page/cards/applepay.js
  client/connect-account-page/cards/cb.js
  client/connect-account-page/cards/diners.js
  client/connect-account-page/cards/discover.js
  client/connect-account-page/cards/jcb.js
  client/connect-account-page/cards/maestro.js
  client/connect-account-page/cards/mastercard.js
  client/connect-account-page/cards/unionpay.js
  client/connect-account-page/cards/visa.js
  client/connect-account-page/hero-image.js
  client/connect-account-page/index.js
  client/connect-account-page/strings.js
  client/connect-account-page/style.scss
  client/connect-account-page/test/__snapshots__/index.js.snap
  client/connect-account-page/wcpay-logo.js
  client/tracks/index.js
Labels: pr: needs review

#1609 Send translations to GlotPress on release
  .eslintrc
  .gitignore
  babel.config.js
  bin/combine-pot-files.php
  client/checkout/blocks/index.js
  client/components/customer-link/test/__snapshots__/index.js.snap
  client/index.js
  languages/README.md
  package-lock.json
  package.json
  tasks/release.js
  webpack.config.js
Labels: pr: ready to merge

#1580 feat: add WCPay sections in settings pages
  includes/admin/class-wc-payments-admin-sections-overwrite.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments.php
Labels: component: grouped-settings, pr: ready to merge

#1533 Add "Payment methods" card to the Settings page
  assets/images/drag-handle.svg
  assets/images/payment-methods/apple-pay.svg
  assets/images/payment-methods/cc.svg
  assets/images/payment-methods/giropay.svg
  assets/images/payment-methods/google-pay.svg
  assets/images/payment-methods/sepa.svg
  assets/images/payment-methods/sofort.svg
  client/components/orderable-list/index.js
  client/components/orderable-list/payment-method.js
  client/components/orderable-list/payment-method.scss
  client/components/orderable-list/style.scss
  client/components/orderable-list/test/index.js
  client/components/orderable-list/test/payment-method.js
  client/payment-methods/index.js
  client/payment-methods/style.scss
  client/payment-methods/test/index.js
  client/settings/index.js
  client/settings/settings-manager/index.js
  client/settings/style.scss
  includes/admin/class-wc-payments-admin.php
  package-lock.json
  package.json
  webpack.config.js
Labels: component: grouped-settings, pr: needs review

#1568 Remove setConfig()
  changelog.txt
  client/checkout/api/index.js
  client/utils/checkout.js
  includes/class-wc-payment-gateway-wcpay.php
  readme.txt
Labels: pr: ready to merge

#1648 Use type wcpay_sepa for payment token to avoid conflicts with stripe plugin
  includes/class-wc-payment-token-wcpay-sepa.php
  includes/class-wc-payments-token-service.php
  includes/class-wc-payments.php
  tests/unit/helpers/class-wc-helper-token.php
  tests/unit/test-class-payment-information.php
  tests/unit/test-class-wc-payment-token-sepa.php
  tests/unit/test-class-wc-payments-token-service.php
Labels: component: sepa, pr: needs review

#1670 Fix/1587 giropay transaction page
  assets/css/admin.css
  client/components/payment-method-details/index.js
  client/payment-details/payment-method/giropay/index.js
  client/payment-details/payment-method/index.js
Labels: pr: needs review

#1667 fix: payment methods elements align on wrap
  client/components/orderable-list/payment-method.scss
Labels: component: grouped-settings, pr: needs review

#1672 refactor: update payment methods list from design
  client/payment-methods/index.js
  client/payment-methods/style.scss
Labels: component: grouped-settings, pr: needs review

#1542 feat(Settings): add sortable list reusable component
  client/components/orderable-list/index.js
  client/components/orderable-list/style.scss
  client/components/orderable-list/test/index.js
  client/payment-methods/index.js
  package-lock.json
  package.json
  tsconfig.json
Labels: component: grouped-settings, pr: needs review

#1675 Add `transform-runtime` plugin to babel.config.js
  babel.config.js
Labels: pr: needs review

#1668 Use an option instead of a transient for caching account details
  changelog.txt
  includes/class-wc-payments-account.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  readme.txt
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-account.php
Labels: pr: ready to merge

#1684 fix: prevent JS error on settings page
  client/settings/index.js
Labels: component: grouped-settings, pr: needs review

#1686 fix: SVG webpack loader conflict
  package-lock.json
  package.json
  webpack.config.js
Labels: component: grouped-settings, pr: needs review

#1536 Update @wordpress/components to the latest version
  changelog.txt
  client/components/progress-bar/style.scss
  client/connect-account-page/index.js
  client/connect-account-page/test/__snapshots__/index.js.snap
  client/deposits/details/style.scss
  client/deposits/details/test/__snapshots__/index.js.snap
  client/deposits/instant-deposits/index.js
  client/deposits/instant-deposits/modal.js
  client/deposits/instant-deposits/test/__snapshots__/index.js.snap
  client/deposits/overview/style.scss
  client/disputes/details/actions.js
  client/disputes/details/test/__snapshots__/actions.js.snap
  client/disputes/details/test/__snapshots__/index.js.snap
  client/disputes/evidence/file-upload.js
  client/disputes/evidence/index.js
  client/disputes/evidence/test/__snapshots__/file-upload.js.snap
  client/disputes/evidence/test/__snapshots__/index.js.snap
  client/disputes/style.scss
  client/payment-details/summary/style.scss
  client/payment-details/summary/test/__snapshots__/index.js.snap
  client/payment-details/timeline/test/__snapshots__/index.js.snap
  client/payment-methods/index.js
  client/stylesheets/abstracts/_colors.scss
  client/tos/modal/index.js
  client/tos/modal/style.scss
  client/tos/modal/test/__snapshots__/index.js.snap
  client/transactions/list/test/__snapshots__/converted-amount.js.snap
  package-lock.json
  package.json
  readme.txt
  webpack.config.js
Labels: pr: needs review

#1623 Complete an order if payment intent is successful
  includes/admin/class-wc-rest-payments-webhook-controller.php
  includes/class-wc-payments-db.php
  tests/unit/admin/test-class-wc-rest-payments-webhook.php
Labels: pr: ready to merge

#1692 Apply styles correctly to SEPA input
  client/checkout/classic/style.scss
Labels: pr: needs review

#1696 Put passing sepa as payment method behind feature flag in create_and_confirm_setup_intent()
  changelog.txt
  includes/wc-payment-api/class-wc-payments-api-client.php
  readme.txt
Labels: pr: ready to merge

#1543 Add E2E Merchant / Order / Full Refund
  tests/e2e/specs/merchant/order-full-refund.spec.js
  tests/e2e/utils/flows.js
  tests/e2e/utils/helpers.js
Labels: category: E2E, pr: ready to merge

#1650 Fix translation strings domain
  client/account-status/index.js
  client/connect-account-page/strings.js
  client/disputes/evidence/file-upload.js
  client/disputes/evidence/index.js
  client/payment-details/timeline/map-events.js
  client/transactions/autocompleter.js
  client/transactions/filters/config.js
Labels: pr: ready to merge

#1611 Fix details not displayed in deposits overview
  changelog.txt
  client/deposits/overview/index.js
  client/deposits/overview/style.scss
  client/deposits/overview/test/__snapshots__/index.js.snap
  readme.txt
Labels: component: deposits, pr: ready to merge

#1690 Add empty payment method edit screen
  client/components/orderable-list/payment-method.js
  client/components/orderable-list/payment-method.scss
  client/components/orderable-list/style.scss
  client/components/orderable-list/test/index.js
  client/components/orderable-list/test/payment-method.js
  client/payment-methods/index.js
  client/payment-methods/test/index.js
  client/settings/index.js
  client/settings/payment-method-settings/giropay-settings.js
  client/settings/payment-method-settings/index.js
  client/settings/payment-method-settings/index.scss
  client/settings/payment-method-settings/test/index.js
  client/settings/settings-manager/index.js
  client/settings/settings-section.js
  client/settings/settings-section.scss
  client/settings/style.scss
  client/settings/test/settings-section.js
  client/utils/index.js
  client/utils/test/index.js
  includes/admin/class-wc-payments-admin-sections-overwrite.php
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-utils.php
  tests/unit/admin/test-class-wc-payments-admin-sections-overwrite.php
  tests/unit/bootstrap.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-utils.php
Labels: component: grouped-settings, pr: needs review

#1699 Fix Add Payment method for SEPA by sending mandate data on intent.
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: component: sepa, pr: needs review

#1698 chore: update add payment method button style
  client/payment-methods/index.js
  client/settings/payment-methods-selector/index.js
Labels: component: grouped-settings, pr: needs review
