Repository Automattic/woocommerce-payments, pull requests merged in 2021-05, with the labels that each got.

#1700 Pull in and use the e2e-utils and api packages for e2e tests
  package-lock.json
  package.json
  tests/e2e/specs/admin/deposits.spec.js
  tests/e2e/specs/admin/disputes.spec.js
  tests/e2e/specs/admin/transactions.spec.js
  tests/e2e/specs/merchant/order-full-refund.spec.js
  tests/e2e/specs/purchase.spec.js
  tests/e2e/specs/saved-cards/saved-cards-checkout.spec.js
  tests/e2e/specs/saved-cards/saved-cards-my-account.spec.js
  tests/e2e/utils/flows.js
  tests/e2e/utils/helpers.js
  tests/e2e/utils/payments.js
Labels: category: E2E, pr: ready to merge

#1701 feat: add general settings section
  client/settings/general-settings/index.js
  client/settings/general-settings/style.scss
  client/settings/general-settings/test/general-settings.test.js
  client/settings/settings-manager/index.js
  client/settings/settings-section.scss
  client/settings/test-mode-settings/index.js
  client/settings/test-mode-settings/style.scss
Labels: component: grouped-settings, pr: needs review

#1693 feat: add digital wallets section
  client/settings/digital-wallets/index.js
  client/settings/digital-wallets/test/index.test.js
  client/settings/settings-manager/index.js
Labels: component: grouped-settings, pr: needs review

#1592 Subscribe extension to automated translation updates
  woocommerce-payments.php
Labels: pr: needs review

#1680 Fix using CC token for wrong payment method
  includes/class-payment-information.php
  tests/unit/test-class-payment-information.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-payment-method-order-note.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-process-payment.php
Labels: pr: needs review

#1718 Fix payment gateway filtering
  changelog.txt
  includes/class-wc-payments.php
  readme.txt
Labels: pr: ready to merge

#1709 refactor: SettingsSection description
  client/settings/payment-method-settings/index.js
  client/settings/settings-manager/index.js
  client/settings/settings-section.js
  client/settings/test/settings-section.js
Labels: component: grouped-settings, pr: needs review

#1710 refactor: SettingsManager gateway icons
  assets/images/payment-methods/apple-pay.svg
  assets/images/payment-methods/cc.svg
  assets/images/payment-methods/giropay.svg
  assets/images/payment-methods/google-pay.svg
  assets/images/payment-methods/sepa.svg
  assets/images/payment-methods/sofort.svg
  client/components/orderable-list/payment-method.js
  client/components/orderable-list/payment-method.scss
  client/gateway-icons/apple-pay.js
  client/gateway-icons/credit-card.js
  client/gateway-icons/giropay.js
  client/gateway-icons/google-pay.js
  client/gateway-icons/sepa.js
  client/gateway-icons/sofort.js
  client/payment-methods/index.js
  client/payment-methods/style.scss
  client/payment-methods/test/index.js
  client/settings/payment-method-icon/giropay.svg
  client/settings/payment-method-icon/index.js
  client/settings/payment-method-icon/sepa.svg
  client/settings/payment-method-icon/sofort.svg
  client/settings/payment-method-icon/style.scss
  client/settings/payment-method-icon/test/index.js
  client/settings/payment-method-settings/test/index.js
  client/settings/payment-methods-selector/test/index.js
  client/settings/settings-manager/index.js
  client/settings/settings-section.scss
Labels: component: grouped-settings

#1716 Fix translations not loading for Javascript files
  client/deposits/list/index.js
  client/transactions/list/index.js
  includes/class-wc-payments-translations-loader.php
  includes/class-wc-payments.php
Labels: pr: needs review

#1731 feat: do not show delete when one payment method enabled
  client/components/orderable-list/payment-method.js
  client/components/orderable-list/test/payment-method.js
  client/payment-methods/index.js
  client/payment-methods/test/index.js
Labels: component: grouped-settings, pr: needs review

#1673 Instant Deposit button and modal design tweaks
  changelog.txt
  client/deposits/instant-deposits/index.js
  client/deposits/instant-deposits/modal.js
  client/deposits/instant-deposits/test/__snapshots__/index.js.snap
  client/deposits/instant-deposits/test/index.js
  client/deposits/overview/index.js
  client/deposits/overview/test/index.js
  includes/notes/class-wc-payments-notes-instant-deposits-eligible.php
  readme.txt
Labels: component: instant deposits, needs design, pr: needs review

#1654 deps: add yarnhook
  .husky/post-checkout
  .husky/post-merge
  .husky/post-rewrite
  package-lock.json
  package.json
Labels: pr: needs review, type: enhancement

#1529 Add Payment Request button support for Woo blocks
  changelog.txt
  client/checkout/api/index.js
  client/checkout/blocks/index.js
  client/checkout/blocks/request.js
  client/checkout/constants.js
  client/payment-request/blocks/apple-pay-preview.js
  client/payment-request/blocks/branded-buttons.js
  client/payment-request/blocks/custom-button.js
  client/payment-request/blocks/index.js
  client/payment-request/blocks/payment-request-express.js
  client/payment-request/blocks/use-initialization.js
  client/payment-request/event-handlers.js
  client/payment-request/index.js
  client/payment-request/style.scss
  client/payment-request/utils/index.js
  client/payment-request/utils/normalize.js
  client/payment-request/utils/utils.js
  includes/class-wc-payments-blocks-payment-method.php
  includes/class-wc-payments-payment-request-button-handler.php
  readme.txt
  tests/unit/test-class-wc-payments-payment-request-button-handler.php
Labels: pr: needs design review, pr: ready to merge

#1642 Use correct amount for Variable products if “Default form values” is set
  includes/class-wc-payments-payment-request-button-handler.php
Labels: pr: needs review

#1708 Revert "Update Connect page (#1600)"
  client/connect-account-page/cards/amex.js
  client/connect-account-page/cards/applepay.js
  client/connect-account-page/cards/cb.js
  client/connect-account-page/cards/diners.js
  client/connect-account-page/cards/discover.js
  client/connect-account-page/cards/jcb.js
  client/connect-account-page/cards/maestro.js
  client/connect-account-page/cards/mastercard.js
  client/connect-account-page/cards/unionpay.js
  client/connect-account-page/cards/visa.js
  client/connect-account-page/hero-image.js
  client/connect-account-page/index.js
  client/connect-account-page/strings.js
  client/connect-account-page/style.scss
  client/connect-account-page/test/__snapshots__/index.js.snap
  client/connect-account-page/wcpay-logo.js
  client/tracks/index.js
Labels: pr: ready to merge

#1739 Add @woocommerce/explat Dependency
  package-lock.json
  package.json
  readme.txt
Labels: pr: ready to merge

#1744 Fix lint-staged eslint config to lint only staged files
  .husky/pre-commit
  package.json
Labels: pr: ready to merge, type: enhancement

#1379 Update dockerfile for client container in E2E environment
  tests/e2e/env/wordpress-xdebug/Dockerfile
Labels: pr: needs review

#1746 Add Connect Page A/B Test
  changelog.txt
  client/connect-account-page-experiment/index.js
  client/connect-account-page-variant/cards/amex.js
  client/connect-account-page-variant/cards/applepay.js
  client/connect-account-page-variant/cards/cb.js
  client/connect-account-page-variant/cards/diners.js
  client/connect-account-page-variant/cards/discover.js
  client/connect-account-page-variant/cards/gpay.js
  client/connect-account-page-variant/cards/jcb.js
  client/connect-account-page-variant/cards/maestro.js
  client/connect-account-page-variant/cards/mastercard.js
  client/connect-account-page-variant/cards/unionpay.js
  client/connect-account-page-variant/cards/visa.js
  client/connect-account-page-variant/hero-image.js
  client/connect-account-page-variant/index.js
  client/connect-account-page-variant/strings.js
  client/connect-account-page-variant/style.scss
  client/connect-account-page-variant/test/__snapshots__/index.js.snap
  client/connect-account-page-variant/test/index.js
  client/connect-account-page-variant/wcpay-logo.js
  client/index.js
  client/tracks/index.js
  readme.txt
Labels: pr: ready to merge

#1733 fix: drag handles display
  client/components/orderable-list/style.scss
Labels: component: grouped-settings, type: bug

#1742 Fix: 1719 Columns are misaligned on Payments->Transactions/Disputes page
  changelog.txt
  client/disputes/index.js
  client/disputes/style.scss
  client/disputes/test/__snapshots__/index.js.snap
  client/transactions/list/style.scss
  readme.txt
Labels: pr: needs review

#1741 Fix: #1720 Risk level being displayed as a numeric value in CSV export file
  changelog.txt
  client/components/risk-level/index.js
  client/components/risk-level/test/index.js
  client/transactions/list/index.js
  readme.txt
Labels: pr: needs review

#1747 Bump minimum WooCommerce version to 4.5
  changelog.txt
  readme.txt
Labels: pr: needs review

#1771 refactor: payment method checkboxes
  client/components/payment-methods-checkboxes/index.js
  client/components/payment-methods-checkboxes/payment-method-checkbox.js
  client/components/payment-methods-checkboxes/payment-method-checkbox.scss
  client/components/payment-methods-checkboxes/test/index.js
  client/settings/payment-method-icon/index.js
  client/settings/payment-methods-selector/index.js
  client/settings/payment-methods-selector/style.scss
Labels: component: grouped-settings, pr: needs review

#1760 Revert Connect Page Event Name
  client/tracks/index.js
Labels: pr: needs review

#1786 Fix the name of the hook for the api client
  includes/class-wc-payments.php
Labels: pr: ready to merge

#1758 Add in WC Subscriptions for e2e tests
  .github/workflows/e2e-test.yml
  tests/e2e/README.md
  tests/e2e/env/docker-compose.yml
  tests/e2e/env/setup.sh
  tests/e2e/specs/subscriptions/README.md
  tests/e2e/specs/subscriptions/subscription-settings.spec.js
  tests/e2e/utils/flows.js
Labels: category: E2E, pr: ready to merge

#1795 Initialize WCPay multi currency, set mock currencies
  includes/class-wc-payments.php
  includes/multi-currency/class-wc-payments-multi-currency-currency.php
  includes/multi-currency/class-wc-payments-multi-currency.php
  includes/multi-currency/wc-payments-multi-currency.php
Labels: component: multi shopper currencies, pr: needs review

#1791 fix: payment methods modal action order
  client/settings/payment-methods-selector/index.js
  client/settings/payment-methods-selector/style.scss
  client/stylesheets/abstracts/_mixins.scss
Labels: component: grouped-settings, pr: needs review

#1797 chore: settings copy updates
  client/settings/digital-wallets/index.js
  client/settings/digital-wallets/test/index.test.js
  client/settings/general-settings/index.js
  client/settings/general-settings/style.scss
  client/settings/settings-manager/index.js
Labels: component: grouped-settings, pr: needs review

#1754 Set a locale when loading Stripe.js elements
  changelog.txt
  client/checkout/api/index.js
  client/checkout/blocks/index.js
  client/checkout/classic/index.js
  client/payment-request/index.js
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-blocks-payment-method.php
  includes/class-wc-payments-payment-request-button-handler.php
  includes/class-wc-payments-utils.php
  includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php
  includes/payment-methods/class-giropay-payment-gateway.php
  includes/payment-methods/class-sofort-payment-gateway.php
  readme.txt
  tests/unit/test-class-wc-payments-utils.php
Labels: pr: ready to merge

#1647 Use API and wordpress data to get and set gateway settings
  client/data/index.js
  client/data/settings/action-types.js
  client/data/settings/actions.js
  client/data/settings/hooks.js
  client/data/settings/index.js
  client/data/settings/reducer.js
  client/data/settings/resolvers.js
  client/data/settings/selectors.js
  client/data/settings/test/actions.js
  client/data/settings/test/hooks.js
  client/data/settings/test/reducer.js
  client/data/settings/test/resolvers.js
  client/data/settings/test/selectors.js
  client/data/store.js
  client/payment-methods/index.js
  client/payment-methods/test/index.js
  client/settings/general-settings/index.js
  client/settings/general-settings/test/general-settings.test.js
  client/settings/payment-method-icon/index.js
  client/settings/payment-method-icon/test/index.js
  client/settings/payment-methods-selector/index.js
  client/settings/payment-methods-selector/test/index.js
  client/settings/settings-manager/index.js
  client/settings/settings-manager/style.scss
  client/settings/settings-section.js
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-wc-payments.php
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
  tests/unit/bootstrap.php
  tests/unit/test-class-wc-payments.php
Labels: component: grouped-settings, pr: needs review

#1783 Move data utility function test to client/utils/test/data.js
  client/utils/test/data.js
Labels: category: refactor

#1801 Change protected properties to public, fix filenames
  includes/multi-currency/class-currency.php
  includes/multi-currency/class-multi-currency.php
  includes/multi-currency/class-wc-payments-multi-currency-currency.php
  includes/multi-currency/wc-payments-multi-currency.php
Labels: component: multi shopper currencies, pr: needs review

#1772 Add placeholder TaskList component to the Overview page.
  client/overview/index.js
  client/overview/style.scss
  client/overview/task-list.js
  client/overview/test/index.js
  client/stylesheets/abstracts/_colors.scss
  client/stylesheets/abstracts/_variables.scss
  package-lock.json
  package.json
  webpack.config.js
Labels: dependencies, pr: needs review

#1799 Add "update business details" task
  client/overview/index.js
  client/overview/style.scss
  client/overview/task-list.js
  client/overview/task-list/index.js
  client/overview/task-list/tasks.js
  client/overview/task-list/test/tasks.js
  client/overview/test/index.js
  includes/admin/class-wc-payments-admin.php
  package-lock.json
  package.json
Labels: component: account overview page, component: accounts, needs feedback

#1759 Redirect to WC home page after successful WCPay KYC
  changelog.txt
  includes/class-wc-payments-account.php
Labels: pr: ready to merge

#1841 Fix/issue 1732 add payment methods
  client/payment-methods/index.js
  client/settings/payment-methods-selector/index.js
  client/settings/payment-methods-selector/test/index.js
Labels: component: grouped-settings, pr: needs review

#1842 refactor: modal buttons alignment
  client/settings/payment-methods-selector/index.js
  client/settings/payment-methods-selector/style.scss
  client/stylesheets/abstracts/_mixins.scss
Labels: component: grouped-settings, pr: needs review

#1790 feat: disable individual payment methods confirmation dialog
  client/components/orderable-list/delete-button.js
  client/components/orderable-list/delete-button.scss
  client/components/orderable-list/payment-method.js
  client/components/orderable-list/test/payment-method.js
  client/payment-methods/index.js
  client/payment-methods/test/index.js
Labels: component: grouped-settings, pr: needs review

#1792 refactor: remove sortable payment methods list
  client/components/orderable-list/index.js
  client/components/orderable-list/style.scss
  client/components/orderable-list/test/index.js
  client/components/payment-methods-list/delete-button.js
  client/components/payment-methods-list/delete-button.scss
  client/components/payment-methods-list/index.js
  client/components/payment-methods-list/payment-method.js
  client/components/payment-methods-list/payment-method.scss
  client/components/payment-methods-list/style.scss
  client/components/payment-methods-list/test/index.js
  client/components/payment-methods-list/test/payment-method.js
  client/payment-methods/index.js
  client/payment-methods/style.scss
  client/payment-methods/test/index.js
  client/stylesheets/abstracts/_mixins.scss
  package-lock.json
  package.json
Labels: component: grouped-settings, pr: needs review

#1838 Fix: Columns are misaligned on Payments->Deposits
  changelog.txt
  client/deposits/list/index.js
  client/deposits/list/style.scss
  client/deposits/list/test/__snapshots__/index.js.snap
  client/transactions/list/style.scss
  readme.txt
Labels: pr: ready to merge

#1751 feat: additional payment methods onboarding
  client/additional-methods-setup/index.js
  client/additional-methods-setup/index.scss
  client/additional-methods-setup/methods-selector/add-payment-methods-task.js
  client/additional-methods-setup/methods-selector/add-payment-methods-task.scss
  client/additional-methods-setup/methods-selector/index.js
  client/additional-methods-setup/methods-selector/index.scss
  client/additional-methods-setup/methods-selector/setup-complete-task.js
  client/additional-methods-setup/methods-selector/setup-complete-task.scss
  client/additional-methods-setup/wizard/README.md
  client/additional-methods-setup/wizard/collapsible-body.js
  client/additional-methods-setup/wizard/collapsible-body.scss
  client/additional-methods-setup/wizard/task-item.js
  client/additional-methods-setup/wizard/task-item.scss
  client/additional-methods-setup/wizard/task-list.js
  client/additional-methods-setup/wizard/task/context.js
  client/additional-methods-setup/wizard/task/index.js
  client/additional-methods-setup/wizard/test/index.js
  client/additional-methods-setup/wizard/wrapper/context.js
  client/additional-methods-setup/wizard/wrapper/index.js
Labels: component: grouped-settings, pr: needs review

#1806 refactor: rename delete button from list
  client/components/payment-methods-list/delete-button.js
  client/components/payment-methods-list/test/payment-method.js
  client/payment-methods/test/index.js
Labels: component: grouped-settings, pr: needs review

#1849 refactor: sensible settings selectors defaults
  client/data/settings/selectors.js
Labels: component: grouped-settings, pr: needs review

#1854 chore: remove giropay-specific settings page
  client/settings/payment-method-settings/giropay-settings.js
  client/settings/payment-method-settings/index.js
  client/settings/payment-method-settings/test/index.js
Labels: component: grouped-settings, pr: needs review

#1856 Create data store for multi shopper currency feature
  client/data/index.js
  client/data/multi-currency/action-types.js
  client/data/multi-currency/actions.js
  client/data/multi-currency/hooks.js
  client/data/multi-currency/index.js
  client/data/multi-currency/reducer.js
  client/data/multi-currency/resolvers.js
  client/data/multi-currency/selectors.js
  client/data/store.js
Labels: component: multi shopper currencies, pr: ready to merge

#1805 refactor: enable eslint hook rules
  .eslintrc
  client/additional-methods-setup/wizard/wrapper/index.js
  client/checkout/blocks/fields.js
  client/components/page/index.js
  client/data/settings/hooks.js
  client/deposits/list/index.js
  client/disputes/evidence/index.js
  client/payment-details/index.js
  client/payment-details/timeline/index.js
  client/payment-details/timeline/test/__snapshots__/index.js.snap
  client/payment-details/timeline/test/index.js
  client/payment-request/blocks/use-initialization.js
  client/settings/payment-methods-selector/index.js
  client/transactions/list/index.js
  client/utils/use-confirm-navigation.js
Labels: component: grouped-settings, pr: needs review, type: task

#1862 fix: payment method icon borders
  client/components/payment-methods-list/delete-button.js
  client/components/payment-methods-list/payment-method.js
  client/payment-methods/index.js
Labels: component: grouped-settings, pr: needs review

#1821 Add tracking for returning from OAuth connection
  changelog.txt
  client/tos/index.js
  client/tos/modal/index.js
  client/tos/modal/test/index.js
  client/tos/request.js
  client/tracks/index.js
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-tos-controller.php
  includes/class-wc-payments-account.php
  readme.txt
  tests/unit/admin/test-class-wc-rest-payments-tos-controller.php
Labels: pr: needs review

#1788 Construct table summary data only when transactions and deposits summary data has been loaded.
  changelog.txt
  client/deposits/list/index.js
  client/deposits/list/test/index.js
  client/transactions/list/index.js
  client/transactions/list/test/__snapshots__/index.js.snap
  client/transactions/list/test/index.js
  readme.txt
Labels: pr: ready to merge

#1866 Add basic session management for multi shopper currency
  includes/multi-currency/class-multi-currency.php
Labels: pr: needs review

#1844 Update deposit overview details
  changelog.txt
  client/deposits/details/index.js
  client/deposits/details/style.scss
  client/deposits/details/test/__snapshots__/index.js.snap
  client/deposits/details/test/index.js
  client/deposits/overview/index.js
  client/deposits/overview/style.scss
  client/style.scss
  readme.txt
Labels: pr: ready to merge

#1874 Fix undefined default currency notices in multi currency tests
  tests/unit/bootstrap.php
Labels: pr: ready to merge, type: bug

#1858 Added api endpoints for multi shopper currency project.
  includes/multi-currency/class-currency.php
  includes/multi-currency/class-multi-currency.php
  includes/multi-currency/class-wc-rest-controller.php
Labels: component: multi shopper currencies, pr: needs review

#1850 feat: hide add payment method section when necessary
  client/data/settings/hooks.js
  client/data/settings/selectors.js
  client/payment-methods/index.js
  client/payment-methods/test/index.js
  client/settings/payment-method-icon/index.js
  client/settings/payment-methods-selector/index.js
  client/settings/payment-methods-selector/test/index.js
Labels: component: grouped-settings

#1857 chore: remove payment method order setting
  includes/class-wc-payments.php
  tests/unit/test-class-wc-payments.php
Labels: component: grouped-settings

#1873 Restore delete icons used on transaction pages
  assets/images/payment-methods/giropay.svg
  assets/images/payment-methods/sofort.svg
Labels: pr: needs review

#1863 Fix failing unit test due to Woo default currency change.
  tests/unit/helpers/class-wc-helper-order.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
Labels: pr: ready to merge

#1864 Fix typo function call
  client/tos/request.js
Labels: pr: ready to merge

#1851 Update changelog about redirection after KYC.
  changelog.txt
  readme.txt
Labels: pr: ready to merge

#1852 Emoji country flags for Multi-Shopper Currencies
  includes/multi-currency/class-country-flags.php
  includes/multi-currency/class-currency.php
  includes/multi-currency/class-multi-currency.php
  tests/unit/multi-currency/test-class-country-flags.php
Labels: component: multi shopper currencies, pr: ready to merge

#1776 Fix: #1721 Replaced column with info icon with transaction id column for CSV
  changelog.txt
  client/transactions/list/index.js
  client/transactions/list/test/__snapshots__/index.js.snap
  client/transactions/list/test/index.js
  readme.txt
Labels: pr: ready to merge

#1876 Add multi currency tests for Currency and Multi_Currency session handling
  includes/multi-currency/class-multi-currency.php
  includes/multi-currency/tests/unit/test-class-currency.php
  includes/multi-currency/tests/unit/test-class-multi-currency.php
  phpunit.xml.dist
  tests/unit/bootstrap.php
Labels: component: multi shopper currencies, pr: ready to merge

#1886 Move Customer multi-currency tests to tests/unit/multi-currency
  phpunit.xml.dist
  tests/unit/multi-currency/test-class-currency.php
  tests/unit/multi-currency/test-class-multi-currency.php
Labels: component: customer multi-currency, pr: ready to merge

#1887 Add customer multi-currency feature flag
  includes/class-wc-payments-features.php
  includes/class-wc-payments.php
  tests/unit/bootstrap.php
Labels: component: customer multi-currency, pr: needs review

#1888 feat: add dev mode in settings screen
  client/data/settings/action-types.js
  client/data/settings/actions.js
  client/data/settings/hooks.js
  client/data/settings/reducer.js
  client/data/settings/selectors.js
  client/settings/settings-manager/index.js
  client/settings/test-mode-settings/index.js
  includes/admin/class-wc-rest-payments-settings-controller.php
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
Labels: component: grouped-settings

#1853 Add legacy widget for multi shopper currencies
  includes/multi-currency/class-currency-switcher-widget.php
  includes/multi-currency/class-multi-currency.php
  tests/unit/multi-currency/test-class-currency-switcher-widget.php
Labels: pr: ready to merge

#1882 feat: add confirmation modal component
  client/components/confirmation-modal/index.js
  client/components/confirmation-modal/styles.scss
  client/components/payment-delete-illustration/index.js
  client/components/payment-delete-illustration/styles.scss
  client/components/payment-methods-list/delete-button.js
  client/components/payment-methods-list/delete-button.scss
  client/settings/payment-methods-selector/index.js
Labels: component: grouped-settings, pr: needs review

#1800 feat: add advanced settings section
  client/settings/advanced-settings/index.js
  client/settings/advanced-settings/style.scss
  client/settings/advanced-settings/test/index.test.js
  client/settings/general-settings/index.js
  client/settings/settings-manager/index.js
Labels: component: grouped-settings

#1861 feat: add onboarding UPE payment methods
  client/additional-methods-setup/methods-selector/add-payment-methods-task.js
  client/additional-methods-setup/methods-selector/index.js
  client/additional-methods-setup/methods-selector/setup-complete-task.js
  client/additional-methods-setup/methods-selector/test/add-payment-methods-task.test.js
  client/data/settings/actions.js
  client/settings/payment-method-icon/index.js
  includes/admin/class-wc-payments-admin-additional-methods-setup.php
  includes/class-wc-payments.php
Labels: component: grouped-settings, pr: needs review

#1897 feat: placeholder an input type on settings > advanced styles
  client/settings/advanced-settings/index.js
Labels: component: grouped-settings

#1889 refactor: settings hooks
  client/data/settings/hooks.js
  client/data/settings/test/hooks.js
  client/payment-methods/index.js
  client/payment-methods/test/index.js
  client/settings/digital-wallets/index.js
  client/settings/digital-wallets/test/index.test.js
  client/settings/general-settings/index.js
  client/settings/general-settings/test/general-settings.test.js
  client/settings/payment-methods-selector/index.js
  client/settings/payment-methods-selector/test/index.js
  client/settings/test-mode-settings/index.js
Labels: component: grouped-settings, pr: needs review

#1883 feat: disable WCPay confirmation dialog
  client/gateway-icons/woo-card.js
  client/payment-gateways/disable-confirmation-modal.js
  client/payment-gateways/index.js
  client/payment-gateways/payment-gateways-confirmation.js
  client/payment-gateways/styles.scss
  client/payment-gateways/test/disable-confirmation-modal.test.js
  includes/admin/class-wc-payments-admin.php
  tests/e2e/specs/admin/payment-gateways-confirmation.spec.js
  webpack.config.js
Labels: component: grouped-settings

#1809 Added tests and workflows for sub product with signup fee
  package-lock.json
  package.json
  tests/e2e/env/setup.sh
  tests/e2e/specs/subscriptions/purchase-sign-up-fee-subscription.spec.js
  tests/e2e/specs/subscriptions/subscription-settings.spec.js
  tests/e2e/utils/flows.js
  tests/e2e/utils/helpers.js
  tests/e2e/utils/payments.js
Labels: category: E2E, pr: ready to merge

#1860 Add customer facing prices for customer multi-currency
  includes/multi-currency/class-frontend-currencies.php
  includes/multi-currency/class-frontend-prices.php
  includes/multi-currency/class-multi-currency.php
  tests/unit/multi-currency/test-class-frontend-currencies.php
  tests/unit/multi-currency/test-class-frontend-prices.php
  tests/unit/multi-currency/test-class-multi-currency.php
Labels: component: customer multi-currency, pr: ready to merge

#1464 Account Status block for an Account Overview page
  client/account-fees-settings/index.js
  client/account-fees-settings/test/__snapshots__/index.js.snap
  client/account-fees-settings/test/index.js
  client/account-status-settings/index.js
  client/account-status-settings/style.scss
  client/account-status-settings/test/__snapshots__/index.js.snap
  client/account-status-settings/test/index.js
  client/account-status/style.scss
  client/components/account-status/account-fees.js
  client/components/account-status/account-status-item.js
  client/components/account-status/index.js
  client/components/account-status/shared.scss
  client/components/account-status/status-chip.js
  client/components/account-status/style.scss
  client/components/account-status/test/__snapshots__/index.js.snap
  client/components/account-status/test/index.js
  client/components/deposits-status/index.js
  client/components/deposits-status/test/__snapshots__/index.js.snap
  client/components/deposits-status/test/index.js
  client/components/payments-status/index.js
  client/components/payments-status/test/__snapshots__/index.js.snap
  client/components/payments-status/test/index.js
  client/overview/index.js
  client/overview/style.scss
  client/overview/test/index.js
  client/settings/index.js
  client/utils/account-fees.js
  client/utils/currency/index.js
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-account.php
Labels: pr: ready to merge

#1893 Fix: added missing display attribute to the table row data
  client/transactions/list/index.js
Labels: pr: ready to merge

#1910 Add customer default currency to account settings
  includes/multi-currency/class-multi-currency.php
  includes/multi-currency/class-user-settings.php
  tests/unit/multi-currency/test-class-user-settings.php
Labels: component: customer multi-currency, pr: ready to merge

#1840 [Mobile Payments] Partially addresses display of card-present transactions
  client/payment-details/payment-method/card-present/index.js
  client/payment-details/payment-method/card-present/test/__snapshots__/index.js.snap
  client/payment-details/payment-method/card-present/test/index.js
  client/payment-details/payment-method/index.js
Labels: [Feature] Card Present, pr: ready to merge

#1798 Add workflow for scheduled weekly I18N build
  .github/workflows/i18n-weekly-release.yml
Labels: pr: ready to merge

#1941 chore: rename 1-click checkouts
  client/settings/digital-wallets/index.js
  client/settings/digital-wallets/test/index.test.js
  client/settings/payment-method-settings/index.js
  client/settings/payment-method-settings/test/index.js
  client/settings/settings-manager/index.js
  includes/admin/class-wc-rest-payments-settings-controller.php
Labels: component: grouped-settings

#1939 refactor: settings save button section
  client/settings/payment-method-settings/digital-wallets-settings.js
  client/settings/payment-method-settings/index.js
  client/settings/payment-method-settings/index.scss
  client/settings/payment-method-settings/test/index.js
  client/settings/save-settings-section/index.js
  client/settings/save-settings-section/style.scss
  client/settings/save-settings-section/test/index.test.js
  client/settings/settings-manager/index.js
  client/settings/settings-manager/style.scss
Labels: component: grouped-settings, pr: needs review

#1943 chore: payment method CTA spacing
  client/components/payment-methods-list/payment-method.scss
Labels: component: grouped-settings

#1948 chore: copy updates on payment delete modal
  client/components/payment-methods-list/delete-button.js
  client/settings/test-mode-settings/index.js
Labels: component: grouped-settings, pr: needs review

#1904 refactor: remove DW gateway class from new settings
  client/data/settings/reducer.js
  client/data/settings/selectors.js
  client/data/settings/test/hooks.js
  client/data/settings/test/reducer.js
  client/data/settings/test/selectors.js
  client/settings/digital-wallets/index.js
  client/settings/digital-wallets/test/index.test.js
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/constants/class-digital-wallets-locations.php
  includes/payment-methods/class-digital-wallets-payment-gateway.php
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
  tests/unit/payment-methods/test-class-digital-wallets-payment-gateway.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: component: grouped-settings, pr: needs review

#1917 Add the store's currency to the list of available currencies
  includes/multi-currency/class-multi-currency.php
  tests/unit/multi-currency/test-class-multi-currency.php
Labels: component: customer multi-currency, pr: needs review

#1956 Fix enabled currencies list so that it reloads on update.
  client/data/multi-currency/actions.js
Labels: component: customer multi-currency

#1929 Fix styling for enabled currencies components, cleaned up classnames.
  client/multi-currency/enabled-currencies-list/delete-button.js
  client/multi-currency/enabled-currencies-list/delete-button.scss
  client/multi-currency/enabled-currencies-list/index.js
  client/multi-currency/enabled-currencies-list/list-item.js
  client/multi-currency/enabled-currencies-list/modal-checkbox.js
  client/multi-currency/enabled-currencies-list/modal.js
  client/multi-currency/enabled-currencies-list/style.scss
  includes/multi-currency/class-multi-currency.php
Labels: component: customer multi-currency, pr: needs review

#1919 Update payment intent in UPE workflow
  includes/payment-methods/class-upe-payment-gateway.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: category: engineering, pr: needs review

#1906 feat: digital wallets onboarding page
  client/additional-methods-setup/methods-selector/add-payment-methods-task.js
  client/additional-methods-setup/methods-selector/test/add-payment-methods-task.test.js
Labels: component: grouped-settings, pr: needs review

#1957 Update to use wcpaySettings across pages to reduce duplication
  .eslintrc
  client/settings/index.js
  includes/admin/class-wc-payments-admin.php
Labels: pr: ready to merge

#1892 Deposits information block on account overview page
  changelog.txt
  client/components/account-status/style.scss
  client/components/deposits-information/block.tsx
  client/components/deposits-information/declarations.d.ts
  client/components/deposits-information/index.tsx
  client/components/deposits-information/loading.tsx
  client/components/deposits-information/style.scss
  client/components/deposits-information/test/__snapshots__/index.js.snap
  client/components/deposits-information/test/index.js
  client/components/loadable/index.js
  client/data/deposits/action-types.js
  client/data/deposits/actions.js
  client/data/deposits/hooks.js
  client/data/deposits/reducer.js
  client/data/deposits/resolvers.js
  client/data/deposits/selectors.js
  client/data/deposits/test/overviews.fixture.json
  client/data/deposits/test/selectors.js
  client/data/index.js
  client/deposits/overview/index.js
  client/deposits/overview/test/index.js
  client/deposits/utils/index.js
  client/deposits/utils/test/index.js
  client/overview/index.js
  client/overview/style.scss
  includes/admin/class-wc-rest-payments-deposits-controller.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  package-lock.json
  package.json
  readme.txt
Labels: pr: ready to merge

#1895 Set overview page as default page for WCPay.
  assets/css/admin.css
  changelog.txt
  client/index.js
  client/overview/index.js
  client/overview/style.scss
  client/overview/test/index.js
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-account.php
  package-lock.json
  readme.txt
Labels: pr: ready to merge

#1966 Deleted account status, base free from WCPay settings and migrated few components from WCPay settings to overview page.
  changelog.txt
  client/components/account-status/account-fees.js
  client/components/account-status/account-fees/expiration-bar.js
  client/components/account-status/account-fees/expiration-description.js
  client/components/account-status/account-fees/index.js
  client/components/account-status/account-fees/test/__snapshots__/index.js.snap
  client/components/account-status/account-fees/test/index.js
  client/components/account-status/index.js
  client/components/account-status/style.scss
  client/components/account-status/test/__snapshots__/index.js.snap
  client/settings/index.js
  includes/class-wc-payment-gateway-wcpay.php
  readme.txt
Labels: pr: ready to merge

#1743 Add custom GlotPress project to woorelease config
  package.json
Labels: pr: ready to merge
