Repository Automattic/woocommerce-payments, pull requests merged in 2021-02, with the labels that each got.

#1250 Currencies: allow non-usd order in dev-environment
  includes/class-wc-payment-gateway-wcpay.php
Labels: [Status] Ready to Merge

#1262 Add Gutenberg plugin to the test setup.
  bin/install-wp-tests.sh
  tests/e2e/env/setup.sh
Labels: [Status] Ready to Merge

#1117 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: [Status] Ready to Merge

#1265 Fix wcpaySettings is not defined on the settings page
  includes/admin/class-wc-payments-admin.php
Labels: [Status] Ready to Merge, [Type] Bug

#1207 Enqueue Sift JS on every WCPay page
  changelog.txt
  client/checkout/blocks/index.js
  client/checkout/classic/index.js
  client/components/page/index.js
  client/fraud-scripts/index.js
  client/fraud-scripts/sift.js
  client/fraud-scripts/stripe.js
  client/hooks/include-stripe-js/index.js
  client/settings.js
  composer.json
  composer.lock
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-action-scheduler-service.php
  includes/class-wc-payments-customer-service.php
  includes/class-wc-payments-fraud-service.php
  includes/class-wc-payments.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  includes/wc-payment-api/class-wc-payments-http-interface.php
  includes/wc-payment-api/class-wc-payments-http.php
  readme.txt
  tests/unit/admin/test-class-wc-rest-payments-tos-controller.php
  tests/unit/test-class-wc-payment-gateway-wcpay-payment-types.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-action-scheduler-service.php
  tests/unit/test-class-wc-payments-customer-service.php
Labels: [Status] Ready to Merge

#1227 Pass order currency to wc_price() when not in customer's session.
  changelog.txt
  includes/admin/class-wc-rest-payments-webhook-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-utils.php
  includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  includes/wc-payment-api/models/class-wc-payments-api-intention.php
  readme.txt
  tests/unit/admin/test-class-wc-rest-payments-webhook.php
  tests/unit/test-class-wc-payment-gateway-wcpay-payment-types.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-utils.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: [Status] Ready to Merge

#1171 Link customer name on transaction list page to Woo Customers page
  changelog.txt
  client/transactions/list/index.js
  client/transactions/list/test/__snapshots__/index.js.snap
  includes/wc-payment-api/class-wc-payments-api-client.php
  readme.txt
Labels: [Status] Ready to Merge

#1277 Fix woocommerce_update_order incompatibility with WC Subscriptions
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  readme.txt
Labels: [Status] Needs Review, [Type] Bug

#1270 Fixed broken transactions listing when order is missing
  changelog.txt
  client/transactions/list/index.js
  readme.txt
Labels: [Status] In Progress, [Status] Ready to Merge

#1268 Added new Connection_Exception class to be used to catch connection errors for better notices/logging
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments.php
  includes/exceptions/class-connection-exception.php
  includes/wc-payment-api/class-wc-payments-http.php
  readme.txt
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
Labels: [Status] Ready to Merge

#1269 Update Payments > Settings > Account status/Deposits notice to Temporarily suspended if deposits are manual
  changelog.txt
  client/account-status/index.js
  client/account-status/style.scss
  client/account-status/test/__snapshots__/index.js.snap
  client/account-status/test/index.js
  readme.txt
Labels: [Status] Ready to Merge

#1281 Transactions: render customer details as text when order is missing
  changelog.txt
  client/transactions/list/index.js
  readme.txt
Labels: [Status] Ready to Merge

#1291 Register Stripe JS before using it as a dependency in block checkout
  changelog.txt
  includes/class-wc-payments-blocks-payment-method.php
Labels: [Status] Ready to Merge

#1285 Add payment features configuration to WooCommerce Blocks registration.
  client/checkout/blocks/index.js
  includes/class-wc-payment-gateway-wcpay.php
Labels: [Status] Ready to Merge

#1290 Use checkout block config when wcpay_config global is not defined
  changelog.txt
  client/utils/checkout.js
  readme.txt
Labels: [Status] Ready to Merge

#1228 Update/1054 transaction details
  changelog.txt
  client/payment-details/summary/index.js
  client/payment-details/summary/test/index.js
  client/utils/charge/index.js
  client/utils/charge/test/index.js
  readme.txt
Labels: [Status] Ready to Merge

#1241 Update timeline details rendering for multi-currency transactions
  changelog.txt
  client/payment-details/timeline/map-events.js
  client/payment-details/timeline/test/__snapshots__/map-events.js.snap
  client/payment-details/timeline/test/map-events.js
  client/utils/currency/index.js
  client/utils/currency/test/index.js
  readme.txt
Labels: [Status] Ready to Merge

#1300 Fix rendering amount in multi-currency transaction summary
  client/payment-details/summary/index.js
Labels: [Status] Ready to Merge

#1304 Fix "Stripe.js loaded more than one time" warning
  client/fraud-scripts/index.js
Labels: [Status] Ready to Merge

#1263 Enable TypeScript
  .eslintrc
  client/index.js
  package-lock.json
  package.json
  tests/js/jest.config.js
  tsconfig.json
  webpack.config.js
Labels: [Status] Ready to Merge

#1283 Add connection tokens endpoint
  includes/admin/class-wc-rest-payments-connection-tokens-controller.php
  includes/class-wc-payments.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: [Status] Needs Review

#1302 Transactions list: Add conversion icon with tooltip showing original amount
  changelog.txt
  client/transactions/list/converted-amount.js
  client/transactions/list/index.js
  client/transactions/list/style.scss
  client/transactions/list/test/__snapshots__/converted-amount.js.snap
  client/transactions/list/test/__snapshots__/index.js.snap
  client/transactions/list/test/converted-amount.js
  client/transactions/list/test/index.js
  readme.txt
Labels: [Status] Ready to Merge

#1309 Link order notes to transaction details
  changelog.txt
  client/utils/charge/index.js
  includes/class-wc-payment-gateway-wcpay.php
  readme.txt
Labels: [Status] Ready to Merge

#1295 Action Scheduler Logic Updates for Order Create/Update Events
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-action-scheduler-service.php
  readme.txt
  tests/unit/test-class-wc-payments-action-scheduler-service.php
Labels: [Status] Ready to Merge

#1343 Update forward_request to use error code returned from API_Exception
  includes/admin/class-wc-payments-rest-controller.php
Labels: [Status] Ready to Merge

#1288 Fix changing payment from saved payment for subscriptions order.
  changelog.txt
  includes/class-payment-information.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php
  readme.txt
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-process-payment.php
Labels: [Status] Ready to Merge

#1312 Subscriptions compatibility for order tracking updates
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-action-scheduler-service.php
  includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-action-scheduler-service.php
Labels: [Status] Ready to Merge

#1349 Add Forter fraud tracking
  client/fraud-scripts/forter.js
  client/fraud-scripts/index.js
  client/fraud-scripts/sift.js
  client/fraud-scripts/stripe.js
  includes/class-wc-payments-fraud-service.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: [Status] Ready to Merge

#1264 Deposits summary and details: use proper currencies
  changelog.txt
  client/data/deposits/resolvers.js
  client/deposits/details/index.js
  client/deposits/list/index.js
  client/deposits/overview/index.js
  client/transactions/list/index.js
  readme.txt
Labels: [Status] Ready to Merge

#1148 Show last 4 digit credit card in subscriptions order's note when updating failed payment
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  includes/compat/subscriptions/class-wc-payment-gateway-wcpay-subscriptions-compat.php
  readme.txt
  tests/unit/helpers/class-wc-helper-subscription.php
  tests/unit/helpers/class-wc-mock-wc-data-store.php
  tests/unit/helpers/class-wc-mock-wc-data.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-payment-method-order-note.php
Labels: [Status] Ready to Merge

#1367 Move changelog entry for #1148 to its proper place
  changelog.txt
  readme.txt
Labels: [Status] Needs Review
