Repository Automattic/woocommerce-payments, pull requests merged in 2021-07, with the labels that each got.

#2337 Initial Setup of Psalm for WC Pay Client
  .github/workflows/php-lint-test.yml
  bin/run-psalm.sh
  composer.json
  composer.lock
  includes/class-experimental-abtest.php
  includes/class-logger.php
  includes/class-payment-information.php
  includes/class-wc-payments-token-service.php
  includes/constants/class-digital-wallets-locations.php
  includes/constants/class-payment-capture-type.php
  includes/constants/class-payment-initiated-by.php
  includes/constants/class-payment-method.php
  includes/constants/class-payment-type.php
  includes/exceptions/class-api-exception.php
  includes/exceptions/class-base-exception.php
  includes/multi-currency/FrontendPrices.php
  includes/multi-currency/RestController.php
  includes/multi-currency/wc-payments-multi-currency.php
  includes/notes/class-wc-payments-remote-note-service.php
  includes/payment-methods/class-giropay-payment-gateway.php
  includes/payment-methods/class-sofort-payment-gateway.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/wc-payment-api/class-wc-payments-http-interface.php
  package.json
  psalm-baseline.xml
  psalm-loader.php
  psalm.xml
Labels: pr: ready to merge

#2339 Prep for 2.6.1 release
  changelog.txt
  includes/class-wc-payments.php
  readme.txt
Labels: pr: needs review

#2344 Psalm: suppress DuplicateClass errors
  psalm.xml
Labels: pr: ready to merge

#2322 Add notification on store currency change
  includes/multi-currency/AdminNotices.php
  includes/multi-currency/MultiCurrency.php
  tests/unit/multi-currency/test-class-admin-notices.php
Labels: component: customer multi-currency, pr: needs review

#2350 Meetup: migrate transactions page to TS
  client/components/deposits-information/block.tsx
  client/components/deposits-information/declarations.d.ts
  client/components/deposits-information/index.tsx
  client/components/page/index.tsx
  client/components/test-mode-notice/index.js
  client/connect-account-page/modal/test/__snapshots__/index.js.snap
  client/data/index.ts
  client/data/transactions/hooks.ts
  client/deposits/index.js
  client/deposits/instant-deposits/test/__snapshots__/index.js.snap
  client/empty-state-table/deposits-banner.svg
  client/empty-state-table/index.js
  client/empty-state-table/list.js
  client/empty-state-table/style.scss
  client/empty-state-table/transactions-banner.svg
  client/globals.d.ts
  client/multi-currency/enabled-currencies-list/test/__snapshots__/index.js.snap
  client/transactions/autocompleter.tsx
  client/transactions/declarations.d.ts
  client/transactions/filters/config.ts
  client/transactions/filters/index.tsx
  client/transactions/filters/test/__snapshots__/index.tsx.snap
  client/transactions/filters/test/index.tsx
  client/transactions/index.tsx
  client/transactions/list/converted-amount.tsx
  client/transactions/list/deposit.js
  client/transactions/list/deposit.tsx
  client/transactions/list/index.tsx
  client/transactions/list/test/__snapshots__/converted-amount.tsx.snap
  client/transactions/list/test/__snapshots__/deposit.tsx.snap
  client/transactions/list/test/__snapshots__/index.tsx.snap
  client/transactions/list/test/converted-amount.tsx
  client/transactions/list/test/deposit.tsx
  client/transactions/list/test/index.tsx
  client/transactions/strings.ts
  client/utils/compute-suggestion-match.ts
  package-lock.json
  package.json
  tsconfig.json
Labels: pr: ready to merge

#2276 Link back to evidence form from success notice
  changelog.txt
  client/disputes/evidence/index.js
  readme.txt
Labels: component: disputes, pr: ready to merge

#2317 Query the Server to fetch new rates when the store default currency is changed
  includes/multi-currency/MultiCurrency.php
  tests/unit/multi-currency/test-class-multi-currency.php
Labels: component: customer multi-currency, pr: ready to merge

#2319 Added logic to format the example rate differently if a zero decimal currency is used
  client/multi-currency/enabled-currencies-list/index.js
  client/multi-currency/enabled-currencies-list/list-item.js
  includes/multi-currency/Settings.php
Labels: pr: ready to merge

#2356 Set description when creating payment intents
  changelog.txt
  includes/payment-methods/class-upe-payment-gateway.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  readme.txt
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: ready to merge

#2338 Update multi currency settings UX
  client/multi-currency/index.js
  includes/multi-currency/Settings.php
Labels: component: customer multi-currency, pr: needs review

#2367 Fix so that resubscribe prices are not converted a second time
  includes/multi-currency/Compatibility.php
  tests/unit/helpers/class-wc-helper-subscriptions.php
  tests/unit/multi-currency/test-class-compatibility.php
Labels: component: customer multi-currency, pr: ready to merge

#2368 chore: rename digital wallets components
  client/additional-methods-setup/methods-selector/add-payment-methods-task.js
  client/additional-methods-setup/methods-selector/test/add-payment-methods-task.test.js
  client/data/settings/actions.js
  client/data/settings/hooks.js
  client/data/settings/selectors.js
  client/data/settings/test/hooks.js
  client/data/settings/test/reducer.js
  client/data/settings/test/selectors.js
  client/settings/payment-method-settings/index.js
  client/settings/payment-method-settings/payment-request-settings.js
  client/settings/payment-method-settings/test/index.js
  client/settings/payment-method-settings/test/payment-request-settings.test.js
  client/settings/payment-request/index.js
  client/settings/payment-request/style.scss
  client/settings/payment-request/test/index.test.js
  client/settings/settings-manager/index.js
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-wc-payments.php
  includes/constants/class-digital-wallets-locations.php
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: component: grouped-settings, pr: needs review

#2373 fix: allow all payment methods view when not connected
  changelog.txt
  includes/admin/class-wc-payments-admin-sections-overwrite.php
  includes/class-wc-payments.php
  tests/unit/admin/test-class-wc-payments-admin-sections-overwrite.php
Labels: component: grouped-settings, pr: needs review

#2379 Add a Last Updated Column to the Currency class
  includes/multi-currency/Currency.php
  includes/multi-currency/FrontendCurrencies.php
  includes/multi-currency/MultiCurrency.php
  includes/multi-currency/Settings.php
  tests/unit/multi-currency/test-class-currency.php
  tests/unit/multi-currency/test-class-multi-currency.php
Labels: component: customer multi-currency, pr: ready to merge

#2384 feat: display error on invalid bank statement
  client/data/settings/actions.js
  client/data/settings/hooks.js
  client/data/settings/reducer.js
  client/data/settings/selectors.js
  client/data/settings/test/actions.js
  client/data/settings/test/reducer.js
  client/settings/general-settings/index.js
  client/settings/transactions-and-deposits/index.js
  client/settings/transactions-and-deposits/style.scss
  client/settings/transactions-and-deposits/test/index.test.js
  includes/admin/class-wc-rest-payments-settings-controller.php
Labels: component: grouped-settings, pr: needs review

#2197 Add support for saved cards in Block based checkout
  changelog.txt
  client/checkout/blocks/confirm-card-payment.js
  client/checkout/blocks/fields.js
  client/checkout/blocks/hooks.js
  client/checkout/blocks/index.js
  client/checkout/blocks/saved-token-handler.js
  includes/class-wc-payment-gateway-wcpay.php
  readme.txt
Labels: pr: ready to merge

#2348 Add E2E screenshots saved to file
  .github/workflows/e2e-test.yml
  tests/e2e/config/jest.config.js
  tests/e2e/env/setup.sh
  tests/e2e/specs/merchant/merchant-admin-deposits.spec.js
  tests/e2e/specs/merchant/merchant-admin-transactions.spec.js
  tests/e2e/specs/merchant/merchant-orders-full-refund.spec.js
  tests/e2e/specs/shopper/shopper-checkout-purchase.spec.js
  tests/e2e/utils/helpers.js
Labels: category: E2E, pr: ready to merge

#2332 feat: opt-out survey endpoint
  composer.json
  includes/admin/class-wc-rest-payments-survey-controller.php
  includes/class-wc-payments.php
  includes/wc-payment-api/class-wc-payments-http-interface.php
  includes/wc-payment-api/class-wc-payments-http.php
  tests/unit/admin/test-class-wc-rest-payments-survey-controller.php
  tests/unit/bootstrap.php
Labels: component: grouped-settings, pr: needs review

#2404 fix: additional payment methods task
  includes/admin/class-wc-payments-admin-additional-methods-setup.php
Labels: component: grouped-settings

#2326 Fix failed free trial checkout when card requires authentication
  includes/class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-process-payment.php
Labels: pr: ready to merge

#2394 Remove currency settings when removed as an enabled currency.
  includes/multi-currency/MultiCurrency.php
  tests/unit/multi-currency/test-class-multi-currency.php
Labels: component: customer multi-currency, pr: ready to merge

#2352 Use date picker for applicable dispute evidence fields
  .github/PULL_REQUEST_TEMPLATE.md
  changelog.txt
  client/disputes/evidence/fields.js
  client/disputes/evidence/index.js
  client/disputes/evidence/test/__snapshots__/index.js.snap
  client/disputes/evidence/test/index.js
  readme.txt
Labels: pr: ready to merge

#2357 Add check for updated locale-info.php and provide fallback
  i18n/currency-info.php
  i18n/locale-info.php
  includes/multi-currency/FrontendCurrencies.php
  tests/unit/multi-currency/test-class-frontend-currencies.php
Labels: category: i18n, component: customer multi-currency, pr: ready to merge, size: small

#2408 Created Locale class and moved locale functions into it.
  includes/multi-currency/FrontendCurrencies.php
  includes/multi-currency/Locale.php
  includes/multi-currency/MultiCurrency.php
  includes/multi-currency/Utils.php
  tests/unit/multi-currency/test-class-frontend-currencies.php
  tests/unit/multi-currency/test-class-locale.php
  tests/unit/multi-currency/test-class-utils.php
Labels: component: customer multi-currency, pr: needs review

#2412 Fix some locales in currency-info.php
  i18n/currency-info.php
Labels: component: customer multi-currency, pr: ready to merge, size: small

#2414 Update currency-info.php
  i18n/currency-info.php
  i18n/locale-info.php
  tests/unit/multi-currency/test-class-locale.php
Labels: component: customer multi-currency, pr: needs review, size: small

#2396 Fix to not double convert subscription percentage coupons
  includes/multi-currency/Compatibility.php
  tests/unit/multi-currency/test-class-compatibility.php
Labels: component: customer multi-currency, pr: ready to merge

#2382 Fix Recurring Product Discount coupon double conversion
  includes/multi-currency/Compatibility.php
  includes/multi-currency/FrontendPrices.php
  tests/unit/multi-currency/test-class-compatibility.php
  tests/unit/multi-currency/test-class-frontend-prices.php
Labels: component: customer multi-currency, pr: needs review

#2372 Add header to Payment Methods, tweak display when UPE is disabled.
  client/payment-methods/index.js
  client/payment-methods/style.scss
  client/payment-methods/test/index.js
  client/settings/settings-manager/index.js
Labels: component: grouped-settings, pr: needs review

#2421 Created changelog entry for 2.8.0
  changelog.txt
  readme.txt
Labels: pr: ready to merge

#2349 Meetup: E2E - Add accept_tos=1 when adding linking account
  tests/e2e/env/setup.sh
Labels: pr: ready to merge, status: blocked

#2329 Add a fix for dispute winning e2e test
  tests/e2e/specs/merchant/merchant-disputes-submit-losing.spec.js
  tests/e2e/specs/merchant/merchant-disputes-submit-winning.spec.js
Labels: category: E2E, pr: needs review

#2411 Format customer currency based on locale
  includes/multi-currency/FrontendCurrencies.php
  includes/multi-currency/Locale.php
  tests/unit/multi-currency/test-class-frontend-currencies.php
  tests/unit/multi-currency/test-class-locale.php
Labels: component: customer multi-currency, pr: ready to merge

#2444 fix: alignment of payment method checkboxes
  client/additional-methods-setup/wizard/collapsible-body.js
  client/components/payment-methods-checkboxes/payment-method-checkbox.scss
Labels: component: grouped-settings

#2443 fix: clipping of focus indicator on modal
  client/multi-currency/enabled-currencies-list/style.scss
Labels: component: customer multi-currency, pr: needs review

#2442 fix: confirmation modal rulers
  client/components/confirmation-modal/styles.scss
  client/multi-currency/enabled-currencies-list/delete-button.js
  client/multi-currency/enabled-currencies-list/modal.js
  client/multi-currency/enabled-currencies-list/style.scss
  client/multi-currency/enabled-currencies-list/test/__snapshots__/index.js.snap
  client/stylesheets/abstracts/_mixins.scss
Labels: component: customer multi-currency, pr: needs review

#2436 Add Dispute Status Chip into the header of the Dispute Details page
  client/disputes/details/index.js
  client/disputes/details/test/__snapshots__/index.js.snap
  client/disputes/details/test/index.js
  client/disputes/style.scss
Labels: pr: ready to merge

#2439 Use a singular label in the summary of Transactions and Deposits lists
  client/deposits/list/index.js
  client/deposits/list/test/__snapshots__/index.js.snap
  client/deposits/list/test/index.js
  client/transactions/list/index.tsx
  client/transactions/list/test/__snapshots__/index.tsx.snap
  client/transactions/list/test/index.tsx
Labels: pr: ready to merge

#2318 Fix multiple conversions with subscription switching, minor refactor for manual renewals
  includes/multi-currency/Compatibility.php
  includes/multi-currency/FrontendPrices.php
  includes/multi-currency/MultiCurrency.php
  tests/unit/helpers/class-wc-helper-subscriptions.php
  tests/unit/multi-currency/test-class-compatibility.php
  tests/unit/multi-currency/test-class-frontend-prices.php
Labels: component: customer multi-currency, pr: needs review

#2410 Set currency_format locale data into a transient.
  includes/multi-currency/Locale.php
  tests/unit/multi-currency/test-class-locale.php
Labels: component: customer multi-currency, pr: needs review

#2419 fix: payment methods icon borders
  assets/css/admin.css
Labels: component: grouped-settings, pr: needs review, type: bug

#2426 refactor: loading indicator on payments section
  client/payment-methods/index.js
  client/payment-methods/style.scss
Labels: component: grouped-settings, pr: needs review

#2393 Update enabled currencies list/table design.
  client/multi-currency/enabled-currencies-list/list-item.js
  client/multi-currency/enabled-currencies-list/style.scss
  client/multi-currency/enabled-currencies-list/test/__snapshots__/index.js.snap
Labels: component: customer multi-currency, pr: needs review

#2438 In-person payments: attach level 3 data when capturing payments
  includes/admin/class-wc-rest-payments-orders-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/payment-methods/class-upe-payment-gateway.php
  tests/unit/admin/test-class-wc-rest-payments-orders-controller.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge

#2358 Display APM setup task on the WCPay Overview page
  client/additional-methods-setup/index.js
  client/additional-methods-setup/methods-selector/setup-complete-task.js
  client/additional-methods-setup/methods-selector/test/setup-complete-task.test.js
  client/additional-methods-setup/task.js
  client/additional-methods-setup/test/task.test.js
  client/additional-methods-setup/upe-preview-methods-selector/setup-complete-task.js
  client/additional-methods-setup/upe-preview-methods-selector/test/setup-complete-task.test.js
  client/index.js
  client/overview/index.js
  client/overview/task-list/index.js
  client/overview/task-list/tasks.js
  client/overview/task-list/test/index.js
  client/overview/task-list/test/tasks.js
  composer.lock
  includes/admin/class-wc-payments-admin-additional-methods-setup.php
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments.php
  tests/unit/admin/test-class-wc-payments-admin.php
  webpack.config.js
Labels: pr: needs review

#2090 Hide Payment Request Buttons when cart contains multiple packages
  changelog.txt
  includes/class-wc-payments-payment-request-button-handler.php
  readme.txt
  tests/unit/test-class-wc-payments-payment-request-button-handler.php
Labels: pr: ready to merge

#2423 fix: size of payment methods card
  client/payment-methods/index.js
  client/payment-methods/style.scss
  client/payment-methods/test/index.js
Labels: component: grouped-settings, pr: needs review, type: bug

#2478 Remove references to WCPay being "US-only" in the Readme
  readme.txt
Labels: pr: ready to merge

#2477 Avoid crash when seeing the details of an empty deposit
  changelog.txt
  client/transactions/list/index.tsx
  readme.txt
Labels: pr: ready to merge

#2365 Add ellipsis to dispute task
  client/overview/index.js
  client/overview/task-list/index.js
  client/overview/task-list/tasks.js
  includes/admin/class-wc-payments-admin.php
Labels: needs feedback

#2458 fix: reset modal state on close
  client/payment-methods/index.js
  client/settings/payment-methods-selector/index.js
  client/settings/payment-methods-selector/test/index.js
Labels: component: grouped-settings, pr: needs review

#2328 Move completed task to the bottom
  client/overview/index.js
  client/overview/task-list/tasks.js
  client/overview/task-list/test/tasks.js
Labels: pr: ready to merge

#2472 feat: UPE payment methods onboarding fixes
  client/additional-methods-setup/methods-selector/add-payment-methods-task.js
  client/additional-methods-setup/methods-selector/test/add-payment-methods-task.test.js
Labels: component: grouped-settings, pr: needs review

#2420 feat: UPE preview onboarding first step
  client/additional-methods-setup/upe-preview-methods-selector/enable-upe-preview-task.js
  client/additional-methods-setup/upe-preview-methods-selector/enable-upe-preview-task.scss
  client/additional-methods-setup/upe-preview-methods-selector/index.scss
Labels: component: grouped-settings, pr: needs review

#2405 feat: UPE preview onboarding second step
  client/additional-methods-setup/upe-preview-methods-selector/add-payment-methods-task.js
  client/additional-methods-setup/upe-preview-methods-selector/index.js
  client/additional-methods-setup/upe-preview-methods-selector/test/add-payment-methods-task.test.js
  client/additional-methods-setup/upe-preview-methods-selector/test/wcpay-settings-fetcher.test.js
  client/additional-methods-setup/upe-preview-methods-selector/wcpay-settings-fetcher.js
Labels: component: grouped-settings, pr: needs review

#2487 Fee discounts should use the discount currency rather than the base fee currency
  changelog.txt
  client/components/account-status/account-fees/expiration-bar.js
  client/components/account-status/account-fees/expiration-description.js
  client/components/account-status/account-fees/index.js
  client/components/account-status/account-fees/test/__snapshots__/index.js.snap
  client/components/account-status/account-fees/test/index.js
  readme.txt
Labels: pr: ready to merge

#2480 Disable payment gateway when not in test mode and not using https or ssl checkout enforcement
  client/overview/index.js
  client/overview/task-list/index.js
  client/overview/task-list/tasks.js
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge

#2425 feat: update multi-currency settings url
  client/additional-methods-setup/upe-preview-methods-selector/setup-complete-task.js
Labels: component: grouped-settings, pr: needs review

#2456 feat: remove non-UPE methods when UPE is disabled
  client/settings/wcpay-upe-toggle/provider.js
  client/settings/wcpay-upe-toggle/test/provider.test.js
Labels: component: grouped-settings, pr: needs review

#2484 feat: payment methods tooltip info
  client/components/payment-methods-checkboxes/payment-method-checkbox.js
  client/components/payment-methods-checkboxes/payment-method-checkbox.scss
  client/components/tooltip/README.md
  client/components/tooltip/index.js
  client/components/tooltip/style.scss
  client/components/tooltip/test/index.test.js
  client/components/tooltip/test/tooltip-base.test.js
  client/components/tooltip/tooltip-base.js
  client/payment-methods-map.js
  client/payment-methods/index.js
  client/settings/payment-methods-selector/index.js
Labels: component: grouped-settings

#2498 fix: onboarding task on account task list disabled
  client/index.js
  client/overview/task-list/tasks.js
  client/overview/task-list/test/tasks.js
Labels: component: grouped-settings, pr: needs review

#2448 feat: add euro when euro payments enabled
  includes/multi-currency/MultiCurrency.php
  includes/multi-currency/PaymentMethodsCompatibility.php
  tests/unit/multi-currency/test-class-payment-methods-compatibility.php
Labels: component: customer multi-currency, component: grouped-settings, pr: needs review

#2462 feat: payment methods selector add currency notice
  client/payment-methods/test/index.js
  client/settings/payment-methods-selector/index.js
  client/settings/payment-methods-selector/test/index.js
Labels: component: grouped-settings, pr: needs review

#2464 feat: add saved cards setting
  client/data/settings/actions.js
  client/data/settings/hooks.js
  client/data/settings/selectors.js
  client/settings/transactions-and-deposits/index.js
  client/settings/transactions-and-deposits/test/index.test.js
  includes/admin/class-wc-rest-payments-settings-controller.php
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
Labels: component: grouped-settings

#2504 fix: test mode flag
  changelog.txt
  includes/admin/class-wc-rest-payments-settings-controller.php
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
Labels: component: grouped-settings

#2369 SCA support for subscription renewals
  changelog.txt
  client/checkout/classic/index.js
  includes/class-wc-payment-gateway-wcpay.php
  includes/compat/subscriptions/class-wc-payments-email-failed-authentication-retry.php
  includes/compat/subscriptions/class-wc-payments-email-failed-renewal-authentication.php
  includes/compat/subscriptions/emails/failed-renewal-authentication-requested.php
  includes/compat/subscriptions/emails/failed-renewal-authentication.php
  includes/compat/subscriptions/emails/plain/failed-renewal-authentication-requested.php
  includes/compat/subscriptions/emails/plain/failed-renewal-authentication.php
  includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php
  psalm-baseline.xml
  readme.txt
Labels: pr: needs review

#2447 Fix flags not displaying for some currencies
  client/multi-currency/enabled-currencies-list/list-item.js
  client/multi-currency/enabled-currencies-list/modal-checkbox.js
  client/multi-currency/enabled-currencies-list/style.scss
  includes/multi-currency/CountryFlags.php
  tests/unit/multi-currency/test-class-country-flags.php
Labels: pr: needs design review, pr: needs review

#2510 fix: UPE opt-in banner flag check
  client/payment-methods/index.js
  client/payment-methods/test/index.js
Labels: component: grouped-settings

#2517 fix: onboarding wizard step
  client/additional-methods-setup/upe-preview-methods-selector/enable-upe-preview-task.js
  client/additional-methods-setup/upe-preview-methods-selector/test/enable-upe-preview-task.test.js
Labels: component: grouped-settings, type: bug

#2508 chore: update UPE preview doc links
  client/additional-methods-setup/upe-preview-methods-selector/add-payment-methods-task.js
  client/additional-methods-setup/upe-preview-methods-selector/enable-upe-preview-task.js
  client/additional-methods-setup/wizard/task-item.scss
Labels: component: grouped-settings

#2360 Display method fees when enabling payment methods
  client/additional-methods-setup/methods-selector/add-payment-methods-task.js
  client/additional-methods-setup/task.js
  client/additional-methods-setup/upe-preview-methods-selector/add-payment-methods-task.js
  client/components/payment-methods-checkboxes/payment-method-checkbox.js
  client/components/payment-methods-checkboxes/test/index.js
  client/settings/payment-methods-selector/index.js
  client/settings/wcpay-settings-context.js
  client/utils/account-fees.js
  client/utils/test/account-fees.js
Labels: pr: needs review

#2470 Add automatic currency switching via geolocation.
  includes/multi-currency/Locale.php
  includes/multi-currency/MultiCurrency.php
  includes/multi-currency/Settings.php
  tests/unit/multi-currency/test-class-locale.php
  tests/unit/multi-currency/test-class-multi-currency.php
Labels: component: customer multi-currency, pr: ready to merge

#2465 feat: enable UPE preview
  changelog.txt
  includes/class-wc-payments-features.php
Labels: component: grouped-settings

#2496 Remove unsupported WC Pay currencies from the available currencies array
  includes/multi-currency/MultiCurrency.php
  tests/unit/multi-currency/test-class-multi-currency.php
Labels: component: customer multi-currency

#2506 Add geolocation automatic currency switch notice
  includes/multi-currency/MultiCurrency.php
  includes/multi-currency/Settings.php
  tests/unit/multi-currency/test-class-multi-currency.php
Labels: component: customer multi-currency, pr: ready to merge

#2453 Unsupported country modal: extend supported countries list
  changelog.txt
  includes/class-wc-payments-utils.php
  readme.txt
Labels: pr: ready to merge

#2539 chore: remove full stop after learn more link
  client/additional-methods-setup/upe-preview-methods-selector/add-payment-methods-task.js
  client/additional-methods-setup/upe-preview-methods-selector/enable-upe-preview-task.js
  client/settings/general-settings/index.js
Labels: component: grouped-settings

#2537 fix: confirmation modal scoll bars
  client/components/confirmation-modal/styles.scss
Labels: component: grouped-settings, pr: needs review

#2540 fix: upe preview task
  client/additional-methods-setup/upe-preview-methods-selector/enable-upe-preview-task.js
Labels: component: grouped-settings

#2541 fix: bottom margin on settings mobile
  client/settings/settings-section.scss
Labels: component: grouped-settings

#2543 fix: wcpay banner logo width
  client/banner/banner.scss
Labels: component: grouped-settings

#2542 fix: pill spacing
  client/additional-methods-setup/upe-preview-methods-selector/enable-upe-preview-task.js
  client/additional-methods-setup/wizard/task-item.scss
  client/components/pill/style.scss
  client/payment-methods/index.js
  client/payment-methods/style.scss
  client/payment-methods/test/index.js
Labels: component: grouped-settings

#2538 Refactor Locale class into Geolocation and Localization Service
  includes/class-wc-payments-localization-service.php
  includes/class-wc-payments.php
  includes/multi-currency/FrontendCurrencies.php
  includes/multi-currency/Geolocation.php
  includes/multi-currency/Locale.php
  includes/multi-currency/MultiCurrency.php
  tests/unit/multi-currency/test-class-frontend-currencies.php
  tests/unit/multi-currency/test-class-geolocation.php
  tests/unit/multi-currency/test-class-locale.php
  tests/unit/multi-currency/test-class-multi-currency.php
  tests/unit/test-class-wc-payments-localization-service.php
Labels: category: refactor, pr: ready to merge

#2516 Fix duplicated currency code on enabled list
  client/multi-currency/enabled-currencies-list/list-item.js
  client/multi-currency/enabled-currencies-list/test/__snapshots__/index.js.snap
Labels: component: customer multi-currency, pr: needs review

#2515 Fix add enabled currencies modal overflow margins
  client/multi-currency/enabled-currencies-list/style.scss
Labels: component: customer multi-currency, pr: needs review

#2553 fix: size of payment methods in modal
  client/components/confirmation-modal/styles.scss
  client/payment-methods/index.js
  client/settings/disable-upe-modal/index.js
  client/settings/disable-upe-modal/style.scss
Labels: component: grouped-settings

#2529 feat: update account data on upgrade
  includes/class-wc-payments.php
  includes/migrations/class-update-service-data-from-server.php
  tests/unit/migrations/test-class-update-service-data-from-server.php
Labels: component: grouped-settings

#2514 Dispatch 'maybe_redirect_to_onboarding' action after onboarding redirection logic in `WC_Payments_Admin`
  changelog.txt
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-account.php
  readme.txt
Labels: pr: needs review

#2569 Format the currency properly in the exchange preview field
  client/multi-currency/index.js
  includes/multi-currency/Settings.php
Labels: component: customer multi-currency, pr: ready to merge

#2574 Adding the `i18n` directory to release.js
  tasks/release.js
Labels: pr: ready to merge

#2476 Fix: Expose error messages in two screens Connect and Overview
  changelog.txt
  client/overview/index.js
  client/overview/test/index.js
  includes/class-wc-payments-account.php
  readme.txt
Labels: pr: ready to merge

#2570 feat: display added payment methods on onboarding
  client/additional-methods-setup/upe-preview-methods-selector/add-payment-methods-task.js
  client/additional-methods-setup/upe-preview-methods-selector/setup-complete-task.js
  client/additional-methods-setup/upe-preview-methods-selector/setup-complete-task.scss
  client/additional-methods-setup/upe-preview-methods-selector/test/add-payment-methods-task.test.js
  client/additional-methods-setup/upe-preview-methods-selector/test/setup-complete-task.test.js
  client/additional-methods-setup/wizard/task-item.scss
  client/settings/payment-method-icon/index.js
Labels: pr: needs review

#2489 Update - Allow viewing Stripe account details only in page Overview.
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  readme.txt
Labels: pr: ready to merge

#2564 fix: settings cards spacing
  client/payment-methods/index.js
  client/settings/card-body/styles.scss
Labels: pr: needs review

#2551 refactor: replace survey notices with Gutenberg
  client/additional-methods-setup/upe-preview-methods-selector/test/add-payment-methods-task.test.js
  client/components/currency-information-for-methods/index.js
  client/components/currency-information-for-methods/styles.scss
  client/components/currency-information-for-methods/test/index.test.js
  client/components/inline-notice/index.js
  client/components/inline-notice/style.scss
  client/settings/disable-upe-modal/index.js
  client/settings/disable-upe-modal/style.scss
  client/settings/survey-modal/index.js
  client/settings/survey-modal/style.scss
Labels: component: grouped-settings

#2552 Enable customer multi-currency for all merchants
  changelog.txt
  includes/class-wc-payments-features.php
  readme.txt
  tests/unit/bootstrap.php
  tests/unit/test-class-wc-payments-features.php
Labels: pr: ready to merge

#2579 Fix currency switcher settings not being saved
  includes/multi-currency/CurrencySwitcherWidget.php
Labels: pr: ready to merge

#2590 Store Stripe exchange rate after a purchase
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  tests/unit/payment-methods/test-class-giropay-payment-gateway.php
  tests/unit/payment-methods/test-class-sepa-payment-gateway.php
  tests/unit/payment-methods/test-class-sofort-payment-gateway.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
Labels: pr: needs review

#2558 Disable gateway when the currency is not supported in the country account
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge

#2583 refactor: payment method name consistency
  client/additional-methods-setup/methods-selector/test/add-payment-methods-task.test.js
  client/additional-methods-setup/upe-preview-methods-selector/test/add-payment-methods-task.test.js
  client/settings/payment-method-icon/index.js
  client/settings/payment-method-icon/style.scss
  client/settings/payment-method-icon/test/index.js
  client/settings/payment-methods-selector/test/index.js
Labels: component: grouped-settings, pr: needs review

#2568 refactor: UPE opt-in messages visibility
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-upe-flag-toggle-controller.php
  includes/class-wc-payments-features.php
  includes/notes/class-wc-payments-notes-additional-payment-methods.php
  tests/unit/admin/test-class-wc-rest-upe-flag-toggle-controller.php
Labels: pr: needs review

#2503 Use expired cached rate data on server error
  includes/multi-currency/MultiCurrency.php
  tests/unit/multi-currency/test-class-multi-currency.php
Labels: pr: ready to merge

#2593 Bump Required Versions for 2.8 Release
  changelog.txt
  phpcs.xml.dist
  readme.txt
  woocommerce-payments.php
Labels: pr: ready to merge

#2572 Stop refund process when using an invalid amount
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  readme.txt
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge

#2587 chore: update UPE doc links
  client/payment-methods/index.js
  includes/notes/class-wc-payments-notes-additional-payment-methods.php
  tests/unit/notes/test-class-wc-payments-notes-additional-payment-methods.php
Labels: component: grouped-settings

#2559 Send the "off_session" parameter as a string instead of a boolean.
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: needs review

#2471 Storefront integration for Multi-Currency
  includes/multi-currency/MultiCurrency.php
  includes/multi-currency/Settings.php
  includes/multi-currency/StorefrontIntegration.php
  tests/unit/multi-currency/test-class-multi-currency.php
  tests/unit/multi-currency/test-class-storefront-integration.php
Labels: component: customer multi-currency, pr: ready to merge

#2395 Add currency suffixes to key prices
  client/deposits/details/index.js
  client/deposits/details/test/__snapshots__/index.js.snap
  client/deposits/instant-deposits/modal.js
  client/deposits/instant-deposits/test/__snapshots__/index.js.snap
  client/deposits/list/index.js
  client/deposits/list/test/__snapshots__/index.js.snap
  client/disputes/details/test/__snapshots__/index.js.snap
  client/disputes/evidence/test/__snapshots__/index.js.snap
  client/disputes/index.js
  client/disputes/info/index.js
  client/disputes/info/test/__snapshots__/index.js.snap
  client/disputes/test/__snapshots__/index.js.snap
  client/payment-details/summary/index.js
  client/payment-details/summary/test/__snapshots__/index.js.snap
  client/payment-details/timeline/map-events.js
  client/payment-details/timeline/test/__snapshots__/index.js.snap
  client/payment-details/timeline/test/__snapshots__/map-events.js.snap
  client/transactions/list/converted-amount.tsx
  client/transactions/list/index.tsx
  client/transactions/list/test/__snapshots__/converted-amount.tsx.snap
  client/transactions/list/test/__snapshots__/index.tsx.snap
  client/utils/currency/index.js
  client/utils/currency/test/index.js
  includes/class-wc-payments-explicit-price-formatter.php
  includes/class-wc-payments.php
  includes/multi-currency/BackendCurrencies.php
  includes/multi-currency/MultiCurrency.php
  tests/e2e/specs/merchant/merchant-subscriptions-purchase-no-sign-up.spec.js
  tests/e2e/specs/merchant/merchant-subscriptions-purchase-sign-up-fee.spec.js
  tests/unit/multi-currency/test-class-backend-currencies.php
  tests/unit/test-class-wc-payments-explicit-price-formatter.php
Labels: component: customer multi-currency, pr: needs review

#2533 Do not redirect to the onboarding page when account retrieval fails.
  changelog.txt
  includes/admin/class-wc-payments-admin.php
  readme.txt
Labels: pr: ready to merge

#2611 Bump wcpay_empty_state_preview_mode Version
  client/deposits/index.js
  client/transactions/index.tsx
  includes/admin/class-wc-payments-admin.php
Labels: pr: needs review

#2500 Add fee breakdown in payments timeline.
  changelog.txt
  client/payment-details/timeline/index.js
  client/payment-details/timeline/map-events.js
  client/payment-details/timeline/style.scss
  client/payment-details/timeline/test/__snapshots__/index.js.snap
  client/payment-details/timeline/test/__snapshots__/map-events.js.snap
  client/payment-details/timeline/test/map-events.js
  readme.txt
Labels: pr: ready to merge

#2613 Update the copy on the Multi-Currency page
  includes/multi-currency/Settings.php
Labels: component: customer multi-currency, pr: ready to merge

#2554 Add urls for the link to the documentation page
  includes/multi-currency/Settings.php
Labels: component: customer multi-currency, pr: ready to merge

#2501 Add REST API to create customer given an order.
  changelog.txt
  includes/admin/class-wc-rest-payments-orders-controller.php
  includes/class-wc-payments.php
  readme.txt
  tests/unit/admin/test-class-wc-rest-payments-orders-controller.php
Labels: pr: ready to merge

#2594 refactor: add webpack root alias
  client/components/deposits-information/declarations.d.ts
  client/components/deposits-information/index.tsx
  client/components/deposits-information/test/index.js
  client/data/index.ts
  client/deposits/details/index.js
  client/deposits/details/test/index.js
  client/deposits/instant-deposits/index.js
  client/deposits/instant-deposits/test/index.js
  client/deposits/list/index.js
  client/deposits/list/test/index.js
  client/disputes/details/index.js
  client/disputes/details/test/index.js
  client/disputes/evidence/index.js
  client/disputes/evidence/test/index.js
  client/disputes/index.js
  client/disputes/test/index.js
  client/multi-currency/enabled-currencies-list/index.js
  client/multi-currency/enabled-currencies-list/modal.js
  client/multi-currency/enabled-currencies-list/test/index.js
  client/payment-details/timeline/index.js
  client/payment-details/timeline/test/index.js
  client/payment-gateways/payment-gateways-confirmation.js
  client/payment-methods/index.js
  client/payment-methods/test/index.js
  client/settings/advanced-settings/debug-mode.js
  client/settings/advanced-settings/test/debug-mode.test.js
  client/settings/general-settings/index.js
  client/settings/general-settings/test/general-settings.test.js
  client/settings/payment-methods-selector/index.js
  client/settings/payment-methods-selector/test/index.js
  client/settings/payment-request/index.js
  client/settings/payment-request/test/index.test.js
  client/settings/transactions-and-deposits/test/index.test.js
  tests/js/jest.config.js
  tsconfig.json
  webpack.config.js
Labels: pr: needs review

#2618 Use explicit format when printing amounts in the order notes
  includes/admin/class-wc-rest-payments-webhook-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php
  includes/payment-methods/class-giropay-payment-gateway.php
  includes/payment-methods/class-sofort-payment-gateway.php
  tests/e2e/specs/merchant/merchant-orders-full-refund.spec.js
  tests/unit/admin/test-class-wc-rest-payments-webhook.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
Labels: component: customer multi-currency, pr: ready to merge

#2622 Fix/2621 enqueue admin assets when needed
  includes/multi-currency/MultiCurrency.php
Labels: component: customer multi-currency, pr: needs review

#2620 Fix checkout not working for 3DS cards and saving exchange rate
  includes/class-wc-payment-gateway-wcpay.php
  includes/payment-methods/class-upe-payment-gateway.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: component: customer multi-currency, pr: ready to merge
