Repository Automattic/woocommerce-payments, pull requests merged in 2022-08, with the labels that each got.

#4495 Make updating existing customer details during checkout async
  changelog/update-manage-customer-details-async
  includes/class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php
Labels: pr: ready to merge

#4497 Update function call and declarations to remove unused arguments and parameters
  changelog/update-remove-unused-function-arguments
  includes/admin/class-wc-rest-payments-orders-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-order-service.php
  tests/unit/test-class-wc-payments-order-service.php
Labels: pr: ready to merge

#4496 Sanitize option key for subscription
  changelog/'Sanitize option key for subscription'
  includes/subscriptions/class-wc-payments-product-service.php
  tests/unit/subscriptions/test-class-wc-payments-product-service.php
Labels: pr: ready to merge, component: order details, component: wcpay subscriptions, category: core

#4507 Fix StripeLink + WooCommerce Blocks issues
  changelog/fix-stripe-link-woo-blocks
  client/checkout/blocks/upe-fields.js
Labels: pr: ready to merge

#4533 Avoid execution context errors for E2E tests
  changelog/dev-fix-e2e-tests-execution-context-errors
  tests/e2e/utils/payments.js
Labels: pr: ready to merge

#4442 Avoid saving a session cookie when the currency is changed because of geolocation
  changelog/fix-3761-multicurrency-geolocation-cookie
  includes/multi-currency/MultiCurrency.php
  includes/multi-currency/Utils.php
  tests/unit/multi-currency/test-class-multi-currency.php
Labels: pr: ready to merge

#4527 Add thousand separator to the transactions count
  changelog/fix-page-result-count-formatting
  client/transactions/list/index.tsx
  package-lock.json
  package.json
Labels: pr: ready to merge

#4549 E2E GitHub Workflow: Re-run Failed Test Files.
  .github/workflows/e2e-test.yml
  changelog/dev-e2e-retry-failed-test-files
Labels: pr: needs review

#4558 Include subscriptions plugin status in WooPay store data
  changelog/add-woopay-subscriptions-store-data
  includes/class-wc-payments.php
Labels: pr: needs review, component: wcpay subscriptions

#4541 Fix how we detect if WCS is installed via WP CLI
  changelog/fix-init-subscriptions-core-when-wp-cli-has-arguments
  woocommerce-payments.php
Labels: pr: ready to merge

#4576 Move the applyThousandSeparator method to utils
  changelog/update-move-applyThousandSeparator-method-to-client-utils
  client/deposits/list/index.tsx
  client/disputes/index.tsx
  client/transactions/list/index.tsx
  client/utils/index.js
Labels: pr: needs review

#4516 Remove Charge request from Transaction Details page
  changelog/update-353-charge
  client/data/payment-intents/hooks.ts
  client/data/payment-intents/test/hooks.ts
  client/data/payment-intents/test/resolvers.ts
  client/data/payment-intents/test/selectors.ts
  client/payment-details/summary/test/index.tsx
  client/payment-details/test/index.tsx
  client/style.scss
  client/transactions/list/index.tsx
  client/transactions/list/test/__snapshots__/index.tsx.snap
  client/types/charges.d.ts
  client/types/payment-intents.d.ts
  client/utils/charge/index.ts
  includes/admin/class-wc-rest-payments-charges-controller.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  includes/wc-payment-api/models/class-wc-payments-api-charge.php
Labels: pr: ready to merge

#4448 Bump NodeJS to version 14
  .nvmrc
  changelog/dev-3849-update-node-version
Labels: pr: needs review

#4544 Analytics: Ensure the store default currency always displays in list
  changelog/fix-4479-ensure-default-currency-is-always-shown-in-analytics
  includes/multi-currency/Analytics.php
  tests/unit/multi-currency/test-class-analytics.php
Labels: pr: ready to merge

#4595 Fix charge id validation for UPE transactions
  changelog/fix-upe-charge-id
  client/data/payment-intents/hooks.ts
Labels: pr: ready to merge

#4500 Supporting changes for WooPay Trial Subscriptions
  changelog/indicate-setup-intent-use
  includes/class-wc-payment-gateway-wcpay.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: component: platform checkout

#4590 Refactoring Direct DB query in order_id_from_meta_key_value()
  changelog/fix-4151-order_id_from_meta_key_value
  includes/class-wc-payments-db.php
Labels: pr: ready to merge

#4598 Refactoring Direct DB query in orders_with_charge_id_from_charge_ids
  changelog/fix-4151-orders_with_charge_id_from_charge_ids
  includes/class-wc-payments-db.php
  tests/unit/test-class-wc-payments-db.php
Labels: pr: ready to merge

#4588 Move the Instant deposit button into the available balance block
  changelog/issue-4484-move-instant-deposit-button
  client/components/deposits-information/index.tsx
  client/components/deposits-information/test/__snapshots__/index.js.snap
Labels: pr: ready to merge

#4608 Use customer from session during Store API checkout
  changelog/fix-4607-guest-woopay-subscription-checkout
  includes/class-wc-payments-customer-service.php
Labels: pr: needs review, component: platform checkout, component: wc subscriptions integration

#4551 Fix errors for apple pay registration
  changelog/fix-4511-apple-pay-registration
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-apple-pay-registration.php
  includes/class-wc-payments-utils.php
Labels: pr: needs review

#4589 Fix Link errors after update
  changelog/4532-fix-stripelink-errors
  client/checkout/blocks/upe-fields.js
  client/checkout/classic/upe.js
  client/checkout/stripe-link/index.js
Labels: pr: needs review

#4634 Only offer WooPay when cart needs payment
  changelog/update-woopay-cart-needs-no-payment
  includes/class-wc-payment-gateway-wcpay.php
Labels: component: platform checkout

#4542 Remove duplication of deposit schedule
  changelog/fix-4453_deposit_status_deduplication
  client/account-status-settings/test/__snapshots__/index.js.snap
  client/components/account-status/test/__snapshots__/index.js.snap
  client/components/deposits-status/index.js
  client/components/deposits-status/test/__snapshots__/index.js.snap
Labels: pr: ready to merge

#4647 Add check for guest users while updating customer with order data
  changelog/fix-4639-fallback-guest-user
  includes/class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge

#4525 Show the "Temporarily Suspended" notice only when deposits are "blocked"
  changelog/update-4452-suspended-notice-only-when-deposits_status-blocked
  client/account-status-settings/index.js
  client/account-status-settings/test/__snapshots__/index.js.snap
  client/account-status-settings/test/index.js
  client/components/account-status/index.js
  client/components/account-status/test/index.js
  client/components/deposits-information/declarations.d.ts
  client/components/deposits-status/index.js
  client/components/deposits-status/test/__snapshots__/index.js.snap
  client/components/deposits-status/test/index.js
  client/deposits/utils/index.js
  client/deposits/utils/test/index.js
  client/globals.d.ts
  client/overview/test/index.js
  includes/class-wc-payments-account.php
  includes/class-wc-payments-features.php
  tests/unit/test-class-wc-payments-features.php
Labels: pr: ready to merge, component: deposits, component: accounts, category: refactor

#4625 Add intent order_id validation check in IPP capture endpoint
  changelog/fix-4556-ipp-harden-intent-validation
  includes/admin/class-wc-rest-payments-orders-controller.php
  tests/unit/admin/test-class-wc-rest-payments-orders-controller.php
Labels: pr: ready to merge, component: card present

#4641 Fix error while changing payment method of subscription product
  changelog/fix-3924-update-subscription-multiple-cards
  includes/class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php
Labels: pr: ready to merge, component: saved cards and subscriptions, category: core

#4658 E2E - Add for workflow for Pull Requests, split existing workflow & introduce composite actions
  .github/actions/e2e/env-setup/action.yml
  .github/actions/e2e/run-log-tests/action.yml
  .github/workflows/e2e-pull-request.yml
  .github/workflows/e2e-test.yml
  changelog/e2e-pr-workflow-composite-actions
Labels: pr: ready to merge, category: e2e, category: devops

#4633 Removed an unnecessary `$order->save()`, called with outdated data.
  changelog/fix-order-status-after-lost-dispute
  includes/class-wc-payments-order-service.php
Labels: pr: needs review

#4648 If COT enabled, use COT query to gather tracking data
  changelog/update-4148-refactor-db-query-tracking
  includes/multi-currency/Tracking.php
Labels: pr: ready to merge
