Repository Automattic/woocommerce-payments, pull requests merged in 2022-09, with the labels that each got.

#4662 Inbox notes: actualize FAQ link for 'Set up refund policy' note
  changelog/fix-notes-refund-policy-link
  includes/notes/class-wc-payments-notes-set-up-refund-policy.php
Labels: pr: ready to merge

#4661 When COT enabled, use COT query for customer currencies query
  changelog/update-4148-refactor-db-query-get-currencies
  includes/multi-currency/MultiCurrency.php
Labels: pr: needs review

#4626 Dismissible message for applepay error
  changelog/fix-4610-dismissible-error-message-applepay
  includes/class-wc-payment-gateway-wcpay.php
Labels: pr: needs review

#4643 Update subscriptions-core to 2.2.1
  changelog/subscriptions-core-2.2.1
  changelog/subscriptions-core-2.2.1-fix
  composer.json
  composer.lock
Labels: pr: ready to merge

#4656 Merchants can change their deposit schedule
  changelog/add-4464-merchants-can-change-deposit-schedule
  client/data/settings/actions.js
  client/data/settings/hooks.js
  client/data/settings/selectors.js
  client/deposits/utils/index.js
  client/deposits/utils/test/index.js
  client/settings/deposits/index.js
  client/settings/deposits/style.scss
  client/settings/deposits/test/index.test.js
  client/settings/settings-manager/index.js
  client/settings/transactions/index.js
  client/settings/transactions/manual-capture-control.js
  client/settings/transactions/style.scss
  client/settings/transactions/test/index.test.js
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  psalm-baseline.xml
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
Labels: pr: needs review

#4649 Payment Requests: Fix variations without price, sign-up fee taxes, and variable subscriptions with sign-up taxes
  changelog/fix-4579-fatal-variation-errors
  client/payment-request/index.js
  includes/class-wc-payments-payment-request-button-handler.php
  includes/class-wc-payments.php
  includes/exceptions/class-invalid-price-exception.php
  tests/unit/helpers/class-wc-helper-subscriptions-product.php
  tests/unit/test-class-wc-payments-payment-request-button-handler.php
Labels: pr: ready to merge

#4677 Refactor the SQL query modifications in Analytics
  changelog/cot-4632-analytics-meta-queries
  includes/multi-currency/Analytics.php
  tests/unit/multi-currency/test-class-analytics.php
Labels: pr: needs review

#4657 E2E subscription tests - Fix timeouts & optimize flow
  changelog/e2e-update-subscription-test-flows
  package-lock.json
  package.json
  tests/e2e/config/test.json
  tests/e2e/env/setup.sh
  tests/e2e/env/wc-subscription-products.xml
  tests/e2e/specs/subscriptions/merchant/merchant-subscriptions-renew-action-scheduler.spec.js
  tests/e2e/specs/subscriptions/merchant/merchant-subscriptions-renew-subscription.spec.js
  tests/e2e/specs/subscriptions/merchant/merchant-subscriptions-settings.spec.js
  tests/e2e/specs/subscriptions/shopper/shopper-myaccount-renew-subscription.spec.js
  tests/e2e/specs/subscriptions/shopper/shopper-subscriptions-change-payment-method.spec.js
  tests/e2e/specs/subscriptions/shopper/shopper-subscriptions-free-trial.spec.js
  tests/e2e/specs/subscriptions/shopper/shopper-subscriptions-manage-payments.spec.js
  tests/e2e/specs/subscriptions/shopper/shopper-subscriptions-purchase-free-trial.spec.js
  tests/e2e/specs/subscriptions/shopper/shopper-subscriptions-purchase-multiple-subscriptions.spec.js
  tests/e2e/specs/subscriptions/shopper/shopper-subscriptions-purchase-no-sign-up-fee.spec.js
  tests/e2e/specs/subscriptions/shopper/shopper-subscriptions-purchase-sign-up-fee.spec.js
  tests/e2e/specs/subscriptions/shopper/shopper-subscriptions-purchase-subscription-product.spec.js
  tests/e2e/utils/flows.js
Labels: pr: needs review, category: e2e, category: devops

#4694 Ensure get_deposit_schedule_monthly_anchor() returns an int or null.
  changelog/fix-4656-rest-invalid-param
  includes/class-wc-payments-account.php
Labels: pr: needs review

#4700 Removing unnecessary check against server response
  changelog/fix-4699-remove-unneeded-key-check
  includes/class-wc-payments-account.php
Labels: pr: ready to merge

#4693 Minor readability improvements
  changelog/fix-minor-readability-change-in-test
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php
Labels: pr: needs author reply, priority: low, component: tests

#4697 Calculate the shipping price correctly when using MultiCurrency and Table Rate Shipping
  changelog/fix-4609-table-rate-shipping-wrong-rate-calculated
  includes/multi-currency/FrontendPrices.php
  tests/unit/multi-currency/test-class-frontend-prices.php
Labels: pr: ready to merge

#4711 Format date filters for transactions listing as per timezone
  changelog/add-2275-timezone-formatting-transactions
  client/data/transactions/resolvers.js
  client/data/transactions/test/resolvers.js
  client/transactions/list/test/index.tsx
  includes/admin/class-wc-rest-payments-transactions-controller.php
Labels: pr: ready to merge

#4713 Retain test mode context in CRON jobs queued up while checking out
  changelog/fix-1257-test-data-leaking-to-live
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-order-service.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
Labels: type: bug

#4705 Hide Link payment method for non-us accounts
  changelog/fix-4668-stripelink-non-us-accounts
  includes/payment-methods/class-upe-payment-gateway.php
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
Labels: pr: ready to merge

#4704 Fix email notification error with StripeLink button code
  changelog/fix-4675-stripelink-notification
  includes/class-wc-payment-gateway-wcpay.php
Labels: type: bug, pr: needs author reply, component: stripe link

#4726 Fix Apple Pay verify domain waring notice showing up constantly
  changelog/fix-4712-apple-pay-incorrect-admin-notice
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-apple-pay-registration.php
  includes/class-wc-payments-utils.php
Labels: pr: ready to merge

#4756 Hide checkout modal button when StripeLink is disabled.
  changelog/fix-4755-stripelink-button-showing-when-disabled
  includes/class-wc-payment-gateway-wcpay.php
Labels: type: bug, pr: ready to merge, component: stripe link

#4761 Apply timezone formatting only in case client provides user timezone
  changelog/update-timezone-check-client
  includes/admin/class-wc-rest-payments-transactions-controller.php
Labels: pr: ready to merge

#4683 Stripe Link: Pre-fill first and last names on checkout
  changelog/add-4512-link-prefill-first-last-name
  client/checkout/blocks/upe-fields.js
  client/checkout/classic/upe.js
  client/checkout/stripe-link/index.js
Labels: pr: ready to merge

#4751 Bump WC versions for 4.8.0 release
  .github/workflows/compatibility.yml
  .github/workflows/e2e-test.yml
  changelog/dev-bump-versions-4-8-0
  woocommerce-payments.php
Labels: pr: needs review

#4707 Pass down the feature flag parameter for the task list in Payments > Overview
  changelog/fix-4471-some-tasks-missing-in-payments-overview-task-list
  client/index.js
  client/overview/index.js
  client/overview/task-list/tasks.js
  client/overview/task-list/test/tasks.js
  includes/admin/class-wc-payments-admin.php
  includes/notes/class-wc-payments-notes-set-https-for-checkout.php
Labels: pr: ready to merge

#4659 Remove beta headers from stripe requests
  changelog/add-4514-remove-beta-headers
  client/checkout/api/index.js
Labels: pr: ready to merge

#4790 Exit before processing a scheduled subscription payment for WCPay Subscriptions
  changelog/issue-4788
  includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php
  tests/unit/test-class-wc-payment-gateway-wcpay-payment-types.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php
Labels: pr: ready to merge, component: wcpay subscriptions

#4637 Add bundle size check to PR's
  .github/workflows/bundle-size.yml
  changelog/add-4619-add-bundle-size-check
Labels: pr: ready to merge, category: devops

#4787 Allow subscription processing via WooPay
  changelog/add-woopay-subscription-processing
  includes/class-wc-payments-features.php
  includes/platform-checkout/class-platform-checkout-utilities.php
  tests/unit/platform-checkout/test-class-platform-checkout-utilities.php
Labels: pr: needs review

#4741 Limit level 3 product code within 12 digits
  changelog/fix-4411-product-id-data-level3-error
  includes/class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: type: bug, pr: ready to merge, component: checkout, category: core

#4725 Update node to v16 (LTS) and npm to v8
  .npmrc
  .nvmrc
  changelog/update-node-16-and-npm-8
  client/connect-account-page-experiment/treatment/test/index.js
  client/connect-account-page/test/index.js
  client/data/disputes/test/actions.js
  package-lock.json
  package.json
  tests/e2e/README.md
  tests/e2e/config/jest-puppeteer.config.js
Labels: pr: needs review

#4780 Limit product_code in Level3 data shipping-only order within 12 characters
  changelog/fix-4738-level3-shipping-order-error
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: type: bug, pr: ready to merge, component: checkout, category: core

#4800 Remove GH token to change comment author
  .github/workflows/bundle-size.yml
  changelog/Remove GH token to change comment author for bundle size check
Labels: pr: needs review

#4808 Fix Node version in Platform Checkout workflow
  .github/workflows/platform-checkout-test-site-sync.yml
  changelog/fix-platform-checkout-workflow
Labels: pr: needs review, category: devops
