Repository Automattic/woocommerce-payments, pull requests merged in 2022-04, with the labels that each got.

#4014 Custom email receipt for terminal card reader
  changelog/add-3558-custom-email-receipt-for-terminal-card-reader
  includes/class-wc-payments-webhook-processing-service.php
  includes/class-wc-payments.php
  includes/emails/class-wc-payments-email-ipp-receipt.php
  includes/in-person-payments/class-wc-payments-in-person-payments-receipts-service.php
  templates/emails/customer-ipp-receipt.php
  templates/emails/email-ipp-receipt-compliance-details.php
  templates/emails/email-ipp-receipt-store-details.php
  templates/emails/plain/customer-ipp-receipt.php
  templates/emails/plain/email-ipp-receipt-compliance-details.php
  templates/emails/plain/email-ipp-receipt-store-details.php
  tests/unit/in-person-payments/test-class-wc-payments-in-person-payments-receipts-service.php
  tests/unit/test-class-wc-payments-webhook-processing-service.php
Labels: pr: ready to merge

#4057 Fix preview print receipt functionality
  changelog/fix-4056-preview-print-receipt-functionality
  client/card-readers/preview-receipt/receipt.tsx
Labels: pr: ready to merge

#4067 Remove _wcpay_feature_card_readers flag
  changelog/add-3512-remove-the-feature-flag-_wcpay_feature_card_readers
  includes/admin/class-wc-payments-admin.php
Labels: pr: ready to merge

#4072 Remove isBrandingEnabled feature flag
  changelog/fix-remove-card-reader-settings-branding-feature-flag
  client/card-readers/settings/index.tsx
Labels: pr: ready to merge

#4051 Check for platform checkout eligibility before customer is redirected
  changelog/update-fetch-platform-checkout-eligibility
  client/checkout/platform-checkout/email-input-iframe.js
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: component: platform checkout

#4055 Link the Requirements Component with the form
  client/data/onboarding/action-types.ts
  client/data/onboarding/actions.ts
  client/data/onboarding/hooks.ts
  client/data/onboarding/reducer.ts
  client/data/onboarding/resolvers.ts
  client/data/onboarding/selectors.ts
  client/data/onboarding/types.d.ts
  client/onboarding/index.scss
  client/onboarding/strings.js
  client/onboarding/tasks/add-business-info-task/index.js
  client/onboarding/tasks/add-business-info-task/required-verification-info.js
  client/onboarding/tasks/add-business-info-task/test/__snapshots__/index.js.snap
  client/onboarding/tasks/add-business-info-task/test/__snapshots__/required-verification-info.js.snap
  client/onboarding/tasks/add-business-info-task/test/required-verification-info.js
  includes/admin/class-wc-rest-payments-onboarding-controller.php
  includes/class-wc-payments-onboarding-service.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/admin/test-class-wc-rest-payments-onboarding-controller.php
  tests/unit/test-class-wc-payments-onboarding-service.php
Labels: pr: ready to merge

#3989 Check for file access in domain verification before throwing a warning
  changelog/fix-3899
  includes/class-wc-payments-apple-pay-registration.php
Labels: [Type] Bug

#4086 Update subscriptions-core to `1.8.0`
  changelog/subscriptions-core-1.8.0
  composer.json
  composer.lock
Labels: pr: needs review

#4061 Add handling for server export for disputes CSV download
  changelog/update-3846-disputes-csv-export
  client/data/disputes/resolvers.js
  client/disputes/index.tsx
  client/disputes/test/index.tsx
  includes/admin/class-wc-rest-payments-disputes-controller.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: needs review

#4074 Track document downloaded events
  changelog/add-1791-documents-usage-tracking
  includes/admin/class-wc-rest-payments-documents-controller.php
Labels: pr: ready to merge, component: invoices for processing fees

#4085 Payment Request Button - Do not set WC session cookie and HTML container on the product page if not enabled
  changelog/fix-4084-prb-caching-product-page
  includes/class-wc-payments-payment-request-button-handler.php
Labels: pr: ready to merge

#4093 Fix generate receipt preview in FF
  changelog/fix-4070-card-readers-preview-print-receipt-fails-on-firefox
  client/card-readers/preview-receipt/previewer.tsx
  client/card-readers/preview-receipt/test/__snapshots__/preview-receipt.test.tsx.snap
  client/card-readers/preview-receipt/test/__snapshots__/printed-receipt-previewer.test.tsx.snap
  client/card-readers/preview-receipt/test/printed-receipt-previewer.test.tsx
Labels: pr: needs review

#4089 Fix placeholder injection problem in New Receipt email
  changelog/fix-4071-text-placeholders-not-working-on-in-person-payment-receipt-email
  includes/emails/class-wc-payments-email-ipp-receipt.php
Labels: pr: needs review

#4099 Fix linter warnings in DepositsList
  changelog/fix-linter-warnings-in-depositslist
  client/deposits/list/index.tsx
Labels: pr: needs review, type: developer experience

#4097 Record event for registration for platform checkout
  changelog/update-3905-track-platform-checkout-registration
  includes/class-platform-checkout-tracker.php
  includes/class-wc-payment-gateway-wcpay.php
Labels: component: platform checkout

#4047 Add data fingerprinting for fraud prevention in intent creation/update
  changelog/add-data-fingerprinting
  includes/class-wc-payments.php
  includes/fraud-prevention/class-buyer-fingerprinting-service.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/fraud-prevention/test-class-buyer-fingerprinting-service.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: needs author reply

#4096 New onboarding flow refactor
  client/additional-methods-setup/wizard/task/context.ts
  client/components/custom-select-control/index.tsx
  client/components/custom-select-control/test/index.tsx
  client/data/onboarding/action-types.ts
  client/data/onboarding/actions.ts
  client/data/onboarding/hooks.ts
  client/data/onboarding/index.ts
  client/data/onboarding/reducer.ts
  client/data/onboarding/resolvers.ts
  client/data/onboarding/selectors.ts
  client/data/onboarding/types.d.ts
  client/data/store.js
  client/hooks/use-api-fetch.ts
  client/onboarding/hooks.ts
  client/onboarding/index.tsx
  client/onboarding/requirements/index.tsx
  client/onboarding/strings.ts
  client/onboarding/style.scss
  client/onboarding/tasks/add-business-info-task/index.tsx
  client/onboarding/tasks/add-business-info-task/required-verification-info.tsx
  client/onboarding/tasks/add-business-info-task/test/__snapshots__/index.tsx.snap
  client/onboarding/tasks/add-business-info-task/test/__snapshots__/required-verification-info.tsx.snap
  client/onboarding/tasks/add-business-info-task/test/index.tsx
  client/onboarding/tasks/add-business-info-task/test/required-verification-info.tsx
  client/onboarding/tasks/setup-complete-task/index.tsx
  client/onboarding/tasks/setup-complete-task/test/__snapshots__/index.tsx.snap
  client/onboarding/tasks/setup-complete-task/test/index.tsx
  client/onboarding/test/__snapshots__/index.tsx.snap
  client/onboarding/test/index.tsx
  client/onboarding/types.d.ts
  webpack.config.js
Labels: pr: needs review

#4091 KYC New onboarding flow experiment
  changelog/add-new-onboarding-flow
  client/additional-methods-setup/wizard/task/context.ts
  client/components/custom-select-control/index.tsx
  client/components/custom-select-control/style.scss
  client/components/custom-select-control/test/__snapshots__/index.tsx.snap
  client/components/custom-select-control/test/index.tsx
  client/data/store.js
  client/hooks/use-api-fetch.ts
  client/index.js
  client/onboarding/hooks.ts
  client/onboarding/index.tsx
  client/onboarding/requirements/company.tsx
  client/onboarding/requirements/group.tsx
  client/onboarding/requirements/index.tsx
  client/onboarding/requirements/individual.tsx
  client/onboarding/requirements/keymap.tsx
  client/onboarding/requirements/strings.tsx
  client/onboarding/requirements/style.scss
  client/onboarding/requirements/test/__snapshots__/company.tsx.snap
  client/onboarding/requirements/test/__snapshots__/individual.tsx.snap
  client/onboarding/requirements/test/company.tsx
  client/onboarding/requirements/test/individual.tsx
  client/onboarding/requirements/test/keymap.tsx
  client/onboarding/strings.ts
  client/onboarding/style.scss
  client/onboarding/tasks/add-business-info-task/index.tsx
  client/onboarding/tasks/add-business-info-task/required-verification-info.tsx
  client/onboarding/tasks/add-business-info-task/test/__snapshots__/index.tsx.snap
  client/onboarding/tasks/add-business-info-task/test/__snapshots__/required-verification-info.tsx.snap
  client/onboarding/tasks/add-business-info-task/test/index.tsx
  client/onboarding/tasks/add-business-info-task/test/required-verification-info.tsx
  client/onboarding/tasks/setup-complete-task/index.tsx
  client/onboarding/tasks/setup-complete-task/test/__snapshots__/index.tsx.snap
  client/onboarding/tasks/setup-complete-task/test/index.tsx
  client/onboarding/test/__snapshots__/index.tsx.snap
  client/onboarding/test/index.tsx
  client/onboarding/translations/descriptions.tsx
  client/onboarding/translations/structures.tsx
  client/onboarding/translations/types.tsx
  client/onboarding/types.d.ts
  client/utils/strings.tsx
  client/utils/test/strings.tsx
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-onboarding-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-onboarding-service.php
  includes/class-wc-payments-utils.php
  includes/class-wc-payments.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  package-lock.json
  tests/unit/admin/test-class-wc-rest-payments-onboarding-controller.php
  tests/unit/bootstrap.php
  tests/unit/test-class-wc-payments-onboarding-service.php
  webpack.config.js
Labels: pr: needs review

#4107 WooPay naming/styling updates
  changelog/update-woopay-strings
  client/checkout/platform-checkout/email-input-iframe.js
  client/components/platform-checkout/icons/lock-icon/icon.svg
  client/components/platform-checkout/icons/lock-icon/index.js
  client/components/platform-checkout/icons/lock.js
  client/components/platform-checkout/icons/phone-icon/icon.svg
  client/components/platform-checkout/icons/phone-icon/index.js
  client/components/platform-checkout/icons/phone.js
  client/components/platform-checkout/save-user/about-platform-checkout.js
  client/components/platform-checkout/save-user/additional-information.js
  client/components/platform-checkout/save-user/agreement.js
  client/components/platform-checkout/save-user/checkout-page-save-user.js
  client/components/platform-checkout/save-user/style.scss
  client/components/platform-checkout/save-user/test/checkout-page-save-user.test.js
  client/gateway-icons/woo.js
  client/settings/express-checkout-settings/index.js
  client/settings/express-checkout-settings/platform-checkout-settings.js
  client/settings/express-checkout-settings/test/index.js
  client/settings/express-checkout-settings/test/platform-checkout-settings.test.js
  client/settings/express-checkout/index.js
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-blocks-payment-method.php
  includes/class-wc-payments.php
Labels: pr: needs review, component: platform checkout

#4112 Add usage notice to platform checkout setting
  changelog/add-platform-checkout-tos-notice
  client/settings/express-checkout/index.js
Labels: pr: needs review, component: platform checkout

#4066 Prevent platform checkout iframe appear when go back
  changelog/fix-4065-prevent-platform-checkout-iframe-appear-when-go-back
  client/checkout/platform-checkout/email-input-iframe.js
Labels: component: platform checkout

#3903 Avoid checking jetpack_tos_agreed flag in platform-checkout tracking
  changelog/update-tracking-conditions
  includes/class-platform-checkout-tracker.php
  tests/unit/test-class-platform-checkout-tracker.php
Labels: pr: needs review, component: platform checkout

#4041 Prevent WCPay server refund of interac_present
  changelog/interac-present-refund
  includes/class-wc-payment-gateway-wcpay.php
  includes/constants/class-payment-method.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge

#4102 Add handling for server export for deposits CSV download
  changelog/update-3847-depsoits-csv-export
  client/data/deposits/resolvers.js
  client/deposits/list/index.tsx
  client/deposits/list/test/index.tsx
  includes/admin/class-wc-rest-payments-deposits-controller.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: ready to merge

#4104 UPE - Fix saving payment methods on WC Blocks if a non-reusable method is enabled
  changelog/fix-blocks-upe-save-payment-method
  client/checkout/blocks/upe-fields.js
Labels: pr: needs review, component: checkout, component: upe

#4118 Fix - Hide save payment method checkbox for non-reusable payment methods on WooCommerce Blocks
  changelog/fix-3667-saving-payment-methods-upe
  client/checkout/blocks/upe-fields.js
Labels: pr: ready to merge, component: checkout, component: upe

#4122 Send CVC confirmation to server for fraud prevention
  changelog/fix-4121-send-cvc-confirmation-to-server
  includes/class-payment-information.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: needs author reply

#4137 Update: remove merchant onboarding E2E tests
  changelog/update-remove-merchant-onboarding-e2e-tests
  package-lock.json
  package.json
  tests/e2e/specs/wcpay/merchant/merchant-a-onboarding-setup.spec.js
  tests/e2e/specs/wcpay/merchant/merchant-a-onboarding-task-list.spec.js
Labels: pr: ready to merge, category: e2e, category: devops

#4134 Add StripeLink logo to transactions list
  assets/css/admin.css
  assets/images/cards/link.png
  changelog/add-stripelink-logo-in-transactions
Labels: pr: ready to merge

#2303 Sync blog locale to WCPay Account
  changelog/add-888-sync-blog-lang-to-wcpay-account
  includes/class-wc-payments-account.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: needs review

#4131 Update _charge_id in metadata
  changelog/fix-3857-update-charge-id
  includes/class-wc-payments-webhook-processing-service.php
Labels: pr: needs review

#4130 Fix UPE alignment issues on Classic Checkout
  changelog/fix-upe-alignment
  client/checkout/classic/style.scss
Labels: pr: needs review, component: upe

#4120 Code amelioration for card testing service
  changelog/fix-fingerprinting-service
  includes/fraud-prevention/class-buyer-fingerprinting-service.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/fraud-prevention/test-class-buyer-fingerprinting-service.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: needs review

#4149 Fix changelog entry with newline.
  changelog.txt
  changelog/fix-changelog-4.0.0-newline
Labels: pr: needs review

#4140 Add missing VAT information prompt when downloading invoice
  changelog/add-3933-vat-data-prompt
  client/data/store.js
  client/documents/list/index.tsx
  client/documents/list/test/index.tsx
  client/globals.d.ts
  client/vat/form-modal/index.tsx
  client/vat/form-modal/test/__snapshots__/index.tsx.snap
  client/vat/form-modal/test/index.tsx
  includes/class-wc-payments-account.php
Labels: pr: ready to merge, component: invoices for processing fees

#4156 Fix templates folder missing in package
  changelog/fix-4154-template-files-missing-in-package
  tasks/release.js
Labels: pr: ready to merge

#4161 Sync changelog.txt and readme.txt.
  changelog/fix-changelog-readme-4.0.0-newline
  readme.txt
Labels: pr: needs review

#4162 Release branch for 4.0.1
  changelog.txt
  changelog/fix-4154-template-files-missing-in-package
  readme.txt
Labels: pr: needs review

#4163 Add more logging info when sending requests to WooCommerce Payments server
  changelog/add-3998-more-data-logging
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: needs review

#4170 Fix "Compatibility - WC, WP and PHP" CI failures
  .github/workflows/compatibility.yml
  changelog/fix-4169-compatibility-ci-failures
  tests/unit/multi-currency/notes/test-class-note-multi-currency-available-test.php
  tests/unit/notes/test-class-wc-payments-notes-additional-payment-methods.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
Labels: pr: needs review

#4172 Update GH Workflow to skip setting up WC Blocks for incompatible WC versions
  .github/workflows/e2e-test.yml
  changelog/update-gh-e2e-env-setup
  tests/e2e/specs/blocks/shopper/shopper-wc-blocks-checkout-failures.spec.js
Labels: pr: in progress, category: e2e, category: devops

#4168 Add VAT details form when downloading invoice
  changelog/add-3934-vat-data-form
  client/documents/list/index.tsx
  client/documents/list/test/index.tsx
  client/globals.d.ts
  client/vat/form-modal/index.tsx
  client/vat/form-modal/test/__snapshots__/index.tsx.snap
  client/vat/form-modal/test/index.tsx
  client/vat/form/index.tsx
  client/vat/form/style.scss
  client/vat/form/tasks/company-data-task.tsx
  client/vat/form/tasks/vat-number-task.tsx
  client/vat/form/test/index.tsx
  client/vat/types.d.ts
  includes/admin/class-wc-rest-payments-vat-controller.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: ready to merge, component: invoices for processing fees

#4176 E2E - Optimize setup script to install Action Scheduler & WC Blocks from WordPress.org
  changelog/e2e-optimize-setup-script
  tests/e2e/README.md
  tests/e2e/env/docker-compose.yml
  tests/e2e/env/setup.sh
Labels: pr: ready to merge, category: e2e, category: devops

#4164 Remove test_document document type.
  changelog/dev-1837-remove-test-document-type
  client/data/documents/hooks.ts
  client/data/documents/test/reducer.js
  client/data/documents/test/selectors.js
  client/documents/filters/test/__snapshots__/index.tsx.snap
  client/documents/filters/test/index.tsx
  client/documents/list/index.tsx
  client/documents/list/test/__snapshots__/index.tsx.snap
  client/documents/list/test/index.tsx
  client/documents/strings.ts
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: ready to merge, component: invoices for processing fees

#4141 Fix platform checkout Store API nonce check
  changelog/fix-747-store-api-nonce-check
  includes/class-wc-payments.php
  tests/unit/test-class-wc-payments.php
Labels: priority: critical, component: platform checkout

#4180 Add support for direct document access
  changelog/add-s1838-document-direct-link
  client/documents/list/index.tsx
  client/documents/list/test/__snapshots__/index.tsx.snap
  client/documents/list/test/index.tsx
  client/transactions/declarations.d.ts
Labels: pr: needs review, component: invoices for processing fees

#4181 Platform checkout: Remove WooCommerce Blocks plugin dependency
  changelog/fix-platform-checkout-inject-payments-api
  includes/class-wc-payments.php
Labels: pr: needs review, component: platform checkout

#4184 In-Person Payments: extend REST-endpoints documentation
  changelog/dev-rest-endpoints-documentation
  includes/admin/class-wc-rest-payments-orders-controller.php
Labels: pr: ready to merge

#4185 In-Person Payments: send receipt for Interac payments.
  changelog/fix-4183-send-receipts-for-interac-payments
  includes/class-wc-payments-webhook-processing-service.php
Labels: pr: ready to merge

#4129 Pass along the platform checkout user session key
  changelog/add-platform-checkout-user-session
  client/checkout/api/index.js
  client/checkout/api/test/index.test.js
  client/checkout/platform-checkout/email-input-iframe.js
  includes/class-wc-payments.php
Labels: pr: needs review, component: platform checkout

#4198 Fix IPP email receipt removes custom email settings
  changelog/fix-ipp-email-receipt-removes-custom-email-settings
  includes/class-wc-payments.php
  includes/in-person-payments/class-wc-payments-in-person-payments-receipts-service.php
  tests/unit/in-person-payments/test-class-wc-payments-in-person-payments-receipts-service.php
Labels: pr: needs review

#4200 Card testing: replace enable toggle with account eligibility flag
  changelog/add-4178-replace-toggle-with-eligibility-flag
  client/data/settings/actions.js
  client/data/settings/hooks.js
  client/data/settings/selectors.js
  client/settings/fraud-prevention/index.tsx
  client/settings/settings-manager/index.js
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  includes/fraud-prevention/class-fraud-prevention-service.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/fraud-prevention/test-class-fraud-prevention-service.php
  tests/unit/test-class-wc-payment-gateway-wcpay-payment-types.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: ready to merge

#4199 Enable documents feature based on is_documents_enabled
  changelog/add-4017-enable-documents-feature
  changelog/add-s1838-document-direct-link
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-features.php
  tests/unit/test-class-wc-payments-features.php
Labels: pr: needs review, component: invoices for processing fees

#4207 Card testing: rework errors handling.
  changelog/update-1833-card-testing-errors-handling
  includes/class-wc-payment-gateway-wcpay.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge

#4205 Protect account status usage during Overview page init
  changelog/fix-4204-protect-account-status-usage-for-overview
  client/overview/index.js
Labels: pr: ready to merge

#4208 Move the email field to the top of the Checkout page when StripeLink is enabled
  assets/images/payment-methods/link.svg
  changelog/add-3801-move-email-field-stripelink
  client/checkout/classic/style.scss
  client/checkout/classic/upe.js
  includes/class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge

#4177 Remove the color fields and icon on receipt settings page
  changelog/update-4144-remove-the-color-fields-on-receipt-settings
  client/card-readers/settings/sections/branding-details.js
  client/card-readers/settings/sections/test/index.test.js
  client/data/settings/actions.js
  client/data/settings/hooks.js
  client/data/settings/selectors.js
  client/data/settings/test/reducer.js
  client/data/settings/test/selectors.js
Labels: pr: ready to merge

#4215 Ignore cache expiry check when checking platform_checkout eligibility
  changelog/fix-cache-lookup-platform-checkout-eligibility
  includes/class-database-cache.php
  includes/class-wc-payments-features.php
Labels: component: platform checkout
