Repository Automattic/woocommerce-payments, pull requests merged in 2022-11, with the labels that each got.

#5029 Update the balance component header
  changelog/update-5017-balance-header-component-ui-enhancements
  client/components/deposits-information/index.tsx
  client/components/deposits-information/test/__snapshots__/index.js.snap
  client/components/deposits-information/test/index.js
  client/deposits/utils/index.js
  client/deposits/utils/test/index.js
Labels: pr: needs review

#4949 Authorizations: Replace mocked data in reducer/store with actual fetching + add tests
  changelog/change-mocked-data-with-actual-data
  client/data/authorizations/actions.ts
  client/data/authorizations/hooks.ts
  client/data/authorizations/reducer.ts
  client/data/authorizations/resolvers.ts
  client/data/authorizations/selectors.ts
  client/data/authorizations/test/reducer.ts
  client/data/authorizations/test/resolvers.ts
  client/data/authorizations/test/selectors.ts
  client/types/authorizations.d.ts
Labels: pr: needs review

#5030 Update Stripe Link inbox notification wording
  changelog/fix-link-inbox-notification-wording
  includes/notes/class-wc-payments-notes-set-up-stripelink.php
  tests/unit/notes/test-class-wc-payments-notes-set-up-stripelink.php
Labels: pr: needs author reply

#4935 Add watch mode to php unit tests
  .phpunit-watcher.yml
  bin/run-tests.sh
  changelog/dev-677-unit-test-watcher
  composer.json
  composer.lock
  package.json
  tests/README.md
Labels: pr: ready to merge

#5011 Fix currency switcher block padding
  changelog/fix-4945-currency-swticher-block-padding
  client/multi-currency/blocks/currency-switcher.js
Labels: pr: needs review

#5049 Fix tests for WP 6.1
  changelog/fix-wp-6.1-tests
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-webhook-processing-service.php
Labels: pr: ready to merge, component: tests, category: devops

#5004 New Tracks event on KYC modal open
  changelog/4980-add-kyc-modal-tracking
  client/connect-account-page/index.js
  client/tracks/index.js
Labels: pr: ready to merge

#4943 Update Dockerfile image to `wordpress:php7.4`
  changelog/dev-update-docker-image-php-version
  docker/wordpress_xdebug/Dockerfile
Labels: pr: needs review

#5003 Add new workflow for post-release updates
  .github/actions/build/action.yml
  .github/actions/create-branch-tag/action.yml
  .github/actions/create-branch/action.yml
  .github/actions/create-tag/action.yml
  .github/actions/generate-changelog/action.yml
  .github/actions/setup-repo/action.yml
  .github/actions/trigger-translations/action.yml
  .github/actions/version-check/action.yml
  .github/workflows/build-zip-file.yml
  .github/workflows/create-pre-release.yml
  .github/workflows/create-release.yml
  .github/workflows/post-release-updates.yml
  .github/workflows/release-code-freeze.yml
  .github/workflows/release-pr.yml
  .github/workflows/scripts/get-next-version.php
  changelog/dev-4824-post-release-workflow
Labels: pr: needs review

#5050 Revert "Adding manual option to deposit schedule selection (#4715)"
  changelog/add-4696-manual-deposit-schedule-selection
  changelog/revert-4696-add-4696-manual-deposit-schedule-selection
  client/settings/deposits/index.js
  client/settings/deposits/style.scss
  client/settings/deposits/test/index.test.js
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-account.php
Labels: pr: ready to merge

#4982 [Authorizations] Wire Uncaptured Transactions screen to API data
  changelog/add-authorizations-screen
  client/data/authorizations/test/reducer.ts
  client/data/authorizations/test/selectors.ts
  client/transactions/declarations.d.ts
  client/transactions/index.tsx
  client/transactions/uncaptured/index.tsx
  client/transactions/uncaptured/test/__snapshots__/index.tsx.snap
  client/transactions/uncaptured/test/index.tsx
  client/types/authorizations.d.ts
Labels: pr: needs review

#4962 [Authorizations] [Integration] Capture authorizations from table
  changelog/add-4569-authorizations-capture-from-table-integration
  client/components/capture-authorization-button/index.tsx
  client/components/capture-authorization-button/test/__snapshots__/index.test.tsx.snap
  client/components/capture-authorization-button/test/index.test.tsx
  client/data/authorizations/action-types.ts
  client/data/authorizations/actions.ts
  client/data/authorizations/hooks.ts
  client/data/authorizations/reducer.ts
  client/data/authorizations/resolvers.ts
  client/data/authorizations/selectors.ts
  client/data/authorizations/test/actions.test.ts
  client/data/authorizations/test/authorizations-summary.fixture.json
  client/data/authorizations/test/authorizations.fixture.json
  client/data/authorizations/test/reducer.test.ts
  client/data/authorizations/test/resolvers.test.ts
  client/data/authorizations/test/selectors.test.ts
  client/transactions/uncaptured/index.tsx
  client/transactions/uncaptured/test/__snapshots__/index.tsx.snap
  client/transactions/uncaptured/test/index.tsx
  client/types/authorizations.d.ts
  docs/rest-api/source/includes/wp-api-v3/order.md
  includes/admin/class-wc-rest-payments-orders-controller.php
  tests/unit/admin/test-class-wc-rest-payments-orders-controller.php
  tsconfig.json
Labels: pr: ready to merge

#5006 Add Capture Charge button on payment details page
  changelog/add-4506-ui-components-and-data-store
  client/components/capture-authorization-button/index.tsx
  client/components/capture-authorization-button/test/__snapshots__/index.test.tsx.snap
  client/components/capture-authorization-button/test/index.test.tsx
  client/components/test-mode-notice/index.js
  client/data/authorizations/actions.ts
  client/data/authorizations/resolvers.ts
  client/data/authorizations/test/actions.test.ts
  client/data/authorizations/test/reducer.test.ts
  client/data/authorizations/test/resolvers.test.ts
  client/data/authorizations/test/selectors.test.ts
  client/payment-details/summary/index.tsx
  client/payment-details/summary/style.scss
  client/payment-details/summary/test/__snapshots__/index.tsx.snap
  client/payment-details/test/__snapshots__/index.test.tsx.snap
  client/payment-details/test/index.test.tsx
  client/transactions/index.tsx
  client/transactions/uncaptured/index.tsx
  client/transactions/uncaptured/test/__snapshots__/index.test.tsx.snap
  client/transactions/uncaptured/test/index.test.tsx
  client/types/authorizations.d.ts
Labels: pr: ready to merge

#4987 Refund Confirmation modal on order status change
  changelog/add-2814-refund-confirmation-modal
  client/order/index.js
  client/order/refund-confirm-modal/index.js
  client/order/refund-confirm-modal/styles.scss
  includes/admin/class-wc-payments-admin.php
Labels: pr: needs author reply

#5065 Fix jest tests due to daylight saving
  changelog/fix-jest-timezone-nov-2022
  client/data/transactions/test/resolvers.js
  client/transactions/list/test/index.tsx
Labels: pr: needs review

#5060 Fetch authorization data only if the payment is marked for manual capture
  changelog/fix-fetch-auth
  client/data/authorizations/hooks.ts
  client/payment-details/summary/index.tsx
Labels: type: bug, pr: ready to merge, category: projects, component: authorizations

#5055 Add PHPCS object operator indent rule
  changelog/dev-phpcs-object-operator-indent
  phpcs.xml.dist
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
  tests/unit/multi-currency/compatibility/test-class-woocommerce-deposits.php
  tests/unit/multi-currency/compatibility/test-class-woocommerce-subscriptions.php
  tests/unit/subscriptions/test-class-wc-payments-product-service.php
  tests/unit/subscriptions/test-class-wc-payments-subscription-service.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-payment-method-order-note.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-payment-request-button-handler.php
  tests/unit/test-class-wc-payments-webhook-processing-service.php
  tests/unit/test-class-wc-payments-webhook-reliability-service.php
  tests/unit/test-class-wc-payments.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: ready to merge

#5070 Clean up some workflows for the release automation
  .github/workflows/build-zip-file.yml
  .github/workflows/post-release-updates.yml
  changelog/update-remove-pull-request-trigger-from-zip-workflow
Labels: pr: ready to merge

#5087 Add description for capture authorization endpoint docs
  changelog/fix-api-docs-capture-authorization
  docs/rest-api/source/includes/wp-api-v3/order.md
Labels: pr: ready to merge

#5091 Fix section divider in Authentication API docs
  changelog/fix-api-docs-authentication-section-divider
  docs/rest-api/source/includes/wp-api-v3/authentication.md
Labels: pr: ready to merge, type: documentation

#5088 Add API docs for authorization endpoints
  changelog/add-api-docs-authorizations
  docs/rest-api/source/includes/wp-api-v3/authorization.md
Labels: pr: ready to merge, type: documentation

#5098 Check if user can `manage_woocommerce` in maybe_redirect_to_onboarding()
  changelog/fix-5096-fatal-error-admin
  includes/class-wc-payments-account.php
  includes/class-wc-payments.php
  tests/unit/test-class-wc-payments-account.php
Labels: pr: needs review

#5072 Show uncaptured transactions tab only when some criteria is met
  changelog/add-show-uncaptured-when-checks-are-meeted
  client/globals.d.ts
  client/payment-details/summary/index.tsx
  client/payment-details/summary/test/index.tsx
  client/settings/wcpay-settings-context.js
  client/transactions/index.tsx
  client/transactions/test/index.tsx
  includes/class-wc-payments-features.php
  tests/unit/test-class-wc-payments-features.php
Labels: pr: ready to merge

#5097 Add the missing include for authorization API docs in sidebar
  changelog/fix-api-docs--include-authorization-docs
  docs/rest-api/source/index.html.md
Labels: pr: ready to merge, type: documentation

#5095 Add count of pending authorizations to Uncaptured tab
  changelog/fix-5089-count-of-pending-authorizations-with-parenthesis
  client/transactions/index.tsx
  client/transactions/test/index.tsx
  client/transactions/uncaptured/index.tsx
  client/transactions/uncaptured/test/__snapshots__/index.test.tsx.snap
Labels: pr: ready to merge

#5103 Update copy of Subscriptions warning modal
  changelog/update-5047-warning-modal-while-deactivating-subs-extension
  includes/subscriptions/templates/html-subscriptions-plugin-notice.php
Labels: pr: ready to merge, component: wcpay subscriptions, category: core, component: wc subscriptions integration

#5104 Expose fraud prevention token, send it to blocks checkout
  changelog/fix-card-testing-nonce-blocks-checkout
  client/checkout/blocks/generate-payment-method.js
  client/checkout/blocks/upe-fields.js
  includes/class-wc-payments-blocks-payment-method.php
Labels: pr: needs review

#5105 Fix the "Learn More" link on Express Checkout settings section
  changelog/fix-5083-link-learn-more-express-checkout
  client/settings/settings-manager/index.js
Labels: pr: ready to merge, priority: low, component: settings, category: core

#5120 Update subscriptions core version to 5.0.0
  changelog/subscriptions-core-5.0.0
  changelog/subscriptions-core-5.0.0-1
  changelog/subscriptions-core-5.0.0-2
  composer.json
  composer.lock
Labels: pr: needs review

#5123 Release 5.0.2.
  changelog.txt
  changelog/fix-rest-api-fatal-error
  readme.txt
Labels: pr: needs review

#5133 Fixes purchasing a synced subscription with WCPay Subscriptions results in an unsynced subscription
  changelog/subscriptions-core-2.5.2
  composer.json
  composer.lock
Labels: pr: ready to merge

#5135 Prevent the double-zip issue when downloading from zip file workflow
  .github/workflows/build-zip-file.yml
  changelog/fix-prevent-double-zip-issue-for-workflow
Labels: pr: needs review

#4782 Cloak client secret
  changelog/add-4774-cloak-client-secret
  client/checkout/api/index.js
  client/checkout/blocks/upe-fields.js
  client/checkout/classic/upe.js
  client/checkout/utils/encryption.js
  client/data/settings/actions.js
  client/data/settings/hooks.js
  client/data/settings/selectors.js
  client/data/settings/test/hooks.js
  client/data/settings/test/reducer.js
  client/data/settings/test/selectors.js
  client/settings/advanced-settings/client-secret-encryption-toggle.js
  client/settings/advanced-settings/index.js
  client/settings/advanced-settings/test/client-secret-encryption-toggle.test.js
  client/settings/advanced-settings/test/index.test.js
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-checkout.php
  includes/class-wc-payments-features.php
  includes/class-wc-payments-utils.php
  includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php
  includes/payment-methods/class-upe-payment-gateway.php
  package-lock.json
  package.json
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
Labels: pr: ready to merge, type: good for architectural review

#5170 Subscriptions core/5.1.0
  changelog/subscriptions-core-5.1.0
  changelog/subscriptions-core-5.1.0-1
  changelog/subscriptions-core-5.1.0-10
  changelog/subscriptions-core-5.1.0-11
  changelog/subscriptions-core-5.1.0-12
  changelog/subscriptions-core-5.1.0-13
  changelog/subscriptions-core-5.1.0-14
  changelog/subscriptions-core-5.1.0-15
  changelog/subscriptions-core-5.1.0-16
  changelog/subscriptions-core-5.1.0-17
  changelog/subscriptions-core-5.1.0-2
  changelog/subscriptions-core-5.1.0-3
  changelog/subscriptions-core-5.1.0-4
  changelog/subscriptions-core-5.1.0-5
  changelog/subscriptions-core-5.1.0-6
  changelog/subscriptions-core-5.1.0-7
  changelog/subscriptions-core-5.1.0-8
  changelog/subscriptions-core-5.1.0-9
  composer.json
  composer.lock
Labels: pr: needs review

#5107 Handle errors in retrieving a file gracefully
  changelog/fix-4936-handle-error-in-retrieving-file-contents
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: ready to merge, component: card present

#5185 Fix error sorting the Uncaptured table using Capture by column
  changelog/fix-5184-sort-by-capture-by-column-of-uncaptured-transactions-table-causes-an-error
  client/data/authorizations/resolvers.ts
  client/transactions/uncaptured/index.tsx
Labels: pr: needs review, pr: ready to merge

#5173 Use botwoo machine user to merge trunk changes in develop
  .github/workflows/post-release-updates.yml
  changelog/update-use-botwoo-post-release-steps-workflow
Labels: pr: ready to merge

#5071 Implement FingerprintJS on the checkout page
  changelog/add-4772-fingerprintjs
  client/checkout/api/index.js
  client/checkout/blocks/fields.js
  client/checkout/blocks/generate-payment-method.js
  client/checkout/blocks/hooks.js
  client/checkout/blocks/upe-fields.js
  client/checkout/classic/index.js
  client/checkout/classic/upe.js
  client/checkout/utils/fingerprint.js
  includes/class-payment-information.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/fraud-prevention/class-buyer-fingerprinting-service.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  package-lock.json
  package.json
  tests/unit/fraud-prevention/test-class-buyer-fingerprinting-service.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
  tests/unit/test-class-payment-information.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: ready to merge

#5204 Fix PR checks not triggered for release PR created by workflow
  .github/workflows/release-pr.yml
  changelog/fix-5197-required-checks-not-triggered-for-pr-created-by-workflow
Labels: pr: ready to merge

#5200 Set github-actions bot as the commit author for the code freeze workflow
  .github/workflows/release-pr.yml
  changelog/fix-commit-author-code-freeze-workflow
Labels: pr: needs review

#5171 Fix UPE methods checkbox selection
  changelog/fix-4629-UPE-methods-selection
  client/data/settings/action-types.js
  client/data/settings/actions.js
  client/data/settings/hooks.js
  client/data/settings/reducer.js
  client/payment-methods/index.js
  client/payment-methods/test/index.js
Labels: type: bug, pr: needs review, component: settings, component: upe, category: core
