Repository Automattic/woocommerce-payments, pull requests merged in 2022-03, with the labels that each got.

#3854 Remove image preview for Disputes Evidence upload fields settings
  changelog/fix-3853-deposits-evidence-upload-preview
  client/card-readers/settings/file-upload.js
  client/components/file-upload/index.tsx
  client/components/file-upload/preview.tsx
  client/components/file-upload/test/__snapshots__/index.tsx.snap
  client/components/file-upload/test/index.tsx
  client/components/file-upload/upload-error.tsx
  client/disputes/evidence/index.js
  client/types/disputes.d.ts
Labels: pr: needs review

#3879 E2E - Update GH workflow to fix compatibility with WC 4.8.0
  .github/workflows/e2e-test.yml
  tests/e2e/env/setup.sh
Labels: pr: ready to merge, category: e2e, category: devops

#3848 Remove interactions with the dev tools setting "grouped settings" in E2E tests
  tests/e2e/specs/wcpay/merchant/merchant-payment-gateways-confirmation.spec.js
Labels: pr: ready to merge

#3863 Remove "wcpay_current_session_id" filter from wc-payments-fraud-service
  changelog/fix-3532-fraud-service-dead-code
  includes/class-wc-payments-fraud-service.php
  psalm-baseline.xml
  tests/unit/test-class-wc-payments-fraud-service.php
Labels: pr: ready to merge

#3878 Update payment methods grouped card icons
  changelog/tweak-2695-update-grouped-card-icon
  client/connect-account-page/cards/cb.js
  client/connect-account-page/index.js
  client/connect-account-page/test/__snapshots__/index.js.snap
  client/gateway-icons/credit-card.js
  client/payment-methods/test/__snapshots__/activation-modal.test.js.snap
  client/payment-methods/test/__snapshots__/delete-modal.test.js.snap
Labels: component: settings, component: grouped-settings, component: onboarding

#3866 Track platform checkout OTP attempts
  changelog/add-otp-tracks
  client/checkout/platform-checkout/email-input-iframe.js
  client/tracks/index.js
Labels: pr: needs review, category: projects, component: platform checkout

#3890 Release branch for WooCommerce Payments 3.8.1
  changelog.txt
  changelog/fix-lodash-dependency-in-bundle
  readme.txt
Labels: pr: ready to merge

#3867 Add tracking for checkout start and completion
  changelog/add-checkout-tracks
  includes/class-platform-checkout-tracker.php
Labels: pr: needs review, component: platform checkout

#3865 Add filter for "wcpay_is_wcpay_subscriptions_enabled"
  changelog/Add wcpay_is_wcpay_subscriptions_enabled filter
  includes/class-wc-payments-features.php
Labels: pr: needs review, component: wcpay subscriptions

#3881 Fix woocommerce_order_actions when order is empty
  changelog/tweak-2704-check-order-on-woocommerce_order_actions
  includes/class-wc-payment-gateway-wcpay.php
Labels: type: bug

#3893 Fix fatal error when a subscription renews automatically
  changelog/fix-3892-fatal-error-subscription-renewal
  includes/payment-methods/class-upe-payment-gateway.php
Labels: pr: ready to merge

#3852 Refactor: decouple webhook processing service
  changelog/refactor-decouple-webhook-processing-service
  includes/admin/class-wc-rest-payments-webhook-controller.php
  includes/class-wc-payments-webhook-processing-service.php
  includes/class-wc-payments.php
  includes/exceptions/class-invalid-webhook-data-exception.php
  includes/notes/class-wc-payments-remote-note-service.php
  includes/subscriptions/class-wc-payments-subscriptions-event-handler.php
  tests/unit/admin/test-class-wc-rest-payments-webhook.php
  tests/unit/subscriptions/test-class-wc-payments-subscriptions-event-handler.php
  tests/unit/test-class-wc-payments-webhook-processing-service.php
Labels: type: enhancement, pr: ready to merge, status: has pr, component: wcpay subscriptions, category: core

#3896 Drop `wordpress-element` package
  changelog/remove-709-wordpress-element
  client/account-status-settings/index.js
  client/components/deposits-status/index.js
  client/connect-account-page/strings.js
  client/deposits/instant-deposits/modal.js
  client/deposits/utils/index.js
  client/payment-details/timeline/map-events.js
  client/subscription-product-onboarding/modal.js
  client/subscriptions-empty-state/index.js
  package-lock.json
  package.json
Labels: pr: ready to merge

#3762 Allow saving credit cards to platform account from classic checkout
  changelog/add-3732-save-platform-payment-method
  client/components/platform-checkout/hooks/use-selected-payment-method.js
  client/components/platform-checkout/save-user/checkout-page-save-user.js
  client/components/platform-checkout/save-user/test/checkout-page-save-user.test.js
  includes/class-payment-information.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
  tests/unit/test-class-wc-payment-gateway-wcpay-payment-types.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge, component: platform checkout

#3860 Add all subscription line items when creating WCPay Subscriptions
  changelog/fix-3826
  includes/subscriptions/class-wc-payments-product-service.php
  includes/subscriptions/class-wc-payments-subscription-service.php
Labels: pr: ready to merge

#3869 Check the merchant's account before showing the multi-currency inbox note
  .gitignore
  changelog/fix-3806-do-not-show-multiple-currencies-inbox-note-if-wcpay-not-set-up-yet
  includes/multi-currency/MultiCurrency.php
  includes/multi-currency/Notes/NoteMultiCurrencyAvailable.php
  tests/unit/multi-currency/notes/test-class-note-multi-currency-available-test.php
Labels: pr: ready to merge

#3883 Add compatibility between Multi-Currency and WooCommerce Name Your Price
  changelog/add-3507-name-your-price-compatibility
  includes/multi-currency/Compatibility.php
  includes/multi-currency/Compatibility/WooCommerceNameYourPrice.php
  psalm-baseline.xml
  tests/unit/helpers/class-wc-helper-deposit-product-manager.php
  tests/unit/helpers/class-wc-helper-name-your-price.php
  tests/unit/multi-currency/compatibility/test-class-woocommerce-name-your-price.php
Labels: pr: ready to merge

#3911 HACK week: migration to TypeScripts (client/payment-details)
  client/components/customer-link/index.js
  client/components/customer-link/index.tsx
  client/components/customer-link/test/__snapshots__/index.tsx.snap
  client/components/customer-link/test/index.tsx
  client/components/deposits-information/declarations.d.ts
  client/components/order-link/index.js
  client/components/order-link/index.tsx
  client/components/order-link/test/__snapshots__/index.tsx.snap
  client/components/order-link/test/index.tsx
  client/components/risk-level/strings.js
  client/data/transactions/hooks.ts
  client/disputes/test/index.tsx
  client/payment-details/summary/index.tsx
  client/payment-details/summary/test/__snapshots__/index.tsx.snap
  client/payment-details/summary/test/index.js
  client/payment-details/summary/test/index.tsx
  client/types/charges.d.ts
  client/types/disputes.d.ts
  client/types/orders.d.ts
Labels: pr: ready to merge

#3913 Improve visibility of wcpay payment methods fields for dark themes
  changelog/fix-1152-wcpay-checkout-payment-methods-fields-visibility
  client/checkout/blocks/style.scss
Labels: pr: ready to merge

#3899 Fee Display Causing Confusion for Merchants
  changelog/fix-fee-display-confusion
  client/utils/account-fees.tsx
  client/utils/test/account-fees.tsx
Labels: pr: needs review

#3919 Track when platform checkout is offered
  changelog/add-platform-checkout-offered-tracks
  client/capital/style.scss
  client/checkout/platform-checkout/email-input-iframe.js
  client/tracks/index.js
  composer.lock
Labels: component: platform checkout

#3917 TS migration for deposit details view
  client/data/deposits/hooks.ts
  client/deposits/declarations.d.ts
  client/deposits/details/index.tsx
  client/deposits/details/test/__snapshots__/index.tsx.snap
  client/deposits/details/test/index.tsx
  client/types/deposits.d.ts
Labels: pr: ready to merge

#3940 Fix the conversion amount in the transaction list
  changelog/fix-3939-incorrect-conversion-in-transaction-list
  client/transactions/list/index.tsx
Labels: pr: needs review, component: transactions

#3827 Webhook Reliability: Fetch failed events and process them
  changelog/add-3813-fetch-run-webhooks
  includes/class-wc-payments-webhook-reliability-service.php
  includes/class-wc-payments.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/test-class-wc-payments-webhook-reliability-service.php
Labels: pr: ready to merge

#3921 HACK week: migration to TypeScript (client/utils/currency)
  client/globals.d.ts
  client/utils/currency/declarations.d.ts
  client/utils/currency/index.ts
Labels: pr: ready to merge

#3916 HACK week: migration to TypeScript (client/card-readers/list)
  client/card-readers/index.tsx
  client/card-readers/list/index.tsx
  client/card-readers/list/list-item.tsx
  client/card-readers/list/test/index.test.tsx
  client/card-readers/settings/index.js
  client/card-readers/style.scss
  client/card-readers/test/index.test.tsx
  client/data/card-readers/hooks.js
  client/data/card-readers/hooks.ts
  client/multi-currency/multi-currency-settings/enabled-currencies-list/index.js
  client/multi-currency/multi-currency-settings/store-settings/index.js
  client/multi-currency/single-currency-settings/index.js
  client/settings/express-checkout-settings/index.js
  client/settings/settings-manager/index.js
  client/settings/settings-section.tsx
  client/settings/test/settings-section.tsx
Labels: pr: ready to merge

#3625 [Settings] Add shortened customer bank statement
  changelog/update-statement-descriptors
  client/data/settings/actions.js
  client/data/settings/hooks.js
  client/data/settings/selectors.js
  client/settings/transactions-and-deposits/index.js
  client/settings/transactions-and-deposits/test/index.test.js
  client/settings/transactions-and-deposits/text-length-help-input-wrapper.js
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: needs review, component: settings, category: core

#3910 TypeScript support for client/payment-methods
  client/components/confirmation-modal/index.tsx
  client/components/payment-confirm-illustration/index.tsx
  client/components/payment-confirm-illustration/test/__snapshots__/index.tsx.snap
  client/components/payment-confirm-illustration/test/index.tsx
  client/components/payment-delete-illustration/index.tsx
  client/components/payment-delete-illustration/test/__snapshots__/index.tsx.snap
  client/components/payment-delete-illustration/test/index.tsx
  client/globals.d.ts
  client/payment-gateways/disable-confirmation-modal.js
  client/payment-methods-map.ts
  client/payment-methods/activation-modal.tsx
  client/payment-methods/delete-modal.tsx
  client/payment-methods/index.js
  client/payment-methods/test/delete-modal.test.js
  client/requirements-map.ts
  client/settings/payment-method-icon/index.js
Labels: pr: ready to merge

#3949 Fix/platform checkout my account email
  changelog/fix-platform-checkout-my-account-email
  includes/class-wc-payments.php
Labels: type: bug, pr: ready to merge, component: platform checkout

#3959 Fix `is_platform_payment_method` flag on blocks checkout
  changelog/fix-is-platform-payment-method-flag
  includes/class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
Labels: type: bug, pr: ready to merge, component: platform checkout

#3937 Add a filter in get_metadata_from_order
  changelog/add-metadata-filter
  includes/class-wc-payment-gateway-wcpay.php
Labels: pr: needs review

#3912 REST API documentation
  .eslintrc
  .github/workflows/deploy-api-docs.yml
  .stylelintignore
  changelog/dev-hack-week-rest-api-documentation
  docs/rest-api/build.sh
  docs/rest-api/font-selection.json
  docs/rest-api/source/fonts/slate.eot
  docs/rest-api/source/fonts/slate.svg
  docs/rest-api/source/fonts/slate.ttf
  docs/rest-api/source/fonts/slate.woff
  docs/rest-api/source/fonts/slate.woff2
  docs/rest-api/source/images/favicon-180x180.png
  docs/rest-api/source/images/favicon-192x192.png
  docs/rest-api/source/images/favicon-270x270.png
  docs/rest-api/source/images/favicon-32x32.png
  docs/rest-api/source/images/logo.png
  docs/rest-api/source/images/navbar.png
  docs/rest-api/source/images/woocommerce-api-key-generated.png
  docs/rest-api/source/images/woocommerce-api-keys-settings.png
  docs/rest-api/source/images/woocommerce-creating-api-keys.png
  docs/rest-api/source/includes/wp-api-v3/authentication.md
  docs/rest-api/source/includes/wp-api-v3/introduction.md
  docs/rest-api/source/includes/wp-api-v3/order.md
  docs/rest-api/source/index.html.md
  docs/rest-api/source/javascripts/all.js
  docs/rest-api/source/javascripts/all_nosearch.js
  docs/rest-api/source/javascripts/app/_lang.js
  docs/rest-api/source/javascripts/app/_search.js
  docs/rest-api/source/javascripts/app/_toc.js
  docs/rest-api/source/javascripts/lib/_energize.js
  docs/rest-api/source/javascripts/lib/_imagesloaded.min.js
  docs/rest-api/source/javascripts/lib/_jquery.highlight.js
  docs/rest-api/source/javascripts/lib/_jquery.js
  docs/rest-api/source/javascripts/lib/_lunr.js
  docs/rest-api/source/layouts/layout.erb
  docs/rest-api/source/stylesheets/_api-endpoint.scss
  docs/rest-api/source/stylesheets/_content.scss
  docs/rest-api/source/stylesheets/_icon-font.scss
  docs/rest-api/source/stylesheets/_label.scss
  docs/rest-api/source/stylesheets/_lang-selector.scss
  docs/rest-api/source/stylesheets/_normalize.scss
  docs/rest-api/source/stylesheets/_rtl.scss
  docs/rest-api/source/stylesheets/_toc.scss
  docs/rest-api/source/stylesheets/_variables.scss
  docs/rest-api/source/stylesheets/_warning.scss
  docs/rest-api/source/stylesheets/print.css.scss
  docs/rest-api/source/stylesheets/screen.css.scss
Labels: pr: ready to merge, type: documentation

#3962 Fix wrong update when payment intent is attached to multiple order ids in UPE
  changelog/fix-3784-duplicate-order-UPE
  includes/class-wc-payments-db.php
Labels: pr: needs review

#3936 Add hyphen to last name on billing addresses without it
  changelog/tweak-2828-payment-without-billing-last-name-fix
  client/payment-request/utils/normalize.js
  client/payment-request/utils/tests/normalize.test.js
Labels: pr: needs review, category: core

#3948 Load currencies from WooCommerce Core
  changelog/tweak-2251-load-currencies-from-wc-core
  client/components/account-status/account-fees/test/__snapshots__/index.js.snap
  client/components/account-status/account-fees/test/index.js
  client/components/account-status/test/__snapshots__/index.js.snap
  client/components/account-status/test/index.js
  client/components/deposits-information/test/__snapshots__/index.js.snap
  client/components/deposits-information/test/index.js
  client/payment-details/summary/test/index.js
  client/payment-details/timeline/test/__snapshots__/map-events.js.snap
  client/payment-details/timeline/test/index.js
  client/payment-details/timeline/test/map-events.js
  client/transactions/list/test/index.tsx
  client/utils/currency/index.js
  client/utils/currency/test/index.js
  includes/admin/class-wc-payments-admin.php
Labels: pr: needs review

#3811 Add support for platform checkout server side payment processing
  changelog/add-platform-checkout-server-side-payment-processing
  changelog/add-platform-checkout-server-side-payment-processing-2
  client/checkout/api/index.js
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments.php
Labels: type: enhancement, pr: needs review, status: has pr, category: core

#3901 Fix Printed receipt endpoint throws error when called from Jetpack API
  changelog/fix-3900-printed-receipt-endpoint-throws-error-when-called-from-jetpack-api
  includes/admin/class-wc-rest-payments-reader-controller.php
Labels: pr: ready to merge

#3967 Check for variables before using them to prevent possible errors during UPE checkout process.
  changelog/fix-3966-possible-fatal-during-upe-checkout
  includes/payment-methods/class-upe-payment-gateway.php
Labels: pr: needs review

#3944 Fix the menu badge inconsistency on wp.com
  changelog/fix-3941-fix-menu-notification-badge
  includes/admin/class-wc-payments-admin.php
Labels: pr: ready to merge

#3964 Revert "Clear cart for fraudulent payments"
  changelog/add-1659-generate-new-nonce-for-fraudulent-payments
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: ready to merge

#3918 TS migration for deposit list
  client/data/deposits/hooks.ts
  client/data/transactions/hooks.ts
  client/deposits/list/index.tsx
  client/deposits/list/test/__snapshots__/index.tsx.snap
  client/deposits/list/test/index.tsx
  client/globals.d.ts
  client/types/deposits.d.ts
Labels: pr: ready to merge

#3914 Do not enqueue admin assets if user cannot manage_woocommerce
  changelog/fix-do-not-enqueue-admin-assets-when-no-manage-woocommerce
  includes/class-wc-payments.php
  includes/multi-currency/Analytics.php
  includes/multi-currency/MultiCurrency.php
  tests/unit/multi-currency/test-class-analytics.php
Labels: type: enhancement, pr: ready to merge, category: performance, category: core

#3943 HACK week: TypeScript migration: client/card-readers/setings
  client/card-readers/settings/file-upload.tsx
  client/card-readers/settings/index.tsx
  client/card-readers/settings/test/__snapshots__/index.test.tsx.snap
  client/card-readers/settings/test/index.test.tsx
  client/types/disputes.d.ts
Labels: pr: ready to merge

#3983 Update subscriptions-core to `1.7.0`
  changelog/subscriptions-core-1.7.0-pr-103
  changelog/subscriptions-core-1.7.0-pr-115
  changelog/subscriptions-core-1.7.0-pr-121
  changelog/subscriptions-core-1.7.0-pr-125
  composer.json
  composer.lock
Labels: pr: ready to merge

#3977 Changelog: document the guidelines in contribution notes.
  CONTRIBUTING.md
  changelog/dev-update-contribution-notes-changelog
Labels: pr: needs review

#3991 Revert "Add shortened customer bank statement"
  changelog/update-statement-descriptors
  client/data/settings/actions.js
  client/data/settings/hooks.js
  client/data/settings/selectors.js
  client/settings/transactions-and-deposits/index.js
  client/settings/transactions-and-deposits/test/index.test.js
  client/settings/transactions-and-deposits/text-length-help-input-wrapper.js
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: needs review, component: settings

#3990 Documentation: document usage of metadata generated from order.
  changelog/dev-document-order-metadata-usage
  includes/class-wc-payment-gateway-wcpay.php
Labels: pr: needs review

#3877 Remove business support URL validation
  changelog/fix-3874-business-url-validation-prevents-saving-settings
  client/card-readers/settings/sections/business-details.js
  includes/admin/class-wc-rest-payments-settings-controller.php
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
Labels: pr: needs review

#3993 Fix capital list formatting
  changelog/fix-3992-fix-table-value-formatting-in-capital-page-table
  client/additional-methods-setup/wizard/README.md
  client/capital/index.tsx
  client/components/active-loan-summary/index.tsx
  client/components/active-loan-summary/test/__snapshots__/index.js.snap
  client/components/tooltip/README.md
  client/data/deposits/test/overviews.fixture.json
  client/payment-details/timeline/map-events.js
  client/payment-details/timeline/test/__snapshots__/map-events.js.snap
Labels: pr: needs review, size: small, component: capital

#3925 Place WCPay subscriptions on-hold prior to renewal
  changelog/fix-3923-subscription-renew-action
  includes/subscriptions/class-wc-payments-subscriptions-event-handler.php
  tests/unit/helpers/class-wc-helper-subscription.php
Labels: pr: ready to merge, component: wcpay subscriptions

#3995 Deprecate the create customer endpoint
  changelog/update-3953-deprecate-create-customer-endpoint
  includes/admin/class-wc-rest-payments-orders-controller.php
  tests/unit/admin/test-class-wc-rest-payments-orders-controller.php
Labels: pr: needs review, component: card present

#4006 Replace the "colors" dependency with chalk
  changelog/remove-3961-colors-dependency
  package-lock.json
  package.json
  tasks/release.js
Labels: pr: ready to merge

#3954 Respect server-side toggle for platform checkout eligibility
  changelog/add-platform-checkout-eligibility-toggle
  includes/class-platform-checkout-tracker.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-blocks-payment-method.php
  includes/class-wc-payments-features.php
  includes/class-wc-payments.php
  tests/unit/test-class-platform-checkout-tracker.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-features.php
  tests/unit/test-class-wc-payments.php
Labels: component: platform checkout

#4005 Handle the case when some attributes from WC's currency data is null.
  changelog/fix-4001-payment-details-tostring-error
  includes/admin/class-wc-payments-admin.php
Labels: pr: ready to merge

#3898 Exclude Level3 data when capturing a terminal payment
  changelog/update-3861-ipp-exclude-l2-l3-data
  includes/admin/class-wc-rest-payments-orders-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge, component: card present

#3747 Fixed sed invocation in WP tests installabtion script, when running on MacOS
  bin/install-wp-tests.sh
  changelog/dev-3632-fix-bash-warning
Labels: pr: ready to merge

#3996 Add handling for refund failure in payment timeline
  changelog/add-1476-refund-failure-event
  client/components/payment-status-chip/mappings.js
  client/payment-details/timeline/map-events.js
  client/payment-details/timeline/test/__snapshots__/map-events.js.snap
  client/payment-details/timeline/test/map-events.js
  client/utils/charge/index.ts
Labels: pr: ready to merge

#3972 Allow filtering API request params
  changelog/add-api-request-params-filter
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: needs review

#3975 Prevent webhook duplicate actions
  changelog/update-3814-prevent-webhook-duplicate-actions
  includes/class-wc-payments-order-service.php
  includes/class-wc-payments-webhook-processing-service.php
  tests/unit/test-class-wc-payments-order-service.php
  tests/unit/test-class-wc-payments-webhook-reliability-service.php
Labels: pr: ready to merge, category: core

#3927 Add connect account page experiment
  changelog/add-3790-welcome-screen-experiment
  client/connect-account-page-experiment/index.js
  client/connect-account-page-experiment/treatment/illustrations/manage.svg
  client/connect-account-page-experiment/treatment/illustrations/multicurrency.svg
  client/connect-account-page-experiment/treatment/illustrations/payments.svg
  client/connect-account-page-experiment/treatment/illustrations/wcpay.svg
  client/connect-account-page-experiment/treatment/index.js
  client/connect-account-page-experiment/treatment/payment-methods/americanexpress.js
  client/connect-account-page-experiment/treatment/payment-methods/applepay.js
  client/connect-account-page-experiment/treatment/payment-methods/dinersclub.js
  client/connect-account-page-experiment/treatment/payment-methods/discover.js
  client/connect-account-page-experiment/treatment/payment-methods/giropay.js
  client/connect-account-page-experiment/treatment/payment-methods/googlepay.js
  client/connect-account-page-experiment/treatment/payment-methods/jcb.js
  client/connect-account-page-experiment/treatment/payment-methods/mastercard.js
  client/connect-account-page-experiment/treatment/payment-methods/sofort.js
  client/connect-account-page-experiment/treatment/payment-methods/unionpay.js
  client/connect-account-page-experiment/treatment/payment-methods/visa.js
  client/connect-account-page-experiment/treatment/strings.js
  client/connect-account-page-experiment/treatment/style.scss
  client/connect-account-page-experiment/treatment/test/__snapshots__/index.js.snap
  client/connect-account-page-experiment/treatment/test/index.js
  client/index.js
Labels: pr: needs review

#3994 Add fraud protection section in settings page
  changelog/add-fraud-protection-settings
  client/data/settings/actions.js
  client/data/settings/hooks.js
  client/data/settings/selectors.js
  client/settings/card-body/index.tsx
  client/settings/fraud-prevention/index.tsx
  client/settings/settings-manager/index.js
  includes/admin/class-wc-rest-payments-settings-controller.php
Labels: pr: ready to merge

#3951 KYC: New Onboarding Flow
  changelog/add-new-onboarding-flow
  client/components/onboarding-select-control/index.js
  client/components/onboarding-select-control/style.scss
  client/components/onboarding-select-control/test/__snapshots__/index.tsx.snap
  client/components/onboarding-select-control/test/index.tsx
  client/data/onboarding/action-types.ts
  client/data/onboarding/actions.ts
  client/data/onboarding/hooks.ts
  client/data/onboarding/index.ts
  client/data/onboarding/reducer.ts
  client/data/onboarding/resolvers.ts
  client/data/onboarding/selectors.ts
  client/data/onboarding/types.d.ts
  client/data/store.js
  client/index.js
  client/onboarding/index.js
  client/onboarding/index.scss
  client/onboarding/strings.js
  client/onboarding/tasks/add-business-info-task/index.js
  client/onboarding/tasks/add-business-info-task/test/__snapshots__/index.js.snap
  client/onboarding/tasks/add-business-info-task/test/index.js
  client/onboarding/tasks/setup-complete-task/index.js
  client/onboarding/tasks/setup-complete-task/test/__snapshots__/index.js.snap
  client/onboarding/tasks/setup-complete-task/test/index.js
  client/onboarding/test/__snapshots__/index.js.snap
  client/onboarding/test/index.js
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-onboarding-controller.php
  includes/class-wc-payments-onboarding-service.php
  includes/class-wc-payments.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  package-lock.json
  tests/unit/admin/test-class-wc-rest-payments-onboarding-controller.php
  tests/unit/bootstrap.php
  tests/unit/test-class-wc-payments-onboarding-service.php
  webpack.config.js
Labels: pr: ready to merge, component: kyc optimization

#4000 Adding Document list to WCPay client
  changelog/add-3929-add-document-records-list
  client/components/test-mode-notice/index.js
  client/components/test-mode-notice/test/__snapshots__/index.js.snap
  client/components/test-mode-notice/test/index.js
  client/data/documents/action-types.js
  client/data/documents/actions.js
  client/data/documents/hooks.ts
  client/data/documents/index.js
  client/data/documents/reducer.js
  client/data/documents/resolvers.js
  client/data/documents/selectors.js
  client/data/documents/test/reducer.js
  client/data/documents/test/resolvers.js
  client/data/documents/test/selectors.js
  client/data/index.ts
  client/data/store.js
  client/documents/filters/config.ts
  client/documents/filters/index.tsx
  client/documents/filters/style.scss
  client/documents/filters/test/__snapshots__/index.tsx.snap
  client/documents/filters/test/index.tsx
  client/documents/index.tsx
  client/documents/list/index.tsx
  client/documents/list/style.scss
  client/documents/list/test/__snapshots__/index.tsx.snap
  client/documents/list/test/index.tsx
  client/documents/strings.ts
  client/index.js
  client/transactions/filters/config.ts
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-documents-controller.php
  includes/class-wc-payments-features.php
  includes/class-wc-payments.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/test-class-wc-payments-features.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: ready to merge, component: invoices for processing fees

#4034 IPP HTML Receipts are missing fees and shipping
  changelog/fix-3984-add-shipping-fee
  includes/admin/class-wc-rest-payments-reader-controller.php
  includes/in-person-payments/class-wc-payments-in-person-payments-receipts-service.php
  includes/in-person-payments/class-wc-payments-printed-receipt-sample-order.php
  includes/in-person-payments/templates/html-in-person-payment-receipt.php
  tests/unit/admin/test-class-wc-rest-payments-readers-controller.php
Labels: pr: needs review

#4011 Add document download link and handler
  changelog/add-3942-document-download
  client/documents/list/index.tsx
  client/documents/list/test/__snapshots__/index.tsx.snap
  client/utils/index.js
  client/utils/test/index.js
  includes/admin/class-wc-rest-payments-documents-controller.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/js/jest-test-file-setup.js
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: ready to merge, component: invoices for processing fees

#3965 Fix/handle async failed refunds
  changelog/fix-handle-async-failed-refunds
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-utils.php
  includes/class-wc-payments-webhook-processing-service.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-utils.php
  tests/unit/test-class-wc-payments-webhook-processing-service.php
Labels: pr: ready to merge, category: core, component: webhooks

#4031 Add error notices when transactions cannot be retrieved
  changelog/fix-4029-error-retrieving-transactions-notices
  client/data/charges/resolvers.js
  client/data/charges/test/resolvers.js
  client/data/transactions/resolvers.js
  client/data/transactions/test/resolvers.js
Labels: pr: ready to merge

#4045 Update order note format to fix E2E tests
  changelog/fix-e2e-wcpay-merchant-full-refund-test
  includes/class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge, category: e2e

#4040 Add new onboarding flow experiment
  client/index.js
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-utils.php
Labels: pr: needs review

#4052 Translatable Strings for Business type, description and structure
  changelog/add-4026-tranlatable-strings
  client/data/onboarding/reducer.ts
  client/data/onboarding/selectors.ts
  client/data/onboarding/types.d.ts
  client/onboarding/strings.js
  client/onboarding/tasks/add-business-info-task/test/__snapshots__/index.js.snap
  client/onboarding/tasks/add-business-info-task/test/index.js
  client/onboarding/translations/descriptions.tsx
  client/onboarding/translations/structures.tsx
  client/onboarding/translations/types.tsx
Labels: pr: ready to merge

#3979 Add fraud protection token to checkout
  changelog/add-1659-generate-new-nonce-for-fraudulent-payments
  docs/rest-api/source/javascripts/lib/_jquery.js
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments.php
  includes/fraud-prevention/class-fraud-prevention-service.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/fraud-prevention/test-class-fraud-prevention-service.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: ready to merge

#3999 Add card readers page business url field client validation
  changelog/add-card-readers-inline-validation
  client/card-readers/settings/index.tsx
  client/card-readers/settings/sections/business-details.js
  client/card-readers/settings/sections/test/index.test.js
  client/settings/save-settings-section/index.js
Labels: pr: ready to merge

#4054 Tweak onboarding select control
  client/components/custom-select-control/index.js
  client/components/custom-select-control/style.scss
  client/components/custom-select-control/test/__snapshots__/index.tsx.snap
  client/components/custom-select-control/test/index.tsx
  client/components/onboarding-select-control/style.scss
  client/components/onboarding-select-control/test/__snapshots__/index.tsx.snap
  client/components/onboarding-select-control/test/index.tsx
  client/data/onboarding/selectors.ts
  client/onboarding/index.scss
  client/onboarding/tasks/add-business-info-task/index.js
  client/onboarding/tasks/add-business-info-task/test/__snapshots__/index.js.snap
Labels: pr: needs review

#4063 fix: payment method list icon
  changelog/frosso-patch-1
  client/payment-methods/index.js
Labels: pr: ready to merge

#4030 Fix price on payment request for variable subscription products
  changelog/fix-3536-payment-request-variable-subs-price
  includes/class-wc-payments-payment-request-button-handler.php
Labels: pr: ready to merge

#4049 Fix - Using additional payment methods "Pay for order" form triggers WCPay validation errors
  changelog/fix-pay-for-order-upe-checkout
  client/checkout/classic/index.js
  client/checkout/classic/upe.js
  client/checkout/utils/upe.js
Labels: pr: ready to merge, component: checkout, component: upe
