Repository Automattic/woocommerce-payments, pull requests merged in 2022-02, with the labels that each got.

#3688 Add more info for platform payment initialization
  includes/class-wc-payments.php
Labels: type: enhancement, pr: needs review, status: has pr, category: core, component: platform checkout

#3662 Platform Checkout - move email field to top of checkout and handle input
  client/checkout/blocks/index.js
  client/checkout/blocks/style.scss
  client/checkout/blocks/upe.js
  client/checkout/classic/index.js
  client/checkout/classic/style.scss
  client/checkout/classic/upe.js
  client/checkout/utils/platform-checkout.js
  includes/class-wc-payments.php
Labels: component: platform checkout

#3722 Use base64 image for the menu icon
  includes/admin/class-wc-payments-admin.php
Labels: pr: needs review

#3718 Fix checkout on block-based themes
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  includes/payment-methods/class-upe-payment-gateway.php
  readme.txt
Labels: pr: needs review

#3731 Show Currency filter in Disputes page
  changelog.txt
  client/disputes/filters/test/index.tsx
  client/disputes/index.tsx
  client/types/disputes.d.ts
  readme.txt
Labels: pr: needs review

#3733 Saving Payments -> Settings fails because of the Card Readers settings validation along with E2E tests
  includes/admin/class-wc-rest-payments-settings-controller.php
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
Labels: pr: ready to merge

#3616 Add EPS as UPE payment method
  assets/css/admin.css
  assets/images/payment-methods/eps.svg
  changelog.txt
  client/additional-methods-setup/constants.js
  client/additional-methods-setup/upe-preview-methods-selector/test/add-payment-methods-task.test.js
  client/additional-methods-setup/upe-preview-methods-selector/test/setup-complete-task.test.js
  client/components/currency-information-for-methods/test/index.test.js
  client/components/payment-method-details/index.js
  client/components/payment-methods-checkboxes/test/index.js
  client/gateway-icons/eps.js
  client/payment-details/payment-method/eps/bank-list.js
  client/payment-details/payment-method/eps/index.js
  client/payment-details/payment-method/index.js
  client/payment-methods-map.js
  client/payment-methods/test/index.js
  client/settings/payment-method-icon/test/index.js
  client/types/payment-methods.d.ts
  client/utils/account-fees.tsx
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments.php
  includes/payment-methods/class-eps-payment-method.php
  includes/payment-methods/class-upe-payment-gateway.php
  readme.txt
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
  tests/unit/multi-currency/test-class-payment-methods-compatibility.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
Labels: pr: ready to merge, component: upe

#3684 Cache UPE intents for reuse
  changelog.txt
  client/checkout/classic/upe.js
  client/utils/index.js
  client/utils/test/index.js
  includes/class-wc-payment-gateway-wcpay.php
  includes/payment-methods/class-upe-payment-gateway.php
  readme.txt
Labels: pr: needs review, component: upe

#3741 Add redirect to view Capital financing offers
  client/overview/index.js
  client/overview/test/index.js
  includes/class-wc-payments-account.php
  includes/class-wc-payments-features.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/test-class-wc-payments-account-capital.php
  tests/unit/test-class-wc-payments-features.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: ready to merge, component: capital

#3744 Update: fix typos in IDC modal text
  woocommerce-payments.php
Labels: pr: ready to merge

#3746 Use dedicated data attributes for E2E tests
  client/disputes/evidence/index.js
  client/disputes/evidence/test/__snapshots__/index.js.snap
  client/payment-details/timeline/map-events.js
  client/payment-details/timeline/test/__snapshots__/index.js.snap
  client/payment-details/timeline/test/__snapshots__/map-events.js.snap
  client/settings/transactions-and-deposits/index.js
  tests/e2e/specs/wcpay/merchant/merchant-disputes-save-for-editing.spec.js
  tests/e2e/specs/wcpay/merchant/merchant-disputes-submit-losing.spec.js
  tests/e2e/specs/wcpay/merchant/merchant-disputes-submit-winning.spec.js
  tests/e2e/specs/wcpay/merchant/merchant-orders-manual-capture.spec.js
  tests/e2e/utils/flows.js
Labels: pr: needs review

#3682 New platform checkout user on checkout page
  client/checkout/platform-checkout/index.js
  client/components/platform-checkout/hooks/use-platform-checkout-user.js
  client/components/platform-checkout/hooks/use-selected-payment-method.js
  client/components/platform-checkout/icons/lock-icon/icon.svg
  client/components/platform-checkout/icons/lock-icon/index.js
  client/components/platform-checkout/icons/phone-icon/icon.svg
  client/components/platform-checkout/icons/phone-icon/index.js
  client/components/platform-checkout/save-user/about-platform-checkout.js
  client/components/platform-checkout/save-user/additional-information.js
  client/components/platform-checkout/save-user/agreement.js
  client/components/platform-checkout/save-user/checkout-page-save-user.js
  client/components/platform-checkout/save-user/style.scss
  client/components/platform-checkout/save-user/test/checkout-page-save-user.test.js
  includes/class-wc-payments.php
  includes/platform-checkout-user/class-platform-checkout-save-user.php
  webpack.config.js
Labels: pr: ready to merge, component: platform checkout

#3717 Add payout and paydown transactions to the transactions list
  client/data/transactions/hooks.ts
  client/data/transactions/resolvers.js
  client/data/transactions/test/resolvers.js
  client/globals.d.ts
  client/settings/wcpay-settings-context.js
  client/style.scss
  client/transactions/declarations.d.ts
  client/transactions/filters/config.ts
  client/transactions/filters/index.tsx
  client/transactions/filters/style.scss
  client/transactions/list/index.tsx
  client/transactions/list/test/__snapshots__/index.tsx.snap
  client/transactions/list/test/index.tsx
  client/transactions/strings.ts
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-transactions-controller.php
  includes/class-wc-payments-account.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: ready to merge, component: capital

#3699 Phone number input with country code
  client/components/platform-checkout/hooks/use-phone-number-validity.js
  client/components/platform-checkout/save-user/checkout-page-save-user.js
  client/components/platform-checkout/save-user/phone-number-input.js
  client/components/platform-checkout/save-user/style.scss
  client/components/platform-checkout/save-user/test/phone-number-input.test.js
  package-lock.json
  package.json
  tests/js/jest.config.js
  webpack.config.js
Labels: type: enhancement, category: projects, component: platform checkout

#3756 Allow to upload files as platform account
  client/card-readers/settings/file-upload.js
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: needs review

#3774 Update subscriptions-core to `1.6.4`
  changelog.txt
  composer.json
  composer.lock
  readme.txt
Labels: pr: needs review, component: wcpay subscriptions

#3772 Fix subscription PM changes.
  includes/payment-methods/class-upe-payment-gateway.php
Labels: pr: ready to merge

#3773 Temporarily skip failing E2E tests
  tests/e2e/specs/wcpay/merchant/merchant-a-onboarding-setup.spec.js
Labels: pr: ready to merge

#3519 Add filter for payment request button payment method title
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-payment-request-button-handler.php
  readme.txt
Labels: pr: ready to merge

#3785 Fix not populated loan variable without account cache
  includes/class-wc-payments-account.php
Labels: type: bug, pr: needs review, priority: high

#3758 Add paydown timeline item to transaction details
  client/payment-details/summary/index.js
  client/payment-details/summary/test/__snapshots__/index.js.snap
  client/payment-details/timeline/map-events.js
  client/payment-details/timeline/test/__snapshots__/map-events.js.snap
  client/payment-details/timeline/test/map-events.js
Labels: pr: ready to merge, component: capital

#3755 Move class name to the outer level
  client/checkout/platform-checkout/index.js
  client/components/platform-checkout/save-user/checkout-page-save-user.js
Labels: type: bug, pr: needs review, component: alternative payment methods

#3685 Add Jetpack Changelogger
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/check-changelog.yml
  .github/workflows/pre-release-publish-on-tag.yaml
  bin/check-changelog.sh
  bin/class-wcpay-changelog-formatter.php
  changelog.txt
  changelog/.gitkeep
  changelog/add-3645-jp-changelogger
  composer.json
  composer.lock
  package.json
  readme.txt
Labels: pr: ready to merge

#3674 Add an endpoint to retrieve an uploaded file
  changelog.txt
  changelog/add-3595-retrieve-uploaded-files
  includes/admin/class-wc-rest-payments-disputes-controller.php
  includes/admin/class-wc-rest-payments-files-controller.php
  includes/class-wc-payments-file-service.php
  includes/class-wc-payments.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  readme.txt
  tests/unit/admin/test-class-wc-rest-payments-files-controller.php
  tests/unit/bootstrap.php
Labels: pr: needs review

#3736 Load iframe if correct email is entered
  client/checkout/blocks/fields.js
  client/checkout/blocks/index.js
  client/checkout/blocks/style.scss
  client/checkout/blocks/upe.js
  client/checkout/classic/index.js
  client/checkout/classic/style.scss
  client/checkout/classic/upe.js
  client/checkout/platform-checkout/email-input-iframe.js
  client/checkout/platform-checkout/style.scss
  client/checkout/utils/platform-checkout.js
  client/components/platform-checkout/index.tsx
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-blocks-payment-method.php
  webpack.config.js
Labels: type: bug, category: accessibility, needs prioritisation, component: platform checkout

#3763 Add jetpack-sync package to support Woo Mobile
  changelog/add-jetpack-sync-2nd
  composer.json
  composer.lock
  woocommerce-payments.php
Labels: pr: needs review

#3789 Fix Stripe Level 3 data limit for orders with more than 200 different products
  changelog/fix-stripe-200-level3-limit
  includes/class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge

#3782 Cache UPE intents for reuse (WC Session edition)
  changelog/fix-3602-redundant-upe-intents
  client/checkout/classic/upe.js
  client/checkout/utils/upe.js
  includes/class-wc-payment-gateway-wcpay.php
  includes/payment-methods/class-upe-payment-gateway.php
Labels: pr: ready to merge, component: upe, category: core

#3822 Remove Capital feature flag
  changelog/update-3804-remove-capital-feature-flag
  client/globals.d.ts
  client/overview/index.js
  client/overview/test/index.js
  client/payment-details/summary/index.js
  client/payment-details/timeline/map-events.js
  client/payment-details/timeline/test/map-events.js
  client/transactions/filters/config.ts
  client/transactions/filters/test/__snapshots__/index.tsx.snap
  client/transactions/strings.ts
  includes/class-wc-payments-account.php
  includes/class-wc-payments-features.php
  tests/unit/test-class-wc-payments-account-capital.php
  tests/unit/test-class-wc-payments-account.php
  tests/unit/test-class-wc-payments-features.php
Labels: pr: ready to merge, component: capital

#3788 Add card reader print receipt branding logo
  changelog.txt
  changelog/add-3559-card-readers-print-receipt-logo
  includes/admin/class-wc-rest-payments-reader-controller.php
  includes/in-person-payments/class-wc-payments-in-person-payments-receipts-service.php
  includes/in-person-payments/templates/html-in-person-payment-receipt.php
  readme.txt
  tests/unit/admin/test-class-wc-rest-payments-readers-controller.php
  tests/unit/in-person-payments/test-class-wc-payments-in-person-payments-receipts-service.php
Labels: pr: needs review

#3821 Conditionally add subscription payment gateway features
  changelog/fix-3819-subscriptions-support-flags
  includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php
  includes/subscriptions/class-wc-payments-subscription-service.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-trait.php
Labels: pr: ready to merge, component: wcpay subscriptions

#3837 Enable capture terminal payment for succeeded intents
  changelog/update-3764-register-captured-terminal-payment
  includes/admin/class-wc-rest-payments-orders-controller.php
  tests/unit/admin/test-class-wc-rest-payments-orders-controller.php
Labels: pr: ready to merge, component: card present

#3838 Fix WP & WC versions for E2E Tests + Optimizations
  .github/workflows/e2e-test.yml
  tests/e2e/README.md
  tests/e2e/env/docker-compose.yml
  tests/e2e/env/setup.sh
  tests/e2e/env/shared.sh
Labels: pr: ready to merge, category: e2e, category: devops, type: developer experience

#3748 Add IPP print receipt preview
  changelog/add-3561-preview-card-reader-receipts
  client/card-readers/preview-receipt/index.tsx
  client/card-readers/preview-receipt/previewer.tsx
  client/card-readers/preview-receipt/receipt.tsx
  client/card-readers/preview-receipt/style.scss
  client/card-readers/preview-receipt/test/__snapshots__/preview-receipt.test.tsx.snap
  client/card-readers/preview-receipt/test/__snapshots__/printed-receipt-previewer.test.tsx.snap
  client/card-readers/preview-receipt/test/preview-receipt.test.tsx
  client/card-readers/preview-receipt/test/printed-receipt-previewer.test.tsx
  client/card-readers/settings/index.js
  client/card-readers/settings/test/__snapshots__/index.test.js.snap
  client/index.js
  client/types/card-readers.d.ts
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-reader-controller.php
  includes/in-person-payments/class-wc-payments-in-person-payments-receipts-service.php
  includes/in-person-payments/class-wc-payments-printed-receipt-sample-order.php
  includes/in-person-payments/templates/html-in-person-payment-receipt.php
  tests/unit/admin/test-class-wc-rest-payments-readers-controller.php
Labels: pr: ready to merge

#3675 Add/order service
  changelog/add-order-service
  includes/admin/class-wc-rest-payments-orders-controller.php
  includes/admin/class-wc-rest-payments-webhook-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-order-service.php
  includes/class-wc-payments-utils.php
  includes/class-wc-payments.php
  includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php
  includes/payment-methods/class-cc-payment-gateway.php
  includes/payment-methods/class-upe-payment-gateway.php
  tests/unit/admin/test-class-wc-rest-payments-orders-controller.php
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
  tests/unit/admin/test-class-wc-rest-payments-tos-controller.php
  tests/unit/admin/test-class-wc-rest-payments-webhook.php
  tests/unit/admin/test-class-wc-rest-upe-flag-toggle-controller.php
  tests/unit/helpers/class-wc-helper-subscriptions.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
  tests/unit/test-class-wc-payment-gateway-wcpay-payment-types.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-payment-method-order-note.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-order-service.php
  tests/unit/test-class-wc-payments-payment-request-button-handler.php
Labels: pr: needs review, type: technical debt

#3851 Fix the styling issue in the subscription product publish modal.
  changelog/fix-3840-modal-css-issue
  client/subscription-product-onboarding/style.scss
Labels: pr: ready to merge, component: wcpay subscriptions

#3796 Jetpack Tracking integration
  changelog/add-jetpack-tracking
  client/tracks/index.js
  composer.json
  composer.lock
  includes/class-platform-checkout-tracker.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-payment-request-button-handler.php
  includes/class-wc-payments.php
  includes/wc-payment-api/class-wc-payments-http.php
  tests/unit/bootstrap.php
  tests/unit/test-class-platform-checkout-tracker.php
Labels: component: platform checkout
