Repository Automattic/woocommerce-payments, pull requests merged in 2022-06, with the labels that each got.

#4206 fix proposal for Apple pay issue w/ WordPress in subfolder
  changelog/apple-pay-folder-wordpress-fix
  includes/class-wc-payments-apple-pay-registration.php
Labels: pr: needs review

#4304 In-Person Payments: fix an error in store location endpoint when blog name is empty
  changelog/fix-4305-ipp-failure-in-store-location-endpoint
  includes/admin/class-wc-rest-payments-terminal-locations-controller.php
  tests/unit/admin/test-class-wc-rest-payments-terminal-locations-controller.php
Labels: pr: ready to merge

#4301 Pass capture_method preference to platform store
  changelog/fix-platform-capture-method
  includes/class-wc-payments.php
Labels: pr: needs review

#4307 Update payment in renewal order from subscriptions
  changelog/fix-2813-payment-method-copy-subscriptions
  includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php
Labels: pr: needs review

#4322 Fix refunding of orders without _payment_method_id
  changelog/fix-4297-payment-method-refund-error
  includes/class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-refund.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge

#4325 Update subscriptions-core to 2.1.0
  changelog/subscriptions-core-2.1.0
  changelog/subscriptions-core-2.1.0-2
  composer.json
  composer.lock
Labels: pr: needs review, component: wcpay subscriptions

#4303 Fix webhook idempotency again (for payment intents)
  changelog/re-fix-3783-webhook-idempotency
  includes/class-wc-payments-order-service.php
  tests/unit/test-class-wc-payments-order-service.php
Labels: pr: needs review

#4340 Display the "Respond by" dispute date in local time
  changelog/fix-4338-dispute-utc-time
  client/disputes/index.tsx
  client/disputes/test/__snapshots__/index.tsx.snap
Labels: pr: needs review, component: disputes

#4346 Add has_card_readers_available flag to conditionally display Card readers page
  changelog/add-4190-card-reader-menu-toggle
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-account.php
Labels: pr: needs review

#4316 Add/stripelink in blocks
  changelog/add-stripelink-in-blocks
  client/checkout/blocks/style.scss
  client/checkout/blocks/upe-fields.js
  client/checkout/blocks/upe.js
  client/checkout/classic/upe.js
  client/checkout/constants.js
  client/checkout/stripe-link/index.js
Labels: pr: needs review

#4349 Add host.docker.internal extra host
  changelog/chore-host-docker-internal-linux
  docker-compose.yml
Labels: type: enhancement

#4354 Extend create intentions endpoint
  changelog/add-extend-create-intentions-endpoint
  docs/rest-api/source/includes/wp-api-v3/order.md
  includes/admin/class-wc-rest-payments-orders-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-order-service.php
  includes/constants/class-payment-method.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/admin/test-class-wc-rest-payments-orders-controller.php
Labels: pr: ready to merge

#4336 Update WC_Payments_API_Intention and WC_Payments_API_Charge constructors
  changelog/update-3122-payment-intent
  includes/admin/class-wc-rest-payments-orders-controller.php
  includes/admin/class-wc-rest-payments-reader-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-utils.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/subscriptions/class-wc-payments-invoice-service.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  includes/wc-payment-api/models/class-wc-payments-api-charge.php
  includes/wc-payment-api/models/class-wc-payments-api-intention.php
  tests/unit/admin/test-class-wc-rest-payments-orders-controller.php
  tests/unit/admin/test-class-wc-rest-payments-readers-controller.php
  tests/unit/helpers/class-wc-helper-intention.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
  tests/unit/subscriptions/test-class-wc-payments-invoice-service.php
  tests/unit/test-class-wc-payment-gateway-wcpay-payment-types.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-refund.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge

#4335 Disable new skeleton loader experience
  changelog/update-4327-disable-stripe-loader
  client/checkout/blocks/upe-fields.js
  client/checkout/classic/upe.js
Labels: pr: ready to merge

#4361 Add "Needs Response" disputes page filter option
  changelog/add-4124-disputes-display-needs-response-filter-option
  client/data/disputes/hooks.ts
  client/data/disputes/resolvers.js
  client/disputes/filters/config.ts
  client/disputes/filters/test/__snapshots__/index.tsx.snap
  client/disputes/filters/test/index.tsx
  client/transactions/declarations.d.ts
  includes/admin/class-wc-rest-payments-disputes-controller.php
Labels: pr: ready to merge, component: disputes, category: core

#4365 Hide Platform Checkout iframe on browser back button
  changelog/fix-4364-hide-platform-checkout-iframe-on-browser-back-button
  client/checkout/platform-checkout/email-input-iframe.js
Labels: component: platform checkout

#4228 Use recommended order currency API for multicurrency subscription renewal | switch | resubscribe
  changelog/fix-4152-subscribe-renew-multicurrency-order-meta-api
  includes/multi-currency/Compatibility/WooCommerceSubscriptions.php
  tests/unit/multi-currency/compatibility/test-class-woocommerce-subscriptions.php
Labels: pr: in progress

#4326 Add a notification badge to disputes admin menu item indicating disputes needing response
  changelog/add-dispute-notification-badge
  client/data/disputes/actions.js
  includes/admin/class-wc-payments-admin.php
  includes/class-database-cache.php
  includes/class-wc-payments-webhook-processing-service.php
  includes/class-wc-payments.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/admin/test-class-wc-payments-admin.php
  tests/unit/test-class-wc-payments-webhook-processing-service.php
Labels: pr: needs review

#4324 Add order update sync webhook for platform checkout
  changelog/add-3960-create-platform-checkout-webhook
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments.php
  includes/platform-checkout/class-platform-checkout-order-status-sync.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/platform-checkout/test-class-platform-checkout-order-status-sync.php
Labels: component: platform checkout

#4369 Platform Checkout settings responsiveness
  changelog/fix-4337-platform-checkout-settings-responsive
  client/settings/express-checkout-settings/index.js
  client/settings/express-checkout-settings/platform-checkout-preview.js
  client/settings/express-checkout-settings/platform-checkout-settings.js
  client/settings/express-checkout-settings/test/platform-checkout-settings.test.js
Labels: component: platform checkout
