Repository Automattic/woocommerce-payments, pull requests merged in 2022-01, with the labels that each got.

#3589 Fix UPE validation error visibility
  changelog.txt
  client/checkout/classic/upe.js
  readme.txt
Labels: pr: ready to merge

#3597 Upgrade WP from 5.4 to 5.6 for the edge case in the compatibility CI tests
  .github/workflows/compatibility.yml
  .github/workflows/php-lint-test.yml
  bin/install-wp-tests.sh
  bin/run-ci-tests.bash
Labels: pr: needs review, category: devops

#3475 HACK week: use new PHP 8.0/8.1 functions across codebase and add symfony polyfills to enable this
  composer.json
  composer.lock
  includes/class-wc-payments-explicit-price-formatter.php
  includes/class-wc-payments-translations-loader.php
  includes/class-wc-payments-utils.php
  includes/class-wc-payments.php
  includes/multi-currency/Analytics.php
  phpcs-compat.xml.dist
Labels: pr: ready to merge, status: on hold

#3477 Re-Initiate transactions export in server via download button (un-revert)
  changelog.txt
  client/data/transactions/resolvers.js
  client/transactions/list/index.tsx
  client/transactions/list/test/index.tsx
  includes/admin/class-wc-rest-payments-transactions-controller.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  readme.txt
Labels: pr: needs review

#3601 Change file ignore regex to `--extensions` argument in phpcs configuration
  phpcs-compat.xml.dist
  phpcs.xml.dist
Labels: pr: ready to merge, type: task, category: devops

#3605 Fix emoji flag rendering in Currency Switcher Block widget
  changelog.txt
  includes/multi-currency/Settings.php
  readme.txt
  tests/unit/multi-currency/test-class-settings.php
Labels: pr: ready to merge

#3586 Remove the custom Translations Loader initialization
  changelog.txt
  includes/class-wc-payments-translations-loader.php
  includes/class-wc-payments.php
  readme.txt
Labels: pr: needs review, category: i18n

#3592 Bump Tested Up To Versions for 3.6 Release
  .github/workflows/compatibility.yml
  .github/workflows/e2e-test.yml
  .github/workflows/php-lint-test.yml
  changelog.txt
  readme.txt
  woocommerce-payments.php
Labels: pr: ready to merge, category: core

#3603 Set billing details name from payerName to allow order placement in WooCommerce
  changelog.txt
  client/payment-request/utils/normalize.js
  readme.txt
Labels: pr: needs review

#3608 Modified the Post-merge task to provide link to QA Testing Instructions
  .github/PULL_REQUEST_TEMPLATE.md
Labels: pr: ready to merge

#3590 Loads the Sift tracking JS after onboarding, regardless of where the merchant has been dropped into.
  includes/class-wc-payments-fraud-service.php
Labels: pr: ready to merge

#3534 Update Payment Element from beta version to release version.
  changelog.txt
  client/checkout/api/index.js
  client/checkout/classic/upe.js
  readme.txt
Labels: pr: ready to merge, component: upe

#3612 Logged exceptions while listing disputes
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: ready to merge

#3587 Adjust shopper WC Blocks e2e tests that were failing
  package-lock.json
  tests/e2e/specs/blocks/shopper/shopper-wc-blocks-checkout-failures.spec.js
  tests/e2e/specs/blocks/shopper/shopper-wc-blocks-checkout-purchase.spec.js
  tests/e2e/utils/flows.js
Labels: pr: ready to merge, type: task, component: tests, category: engineering, category: e2e, needs prioritisation

#3599 Update subscriptions-core to `1.4.0`.
  changelog.txt
  composer.json
  composer.lock
  readme.txt
Labels: pr: needs review

#3611 Refactor to split the attach intent logic with the logic to complete …
  includes/admin/class-wc-rest-payments-orders-controller.php
  includes/admin/class-wc-rest-payments-webhook-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-utils.php
  includes/payment-methods/class-upe-payment-gateway.php
  tests/unit/multi-currency/test-class-analytics.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: needs review

#3623 Suppress extra console logs for E2E tests
  tests/e2e/config/jest.setup.js
Labels: pr: ready to merge

#3635 Aligned the changelog in readme.txt and changelog.txt
  changelog.txt
  readme.txt
Labels: pr: ready to merge

#3637 Update capability request to use the gateway map
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge

#3628 Handle payment_failed payment intent webhooks.
  changelog.txt
  includes/admin/class-wc-rest-payments-webhook-controller.php
  readme.txt
  tests/unit/admin/test-class-wc-rest-payments-webhook.php
Labels: pr: ready to merge

#3634 Update subscriptions-core to `1.5.0`
  changelog.txt
  composer.json
  composer.lock
  readme.txt
Labels: pr: ready to merge, component: wcpay subscriptions

#3598 Display a notice on checkout when server responds with an Amount_Too_Small_Exception when creating WC Pay Subscriptions
  changelog.txt
  includes/subscriptions/class-wc-payments-subscription-service.php
  readme.txt
Labels: pr: ready to merge

#3644 Update subscriptions-core to `1.6.0`
  changelog.txt
  composer.json
  composer.lock
  readme.txt
Labels: pr: needs review, component: wcpay subscriptions

#3636 Update: remove asset blocking from E2E tests
  tests/e2e/config/jest.setup.js
Labels: pr: ready to merge

#3545 Add pagination and summary to Disputes table
  changelog.txt
  client/components/dispute-status-chip/mappings.ts
  client/data/disputes/action-types.js
  client/data/disputes/actions.js
  client/data/disputes/hooks.ts
  client/data/disputes/reducer.js
  client/data/disputes/resolvers.js
  client/data/disputes/selectors.js
  client/data/disputes/test/reducer.js
  client/data/disputes/test/resolvers.js
  client/data/disputes/test/selectors.js
  client/disputes/index.tsx
  client/disputes/style.scss
  client/disputes/test/__snapshots__/index.tsx.snap
  client/disputes/test/index.tsx
  client/types/charges.d.ts
  client/types/disputes.d.ts
  includes/admin/class-wc-rest-payments-disputes-controller.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  readme.txt
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: ready to merge, status: blocked

#3653 Update subscriptions-core version to 1.6.1
  composer.json
  composer.lock
Labels: pr: ready to merge, component: wcpay subscriptions

#3650 Better handling of failed payment_intent webhooks.
  includes/admin/class-wc-rest-payments-webhook-controller.php
  includes/class-wc-payments-utils.php
  includes/constants/class-payment-method.php
  tests/unit/admin/test-class-wc-rest-payments-webhook.php
Labels: pr: needs review

#3663 Only limit subscription interval to one year if the Subscriptions plugin not active
  changelog.txt
  includes/subscriptions/class-wc-payments-product-service.php
  readme.txt
Labels: pr: ready to merge, component: wcpay subscriptions

#3639 Disable unavailable payment methods due to country restrictions
  includes/payment-methods/class-upe-payment-gateway.php
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
Labels: pr: ready to merge

#3652 Add the WCPay customer ID to the WP user during checkout
  changelog.txt
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-customer-service.php
  includes/payment-methods/class-upe-payment-gateway.php
  readme.txt
Labels: pr: needs review, component: wcpay subscriptions, category: projects

#3658 Fix fee amount not showing negative value in transactions CSV
  changelog.txt
  client/transactions/list/index.tsx
  client/transactions/list/test/index.tsx
  readme.txt
Labels: pr: ready to merge

#3660 Fix stripe.confirmSetup() expected either `elements` or `clientSecret`.
  client/checkout/classic/upe.js
Labels: pr: needs review, component: upe

#3669 Bump subscriptions-core to 1.6.2.
  composer.json
  composer.lock
Labels: pr: needs review

#3617 Fix currency name not translated in the Overview card title
  changelog.txt
  client/utils/currency/index.js
  readme.txt
Labels: pr: needs review

#3677 Fix e2e to download wcs release instead of zipped repo.
  tests/e2e/env/setup.sh
Labels: pr: ready to merge

#3683 Fix disable unavailable payment methods returning associative array
  includes/payment-methods/class-upe-payment-gateway.php
Labels: pr: needs review

#3630 Add BECS payment method
  assets/css/admin.css
  assets/images/payment-methods/bank_debit.svg
  changelog.txt
  client/additional-methods-setup/constants.js
  client/checkout/classic/index.js
  client/checkout/constants.js
  client/components/payment-method-details/index.js
  client/gateway-icons/bank-debit.js
  client/payment-details/payment-method/becs/index.js
  client/payment-details/payment-method/index.js
  client/payment-methods-map.js
  client/payment-methods/test/index.js
  client/settings/payment-method-icon/test/index.js
  client/types/payment-methods.d.ts
  client/utils/account-fees.tsx
  includes/admin/class-wc-rest-payments-webhook-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments.php
  includes/constants/class-payment-method.php
  includes/payment-methods/class-becs-payment-method.php
  includes/payment-methods/class-upe-payment-gateway.php
  readme.txt
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
  tests/unit/multi-currency/test-class-payment-methods-compatibility.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
Labels: pr: ready to merge

#3609 Add Disputes filters
  changelog.txt
  client/data/disputes/actions.js
  client/data/disputes/hooks.ts
  client/data/disputes/reducer.js
  client/data/disputes/resolvers.js
  client/data/disputes/selectors.js
  client/data/disputes/test/reducer.js
  client/data/disputes/test/resolvers.js
  client/data/disputes/test/selectors.js
  client/disputes/details/index.tsx
  client/disputes/filters/config.ts
  client/disputes/filters/index.tsx
  client/disputes/filters/test/__snapshots__/index.tsx.snap
  client/disputes/filters/test/index.tsx
  client/disputes/index.tsx
  client/disputes/strings.ts
  client/disputes/test/__snapshots__/index.tsx.snap
  client/transactions/declarations.d.ts
  client/types/disputes.d.ts
  includes/admin/class-wc-rest-payments-disputes-controller.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  readme.txt
Labels: pr: needs review

#3626 Add sorting to Disputes list
  changelog.txt
  client/data/disputes/hooks.ts
  client/data/disputes/resolvers.js
  client/data/disputes/test/resolvers.js
  client/disputes/index.tsx
  client/disputes/test/__snapshots__/index.tsx.snap
  client/disputes/test/index.tsx
  client/types/disputes.d.ts
  readme.txt
Labels: pr: ready to merge

#3706 Update `get_enabled_payment_method_currencies` to support more payment methods
  includes/multi-currency/PaymentMethodsCompatibility.php
  tests/unit/multi-currency/test-class-payment-methods-compatibility.php
Labels: pr: needs review

#3704 Add currency to Disputes export
  changelog.txt
  client/disputes/index.tsx
  client/disputes/test/index.tsx
  client/types/disputes.d.ts
  readme.txt
Labels: type: bug, pr: ready to merge, component: disputes, category: core

#3714 Skip flaky subscription tests
  tests/e2e/specs/subscriptions/merchant/merchant-subscriptions-renew-action-scheduler.spec.js
  tests/e2e/specs/subscriptions/merchant/merchant-subscriptions-renew-subscription.spec.js
Labels: pr: ready to merge

#3708 Revert Symfony polyfills
  changelog.txt
  composer.json
  composer.lock
  includes/class-wc-payments-explicit-price-formatter.php
  includes/class-wc-payments-utils.php
  includes/class-wc-payments.php
  includes/multi-currency/Analytics.php
  phpcs-compat.xml.dist
  readme.txt
Labels: pr: needs review

#3580 Add and config Jetpack IDC package
  assets/images/logo.svg
  changelog.txt
  client/banner/wcpay-logo.js
  client/components/jetpack-idc-notice/index.js
  client/connect-account-page/test/__snapshots__/index.js.snap
  client/globals.d.ts
  client/overview/index.js
  client/overview/test/index.js
  client/settings/payment-method-settings/test/index.js
  composer.json
  composer.lock
  includes/admin/class-wc-payments-admin.php
  readme.txt
  woocommerce-payments.php
Labels: pr: needs review

#3716 Bump minimum supported and tested up to version for 3.7 release
  .github/workflows/compatibility.yml
  .github/workflows/coverage.yml
  .github/workflows/e2e-test.yml
  .github/workflows/php-lint-test.yml
  changelog.txt
  phpcs.xml.dist
  readme.txt
  woocommerce-payments.php
Labels: pr: needs review

#3725 Add allow-plugins configuration to composer.json
  composer.json
Labels: pr: needs review

#3723 Add customer link in disputes list
  changelog.txt
  client/disputes/index.tsx
  client/disputes/test/__snapshots__/index.tsx.snap
  client/disputes/test/index.tsx
  readme.txt
Labels: pr: needs review
