Repository Automattic/woocommerce-payments, pull requests merged in 2022-12, with the labels that each got.

#5217 Fix the trigger-translations job in the post-release workflow
  .github/workflows/post-release-updates.yml
  changelog/fix-5216-translations-job-for-post-release
Labels: pr: ready to merge

#5220 Delete the old pre-release workflow
  .github/workflows/pre-release-publish-on-tag.yaml
  changelog/remove-5219-unused-publish-on-tag-workflow
Labels: pr: ready to merge

#5154 Check for valid deadline when setting Update Business Details task
  changelog/4846-update-by-jan-1970
  client/overview/task-list/tasks.js
  client/overview/task-list/test/tasks.js
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-account.php
Labels: pr: ready to merge

#5169 Warn merchant when deactivating WCPay plugin that WCPay Subscriptions (Stripe Billing )will continue renewing
  changelog/fix-5090-warn-deactivate-with-live-stripe-subscriptions
  includes/subscriptions/assets/js/plugin-page.js
  includes/subscriptions/class-wc-payments-subscription-service.php
  includes/subscriptions/class-wc-payments-subscriptions-plugin-notice-manager.php
  includes/subscriptions/templates/html-subscriptions-plugin-notice.php
  includes/subscriptions/templates/html-wcpay-deactivate-warning.php
Labels: component: wcpay subscriptions

#5130 Replace direct database queries in WCPay Subscription code which pulls orders and subscriptions via invoice or subscription id
  changelog/update-wcpay_subscription_direct_queries
  changelog/update-wcpay_subscription_direct_queries-sub_id
  includes/class-wc-payments-utils.php
  includes/subscriptions/class-wc-payments-invoice-service.php
  includes/subscriptions/class-wc-payments-subscription-service.php
  psalm-baseline.xml
  tests/unit/helpers/class-wc-helper-subscriptions.php
  tests/unit/subscriptions/test-class-wc-payments-subscriptions-event-handler.php
Labels: pr: needs review

#5257 Allow i18n for UPE checkout blocks error message
  changelog/fix-4612-checkout-blocks-upe-error-message-i18n
  client/checkout/blocks/upe-fields.js
  client/checkout/classic/upe.js
Labels: pr: ready to merge

#5250 Separate authorizations cache summary for live mode and test mode
  changelog/add-auhtorizations-cache-test-mode
  includes/admin/class-wc-payments-admin.php
  includes/class-database-cache.php
  includes/class-wc-payments-webhook-processing-service.php
Labels: pr: ready to merge

#5251 Fixes to the Currency Rates API
  changelog/dev-currency-rate-fixes
  includes/multi-currency/MultiCurrency.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/multi-currency/test-class-multi-currency.php
Labels: pr: ready to merge

#3011 Fix recurring payments on Indian CCs
  changelog/fix-2935-recurring-transactions-indian-ccs
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-webhook-processing-service.php
  includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  includes/wc-payment-api/models/class-wc-payments-api-intention.php
  tests/unit/helpers/class-wc-helper-subscription.php
  tests/unit/test-class-wc-payment-gateway-wcpay-payment-types.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php
  tests/unit/test-class-wc-payments-webhook-processing-service.php
Labels: pr: needs review

#5276 Filter Stripe Link payment method availability check by country
  changelog/fix-stripe-link-country-check
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-upe-checkout.php
  includes/notes/class-wc-payments-notes-set-up-stripelink.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/notes/test-class-wc-payments-notes-set-up-stripelink.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
Labels: pr: ready to merge

#5269 Support custom remote port for xDebug
  changelog/dev-support-custom-remote-port-for-xdebug
  docker-compose.yml
  docker/README.md
  docker/wordpress_xdebug/Dockerfile
Labels: pr: ready to merge

#5285 hide capture charge and cancel authorization on status complete/processing
  changelog/fix-4789-status-processing-before-capture
  includes/class-wc-payment-gateway-wcpay.php
Labels: pr: needs review

#5299 Make custom fees show up correctly in settings tooltip, whenever applicable
  changelog/fix-5255-custom-fee-tooltip-in-settings
  client/components/account-status/account-fees/index.js
  client/utils/account-fees.tsx
  client/utils/test/account-fees.tsx
Labels: pr: needs review

#5288 Prevent processing the wrong kind of webhook for a gateway
  changelog/fix-5266-webhook-processing
  includes/class-wc-payments-webhook-processing-service.php
  tests/unit/test-class-wc-payments-webhook-processing-service.php
Labels: pr: ready to merge

#5298 Fix translations in the deactivating WCPay Subscriptions warning file
  changelog/fix-5266-webhook-processing
  changelog/fix-setting-default-payment-method-subscriptions
  includes/class-wc-payments-webhook-processing-service.php
  includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php
  includes/subscriptions/templates/html-wcpay-deactivate-warning.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php
  tests/unit/test-class-wc-payments-webhook-processing-service.php
Labels: pr: needs review

#5284 HPOS: Fix subscriptions remaining on-hold after WCPay Subscription renewal
  changelog/fix-hpos-wcpay-subscription-renewals
  includes/subscriptions/class-wc-payments-subscriptions-event-handler.php
  tests/unit/subscriptions/test-class-wc-payments-subscriptions-event-handler.php
Labels: pr: needs review

#5306 Let code freeze workflow pass botwoo token secret to release-pr workflow
  .github/workflows/release-code-freeze.yml
  .github/workflows/release-pr.yml
  changelog/fix-release-code-freeze-workflow-secret
Labels: pr: ready to merge

#5287 Update save my info section
  changelog/update-1505-save-my-info-section
  client/checkout/platform-checkout/index.js
  client/components/platform-checkout/save-user/additional-information.js
  client/components/platform-checkout/save-user/agreement.js
  client/components/platform-checkout/save-user/checkout-page-save-user.js
  client/components/platform-checkout/save-user/container.js
  client/components/platform-checkout/save-user/style.scss
  client/components/platform-checkout/save-user/test/checkout-page-save-user.test.js
  client/settings/phone-input/index.tsx
  client/settings/phone-input/style.scss
Labels: pr: needs review

#5315 Provide return URL with platform init request
  changelog/add-dynamic-platform-checkout-return-url
  client/checkout/api/index.js
  client/checkout/api/test/index.test.js
  includes/class-wc-payments.php
Labels: pr: needs review

#4986 Add a class, which controls WCPay's mode
  changelog/add-core-mode-class
  includes/admin/class-wc-payments-admin-settings.php
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-accounts-controller.php
  includes/admin/class-wc-rest-payments-connection-tokens-controller.php
  includes/admin/class-wc-rest-payments-documents-controller.php
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-logger.php
  includes/class-platform-checkout-tracker.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-action-scheduler-service.php
  includes/class-wc-payments-apple-pay-registration.php
  includes/class-wc-payments-checkout.php
  includes/class-wc-payments-customer-service.php
  includes/class-wc-payments-fraud-service.php
  includes/class-wc-payments-order-service.php
  includes/class-wc-payments-payment-request-button-handler.php
  includes/class-wc-payments-upe-checkout.php
  includes/class-wc-payments.php
  includes/core/README.md
  includes/core/class-mode.php
  includes/multi-currency/Analytics.php
  includes/subscriptions/class-wc-payments-product-service.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/admin/test-class-wc-rest-payments-accounts-controller.php
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
  tests/unit/core/test-class-mode.php
  tests/unit/subscriptions/test-class-wc-payments-product-service.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-account.php
  tests/unit/test-class-wc-payments-action-scheduler-service.php
  tests/unit/test-class-wc-payments-customer-service.php
  tests/unit/test-class-wc-payments.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: ready to merge

#5322 Fix naming of REMOTE_PORT to more self-documented
  changelog/dev-tweak_remote_port_arg_for_xdebug
  docker-compose.yml
  docker/README.md
  docker/wordpress_xdebug/Dockerfile
Labels: pr: needs review

#5235 Implementation of Intent request classes
  includes/admin/class-wc-rest-payments-charges-controller.php
  includes/admin/class-wc-rest-payments-orders-controller.php
  includes/admin/class-wc-rest-payments-reader-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-webhook-processing-service.php
  includes/class-wc-payments.php
  includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php
  includes/core/server/class-request.php
  includes/core/server/class-response.php
  includes/core/server/request/class-cancel-intention.php
  includes/core/server/request/class-capture-intention.php
  includes/core/server/request/class-create-and-confirm-intention.php
  includes/core/server/request/class-create-and-confirm-setup-intention.php
  includes/core/server/request/class-create-intent.php
  includes/core/server/request/class-create-intention.php
  includes/core/server/request/class-create-setup-intention.php
  includes/core/server/request/class-generic.php
  includes/core/server/request/class-get-charge.php
  includes/core/server/request/class-get-intention.php
  includes/core/server/request/class-update-intention.php
  includes/core/server/request/class-woopay-create-and-confirm-setup-intention.php
  includes/core/server/request/class-woopay-create-intent.php
  includes/core/server/request/trait-level3.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/subscriptions/class-wc-payments-invoice-service.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  includes/woopay/services/class-checkout-service.php
  tests/WCPAY_UnitTestCase.php
  tests/unit/admin/test-class-wc-rest-payments-orders-controller.php
  tests/unit/admin/test-class-wc-rest-payments-readers-controller.php
  tests/unit/core/server/request/test-class-core-cancel-intention-request.php
  tests/unit/core/server/request/test-class-core-capture-intention-request.php
  tests/unit/core/server/request/test-class-core-create-intention-request.php
  tests/unit/core/server/request/test-class-core-create-setup-intention-request.php
  tests/unit/core/server/request/test-class-core-get-charge-request.php
  tests/unit/core/server/request/test-class-core-get-intention-request.php
  tests/unit/core/server/request/test-class-core-update-intention-request.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
  tests/unit/subscriptions/test-class-wc-payments-invoice-service.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-refund.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-payment-request-button-handler.php
Labels: pr: needs author reply

#5162 Introduce WCPay_Order
  changelog/add-4951-wcpay-order
  docs/metadata.md
  includes/admin/class-wc-rest-payments-orders-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-action-scheduler-service.php
  includes/class-wc-payments-order-service.php
  includes/class-wc-payments-webhook-processing-service.php
  includes/class-wc-payments.php
  includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/subscriptions/class-wc-payments-invoice-service.php
  includes/subscriptions/class-wc-payments-subscriptions.php
  tests/unit/admin/test-class-wc-rest-payments-orders-controller.php
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
  tests/unit/admin/test-class-wc-rest-payments-tos-controller.php
  tests/unit/admin/test-class-wc-rest-upe-flag-toggle-controller.php
  tests/unit/subscriptions/test-class-wc-payments-invoice-service.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-refund.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-action-scheduler-service.php
  tests/unit/test-class-wc-payments-order-service.php
  tests/unit/test-class-wc-payments-webhook-processing-service.php
Labels: pr: ready to merge

#5320 Use dedicated enum class for order status constants
  changelog/refactor-5286-order-status-constants-as-enum-class
  includes/admin/class-wc-rest-payments-orders-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-order-service.php
  includes/class-wc-payments-webhook-processing-service.php
  includes/class-wc-payments.php
  includes/constants/class-order-status.php
  includes/payment-methods/class-upe-payment-gateway.php
  tests/unit/admin/test-class-wc-rest-payments-orders-controller.php
  tests/unit/helpers/class-wc-helper-order.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-refund.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-order-service.php
  tests/unit/test-class-wc-payments-webhook-processing-service.php
Labels: pr: ready to merge

#5309 Retry API requests on network failures.
  changelog/tweak-api-retry-on-network-failure
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: ready to merge

#5247 Fix duplicate order: Store order ID to session, check it before update/create_confirm intents
  changelog/add-session-wcpay_pending_order
  client/checkout/api/index.js
  client/checkout/blocks/upe-fields.js
  client/checkout/classic/upe.js
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-order-success-page.php
  includes/constants/class-order-status.php
  includes/payment-methods/class-upe-payment-gateway.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
Labels: pr: needs review

#5209 Skip payment processing for WooPay's order validation request
  changelog/add-handle-woopay-order-validation
  includes/class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: status: blocked

#5348 Add `wp-i18n` as one of UPE script's dependencies.
  changelog/fix-5347-undefined-i18n-upe
  includes/payment-methods/class-upe-payment-gateway.php
Labels: pr: ready to merge

#5349 Release branch for 5.2.1
  changelog.txt
  changelog/fix-5197-required-checks-not-triggered-for-pr-created-by-workflow
  changelog/fix-5347-undefined-i18n-upe
  package-lock.json
  package.json
  readme.txt
  woocommerce-payments.php
Labels: pr: ready to merge

#5351 Revert release 5.2.1.
  changelog.txt
  changelog/fix-5197-required-checks-not-triggered-for-pr-created-by-workflow
  changelog/fix-5347-undefined-i18n-upe
  package-lock.json
  package.json
  readme.txt
  woocommerce-payments.php
Labels: pr: ready to merge

#5350 Pin setup repo composer version
  .github/actions/setup-repo/action.yml
  .github/workflows/php-compatibility.yml
  changelog/fix-php-compatibility-workflow
Labels: pr: needs review
