Repository Automattic/woocommerce-payments, pull requests merged in 2022-05, with the labels that each got.

#4211 Fix - UPE Appearance on WC Blocks
  changelog/fix-upe-blocks-appearance
  client/checkout/api/index.js
  client/checkout/api/test/index.test.js
  client/checkout/blocks/index.js
  client/checkout/blocks/upe-fields.js
  client/checkout/blocks/upe.js
  client/checkout/classic/upe.js
  client/checkout/upe-styles/index.js
  client/checkout/utils/request.js
  includes/payment-methods/class-upe-payment-gateway.php
Labels: pr: needs review, component: upe

#4225 Update Abacus KYC experiment version
  changelog/fix-update_kyc_experiment_version
  includes/class-wc-payments-utils.php
Labels: pr: ready to merge

#4237 Send merchant shop url to platform checkout
  changelog/platform-checkout-send-merchant-shop-url
  includes/class-wc-payments.php
Labels: component: platform checkout

#4235 change type with transaction type in transaction details url
  changelog/fix-type-parameter-in-transaction
  client/payment-details/index.js
  client/transactions/list/index.tsx
  client/transactions/list/test/__snapshots__/index.tsx.snap
Labels: pr: needs review

#4224 Fix empty phone and email value
  changelog/fix-empty-phone-email-value
  client/card-readers/settings/index.tsx
  client/card-readers/settings/sections/contacts-details.js
  includes/admin/class-wc-rest-payments-settings-controller.php
Labels: pr: ready to merge

#4242 Do not show country code on Platform Checkout opt-in
  changelog/fix-4241-platform-checkout-optin-country-code
  client/components/platform-checkout/save-user/phone-number-input.js
Labels: component: platform checkout

#4255 Fix the WCPay Subscriptions onboarding modal and toast on newer WC versions
  changelog/fix-4254-empty-state-modal
  client/subscription-product-onboarding/modal.js
  client/subscription-product-onboarding/toast.js
  includes/subscriptions/class-wc-payments-subscriptions-onboarding-handler.php
Labels: pr: needs review, component: wcpay subscriptions

#4212 Add fee details to order notes for successful payments
  changelog/add-order-note-fee-breakup
  includes/class-wc-payments-captured-event-note.php
  includes/class-wc-payments-order-service.php
  includes/class-wc-payments-utils.php
  includes/class-wc-payments.php
  tests/unit/admin/test-class-wc-rest-payments-orders-controller.php
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
  tests/unit/admin/test-class-wc-rest-payments-tos-controller.php
  tests/unit/admin/test-class-wc-rest-upe-flag-toggle-controller.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-captured-event-note.php
  tests/unit/test-class-wc-payments-order-service.php
  tests/unit/test-class-wc-payments-utils.php
  tests/unit/test-class-wc-payments-webhook-processing-service.php
Labels: pr: ready to merge

#4266 Modify the pointer content on the "Add new product" page when WCS is not active.
  changelog/update-4098-remove-reference-to-wcs
  includes/subscriptions/class-wc-payments-subscriptions-onboarding-handler.php
Labels: pr: needs review, component: wcpay subscriptions

#4262 Update payment method id order meta after checkout
  includes/class-wc-payment-gateway-wcpay.php
Labels: pr: needs review, priority: critical

#4272 Add exception handling to prevent fatal errors when fetching payment methods on the checkout block
  changelog/fix-1566-checkout_block_account_suspended
  includes/class-wc-payments-token-service.php
  tests/unit/test-class-wc-payments-token-service.php
Labels: pr: ready to merge

#4238 Pass store API mode to platform checkout session and endpoints
  changelog/fix-use-merchant-store-api-mode
  changelog/fix-use-merchant-store-api-mode-2
  client/checkout/platform-checkout/email-input-iframe.js
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments.php
Labels: pr: needs review

#4258 Allow merchant to set store logo on Platform Checkout settings
  changelog/fix-4257-allow-set-store-logo-on-platform-checkout-settings
  client/components/file-upload/index.tsx
  client/components/file-upload/preview.tsx
  client/components/file-upload/test/index.tsx
  client/data/settings/actions.js
  client/data/settings/hooks.js
  client/data/settings/selectors.js
  client/data/settings/test/hooks.js
  client/data/settings/test/reducer.js
  client/data/settings/test/selectors.js
  client/disputes/evidence/test/index.js
  client/globals.d.ts
  client/settings/express-checkout-settings/file-upload.tsx
  client/settings/express-checkout-settings/index.js
  client/settings/express-checkout-settings/index.scss
  client/settings/express-checkout-settings/platform-checkout-preview.js
  client/settings/express-checkout-settings/platform-checkout-settings.js
  client/settings/express-checkout-settings/test/file-upload.test.js
  client/settings/express-checkout-settings/test/index.js
  client/settings/express-checkout-settings/test/platform-checkout-settings.test.js
  client/types/disputes.d.ts
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-wc-payments.php
  tests/js/jest-test-file-setup.js
Labels: component: platform checkout

#4274 Add checkbox to add or update critical flows in PR template.
  .github/PULL_REQUEST_TEMPLATE.md
  changelog/dev-critical-flows-in-pr-template
Labels: pr: ready to merge

#4244 Fix invalid_request_error when level3 line_items contain a negative unit cost
  changelog/fix-721-invalid_request_error-caused-by-negative-unit-cost-level3
  includes/class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge

#4269 Dev: update @wordpress/scripts package to use dart-sass instead of node-sass
  changelog/dev-move-to-dart-sass
  package-lock.json
  package.json
Labels: pr: ready to merge, category: engineering, type: developer experience

#4240 Send complete store_api_url to platform site
  changelog/fix-store-api-url
  includes/class-wc-payments.php
Labels: component: platform checkout

#4279 Update subscriptions-core to 2.0.0
  changelog/subscriptions-core-2.0.0
  changelog/subscriptions-core-2.0.0-1
  changelog/subscriptions-core-2.0.0-2
  changelog/subscriptions-core-2.0.0-3
  changelog/subscriptions-core-2.0.0-4
  changelog/subscriptions-core-2.0.0-5
  changelog/subscriptions-core-2.0.0-6
  composer.json
  composer.lock
Labels: pr: needs review

#4278 Fix webhook idempotency (for payment intents)
  changelog/fix-3783-webhook-idempotency
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-order-service.php
Labels: pr: needs review

#4271 E2E environment setup & workflow optimizations
  .github/workflows/e2e-test.yml
  changelog/e2e-setup-gh-actions-enable-server-instance
  tests/e2e/env/down.sh
  tests/e2e/env/setup.sh
  tests/e2e/env/shared.sh
  tests/e2e/env/up.sh
Labels: type: enhancement, pr: needs review, category: e2e, category: devops

#4245 Visually hide UPE payment methods if manual capture is enabled
  changelog/add-3567-show-upe-methods-with-manual-capture
  client/additional-methods-setup/upe-preview-methods-selector/test/add-payment-methods-task.test.js
  client/components/loadable-checkbox/index.js
  client/components/loadable-checkbox/style.scss
  client/components/payment-methods-list/payment-method.js
  client/components/payment-methods-list/payment-method.scss
  client/payment-methods-map.ts
  client/payment-methods/index.js
  client/payment-methods/test/index.js
  client/settings/settings-manager/index.js
  client/settings/transactions-and-deposits/index.js
  client/settings/transactions-and-deposits/manual-capture-control.js
  tests/e2e/specs/wcpay/merchant/merchant-payment-settings-manual-capture.spec.js
Labels: pr: ready to merge

#4295 Add checkbox to submit PR details to release announcement post
  .github/PULL_REQUEST_TEMPLATE.md
Labels: pr: needs review

#4273 Add developer document for "Version Support Policy"
  README.md
  changelog/add-version-support-policy
  docs/version-support-policy.md
Labels: pr: needs review

#4296 Prevent expensive JOINs when there aren't multiple currencies used
  changelog/update-reduce-expensive-queries
  includes/multi-currency/Analytics.php
  tests/unit/multi-currency/test-class-analytics.php
Labels: pr: ready to merge
