Repository Automattic/woocommerce-payments, pull requests merged in 2022-07, with the labels that each got.

#4378 Add support for remote inbox notes with actions that have relative admin URLs
  changelog/issue-4350
  includes/notes/class-wc-payments-remote-note-service.php
Labels: pr: ready to merge

#4391 Add client-side server links handler
  changelog/add-4342-client-link-handler
  client/overview/index.js
  client/overview/test/index.js
  includes/class-wc-payments-account.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/test-class-wc-payments-account-link.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: ready to merge

#4370 Fixes small typo in changelog entry introduced in PR #4336
  changelog/update-3122-payment-intent
Labels: pr: ready to merge

#4371 TypeScript: twweaks for Card reader types suggested on GitHub
  changelog/dev-tweak-ts-definitions
  client/card-readers/list/list-item.tsx
  client/types/card-readers.d.ts
Labels: pr: ready to merge

#4374 Include WordPress nightly build into E2E tests
  .github/workflows/e2e-test.yml
  changelog/e2e-include-wp-prelease-version
Labels: pr: ready to merge, category: e2e, category: devops

#4366 Align Payment Request pop-ups Pricing with Cart pricing display.
  changelog/fix-4265-tax-inclusive-payment-request
  includes/class-wc-payments-payment-request-button-handler.php
Labels: pr: ready to merge

#4414 Fix dispute task grammar for multiple disputes and change the redirect when clicked
  changelog/fix-dispute-task-plural-phrasing
  changelog/update-dispute-task-redirect
  client/overview/task-list/tasks.js
  client/overview/task-list/test/tasks.js
Labels: pr: ready to merge

#4418 Add a disputes task to the "Things to do next" list on WC > Home
  changelog/add-wc-home-dispute-task
  includes/admin/tasks/class-wc-payments-task-disputes.php
  includes/class-wc-payments-tasks.php
  psalm-baseline.xml
  woocommerce-payments.php
Labels: pr: needs review

#4419 Add a view and respond subtext to the dispute task on WC → Home
  includes/admin/tasks/class-wc-payments-task-disputes.php
Labels: pr: needs review

#4400 Move the Payments → Overview task list above account details card to improve visibility
  changelog/update-4399-move-payments-overview-task-list
  client/overview/index.js
Labels: component: account overview page

#4383 Fix display of UPE payment methods when manual capture is enabled
  changelog/fix-4382-upe-payment-method-display-with-manual-capture
  client/components/payment-methods-checkboxes/payment-method-checkbox.js
  client/components/payment-methods-checkboxes/payment-method-checkbox.scss
  client/components/payment-methods-checkboxes/test/index.js
  client/components/payment-methods-list/payment-method.js
  client/components/payment-methods-list/payment-method.scss
Labels: pr: needs review

#4390 Add Customer Currency filter to transactions advanced filters
  changelog/dev-1278-add-customer-currency-filter
  client/data/transactions/hooks.ts
  client/data/transactions/resolvers.js
  client/transactions/declarations.d.ts
  client/transactions/filters/config.ts
  client/transactions/filters/index.tsx
  client/transactions/filters/test/__snapshots__/index.tsx.snap
  client/transactions/filters/test/index.tsx
  client/transactions/list/index.tsx
  client/transactions/list/test/__snapshots__/index.tsx.snap
  includes/admin/class-wc-rest-payments-transactions-controller.php
Labels: pr: ready to merge

#4426 Update explicit pricing missing E2E tests
  changelog/fix-explicit-pricing-tests
  tests/e2e/specs/subscriptions/merchant/merchant-subscriptions-purchase-no-sign-up.spec.js
  tests/e2e/specs/subscriptions/merchant/merchant-subscriptions-purchase-sign-up-fee.spec.js
  tests/e2e/specs/wcpay/merchant/merchant-orders-full-refund.spec.js
  tests/e2e/specs/wcpay/merchant/merchant-orders-partial-refund.spec.js
Labels: pr: ready to merge, category: e2e

#4425 Bump WC minimum supported version for 4.5.0 release
  .github/workflows/compatibility.yml
  .github/workflows/coverage.yml
  .github/workflows/e2e-test.yml
  .github/workflows/php-lint-test.yml
  changelog/dev-bump-versions-4-5-0
  phpcs.xml.dist
  readme.txt
  woocommerce-payments.php
Labels: pr: needs review

#4344 Add E2E test to test checkout performance
  .gitignore
  changelog/add-1021-performance-measure
  package.json
  tests/e2e/config/jest.performance.config.js
  tests/e2e/specs/performance/payment-methods.spec.js
  tests/e2e/utils/constants.js
  tests/e2e/utils/flows.js
  tests/e2e/utils/performance.js
Labels: category: performance, category: e2e

#4429 Make adding fee details to order notes async
  changelog/update-fee-order-details-async
  includes/class-wc-payments-order-service.php
  includes/class-wc-payments.php
Labels: pr: ready to merge

#4355 Use country-phone input component for terminal settings phone field
  changelog/fix-phone-input-component
  client/card-readers/settings/sections/contacts-details.js
  client/card-readers/settings/sections/test/index.test.js
  client/components/platform-checkout/save-user/checkout-page-save-user.js
  client/components/platform-checkout/save-user/phone-number-input.js
  client/components/platform-checkout/save-user/test/phone-number-input.test.js
  client/settings/phone-input/declarations.d.ts
  client/settings/phone-input/index.tsx
  client/settings/phone-input/style.scss
  client/settings/phone-input/test/phone-input.test.js
  package-lock.json
  package.json
  tsconfig.json
Labels: pr: ready to merge

#4443 Make updating saved payment method async during checkout
  changelog/update-saved-payment-method-async
  includes/class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
Labels: pr: ready to merge

#4434 Fix multicurrency shipping tax conversion
  changelog/fix-4417-shipping-tax-conversion
  includes/multi-currency/FrontendPrices.php
  tests/unit/multi-currency/test-class-frontend-prices.php
Labels: pr: ready to merge

#4348 Redirect "ch_" charge id format to "pi_" payment intent id on Transaction Detail screens
  changelog/update-3122-redirect
  client/data/capital/actions.ts
  client/data/capital/resolvers.ts
  client/data/capital/selectors.ts
  client/data/capital/types.d.ts
  client/data/charges/hooks.js
  client/data/charges/hooks.ts
  client/data/charges/types.d.ts
  client/data/index.ts
  client/data/payment-intents/action-types.ts
  client/data/payment-intents/actions.ts
  client/data/payment-intents/hooks.ts
  client/data/payment-intents/index.ts
  client/data/payment-intents/reducer.ts
  client/data/payment-intents/resolvers.ts
  client/data/payment-intents/selectors.ts
  client/data/payment-intents/test/hooks.ts
  client/data/payment-intents/test/resolvers.ts
  client/data/payment-intents/test/selectors.ts
  client/data/payment-intents/types.d.ts
  client/data/store.js
  client/data/timeline/hooks.js
  client/data/types.d.ts
  client/payment-details/index.js
  client/payment-details/test/__snapshots__/index.tsx.snap
  client/payment-details/test/index.tsx
  client/payment-details/timeline/index.js
  client/types/charges.d.ts
  client/types/errors.d.ts
  client/types/payment-intents.d.ts
  includes/admin/class-wc-rest-payments-payment-intents-controller.php
  includes/class-wc-payments.php
  includes/wc-payment-api/models/class-wc-payments-api-charge.php
  includes/wc-payment-api/models/class-wc-payments-api-intention.php
  package-lock.json
Labels: pr: ready to merge

#4459 Fix an issue with sorting by customer currency on analytics > orders
  changelog/dev-fix-analytics-sorting
  client/multi-currency-analytics/index.js
Labels: pr: ready to merge

#4463 Remove the slide in animation from the dispute task item on Payments > Overview
  changelog/issue-4461
  client/overview/task-list/index.js
Labels: pr: ready to merge

#4458 Fix caching dispute issues after accepting a dispute
  changelog/fix-dispute-caching-after-accept
  client/data/disputes/actions.js
  client/data/disputes/test/actions.js
  client/disputes/evidence/index.js
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: needs review

#4460 Enable the Payments → Overview task list for all merchants
  changelog/update-4457-launch-the-payments-overview-task-list
  includes/class-wc-payments-features.php
  tests/unit/test-class-wc-payments-features.php
Labels: pr: needs review, component: account overview page, category: core

#4472 Fix the plural string used in the disputes task list
  changelog/fix-plural-disputes-task-list
  client/globals.d.ts
  client/overview/index.js
  client/overview/task-list/test/tasks.js
Labels: pr: needs review

#4473 Remove the conditional `completed` and `additionalInfo` attribute for dispute task.
  changelog/fix-4123-dispute-count
  client/overview/task-list/tasks.js
  client/overview/task-list/test/tasks.js
Labels: pr: needs review

#4467 Update transaction details link to use Payment Intent ID instead of Charge ID
  changelog/update-3122-links
  client/data/transactions/hooks.ts
  client/transactions/list/index.tsx
  client/transactions/list/test/__snapshots__/index.tsx.snap
  client/transactions/list/test/index.tsx
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-order-service.php
  includes/class-wc-payments-utils.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/test-class-wc-payments-order-service.php
Labels: pr: needs review

#4465 Add Multi-Currency compatibility with Points & Rewards plugin
  changelog/add-2848-mc-points-rewards-compat
  includes/multi-currency/Compatibility.php
  includes/multi-currency/Compatibility/WooCommercePointsAndRewards.php
  tests/unit/helpers/class-wc-helper-points-and-rewards.php
  tests/unit/multi-currency/compatibility/test-class-woocommerce-points-and-rewards.php
Labels: pr: ready to merge

#4476 Update to support selection of multiple currencies in analytics
  changelog/add-advanced-filter-analytics
  client/multi-currency-analytics/index.js
  includes/multi-currency/Analytics.php
  tests/unit/multi-currency/test-class-analytics.php
Labels: pr: ready to merge

#4481 E2E - Skip blocks tests against incompatible WC versions
  .github/workflows/e2e-test.yml
  changelog/e2e-update-e2e-workflow-wc-versions
Labels: category: e2e, category: devops

#4488 E2E - Fix failing dispute tests
  changelog/e2e-fix-dispute-tests
  tests/e2e/specs/wcpay/merchant/merchant-disputes-submit-losing.spec.js
  tests/e2e/specs/wcpay/merchant/merchant-disputes-submit-winning.spec.js
Labels: pr: ready to merge, category: e2e, category: devops

#4392 Add payment channel information + payment identifiers to transactions
  changelog/add-transactions-channels
  client/components/payment-method-details/index.js
  client/data/transactions/hooks.ts
  client/payment-details/payment-method/becs/index.js
  client/payment-details/payment-method/card-present/index.js
  client/payment-details/payment-method/card-present/test/__snapshots__/index.js.snap
  client/payment-details/payment-method/card/index.js
  client/payment-details/payment-method/p24/bank-list.ts
  client/payment-details/payment-method/sepa/index.js
  client/payment-details/summary/index.tsx
  client/payment-details/summary/test/__snapshots__/index.tsx.snap
  client/payment-details/test/__snapshots__/index.tsx.snap
  client/style.scss
  client/transactions/list/index.tsx
  client/transactions/list/test/__snapshots__/index.tsx.snap
  client/transactions/list/test/index.tsx
  client/types/charges.d.ts
  client/utils/charge/index.ts
Labels: pr: needs author reply

#4311 Remove cached UPE setup intent when changing subscription payment method to allow subsequent payment changes
  changelog/fix-4308-change-sub-payment-more-than-once-per-session-upe
  includes/payment-methods/class-upe-payment-gateway.php
Labels: pr: needs review, component: saved cards and subscriptions, component: upe, component: wcpay subscriptions

#4494 Update currencies modal height
  changelog/fix-4491-currencies-modal-height
  client/components/confirmation-modal/styles.scss
  client/multi-currency/multi-currency-settings/enabled-currencies-list/style.scss
Labels: pr: needs author reply

#4436 Ask for login when buying a subscription with WooPay
  changelog/fix-4435-woopay-ask-for-login-before-checkout-subscription
  client/checkout/classic/upe.js
  client/checkout/platform-checkout/email-input-iframe.js
  client/checkout/utils/show-error-checkout.js
  includes/admin/class-wc-rest-user-exists-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments.php
Labels: component: platform checkout
