Repository Automattic/woocommerce-payments, pull requests merged in 2022-10, with the labels that each got.

#4784 Avoid hidden overflow on the ellipsis menu from the task list
  changelog/fix-4470-ellipsis-menu-cut-off-in-task-list
  client/overview/style.scss
  client/overview/task-list/index.js
Labels: pr: ready to merge

#4819 Fix fatal error in Multi-Currency Compatibility
  changelog/fix-4818-multi-currency-compatibility-fatal
  includes/multi-currency/Compatibility.php
  tests/unit/multi-currency/test-class-compatibility.php
Labels: pr: needs review

#4826 Add onboarding page for progressive onboarding prototype
  client/index.js
  client/onboarding-experiment/hooks.ts
  client/onboarding-experiment/index.tsx
  client/onboarding-experiment/requirements/company.tsx
  client/onboarding-experiment/requirements/group.tsx
  client/onboarding-experiment/requirements/index.tsx
  client/onboarding-experiment/requirements/individual.tsx
  client/onboarding-experiment/requirements/keymap.tsx
  client/onboarding-experiment/requirements/strings.tsx
  client/onboarding-experiment/requirements/style.scss
  client/onboarding-experiment/requirements/test/__snapshots__/company.tsx.snap
  client/onboarding-experiment/requirements/test/__snapshots__/individual.tsx.snap
  client/onboarding-experiment/requirements/test/company.tsx
  client/onboarding-experiment/requirements/test/individual.tsx
  client/onboarding-experiment/requirements/test/keymap.tsx
  client/onboarding-experiment/strings.ts
  client/onboarding-experiment/style.scss
  client/onboarding-experiment/tasks/add-business-info-task/index.tsx
  client/onboarding-experiment/tasks/add-business-info-task/required-verification-info.tsx
  client/onboarding-experiment/tasks/add-business-info-task/test/__snapshots__/index.tsx.snap
  client/onboarding-experiment/tasks/add-business-info-task/test/__snapshots__/required-verification-info.tsx.snap
  client/onboarding-experiment/tasks/add-business-info-task/test/index.tsx
  client/onboarding-experiment/tasks/add-business-info-task/test/required-verification-info.tsx
  client/onboarding-experiment/tasks/setup-complete-task/index.tsx
  client/onboarding-experiment/tasks/setup-complete-task/test/__snapshots__/index.tsx.snap
  client/onboarding-experiment/tasks/setup-complete-task/test/index.tsx
  client/onboarding-experiment/test/__snapshots__/index.tsx.snap
  client/onboarding-experiment/test/index.tsx
  client/onboarding-experiment/translations/descriptions.tsx
  client/onboarding-experiment/translations/structures.tsx
  client/onboarding-experiment/translations/types.tsx
  client/onboarding-experiment/types.d.ts
  client/onboarding-prototype/index.tsx
  client/onboarding-prototype/onboarding-form.js
  client/onboarding-prototype/regular-onboarding-notice.tsx
  client/onboarding-prototype/strings.tsx
  client/onboarding-prototype/utils.tsx
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-account.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
  webpack.config.js
Labels: pr: ready to merge

#4798 Dev: Adjust E2E tests to work locally on Apple silicon chips, and improve some tests
  bin/docker-setup.sh
  changelog/update-e2e-test-image
  package-lock.json
  package.json
  tests/e2e/config/e2e-default.env
  tests/e2e/config/jest-puppeteer.config.js
  tests/e2e/config/jest.config.js
  tests/e2e/env/default.env
  tests/e2e/env/shared.sh
  tests/e2e/env/wordpress-xdebug/Dockerfile
  tests/e2e/specs/blocks/shopper/shopper-wc-blocks-checkout-failures.spec.js
  tests/e2e/specs/blocks/shopper/shopper-wc-blocks-checkout-purchase.spec.js
  tests/e2e/specs/wcpay/merchant/merchant-admin-analytics.spec.js
  tests/e2e/utils/flows.js
  tests/e2e/utils/helpers.js
Labels: pr: needs review, dependencies, category: e2e, type: developer experience

#4823 Handle rate limit errors during the checkout process
  changelog/fix-4801-429-lock-timeout-error
  client/checkout/api/index.js
  client/checkout/blocks/confirm-upe-payment.js
  client/checkout/blocks/upe-fields.js
  client/checkout/classic/upe.js
Labels: pr: needs review

#4687 Display analytics orders in customer currency
  changelog/add-4446-display-analytics-in-customer-currency
  client/multi-currency-analytics/index.js
  includes/multi-currency/Analytics.php
  tests/unit/multi-currency/test-class-analytics.php
Labels: pr: ready to merge

#4854 Update webhook processing to override existing meta data
  changelog/update-order-meta-data-override
  includes/class-wc-payments-webhook-processing-service.php
Labels: pr: needs review, component: webhooks

#4857 Update subscriptions-core to 2.3.0
  changelog/subscriptions-core-2.3.0
  changelog/subscriptions-core-2.3.0-fix
  changelog/subscriptions-core-2.3.0-update
  composer.json
  composer.lock
Labels: pr: ready to merge

#4828 Update readme.txt
  changelog/readme-tags-update
  readme.txt
Labels: pr: ready to merge, size: small

#4928 Add KYC additional info modal and notice banner
  assets/images/icons/lightbulb.svg
  changelog/add-4849-kyc-additional-info
  client/connect-account-page/index.js
  client/connect-account-page/info-modal/index.tsx
  client/connect-account-page/info-modal/style.scss
  client/connect-account-page/info-modal/test/__snapshots__/index.tsx.snap
  client/connect-account-page/info-modal/test/index.tsx
  client/connect-account-page/strings.js
  client/connect-account-page/style.scss
  client/connect-account-page/test/__snapshots__/index.js.snap
Labels: pr: ready to merge

#4510 Add HMR and split webpack configuration
  CONTRIBUTING.md
  changelog/hmr-webpack5
  includes/class-wc-payments.php
  package-lock.json
  package.json
  webpack.config.js
  webpack/development.js
  webpack/hmr.js
  webpack/production.js
  webpack/shared.js
Labels: pr: ready to merge

#4781 Save tokens for Link payment method
  changelog/fix-4703-link-for-subscriptions
  includes/class-wc-payment-token-wcpay-link.php
  includes/class-wc-payments-token-service.php
  includes/class-wc-payments.php
  includes/constants/class-payment-method.php
  tests/unit/test-class-wc-payments-token-service.php
Labels: pr: ready to merge

#4921 Declare HPOS incompatibility
  changelog/add-declare-cot-incompatibility
  woocommerce-payments.php
Labels: pr: needs review

#4925 Add new GitHub workflows to manage pre-release and release packages
  .github/actions/build/action.yml
  .github/actions/create-branch-tag/action.yml
  .github/actions/generate-changelog/action.yml
  .github/actions/setup-repo/action.yml
  .github/workflows/build-zip-file.yml
  .github/workflows/create-pre-release.yml
  .github/workflows/create-release.yml
  .github/workflows/release-code-freeze.yml
  .github/workflows/release-pr.yml
  changelog/add-4684-package-creation-workflow
Labels: pr: needs review

#4947 Fix regex to check format of tag for a pre-release
  .github/actions/create-branch-tag/action.yml
  changelog/fix-update-regex-branch-tag-workflow
Labels: pr: needs review

#4932 Create an inbox note for Stripe Link set-up
  changelog/add-stripe-link-note
  includes/class-wc-payments.php
  includes/notes/class-wc-payments-notes-set-up-stripelink.php
  tests/unit/notes/test-class-wc-payments-notes-set-up-stripelink.php
Labels: pr: ready to merge

#4715 Adding manual option to deposit schedule selection
  changelog/add-4696-manual-deposit-schedule-selection
  client/settings/deposits/index.js
  client/settings/deposits/style.scss
  client/settings/deposits/test/index.test.js
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-account.php
Labels: pr: needs review

#4281 Switch to `@woocommerce/dependency-extraction-webpack-plugin`
  changelog/dev-switch-to-woo-dep-extraction-webpack-plugin
  docs/renovate.md
  package-lock.json
  package.json
  webpack/shared.js
Labels: pr: ready to merge

#4948 Drop IE11 support
  changelog/update-drop-ie11-support
  package-lock.json
  package.json
Labels: pr: needs review

#4852 Adjust texts and links in WC admin express checkout section
  changelog/add-link-wording-tweaks
  client/settings/express-checkout/index.js
  client/settings/express-checkout/style.scss
  client/settings/express-checkout/test/index.test.js
  client/settings/settings-manager/index.js
Labels: pr: ready to merge

#4822 add link payment method for capture later option
  changelog/fix-4821-link-enabled-capture-later
  includes/payment-methods/class-upe-payment-gateway.php
Labels: pr: ready to merge

#4952 Remove unnecessary babel plugins
  .babelrc
  babel.config.js
  changelog/dev-remove-unnecessary-babel-plugins
  package-lock.json
  package.json
Labels: pr: ready to merge

#4967 Use individual Gridicons imports
  .eslintrc
  changelog/dev-individual-gridicons-import
  client/components/currency-delete-illustration/index.js
  client/components/deposits-information/declarations.d.ts
  client/components/deposits-information/index.tsx
  client/components/deposits-information/loading.tsx
  client/components/details-link/index.js
  client/components/download-button/index.js
  client/components/file-upload/index.tsx
  client/components/payment-confirm-illustration/index.tsx
  client/components/payment-delete-illustration/index.tsx
  client/declarations.d.ts
  client/multi-currency/multi-currency-settings/enabled-currencies-list/delete-button.js
  client/onboarding/requirements/company.tsx
  client/onboarding/requirements/group.tsx
  client/onboarding/requirements/individual.tsx
  client/payment-details/timeline/map-events.js
  client/payment-details/timeline/test/__snapshots__/map-events.js.snap
  client/payment-details/timeline/test/map-events.js
  client/settings/deposits/index.js
  client/settings/express-checkout-settings/file-upload.tsx
  client/transactions/list/converted-amount.tsx
Labels: pr: needs review

#4963 Update lodash to version 4.17.21
  .prettierignore
  changelog/update-update-lodash
  docs/renovate.md
  package-lock.json
  package.json
Labels: pr: ready to merge, dependencies

#4984 Update some workflow files to use an env variable for L-2 versions
  .github/workflows/compatibility.yml
  .github/workflows/e2e-test.yml
  .github/workflows/php-lint-test.yml
  changelog/dev-refactor-ci-workflow-for-l-2-versions
Labels: pr: ready to merge

#4941 Update husky to v 8.0.1
  .husky/.gitignore
  changelog/update-update-husky
  docs/renovate.md
  package-lock.json
  package.json
Labels: dependencies

#4991 Update `woocommerce-payments` package version number in `package-lock.json`
  changelog/fix-4990-outdated-package-version
  package-lock.json
Labels: pr: needs review

#4840 Hide upload buttons, amend placeholders in submitted evidence form
  changelog/fix-495-update-submitted-evidence-form
  client/components/file-upload/index.tsx
  client/components/file-upload/test/index.tsx
  client/disputes/evidence/index.js
  client/disputes/evidence/test/__snapshots__/index.js.snap
  client/style.scss
  client/types/disputes.d.ts
Labels: type: enhancement, pr: needs review, component: disputes, category: core

#4957 [Authorizations][Capture from table] Add capture_authorization endpoint
  changelog/add-4569-capture-auth-endpoint
  docs/rest-api/source/includes/wp-api-v3/order.md
  includes/admin/class-wc-rest-payments-orders-controller.php
  tests/unit/admin/test-class-wc-rest-payments-orders-controller.php
Labels: pr: needs review

#4960 [Authorizations][Capture from table] Add CaptureAuthorizationButton component
  changelog/add-4569-capture-authorization-button-component
  client/components/capture-authorization-button/index.tsx
  client/components/capture-authorization-button/test/__snapshots__/index.test.tsx.snap
  client/components/capture-authorization-button/test/index.test.tsx
  client/data/authorizations/action-types.ts
  client/data/authorizations/hooks.ts
Labels: pr: needs review

#4939 Update priority for Multi-Currency filters for prices and currency
  changelog/update-4938-update-multi-currency-filter-priority
  includes/multi-currency/FrontendCurrencies.php
  includes/multi-currency/FrontendPrices.php
  tests/unit/multi-currency/test-class-frontend-currencies.php
  tests/unit/multi-currency/test-class-frontend-prices.php
  tests/unit/multi-currency/test-class-multi-currency.php
Labels: pr: ready to merge

#4965 Update deprecated interpolate-components to new @automattic/interpolate-components
  changelog/update-interpolate-components
  docs/renovate.md
  package-lock.json
  package.json
Labels: pr: needs review, dependencies

#5013 Add dependencies.md to replace renovate.md
  .prettierignore
  docs/dependencies.md
  docs/renovate.md
Labels: pr: needs review
