Repository Automattic/woocommerce-payments, pull requests merged in 2023-07, with the labels that each got.

#6648 Only remove all E2E tests dependencies if FORCE_E2E_DEPS_SETUP is true
  .github/workflows/e2e-pull-request.yml
  .github/workflows/e2e-test.yml
  changelog/fix-e2e-test-workflow
  tests/e2e/env/setup.sh
Labels: pr: ready to merge

#6628 Fix process changelog composite action
  .github/actions/process-changelog/action.yml
  changelog/fix-process-changelog-composite-action
Labels: pr: ready to merge

#6657 Add `strlen` as a callback to metadata filter
  changelog/fix-6598-qit-warning-in-class-buyer-fingerprinting-service
  includes/fraud-prevention/class-buyer-fingerprinting-service.php
  tests/unit/fraud-prevention/test-class-buyer-fingerprinting-service.php
Labels: pr: ready to merge

#6653 Update references to fraudulent disputes
  changelog/fix-6611-rename-fraudulent-dispute-references
  client/disputes/details/test/__snapshots__/index.tsx.snap
  client/disputes/strings.ts
  includes/notes/class-wc-payments-notes-set-up-refund-policy.php
Labels: pr: ready to merge

#6579 Prefill the Business URL on the onboarding form
  changelog/add-prefill-business-url
  client/onboarding/context.tsx
  client/onboarding/index.tsx
  client/onboarding/test/context.tsx
Labels: pr: ready to merge

#6377 Fix fatal errors when `get_product` method returns `null`
  changelog/fix-5906-request-button-fatal-errors
  includes/class-wc-payments-payment-request-button-handler.php
Labels: pr: ready to merge

#6665 Fix minor comment typos
  changelog/fix-minor-comment-typos
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-customer-service.php
Labels: pr: ready to merge

#6596 Add - Tooltip and ARIA label to PM logos in Translation list and Payment Details page
  changelog/update-6589-tooltip-transaction-logos
  client/components/payment-method-details/index.js
  client/components/payment-method-details/style.scss
  client/components/payment-method-details/test/__snapshots__/index.js.snap
  client/payment-details/order-details/test/__snapshots__/index.test.tsx.snap
  client/payment-details/summary/test/__snapshots__/index.tsx.snap
  client/payment-details/test/__snapshots__/index.test.tsx.snap
  client/payment-methods-map.tsx
  client/payment-methods/constants.ts
  client/transactions/list/index.tsx
  client/transactions/list/test/__snapshots__/index.tsx.snap
Labels: pr: ready to merge

#6582 Tool to update Multi-Currency meta data
  changelog/add-server-3431-mc-tool-for-meta-conversion-correction
  includes/class-wc-payments-features.php
  includes/multi-currency/Helpers/OrderMetaHelper.md
  includes/multi-currency/Helpers/OrderMetaHelper.php
  includes/multi-currency/MultiCurrency.php
Labels: pr: ready to merge, component: customer multi-currency

#6357 Add E2E tests for Fraud & Risk tools
  changelog/dev-6329-frt-e2e
  includes/core/server/request/class-list-fraud-outcome-transactions.php
  tests/e2e/specs/wcpay/merchant/merchant-fraud-protection.spec.js
  tests/e2e/utils/flows.js
  tests/e2e/utils/payments.js
Labels: pr: ready to merge

#6664 Remove Remind Me Later option from the FRT discoverability banner
  changelog/update-6321-remove-frt-discoverability-banner-remind-option
  client/components/fraud-risk-tools-banner/components/banner-actions/index.tsx
  client/components/fraud-risk-tools-banner/components/banner-actions/test/__snapshots__/index.test.tsx.snap
  client/components/fraud-risk-tools-banner/components/banner-actions/test/index.test.tsx
  client/components/fraud-risk-tools-banner/index.tsx
  client/components/fraud-risk-tools-banner/test/__snapshots__/index.test.tsx.snap
  client/components/fraud-risk-tools-banner/test/index.test.tsx
  client/overview/test/index.js
Labels: pr: needs review

#6421 Duplicate payment prevention service
  changelog/fix-6285-duplicate-payment-prevention-service
  includes/class-duplicate-payment-prevention-service.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-order-success-page.php
  includes/class-wc-payments.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/payment-methods/class-upe-split-payment-gateway.php
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
  tests/unit/admin/test-class-wc-rest-payments-tos-controller.php
  tests/unit/admin/test-class-wc-rest-upe-flag-toggle-controller.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
  tests/unit/payment-methods/test-class-upe-split-payment-gateway.php
  tests/unit/test-class-duplicate-payment-prevention-service.php
  tests/unit/test-class-wc-payment-gateway-wcpay-payment-types.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-refund.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-payment-method-order-note.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-express-checkout-button-display-handler.php
  tests/unit/test-class-wc-payments-payment-request-button-handler.php
  tests/unit/test-class-wc-payments-woopay-button-handler.php
Labels: pr: needs review

#6666 Hide `disputed on` column in disputes listing
  changelog/fix-6661-hide-disputed-on-column
  client/disputes/index.tsx
  client/disputes/test/__snapshots__/index.tsx.snap
  client/disputes/test/index.tsx
Labels: pr: ready to merge

#6631 [BNPL site messaging] Fix Country informed as empty for logged-out user
  changelog/fix-6630-bnpl-site-messaging-country-informed-as-empty-for-logged-out-user
  includes/class-wc-payments-payment-method-messaging-element.php
Labels: pr: needs review

#6626 BNPL - Integrate BNPL offer messaging for variations in variable products
  changelog/add-6591-bnpl-messaging-variable-product
  client/product-details/bnpl-site-messaging/index.js
  client/product-details/index.js
  includes/class-wc-payments-payment-method-messaging-element.php
Labels: pr: ready to merge

#6713 Remove WooCommerce Payments from taking over the WooCommerce Core Settings
  changelog/4073-imp-woo-deafult-payment-settings
  includes/admin/class-wc-payments-admin-sections-overwrite.php
  tests/unit/admin/test-class-wc-payments-admin-sections-overwrite.php
Labels: pr: ready to merge

#6715 Change active menu item for Fraud protection
  changelog/fix-6369-wooexpress-remove-fraud-protection-menu-disconnected
  client/index.js
  client/settings/fraud-protection/advanced-settings/index.tsx
Labels: pr: needs review

#6695 Add action column with respond button to dispute list view
  changelog/fix-6667-disputes-listing-add-respond-button
  client/disputes/index.tsx
  client/disputes/style.scss
  client/disputes/test/__snapshots__/index.tsx.snap
  client/tracks/index.js
  client/types/disputes.d.ts
Labels: pr: ready to merge

#6249 Migrate `HorizontalList` component to TS
  changelog/add-migrate-horizontal-list-to-ts
  client/components/horizontal-list/index.js
  client/components/horizontal-list/index.tsx
  client/components/horizontal-list/test/__snapshots__/index.tsx.snap
  client/components/horizontal-list/test/index.tsx
  client/deposits/declarations.d.ts
  client/payment-details/summary/index.tsx
  client/utils/is-value-truthy.ts
Labels: type: task, category: refactor

#6373 Show active dispute as inline notice in order edit screen
  changelog/try-contextual-notice-in-order-details-wccore-hook
  client/order/index.js
  client/order/style.scss
  client/tracks/index.js
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments.php
  tests/unit/admin/test-class-wc-payments-admin.php
Labels: pr: ready to merge

#6736 Fix incorrect channel value in transaction description screen for Tap to Pay for Android transactions
  changelog/fix-6735-incorrect-channel-value
  client/payment-details/summary/index.tsx
Labels: pr: ready to merge, component: card present

#6738 Adjust style of save my info based on previous section
  changelog/fix-6640-save-my-info
  client/checkout/woopay/index.js
Labels: pr: ready to merge

#6733 Remove FRT E2E tests
  changelog/fix-e2e-tests-frt
  tests/e2e/specs/wcpay/merchant/merchant-fraud-protection.spec.js
  tests/e2e/utils/flows.js
  tests/e2e/utils/payments.js
Labels: pr: needs review

#6642 Remove total from active dispute task title when from multiple currencies
  changelog/fix-6613-active-dispute-task-wording-multicurrency
  client/overview/task-list/dispute-tasks.ts
  client/overview/task-list/test/tasks.js
  includes/admin/tasks/class-wc-payments-task-disputes.php
  tests/unit/admin/tasks/test-class-wc-payments-task-disputes.php
Labels: pr: ready to merge

#6723 Update colour coding of DisputeStatusChip based on dispute status and urgency
  changelog/fix-6722-dispute-list-status-chip-colours
  client/components/chip/index.js
  client/components/chip/style.scss
  client/components/chip/test/__snapshots__/index.js.snap
  client/components/dispute-status-chip/index.js
  client/components/dispute-status-chip/mappings.ts
  client/components/dispute-status-chip/test/__snapshots__/index.js.snap
  client/components/dispute-status-chip/test/index.js
  client/components/payment-status-chip/test/__snapshots__/index.js.snap
  client/disputes/details/index.tsx
  client/disputes/details/test/__snapshots__/index.tsx.snap
  client/disputes/index.tsx
  client/disputes/test/__snapshots__/index.tsx.snap
  client/disputes/test/utils.test.ts
  client/disputes/utils.ts
  client/payment-details/summary/test/__snapshots__/index.tsx.snap
Labels: pr: ready to merge

#6703 Dispute Listing: Add smart-date respond by column
  changelog/fix-6702-dispute-listing-smart-dates
  client/disputes/index.tsx
  client/disputes/style.scss
  client/disputes/test/__snapshots__/index.tsx.snap
  client/disputes/test/index.tsx
Labels: pr: ready to merge

#6746 Highlight the active dispute task if disputes due within 72 hours.
  changelog/fix-6701-dispute-task-72h-urgency
  client/overview/task-list/dispute-tasks.ts
  client/overview/task-list/test/tasks.js
Labels: pr: ready to merge

#6754 Changelog for disputes list page improvements.
  changelog/add-6355-changelog
  changelog/fix-6722-dispute-list-status-chip-colours
Labels: pr: ready to merge

#6696 Remove Task List Feature Flag and task list refactors
  changelog/dev-4489-remove-feature-flag
  client/index.js
  client/overview/index.js
  client/overview/task-list/strings.tsx
  client/overview/task-list/tasks.js
  client/overview/task-list/tasks.tsx
  client/overview/task-list/tasks/dispute-task.tsx
  client/overview/task-list/tasks/po-task.tsx
  client/overview/task-list/tasks/reconnect-task.tsx
  client/overview/task-list/tasks/test/po-tasks.tsx
  client/overview/task-list/tasks/update-business-details-task.tsx
  client/overview/task-list/test/tasks.js
  includes/class-wc-payments-features.php
  tests/unit/test-class-wc-payments-features.php
Labels: pr: needs review

#6121 Authorizations - Expired auth should mark order as failed
  changelog/update-improve-authorization-expiry
  includes/class-wc-payments-order-service.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-order-service.php
Labels: pr: ready to merge, category: core, component: authorizations

#6632 Confirm subscription owner before using its currency for switch purposes
  changelog/add-confirm-switch-id-in-currency-override
  includes/multi-currency/Compatibility/WooCommerceSubscriptions.php
  tests/unit/multi-currency/compatibility/test-class-woocommerce-subscriptions.php
Labels: pr: needs review, component: customer multi-currency

#5489 Fix issue where subscription signup fees are not converted correctly with Multi-Currency
  changelog/fix-5292-fix-incorrect-signup-fee-conversion
  includes/multi-currency/Compatibility/WooCommerceSubscriptions.php
  includes/multi-currency/FrontendPrices.php
  tests/unit/helpers/class-wc-helper-subscription.php
  tests/unit/multi-currency/compatibility/test-class-woocommerce-subscriptions.php
  tests/unit/multi-currency/test-class-frontend-prices.php
Labels: pr: ready to merge

#6749 Add Android option in Device type advanced filter on Transactions page
  changelog/add-6748-android-option-device-filters
  client/transactions/filters/test/__snapshots__/index.tsx.snap
  client/transactions/filters/test/index.tsx
  client/transactions/strings.ts
Labels: pr: needs review

#6711 Add Tracking Property for New Onboarding Flow
  changelog/dev-6710-track-new-flow
  client/connect-account-page/index.tsx
  client/empty-state-table/list.tsx
  client/globals.d.ts
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-utils.php
Labels: pr: needs review

#6766 Branding rollout: Change WordPress.org assets for WCPay
  changelog/update-6669-change-wordpress-assets-to-match-new-branding
  client/banner/banner.scss
  client/banner/index.js
  client/components/welcome/index.tsx
  client/connect-account-page/strings.tsx
  client/connect-account-page/test/__snapshots__/index.test.tsx.snap
  client/connect-account-page/test/__snapshots__/info-notice-modal.test.tsx.snap
  client/overview/modal/progressive-onboarding-eligibility/index.tsx
  includes/multi-currency/Helpers/OrderMetaHelper.md
  readme.txt
  wordpress-org-assets/banner-1544x500.png
  wordpress-org-assets/banner-772x250.png
  wordpress-org-assets/icon-128x128.png
  wordpress-org-assets/icon-256x256.png
  wordpress-org-assets/screenshot-1.jpg
  wordpress-org-assets/screenshot-2.jpg
  wordpress-org-assets/screenshot-3.jpg
  wordpress-org-assets/screenshot-4.jpg
Labels: pr: ready to merge

#6787 Fix failing dispute e2e test `merchant-disputes-submit-winning`
  changelog/fix-6771-dispute-won-e2e-test
  tests/e2e/specs/wcpay/merchant/merchant-disputes-submit-winning.spec.js
Labels: pr: ready to merge

#6502 Fix Husky post-merge script to conform to `sh` syntax
  .husky/post-merge
  changelog/fix-husky-post-merge-checks
Labels: pr: needs review

#6545 Affirm&Afterpay: flexible payment ranges (optional min/max).
  changelog/add-affirm-afterpay-ranges-flexible
  includes/payment-methods/class-upe-payment-method.php
Labels: pr: ready to merge

#6793 PO Form UX & Copy Tweaks
  changelog/dev-6741-po-copy-tweaks
  client/onboarding/strings.tsx
Labels: pr: needs review, pr: needs design review

#6487 Prevent duplicate orders with a single payment intent
  changelog/fix-5786-avoid-multiple-order-upe-flow
  includes/payment-methods/class-upe-payment-gateway.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
  tests/unit/payment-methods/test-class-upe-split-payment-gateway.php
Labels: pr: ready to merge

#6234 Migration of simple requests to request classes
  changelog/dev-6217-generic-get-request-class
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-authorizations-controller.php
  includes/admin/class-wc-rest-payments-capital-controller.php
  includes/admin/class-wc-rest-payments-deposits-controller.php
  includes/admin/class-wc-rest-payments-reader-controller.php
  includes/admin/class-wc-rest-payments-terminal-locations-controller.php
  includes/admin/class-wc-rest-payments-vat-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments.php
  includes/core/server/CONTRIBUTING.md
  includes/core/server/class-request.php
  includes/core/server/request/class-create-intention.php
  includes/core/server/request/class-get-request.md
  includes/core/server/request/class-get-request.php
  includes/core/server/request/class-list-charge-refunds.php
  includes/core/server/request/class-refund-charge.php
  includes/core/server/request/class-update-intention.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/payment-methods/class-upe-split-payment-gateway.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/admin/test-class-wc-rest-payments-readers-controller.php
  tests/unit/admin/test-class-wc-rest-payments-terminal-locations-controller.php
  tests/unit/core/server/request/test-class-get-request.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
  tests/unit/payment-methods/test-class-upe-split-payment-gateway.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-account.php
  tests/unit/test-class-wc-payments-payment-request-button-handler.php
  tests/unit/test-class-wc-payments-woopay-button-handler.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: ready to merge

#6745 Migrate DisputeStatusChip comp to TS to improve code quality
  changelog/dev-ts-refactor-dispute-status-chip
  client/components/dispute-status-chip/index.tsx
  client/components/dispute-status-chip/test/__snapshots__/index.test.tsx.snap
  client/components/dispute-status-chip/test/index.test.tsx
Labels: pr: ready to merge, type: task, category: refactor

#6744 Migrate Chip component to TypeScript to improve code quality
  changelog/dev-ts-refactor-chip-component
  client/components/chip/index.tsx
  client/components/chip/test/__snapshots__/index.test.tsx.snap
  client/components/chip/test/index.test.tsx
Labels: pr: ready to merge, type: task, category: refactor

#6827 Visual fixes for the connect page hero
  assets/images/fraud-protection/discoverability-banner@2x.png
  assets/images/illustrations/connect-hero.png
  changelog/fix-6780-connect-page-illustration
  client/connect-account-page/style.scss
Labels: pr: needs review

#6845 BNPL - Fix error adding variable product to cart in some themes
  changelog/fix-6819-afterpay-variable-product-messaging-on-flatsome
  client/product-details/index.js
  includes/class-wc-payments-payment-method-messaging-element.php
  includes/class-wc-payments.php
  includes/constants/class-payment-method.php
Labels: pr: ready to merge, component: affirm & afterpay

#6800 BNPL - Fix sending of shipping data for Afterpay in classic checkout
  changelog/fix-6792-afterpay-shipping-data
  client/checkout/classic/upe-split.js
  client/checkout/classic/upe.js
  client/checkout/utils/upe.js
  includes/class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge, component: affirm & afterpay

#6708 Restrict PM to domestic country
  changelog/fix-6517-restrict-bnpl-to-domestic-country
  includes/class-wc-payment-gateway-wcpay.php
  includes/payment-methods/class-affirm-payment-method.php
  includes/payment-methods/class-afterpay-payment-method.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/payment-methods/class-upe-payment-method.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
  tests/unit/payment-methods/test-class-upe-split-payment-gateway.php
Labels: pr: ready to merge, component: affirm & afterpay

#5988 Remove AccountOverview namespace and define DepositStatus type
  changelog/issue-5987-refactor-accountOverview-namespace
  client/components/account-balances/index.tsx
  client/components/account-balances/test/index.test.tsx
  client/components/deposit-status-pill/index.tsx
  client/components/deposit-status-pill/test/index.test.tsx
  client/components/deposits-overview/deposit-schedule.tsx
  client/components/deposits-overview/next-deposit.tsx
  client/components/deposits-overview/test/index.tsx
  client/components/deposits-overview/utils.ts
  client/components/pill/index.tsx
  client/data/deposits/hooks.ts
  client/deposits/instant-deposits/index.tsx
  client/deposits/instant-deposits/modal.tsx
  client/deposits/instant-deposits/test/index.tsx
  client/overview/hooks.ts
  client/types/account-overview.d.ts
  client/types/deposits.d.ts
Labels: pr: ready to merge

#6835 Disputes List: Renaming `response date` to `respond by`
  changelog/fix-6872-disputes-response-column
  client/disputes/index.tsx
  client/disputes/test/__snapshots__/index.tsx.snap
  client/disputes/test/index.tsx
Labels: pr: ready to merge, component: disputes

#6860 Add Tracks account connect events
  changelog/add-6859-tracks-account-connect-events
  client/connect-account-page/index.tsx
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-account.php
Labels: pr: needs review

#6837 Add a base class to log entries for the Stripe billing -> tokenised subscription migration
  changelog/add-wcs_stripe_billing_migration_log
  includes/class-wc-payments.php
  includes/subscriptions/class-wc-payments-subscription-migration-log-handler.php
  tests/unit/subscriptions/test-class-wc-payments-subscription-migration-log-handler.php
Labels: pr: needs review

#6838 BNPL - Fix sending of shipping data for Afterpay in block checkout
  changelog/fix-6792-1-afterpay-shipping-data-block-checkout
  client/checkout/blocks/confirm-upe-payment.js
  client/checkout/blocks/upe-fields.js
  client/checkout/blocks/upe-split-fields.js
Labels: pr: needs review, component: affirm & afterpay
