Repository Automattic/woocommerce-payments, pull requests merged in 2023-06, with the labels that each got.

#6411 E2E - Fix failing shopper test on WC Beta
  changelog/e2e-fix-wc-beta-shopper-test
  tests/e2e/specs/wcpay/shopper/shopper-pay-for-order.spec.js
Labels: pr: ready to merge, category: e2e, category: devops

#6414 Show PO eligibility modal without checking account status
  changelog/fix-6412-eligibility-modal-peding-status
  client/overview/index.js
Labels: pr: ready to merge

#6420 Adjust style of deposits icon and text in account details for progressive accounts
  changelog/fix-account-status-deposits-disabled-to-not-connected
  client/components/account-status/index.js
  client/components/deposits-status/index.tsx
  client/components/deposits-status/test/index.js
Labels: pr: ready to merge

#6431 Add setup_mode to the account data.
  changelog/dev-pass-setup-mode
  includes/class-wc-payments-account.php
Labels: pr: ready to merge

#6430 Validate PO text fields on change only after blur
  changelog/update-6407-po-form-validation-on-blur
  client/components/phone-number-control/index.tsx
  client/onboarding-prototype/form.tsx
  client/onboarding-prototype/test/form.tsx
Labels: pr: needs review

#6433 Show setup deposits task for PO accounts without sales and right after account creation
  changelog/fix-show-connect-deposits-for-po-accounts-without-sales-before-14-days
  client/overview/task-list/po-tasks.tsx
Labels: pr: needs review

#6418 Remove feature flag for simplify deposits ui that was re-added due to merge conflict
  changelog/fix-recover-simplify-deposits-ui-feature-flag
  includes/class-wc-payments-features.php
Labels: pr: ready to merge

#6417 Add Affirm and Afterpay providers to additional payment method setup screen
  assets/images/payment-methods/affirm.svg
  assets/images/payment-methods/afterpay.svg
  client/additional-methods-setup/constants.js
  client/additional-methods-setup/upe-preview-methods-selector/add-payment-methods-task.js
  client/additional-methods-setup/upe-preview-methods-selector/enable-upe-preview-task.js
  client/additional-methods-setup/upe-preview-methods-selector/enable-upe-preview-task.scss
  client/additional-methods-setup/upe-preview-methods-selector/index.js
  client/additional-methods-setup/upe-preview-methods-selector/setup-complete-task.js
  client/additional-methods-setup/upe-preview-methods-selector/test/enable-upe-preview-task.test.js
  client/additional-methods-setup/wizard/task-item.scss
  client/components/payment-methods-list/payment-method.scss
  client/globals.d.ts
  client/payment-methods-map.tsx
  client/types/payment-methods.d.ts
  client/utils/account-fees.tsx
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments.php
  includes/constants/class-payment-method.php
  includes/payment-methods/class-affirm-payment-method.php
  includes/payment-methods/class-afterpay-payment-method.php
  includes/payment-methods/class-upe-payment-gateway.php
Labels: pr: needs author reply

#6462 Fix changelog for pre-release workflow when running from the release branch
  .github/actions/commit-push-as-bot/action.yml
  .github/actions/process-changelog/action.yml
  .github/workflows/create-pre-release.yml
  .github/workflows/release-pr.yml
  changelog/fix-changelog-pre-release-workflow
Labels: pr: ready to merge

#6290 Track WooPay button location updates
  changelog/add-track-woopay-express-btn-location-updates
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-woopay-tracker.php
Labels: pr: needs review, component: platform checkout

#6381 Clarify "disputed" order note: add amount and deadline
  changelog/fix-6379-clarify-disputed-order-note
  includes/class-wc-payments-explicit-price-formatter.php
  includes/class-wc-payments-order-service.php
  includes/class-wc-payments-webhook-processing-service.php
  tests/unit/test-class-wc-payments-order-service.php
  tests/unit/test-class-wc-payments-webhook-processing-service.php
Labels: pr: ready to merge

#6482 Introduce code ownership file
  .github/CODEOWNERS
  changelog/add-define-code-owners
Labels: pr: ready to merge

#6397 Move the overview task list to the welcome greeting to improve visibility
  changelog/fix-6382-move-overview-task-list
  client/overview/index.js
  client/overview/style.scss
  client/overview/task-list/index.js
Labels: pr: ready to merge

#6386 Update UPE settings block for BNLP
  assets/images/payment-methods/all_local_payments.svg
  assets/images/payment-methods/local_payments.svg
  changelog/update-6276-upe-settings-for-bnlp
  client/payment-methods/index.js
  client/payment-methods/style.scss
  client/payment-methods/test/index.js
Labels: pr: ready to merge

#6486 Add QIT integration for running security tests locally
  changelog/dev-qit-tests
  composer.json
  composer.lock
  package.json
  tests/qit/README.md
  tests/qit/config/default.env
  tests/qit/security.sh
Labels: pr: ready to merge

#6513 Make QIT changelog a comment
  changelog/dev-qit-tests
Labels: pr: ready to merge

#6514 Fix the ACTION_TYPE variable for the default case of the pre-release workflow
  .github/actions/process-changelog/action.yml
  changelog/fix-pre-release-workflow
Labels: pr: ready to merge

#6521 Links in subscription deactiavtion modal now open in a new tab
  changelog/add-target-blank-in-sub-deactivation-modal
  includes/subscriptions/templates/html-subscriptions-plugin-notice.php
Labels: pr: needs review

#6536 Bump WC versions
  .github/workflows/compatibility.yml
  .github/workflows/e2e-test.yml
  .github/workflows/php-lint-test.yml
  changelog/dev-bump-versions-6.1.0
  readme.txt
  woocommerce-payments.php
Labels: pr: needs review

#6398 BNPL: Add Affirm and Afterpay to settings
  changelog/add-6271-bnpl-checkboxes-to-settings
  client/payment-methods-map.tsx
  client/payment-methods/constants.ts
  client/payment-methods/index.js
  client/payment-methods/test/index.js
  client/types/payment-methods.d.ts
Labels: pr: ready to merge

#6538 Affirm&Afterpay: added logo for transactions listing and transaction details
  assets/css/admin.css
  changelog/add-6123-affirm-afterpay-logo
Labels: pr: ready to merge, component: affirm & afterpay

#6371 Improve the wording and style of the "Active Disputes" task list item on the Payments → Overview screen to highlight urgency
  changelog/add-overview-active-disputes-notice
  changelog/add-overview-active-disputes-notice-2
  client/globals.d.ts
  client/overview/index.js
  client/overview/style.scss
  client/overview/task-list/dispute-tasks.ts
  client/overview/task-list/index.js
  client/overview/task-list/tasks.js
  client/overview/task-list/test/tasks.js
  client/overview/task-list/types.d.ts
  client/overview/test/index.js
  client/tracks/index.js
  client/transactions/declarations.d.ts
  includes/admin/class-wc-payments-admin.php
Labels: pr: ready to merge

#6540 Affirm&Afterpay: respect supported payment ranges.
  changelog/fix-affirm-afterpay-respect-cart-total
  includes/payment-methods/class-affirm-payment-method.php
  includes/payment-methods/class-afterpay-payment-method.php
  includes/payment-methods/class-upe-payment-method.php
Labels: pr: needs review

#6492 Add Affirm and Afterpay to Block Checkout
  changelog/add-6231-bnpl-block-checkout
  client/checkout/blocks/confirm-upe-payment.js
  client/checkout/blocks/upe-fields.js
  client/checkout/blocks/upe-split-fields.js
  client/checkout/blocks/upe-split.js
  client/checkout/constants.js
  client/components/account-status/account-fees/test/__snapshots__/index.js.snap
  client/components/payment-method-details/index.js
  client/data/transactions/hooks.ts
  client/types/charges.d.ts
  client/utils/account-fees.tsx
  includes/class-wc-payment-gateway-wcpay.php
  includes/core/server/request/class-create-intention.php
  includes/payment-methods/class-affirm-payment-method.php
Labels: pr: ready to merge

#6295 Add a device type filter to the Transactions list page
  changelog/add-ttp-transactions-list-filter
  client/data/transactions/hooks.ts
  client/data/transactions/resolvers.js
  client/data/transactions/test/resolvers.js
  client/transactions/declarations.d.ts
  client/transactions/filters/config.ts
  client/transactions/filters/test/__snapshots__/index.tsx.snap
  client/transactions/filters/test/index.tsx
  client/transactions/list/index.tsx
  client/transactions/strings.ts
  includes/admin/class-wc-rest-payments-transactions-controller.php
  includes/core/server/request/class-list-transactions.md
  includes/core/server/request/class-list-transactions.php
  tests/unit/core/server/request/test-class-list-transactions-request.php
Labels: pr: ready to merge

#6544 Implement BNPL providers in classic checkout flow
  changelog/add-6119-bnpl-shortcode-checkout
  client/checkout/classic/upe-split.js
  client/checkout/classic/upe.js
Labels: pr: ready to merge

#6388 Fix some i18n issues in checkout
  changelog/add-fix-i18n-issues-in-checkout
  client/checkout/blocks/upe-fields.js
  client/checkout/blocks/upe-split-fields.js
  client/checkout/classic/upe-split.js
  client/checkout/classic/upe.js
  client/checkout/utils/fingerprint.js
Labels: pr: needs review

#6518 Add track events when BNPL is enabled/disabled
  changelog/add-bnpl-affirm-afterpay-track-events
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/admin/class-wc-rest-upe-flag-toggle-controller.php
  includes/class-wc-payments.php
  includes/constants/class-track-events.php
Labels: pr: ready to merge

#6334 Remove payment button when product price is 0
  changelog/add-5406-remove-payment-button-on-0-cart
  includes/class-wc-payments-payment-request-button-handler.php
Labels: pr: ready to merge

#6561 Increase the size of PO elegibility modal to avoid vertical scroll
  changelog/fix-6560-elegibility-modal-scroll
  client/overview/modal/progressive-onboarding-eligibility/style.scss
Labels: pr: ready to merge

#6555 Improve validation when `Enter` key is pressed
  changelog/6547-validation-po-form
  client/components/phone-number-control/index.tsx
  client/components/phone-number-control/test/index.test.tsx
  client/onboarding-prototype/form.tsx
Labels: pr: ready to merge

#6436 Add support for deposit schedule restrictions
  changelog/add-deposit-schedule-restriction-support
  client/data/settings/hooks.js
  client/data/settings/selectors.js
  client/settings/deposits/index.js
  client/settings/deposits/test/index.test.js
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
Labels: pr: needs review

#6468 Add validation for Multi-Currency settings updates (and minor text fixes)
  changelog/add-validation-for-mc-settings
  client/multi-currency-setup/tasks/store-settings-task/index.js
  client/multi-currency-setup/tasks/store-settings-task/test/__snapshots__/index.test.js.snap
  client/multi-currency/multi-currency-settings/enabled-currencies-list/modal.js
  client/multi-currency/multi-currency-settings/enabled-currencies-list/test/__snapshots__/index.js.snap
  client/multi-currency/multi-currency-settings/enabled-currencies-list/test/index.js
  includes/multi-currency/Exceptions/InvalidCurrencyException.php
  includes/multi-currency/Exceptions/InvalidCurrencyRateException.php
  includes/multi-currency/MultiCurrency.php
  includes/multi-currency/PaymentMethodsCompatibility.php
  includes/multi-currency/RestController.php
  tests/unit/multi-currency/test-class-multi-currency.php
  tests/unit/multi-currency/test-class-rest-controller.php
Labels: pr: needs review, component: customer multi-currency

#6556 Add additional validation in VAT controller
  changelog/add-add-validation-vat-controller
  includes/admin/class-wc-rest-payments-vat-controller.php
Labels: pr: ready to merge

#6242 Refactor the DownloadButton component to use TypeScript
  changelog/dev-ts-refactor-download-button
  client/components/download-button/index.tsx
  client/components/download-button/test/__snapshots__/index.tsx.snap
  client/components/download-button/test/index.tsx
Labels: type: task, category: refactor

#6243 Refactor the InlineNotice component to use TypeScript
  changelog/dev-ts-refactor-inline-notice
  client/components/inline-notice/index.tsx
Labels: type: task, category: refactor

#6504 Fix issue where checkbox remained disabled when credit card was disabled
  changelog/fix-5525-cant-enable-cc-payments
  client/payment-methods/index.js
Labels: pr: ready to merge

#6419 Fix Pay for Order missing item count meta, wrong fraud box type, missing status codes on json errors, and confirming after error response
  changelog/fix-6278-frt-meta-missing-on-manual-capture
  client/checkout/classic/index.js
  client/checkout/classic/upe-split.js
  client/checkout/classic/upe.js
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-payment-request-button-handler.php
  includes/class-wc-payments-utils.php
  includes/fraud-prevention/class-buyer-fingerprinting-service.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/payment-methods/class-upe-split-payment-gateway.php
  tests/e2e/env/setup.sh
  tests/js/jest.config.js
Labels: pr: needs review

#6245 Refactor the ProgressBar component to use TypeScript
  changelog/dev-ts-refactor-progress-bar
  client/components/progress-bar/index.tsx
  client/components/progress-bar/test/__snapshots__/index.tsx.snap
  client/components/progress-bar/test/index.tsx
Labels: type: task, category: refactor

#6350 Add support for Czech Republic, Hungary, and Sweden
  changelog/add-intl-expansion-phase3-batch2
  client/utils/account-fees.tsx
  includes/class-wc-payments-utils.php
  includes/class-wc-payments.php
Labels: pr: needs review

#6570 Affirm&Afterpay: messaging element shall not appear for subscription products.
  changelog/update-messaging-element-hide-for-subscriptions
  includes/class-wc-payments.php
Labels: pr: ready to merge

#6548 WC Home active disputes task: improve wording and reduce `due_by` threshold to align with Payments Overview task
  changelog/update-6505-dispute-task-wc-home
  client/overview/task-list/dispute-tasks.ts
  client/overview/task-list/test/tasks.js
  includes/admin/tasks/class-wc-payments-task-disputes.php
  includes/class-database-cache.php
  includes/class-wc-payments-webhook-processing-service.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/admin/tasks/test-class-wc-payments-task-disputes.php
Labels: pr: ready to merge

#6475 Show description dispute reasons in order notes
  changelog/fix-6474-consistent-dispute-naming
  client/disputes/strings.ts
  includes/class-wc-payments-order-service.php
  includes/class-wc-payments-utils.php
  tests/unit/test-class-wc-payments-order-service.php
Labels: pr: ready to merge

#6568 Improve the logic which determines if a subscriptions plugin is being activated
  changelog/fix-tighten-subscriptions-plugin-activate-logic
  woocommerce-payments.php
Labels: pr: needs review

#6571 Add connect page incentive
  assets/images/illustrations/connect-hero.png
  changelog/add-connect-incentive
  client/components/tip-box/index.tsx
  client/components/tip-box/style.scss
  client/connect-account-page/incentive.tsx
  client/connect-account-page/index.tsx
  client/connect-account-page/info-notice-modal.tsx
  client/connect-account-page/payment-methods.tsx
  client/connect-account-page/strings.tsx
  client/connect-account-page/style.scss
  client/connect-account-page/test/__snapshots__/index.test.tsx.snap
  client/connect-account-page/test/index.test.tsx
  client/external-declarations.d.ts
  client/globals.d.ts
  client/stylesheets/abstracts/_mixins.scss
  client/utils/sanitize.ts
  client/utils/test/sanitize.test.ts
  includes/admin/class-wc-payments-admin.php
  includes/class-database-cache.php
  includes/class-wc-payments-incentives-service.php
  includes/class-wc-payments.php
  tests/unit/admin/test-class-wc-payments-admin.php
  tests/unit/test-class-wc-payments-incentives-service.php
Labels: pr: ready to merge

#6585 Affirm&Afterpay: add new test cases.
  changelog/add-tests-affirm-afterpay-methods-availability
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
Labels: pr: ready to merge

#6603 Handle when `get_disputes_needing_response()` returns non-array.
  changelog/fix-6597-fatal-error-dispute-task-wc-home
  includes/admin/tasks/class-wc-payments-task-disputes.php
Labels: pr: ready to merge

#6605 Affirm&Afterpay: refactor subscription product detection.
  changelog/dev-affirm-afterpay-subscription-detection-enahnce
  includes/class-wc-payments.php
  psalm-baseline.xml
Labels: pr: ready to merge

#6580 Fixed typo in businessInfo strings in strings.tsx file
  changelog/6368-fix-typo-business-info
  client/connect-account-page/strings.tsx
  client/connect-account-page/test/__snapshots__/info-notice-modal.test.tsx.snap
Labels: pr: needs review

#6614 Wrap logos to not overlap the container
  changelog/fix-6590-wrap-logos-on-confirmation-screen
  client/additional-methods-setup/upe-preview-methods-selector/setup-complete-task.scss
Labels: pr: ready to merge

#6629 Hotfix: additional filters on deposits
  changelog/hotfix-fix-deposits-adv-filters
  client/deposits/filters/config.js
  client/deposits/filters/test/index.js
Labels: pr: needs review

#6623 Allow skipping the build zip job when running the "Release - Create a PR" workflow
  .github/workflows/release-pr.yml
  changelog/update-release-pr-workflow
Labels: pr: ready to merge
