Repository Automattic/woocommerce-payments, pull requests merged in 2023-12, with the labels that each got.

#7816 Update dispute winning e2e test to look for other text that does not depend on webhook.
  changelog/update-dispute-winning-e2e-test-no-webhook
  tests/e2e/specs/wcpay/merchant/merchant-disputes-submit-winning.spec.js
Labels: pr: ready to merge

#7811 Add connect page non supported country banner
  changelog/add-7699-non-supported-country-banner
  client/connect-account-page/index.tsx
  client/connect-account-page/strings.tsx
  client/connect-account-page/test/index.test.tsx
Labels: pr: needs review

#7820 Update settings redirection to handle every case
  changelog/fix-7730-better-hadling-settings-redirection
  includes/class-wc-payments-account.php
  tests/unit/test-class-wc-payments-account.php
Labels: pr: needs review

#7754 Introduce filters for channel, customer country, and risk level on the transactions list page
  changelog/add-7596-transactions-filters
  client/data/transactions/hooks.ts
  client/data/transactions/resolvers.js
  client/deposits/details/test/index.tsx
  client/transactions/declarations.d.ts
  client/transactions/filters/config.ts
  client/transactions/filters/test/__snapshots__/index.tsx.snap
  client/transactions/filters/test/index.tsx
  client/transactions/list/index.tsx
  client/transactions/strings.ts
  includes/admin/class-wc-rest-payments-transactions-controller.php
  includes/core/server/request/class-list-transactions.md
  includes/core/server/request/class-list-transactions.php
  tests/js/jest-test-file-setup.js
  tests/unit/core/server/request/test-class-list-transactions-request.php
Labels: pr: ready to merge

#7769 Fix missing order numbers from transaction report CSV
  changelog/fix-7592-update-transaction-order-id
  includes/subscriptions/class-wc-payments-invoice-service.php
  includes/subscriptions/class-wc-payments-subscriptions-event-handler.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/subscriptions/test-class-wc-payments-subscriptions-event-handler.php
Labels: pr: ready to merge

#7826 Update Fraud & Risk docs link text in settings
  changelog/update-6325-fraud-risk-link-text-in-settings
  client/settings/settings-manager/index.js
Labels: pr: ready to merge

#7862 Decode HTML entities in international IP filter country list
  changelog/fix-7838-fraud-filters-html-encode-bug
  client/settings/fraud-protection/advanced-settings/allow-countries-notice.tsx
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/allow-countries-notice.test.tsx.snap
  client/settings/fraud-protection/advanced-settings/test/allow-countries-notice.test.tsx
Labels: pr: needs review

#7830 Refresh account balance amounts on the Payments Overview screen upon successful instant deposit
  changelog/fix-refresh-payments-overview-account-balances-on-instant-deposit
  client/data/deposits/actions.js
Labels: pr: ready to merge

#7800 Remove "Set-up refund policy" Inbox note
  changelog/update-change-setup-refund-policy-note-into-task
  includes/class-wc-payments.php
  includes/notes/class-wc-payments-notes-set-up-refund-policy.php
  psalm.xml
  tests/unit/notes/test-class-wc-payments-notes-set-up-refund-policy.php
Labels: pr: ready to merge

#7860 Update payment assets to match partner brand guidelines
  assets/images/cards/amex.svg
  assets/images/cards/diners.svg
  assets/images/cards/discover.svg
  assets/images/cards/visa.svg
  assets/images/payment-methods/cc.svg
  changelog/fix-update-payment-assets
Labels: pr: ready to merge

#7787 Include discount in fees brakedown tooltip
  changelog/fix-7750-include-discount-in-tooltip
  client/utils/account-fees.tsx
  client/utils/test/__snapshots__/account-fees.tsx.snap
  client/utils/test/account-fees.tsx
Labels: pr: ready to merge

#7825 Update Qualitative Feedback note to have more efficient sql query
  changelog/fix-3693-qualitative-feedback-note
  includes/notes/class-wc-payments-notes-qualitative-feedback.php
Labels: pr: ready to merge

#7875 Show deposit schedule message if account's deposits are unrestricted
  changelog/fix-7874-show-deposit-schedule-when-zero-available-balance
  client/components/deposits-overview/deposit-schedule.tsx
  client/components/deposits-overview/index.tsx
  client/components/deposits-overview/test/__snapshots__/index.tsx.snap
  client/components/deposits-overview/test/index.tsx
  client/globals.d.ts
Labels: pr: ready to merge

#7878 Transactions List - indicate when a transaction is expected to be included in a future deposit
  changelog/add-transaction-list-future-deposit
  client/transactions/list/deposit.tsx
  client/transactions/list/index.tsx
  client/transactions/list/style.scss
  client/transactions/list/test/__snapshots__/deposit.tsx.snap
  client/transactions/list/test/__snapshots__/index.tsx.snap
  client/transactions/list/test/deposit.tsx
Labels: pr: ready to merge

#7883 Show a deposit schedule notice on the deposits list page
  changelog/add-7877-deposit-list-next-deposit-notice
  client/deposits/index.tsx
  client/globals.d.ts
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-wc-payments-features.php
  includes/class-wc-payments.php
Labels: pr: ready to merge

#7882 Show notice when no funds ready for deposit
  changelog/fix-7879-show-notice-when-no-funds-ready-for-deposit
  client/components/deposits-overview/deposit-notices.tsx
  client/components/deposits-overview/index.tsx
Labels: pr: ready to merge

#7902 Deposits: Remove unnecessary notice when account is in new account waiting period
  changelog/fix-7901-excess-deposit-notices
  client/components/deposits-overview/index.tsx
Labels: pr: ready to merge

#7906 Deposits List - Hide the next deposit notice if account witin the new account waiting period
  changelog/fix-7904-hide-next-deposit-notice-within-waiting-period
  client/deposits/index.tsx
Labels: pr: ready to merge

#7908 Improve consistency of tooltip text style
  changelog/fix-7905-transactions-list-tooltip-styles
  client/components/tooltip/style.scss
  client/transactions/list/style.scss
Labels: pr: ready to merge

#7813 Introduce additional columns to the Transaction list UI
  changelog/add-7591-missing-columns-export-csv
  client/transactions/list/index.tsx
  client/transactions/list/test/__snapshots__/index.tsx.snap
  client/transactions/list/test/index.tsx
Labels: pr: ready to merge

#7891 Use CardNotice component for authorization notification in transaction details page
  changelog/fix-7748-capture-notification-styles-are-broken
  client/payment-details/summary/index.tsx
  client/payment-details/summary/test/__snapshots__/index.test.tsx.snap
Labels: pr: ready to merge

#7921 Correct the `AccountOverview.OverviewsResponse` TS interface `account` type to show it is nullable
  changelog/fix-7920-correct-account-overview-account-type-nullable
  client/components/account-balances/index.tsx
  client/overview/hooks.ts
  client/types/account-overview.d.ts
Labels: pr: ready to merge

#7851 Allow test support phone in dev mode
  changelog/fix-6782-support-phone-dev-mode
  client/settings/support-phone-input/index.js
  client/settings/support-phone-input/test/support-phone-input.test.js
Labels: pr: ready to merge

#7743 Cancel non-captured authorizations if order is cancelled.
  changelog/add-5605-cancel-authorizations-if-order-is-cancelled
  client/order/cancel-authorization-confirm-modal/index.tsx
  client/order/index.js
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-order-service.php
  tests/unit/helpers/class-wc-helper-intention.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-order-service.php
Labels: pr: ready to merge

#7915 Include level3 data when capturing an authorization.
  changelog/fix-6806-authorizations-level-3-data-error-while-trying-to-capture-partial-amount
  client/payment-methods-map.tsx
  client/payment-methods/capability-request/index.tsx
  client/transactions/list/index.tsx
  includes/admin/class-wc-rest-payments-orders-controller.php
Labels: pr: ready to merge

#7935 Fix currency negative sign position on JS rendered amounts
  changelog/fix-6700-remove-currency-sign-modification-code
  client/payment-details/summary/test/__snapshots__/index.test.tsx.snap
  client/payment-details/summary/test/index.test.tsx
  client/payment-details/timeline/test/__snapshots__/index.js.snap
  client/payment-details/timeline/test/__snapshots__/map-events.js.snap
  client/transactions/list/test/__snapshots__/index.tsx.snap
  client/utils/currency/index.js
  includes/class-wc-payments-utils.php
  tests/fixtures/captured-payments/discount.json
  tests/fixtures/captured-payments/foreign-card.json
  tests/fixtures/captured-payments/fx-decimal.json
  tests/fixtures/captured-payments/fx-foreign-card.json
  tests/fixtures/captured-payments/fx-with-capped-fee.json
  tests/fixtures/captured-payments/fx.json
  tests/fixtures/captured-payments/jpy-payment.json
  tests/fixtures/captured-payments/only-base-fee.json
  tests/fixtures/captured-payments/subscription.json
  tests/unit/test-class-wc-payments-utils.php
Labels: pr: needs review

#7898 Add test mode notice in page order detail.
  changelog/add-334-test-mode-notice-order-details
  client/order/index.js
  client/order/test-mode-notice/index.tsx
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-action-scheduler-service.php
  includes/class-wc-payments-order-service.php
  includes/class-wc-payments.php
  includes/constants/class-order-mode.php
  src/Internal/Service/OrderService.php
  src/Internal/Service/PaymentProcessingService.php
Labels: pr: needs review

#7914 Reset Account Management
  changelog/dev-3468-allow-reset-account-management
  client/components/account-status/account-fees/index.js
  client/components/account-status/account-fees/styles.scss
  client/components/account-status/account-fees/test/__snapshots__/index.js.snap
  client/components/account-status/account-tools/index.tsx
  client/components/account-status/account-tools/strings.tsx
  client/components/account-status/account-tools/styles.scss
  client/components/account-status/account-tools/test/__snapshots__/index.test.tsx.snap
  client/components/account-status/account-tools/test/index.test.tsx
  client/components/account-status/index.js
  client/components/account-status/test/__snapshots__/index.js.snap
  client/onboarding/tracking.ts
  client/overview/modal/reset-account/index.tsx
  client/overview/modal/reset-account/strings.tsx
  client/overview/modal/reset-account/style.scss
  client/overview/modal/reset-account/test/index.test.tsx
  client/tracks/index.js
  client/utils/index.js
  includes/class-wc-payments-account.php
Labels: pr: needs review, pr: needs design review

#7939 Modify the test support phone numbers
  changelog/fix-test-support-phone
  client/settings/support-phone-input/index.js
Labels: pr: needs review

#7931 Display a Confirmation Modal before enabling Test Mode
  changelog/add-7846-test-mode-confirm-modal
  client/settings/general-settings/index.js
  client/settings/general-settings/test-mode-confirm-modal.tsx
  client/settings/general-settings/test/general-settings.test.js
  client/settings/general-settings/test/test-mode-confirm-modal.test.js
Labels: pr: ready to merge

#7943 Bump WC tested up to version to 8.4.0
  changelog/dev-bump-wc-version-8-4-0
  woocommerce-payments.php
Labels: pr: needs review
