Repository Automattic/woocommerce-payments, pull requests merged in 2023-10, with the labels that each got.

#7308 Fraud Services - Remove hooks from constructor
  changelog/dev-7261-remove-hooks-from-fraud-services-constructor-2
  dev/phpcs/ruleset.xml
  includes/class-wc-payments-fraud-service.php
  includes/class-wc-payments.php
  includes/fraud-prevention/class-fraud-risk-tools.php
  includes/fraud-prevention/class-order-fraud-and-risk-meta-box.php
  tests/unit/fraud-prevention/test-class-fraud-risk-tools.php
  tests/unit/fraud-prevention/test-class-order-fraud-and-risk-meta-box.php
  tests/unit/test-class-wc-payments-fraud-service.php
Labels: pr: ready to merge, type: technical debt

#7317 Fix variable virtual products require a shipping address for Apple Pay and Google Pay
  changelog/fix-6714-request-button-virtual-variable
  client/payment-request/index.js
Labels: pr: ready to merge

#7330 Move hooks out of MultiCurrency class constructors into own init_hooks methods
  changelog/dev-7258-remove-hooks-from-multi-currency-constructor
  dev/phpcs/ruleset.xml
  includes/multi-currency/AdminNotices.php
  includes/multi-currency/BackendCurrencies.php
  includes/multi-currency/CurrencySwitcherBlock.php
  includes/multi-currency/FrontendCurrencies.php
  includes/multi-currency/FrontendPrices.php
  includes/multi-currency/Helpers/OrderMetaHelper.php
  includes/multi-currency/MultiCurrency.php
  includes/multi-currency/PaymentMethodsCompatibility.php
  includes/multi-currency/Settings.php
  includes/multi-currency/SettingsOnboardCta.php
  includes/multi-currency/Tracking.php
  includes/multi-currency/UserSettings.php
  tests/unit/multi-currency/test-class-admin-notices.php
  tests/unit/multi-currency/test-class-backend-currencies.php
  tests/unit/multi-currency/test-class-currency-switcher-block.php
  tests/unit/multi-currency/test-class-frontend-currencies.php
  tests/unit/multi-currency/test-class-frontend-prices.php
  tests/unit/multi-currency/test-class-payment-methods-compatibility.php
  tests/unit/multi-currency/test-class-settings.php
  tests/unit/multi-currency/test-class-tracking.php
  tests/unit/multi-currency/test-class-user-settings.php
Labels: pr: needs review

#7310 add a new page component for redirecting disputes => details:
  changelog/fix-6891-redirect-dispute-detail-to-transaction
  client/data/disputes/action-types.js
  client/data/disputes/actions.js
  client/data/disputes/hooks.ts
  client/data/disputes/reducer.js
  client/data/disputes/resolvers.js
  client/data/disputes/selectors.js
  client/data/disputes/test/resolvers.js
  client/disputes/details/index.tsx
  client/disputes/redirect-to-transaction-details/index.tsx
  client/disputes/redirect-to-transaction-details/style.scss
  client/index.js
  includes/admin/class-wc-payments-admin.php
Labels: pr: needs author reply

#7224 Add JCB capability request notice
  changelog/add-jcb-capability-request
  client/components/inline-notice/index.tsx
  client/components/payment-methods-list/payment-method.tsx
  client/components/payment-methods-list/style.scss
  client/globals.d.ts
  client/payment-methods-map.tsx
  client/payment-methods/capability-request/capability-request-dismiss-modal.tsx
  client/payment-methods/capability-request/capability-request-map.ts
  client/payment-methods/capability-request/capability-request-notice.tsx
  client/payment-methods/capability-request/index.tsx
  client/payment-methods/capability-request/test/__snapshots__/index.test.js.snap
  client/payment-methods/capability-request/test/dismiss-modal.test.js
  client/payment-methods/capability-request/test/index.test.js
  client/payment-methods/capability-request/types.ts
  client/payment-methods/constants.ts
  client/payment-methods/index.js
  client/payment-methods/test/index.js
  client/types/notices.d.ts
  client/types/payment-methods.d.ts
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments.php
  includes/constants/class-payment-method.php
  includes/payment-methods/class-jcb-payment-method.php
  includes/payment-methods/class-upe-payment-gateway.php
Labels: pr: needs review

#7140 HACK week: Display server error messages on Settings save
  changelog/add-settings-save-error-notice
  client/data/settings/actions.js
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  tests/unit/test-class-wc-payments-account.php
Labels: pr: needs review

#7202 Add helper function/method for raw amount conversion
  changelog/fix-5524-price-conversion-helper-function
  includes/multi-currency/MultiCurrency.php
  tests/unit/multi-currency/test-class-multi-currency.php
  tests/unit/multi-currency/test-class-rest-controller.php
Labels: pr: ready to merge

#7269 Update Name Your Price compatibility to use new Compatibility methods
  changelog/fix-7172-nyp-cart-editing
  includes/multi-currency/Compatibility/WooCommerceNameYourPrice.php
  tests/unit/multi-currency/compatibility/test-class-woocommerce-name-your-price.php
Labels: pr: ready to merge, component: customer multi-currency

#7344 API endpoint to fetch customer's saved payment methods.
  changelog/add-7322-saved-payment-methods-api
  includes/admin/class-wc-rest-payments-customer-controller.php
  includes/class-wc-payments.php
  tests/unit/admin/test-class-wc-rest-payments-customer-controller.php
  tests/unit/bootstrap.php
Labels: pr: needs author reply

#7356 Send current user fingerprint data on onboarding init
  changelog/add-7342-send-merchant-fingerprint-data-on-onboarding
  includes/class-wc-payments-account.php
  includes/class-wc-payments-fraud-service.php
  includes/class-wc-payments-session-service.php
  includes/class-wc-payments-token-service.php
  includes/class-wc-payments.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/test-class-wc-payments-account-capital.php
  tests/unit/test-class-wc-payments-account-link.php
  tests/unit/test-class-wc-payments-account.php
  tests/unit/test-class-wc-payments-fraud-service.php
  tests/unit/test-class-wc-payments-session-service.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: needs review

#6791 Endpoint for creating a payment intent
  changelog/update-payment-intent-create-endpoint
  includes/admin/class-wc-rest-payments-payment-intents-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments.php
  tests/unit/admin/test-class-wc-rest-payments-payment-intents-controller.php
  tests/unit/bootstrap.php
Labels: needs feedback

#7362 Update URL to connect with WooPay
  changelog/update-2179-woopay-connection-url
  client/checkout/woopay/express-button/woopay-express-checkout-button.js
Labels: type: enhancement

#7298 Disputes: Allow merchant to respond to inquiries from transaction detail page
  changelog/add-7193-dispute-cta-for-inquries
  client/payment-details/dispute-details/dispute-awaiting-response-details.tsx
  client/payment-details/summary/index.tsx
  client/payment-details/summary/test/index.test.tsx
  client/tracks/index.js
Labels: pr: ready to merge

#7292 Transaction Details → Show steps to resolve for inquiries
  changelog/add-7245-transaction-details-inquiry-steps-to-resolve
  client/payment-details/dispute-details/dispute-awaiting-response-details.tsx
  client/payment-details/dispute-details/dispute-due-by-date.tsx
  client/payment-details/dispute-details/dispute-steps.tsx
  client/payment-details/dispute-details/dispute-summary-row.tsx
  client/payment-details/summary/test/index.test.tsx
  client/types/disputes.d.ts
Labels: pr: ready to merge

#7365 Enable transaction dispute details feature for all merchants (remove feature flag)
  changelog/add-7289-remove-transaction-dispute-details-feature-flag
  client/globals.d.ts
  client/index.js
  client/payment-details/summary/index.tsx
  client/payment-details/summary/test/__snapshots__/index.test.tsx.snap
  client/payment-details/summary/test/index.test.tsx
  client/settings/wcpay-settings-context.js
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-features.php
Labels: pr: needs review

#7088 Remove 'View dispute' link in Transaction Timeline
  changelog/fix-6928-remove-transaction-details-view-dispute-link
  client/payment-details/timeline/map-events.js
  client/payment-details/timeline/test/__snapshots__/index.js.snap
  client/payment-details/timeline/test/__snapshots__/map-events.js.snap
  tests/e2e/specs/wcpay/merchant/merchant-disputes-save-for-editing.spec.js
  tests/e2e/specs/wcpay/merchant/merchant-disputes-submit-losing.spec.js
  tests/e2e/specs/wcpay/merchant/merchant-disputes-submit-winning.spec.js
  tests/e2e/utils/flows.js
Labels: pr: ready to merge

#7318 RPP: Payments skeleton
  changelog/rpp-6686-payments-skeleton
  includes/class-wc-payment-gateway-wcpay.php
  src/Internal/DependencyManagement/ServiceProvider/PaymentsServiceProvider.php
  src/Internal/Payment/Exception/StateTransitionException.php
  src/Internal/Payment/PaymentContext.php
  src/Internal/Payment/State/AbstractPaymentState.php
  src/Internal/Payment/State/CompletedState.php
  src/Internal/Payment/State/InitialState.php
  src/Internal/Payment/State/StateFactory.php
  src/Internal/Service/PaymentProcessingService.php
  tests/unit/src/Internal/Payment/State/AbstractPaymentStateTest.php
  tests/unit/src/Internal/Payment/State/InitialStateTest.php
  tests/unit/src/Internal/Payment/State/StateFactoryTest.php
  tests/unit/src/Internal/Service/PaymentProcessingServiceTest.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge

#7355 Moving hook initialisation functions out of constructors
  changelog/dev-7262-remove-hooks-from-constructors
  dev/phpcs/ruleset.xml
  includes/class-wc-payments-account.php
  includes/class-wc-payments-incentives-service.php
  includes/class-wc-payments-onboarding-service.php
  includes/class-wc-payments.php
  tests/unit/test-class-wc-payments-account-capital.php
  tests/unit/test-class-wc-payments-account-link.php
  tests/unit/test-class-wc-payments-account.php
  tests/unit/test-class-wc-payments-incentives-service.php
  tests/unit/test-class-wc-payments-onboarding-service.php
Labels: pr: ready to merge

#7282 Introduce Klarna PM
  assets/css/admin.css
  assets/images/payment-methods/klarna.svg
  changelog/add-7243-introduce-klarna-pm
  client/additional-methods-setup/constants.js
  client/checkout/blocks/upe-split.js
  client/checkout/classic/upe-split.js
  client/checkout/constants.js
  client/components/payment-method-details/index.js
  client/payment-details/payment-method/index.js
  client/payment-details/payment-method/klarna/index.js
  client/payment-methods-map.tsx
  client/payment-methods/constants.ts
  client/types/charges.d.ts
  client/types/payment-methods.d.ts
  client/utils/account-fees.tsx
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments.php
  includes/constants/class-payment-method.php
  includes/payment-methods/class-klarna-payment-method.php
  includes/payment-methods/class-upe-payment-gateway.php
Labels: pr: ready to merge, component: klarna

#7315 Restrict PMs to location in deferred UPE implementation
  client/checkout/classic/upe-deferred-intent-creation/event-handlers.js
  client/checkout/utils/upe.js
Labels: type: bug, pr: needs review, component: affirm & afterpay

#7324 RPP: Working Data
  changelog/rpp-6688-working-data
  includes/class-wc-payments.php
  src/Container.php
  src/Internal/DependencyManagement/DelegateContainer/LegacyContainer.php
  src/Internal/DependencyManagement/ServiceProvider/GenericServiceProvider.php
  src/Internal/DependencyManagement/ServiceProvider/PaymentsServiceProvider.php
  src/Internal/Payment/PaymentContext.php
  src/Internal/Payment/PaymentMethod/SavedPaymentMethod.php
  src/Internal/Payment/PaymentRequest.php
  src/Internal/Payment/State/InitialState.php
  src/Internal/Service/OrderService.php
  src/Internal/Service/PaymentProcessingService.php
  tests/unit/src/Internal/DependencyManagement/DelegateContainer/LegacyContainerTest.php
  tests/unit/src/Internal/Payment/PaymentContextTest.php
  tests/unit/src/Internal/Payment/PaymentMethod/SavedPaymentMethodTest.php
  tests/unit/src/Internal/Payment/PaymentRequestTest.php
  tests/unit/src/Internal/Payment/State/InitialStateTest.php
  tests/unit/src/Internal/Service/OrderServiceTest.php
  tests/unit/src/Internal/Service/PaymentProcessingServiceTest.php
Labels: pr: needs review

#7336 Hide helper text related to Storefront theme in Multi-Currency settings when Storefront is not the active theme
  changelog/fix-6182-hide-storefront-tooltip
  client/multi-currency-setup/tasks/store-settings-task/index.js
  client/multi-currency-setup/tasks/store-settings-task/test/__snapshots__/index.test.js.snap
  client/multi-currency/multi-currency-settings/store-settings/index.js
Labels: pr: ready to merge

#7345 Fix payment method section missing for Affirm and Afterpay on transaction details page
  changelog/fix-7343-missing-payment-details-section-in-payment-details-page-for-affirm-and-afterpay-payment-methods
  client/payment-details/payment-method/affirm/index.js
  client/payment-details/payment-method/afterpay-clearpay/index.js
  client/payment-details/payment-method/index.js
Labels: pr: ready to merge

#7333 RPP: Extract gateway methods
  changelog/rpp-extract-gateway-methods
  includes/admin/class-wc-rest-payments-payment-intents-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments.php
  src/Internal/DependencyManagement/ServiceProvider/GenericServiceProvider.php
  src/Internal/Proxy/HooksProxy.php
  src/Internal/Proxy/LegacyProxy.php
  src/Internal/Service/Level3Service.php
  src/Internal/Service/OrderService.php
  tests/WCPAY_UnitTestCase.php
  tests/unit/admin/test-class-wc-rest-payments-payment-intents-controller.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
  tests/unit/payment-methods/test-class-upe-split-payment-gateway.php
  tests/unit/src/Internal/Proxy/HooksProxyTest.php
  tests/unit/src/Internal/Service/Level3ServiceTest.php
  tests/unit/src/Internal/Service/OrderServiceTest.php
  tests/unit/test-class-wc-payment-gateway-wcpay-payment-types.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: needs review

#7369 Added documentation for payment methods API
  changelog/add-7368-add-api-documentation-for-payment-methods-api
  docs/rest-api/source/includes/wp-api-v3/customer.md
Labels: pr: needs review

#7384 Add documentation for create payment intent api endpoint
  changelog/add-7381-add-documentation-for-create-payment-intent-api-endpoint
  docs/rest-api/source/includes/wp-api-v3/intent.md
Labels: pr: needs review

#7386 Prevent onboarding flow access without server connection
  changelog/fix-7360-non-connected-onboarding-flow-access
  includes/admin/class-wc-payments-admin.php
  tests/unit/admin/test-class-wc-payments-admin.php
Labels: pr: ready to merge

#7309 Add e2e tests for progressive onboarding
  changelog/dev-6214-e2e-tests-for-progressive-onboarding
  client/components/custom-select-control/index.tsx
  client/components/grouped-select-control/index.tsx
  client/onboarding/form.tsx
  tests/e2e/specs/wcpay/merchant/merchant-progressive-onboarding.spec.js
  tests/e2e/utils/flows.js
Labels: pr: ready to merge

#7361 Fix MultiCurrency onboarding settings page on Woo Express
  changelog/fix-6466-mc-errors
  includes/multi-currency/SettingsOnboardCta.php
Labels: pr: ready to merge

#7389 Added missing API docs sidebar links
  changelog/fix-docs-api-add-missing-sidebar-links-for-intent-and-pm
  docs/rest-api/source/includes/wp-api-v3/intent.md
  docs/rest-api/source/index.html.md
Labels: pr: ready to merge

#7205 Load MultiCurrency class on Multi-currency setup page
  changelog/fix-7151-multi-currency-onboarding
  client/data/multi-currency/actions.js
  client/multi-currency-setup/tasks/add-currencies-task/index.js
  client/multi-currency-setup/tasks/add-currencies-task/test/__snapshots__/index.test.js.snap
  client/multi-currency-setup/tasks/add-currencies-task/test/index.test.js
  client/multi-currency-setup/tasks/store-settings-task/index.js
  client/multi-currency-setup/tasks/store-settings-task/test/index.test.js
  includes/class-wc-payments.php
  includes/multi-currency/wc-payments-multi-currency.php
Labels: pr: ready to merge

#7390 Add multi-currency enablement check to WooPay session handler
  changelog/fix-7329-missing-multi-currency-check
  includes/woopay/class-woopay-session.php
  tests/unit/woopay/test-class-woopay-session.php
Labels: component: WooPay

#7379 Transaction Details → show dispute amount in shopper currency
  changelog/fix-7373-show-dispute-amount-in-shopper-currency
  changelog/update-7124-transaction-details-dispute-amount-currency
  client/disputes/utils.ts
  client/payment-details/dispute-details/dispute-summary-row.tsx
  client/payment-details/summary/test/index.test.tsx
Labels: pr: ready to merge

#7374 Disputes: wording for disputes implying that fee has not yet been deducted
  changelog/fix-7254-update-dispute-fee-text
  client/payment-details/dispute-details/dispute-awaiting-response-details.tsx
  client/payment-details/dispute-details/dispute-steps.tsx
Labels: pr: ready to merge

#7378 Disputes: Prevent errors crashing the payment details page
  changelog/add-7371-dispute-details-error-boundary
  client/payment-details/summary/index.tsx
Labels: pr: ready to merge

#7394 Gate dispute issuer evidence behind a feature flag.
  changelog/update-7372-issuer-evidence
  client/globals.d.ts
  client/payment-details/dispute-details/dispute-awaiting-response-details.tsx
  client/payment-details/dispute-details/evidence-list.tsx
  client/settings/wcpay-settings-context.js
  client/types/disputes.d.ts
  includes/class-wc-payments-features.php
Labels: pr: needs review

#7087 Change `Dispute → Details` links to `Transaction → Details`
  changelog/fix-6929-change-dispute-details-links-to-transactions-details
  client/disputes/index.tsx
  client/disputes/test/__snapshots__/index.tsx.snap
  client/order/index.js
  client/overview/task-list/tasks/dispute-task.tsx
  includes/admin/tasks/class-wc-payments-task-disputes.php
  includes/class-wc-payments-order-service.php
  includes/class-wc-payments-webhook-processing-service.php
  tests/unit/test-class-wc-payments-order-service.php
Labels: pr: ready to merge

#7238 Update Subscriptions with WooPayments eligibility as we move to deprecate this functionality
  changelog/issue-6510-deprecate-wcpay-subscriptions
  client/settings/advanced-settings/wcpay-subscriptions-toggle.js
  includes/class-wc-payments-features.php
  includes/class-wc-payments.php
Labels: pr: ready to merge

#7400 Update steps to resolve wording in dispute details on transaction details page
  changelog/update-7380-steps-to-resolve-wording
  client/payment-details/dispute-details/dispute-steps.tsx
  client/payment-details/summary/test/index.test.tsx
Labels: pr: ready to merge

#7398 Use consistent colors on transaction page when disputed.
  changelog/fix-7396-disputestatuschip
  client/components/dispute-status-chip/index.tsx
  client/payment-details/summary/index.tsx
Labels: pr: ready to merge

#7391 Bump minimum PHP version to 7.4 for WooCommerce beta matrix only.
  .github/workflows/compatibility.yml
  changelog/fix-bump-min-php-wc-beta
Labels: pr: ready to merge

#7332 RPP: Minimal Checkout
  changelog/rpp-basic-process
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-customer-service.php
  src/Internal/DependencyManagement/ServiceProvider/GenericServiceProvider.php
  src/Internal/DependencyManagement/ServiceProvider/PaymentsServiceProvider.php
  src/Internal/Payment/PaymentContext.php
  src/Internal/Payment/PaymentRequest.php
  src/Internal/Payment/State/AbstractPaymentState.php
  src/Internal/Payment/State/InitialState.php
  src/Internal/Payment/State/PaymentErrorState.php
  src/Internal/Payment/State/SystemErrorState.php
  src/Internal/Service/OrderService.php
  src/Internal/Service/PaymentProcessingService.php
  src/Internal/Service/PaymentRequestService.php
  tests/unit/src/Internal/Payment/PaymentContextTest.php
  tests/unit/src/Internal/Payment/PaymentRequestTest.php
  tests/unit/src/Internal/Payment/State/AbstractPaymentStateTest.php
  tests/unit/src/Internal/Payment/State/InitialStateTest.php
  tests/unit/src/Internal/Service/OrderServiceTest.php
  tests/unit/src/Internal/Service/PaymentProcessingServiceTest.php
  tests/unit/src/Internal/Service/PaymentRequestServiceTest.php
Labels: pr: ready to merge

#7404 Update JCB request capability docs link and capitalize it on the transaction details page
  changelog/fix-finish-setup-link
  client/payment-details/payment-method/card/index.js
  client/payment-methods/capability-request/capability-request-map.ts
Labels: pr: ready to merge

#7406 Enhance design of bnpl payment methods status in settings screen
  changelog/update-6914-enhance-design-of-bnpl-payment-methods-status
  client/components/loadable-checkbox/index.js
  client/components/payment-methods-list/payment-method.scss
  client/components/payment-methods-list/payment-method.tsx
  client/components/payment-methods-list/style.scss
Labels: pr: ready to merge

#7410 Point Klarna documentation to correct url from 'Contact WooCommerce Support' badge
  changelog/fix-correct-documentation-url-for-klarna
  client/components/payment-method-disabled-tooltip/index.tsx
Labels: pr: needs review

#7402 Disputes: Use existing tracks events where possible
  changelog/fix-7395
  client/payment-details/dispute-details/dispute-awaiting-response-details.tsx
  client/payment-details/dispute-details/dispute-resolution-footer.tsx
  client/tracks/index.js
Labels: pr: ready to merge

#7066 Add Reporting Authorization API endpoint
  changelog/add-6342-reports-authorisations-api
  includes/class-wc-payments.php
  includes/core/server/request/class-list-transactions.php
  includes/core/server/request/class-request-utils.php
  includes/reports/class-wc-rest-payments-reports-authorizations-controller.php
  tests/unit/bootstrap.php
  tests/unit/reports/test-class-wc-rest-payments-reports-authorizations-controller.php
  tests/unit/reports/test-class-wc-rest-payments-reports-transactions-controller.php
Labels: pr: needs author reply

#7443 Expose `is_account_partially_onboarded` to be used in WC Core
  changelog/fix-7119-setup-woopayments-task-completion
  includes/class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge

#7460 Remove 'dispute' from possible value of ParentSegment in `details-link`.
  changelog/remove-7363-parentsegment-dispute
  client/components/details-link/index.tsx
  client/components/details-link/test/__snapshots__/index.test.tsx.snap
  client/components/details-link/test/index.test.tsx
Labels: pr: ready to merge

#7456 Rename dispute action from `acceptTransactionDetailsDispute()` to `acceptDispute()`
  changelog/remove-7363-legacy-dispute-details
  changelog/remove-7363-unused-dispute-details-code
  client/data/disputes/actions.js
  client/data/disputes/hooks.ts
  client/data/disputes/test/actions.js
  client/disputes/details/actions.tsx
  client/disputes/details/index.tsx
  client/disputes/details/test/__snapshots__/actions.tsx.snap
  client/disputes/details/test/__snapshots__/index.tsx.snap
  client/disputes/details/test/actions.tsx
  client/disputes/details/test/index.tsx
  client/disputes/style.scss
Labels: pr: ready to merge

#7452 Temporarily use WC 7.7 in the E2E tests wcpay-subscriptions tests matrix
  .github/workflows/e2e-test.yml
  changelog/fix-e2e-tests
Labels: pr: ready to merge

#7444 Added coding standard for ordering of methods
  changelog/add-7427-method-ordering
  composer.json
  composer.lock
  phpcs.xml.dist
  src/Internal/Payment/PaymentContext.php
  src/Internal/Payment/State/AbstractPaymentState.php
Labels: pr: needs author reply

#7467 Skip two E2E tests related to Order Status change
  changelog/fix-e2e-tests-wc-8-2
  tests/e2e/specs/wcpay/merchant/merchant-orders-status-change.spec.js
Labels: pr: ready to merge

#7448 Update dispute challenge/accept e2e tests to match changes to transaction details and order edit screens
  changelog/fix-7377-dispute-e2e-tests
  client/payment-details/dispute-details/dispute-awaiting-response-details.tsx
  tests/e2e/specs/wcpay/merchant/merchant-disputes-save-draft-challenge.spec.js
  tests/e2e/specs/wcpay/merchant/merchant-disputes-submit-losing.spec.js
  tests/e2e/specs/wcpay/merchant/merchant-disputes-submit-winning.spec.js
  tests/e2e/utils/flows.js
Labels: pr: ready to merge

#7454 Fix Multi-Currency formatting on My Account > Orders page
  changelog/fix-7409-fix-formatting-my-account-orders
  includes/multi-currency/FrontendCurrencies.php
  tests/unit/multi-currency/test-class-frontend-currencies.php
Labels: pr: ready to merge

#7334 Unskip merchant e2e tests
  changelog/dev-7252-unskip-merchant-e2e-tests
  client/settings/advanced-settings/multi-currency-toggle.js
  tests/e2e/specs/wcpay/merchant/merchant-orders-manual-capture.spec.js
  tests/e2e/specs/wcpay/merchant/merchant-orders-partial-refund.spec.js
  tests/e2e/specs/wcpay/merchant/merchant-orders-refund-failures.spec.js
  tests/e2e/utils/flows.js
Labels: pr: ready to merge

#7486 Skip merchant dispute e2e tests failing on WC 7.7
  changelog/fix-skip-merchant-dispute-e2e-tests-failing-respond-now-not-found
  tests/e2e/specs/wcpay/merchant/merchant-disputes-save-draft-challenge.spec.js
  tests/e2e/specs/wcpay/merchant/merchant-disputes-submit-losing.spec.js
  tests/e2e/specs/wcpay/merchant/merchant-disputes-submit-winning.spec.js
Labels: pr: ready to merge, component: disputes, component: tests, category: e2e

#7462 Adding Internal Logger
  changelog/add-7428-internal-logger
  includes/class-logger.php
  src/Internal/DependencyManagement/ServiceProvider/GenericServiceProvider.php
  src/Internal/Logger.php
  tests/unit/src/Internal/LoggerTest.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: needs author reply

#7484 Fix Documents page loading on WooCommerce 8.2.0
  changelog/fix-7461-documents-page-api-settings
  includes/admin/class-wc-payments-admin.php
Labels: pr: needs review

#7480 Deprecate Sofort
  assets/images/payment-methods/all_local_payments.svg
  assets/images/payment-methods/local_payments.svg
  changelog/dev-sofort-deprecation
  client/components/payment-methods-list/payment-method.scss
  client/components/payment-methods-list/payment-method.tsx
  client/connect-account-page/payment-methods.tsx
  client/connect-account-page/strings.tsx
  client/connect-account-page/test/__snapshots__/index.test.tsx.snap
  client/payment-methods/delete-modal.tsx
  client/payment-methods/test/__snapshots__/delete-modal.test.js.snap
  includes/admin/class-wc-rest-payments-settings-controller.php
Labels: pr: ready to merge

#7518 Add IE, DK, FI, NO, and SE to Klarna
  changelog/add-additional-countries-for-klarna
  client/payment-methods-map.tsx
  includes/payment-methods/class-klarna-payment-method.php
Labels: pr: ready to merge

#7471 Add AuthorizationRequired State
  changelog/rpp-7414-authentication-required-state
  includes/class-wc-payment-gateway-wcpay.php
  src/Internal/DependencyManagement/ServiceProvider/PaymentsServiceProvider.php
  src/Internal/Payment/PaymentContext.php
  src/Internal/Payment/State/AbstractPaymentState.php
  src/Internal/Payment/State/AuthenticationRequiredState.php
  src/Internal/Payment/State/InitialState.php
  src/Internal/Payment/State/ProcessedState.php
  src/Internal/Service/PaymentProcessingService.php
  tests/unit/src/Internal/Payment/PaymentContextTest.php
  tests/unit/src/Internal/Payment/State/AbstractPaymentStateTest.php
  tests/unit/src/Internal/Payment/State/InitialStateTest.php
  tests/unit/src/Internal/Payment/State/ProcessedStateTest.php
  tests/unit/src/Internal/Service/PaymentProcessingServiceTest.php
Labels: pr: ready to merge

#7527 Fix - HPOS compatibility on Edit Order Screen
  changelog/7466-fix-hpos-compat-order-edit
  client/order/index.js
  tests/e2e/specs/wcpay/merchant/merchant-orders-status-change.spec.js
Labels: pr: ready to merge

#7493 Fix dispute e2e tests for WC 7.7
  changelog/fix-7487-dispute-e2e-tests-failing-wc-77
  tests/e2e/specs/wcpay/merchant/merchant-disputes-save-draft-challenge.spec.js
  tests/e2e/specs/wcpay/merchant/merchant-disputes-submit-losing.spec.js
  tests/e2e/specs/wcpay/merchant/merchant-disputes-submit-winning.spec.js
Labels: pr: ready to merge

#7476 Show a loading UI when accepting a dispute is in progress
  changelog/fix-7473-accept-dispute-loading-state-ui
  client/payment-details/dispute-details/dispute-awaiting-response-details.tsx
  client/payment-details/dispute-details/style.scss
Labels: pr: ready to merge

#7515 Fixed tooltip in mobile settings view
  changelog/fix-6950-fix-imp-mobile-tooltip
  client/components/tooltip/style.scss
  client/components/tooltip/tooltip-base.tsx
Labels: pr: ready to merge

#7552 Fix PO Notice not appearing when adding APMs
  changelog/dev-fix-po-notice-not-appearing
  client/components/payment-methods-list/payment-method.tsx
Labels: pr: ready to merge

#7541 Fix Afterpay checkout error when shipping information is missing
  changelog/fix-7509-afterpay-checkout-fails-when-shipping-information-is-missing
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-order-service.php
  includes/exceptions/class-invalid-address-exception.php
  includes/payment-methods/class-upe-split-payment-gateway.php
Labels: pr: ready to merge

#7320 Added documentation for report API
  changelog/add-6363-add-documentation-for-reporting-api
  docs/rest-api/source/includes/wp-api-v3/reports.md
  docs/rest-api/source/index.html.md
Labels: pr: ready to merge

#7450 RPP - Connect the duplicate payment prevention service (Verification)
  changelog/rpp-7411-duplicate-prevention
  includes/admin/class-wc-rest-payments-orders-controller.php
  includes/class-duplicate-payment-prevention-service.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments.php
  includes/constants/class-intent-status.php
  includes/wc-payment-api/models/class-wc-payments-api-abstract-intention.php
  src/Internal/DependencyManagement/ServiceProvider/GenericServiceProvider.php
  src/Internal/DependencyManagement/ServiceProvider/PaymentsServiceProvider.php
  src/Internal/Payment/PaymentContext.php
  src/Internal/Payment/State/DuplicateOrderDetectedState.php
  src/Internal/Payment/State/InitialState.php
  src/Internal/Payment/State/ProcessedState.php
  src/Internal/Service/DuplicatePaymentPreventionService.php
  src/Internal/Service/OrderService.php
  src/Internal/Service/PaymentProcessingService.php
  src/Internal/Service/SessionService.php
  tests/unit/src/Internal/Payment/PaymentContextTest.php
  tests/unit/src/Internal/Payment/State/InitialStateTest.php
  tests/unit/src/Internal/Payment/State/ProcessedStateTest.php
  tests/unit/src/Internal/Service/DuplicatePaymentPreventionServiceTest.php
  tests/unit/src/Internal/Service/OrderServiceTest.php
  tests/unit/src/Internal/Service/SessionServiceTest.php
  tests/unit/test-class-duplicate-payment-prevention-service.php
Labels: pr: ready to merge

#7546 Use template type for StateFactory methods to assist IDEs better.
  changelog/rpp-add-template-type-create_state
  src/Internal/Payment/State/AbstractPaymentState.php
  src/Internal/Payment/State/StateFactory.php
Labels: pr: ready to merge

#7520 Activate fraud services before WPCOM/Jetpack connection and account onboarding
  changelog/add-7517-activate-fraud-services-pre-wpcom-connection-and-account-creation
  client/onboarding/index.tsx
  includes/admin/class-wc-payments-admin.php
  includes/class-database-cache.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-checkout.php
  includes/class-wc-payments-customer-service.php
  includes/class-wc-payments-fraud-service.php
  includes/class-wc-payments-session-service.php
  includes/class-wc-payments-upe-checkout.php
  includes/class-wc-payments-utils.php
  includes/class-wc-payments.php
  includes/core/server/class-request.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/payment-methods/class-upe-split-payment-gateway.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/admin/test-class-wc-payments-admin.php
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
  tests/unit/admin/test-class-wc-rest-payments-tos-controller.php
  tests/unit/admin/test-class-wc-rest-upe-flag-toggle-controller.php
  tests/unit/core/service/test-class-wc-payments-customer-service-api.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
  tests/unit/payment-methods/test-class-upe-split-payment-gateway.php
  tests/unit/test-class-wc-payment-gateway-wcpay-payment-types.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-refund.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-payment-method-order-note.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-customer-service.php
  tests/unit/test-class-wc-payments-express-checkout-button-display-handler.php
  tests/unit/test-class-wc-payments-fraud-service.php
  tests/unit/test-class-wc-payments-payment-request-button-handler.php
  tests/unit/test-class-wc-payments-session-service.php
  tests/unit/test-class-wc-payments-woopay-button-handler.php
Labels: pr: needs review

#7569 Capital loans page broken on WooCommerce 8.2
  changelog/fix-7531-captial-loans
  client/capital/index.tsx
  client/transactions/declarations.d.ts
Labels: pr: ready to merge

#7547 RPP - Add phone number check
  changelog/rpp-7412-validate-phone-number
  src/Internal/Payment/PaymentContext.php
  src/Internal/Payment/State/InitialState.php
  src/Internal/Service/OrderService.php
  tests/unit/src/Internal/Payment/State/InitialStateTest.php
  tests/unit/src/Internal/Service/OrderServiceTest.php
Labels: pr: ready to merge

#7560 Unify payment method icon design
  assets/css/admin.css
  assets/images/cards/amex.svg
  assets/images/cards/apple-pay.svg
  assets/images/cards/diners.svg
  assets/images/cards/discover.svg
  assets/images/cards/google-pay.svg
  assets/images/cards/jcb.svg
  assets/images/cards/mastercard.svg
  assets/images/cards/unionpay.svg
  assets/images/cards/visa.svg
  assets/images/payment-methods/affirm.svg
  assets/images/payment-methods/afterpay.svg
  assets/images/payment-methods/bancontact.svg
  assets/images/payment-methods/bank-debit.svg
  assets/images/payment-methods/cc.svg
  assets/images/payment-methods/eps.svg
  assets/images/payment-methods/giropay.svg
  assets/images/payment-methods/ideal.svg
  assets/images/payment-methods/jcb.svg
  assets/images/payment-methods/klarna.svg
  assets/images/payment-methods/link.svg
  assets/images/payment-methods/p24.svg
  assets/images/payment-methods/sepa-debit.svg
  assets/images/payment-methods/sofort.svg
  assets/images/payment-methods/woopay.svg
  changelog/fix-7183-unify-pm-icon-design
  client/components/payment-methods-list/payment-method.scss
  client/connect-account-page/payment-methods.tsx
  client/connect-account-page/style.scss
  client/connect-account-page/test/__snapshots__/index.test.tsx.snap
  client/multi-currency/multi-currency-settings/enabled-currencies-list/test/__snapshots__/index.js.snap
  client/payment-methods-icons.tsx
  client/payment-methods-map.tsx
  client/payment-methods/test/__snapshots__/activation-modal.test.js.snap
  client/payment-methods/test/__snapshots__/delete-modal.test.js.snap
  client/settings/express-checkout-settings/index.js
  client/settings/express-checkout-settings/index.scss
  client/settings/express-checkout/apple-google-pay-item.tsx
  client/settings/express-checkout/link-item.tsx
  client/settings/express-checkout/style.scss
  client/settings/express-checkout/woopay-item.tsx
  client/settings/payment-method-icon/index.js
  client/settings/payment-method-icon/style.scss
  client/style.scss
Labels: pr: needs review

#7511 Update Checkout appearance section to display WooPay checkout preview UI
  changelog/update-6995-woopay-checkout-appearance-preview-ui
  client/settings/express-checkout-settings/assets/icons/lock-keyhole/index.js
  client/settings/express-checkout-settings/file-upload.tsx
  client/settings/express-checkout-settings/index.scss
  client/settings/express-checkout-settings/woopay-preview.js
  client/settings/express-checkout-settings/woopay-settings.js
  client/settings/index.js
Labels: priority: high, category: projects, component: WooPay, needs demo

#7571 refactor: hooks and selector dependencies
  changelog/fix-settings-selectors-refactor
  client/components/payment-methods-checkboxes/payment-method-checkbox.tsx
  client/data/settings/hooks.js
  client/data/settings/test/hooks.js
  client/overview/index.js
  client/overview/test/index.js
  client/settings/express-checkout-settings/test/index.js
  client/settings/save-settings-section/index.js
  client/settings/save-settings-section/test/index.test.js
  client/transactions/test/index.tsx
Labels: pr: ready to merge

#7513 Logging the changes to the PaymentContext
  changelog/add-7429-log-context-changes
  src/Internal/DependencyManagement/ServiceProvider/PaymentsServiceProvider.php
  src/Internal/Payment/Change.php
  src/Internal/Payment/PaymentContext.php
  src/Internal/Payment/State/StateFactory.php
  src/Internal/Payment/Transition.php
  src/Internal/Service/PaymentContextLoggerService.php
  src/Internal/Service/PaymentProcessingService.php
  tests/unit/src/Internal/Payment/ChangeTest.php
  tests/unit/src/Internal/Payment/PaymentContextTest.php
  tests/unit/src/Internal/Service/PaymentContextLoggerServiceTest.php
  tests/unit/src/Internal/Service/PaymentProcessingServiceTest.php
Labels: pr: ready to merge

#7211 Disable activation of LPM's requiring additional currencies when MC is disabled
  changelog/fix-7154-onboarding-lpms-while-mc-is-disabled
  client/additional-methods-setup/upe-preview-methods-selector/add-payment-methods-task.js
  client/additional-methods-setup/upe-preview-methods-selector/test/add-payment-methods-task.test.js
  client/components/currency-information-for-methods/index.js
  client/components/currency-information-for-methods/test/index.test.js
  client/components/payment-methods-checkboxes/payment-method-checkbox.tsx
  client/payment-methods/index.js
  client/payment-methods/test/index.js
Labels: pr: needs review

#7557 refactor disputed order notice to separate side effects & add a `_view` tracks event
  changelog/fix-7437-refactor-order-dispute-side-effects
  client/components/disputed-order-notice/index.js
  client/components/disputed-order-notice/style.scss
  client/order/index.js
  client/tracks/index.js
Labels: pr: needs review
