Repository Automattic/woocommerce-payments, pull requests merged in 2023-09, with the labels that each got.

#7100 RPP - Load payment methods through the request class
  changelog/rpp-6685-load-payment-methods
  src/Internal/Payment/PaymentRequest.php
  src/Internal/Payment/PaymentRequestException.php
  tests/unit/src/Internal/Payment/PaymentRequestTest.php
Labels: pr: ready to merge

#7035 RPP: Factor flags
  changelog/rpp-6679-factor-flags
  includes/class-database-cache.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-payment-request-button-handler.php
  includes/class-wc-payments.php
  includes/core/server/class-request.php
  includes/core/server/request/class-get-payment-process-factors.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  src/Internal/DependencyManagement/ServiceProvider/PaymentsServiceProvider.php
  src/Internal/Payment/Factor.php
  src/Internal/Payment/Router.php
  tests/unit/bootstrap.php
  tests/unit/src/ContainerTest.php
  tests/unit/src/Internal/Payment/FactorTest.php
  tests/unit/src/Internal/Payment/RouterTest.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge

#7099 Allow requests to be extended by multiple classes in parallel
  changelog/fix-7061-extended-requests
  includes/core/server/class-request.php
  tests/unit/core/server/request/test-class-core-request.php
Labels: pr: ready to merge

#7116 Check if account service is defined before checking if Stripe account is valid
  changelog/fix-7109-fatal-on-wc-home-task
  includes/class-wc-payments-tasks.php
Labels: pr: ready to merge

#7126 Update Transaction Details → HorizontalList label styles to uppercase
  changelog/update-horizontal-list-label-style-uppercase
  client/components/horizontal-list/style.scss
Labels: pr: ready to merge

#7092 Refactor Woo Subscriptions compatibility to fix currency being able to be updated during renewals, resubscribes, or switches
  changelog/fix-5507-block-currency-update-on-sub-switch
  includes/multi-currency/Compatibility/WooCommerceSubscriptions.php
  tests/unit/helpers/class-wc-helper-subscription.php
  tests/unit/multi-currency/compatibility/test-class-woocommerce-subscriptions.php
Labels: pr: needs review

#7142 Revert bumping minimum required version of WC 8.0.0 and WP 6.1
  .github/workflows/compatibility.yml
  .github/workflows/e2e-test.yml
  .github/workflows/php-lint-test.yml
  changelog/hotfix-revert-460-wp-wc-min-supported-version-bump
  changelog/hotfix-revert-460-wp-wc-min-supported-version-bump-2
  phpcs-compat.xml.dist
  phpcs.xml.dist
  readme.txt
  woocommerce-payments.php
Labels: pr: ready to merge

#7138 Remove unused import `NoticeOutlineIcon` to fix JS linter warning
  changelog/fix-remove-unused-import-noticeoutlineicon
  client/components/deposits-overview/next-deposit.tsx
Labels: pr: ready to merge, type: task, priority: low

#7139 Add Transaction Details notice when a dispute has staged evidence
  changelog/add-6966-transaction-details-dispute-challenge-in-progress-notice
  client/payment-details/dispute-details/index.tsx
  client/payment-details/dispute-details/style.scss
  client/payment-details/dispute-details/test/index.test.tsx
  client/types/disputes.d.ts
Labels: pr: ready to merge

#7111 Add cli npm command
  bin/cli.sh
  changelog/dev-add-cli-command
  package.json
Labels: pr: ready to merge

#7141 Fix multicurrency widget error on post/page edit screen
  changelog/fix-7135-currency-switch-widget-on-edit-post
  client/data/multi-currency/hooks.js
Labels: pr: ready to merge

#7144 Add component test for Transaction Details → Dispute Details
  changelog/dev-add-dispute-summary-row-tests
  client/payment-details/dispute-details/test/index.test.tsx
Labels: pr: ready to merge, type: task, category: projects

#7077 Add Horizontal list of dispute details to the transaction page
  changelog/add-6924-dispute-details-attributes
  changelog/dev-add-dispute-summary-row-tests
  client/payment-details/dispute-details/dispute-summary-row.tsx
  client/payment-details/dispute-details/index.tsx
  client/payment-details/dispute-details/style.scss
  client/payment-details/dispute-details/test/index.test.tsx
Labels: pr: ready to merge

#7155 Avoid redirects on docs links
  README.md
  changelog/fix-docs-links-part-2
  client/additional-methods-setup/upe-preview-methods-selector/add-payment-methods-task.js
  client/checkout/blocks/fields.js
  client/components/account-balances/strings.ts
  client/components/account-balances/test/index.test.tsx
  client/components/deposits-overview/next-deposit.tsx
  client/components/deposits-overview/suspended-deposit-notice.tsx
  client/components/deposits-overview/test/__snapshots__/index.tsx.snap
  client/components/deposits-overview/test/index.tsx
  client/components/deposits-status/index.tsx
  client/components/deposits-status/test/__snapshots__/index.js.snap
  client/connect-account-page/modal/index.js
  client/connect-account-page/modal/test/__snapshots__/index.js.snap
  client/deposits/instant-deposits/modal.tsx
  client/deposits/instant-deposits/test/__snapshots__/index.tsx.snap
  client/order/cancel-confirm-modal/index.js
  client/payment-details/summary/index.tsx
  client/payment-details/summary/test/__snapshots__/index.tsx.snap
  client/payment-gateways/disable-confirmation-modal.js
  client/payment-methods/index.js
  client/settings/advanced-settings/multi-currency-toggle.js
  client/settings/advanced-settings/wcpay-subscriptions-toggle.js
  client/settings/deposits/index.js
  client/settings/disable-upe-modal/index.js
  client/settings/express-checkout/link-item.tsx
  client/settings/fraud-protection/advanced-settings/cards/cvc-verification.tsx
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/cvc-verification.test.tsx.snap
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/index.test.tsx.snap
  client/settings/general-settings/index.js
  client/settings/settings-manager/index.js
  client/utils/account-fees.tsx
  client/utils/test/__snapshots__/account-fees.tsx.snap
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-apple-pay-registration.php
  includes/class-wc-payments-checkout.php
  includes/class-wc-payments-upe-checkout.php
  includes/class-wc-payments-utils.php
  includes/core/CONTRIBUTING.md
  includes/core/class-mode.php
  includes/fraud-prevention/class-order-fraud-and-risk-meta-box.php
  includes/notes/class-wc-payments-notes-additional-payment-methods.php
  includes/notes/class-wc-payments-notes-instant-deposits-eligible.php
  includes/notes/class-wc-payments-notes-set-up-refund-policy.php
  includes/notes/class-wc-payments-notes-set-up-stripelink.php
  includes/subscriptions/templates/html-subscriptions-plugin-notice.php
  includes/subscriptions/templates/html-wcpay-deactivate-warning.php
  readme.txt
  tests/unit/fraud-prevention/test-class-order-fraud-and-risk-meta-box.php
  tests/unit/notes/test-class-wc-payments-notes-additional-payment-methods.php
  tests/unit/notes/test-class-wc-payments-notes-set-up-stripelink.php
  tests/unit/payment-methods/test-class-upe-split-payment-gateway.php
  woocommerce-payments.php
Labels: pr: ready to merge

#7136 Updates to the Inbox Note logic.
  changelog/dev-6441-inbox-notifications-update
  includes/class-wc-payments-account.php
  includes/notes/class-wc-payments-notes-additional-payment-methods.php
  includes/notes/class-wc-payments-notes-instant-deposits-eligible.php
  tests/unit/notes/test-class-wc-payments-notes-additional-payment-methods.php
Labels: pr: ready to merge

#7129 Add New Task to Enable Payment Methods
  changelog/dev-6779-po-new-task
  client/additional-methods-setup/upe-preview-methods-selector/add-payment-methods-task.js
  client/globals.d.ts
  client/index.js
  client/overview/index.js
  client/overview/task-list/strings.tsx
  client/overview/task-list/tasks.tsx
  client/overview/task-list/tasks/add-apms-task.tsx
  client/overview/task-list/tasks/po-task.tsx
  includes/admin/class-wc-payments-admin.php
Labels: pr: needs design review

#6902 Improvement: Query optimisation for get_all_customer_currencies method
  changelog/6852-get_all_customer_currencies_improvement
  includes/multi-currency/MultiCurrency.php
  tests/unit/multi-currency/test-class-multi-currency.php
Labels: pr: needs review

#7180 Avoid empty fields in new onboarding flow
  changelog/fix-6981-missing-onboarding-field-data
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: ready to merge

#7179 Extract minimum supported PHP version from plugin file for GH actions
  .github/actions/e2e/env-setup/action.yml
  .github/actions/setup-php/action.yml
  .github/actions/setup-repo/action.yml
  .github/workflows/check-changelog.yml
  .github/workflows/i18n-weekly-release.yml
  .github/workflows/php-compatibility.yml
  .github/workflows/php-lint-test.yml
  changelog/dev-update-workflows
Labels: pr: ready to merge

#7082 Warn about dev mode enabled on new onboarding flow choice
  changelog/add-6429-warn-about-dev-mode-on-new-onboarding
  client/globals.d.ts
  client/onboarding/steps/mode-choice.tsx
  client/onboarding/steps/personal-details.tsx
  client/onboarding/steps/test/mode-choice.tsx
  client/onboarding/strings.tsx
  client/onboarding/style.scss
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-account.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: ready to merge

#5903 Add the WooPay Express button to the Pay for order page
  changelog/add-pay-for-order
  client/checkout/woopay/email-input-iframe.js
  client/checkout/woopay/express-button/express-checkout-iframe.js
  client/checkout/woopay/utils.js
  includes/class-wc-payments-express-checkout-button-display-handler.php
  includes/class-wc-payments-woopay-button-handler.php
Labels: needs design

#7188 Follow up of Warn about dev mode
  changelog/fix-6429-follow-up-fix
  client/onboarding/steps/mode-choice.tsx
Labels: pr: ready to merge

#7189 Update the links used in the migrate option and automatically notice
  changelog/update-stripe-billing-notice-links
  client/settings/advanced-settings/stripe-billing-notices/migrate-automatically-notice.tsx
  client/settings/advanced-settings/stripe-billing-notices/migrate-option-notice.tsx
Labels: pr: ready to merge

#7194 Revert "Update Subscriptions with WooPayments eligibility as we move to deprecate this functionality"
  changelog/issue-6510-deprecate-wcpay-subscriptions
  client/settings/advanced-settings/wcpay-subscriptions-toggle.js
  includes/class-wc-payments-features.php
  includes/subscriptions/class-wc-payments-subscriptions.php
Labels: pr: ready to merge

#7137 Change ConvertedAmount component to use an updated Tooltip
  changelog/update-6991-table-tooltip
  client/transactions/list/converted-amount.tsx
  client/transactions/list/style.scss
  client/transactions/list/test/__snapshots__/converted-amount.tsx.snap
  client/transactions/list/test/__snapshots__/index.tsx.snap
Labels: pr: ready to merge

#7197 Increase admin enqueue scripts priority
  changelog/fix-7067-admin-enqueue-scripts-priority
  includes/admin/class-wc-payments-admin.php
Labels: pr: ready to merge

#7208 Fix single currency settings saving manual rate
  changelog/fix-6857-multi-currency-manual-exchange-rate-is-not-saved
  client/multi-currency/single-currency-settings/index.js
  includes/multi-currency/MultiCurrency.php
Labels: pr: ready to merge

#7214 Fix checkout error with Afterpay
  changelog/hotfix-7187-checkout-error-with-afterpay
  includes/class-wc-payment-gateway-wcpay.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/payment-methods/class-upe-split-payment-gateway.php
Labels: pr: ready to merge

#7195 Fix changing Stripe Billing payment method which wasn't cancelling at Stripe
  changelog/fix-changing-stripe-billing-payment-method-doesnt-cancel
  includes/subscriptions/class-wc-payments-subscription-service.php
  tests/unit/subscriptions/test-class-wc-payments-subscription-service.php
Labels: pr: ready to merge

#7190 Adds environment metadata to Stripe Billing subscription and invoice payment intents
  changelog/fix-6529-add-stripe-billing-context
  changelog/fix-6529-add-stripe-billing-context-2
  changelog/fix-payment-intent-meta-for-recurring-transactions
  includes/class-wc-payment-gateway-wcpay.php
  includes/subscriptions/class-wc-payments-invoice-service.php
  includes/subscriptions/class-wc-payments-subscription-service.php
  includes/subscriptions/class-wc-payments-subscriptions-event-handler.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/subscriptions/test-class-wc-payments-subscription-service.php
Labels: pr: ready to merge

#7176 Use fallback methods for updating the next payment date after migrating a stripe billing subscription
  changelog/update-subscription-next-payment-on-migrate
  includes/subscriptions/class-wc-payments-subscriptions-migrator.php
Labels: pr: ready to merge

#7192 Allow merchants to see dispute evidence
  changelog/add-7173-dispute-evidence
  client/data/files/action-types.ts
  client/data/files/actions.ts
  client/data/files/hooks.ts
  client/data/files/index.ts
  client/data/files/reducer.ts
  client/data/files/resolvers.ts
  client/data/files/selectors.ts
  client/data/files/types.d.ts
  client/data/index.ts
  client/data/store.js
  client/data/types.d.ts
  client/payment-details/dispute-details/evidence-list.tsx
  client/payment-details/dispute-details/index.tsx
  client/payment-details/dispute-details/style.scss
  client/payment-details/dispute-details/test/index.test.tsx
  client/types/disputes.d.ts
  includes/admin/class-wc-rest-payments-files-controller.php
Labels: pr: ready to merge

#7218 Improve the logging in the Stripe Billing migration of token data
  changelog/fix-migrate-subscription-tokens
  includes/subscriptions/class-wc-payments-subscriptions-migrator.php
Labels: pr: needs review

#7217 Transaction Details → fix typo in staged dispute challenge notice
  changelog/fix-dispute-staged-evidence-notice-typo
  client/payment-details/dispute-details/index.tsx
  client/payment-details/dispute-details/test/index.test.tsx
Labels: pr: ready to merge, component: disputes, component: transaction details, category: projects

#7201 Fix double indicators showing under Payments tab
  changelog/fix-7042-double-payments-badge
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-incentives-service.php
Labels: pr: ready to merge

#7152 Disable automatic currency switching and switcher widgets on pay_for_order page
  changelog/fix-5031-disable-currency-switcher-on-pay-for-order
  includes/multi-currency/Compatibility.php
  includes/multi-currency/Compatibility/WooCommerceSubscriptions.php
  includes/multi-currency/CurrencySwitcherBlock.php
  includes/multi-currency/CurrencySwitcherWidget.php
  includes/multi-currency/MultiCurrency.php
  tests/unit/multi-currency/compatibility/test-class-woocommerce-subscriptions.php
  tests/unit/multi-currency/test-class-compatibility.php
  tests/unit/multi-currency/test-class-currency-switcher-block.php
  tests/unit/multi-currency/test-class-currency-switcher-widget.php
  tests/unit/multi-currency/test-class-multi-currency.php
Labels: pr: needs review

#7047 Add Transaction Details dispute footer for disputes not awaiting a response
  changelog/add-6927-dispute-details-not-awaiting-response
  client/disputes/utils.ts
  client/payment-details/dispute-details/dispute-awaiting-response-details.tsx
  client/payment-details/dispute-details/dispute-resolution-footer.tsx
  client/payment-details/dispute-details/style.scss
  client/payment-details/dispute-details/test/index.test.tsx
  client/payment-details/summary/index.tsx
  client/payment-details/summary/test/__snapshots__/index.tsx.snap
  client/payment-details/summary/test/index.tsx
  client/tracks/index.js
  client/types/balance-transactions.d.ts
  client/types/disputes.d.ts
Labels: pr: ready to merge

#7181 Fix modal header alignment on safari
  changelog/fix-5548-modal-header-alignement-on-safari
  client/components/confirmation-modal/styles.scss
Labels: pr: ready to merge

#7093 Add Dispute Challenge and Accept buttons to Transaction Details
  changelog/fix-6926-transaction-dispute-details-actions
  client/data/disputes/actions.js
  client/data/disputes/hooks.ts
  client/payment-details/dispute-details/dispute-awaiting-response-details.tsx
  client/payment-details/dispute-details/style.scss
  client/payment-details/summary/test/__snapshots__/index.test.tsx.snap
  client/payment-details/summary/test/index.test.tsx
  client/tracks/index.js
  client/types/disputes.d.ts
Labels: pr: ready to merge

#7236 Expand WooPayments SSR entries to cover real HEs needs
  changelog/add-7122-more-details-to-woo-ssr
  includes/class-wc-payments-status.php
  includes/class-wc-payments.php
Labels: pr: ready to merge

#7118 Update Transaction Details breakdown: rename labels and add fee breakdown tooltip when disputed
  changelog/update-6974-transaction-details-breakdown-labels-and-fees
  client/components/tooltip/index.tsx
  client/disputes/utils.ts
  client/payment-details/dispute-details/dispute-awaiting-response-details.tsx
  client/payment-details/dispute-details/dispute-resolution-footer.tsx
  client/payment-details/order-details/test/__snapshots__/index.test.tsx.snap
  client/payment-details/summary/index.tsx
  client/payment-details/summary/style.scss
  client/payment-details/summary/test/__snapshots__/index.test.tsx.snap
  client/payment-details/summary/test/index.test.tsx
  client/payment-details/test/__snapshots__/index.test.tsx.snap
  client/types/disputes.d.ts
Labels: pr: ready to merge

#7234 Increase GBP transaction limit for Afterpay
  changelog/update-7222-bnpl-increase-afterpayclearpay-uk-transaction-upper-limit-to-1200-gbp
  includes/payment-methods/class-afterpay-payment-method.php
Labels: pr: ready to merge

#7231 Show dispute details on the transaction details screen when a dispute is awaiting response and past due
  changelog/fix-7228-dispute-details-when-awaiting-response-past-due
  client/payment-details/dispute-details/dispute-awaiting-response-details.tsx
  client/payment-details/dispute-details/dispute-summary-row.tsx
Labels: pr: ready to merge

#7206 Add dispute steps to resolve to the transaction details page.
  changelog/add-6925-steps-to-resolve
  client/components/tooltip/style.scss
  client/globals.d.ts
  client/payment-details/dispute-details/dispute-awaiting-response-details.tsx
  client/payment-details/dispute-details/dispute-steps.tsx
  client/payment-details/dispute-details/style.scss
  client/payment-details/summary/index.tsx
  client/payment-details/summary/test/__snapshots__/index.test.tsx.snap
  client/payment-details/summary/test/index.test.tsx
  includes/admin/class-wc-payments-admin.php
Labels: pr: ready to merge

#7242 Transaction Details → Show resolution status footer for inquiries
  changelog/fix-7191-dispute-resolution-footer-inquiries
  client/disputes/utils.ts
  client/payment-details/dispute-details/dispute-resolution-footer.tsx
  client/payment-details/summary/test/index.test.tsx
Labels: pr: ready to merge

#7277 Add correct inquiry docs link to active dispute/inquiry notice in transactions screen
  changelog/fix-7241-update-live-dispute-docs-links-in-transaction-detail
  client/payment-details/dispute-details/dispute-awaiting-response-details.tsx
  client/payment-details/dispute-details/dispute-notice.tsx
Labels: pr: ready to merge

#7293 Add different PO congrats message when account is not complete
  changelog/update-6569-customize-success-banner-message-account-status
  client/overview/connection-sucess-notice.tsx
Labels: pr: ready to merge

#7287 Transaction Details → Dispute Details – show dispute amount in store/dispute currency
  changelog/update-7124-transaction-details-dispute-amount-currency
  client/disputes/utils.ts
  client/payment-details/dispute-details/dispute-summary-row.tsx
  client/payment-details/summary/test/index.test.tsx
Labels: pr: ready to merge

#6408 Remove the redundant network requests in `capture_charge`
  changelog/fix-optimise-capture-charge-calls
  includes/admin/class-wc-rest-payments-orders-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/core/server/request/class-capture-intention.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge

#7250 Fix Apple Pay and Google Pay if card payments are disabled
  changelog/fix-5945-add-default-cc-enabled
  includes/core/server/request/class-create-and-confirm-intention.php
  includes/payment-methods/class-upe-payment-gateway.php
Labels: pr: ready to merge

#7153 Fix invalid value error for paymentMethodMessaging in product details page
  changelog/fix-6819-payment-method-messaging-invalid-value
  client/product-details/index.js
Labels: pr: needs review

#7079 Added docs for cancel_authorization endpoint.
  changelog/add-documentation-for-cancel-authorization-endpoint
  docs/rest-api/source/includes/wp-api-v3/order.md
Labels: pr: ready to merge

#7316 RPP: Container Exceptions
  changelog/rpp-container-exceptions
  src/Container.php
  src/Internal/DependencyManagement/ContainerException.php
  src/Internal/DependencyManagement/DelegateContainer/LegacyContainer.php
  src/Internal/DependencyManagement/ExtendedContainer.php
  tests/WCPAY_UnitTestCase.php
  tests/unit/src/ContainerTest.php
  tests/unit/src/Internal/DependencyManagement/DelegateContainer/LegacyContainerTest.php
Labels: pr: needs review

#7143 Store the customer currencies data as an option
  changelog/update-7000-improve-analytics-call-performance
  includes/class-database-cache.php
  includes/multi-currency/Analytics.php
  includes/multi-currency/MultiCurrency.php
  tests/unit/multi-currency/test-class-analytics.php
  tests/unit/multi-currency/test-class-multi-currency.php
Labels: pr: ready to merge

#7199 Preload checkout data in WooPay
  changelog/add-2094-pass-checkout-data-before-auth
  client/checkout/woopay/express-button/express-checkout-iframe.js
  client/checkout/woopay/express-button/index.js
  client/checkout/woopay/express-button/test/woopay-express-checkout-button.test.js
  client/checkout/woopay/express-button/utils.js
  client/checkout/woopay/express-button/woopay-express-checkout-button.js
  includes/class-wc-payments-checkout.php
  includes/class-wc-payments-features.php
  includes/woopay/class-woopay-utilities.php
Labels: type: enhancement
