Repository Automattic/woocommerce-payments, pull requests merged in 2023-01, with the labels that each got.

#5331 Remove redundant compatibility util class and refs
  changelog/refactor-5291-check-redundant-compatibility-util-class
  includes/class-wc-payments-account.php
  includes/class-wc-payments.php
  includes/compat/class-wc-payment-woo-compat-utils.php
  includes/multi-currency/Notes/NoteMultiCurrencyAvailable.php
  includes/notes/class-wc-payments-notes-additional-payment-methods.php
  includes/notes/class-wc-payments-notes-instant-deposits-eligible.php
  includes/notes/class-wc-payments-notes-loan-approved.php
  includes/notes/class-wc-payments-notes-qualitative-feedback.php
  includes/notes/class-wc-payments-notes-set-https-for-checkout.php
  includes/notes/class-wc-payments-notes-set-up-refund-policy.php
  includes/notes/class-wc-payments-notes-set-up-stripelink.php
  includes/notes/class-wc-payments-remote-note-service.php
  tests/unit/test-class-wc-payments-account.php
Labels: pr: ready to merge

#5345 Refactor- Enum class for payment intent status constants
  changelog/refactor-5327-enum-class-for-payment-intent-status-constants
  includes/admin/class-wc-rest-payments-orders-controller.php
  includes/admin/class-wc-rest-payments-reader-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments.php
  includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php
  includes/constants/class-payment-intent-status.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/admin/test-class-wc-rest-payments-orders-controller.php
  tests/unit/admin/test-class-wc-rest-payments-readers-controller.php
  tests/unit/helpers/class-wc-helper-intention.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-refund.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-order-service.php
  tests/unit/test-class-wc-payments-webhook-processing-service.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: ready to merge

#5373 Fix loading correct script dependencies even re-registering them in the same request
  changelog/fix-5137-confilict-max-mega-menu
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-platform-checkout-button-handler.php
  includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php
  includes/multi-currency/Analytics.php
  includes/multi-currency/CurrencySwitcherBlock.php
  includes/multi-currency/MultiCurrency.php
  includes/platform-checkout-user/class-platform-checkout-save-user.php
  includes/subscriptions/class-wc-payments-subscriptions-empty-state-manager.php
  includes/subscriptions/class-wc-payments-subscriptions-onboarding-handler.php
Labels: pr: needs review

#5346 Add/check intent attached to order before payment
  changelog/add-check-intent-attached-to-order-before-payment
  client/checkout/api/index.js
  client/checkout/blocks/upe-fields.js
  client/checkout/classic/upe.js
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-order-success-page.php
  includes/payment-methods/class-upe-payment-gateway.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
Labels: pr: ready to merge

#5393 Add check for session existence before initiating Fraud_Prevention_Service
  changelog/fix-5127-fix-fraud-wc-session-in-cron-task
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-blocks-payment-method.php
  includes/class-wc-payments-checkout.php
  includes/class-wc-payments-upe-checkout.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: needs review

#5394 Add Apple Pay and Google Pay to payment method list in gateway description
  changelog/update-gateway-descriptions-add-apple-google-pay
  includes/class-wc-payment-gateway-wcpay.php
  includes/payment-methods/class-upe-payment-gateway.php
Labels: type: enhancement, pr: ready to merge, category: core

#5388 Settings: fix saving settings when enabled payment methods setting contains faulty data
  changelog/fix-4847-saving-settings-when-enabled-pm-setting-faulty
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/constants/class-payment-method.php
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
Labels: pr: needs review

#5296 Update UPE logic around the cards payment method and improve onboarding styling
  changelog/update-4114-upe-onboarding-with-just-credit-cards-method
  client/additional-methods-setup/upe-preview-methods-selector/add-payment-methods-task.js
  client/additional-methods-setup/upe-preview-methods-selector/test/add-payment-methods-task.test.js
  client/additional-methods-setup/wizard/task-item.scss
  client/components/payment-methods-checkboxes/payment-method-checkbox.js
  client/components/payment-methods-checkboxes/payment-method-checkbox.scss
  client/components/payment-methods-checkboxes/test/index.js
  client/components/payment-methods-list/payment-method.js
  client/components/payment-methods-list/payment-method.scss
  client/components/payment-methods-list/test/payment-method.js
  client/payment-methods/index.js
  client/payment-methods/test/index.js
Labels: pr: ready to merge

#5378 Fix Tooltip rates display when there is a promo fee active
  changelog/fix-5367-fix-promo-tooltip-rate-display
  client/utils/account-fees.tsx
  client/utils/test/__snapshots__/account-fees.tsx.snap
  client/utils/test/account-fees.tsx
Labels: pr: ready to merge

#5440 Update subscriptions-core to 5.2.0
  changelog/subscriptions-core-5.2.0-1
  changelog/subscriptions-core-5.2.0-10
  changelog/subscriptions-core-5.2.0-11
  changelog/subscriptions-core-5.2.0-12
  changelog/subscriptions-core-5.2.0-13
  changelog/subscriptions-core-5.2.0-14
  changelog/subscriptions-core-5.2.0-15
  changelog/subscriptions-core-5.2.0-16
  changelog/subscriptions-core-5.2.0-17
  changelog/subscriptions-core-5.2.0-18
  changelog/subscriptions-core-5.2.0-19
  changelog/subscriptions-core-5.2.0-2
  changelog/subscriptions-core-5.2.0-20
  changelog/subscriptions-core-5.2.0-21
  changelog/subscriptions-core-5.2.0-22
  changelog/subscriptions-core-5.2.0-23
  changelog/subscriptions-core-5.2.0-3
  changelog/subscriptions-core-5.2.0-4
  changelog/subscriptions-core-5.2.0-5
  changelog/subscriptions-core-5.2.0-6
  changelog/subscriptions-core-5.2.0-7
  changelog/subscriptions-core-5.2.0-8
  changelog/subscriptions-core-5.2.0-9
  composer.json
  composer.lock
Labels: pr: needs review, type: task, component: wcpay subscriptions

#5360 Prevent immutable server response wearnings
  changelog/fix-5343-immutable-server-response
  includes/class-wc-payment-gateway-wcpay.php
Labels: pr: needs review

#5414 Fix TOS acceptance can prevent saving settings or accessing account dashboard
  changelog/fix-5275-treat-merchant-that-left-kyc-early-as-new-users
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-account.php
  tests/unit/admin/test-class-wc-payments-admin.php
  tests/unit/test-class-wc-payments-account.php
Labels: pr: ready to merge

#5442 Generate mandates only for INR
  changelog/update-generate-mandates-only-for-inr
  includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php
Labels: pr: ready to merge

#5446 Skip running blocks E2E tests
  .github/workflows/e2e-pull-request.yml
  .github/workflows/e2e-test.yml
  changelog/skip-blocks-e2e-tests
Labels: pr: ready to merge

#5369 Update Business Details task needs more context
  changelog/add-5069-update-business-details-task
  client/card-readers/list/list-item.tsx
  client/globals.d.ts
  client/overview/modal/update-business-details/index.scss
  client/overview/modal/update-business-details/index.tsx
  client/overview/modal/update-business-details/strings.tsx
  client/overview/modal/update-business-details/test/__snapshots__/index.tsx.snap
  client/overview/modal/update-business-details/test/index.tsx
  client/overview/task-list/index.js
  client/overview/task-list/strings.tsx
  client/overview/task-list/tasks.js
  includes/class-wc-payments-account.php
Labels: pr: needs design review, pr: ready to merge

#5458 Fix failing unit tests for Cancelled status in WC beta
  changelog/fix-failing-unit-tests-cancelled
  tests/unit/test-class-wc-payments-order-service.php
Labels: pr: needs review

#5439 Return to cart page when coming back from WooPay
  changelog/add-return-to-cart-from-woopay
  client/checkout/api/index.js
  client/checkout/api/test/index.test.js
  includes/class-wc-payments.php
Labels: pr: ready to merge

#5410 Load chunks properly with JS concatenation enabled
  changelog/dev-chunks-loading
  client/public-path.js
  includes/class-wc-payments.php
  webpack/shared.js
Labels: pr: needs review

#5437 Fix Task List Title Style
  changelog/fix-5436-task-list-title
  client/overview/style.scss
  client/overview/task-list/index.js
Labels: pr: ready to merge

#5404 Fix currency change for manual subscription renewal.
  changelog/fix-5356-currency-change-for-manual-subscription-renewal
  includes/multi-currency/Compatibility/WooCommerceSubscriptions.php
  tests/unit/helpers/class-wc-helper-subscriptions.php
  tests/unit/multi-currency/compatibility/test-class-woocommerce-subscriptions.php
Labels: pr: ready to merge

#5479 Add a session check before trying to get items from the session
  changelog/fix-add-session-check-subs-compatibility
  includes/multi-currency/Compatibility/WooCommerceSubscriptions.php
Labels: pr: needs review

#5389 Change read more link for warning message on Apple Pay domain registration failure
  changelog/fix-4511-change-registration-domain-docs-link
  includes/class-wc-payments-apple-pay-registration.php
Labels: pr: needs review
