Repository Automattic/woocommerce-payments, pull requests merged in 2023-11, with the labels that each got.

#7573 Fix total price for Google Pay on quantity change.
  changelog/fix-payment-button-qty-product
  includes/class-wc-payments-payment-request-button-handler.php
Labels: pr: ready to merge

#7408 Fix currency formatting for totals on My Account > Subscriptions page
  changelog/fix-5488-subs-page-currency-format-incorrect
  includes/multi-currency/Compatibility/WooCommerceSubscriptions.php
  includes/multi-currency/MultiCurrency.php
  tests/unit/multi-currency/compatibility/test-class-woocommerce-subscriptions.php
Labels: pr: needs review

#7598 Remove WC beta tests from matrix config & add a todo comment
  .github/workflows/e2e-test.yml
  changelog/skip-wc-beta-tests
Labels: pr: ready to merge, category: e2e, category: devops

#7535 Always show Express payment buttons for Pay for Order page
  changelog/fix-express-pay-pay-for-order-page
  includes/class-wc-payments-payment-request-button-handler.php
Labels: pr: needs review

#7581 Avoid returning Stripe error message when capturing more than order amount
  changelog/update-7029-avoid-returning-stripe-error-message-when-capturing-more-than-order-amount
  includes/class-wc-payments.php
  includes/exceptions/class-amount-too-large-exception.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: ready to merge

#7060 Add refund controls when transaction is missing order
  changelog/add-7001-refund-control-when-no-order
  client/components/card-notice/index.tsx
  client/components/card-notice/styles.scss
  client/components/card-notice/test/__snapshots__/index.tsx.snap
  client/components/card-notice/test/index.tsx
  client/payment-details/summary/index.tsx
  client/payment-details/summary/missing-order-notice/index.tsx
  client/payment-details/summary/missing-order-notice/style.scss
  client/payment-details/summary/style.scss
  client/payment-details/summary/test/__snapshots__/index.test.tsx.snap
  client/payment-details/summary/test/index.test.tsx
  client/settings/wcpay-settings-context.js
  includes/class-wc-payments-features.php
Labels: pr: needs review

#7549 (Privacy) Fixed some newly added PII keys were not redacted
  changelog/fix-6600-redacting-keys
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: ready to merge

#7613 Remove unused account status settings chip code
  changelog/fix-6415-remove-unused-account-status-settings-chip-code
  client/account-status-settings/index.js
  client/account-status-settings/style.scss
  client/account-status-settings/test/__snapshots__/index.js.snap
  client/account-status-settings/test/index.js
Labels: pr: ready to merge

#7641 Fix the amount conversion rate for blocked transactions
  changelog/fix-7583-mc-decimals
  includes/admin/class-wc-rest-payments-charges-controller.php
Labels: pr: ready to merge

#7605 Exclude estimated deposits from useDeposits data hook by default
  changelog/7604-no-estimated-deposits-on-deposits-detail-page
  client/data/deposits/hooks.ts
Labels: pr: ready to merge

#7601 Ensure shortcode renders for Privacy Policy & Terms of Service
  changelog/fix-7600-woopay-checkout-shortcode-rendering
  client/settings/express-checkout-settings/index.scss
  client/settings/express-checkout-settings/woopay-preview.js
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/woopay/class-woopay-session.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: type: bug, component: WooPay, needs demo

#7627 Remove outdated `wcpay_transactions_download` tracking events.
  changelog/remove-transactions-download-tracks-event
  client/transactions/list/index.tsx
Labels: pr: ready to merge

#7563 Introduce the `wcpay_terminal_payment_completed_order_status` filter
  changelog/add-ipp-order-status-filter
  includes/class-wc-payments-order-service.php
  tests/unit/test-class-wc-payments-order-service.php
Labels: pr: needs review, component: card present

#7652 Fix not allowed page when clicking Set up WooPayments from Core and account is already onboarded
  changelog/fix-7625-fix-setup-payments-task-for-completed-accounts
  includes/class-wc-payments-account.php
Labels: pr: ready to merge

#7660 Update yoast/phpunit-polyfills to 1.1.0 to prevent version mismatch with WP 6.4
  changelog/fix-compatibility-workflow
  composer.json
  composer.lock
Labels: pr: needs review

#7586 Handle rejected capability status
  changelog/fix-7449-handle-rejected-pm-capability-status
  client/additional-methods-setup/constants.js
  client/components/payment-methods-list/payment-method.tsx
Labels: pr: ready to merge

#7659 Polish logic of redirect when click Set Up WooPayments from WC Home
  changelog/tweak-7625-set-up-woopayments-link-from-core-polish-current-logic
  includes/class-wc-payments-account.php
Labels: pr: ready to merge

#7676 Update plugin name to WooPayments
  changelog/fix-update-plugin-name-to-woopayments
  woocommerce-payments.php
Labels: pr: ready to merge

#7638 Hide IPP references in Transaction settings when Cash on Delivery is disabled
  changelog/update-6972-unclear-description-when-enabling-auth-capture
  client/settings/transactions/manual-capture-control.tsx
  client/settings/transactions/test/index.test.js
  includes/admin/class-wc-rest-payments-settings-controller.php
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
Labels: pr: ready to merge

#7648 Calculate next deposit date rather than relying on estimated deposits
  changelog/fix-7628-calculate-next-deposit-date
  client/deposits/utils/index.ts
  client/deposits/utils/test/index.ts
  client/types/account-overview.d.ts
Labels: pr: ready to merge

#7668 Revert "Exclude estimated deposits from useDeposits data hook by default"
  changelog/7604-no-estimated-deposits-on-deposits-detail-page
  changelog/revert-7605-7604-no-estimated-deposits-on-deposits-detail-page
  client/data/deposits/hooks.ts
Labels: pr: ready to merge

#7669 Code quality: remove redundant pluralised string in account balances
  changelog/fix-code-quality-account-balances-remove-duplicate-string
  client/components/account-balances/index.tsx
Labels: pr: ready to merge, type: task, priority: low

#7665 Fixes to the account status logic
  changelog/update-account-status-logic
  client/components/account-status/test/__snapshots__/index.js.snap
  client/components/account-status/test/index.js
  client/components/deposits-status/index.tsx
  client/components/deposits-status/test/__snapshots__/index.js.snap
  client/components/payments-status/index.tsx
Labels: pr: needs review

#7690 WC Beta E2E tests - Add workaround to revert to classic checkout
  .github/workflows/e2e-test.yml
  changelog/update-e2e-wc-8.3-workaround
  tests/e2e/env/setup.sh
Labels: pr: ready to merge, category: e2e, category: devops

#7645 RPP: Default to automatic capture
  changelog/rpp-7416-use_automatic_capture_as_default
  src/Internal/Payment/PaymentContext.php
  src/Internal/Service/PaymentProcessingService.php
  src/Internal/Service/PaymentRequestService.php
  tests/unit/src/Internal/Payment/PaymentContextTest.php
  tests/unit/src/Internal/Service/PaymentRequestServiceTest.php
Labels: pr: ready to merge

#7687 Update Fraud & Risk tools radio button to match colors with the current theme
  changelog/fix-7539-radio-bg-color
  client/settings/fraud-protection/style.scss
Labels: pr: ready to merge

#7575 Remove UGX from zero decimal currencies
  changelog/fix-6946-remove-ugx-zero-decimal
  includes/class-wc-payments-utils.php
Labels: pr: ready to merge

#7698 Revert CC asset
  assets/images/payment-methods/cc.svg
  changelog/fix-revert-cc-asset
  client/payment-methods-icons.tsx
  client/payment-methods/test/__snapshots__/activation-modal.test.js.snap
  client/payment-methods/test/__snapshots__/delete-modal.test.js.snap
  client/style.scss
Labels: pr: ready to merge

#7692 Add country to PM amount limits
  changelog/fix-7680-add-country-to-pm-amount-limits
  includes/payment-methods/class-affirm-payment-method.php
  includes/payment-methods/class-afterpay-payment-method.php
  includes/payment-methods/class-klarna-payment-method.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/payment-methods/class-upe-payment-method.php
  includes/payment-methods/class-upe-split-payment-gateway.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
  tests/unit/payment-methods/test-class-upe-split-payment-gateway.php
Labels: pr: needs review

#7642 Fix builders being stuck after leaving KYC without finishing
  changelog/fix-7626-builder-stuck-on-sorry-you-are-not-allowed
  includes/class-wc-payments-account.php
  tests/unit/test-class-wc-payments-account.php
Labels: pr: needs review

#7611 Update admin PhoneInput style
  changelog/fix-7512-settings-phone-number-input-style
  client/settings/phone-input/style.scss
Labels: pr: needs review, pr: needs design review

#7701 Fix saved card payment error on blocks checkout
  changelog/fix-7700-card-testing-prevention-prevents-saved-card-payments-on-blocks-checkout
  client/checkout/blocks/fields.js
  client/checkout/blocks/generate-payment-method.js
  client/checkout/blocks/saved-token-handler.js
  client/checkout/blocks/upe-fields.js
  client/checkout/blocks/upe-split-fields.js
Labels: pr: needs review

#7650 E2E tests for checking out with Giropay
  changelog/add-6761-giropay-e2e
  tests/e2e/specs/upe-split/shopper/shopper-deferred-intent-creation-upe-enabled.spec.js
  tests/e2e/utils/payments.js
Labels: pr: ready to merge, category: e2e

#7608 Handle minimum amount error in InitialState (project RPP).
  changelog/rpp-7415-verification-minimum-amount
  src/Internal/DependencyManagement/ServiceProvider/PaymentsServiceProvider.php
  src/Internal/Payment/State/InitialState.php
  src/Internal/Service/MinimumAmountService.php
  tests/unit/src/Internal/Payment/State/InitialStateTest.php
  tests/unit/src/Internal/Service/MinimumAmountServiceTest.php
  tests/unit/src/Internal/Service/SessionServiceTest.php
Labels: pr: ready to merge

#7693 Adds a new option which reflects the modal being dismissed.
  changelog/7683-prompt-to-complete-onboarding-shows-twice
  client/globals.d.ts
  client/overview/modal/progressive-onboarding-eligibility/index.tsx
  client/overview/modal/progressive-onboarding-eligibility/test/index.test.tsx
  includes/class-wc-payments-account.php
  includes/class-wc-payments-onboarding-service.php
Labels: pr: ready to merge

#7640 Add customer details flow to inital state
  changelog/rpp-7417-manage-customer-details
  includes/class-wc-payments-customer-service.php
  src/Internal/Payment/PaymentContext.php
  src/Internal/Payment/State/InitialState.php
  src/Internal/Service/OrderService.php
  src/Internal/Service/PaymentProcessingService.php
  tests/unit/src/Internal/Payment/State/InitialStateTest.php
  tests/unit/src/Internal/Service/OrderServiceTest.php
Labels: pr: ready to merge

#7469 Fix old subs links
  changelog/fix-update-subscriptions-related-docs-links
  client/settings/advanced-settings/stripe-billing-notices/migrate-automatically-notice.tsx
  client/settings/advanced-settings/stripe-billing-notices/migrate-option-notice.tsx
  client/settings/advanced-settings/stripe-billing-toggle.tsx
  client/settings/advanced-settings/wcpay-subscriptions-toggle.js
  includes/subscriptions/templates/html-subscriptions-plugin-notice.php
  includes/subscriptions/templates/html-wcpay-deactivate-warning.php
  includes/subscriptions/templates/html-woo-payments-deactivate-warning.php
Labels: type: documentation, component: wcpay subscriptions, needs triage

#7632 Remove "Estimated" option from the deposit list advanced filters
  changelog/fix-7630-remove-estimated-deposit-status-filter-option
  client/components/account-balances/test/index.test.tsx
  client/components/deposit-status-chip/index.tsx
  client/components/deposit-status-chip/test/index.test.tsx
  client/components/deposits-overview/test/__snapshots__/index.tsx.snap
  client/components/deposits-overview/test/index.tsx
  client/components/deposits-overview/utils.ts
  client/data/transactions/hooks.ts
  client/deposits/filters/test/__snapshots__/index.js.snap
  client/deposits/filters/test/index.js
  client/deposits/strings.ts
  client/types/deposits.d.ts
Labels: pr: ready to merge

#7688 Exclude estimated deposits from useDeposits data hook by default
  changelog/7604-no-estimated-deposits-on-deposits-detail-page
  client/data/deposits/hooks.ts
Labels: pr: ready to merge

#7670 Remove estimated deposits from transaction list and details page
  changelog/fix-7657_7658-estimated_deposits
  client/payment-details/timeline/map-events.js
  client/transactions/list/deposit.tsx
  client/transactions/list/test/__snapshots__/deposit.tsx.snap
  client/transactions/list/test/__snapshots__/index.tsx.snap
Labels: pr: ready to merge

#7723 Remove unsupported EUR currency from Afterpay payment method
  changelog/update-7713-remove-eur-from-the-list-of-supported-currencies-for-afterpay
  includes/payment-methods/class-afterpay-payment-method.php
Labels: pr: ready to merge

#7721 Show Payments menu sub-items only for merchants that completed KYC
  changelog/fix-7705-show-payments-menu-subitems-only-if-details-submitted
  client/components/test-mode-notice/index.js
  client/components/test-mode-notice/test/__snapshots__/index.js.snap
  client/components/test-mode-notice/test/index.js
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-account.php
  tests/unit/admin/test-class-wc-payments-admin.php
Labels: pr: ready to merge

#7483 Fix setting options on non-production environments
  changelog/fix-6961-setting-options-non-prod-envs
  includes/class-wc-payments.php
Labels: pr: needs review

#7745 Revert "Merge branch 'add/7596-transactions-filters' into develop"
  changelog/add-7596-transactions-filters
  changelog/revert-7596-transactions-filter-branch
  client/data/transactions/hooks.ts
  client/data/transactions/resolvers.js
  client/deposits/details/test/index.tsx
  client/transactions/declarations.d.ts
  client/transactions/filters/config.ts
  client/transactions/filters/test/__snapshots__/index.tsx.snap
  client/transactions/filters/test/index.tsx
  client/transactions/list/index.tsx
  client/transactions/strings.ts
  includes/admin/class-wc-rest-payments-transactions-controller.php
  includes/core/server/request/class-list-transactions.md
  includes/core/server/request/class-list-transactions.php
  tests/js/jest-test-file-setup.js
  tests/unit/core/server/request/test-class-list-transactions-request.php
Labels: pr: needs review

#7453 E2E tests for Affirm and Afterpay checkout
  changelog/dev-6125-e2e-tests-for-critical-bnpl-flows
  tests/e2e/specs/upe-split/shopper/shopper-bnpls-checkout.spec.js
  tests/e2e/utils/flows.js
Labels: pr: ready to merge

#7696 RPP: Handle fraud prevention service in InitialState
  changelog/rpp-7413-fraud-service
  src/Internal/DependencyManagement/ServiceProvider/PaymentsServiceProvider.php
  src/Internal/Payment/PaymentContext.php
  src/Internal/Payment/State/InitialState.php
  src/Internal/Service/FraudPreventionService.php
  tests/unit/src/Internal/Payment/PaymentContextTest.php
  tests/unit/src/Internal/Payment/State/InitialStateTest.php
  tests/unit/src/Internal/Service/FraudPreventionServiceTest.php
Labels: pr: ready to merge

#7672 RPP: Handle failed transaction rate limiter
  changelog/rpp-7414-transaction-limiter
  composer.json
  composer.lock
  src/Internal/DependencyManagement/ServiceProvider/PaymentsServiceProvider.php
  src/Internal/Payment/AbstractSessionRateLimiter.php
  src/Internal/Payment/FailedTransactionRateLimiter.php
  src/Internal/Payment/State/InitialState.php
  src/Internal/Service/OrderService.php
  tests/unit/bootstrap.php
  tests/unit/src/Internal/Payment/AbstractSessionRateLimiterTest.php
  tests/unit/src/Internal/Payment/FailedTransactionRateLimiterTest.php
  tests/unit/src/Internal/Payment/State/InitialStateTest.php
  tests/unit/src/Internal/Service/OrderServiceTest.php
Labels: pr: ready to merge

#7636 Reinitialise the Express Payment buttons if the customer previously aborted a request and has changed the chosen product variation
  changelog/fix-shipping-method-total-express-checkout-buttons
  client/payment-request/index.js
Labels: pr: needs review

#7737 Clean up after order is completed processing
  changelog/add-7423-completion-cleanup
  src/Internal/DependencyManagement/ServiceProvider/PaymentsServiceProvider.php
  src/Internal/Payment/State/ProcessedState.php
  tests/unit/src/Internal/Payment/State/ProcessedStateTest.php
Labels: pr: ready to merge

#7757 Transaction detail render customer with falling back to order details
  changelog/fix-7740-transaction-detail-render-customer-name-fallback
  client/components/customer-link/index.tsx
  client/components/customer-link/test/__snapshots__/index.tsx.snap
  client/components/customer-link/test/index.tsx
  client/data/payment-intents/test/hooks.ts
  client/payment-details/order-details/test/index.test.tsx
  client/payment-details/summary/index.tsx
  client/transactions/list/test/index.tsx
  client/types/orders.d.ts
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: ready to merge

#7707 Add date_between filter for Authorization Reporting API
  changelog/fix-7445-authorization-filters
  docs/rest-api/source/includes/wp-api-v3/reports.md
  includes/reports/class-wc-rest-payments-reports-authorizations-controller.php
Labels: pr: needs review

#7772 Buyer details reference: handle empty billing name.
  changelog/fix-7740-customer-reference-rendering-no-name
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: ready to merge

#7775 Allow requests with IDs to be extended
  changelog/fix-7508-request-extension
  includes/core/server/class-request.php
  tests/unit/core/server/request/test-class-core-request.php
Labels: pr: needs review

#7773 Enable the new onboarding flow as default for all users
  changelog/update-7738-enable-progressive-onboarding-as-default-flow
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-features.php
  includes/class-wc-payments-utils.php
  tests/e2e/specs/wcpay/merchant/merchant-progressive-onboarding.spec.js
  tests/e2e/utils/flows.js
  tests/unit/test-class-wc-payments-features.php
Labels: pr: ready to merge

#7729 Upgrade the csv-export JS package to the latest version
  changelog/update-7307-csv-export-package-version
  docs/dependencies.md
  package-lock.json
  package.json
Labels: dependencies, category: core, type: developer experience

#7784 Deposit details - for instant deposits, replace the transaction list with a message
  changelog/fix-7771-remove-instant-deposit-transaction-list
  client/data/deposits/hooks.ts
  client/deposits/details/index.tsx
  client/deposits/details/style.scss
  client/deposits/details/test/index.tsx
Labels: pr: ready to merge

#7798 Use supported countries instead of business types for PO
  changelog/update-6841-supported-countries-fallback
  client/onboarding/steps/business-details.tsx
  client/onboarding/steps/test/business-details.tsx
  client/onboarding/utils.ts
Labels: pr: needs review

#7768 Improve Dev Mode Indicators
  changelog/dev-7498-improve-dev-mode
  client/capital/index.tsx
  client/components/banner-notice/index.tsx
  client/components/banner-notice/style.scss
  client/components/test-mode-notice/index.js
  client/components/test-mode-notice/index.tsx
  client/components/test-mode-notice/test/__snapshots__/index.js.snap
  client/components/test-mode-notice/test/__snapshots__/index.tsx.snap
  client/components/test-mode-notice/test/index.js
  client/components/test-mode-notice/test/index.tsx
  client/deposits/details/index.tsx
  client/deposits/index.tsx
  client/disputes/evidence/index.js
  client/disputes/index.tsx
  client/documents/index.tsx
  client/overview/index.js
  client/overview/modal/setup-live-payments/index.tsx
  client/overview/modal/setup-live-payments/style.scss
  client/overview/modal/setup-live-payments/test/index.test.tsx
  client/overview/setup-real-payments.tsx
  client/overview/strings.tsx
  client/overview/style.scss
  client/overview/test/index.js
  client/overview/test/setup-real-payments.test.tsx
  client/payment-details/payment-details/index.tsx
  client/payment-details/readers/index.js
  client/settings/general-settings/index.js
  client/transactions/index.tsx
  includes/class-wc-payments-account.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: needs design review, pr: ready to merge

#7786 Code quality improvements for the Deposit Details component
  changelog/dev-improve-deposit-details-code-quality
  client/deposits/details/index.tsx
  client/deposits/details/test/index.tsx
Labels: pr: ready to merge, type: task, priority: low, component: deposits, category: trash pickup
