Repository Automattic/woocommerce-payments, pull requests merged in 2023-05, with the labels that each got.

#6166 Update `@wordpress/element` dependency to version 4.4.1
  changelog/update-dependency-wordpress-element
  docs/dependencies.md
  package-lock.json
  package.json
Labels: pr: ready to merge, dependencies, category: devops

#6171 Update @wordpress/plugins to 4.4.3
  changelog/update-wordpress-plugins-dependency-2
  docs/dependencies.md
  package-lock.json
  package.json
Labels: pr: ready to merge

#6172 Update @wordpress/hooks to 3.6.1
  changelog/update-wordpress-hooks-dependency
  docs/dependencies.md
  package-lock.json
  package.json
Labels: pr: ready to merge

#6190 Run only pending timers to avoid recursive loop
  changelog/update-jest-timer-recursive
  client/additional-methods-setup/upe-preview-methods-selector/test/add-payment-methods-task.test.js
Labels: pr: ready to merge

#6179 Update @wordpress/scripts to v19.2.3
  changelog/update-wordpress-scripts-dependency
  docs/dependencies.md
  package-lock.json
  package.json
Labels: pr: needs review

#6176 Ignore semgrep errors where safe
  changelog/fix-ignore-semgrep-safe-warnings
  includes/admin/class-wc-payments-admin-sections-overwrite.php
  includes/admin/class-wc-payments-admin-settings.php
  includes/class-experimental-abtest.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-payment-request-button-handler.php
  includes/class-wc-payments-upe-checkout.php
  includes/class-wc-payments-utils.php
  includes/class-wc-payments.php
  includes/compat/subscriptions/class-wc-payments-email-failed-renewal-authentication.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/subscriptions/class-wc-payments-subscription-change-payment-method-handler.php
  includes/subscriptions/class-wc-payments-subscriptions-onboarding-handler.php
Labels: pr: needs review

#6188 Add basic tracking for deposits card
  changelog/deposits-tracks-events
  client/components/deposits-overview/footer.tsx
  client/deposits/declarations.d.ts
  client/tracks/index.js
Labels: pr: ready to merge

#6148 Implement pending account status
  changelog/add-5672-support-pending-account-status
  client/components/account-status/index.js
  client/components/account-status/shared.scss
  client/components/account-status/status-chip.js
  client/components/account-status/test/__snapshots__/index.js.snap
  client/components/account-status/test/index.js
  client/components/chip/index.js
  client/components/chip/test/__snapshots__/index.js.snap
  client/components/chip/test/index.js
  client/components/deposits-status/index.js
  client/components/deposits-status/test/__snapshots__/index.js.snap
  client/components/deposits-status/test/index.js
  client/components/payments-status/index.js
  client/components/payments-status/test/__snapshots__/index.js.snap
  client/components/payments-status/test/index.js
Labels: pr: ready to merge

#6013 Redirect unavailable Payments > Overview to the Payments > Connect page
  changelog/fix-6011-payments-overview-redirect
  client/overview/index.js
  includes/admin/class-wc-payments-admin.php
  tests/unit/admin/test-class-wc-payments-admin.php
Labels: pr: ready to merge

#6167 Fetch, cache, and localize for JS onboarding wizard fields data from PHP, collect and prefill MCC
  changelog/add-6104-preload-and-cache-onboarding-wizard-fields-data
  client/capital/index.tsx
  client/components/grouped-select-control/index.tsx
  client/components/grouped-select-control/test/index.test.tsx
  client/globals.d.ts
  client/onboarding-experiment/hooks.ts
  client/onboarding-experiment/tasks/add-business-info-task/index.tsx
  client/onboarding-experiment/tasks/add-business-info-task/test/__snapshots__/index.tsx.snap
  client/onboarding-experiment/tasks/add-business-info-task/test/index.tsx
  client/onboarding-experiment/translations/structures.tsx
  client/onboarding-experiment/translations/types.tsx
  client/onboarding-experiment/types.d.ts
  client/onboarding-prototype/form.tsx
  client/onboarding-prototype/steps/business-details.tsx
  client/onboarding-prototype/steps/test/business-details.tsx
  client/onboarding-prototype/translations/descriptions.tsx
  client/onboarding-prototype/types.ts
  client/onboarding-prototype/utils.ts
  includes/admin/class-wc-payments-admin.php
  includes/class-database-cache.php
  includes/class-wc-payments-onboarding-service.php
  includes/class-wc-payments.php
  includes/core/class-mode.php
  includes/multi-currency/MultiCurrency.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/admin/test-class-wc-payments-admin.php
Labels: pr: needs review

#6088 Add support for Sweden
  client/utils/account-fees.tsx
  includes/class-wc-payments-utils.php
Labels: pr: needs review

#6063 Add support for Romania
  client/utils/account-fees.tsx
  includes/class-wc-payments-utils.php
Labels: pr: needs review

#6168 Add support for Czech Republic
  client/utils/account-fees.tsx
  includes/class-wc-payments-utils.php
Labels: pr: needs review

#6069 Add support for Croatia
  client/utils/account-fees.tsx
  includes/class-wc-payments-utils.php
Labels: pr: needs review

#6207 Add support for Bulgaria
  client/utils/account-fees.tsx
  includes/class-wc-payments-utils.php
Labels: pr: needs review

#6212 Update `@woocommerce/explat` to v2.3.0
  changelog/update-woocommerce-explat-dependency
  docs/dependencies.md
  package-lock.json
  package.json
Labels: pr: ready to merge

#6201 Bump WC & PHP versions + Remove pinned composer version
  .github/actions/e2e/env-setup/action.yml
  .github/workflows/check-changelog.yml
  .github/workflows/compatibility.yml
  .github/workflows/e2e-test.yml
  .github/workflows/php-lint-test.yml
  bin/run-ci-tests-check-coverage.bash
  bin/run-ci-tests.bash
  changelog/fix-compatibility-tests
  phpcs-compat.xml.dist
  phpcs.xml.dist
  readme.txt
  woocommerce-payments.php
Labels: pr: ready to merge, category: devops

#6237 Update @woocommerce/experimental to 3.2.0
  changelog/update-woocommerce-experimental-dependency
  docs/dependencies.md
  package-lock.json
  package.json
Labels: pr: needs review

#6228 Explicitly mark used dependencies
  changelog/update-explicit-dev-deps
  client/account-status-settings/test/__snapshots__/index.js.snap
  client/components/account-balances/test/__snapshots__/index.test.tsx.snap
  client/components/account-status/test/__snapshots__/index.js.snap
  client/components/deposits-information/test/__snapshots__/index.js.snap
  client/components/deposits-overview/test/__snapshots__/index.tsx.snap
  client/components/deposits-status/test/__snapshots__/index.js.snap
  client/components/details-link/test/__snapshots__/index.js.snap
  client/components/download-button/test/__snapshots__/index.js.snap
  client/components/file-upload/test/__snapshots__/index.tsx.snap
  client/components/payment-confirm-illustration/test/__snapshots__/index.tsx.snap
  client/components/payments-status/test/__snapshots__/index.js.snap
  client/deposits/list/test/__snapshots__/index.tsx.snap
  client/disputes/evidence/test/__snapshots__/index.js.snap
  client/disputes/test/__snapshots__/index.tsx.snap
  client/multi-currency/multi-currency-settings/enabled-currencies-list/test/__snapshots__/index.js.snap
  client/onboarding-experiment/requirements/test/__snapshots__/company.tsx.snap
  client/onboarding-experiment/requirements/test/__snapshots__/individual.tsx.snap
  client/onboarding-experiment/tasks/add-business-info-task/test/__snapshots__/required-verification-info.tsx.snap
  client/payment-details/readers/test/__snapshots__/index.js.snap
  client/payment-details/timeline/test/__snapshots__/index.js.snap
  client/payment-methods/test/__snapshots__/activation-modal.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/avs-mismatch.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/cvc-verification.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/international-ip-address.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/order-items-threshold.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/purchase-price-threshold.test.js.snap
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/allow-countries-notice.test.js.snap
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/index.test.js.snap
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/rule-card-notice.test.js.snap
  client/settings/fraud-protection/components/protection-level-modal-notice/test/__snapshots__/index.test.js.snap
  client/settings/fraud-protection/components/protection-levels/test/__snapshots__/index.test.js.snap
  client/settings/fraud-protection/test/__snapshots__/index.test.js.snap
  client/transactions/list/test/__snapshots__/converted-amount.tsx.snap
  client/transactions/list/test/__snapshots__/index.tsx.snap
  package-lock.json
  package.json
Labels: pr: ready to merge

#6241 Refactor the DownloadButton component to use TypeScript
  client/components/download-button/index.tsx
Labels: type: task, category: refactor

#6225 Add basic usage tracking in deposits list
  changelog/fix-5884-deposits-list-tracks
  client/components/clickable-cell/index.js
  client/deposits/list/index.tsx
  client/tracks/index.js
Labels: pr: ready to merge

#6226 Add support of complete_kyc_link in wcpay-link-handler route
  changelog/add-server-3268-support-complete-kyc-link
  client/onboarding-prototype/steps/loading.tsx
  client/onboarding-prototype/steps/test/loading.tsx
  includes/class-wc-payments-account.php
  tests/unit/admin/test-class-wc-rest-payments-onboarding-controller.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: ready to merge

#6253 Update WordPress dev dependencies
  changelog/update-wordpress-block-editor-dependency
  changelog/update-wordpress-blocks-dependency
  changelog/update-wordpress-dom-dependency
  changelog/update-wordpress-html-entities-dependency
  docs/dependencies.md
  package-lock.json
  package.json
Labels: pr: ready to merge

#6195 Hide the deposits card for merchants without an estimated deposit and deposit history
  changelog/fix-6193-hide-deposits-card-to-new-merchants
  client/components/deposits-overview/index.tsx
Labels: pr: ready to merge

#6154 Update the fraud and risk tools banner
  assets/images/fraud-protection/discoverability-banner@2x.png
  changelog/update-6149-fraud-risk-discoverability-banner
  client/components/fraud-risk-tools-banner/components/banner-body/index.tsx
  client/components/fraud-risk-tools-banner/components/banner-body/test/__snapshots__/index.test.tsx.snap
  client/components/fraud-risk-tools-banner/style.scss
  client/components/fraud-risk-tools-banner/test/__snapshots__/index.test.tsx.snap
Labels: pr: ready to merge

#6156 Update the Fraud & Risk tools welcome tour copy
  changelog/update-6155-tour-copy
  client/settings/fraud-protection/style.scss
  client/settings/fraud-protection/test/__snapshots__/index.test.js.snap
  client/settings/fraud-protection/tour/__snapshots__/index.test.tsx.snap
  client/settings/fraud-protection/tour/index.tsx
  client/settings/fraud-protection/tour/steps.tsx
Labels: pr: ready to merge

#6221 Fraud & Risk tools usability improvements
  changelog/update-6157-usability-improvements
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/address-mismatch.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/international-ip-address.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/ip-address-mismatch.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/order-items-threshold.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/purchase-price-threshold.test.js.snap
  client/settings/fraud-protection/advanced-settings/rule-toggle.js
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/index.test.js.snap
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/rule-toggle.test.js.snap
  client/settings/fraud-protection/advanced-settings/test/rule-toggle.test.js
  client/settings/fraud-protection/components/protection-levels/index.js
  client/settings/fraud-protection/components/protection-levels/test/__snapshots__/index.test.js.snap
  client/settings/fraud-protection/components/protection-levels/test/index.test.js
  client/settings/fraud-protection/style.scss
  client/settings/fraud-protection/test/__snapshots__/index.test.js.snap
  includes/fraud-prevention/class-order-fraud-and-risk-meta-box.php
  tests/unit/fraud-prevention/test-class-order-fraud-and-risk-meta-box.php
Labels: pr: ready to merge

#6260 Special tooltip content when pending balance is negative
  changelog/add-6051-tooltip-negative-pending-balance
  client/components/account-balances/balances-tab-panel.tsx
  client/components/account-balances/test/index.test.tsx
Labels: pr: ready to merge

#6256 Update wordpress/data-controls dependency to 2.6.1
  changelog/update-wordpress-data-controls-dependency
  client/data/authorizations/actions.ts
  client/data/authorizations/resolvers.ts
  client/data/authorizations/test/actions.test.ts
  client/data/authorizations/test/resolvers.test.ts
  client/data/capital/resolvers.ts
  client/data/capital/test/resolvers.js
  client/data/charges/resolvers.js
  client/data/charges/test/resolvers.ts
  client/data/deposits/resolvers.js
  client/data/deposits/test/resolvers.js
  client/data/disputes/actions.js
  client/data/disputes/resolvers.js
  client/data/disputes/test/actions.js
  client/data/disputes/test/resolvers.js
  client/data/documents/resolvers.js
  client/data/documents/test/resolvers.js
  client/data/payment-intents/resolvers.ts
  client/data/payment-intents/test/resolvers.ts
  client/data/transactions/resolvers.js
  client/data/transactions/test/resolvers.js
  client/types/data-controls.d.ts
  client/types/data.d.ts
  docs/dependencies.md
  package-lock.json
  package.json
Labels: pr: needs review

#6284 Update WordPress dev dependencies
  changelog/update-wordpress-babel-plugin-makepot-dependency
  changelog/update-wordpress-base-styles-dependency
  changelog/update-wordpress-jest-default-dependency
  docs/dependencies.md
  package-lock.json
  package.json
Labels: pr: ready to merge

#6286 Fix AJAX response notice for multi-currency due to empty currencies data
  changelog/fix-6257-fix-multicurrency-notice
  includes/multi-currency/MultiCurrency.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: ready to merge

#6037 Add tracking to user interaction of deposits settings
  changelog/add-5882-tracks-for-deposit-settings
  client/settings/deposits/index.js
  client/tracks/index.js
Labels: pr: ready to merge

#6265 Fix Tracks prop to use the correct header
  changelog/fix-place-order-usage-tracking
  includes/class-woopay-tracker.php
Labels: pr: needs review, component: platform checkout

#6175 Update Platform Checkout Tracking conditions
  changelog/update-platform-checkout-admin-tracks
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments.php
  includes/class-woopay-tracker.php
Labels: pr: needs review, component: platform checkout

#6252 Fix keyboard navigation for account balance tooltips
  changelog/fix-6053-overview-deposit-tooltip-keyboard-navigation
  client/components/account-balances/balance-tooltip.tsx
  client/components/account-balances/style.scss
  client/components/account-balances/test/__snapshots__/index.test.tsx.snap
  client/components/tooltip/index.tsx
  client/components/tooltip/style.scss
  client/components/tooltip/test/index.test.tsx
  client/components/tooltip/tooltip-base.tsx
Labels: pr: ready to merge

#6280 Remove `simplifyDepositsUi` feature flag and legacy UI code
  changelog/5749-Remove-feature-flag-and-old-UI-code-for-simplify-deposits-UI
  client/components/account-balances/balances-tab-panel.tsx
  client/components/deposits-information/block.tsx
  client/components/deposits-information/index.tsx
  client/components/deposits-information/loading.tsx
  client/components/deposits-information/style.scss
  client/components/deposits-information/test/__snapshots__/index.js.snap
  client/components/deposits-information/test/index.js
  client/deposits/instant-deposits/index.js
  client/deposits/instant-deposits/index.tsx
  client/deposits/instant-deposits/modal.tsx
  client/deposits/instant-deposits/test/__snapshots__/index.tsx.snap
  client/deposits/instant-deposits/test/index.tsx
  client/deposits/utils/index.js
  client/deposits/utils/index.ts
  client/deposits/utils/test/index.js
  client/deposits/utils/test/index.ts
  client/globals.d.ts
  client/overview/index.js
  client/overview/test/index.js
  includes/class-wc-payments-features.php
  tests/unit/test-class-wc-payments-features.php
Labels: pr: ready to merge

#6210 Update @woocommerce/subscriptions-core to 5.7.1
  changelog/subscriptions-core-5.7.0
  changelog/subscriptions-core-5.7.0-1
  changelog/subscriptions-core-5.7.0-2
  changelog/subscriptions-core-5.7.0-3
  changelog/subscriptions-core-5.7.1-1
  changelog/subscriptions-core-5.7.1-2
  changelog/subscriptions-core-5.7.1-3
  composer.json
  composer.lock
Labels: pr: needs review

#6268 Fix changelog from PR 6225
  changelog/fix-5884-deposits-list-tracks
  changelog/fix-changelog-from-pr-6225
Labels: pr: ready to merge

#6299 Remove fraud and risk tools feature flag again
  changelog/remove-3026-fraud-and-risk-tools-feature-flag
  client/components/fraud-risk-tools-banner/test/index.test.tsx
  client/data/transactions/resolvers.js
  client/globals.d.ts
  client/index.js
  client/overview/index.js
  client/overview/test/index.js
  client/payment-details/order-details/test/__snapshots__/index.test.tsx.snap
  client/payment-details/summary/test/index.tsx
  client/payment-details/timeline/map-events.js
  client/settings/settings-manager/index.js
  client/settings/settings-manager/test/index.test.js
  client/transactions/index.tsx
  client/transactions/test/index.tsx
  client/utils/charge/index.ts
  client/utils/charge/test/index.js
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-features.php
  includes/class-wc-payments-order-service.php
  includes/class-wc-payments.php
  includes/fraud-prevention/class-fraud-risk-tools.php
  includes/fraud-prevention/class-order-fraud-and-risk-meta-box.php
  tests/e2e/specs/wcpay/merchant/merchant-payment-settings-manual-capture.spec.js
  tests/e2e/utils/flows.js
  tests/unit/test-class-wc-payments-features.php
  tests/unit/test-class-wc-payments-order-service.php
Labels: pr: needs review

#6282 Update connect account page
  assets/images/illustrations/manage.svg
  assets/images/illustrations/multicurrency.svg
  assets/images/illustrations/payments.svg
  assets/images/illustrations/wcpay.svg
  assets/images/illustrations/woopayments.svg
  changelog/update-5508-connect-account-page
  client/connect-account-page-experiment/index.js
  client/connect-account-page-experiment/treatment/index.js
  client/connect-account-page-experiment/treatment/strings.js
  client/connect-account-page-experiment/treatment/style.scss
  client/connect-account-page-experiment/treatment/test/__snapshots__/index.js.snap
  client/connect-account-page/index.js
  client/connect-account-page/index.tsx
  client/connect-account-page/info-modal/index.tsx
  client/connect-account-page/info-modal/style.scss
  client/connect-account-page/info-modal/test/__snapshots__/index.tsx.snap
  client/connect-account-page/info-modal/test/index.tsx
  client/connect-account-page/info-notice-modal.tsx
  client/connect-account-page/strings.tsx
  client/connect-account-page/style.scss
  client/connect-account-page/test/__snapshots__/index.js.snap
  client/connect-account-page/test/__snapshots__/index.test.tsx.snap
  client/connect-account-page/test/__snapshots__/info-notice-modal.test.tsx.snap
  client/connect-account-page/test/index.js
  client/connect-account-page/test/index.test.tsx
  client/connect-account-page/test/info-notice-modal.test.tsx
  client/deposits/declarations.d.ts
  client/globals.d.ts
  client/index.js
  client/onboarding-prototype/style.scss
  client/stylesheets/abstracts/_mixins.scss
Labels: pr: ready to merge

#6255 Address progressive onboarding feedback
  changelog/add-6158-progressive-onboarding-feedback
  client/onboarding-prototype/style.scss
  client/overview/index.js
  client/overview/modal/progressive-onboarding-eligibility/style.scss
  client/overview/setup-real-payments.tsx
  client/overview/style.scss
  includes/class-wc-payments-account.php
Labels: pr: needs review

#6269 Fix Single currency settings screen currency preview for ZDC's
  changelog/fix-4528-wrong-multi-currency-preview-for-zero-decimal-currencies
  client/multi-currency/single-currency-settings/currency-preview.js
Labels: pr: needs review

#6307 Track overview balance
  changelog/add-5880-track-overview-balance
  client/components/account-balances/balances-tab-panel.tsx
  client/tracks/index.js
Labels: pr: needs review

#6312 Automatically update the local WCPay Dev Tools clone to use the latest on trunk
  .husky/post-merge
  README.md
  changelog/dev-6311-automatically-update-wcpay-dev-tools
Labels: pr: needs review

#6281 Track downloads on deposit details page.
  changelog/add-5885-deposit-detail-tracking
  client/tracks/index.js
  client/transactions/list/index.tsx
Labels: pr: ready to merge

#6328 Fix tour copy to remove review mentions
  changelog/fix-3379-remove-review-from-frt-tour-copy
  client/settings/fraud-protection/tour/steps.tsx
Labels: pr: needs review, component: fraud & risk tools

#6289 Update `@woocommerce/components` dependency to v12.0.0
  changelog/update-dependency-woocommerce-components
  client/components/deposits-overview/test/__snapshots__/index.tsx.snap
  client/components/fraud-risk-tools-banner/components/new-pill/test/__snapshots__/index.test.tsx.snap
  client/components/horizontal-list/test/index.js
  client/components/risk-level/test/__snapshots__/index.tsx.snap
  client/connect-account-page/modal/test/index.js
  client/connect-account-page/test/index.test.tsx
  client/deposits/filters/test/index.js
  client/deposits/list/test/__snapshots__/index.tsx.snap
  client/deposits/list/test/index.tsx
  client/disputes/evidence/test/index.js
  client/disputes/filters/test/__snapshots__/index.tsx.snap
  client/disputes/filters/test/index.tsx
  client/disputes/test/__snapshots__/index.tsx.snap
  client/disputes/test/index.tsx
  client/documents/filters/test/index.tsx
  client/documents/list/test/__snapshots__/index.tsx.snap
  client/multi-currency/single-currency-settings/test/__snapshots__/index.test.js.snap
  client/order/cancel-confirm-modal/index.js
  client/overview/inbox-notifications/test/index.js
  client/overview/test/index.js
  client/payment-details/order-details/test/index.test.tsx
  client/payment-details/readers/test/__snapshots__/index.js.snap
  client/payment-details/summary/test/index.tsx
  client/payment-details/test/index.test.tsx
  client/settings/fraud-protection/advanced-settings/test/index.test.tsx
  client/transactions/filters/test/index.tsx
  client/transactions/list/test/__snapshots__/index.tsx.snap
  client/transactions/list/test/index.tsx
  client/transactions/test/index.tsx
  client/transactions/uncaptured/test/__snapshots__/index.test.tsx.snap
  client/transactions/uncaptured/test/index.test.tsx
  package-lock.json
  package.json
  tests/js/jest-test-file-setup.js
  tests/js/jest.config.js
  tsconfig.json
Labels: pr: ready to merge, category: devops

#6028 Update e2e tests for compatibility with WCPay Dev Tools revamp
  changelog/update-6027-fix-e2e-test-for-wcpay-dev-tools-revamp
  tests/e2e/utils/flows.js
Labels: pr: ready to merge, type: developer experience, cooldown

#6348 Clean up the dependencies doc
  changelog/dev-update-dependencies-doc
  docs/dependencies.md
Labels: pr: needs review

#6254 Progressive Onboarding: Store onboarding collected merchant data
  changelog/add-s2939-store-onboarding-collected-data
  client/onboarding-prototype/steps/loading.tsx
  client/onboarding-prototype/steps/test/loading.tsx
  client/onboarding-prototype/types.ts
  includes/admin/class-wc-rest-payments-onboarding-controller.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-onboarding-service.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/admin/test-class-wc-rest-payments-onboarding-controller.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: needs review

#6374 Fix po router 500 error
  changelog/fix-type-cast-woo-stats
  includes/admin/class-wc-rest-payments-onboarding-controller.php
Labels: pr: needs review

#6288 Add feature flag for BNLP Affirm Afterpay payment method
  changelog/add-6034-feature-flag-bnlp
  includes/class-wc-payments-features.php
  tests/unit/test-class-wc-payments-features.php
Labels: pr: needs review

#6396 Skip merchant failing e2e tests
  changelog/dev-skip-merchant-failing-e2e-tests
  tests/e2e/specs/wcpay/merchant/merchant-orders-manual-capture.spec.js
  tests/e2e/specs/wcpay/merchant/merchant-orders-partial-refund.spec.js
  tests/e2e/specs/wcpay/merchant/merchant-orders-refund-failures.spec.js
Labels: pr: ready to merge

#6400 Fix for authentication on PO eligibility route
  changelog/dev-fix-po-eligible-route
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: needs review

#6361 Refactor `AccountBalances` card to allow separate welcome / balances cards
  changelog/dev-overview-balance-card-welcome-split
  client/components/account-balances/balances-tab-panel.tsx
  client/components/account-balances/header.tsx
  client/components/account-balances/index.tsx
  client/components/account-balances/strings.ts
  client/components/account-balances/style.scss
  client/components/account-balances/test/__snapshots__/index.test.tsx.snap
  client/components/account-balances/test/index.test.tsx
  client/components/account-balances/test/utils.test.ts
  client/components/account-balances/utils.ts
  client/components/welcome/hooks.ts
  client/components/welcome/index.tsx
  client/components/welcome/style.scss
  client/components/welcome/test/index.test.tsx
  client/overview/index.js
Labels: pr: ready to merge
