Repository Automattic/woocommerce-payments, pull requests merged in 2023-03, with the labels that each got.

#5666 Add merge request trigger to relevant workflows
  .github/workflows/js-lint-test.yml
  .github/workflows/php-lint-test.yml
  changelog/fix-5572-update-workflows-merge-queue
Labels: pr: needs review

#5652 Load Checkout scripts when Cart Total is 0
  changelog/fix-4764-load-js-zero-cart
  changelog/fix-5641-check-cart-initialized
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-checkout.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/payment-methods/class-upe-split-payment-gateway.php
Labels: pr: ready to merge

#5617 Fix monthly deposit schedule displayed incorrectly as '3rd' or '31st' when schedule set to 'Last day of the month'
  changelog/fix-5616-deposits-monthly-schedule-anchor-incorrect
  client/deposits/utils/index.js
  client/deposits/utils/test/index.js
  client/settings/deposits/index.js
Labels: pr: ready to merge, component: deposits

#5536 International Expansion: Add new countries to supported countries list
  changelog/add-new-countries-to-wcpay
  client/utils/account-fees.tsx
  includes/class-wc-payments-utils.php
Labels: pr: ready to merge, Component: International Expansion

#5660 WCPay as a Platform: Fixing the request for listing disputes
  changelog/fix-5642-disputes-page
  includes/core/server/request/class-list-disputes.php
Labels: pr: needs review

#5670 Initial progressive onboarding form
  changelog/add-5473-initial-progressive-onboarding-form
  client/components/custom-select-control/index.tsx
  client/components/stepper/index.tsx
  client/components/stepper/test/test.tsx
  client/onboarding-prototype/context.tsx
  client/onboarding-prototype/index.tsx
  client/onboarding-prototype/onboarding-form.js
  client/onboarding-prototype/regular-onboarding-notice.tsx
  client/onboarding-prototype/steps/business-details.tsx
  client/onboarding-prototype/steps/personal-details.tsx
  client/onboarding-prototype/steps/store-details.tsx
  client/onboarding-prototype/steps/test/business-details.tsx
  client/onboarding-prototype/steps/test/personal-details.tsx
  client/onboarding-prototype/steps/test/store-details.tsx
  client/onboarding-prototype/strings.tsx
  client/onboarding-prototype/test/context.tsx
  client/onboarding-prototype/test/utils.ts
  client/onboarding-prototype/types.ts
  client/onboarding-prototype/utils.ts
Labels: pr: ready to merge

#5358 Allow Get_Charge to handle py_ objects.
  changelog/fix-5341-py-charges
  includes/core/server/request/class-get-charge.php
  tests/unit/core/server/request/test-class-core-get-charge-request.php
Labels: pr: ready to merge

#5680 Update the deprecating set-output command
  .github/actions/e2e/env-setup/action.yml
  .github/actions/e2e/run-log-tests/action.yml
  .github/workflows/bundle-size.yml
  .github/workflows/check-changelog.yml
  .github/workflows/deploy-api-docs.yml
  .github/workflows/e2e-pull-request.yml
  .github/workflows/e2e-test.yml
  .github/workflows/i18n-weekly-release.yml
  changelog/update-5355-update-deprecating-commands
Labels: pr: needs review

#5575 Replace existing manual scripts asset loading with dependency extraction plugin
  changelog/5359-fix-script-dependencies-loading
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-blocks-payment-method.php
  includes/class-wc-payments-payment-request-button-handler.php
  includes/class-wc-payments-platform-checkout-button-handler.php
  includes/class-wc-payments-upe-blocks-payment-method.php
  includes/class-wc-payments-upe-split-blocks-payment-method.php
  includes/class-wc-payments.php
  includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php
  includes/multi-currency/Analytics.php
  includes/multi-currency/CurrencySwitcherBlock.php
  includes/multi-currency/MultiCurrency.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/payment-methods/class-upe-split-payment-gateway.php
  includes/platform-checkout-user/class-platform-checkout-save-user.php
  includes/subscriptions/class-wc-payments-subscriptions-empty-state-manager.php
  includes/subscriptions/class-wc-payments-subscriptions-onboarding-handler.php
Labels: pr: ready to merge

#5693 Avoid adding two fee details in the order page
  changelog/fix-5691-two-fee-notes
  includes/class-wc-payments-action-scheduler-service.php
  includes/class-wc-payments-order-service.php
  includes/class-wc-payments.php
  includes/subscriptions/class-wc-payments-subscriptions.php
Labels: pr: ready to merge

#5692 Update Subscriptions Core to 5.5.0
  changelog/subscriptions-core-5.5.0
  changelog/subscriptions-core-5.5.0-fix-1
  changelog/subscriptions-core-5.5.0-fix-2
  composer.json
  composer.lock
Labels: pr: needs review

#5710 WCPay as a Platform: Fix checkout with WooPay enabled
  changelog/fix-checkout-with-woopay-and-request-classes
  includes/woopay/services/class-checkout-service.php
  tests/unit/woopay/services/test-checkout-service.php
Labels: pr: needs review

#5586 Release automation - Run smoke tests when zip file is created
  .github/actions/e2e/env-setup/action.yml
  .github/workflows/build-zip-and-run-smoke-tests.yml
  .github/workflows/build-zip-file.yml
  .github/workflows/create-pre-release.yml
  .github/workflows/e2e-pull-request.yml
  .github/workflows/release-code-freeze.yml
  .github/workflows/release-pr.yml
  changelog/devops-automate-smoke-tests
  tests/e2e/env/setup.sh
Labels: pr: needs review, category: e2e, category: devops

#5758 Use consistent timezone in tests
  changelog/feature-consistent-timezone-tests
  client/data/transactions/test/resolvers.js
  client/transactions/list/test/index.tsx
  client/utils/test-utils.js
Labels: pr: needs review

#5740 Use concurrency to stop obsolete workflows
  .github/workflows/bundle-size.yml
  .github/workflows/check-changelog.yml
  .github/workflows/compatibility.yml
  .github/workflows/coverage.yml
  .github/workflows/e2e-pull-request.yml
  .github/workflows/js-lint-test.yml
  .github/workflows/php-compatibility.yml
  .github/workflows/php-lint-test.yml
  changelog/update-5361-use-concurrency-to-stop-obsolete-workflows
Labels: pr: needs review

#5763 Add feature flag for simplify deposits UI.
  changelog/add-5690-simplify-deposits-ui-feature-flag
  client/globals.d.ts
  includes/class-wc-payments-features.php
Labels: pr: ready to merge

#5759 New Deposits Overview UI Foundation Component
  changelog/issue-5694-new-deposits-card-skeleton
  client/components/deposits-overview/index.tsx
  client/components/deposits-overview/strings.ts
  client/overview/index.js
Labels: pr: needs review, component: deposits, category: projects

#5766 Fix bug with showing WC tasks when there is no WCPay account
  changelog/fix-4748-check-if-account-status-is-not-error
  client/overview/task-list/tasks.js
  client/overview/task-list/test/tasks.js
Labels: pr: ready to merge

#5755 Add Account Balances foundation component
  changelog/add-5720-account-balances-card
  client/components/account-balances/index.tsx
  client/components/account-balances/style.scss
  client/components/account-balances/test/__snapshots__/index.test.tsx.snap
  client/components/account-balances/test/index.test.tsx
  client/overview/index.js
Labels: pr: ready to merge, component: account overview page, category: projects

#5760 Add greeting to Account Balances header
  assets/images/woopayments.svg
  changelog/5721-add-account-balances-greeting
  client/components/account-balances/header.tsx
  client/components/account-balances/hooks.ts
  client/components/account-balances/index.tsx
  client/components/account-balances/strings.ts
  client/components/account-balances/style.scss
  client/components/account-balances/test/__snapshots__/index.test.tsx.snap
  client/components/account-balances/test/index.test.tsx
  client/components/account-balances/test/utils.test.ts
  client/components/account-balances/utils.ts
Labels: pr: ready to merge, component: account overview page, category: projects

#5467 Fix WooPay phone number on blocks checkout
  changelog/fix-woopay-phone-number-on-blocks-checkout
  client/components/platform-checkout/save-user/checkout-page-save-user.js
  client/components/platform-checkout/save-user/test/checkout-page-save-user.test.js
Labels: type: bug, component: platform checkout

#5638 Advanced fraud tools section
  changelog/add-2797-advanced-fraud-tools-section
  client/components/amount-input/index.js
  client/components/amount-input/style.scss
  client/components/amount-input/test/__snapshots__/index.test.js.snap
  client/components/amount-input/test/index.test.js
  client/data/settings/actions.js
  client/data/settings/hooks.js
  client/data/settings/selectors.js
  client/index.js
  client/settings/fraud-protection/advanced-settings/cards/address-mismatch.js
  client/settings/fraud-protection/advanced-settings/cards/avs-mismatch.js
  client/settings/fraud-protection/advanced-settings/cards/cvc-verification.js
  client/settings/fraud-protection/advanced-settings/cards/international-billing-address.js
  client/settings/fraud-protection/advanced-settings/cards/international-ip-address.js
  client/settings/fraud-protection/advanced-settings/cards/order-items-threshold.js
  client/settings/fraud-protection/advanced-settings/cards/order-velocity.js
  client/settings/fraud-protection/advanced-settings/cards/purchase-price-threshold.js
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/address-mismatch.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/avs-mismatch.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/cvc-verification.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/international-billing-address.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/international-ip-address.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/order-items-threshold.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/order-velocity.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/purchase-price-threshold.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/address-mismatch.test.js
  client/settings/fraud-protection/advanced-settings/cards/test/avs-mismatch.test.js
  client/settings/fraud-protection/advanced-settings/cards/test/cvc-verification.test.js
  client/settings/fraud-protection/advanced-settings/cards/test/international-billing-address.test.js
  client/settings/fraud-protection/advanced-settings/cards/test/international-ip-address.test.js
  client/settings/fraud-protection/advanced-settings/cards/test/order-items-threshold.test.js
  client/settings/fraud-protection/advanced-settings/cards/test/order-velocity.test.js
  client/settings/fraud-protection/advanced-settings/cards/test/purchase-price-threshold.test.js
  client/settings/fraud-protection/advanced-settings/context.js
  client/settings/fraud-protection/advanced-settings/index.js
  client/settings/fraud-protection/advanced-settings/rule-card-notice.js
  client/settings/fraud-protection/advanced-settings/rule-card.js
  client/settings/fraud-protection/advanced-settings/rule-description.js
  client/settings/fraud-protection/advanced-settings/rule-toggle.js
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/index.test.js.snap
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/rule-card-notice.test.js.snap
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/rule-card.test.js.snap
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/rule-description.test.js.snap
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/rule-toggle.test.js.snap
  client/settings/fraud-protection/advanced-settings/test/index.test.js
  client/settings/fraud-protection/advanced-settings/test/rule-card-notice.test.js
  client/settings/fraud-protection/advanced-settings/test/rule-card.test.js
  client/settings/fraud-protection/advanced-settings/test/rule-description.test.js
  client/settings/fraud-protection/advanced-settings/test/rule-toggle.test.js
  client/settings/fraud-protection/components/fp-help-text/index.js
  client/settings/fraud-protection/components/protection-levels/index.js
  client/settings/fraud-protection/components/protection-levels/test/__snapshots__/index.test.js.snap
  client/settings/fraud-protection/style.scss
  client/settings/fraud-protection/test/__snapshots__/index.test.js.snap
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments.php
  includes/fraud-prevention/class-fraud-risk-tools.php
  includes/fraud-prevention/wc-payments-fraud-risk-tools.php
Labels: pr: needs review

#5764 Add individual balance figures to the new Overview Balance card
  changelog/add-balance-card-figures
  client/components/account-balances/balance-block.tsx
  client/components/account-balances/balances-tab-panel.tsx
  client/components/account-balances/index.tsx
  client/components/account-balances/strings.ts
  client/components/account-balances/style.scss
  client/components/account-balances/test/__snapshots__/index.test.tsx.snap
  client/components/account-balances/test/index.test.tsx
  client/components/account-balances/utils.ts
  client/globals.d.ts
  includes/admin/class-wc-payments-admin.php
Labels: pr: needs review, category: projects

#5768 Add workflow "Build live branch for PR"
  .github/workflows/pr-build-live-branch.yml
  changelog/add-5624-live-branch-support
Labels: pr: ready to merge

#5792 Replace "payouts" to "deposits"
  changelog/fix-5689-replace-payout-deposits
  client/connect-account-page/strings.js
  client/connect-account-page/test/__snapshots__/index.js.snap
  client/settings/deposits/index.js
Labels: pr: ready to merge

#5777 [Simplifying Deposits UI] Next deposits table heading
  changelog/issue-5695-next-deposits-heading
  client/components/deposits-overview/index.tsx
  client/components/deposits-overview/next-deposit.tsx
  client/components/deposits-overview/strings.ts
  client/components/deposits-overview/style.scss
Labels: pr: ready to merge

#5739 Added e2e tests for Free Cart & Cart modified on Checkout page
  changelog/add-5738-E2E-test-free-cart-js
  tests/e2e/env/setup.sh
  tests/e2e/specs/wcpay/shopper/shopper-checkout-free-cart.spec.js
Labels: pr: needs review

#5813 Explicitly mention all devDependencies in the package.json file
  changelog/fix-1616-define-dependenciesin-package-json-file
  client/additional-methods-setup/upe-preview-methods-selector/add-payment-methods-task.js
  client/additional-methods-setup/upe-preview-methods-selector/enable-upe-preview-task.js
  client/components/currency-information-for-methods/index.js
  client/components/platform-checkout/index.tsx
  client/components/platform-checkout/save-user/agreement.js
  client/components/platform-checkout/save-user/checkout-page-save-user.js
  client/connect-account-page/modal/index.js
  client/multi-currency-setup/tasks/add-currencies-task/index.js
  client/multi-currency-setup/tasks/store-settings-task/index.js
  client/multi-currency/multi-currency-settings/enabled-currencies-list/delete-button.js
  client/multi-currency/multi-currency-settings/enabled-currencies-list/modal-checkbox.js
  client/payment-gateways/disable-confirmation-modal.js
  client/payment-methods/activation-modal.tsx
  client/payment-methods/delete-modal.tsx
  client/settings/advanced-settings/multi-currency-toggle.js
  client/settings/advanced-settings/wcpay-subscriptions-toggle.js
  client/settings/disable-upe-modal/index.js
  client/settings/express-checkout-settings/general-payment-request-button-settings.js
  client/settings/express-checkout/index.js
  client/settings/fraud-protection/advanced-settings/cards/address-mismatch.js
  client/settings/fraud-protection/advanced-settings/cards/avs-mismatch.js
  client/settings/fraud-protection/advanced-settings/cards/cvc-verification.js
  client/settings/fraud-protection/advanced-settings/cards/international-billing-address.js
  client/settings/fraud-protection/advanced-settings/cards/international-ip-address.js
  client/settings/fraud-protection/components/exceeds-dollar-amount-rule/index.js
  client/settings/fraud-protection/components/fp-modal/index.js
  client/settings/fraud-protection/components/protection-levels/index.js
  client/settings/general-settings/index.js
  client/tos/modal/index.js
  client/transactions/autocompleter.tsx
  client/transactions/declarations.d.ts
  client/utils/account-fees.tsx
  package-lock.json
  package.json
Labels: pr: ready to merge

#5742 Update account connection success message
  assets/images/confetti.svg
  changelog/add-4747-post-po-ui-changes
  client/overview/connection-sucess-notice.tsx
  client/overview/index.js
  client/overview/style.scss
  client/overview/test/index.js
Labels: pr: ready to merge

#5819 Update the merge instructions provided by the release workflow
  .github/workflows/release-pr.yml
  changelog/devops-update-merge-command-release-workflow
Labels: pr: ready to merge

#5821 Add IP country to payment fingerprint data
  changelog/add-server-3127-ip-country-fingerprint
  includes/fraud-prevention/class-buyer-fingerprinting-service.php
  tests/unit/fraud-prevention/test-class-buyer-fingerprinting-service.php
Labels: pr: needs review

#5611 Discoverability banner for Fraud & Risk tools
  changelog/add-2785-discover-fraud-risk-tools-banner
  client/components/fraud-risk-tools-banner/components/banner-actions/index.js
  client/components/fraud-risk-tools-banner/components/banner-actions/test/__snapshots__/index.test.js.snap
  client/components/fraud-risk-tools-banner/components/banner-actions/test/index.test.js
  client/components/fraud-risk-tools-banner/components/banner-body/index.js
  client/components/fraud-risk-tools-banner/components/banner-body/test/__snapshots__/index.test.js.snap
  client/components/fraud-risk-tools-banner/components/banner-body/test/index.test.js
  client/components/fraud-risk-tools-banner/components/index.js
  client/components/fraud-risk-tools-banner/components/new-pill/index.js
  client/components/fraud-risk-tools-banner/components/new-pill/test/__snapshots__/index.test.js.snap
  client/components/fraud-risk-tools-banner/components/new-pill/test/index.test.js
  client/components/fraud-risk-tools-banner/index.js
  client/components/fraud-risk-tools-banner/style.scss
  client/components/fraud-risk-tools-banner/test/__snapshots__/index.test.js.snap
  client/components/fraud-risk-tools-banner/test/index.test.js
  client/constants.ts
  client/overview/index.js
  client/overview/test/index.js
  client/settings/settings-manager/index.js
  includes/admin/class-wc-payments-admin.php
Labels: pr: ready to merge

#5679 Added Cancel Confirmation Modal
  changelog/add-5603-cancel-confirmation-modal
  client/order/cancel-confirm-modal/index.js
  client/order/index.js
  client/order/refund-confirm-modal/index.js
  tests/e2e/specs/wcpay/merchant/merchant-orders-status-change.spec.js
Labels: pr: ready to merge

#5834 Fix initial isLoading for deposits overviews data.
  changelog/fix-5812-initial-loading-state
  client/data/deposits/hooks.ts
Labels: pr: ready to merge

#5791 Add progressive onboarding form validation
  changelog/add-5474-po-form-validation
  client/components/form/fields.tsx
  client/components/form/style.scss
  client/components/form/test/fields.tsx
  client/onboarding-prototype/context.tsx
  client/onboarding-prototype/form.tsx
  client/onboarding-prototype/index.tsx
  client/onboarding-prototype/steps/business-details.tsx
  client/onboarding-prototype/steps/personal-details.tsx
  client/onboarding-prototype/steps/store-details.tsx
  client/onboarding-prototype/strings.tsx
  client/onboarding-prototype/test/context.tsx
  client/onboarding-prototype/test/form.tsx
  client/onboarding-prototype/test/validation.ts
  client/onboarding-prototype/utils.ts
  client/onboarding-prototype/validation.ts
  package-lock.json
  package.json
Labels: pr: needs review

#5716 Add welcome tour to fraud protection settings
  assets/images/fraud-protection/tour/enhanced-protection-step.png
  assets/images/fraud-protection/tour/enhanced-protection-step@2x.png
  changelog/add-3083-welcome-tour
  client/components/tour/components/TourContent.tsx
  client/components/tour/provider.tsx
  client/globals.d.ts
  client/settings/fraud-protection/index.js
  client/settings/fraud-protection/test/__snapshots__/index.test.js.snap
  client/settings/fraud-protection/test/index.test.js
  client/settings/fraud-protection/tour/__snapshots__/index.test.tsx.snap
  client/settings/fraud-protection/tour/declarations.d.ts
  client/settings/fraud-protection/tour/index.test.tsx
  client/settings/fraud-protection/tour/index.tsx
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-features.php
Labels: pr: ready to merge

#5685 Add JSON rule builder for the rule engine
  changelog/add-3043-json-generator-for-rule-engine
  client/data/settings/actions.js
  client/data/settings/hooks.js
  client/data/settings/selectors.js
  client/settings/fraud-protection/advanced-settings/cards/address-mismatch.js
  client/settings/fraud-protection/advanced-settings/cards/avs-mismatch.js
  client/settings/fraud-protection/advanced-settings/cards/cvc-verification.js
  client/settings/fraud-protection/advanced-settings/cards/order-velocity.js
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/address-mismatch.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/avs-mismatch.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/cvc-verification.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/order-velocity.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/avs-mismatch.test.js
  client/settings/fraud-protection/advanced-settings/cards/test/cvc-verification.test.js
  client/settings/fraud-protection/advanced-settings/cards/test/order-velocity.test.js
  client/settings/fraud-protection/advanced-settings/constants.js
  client/settings/fraud-protection/advanced-settings/index.js
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/index.test.js.snap
  client/settings/fraud-protection/advanced-settings/test/index.test.js
  client/settings/fraud-protection/advanced-settings/test/utils.test.js
  client/settings/fraud-protection/advanced-settings/utils.js
  client/settings/fraud-protection/components/fp-help-text/index.js
  client/settings/fraud-protection/components/fp-modal/index.js
  client/settings/fraud-protection/components/fp-modal/test/__snapshots__/index.test.js.snap
  client/settings/fraud-protection/components/fp-modal/test/index.test.js
  client/settings/fraud-protection/components/protection-level-modal-notice/index.js
  client/settings/fraud-protection/components/protection-levels/index.js
  client/settings/fraud-protection/components/protection-levels/test/__snapshots__/index.test.js.snap
  client/settings/fraud-protection/components/protection-levels/test/index.test.js
  client/settings/fraud-protection/test/__snapshots__/index.test.js.snap
  client/settings/fraud-protection/test/index.test.js
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments.php
  includes/exceptions/class-fraud-ruleset-exception.php
  includes/fraud-prevention/class-fraud-risk-tools.php
  includes/fraud-prevention/models/class-check.php
  includes/fraud-prevention/models/class-rule.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: ready to merge

#5801 Add userscript for WCPay Live Branch
  .github/workflows/pr-build-live-branch.yml
  bin/wcpay-live-branches/README.md
  bin/wcpay-live-branches/wcpay-live-branches.user.js
  changelog/add-jn-userscript-for-live-branch
Labels: pr: needs review

#5761 Add new workflow to run E2E tests on a test Atomic site
  .github/actions/e2e/atomic-prepare-and-run/action.yml
  .github/actions/e2e/run-log-tests/action.yml
  .github/actions/setup-repo/action.yml
  .github/workflows/e2e-pull-request.yml
  .github/workflows/e2e-test.yml
  .github/workflows/e2e-tests-atomic.yml
  changelog/test-add-atomic-e2e-tests-workflow
  tests/e2e/README.md
  tests/e2e/config/atomic.json
  tests/e2e/config/default.json
  tests/e2e/config/e2e-default.env
  tests/e2e/config/env.setup.js
  tests/e2e/config/jest.config.js
  tests/e2e/config/jest.setup.js
  tests/e2e/config/test.json
  tests/e2e/env/setup.sh
  tests/e2e/env/shared.sh
  tests/e2e/env/wc-subscription-products-atomic.csv
  tests/e2e/specs/subscriptions/merchant/merchant-subscriptions-settings.spec.js
  tests/e2e/specs/wcpay/merchant/merchant-admin-analytics.spec.js
  tests/e2e/specs/wcpay/shopper/shopper-checkout-failures.spec.js
  tests/e2e/specs/wcpay/shopper/shopper-checkout-free-cart.spec.js
  tests/e2e/specs/wcpay/shopper/shopper-pay-for-order.spec.js
  tests/e2e/utils/payments.js
Labels: pr: needs review

#5744 Add Tap to Pay icon on the transactions list page for Tap to Pay transactions
  assets/images/payment-methods/taptopay.svg
  changelog/add-ttp-logo-transactions-page
  client/data/transactions/hooks.ts
  client/transactions/list/index.tsx
  client/transactions/list/style.scss
  client/transactions/list/test/__snapshots__/index.tsx.snap
  client/transactions/list/test/index.tsx
Labels: pr: needs review

#5810 Update the payment details page to reflect the Tap to Pay transactions channel
  changelog/add-transaction-details-channel-ttp
  client/components/page/index.tsx
  client/data/charges/types.d.ts
  client/data/payment-intents/hooks.ts
  client/data/payment-intents/test/hooks.ts
  client/globals.d.ts
  client/payment-details/index.tsx
  client/payment-details/summary/index.tsx
  client/payment-details/summary/test/__snapshots__/index.tsx.snap
  client/payment-details/summary/test/index.tsx
  client/payment-details/types.ts
  client/types/charges.d.ts
Labels: pr: ready to merge

#5847 Fix saving both protection level and settings in one call
  changelog/fix-advanced-settings-not-saving
  client/settings/fraud-protection/advanced-settings/cards/order-items-threshold.js
  client/settings/fraud-protection/advanced-settings/cards/purchase-price-threshold.js
  client/settings/fraud-protection/advanced-settings/cards/test/address-mismatch.test.js
  client/settings/fraud-protection/advanced-settings/cards/test/avs-mismatch.test.js
  client/settings/fraud-protection/advanced-settings/cards/test/cvc-verification.test.js
  client/settings/fraud-protection/advanced-settings/cards/test/international-billing-address.test.js
  client/settings/fraud-protection/advanced-settings/cards/test/international-ip-address.test.js
  client/settings/fraud-protection/advanced-settings/cards/test/order-items-threshold.test.js
  client/settings/fraud-protection/advanced-settings/cards/test/purchase-price-threshold.test.js
  client/settings/fraud-protection/advanced-settings/context.js
  client/settings/fraud-protection/advanced-settings/index.js
  client/settings/fraud-protection/advanced-settings/rule-toggle.js
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/index.test.js.snap
  client/settings/fraud-protection/advanced-settings/test/index.test.js
  client/settings/fraud-protection/advanced-settings/test/rule-toggle.test.js
Labels: pr: ready to merge

#5796 Refactor the `Tooltip` component to use TypeScript
  changelog/dev-ts-refactor-tooltip-component
  client/components/tooltip/index.tsx
  client/components/tooltip/test/index.test.tsx
  client/components/tooltip/test/tooltip-base.test.tsx
  client/components/tooltip/tooltip-base.tsx
Labels: type: task, category: refactor

#5799 [Simplifying Deposits UI] Adds the next deposits table
  changelog/issue-5696-next-deposits-table
  client/components/deposit-status-chip/index.tsx
  client/components/deposit-status-chip/strings.ts
  client/components/deposit-status-chip/style.scss
  client/components/deposits-overview/index.tsx
  client/components/deposits-overview/next-deposit.tsx
  client/components/deposits-overview/strings.ts
  client/components/deposits-overview/style.scss
  client/components/deposits-overview/test/__snapshots__/index.tsx.snap
  client/components/deposits-overview/test/index.tsx
  client/components/deposits-overview/utils.ts
Labels: pr: ready to merge

#5773 Move TypeScript definitions for AccountOverview to sharable location
  changelog/dev-5772-account-overview-type-definitions
  client/deposits/declarations.d.ts
  client/types/account-overview.d.ts
Labels: pr: ready to merge, type: task, category: projects

#5487 Add "Risk review" and "Blocked" tabs to transactions page
  changelog/update-2787-transactions-page
  client/components/chip/index.js
  client/components/test-mode-notice/index.js
  client/components/transaction-status-chip/__snapshots__/index.test.tsx.snap
  client/components/transaction-status-chip/index.test.tsx
  client/components/transaction-status-chip/index.tsx
  client/components/transaction-status-chip/mappings.ts
  client/components/transaction-status-chip/style.scss
  client/data/transactions/action-types.js
  client/data/transactions/actions.js
  client/data/transactions/hooks.ts
  client/data/transactions/reducer.js
  client/data/transactions/resolvers.js
  client/data/transactions/selectors.js
  client/data/transactions/test/reducer.js
  client/data/transactions/test/selectors.js
  client/globals.d.ts
  client/transactions/blocked/columns.tsx
  client/transactions/blocked/index.tsx
  client/transactions/blocked/test/__snapshots__/columns.test.tsx.snap
  client/transactions/blocked/test/columns.test.tsx
  client/transactions/declarations.d.ts
  client/transactions/fraud-protection/autocompleter.tsx
  client/transactions/index.tsx
  client/transactions/risk-review/columns.tsx
  client/transactions/risk-review/index.tsx
  client/transactions/risk-review/style.scss
  client/transactions/risk-review/test/__snapshots__/columns.test.tsx.snap
  client/transactions/risk-review/test/columns.test.tsx
  client/transactions/test/index.tsx
  includes/admin/class-wc-rest-payments-transactions-controller.php
  includes/class-wc-payments.php
  includes/core/server/README.md
  includes/core/server/request/class-list-fraud-outcome-transactions.md
  includes/core/server/request/class-list-fraud-outcome-transactions.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/core/server/request/test-class-list-fraud-outcome-transactions-request.php
Labels: pr: ready to merge

#5837 Use selling locations in international fraud protection filters
  changelog/update-server-3148-international-check-use-core-settings
  client/settings/fraud-protection/advanced-settings/allow-countries-notice.js
  client/settings/fraud-protection/advanced-settings/cards/international-billing-address.js
  client/settings/fraud-protection/advanced-settings/cards/international-ip-address.js
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/international-billing-address.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/international-ip-address.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/address-mismatch.test.js
  client/settings/fraud-protection/advanced-settings/cards/test/avs-mismatch.test.js
  client/settings/fraud-protection/advanced-settings/cards/test/cvc-verification.test.js
  client/settings/fraud-protection/advanced-settings/cards/test/international-billing-address.test.js
  client/settings/fraud-protection/advanced-settings/cards/test/international-ip-address.test.js
  client/settings/fraud-protection/advanced-settings/cards/test/order-items-threshold.test.js
  client/settings/fraud-protection/advanced-settings/cards/test/purchase-price-threshold.test.js
  client/settings/fraud-protection/advanced-settings/constants.js
  client/settings/fraud-protection/advanced-settings/context.js
  client/settings/fraud-protection/advanced-settings/index.js
  client/settings/fraud-protection/advanced-settings/rule-toggle.js
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/allow-countries-notice.test.js.snap
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/index.test.js.snap
  client/settings/fraud-protection/advanced-settings/test/allow-countries-notice.test.js
  client/settings/fraud-protection/advanced-settings/test/index.test.js
  client/settings/fraud-protection/advanced-settings/test/rule-toggle.test.js
  client/settings/fraud-protection/advanced-settings/test/utils.test.js
  client/settings/fraud-protection/advanced-settings/utils.js
  includes/fraud-prevention/class-fraud-risk-tools.php
  includes/fraud-prevention/models/class-check.php
Labels: pr: needs review

#5858 Add fraud settings enabled filter
  changelog/add-3065-demo
  includes/fraud-prevention/class-fraud-risk-tools.php
Labels: pr: ready to merge

#5849 Add footer elements to the new deposits overview card
  changelog/issue-5719-add-deposit-card-footer
  client/components/deposits-overview/footer.tsx
  client/components/deposits-overview/index.tsx
  client/components/deposits-overview/strings.ts
  client/components/deposits-overview/style.scss
  client/components/deposits-overview/test/__snapshots__/index.tsx.snap
  client/components/deposits-overview/test/index.tsx
Labels: pr: ready to merge

#5814 Add BannerNotice component and update FraudProtectionRuleCardNotice to use banner notices.
  changelog/issue-5798-add-banner-notice
  client/components/banner-notice/index.tsx
  client/components/banner-notice/styles.scss
  client/components/banner-notice/tests/__snapshots__/index.test.tsx.snap
  client/components/banner-notice/tests/index.test.tsx
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/avs-mismatch.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/cvc-verification.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/international-billing-address.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/international-ip-address.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/order-items-threshold.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/purchase-price-threshold.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/order-items-threshold.test.js
  client/settings/fraud-protection/advanced-settings/cards/test/purchase-price-threshold.test.js
  client/settings/fraud-protection/advanced-settings/rule-card-notice.js
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/allow-countries-notice.test.js.snap
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/index.test.js.snap
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/rule-card-notice.test.js.snap
  client/settings/fraud-protection/advanced-settings/test/rule-card-notice.test.js
  client/settings/fraud-protection/style.scss
Labels: pr: ready to merge

#5845 Remove the pull_request trigger for Atomic E2E tests workflow
  .github/workflows/e2e-tests-atomic.yml
  changelog/test-remove-pull-request-trigger-atomic-e2e-tests
Labels: pr: ready to merge

#5867 Update test mode notice for uncaptured authorizations tab
  changelog/update-5181-uncaptured-tab-test-mode-notice
  client/components/test-mode-notice/index.js
Labels: pr: ready to merge

#5868 Add order support for payment details
  changelog/add-3167-order-payment-details
  client/data/charges/hooks.ts
  client/data/charges/resolvers.js
  client/data/charges/selectors.js
  client/data/charges/test/hooks.ts
  client/data/charges/test/reducer.ts
  client/data/charges/test/resolvers.ts
  client/data/charges/test/selectors.ts
  client/data/payment-intents/test/hooks.ts
  client/payment-details/charge-details/index.tsx
  client/payment-details/index.tsx
  client/payment-details/order-details/index.tsx
  client/payment-details/order-details/test/__snapshots__/index.test.tsx.snap
  client/payment-details/order-details/test/index.test.tsx
  client/payment-details/payment-details/index.tsx
  client/payment-details/payment-method/card/index.js
  client/payment-details/summary/index.tsx
  client/transactions/blocked/columns.tsx
  client/transactions/blocked/test/__snapshots__/columns.test.tsx.snap
  client/utils/charge/index.ts
  includes/admin/class-wc-rest-payments-charges-controller.php
  includes/fraud-prevention/class-fraud-risk-tools.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/fraud-prevention/test-class-fraud-risk-tools.php
Labels: pr: needs review

#5866 Remove the "Reserve" funds balance block
  changelog/issue-5865-remove-reserved-funds-section
  client/components/account-balances/balance-block.tsx
  client/components/account-balances/balances-tab-panel.tsx
  client/components/account-balances/strings.ts
  client/components/account-balances/style.scss
  client/components/account-balances/test/__snapshots__/index.test.tsx.snap
Labels: pr: ready to merge

#5782 Add order handling for fraud outcomes
  .prettierignore
  assets/css/admin.css
  assets/images/icons/check-green.svg
  assets/images/icons/shield-stroke-orange.svg
  assets/images/icons/shield-stroke-red.svg
  changelog/add-2794-fraud-order-details-updates-after-order-service-update
  client/components/transaction-status-chip/style.scss
  docs/metadata.md
  includes/admin/class-wc-rest-payments-orders-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-order-service.php
  includes/class-wc-payments-utils.php
  includes/class-wc-payments-webhook-processing-service.php
  includes/class-wc-payments.php
  includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php
  includes/constants/class-fraud-meta-box-type.php
  includes/exceptions/class-order-not-found-exception.php
  includes/fraud-prevention/class-order-fraud-and-risk-meta-box.php
  includes/fraud-prevention/models/class-rule.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/subscriptions/class-wc-payments-invoice-service.php
  includes/subscriptions/class-wc-payments-subscriptions-event-handler.php
  tests/unit/admin/test-class-wc-rest-payments-orders-controller.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
  tests/unit/payment-methods/test-class-upe-split-payment-gateway.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-order-service.php
  tests/unit/test-class-wc-payments-webhook-processing-service.php
Labels: pr: needs review

#5896 Replace custom tour component with TourKit from @woocommerce/components
  assets/images/fraud-protection/tour/enhanced-protection-step.png
  assets/images/fraud-protection/tour/enhanced-protection-step@2x.png
  changelog/update-3136-welcome-tour
  client/components/tour/components/TourContent.tsx
  client/components/tour/components/TourFooter.tsx
  client/components/tour/components/TourImage.tsx
  client/components/tour/components/TourNextButton.tsx
  client/components/tour/components/TourPreviousButton.tsx
  client/components/tour/components/TourStep.tsx
  client/components/tour/components/index.tsx
  client/components/tour/context.tsx
  client/components/tour/index.tsx
  client/components/tour/interfaces.ts
  client/components/tour/provider.tsx
  client/components/tour/style.scss
  client/components/tour/test/__snapshots__/index.test.tsx.snap
  client/components/tour/test/index.test.tsx
  client/components/tour/utils.tsx
  client/deposits/declarations.d.ts
  client/settings/fraud-protection/test/__snapshots__/index.test.js.snap
  client/settings/fraud-protection/test/index.test.js
  client/settings/fraud-protection/tour/__snapshots__/index.test.tsx.snap
  client/settings/fraud-protection/tour/index.test.tsx
  client/settings/fraud-protection/tour/index.tsx
  client/settings/fraud-protection/tour/steps.tsx
Labels: pr: needs review

#5871 Add fraud and risk tools discoverability banner to WooCommerce Core Home page
  changelog/add-server-3135-fraud-risk-tools-discoverability-banner-on-wc-home
  client/components/fraud-risk-tools-banner/index.js
Labels: pr: needs review

#5894 Minor update for platform docs
  changelog/update-platforom-docs-example
  includes/core/server/CONTRIBUTING.md
Labels: pr: needs review

#5862 Add ClickTooltip and HoverTooltip components to improve mobile UX
  changelog/add-5851-add-click-only-tooltip-component-for-tooltips-with-links-to-improve-ux
  client/components/loadable-checkbox/index.js
  client/components/payment-methods-checkboxes/payment-method-checkbox.js
  client/components/payment-methods-list/payment-method.js
  client/components/tooltip/index.tsx
  client/components/tooltip/style.scss
  client/components/tooltip/test/index.test.tsx
  client/settings/express-checkout/index.js
  client/settings/fraud-protection/advanced-settings/rule-toggle.js
  client/transactions/list/index.tsx
Labels: type: enhancement, pr: needs review, category: core

#5875 Sort uncaptured transactions to show older first
  changelog/fix-5183-sort-uncaptured-transactions
  client/data/authorizations/hooks.ts
  client/data/authorizations/resolvers.ts
  client/transactions/uncaptured/index.tsx
  client/transactions/uncaptured/test/__snapshots__/index.test.tsx.snap
  client/transactions/uncaptured/test/index.test.tsx
Labels: pr: ready to merge

#5918 Revert "Add fraud and risk tools discoverability banner to WooCommerce Core Home page"
  changelog/add-server-3135-fraud-risk-tools-discoverability-banner-on-wc-home
  client/components/fraud-risk-tools-banner/index.js
Labels: pr: needs review

#5900 Fraud & Risk tools improvements from feedback
  changelog/update-3181-demo-feedback
  client/components/fraud-risk-tools-banner/style.scss
  client/data/authorizations/actions.ts
  client/data/authorizations/test/actions.test.ts
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/address-mismatch.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/international-billing-address.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/international-ip-address.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/order-items-threshold.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/purchase-price-threshold.test.js.snap
  client/settings/fraud-protection/advanced-settings/index.js
  client/settings/fraud-protection/advanced-settings/rule-toggle.js
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/index.test.js.snap
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/rule-toggle.test.js.snap
  client/settings/fraud-protection/advanced-settings/test/index.test.js
  client/settings/fraud-protection/style.scss
  client/transactions/fraud-protection/autocompleter.tsx
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-order-service.php
  includes/constants/class-fraud-meta-box-type.php
  includes/core/server/request/class-list-fraud-outcome-transactions.php
  includes/fraud-prevention/class-order-fraud-and-risk-meta-box.php
  tests/unit/fraud-prevention/test-class-fraud-risk-tools.php
  tests/unit/test-class-wc-payments-order-service.php
Labels: pr: ready to merge

#5864 Fix overview screen type error when the account has no deposit scheduled
  changelog/fix-5863-account-overview-nextScheduled-typeerror
  client/components/account-balances/balances-tab-panel.tsx
  client/components/deposits-information/index.tsx
  client/components/deposits-overview/test/index.tsx
  client/components/deposits-overview/utils.ts
  client/types/account-overview.d.ts
Labels: pr: needs review, category: projects

#5857 Prefill data from onboarding for in case of non-progressive Stripe KYC
  changelog/add-5476-prefill-fields-for-full-stripe-kyc
  client/onboarding-prototype/steps/loading.tsx
  client/onboarding-prototype/steps/test/loading.tsx
  includes/class-wc-payments-account.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: ready to merge

#5935 Apply latest rule defaults and fix modals
  changelog/fix-adapt-latest-fraud-tools-defaults-and-modals
  client/settings/fraud-protection/components/fp-modal/index.js
  client/settings/fraud-protection/components/fp-modal/test/__snapshots__/index.test.js.snap
  client/settings/fraud-protection/components/index.js
  client/settings/fraud-protection/components/protection-level-modal-notice/index.js
  client/settings/fraud-protection/components/protection-levels/index.js
  client/settings/fraud-protection/components/protection-levels/test/__snapshots__/index.test.js.snap
  client/settings/fraud-protection/test/__snapshots__/index.test.js.snap
  includes/fraud-prevention/class-fraud-risk-tools.php
  tests/unit/fraud-prevention/test-class-fraud-risk-tools.php
Labels: pr: needs review

#5926 Add store currency support to purchase price threshold filter
  changelog/add-3195-purchase-price-threshold-store-currency
  client/settings/fraud-protection/advanced-settings/cards/purchase-price-threshold.js
  client/settings/fraud-protection/advanced-settings/cards/test/purchase-price-threshold.test.js
  client/settings/fraud-protection/advanced-settings/test/index.test.js
  client/settings/fraud-protection/advanced-settings/test/utils.test.js
  client/settings/fraud-protection/advanced-settings/utils.js
  includes/admin/class-wc-payments-admin.php
  includes/fraud-prevention/class-fraud-risk-tools.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/fraud-prevention/test-class-fraud-risk-tools.php
Labels: pr: ready to merge
