Repository Automattic/woocommerce-payments, pull requests merged in 2023-08, with the labels that each got.

#6879 Prefill Business Name and Country Fields
  changelog/dev-6878-prefill-po-fields
  client/onboarding/index.tsx
Labels: pr: ready to merge

#6805 RPP: Create a payment service class
  changelog/rpp-6674-create-payment-service-class
  phpcs.xml.dist
  src/Internal/Service/PaymentProcessingService.php
  src/index.php
  tasks/release.js
Labels: pr: ready to merge

#6856 RPP: Add autoloader
  changelog/rpp-6677-psr-autoloader
  composer.json
  tests/unit/src/Internal/Service/PaymentProcessingServiceTest.php
Labels: pr: ready to merge

#6894 Don't show the congratulations modal if user is in test mode.
  changelog/dev-test-mode-update
  client/overview/connection-sucess-notice.tsx
Labels: pr: ready to merge

#6830 Fixes related to test mode prompt style and copy
  changelog/dev-6778-fix-copy-test-mode
  client/onboarding/strings.tsx
  client/overview/setup-real-payments.tsx
  client/overview/test/index.js
  client/overview/test/setup-real-payments.test.tsx
Labels: pr: needs review, pr: needs design review

#6873 Add constant flag to use the new payment service
  changelog/rpp-6675-use-payment-service
  includes/class-wc-payment-gateway-wcpay.php
  src/Internal/Service/PaymentProcessingService.php
Labels: pr: ready to merge

#6822 Allow users with a migrated WCPay Subscription to pay for a failed renewal order
  changelog/fix-6812
  includes/subscriptions/class-wc-payments-subscription-change-payment-method-handler.php
  tests/unit/subscriptions/test-class-wc-payments-subscription-change-payment-method.php
Labels: pr: needs review

#6896 Only show the Fraud & Risk tour if the user clicked on the "Learn more" button
  changelog/fix-6887-only-show-frt-tour-from-learn-more-button-click
  client/settings/fraud-protection/test/index.test.tsx
  client/settings/fraud-protection/tour/__snapshots__/index.test.tsx.snap
  client/settings/fraud-protection/tour/index.test.tsx
  client/settings/fraud-protection/tour/index.tsx
Labels: pr: ready to merge

#6918 Revert "BNPLs: updated methods copy on settings page (#6880)"
  changelog/revert-6799-bnpl-methods-copy-in-settings-page
  changelog/update-6799-bnpl-methods-copy-in-settings-page
  client/additional-methods-setup/upe-preview-methods-selector/test/add-payment-methods-task.test.js
  client/components/payment-methods-checkboxes/payment-method-checkbox.tsx
  client/data/settings/hooks.js
  client/data/settings/selectors.js
  client/payment-methods-map.tsx
  client/payment-methods/index.js
  client/payment-methods/test/index.js
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
Labels: pr: needs review

#6921 Update readme.txt to improve plugin ranking in WP.org
  changelog/tweak-update-readme-for-wp-org
  readme.txt
Labels: pr: needs review

#6897 Add RTL support script for webpack
  changelog/add-rtl-support
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-blocks-payment-method.php
  includes/class-wc-payments-checkout.php
  includes/class-wc-payments-order-success-page.php
  includes/class-wc-payments-upe-blocks-payment-method.php
  includes/class-wc-payments-upe-checkout.php
  includes/class-wc-payments-utils.php
  includes/class-wc-payments-woopay-button-handler.php
  includes/multi-currency/MultiCurrency.php
  includes/subscriptions/class-wc-payments-subscriptions-empty-state-manager.php
  includes/subscriptions/class-wc-payments-subscriptions-onboarding-handler.php
  includes/subscriptions/class-wc-payments-subscriptions-plugin-notice-manager.php
  includes/woopay-user/class-woopay-save-user.php
  package-lock.json
  package.json
  webpack/shared.js
Labels: pr: ready to merge

#6932 Remove wrong changelog file introduced in previous revert commit.
  changelog/dev-6799-remove-changelog-after-revert
  changelog/revert-6799-bnpl-methods-copy-in-settings-page
Labels: pr: ready to merge

#6905 Add JCB as a coming soon to the list of available payment methods
  assets/images/payment-methods/jcb.svg
  changelog/add-jcb-payment-method
  client/additional-methods-setup/constants.js
  client/components/loadable-checkbox/index.js
  client/components/payment-methods-list/payment-method.tsx
  client/components/tooltip/tooltip-base.tsx
  client/payment-methods-map.tsx
  client/payment-methods/constants.ts
  client/payment-methods/index.js
  client/types/payment-methods.d.ts
  includes/class-wc-payments.php
  includes/constants/class-payment-method.php
  includes/payment-methods/class-jcb-payment-method.php
  includes/payment-methods/class-upe-payment-gateway.php
Labels: pr: ready to merge

#6862 RPP: Dependency Container
  .gitignore
  changelog/rpp-6678-dependency-container
  composer.json
  composer.lock
  includes/class-wc-payment-gateway-wcpay.php
  lib/README.md
  lib/composer.json
  lib/composer.lock
  lib/packages/League/Container/Argument/ArgumentInterface.php
  lib/packages/League/Container/Argument/ArgumentResolverInterface.php
  lib/packages/League/Container/Argument/ArgumentResolverTrait.php
  lib/packages/League/Container/Argument/DefaultValueArgument.php
  lib/packages/League/Container/Argument/DefaultValueInterface.php
  lib/packages/League/Container/Argument/Literal/ArrayArgument.php
  lib/packages/League/Container/Argument/Literal/BooleanArgument.php
  lib/packages/League/Container/Argument/Literal/CallableArgument.php
  lib/packages/League/Container/Argument/Literal/FloatArgument.php
  lib/packages/League/Container/Argument/Literal/IntegerArgument.php
  lib/packages/League/Container/Argument/Literal/ObjectArgument.php
  lib/packages/League/Container/Argument/Literal/StringArgument.php
  lib/packages/League/Container/Argument/LiteralArgument.php
  lib/packages/League/Container/Argument/LiteralArgumentInterface.php
  lib/packages/League/Container/Argument/ResolvableArgument.php
  lib/packages/League/Container/Argument/ResolvableArgumentInterface.php
  lib/packages/League/Container/Container.php
  lib/packages/League/Container/ContainerAwareInterface.php
  lib/packages/League/Container/ContainerAwareTrait.php
  lib/packages/League/Container/Definition/Definition.php
  lib/packages/League/Container/Definition/DefinitionAggregate.php
  lib/packages/League/Container/Definition/DefinitionAggregateInterface.php
  lib/packages/League/Container/Definition/DefinitionInterface.php
  lib/packages/League/Container/DefinitionContainerInterface.php
  lib/packages/League/Container/Exception/ContainerException.php
  lib/packages/League/Container/Exception/NotFoundException.php
  lib/packages/League/Container/Inflector/Inflector.php
  lib/packages/League/Container/Inflector/InflectorAggregate.php
  lib/packages/League/Container/Inflector/InflectorAggregateInterface.php
  lib/packages/League/Container/Inflector/InflectorInterface.php
  lib/packages/League/Container/ReflectionContainer.php
  lib/packages/League/Container/ServiceProvider/AbstractServiceProvider.php
  lib/packages/League/Container/ServiceProvider/BootableServiceProviderInterface.php
  lib/packages/League/Container/ServiceProvider/ServiceProviderAggregate.php
  lib/packages/League/Container/ServiceProvider/ServiceProviderAggregateInterface.php
  lib/packages/League/Container/ServiceProvider/ServiceProviderInterface.php
  phpcs.xml.dist
  src/Container.php
  src/Internal/DependencyManagement/AbstractServiceProvider.php
  src/Internal/DependencyManagement/ContainerException.php
  src/Internal/DependencyManagement/DelegateContainer/WooContainer.php
  src/Internal/DependencyManagement/ExtendedContainer.php
  src/Internal/DependencyManagement/ServiceProvider/PaymentsServiceProvider.php
  src/README.md
  src/wcpay-get-container.php
  tests/unit/bootstrap.php
  tests/unit/src/ContainerTest.php
  woocommerce-payments.php
Labels: pr: needs review

#6909 Remove Daily options from payout dropdown
  changelog/remove-daily-deposits-for-jp-merchants
  client/settings/deposits/index.js
  client/settings/deposits/test/index.test.js
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-wc-payment-gateway-wcpay.php
Labels: pr: needs review

#6901 Resolve legacy card initialization issue for cart with subscription products in split UPE
  changelog/fix-card-gateway-with-woopay-and-subscriptions
  includes/payment-methods/class-upe-split-payment-gateway.php
  tests/unit/payment-methods/test-class-upe-split-payment-gateway.php
Labels: priority: high

#6825 Use shared utility function when comparing dispute `due_by` dates to improve code quality
  changelog/dev-share-dispute-due-by-comparison-logic
  client/overview/task-list/tasks/dispute-task.tsx
Labels: pr: ready to merge

#6945 Euro is displayed as zero-decimal currency for Japanese accounts
  changelog/fix-euro-displayed-as-zerodecimal-currency-for-japan
  client/utils/currency/index.js
Labels: pr: ready to merge

#6876 RPP: Legacy Container
  changelog/add-6707-container-additions
  src/Container.php
  src/Internal/DependencyManagement/DelegateContainer/LegacyContainer.php
  src/Internal/DependencyManagement/DelegateContainer/REAMDE.md
  src/Internal/DependencyManagement/ServiceProvider/PaymentsServiceProvider.php
  src/Internal/Service/ExampleService.php
  src/Internal/Service/ExampleServiceWithDependencies.php
  src/README.md
  tests/unit/src/ContainerTest.php
  tests/unit/src/Internal/DependencyManagement/DelegateContainer/LegacyContainerTest.php
Labels: pr: needs review

#6939 Fix Woopay Button Logo Cut Off in Certain Views
  changelog/fix-woopay-6263-button-logo-cutoff
  client/checkout/woopay/express-button/woopay-express-checkout-button.js
  client/checkout/woopay/style.scss
Labels: type: bug, priority: high, component: WooPay, GA Blocker, needs demo

#6947 Show empty dispute details component on Transaction Details page
  changelog/add-6886-dispute-details-on-transasction-details-page
  client/globals.d.ts
  client/payment-details/dispute-details/index.tsx
  client/payment-details/dispute-details/style.scss
  client/payment-details/summary/index.tsx
  client/settings/wcpay-settings-context.js
  includes/class-wc-payments-features.php
Labels: pr: ready to merge

#6969 Fix improperly rendered payment method brand images on Transaction screens
  assets/css/admin.css
  changelog/fix-payment-method-brand-images
Labels: pr: ready to merge

#6959 Use botwoo for pushing the release changelog changes using the related GitHub workflow
  .github/workflows/release-changelog.yml
  changelog/add-use-botwoo-for-release-changelog
Labels: pr: ready to merge

#6936 Remove Order Meta Helper tool toggle, and add url parameter to enable tool
  changelog/fix-6395-move-meta-helper-behind-url-param
  includes/class-wc-payments-features.php
  includes/multi-currency/Helpers/OrderMetaHelper.php
Labels: pr: needs review

#6954 RPP: Add Psalm exception handling to src
  changelog/add-psalm-exceptions-to-src
  includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php
  includes/subscriptions/class-wc-payments-invoice-service.php
  includes/subscriptions/class-wc-payments-subscriptions-event-handler.php
  psalm.xml
  src/Internal/Service/ExampleService.php
  src/Internal/Service/ExampleServiceWithDependencies.php
  tests/unit/test-class-wc-payments-order-service.php
Labels: pr: needs review

#5980 Fix the intro of the customer service doc
  changelog/fix-customer-service-md
  includes/core/service/customer-service.md
Labels: pr: needs review

#6920 BNPLs: updated methods copy on settings page (part II)
  changelog/update-6799-bnpl-methods-copy-in-settings-page-bis
  client/additional-methods-setup/upe-preview-methods-selector/test/add-payment-methods-task.test.js
  client/components/payment-methods-checkboxes/payment-method-checkbox.tsx
  client/data/settings/hooks.js
  client/data/settings/selectors.js
  client/payment-methods-map.tsx
  client/payment-methods/index.js
  client/payment-methods/test/index.js
  client/utils/payment-methods.tsx
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/payment-methods/class-upe-split-payment-gateway.php
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
  tests/unit/admin/test-class-wc-rest-payments-tos-controller.php
  tests/unit/admin/test-class-wc-rest-upe-flag-toggle-controller.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
  tests/unit/payment-methods/test-class-upe-split-payment-gateway.php
  tests/unit/test-class-wc-payment-gateway-wcpay-payment-types.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-refund.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-payment-method-order-note.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-express-checkout-button-display-handler.php
  tests/unit/test-class-wc-payments-payment-request-button-handler.php
  tests/unit/test-class-wc-payments-woopay-button-handler.php
Labels: pr: ready to merge

#6796 Update Chip component styles with wp-admin colors
  changelog/update-6794-chip-component
  client/account-status-settings/test/__snapshots__/index.js.snap
  client/components/account-status/status-chip.js
  client/components/account-status/test/__snapshots__/index.js.snap
  client/components/chip/index.tsx
  client/components/chip/style.scss
  client/components/chip/test/__snapshots__/index.test.tsx.snap
  client/components/chip/test/index.test.tsx
  client/components/dispute-status-chip/index.tsx
  client/components/dispute-status-chip/mappings.ts
  client/components/dispute-status-chip/test/__snapshots__/index.test.tsx.snap
  client/components/payment-status-chip/mappings.js
  client/components/payment-status-chip/test/__snapshots__/index.js.snap
  client/components/transaction-status-chip/__snapshots__/index.test.tsx.snap
  client/components/transaction-status-chip/index.tsx
  client/components/transaction-status-chip/mappings.ts
  client/components/transaction-status-chip/style.scss
  client/disputes/details/test/__snapshots__/index.tsx.snap
  client/disputes/test/__snapshots__/index.tsx.snap
  client/payment-details/summary/test/__snapshots__/index.tsx.snap
  client/payment-details/test/__snapshots__/index.test.tsx.snap
  client/stylesheets/abstracts/_colors.scss
  client/stylesheets/abstracts/_variables.scss
Labels: pr: ready to merge

#6820 Change DepositStatusPill to use Chip component
  changelog/update-6818-deposit-status-chip-component
  client/components/deposit-status-chip/index.tsx
  client/components/deposit-status-chip/test/index.test.tsx
  client/components/deposit-status-pill/index.tsx
  client/components/deposit-status-pill/test/index.test.tsx
  client/components/deposits-overview/next-deposit.tsx
  client/components/deposits-overview/recent-deposits-list.tsx
  client/components/deposits-overview/test/__snapshots__/index.tsx.snap
  client/deposits/list/index.tsx
  client/deposits/list/test/__snapshots__/index.tsx.snap
Labels: pr: ready to merge

#6331 Fix Multi-Currency switcher support in WooPay
  changelog/fix-invalid-currency-from-store-api-request
  includes/woopay/class-woopay-session.php
Labels: pr: ready to merge

#6988 Add dispute object to DisputeDetails component
  changelog/add-6987-dispute-component
  client/payment-details/dispute-details/index.tsx
  client/payment-details/dispute-details/style.scss
  client/payment-details/summary/index.tsx
Labels: pr: ready to merge

#6968 Fix: Javascript not loading on order screens with HPOS enabled
  changelog/fix-6967-order-screen-js
  includes/admin/class-wc-payments-admin.php
  includes/multi-currency/MultiCurrency.php
Labels: pr: ready to merge

#6973 Added Transactions Reporting API
  changelog/add-6342-reports-transactions-api
  includes/class-wc-payments.php
  includes/reports/class-wc-rest-payments-reports-transactions-controller.php
  tests/unit/admin/test-class-wc-rest-payments-reports-transactions-controller.php
  tests/unit/bootstrap.php
Labels: pr: ready to merge

#7010 Display onboarding MCC field validation error
  changelog/fix-6813-mcc-field-validation
  client/components/form/fields.tsx
  client/components/form/style.scss
  client/components/form/test/fields.tsx
  client/onboarding/form.tsx
  client/onboarding/style.scss
Labels: pr: ready to merge

#7018 Add the lib folder to release build
  changelog/add-lib-folder-to-release-build
  tasks/release.js
Labels: pr: ready to merge

#6983 Updated payment method tooltip in settings page
  changelog/imp-6428-improve-settings-mobile-view-tooltip
  client/payment-methods/style.scss
Labels: pr: ready to merge

#7011 Improved and updated copy for credit card payment method in settings
  changelog/imp-6428-improve-settings-mobile-view-credit-card
  client/components/payment-methods-checkboxes/test/index.test.tsx
  client/payment-methods-map.tsx
  client/payment-methods/test/__snapshots__/activation-modal.test.js.snap
  client/payment-methods/test/__snapshots__/delete-modal.test.js.snap
  client/payment-methods/test/index.js
Labels: pr: ready to merge

#6970 Fix disputes related wording.
  changelog/fix-6803-disputes-wording
  client/disputes/utils.ts
  client/order/index.js
  client/settings/settings-manager/index.js
Labels: pr: ready to merge, component: disputes, category: projects

#7027 Check if store is connected to Stripe account before fetching disputes for WooCommerce home task
  changelog/fix-check-if-conneced-wc-home-disputes-task
  includes/class-wc-payments-tasks.php
Labels: pr: ready to merge

#6957 Change Payment_Intent_Status to Intent_Status
  changelog/refactor-6773-intent-status
  includes/admin/class-wc-rest-payments-orders-controller.php
  includes/admin/class-wc-rest-payments-reader-controller.php
  includes/class-duplicate-payment-prevention-service.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-order-service.php
  includes/class-wc-payments.php
  includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php
  includes/constants/class-intent-status.php
  includes/constants/class-payment-intent-status.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/admin/test-class-wc-rest-payments-orders-controller.php
  tests/unit/admin/test-class-wc-rest-payments-readers-controller.php
  tests/unit/helpers/class-wc-helper-intention.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
  tests/unit/payment-methods/test-class-upe-split-payment-gateway.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-refund.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-order-service.php
  tests/unit/test-class-wc-payments-webhook-processing-service.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: ready to merge

#7019 Fix onboarding text fields autofill validation
  .eslintrc
  changelog/fix-text-fields-autofill-validation
  client/components/form/fields.tsx
  client/onboarding/form.tsx
  client/onboarding/test/form.tsx
Labels: pr: needs review

#6999 Update click tooltip styles to match design library
  changelog/fix-6917-click-tooltip-styles
  client/account-status-settings/test/__snapshots__/index.js.snap
  client/components/account-balances/balance-tooltip.tsx
  client/components/account-balances/style.scss
  client/components/tooltip/index.tsx
  client/components/tooltip/style.scss
Labels: pr: needs review, pr: needs design review

#7021 RPP: Full test coverage for src
  changelog/rpp-src-100-percent-coverage
  phpunit.xml.dist
  src/Internal/DependencyManagement/ExtendedContainer.php
  src/Internal/Service/ExampleServiceWithDependencies.php
  src/Internal/Service/PaymentProcessingService.php
  tests/unit/src/ContainerTest.php
  tests/unit/src/Internal/DependencyManagement/DelegateContainer/LegacyContainerTest.php
  tests/unit/src/Internal/DependencyManagement/DelegateContainer/WooContainerTest.php
  tests/unit/src/Internal/DependencyManagement/ExtendedContainerTest.php
  tests/unit/src/Internal/Service/ExampleServiceWithDependenciesTest.php
  tests/unit/src/Internal/Service/PaymentProcessingServiceTest.php
Labels: pr: needs review

#6934 Add onboarding flow state persistence
  changelog/add-5477-onboarding-progress-persistence
  client/components/stepper/index.tsx
  client/components/stepper/test/test.tsx
  client/globals.d.ts
  client/onboarding/index.tsx
  client/onboarding/restored-state-banner.tsx
  client/onboarding/step.tsx
  client/onboarding/strings.tsx
  client/onboarding/style.scss
  client/onboarding/utils.ts
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-onboarding-controller.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-onboarding-service.php
  tests/unit/admin/test-class-wc-rest-payments-onboarding-controller.php
  tests/unit/test-class-wc-payments-onboarding-service.php
Labels: pr: needs design review

#6984 Update express checkouts section in settings for mobile view
  changelog/imp-6428-improve-settings-mobile-view-express-checkouts
  client/settings/express-checkout/apple-google-pay-item.js
  client/settings/express-checkout/apple-google-pay-item.tsx
  client/settings/express-checkout/interfaces.ts
  client/settings/express-checkout/link-item.js
  client/settings/express-checkout/style.scss
  client/settings/express-checkout/woopay-item.js
Labels: pr: ready to merge

#7022 Update to disable enabling APMs (except card payments) for PO users
  changelog/update-disable-apms-po
  client/additional-methods-setup/upe-preview-methods-selector/add-payment-methods-task.js
  client/additional-methods-setup/upe-preview-methods-selector/add-payment-methods-task.scss
  client/components/payment-methods-list/payment-method.tsx
  client/components/payment-methods-list/test/payment-method.test.tsx
  client/globals.d.ts
  client/payment-methods/index.js
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-account.php
Labels: pr: ready to merge

#7045 Cleanup explat wcpay_empty_state_preview_mode_v5
  changelog/update-255-cleanup-explat-wcpay_empty_state_preview_mode_v5
  client/deposits/index.js
  client/empty-state-table/index.tsx
  client/empty-state-table/list.tsx
  client/empty-state-table/style.scss
  client/empty-state-table/test/__snapshots__/index.tsx.snap
  client/empty-state-table/test/index.tsx
  client/transactions/index.tsx
  includes/admin/class-wc-payments-admin.php
Labels: pr: ready to merge

#7028 Add `is_test_mode` to every JS track event
  changelog/dev-track-events-test-mode
  client/globals.d.ts
  client/tracks/index.js
Labels: pr: needs review

#7031 Remove precision overriding
  changelog/remove-precision-overriding
  client/utils/currency/index.js
Labels: pr: needs review

#7024 Fix incorrect order notes for zero-decimal currencies
  changelog/fix-zero-decimal-in-order-notes
  client/payment-details/timeline/test/captured-event-strings.js
  includes/class-wc-payments-captured-event-note.php
  includes/class-wc-payments-utils.php
  tests/fixtures/captured-payments/jpy-payment.json
  tests/unit/test-class-wc-payments-utils.php
Labels: pr: ready to merge

#7013 Add `is_user_connected()` and `get_connected_user_data()` methods to `WC_Payments_Http_Interface`
  changelog/6997-public-methods-of-wc_payments_http-class-being-used-without-being-a-part-of-the-wc_payments_http_interface
  includes/wc-payment-api/class-wc-payments-http-interface.php
Labels: pr: needs review

#7020 RPP - Add interface and concrete classes for Payment Method
  changelog/rpp-6681-add-payment-method-interface
  src/Internal/Payment/PaymentMethod/NewPaymentMethod.php
  src/Internal/Payment/PaymentMethod/PaymentMethodInterface.php
  src/Internal/Payment/PaymentMethod/SavedPaymentMethod.php
  tests/unit/src/Internal/Payment/PaymentMethod/NewPaymentMethodTest.php
  tests/unit/src/Internal/Payment/PaymentMethod/SavedPaymentMethodTest.php
Labels: pr: ready to merge

#7046 Add typescript guidelines
  changelog/add-typescript-guidelines
  docs/typescript/README.md
  docs/typescript/declaring-types.md
  docs/typescript/interface-vs-type.md
  docs/typescript/react-components.md
  docs/typescript/utility-and-manipulation.md
Labels: pr: needs review, type: documentation

#7041 Fix incorrect condition for domestic country check in checkout
  changelog/fix-6971-incorrect-condition-for-domestic-country-check
  includes/payment-methods/class-upe-payment-gateway.php
  includes/payment-methods/class-upe-payment-method.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
  tests/unit/payment-methods/test-class-upe-split-payment-gateway.php
Labels: pr: ready to merge

#6998 Disputes: Add dispute notice to transactions page
  changelog/add-6923-dispute-details-notice
  client/components/dispute-status-chip/index.tsx
  client/disputes/index.tsx
  client/disputes/strings.ts
  client/disputes/utils.ts
  client/order/index.js
  client/payment-details/dispute-details/dispute-notice.tsx
  client/payment-details/dispute-details/index.tsx
  client/payment-details/dispute-details/style.scss
Labels: pr: ready to merge, component: disputes, category: projects

#7072 Update multi currency documentation links
  changelog/update-6186-mc-settings-links
  client/multi-currency/multi-currency-settings/enabled-currencies-list/index.js
  client/multi-currency/multi-currency-settings/enabled-currencies-list/test/__snapshots__/index.js.snap
  client/multi-currency/multi-currency-settings/store-settings/index.js
  client/multi-currency/multi-currency-settings/store-settings/test/__snapshots__/index.test.js.snap
  client/multi-currency/single-currency-settings/index.js
  includes/multi-currency/SettingsOnboardCta.php
Labels: pr: ready to merge

#6832 Fix Currency Switcher Block flag rendering on Windows platform
  changelog/fix-6192-currency-switcher-block-on-windows
  client/multi-currency/blocks/currency-switcher.js
Labels: pr: ready to merge

#7064 Update Base_Constant to return the singleton object for same static calls
  changelog/update-base-constant-return-same-object-static-call
  includes/constants/class-base-constant.php
  tests/unit/test-class-base-constant.php
Labels: pr: ready to merge, status: blocked

#7054 RPP - Payment request class for loading, sanitizing, and escaping data
  changelog/rpp-6684-request-class
  src/Internal/Payment/PaymentRequest.php
  tests/unit/src/Internal/Payment/PaymentRequestTest.php
Labels: pr: ready to merge

#7078 Update inline notice component
  changelog/update-7048-inline-notice-component
  client/components/banner-notice/index.tsx
  client/components/banner-notice/tests/__snapshots__/index.test.tsx.snap
  client/components/currency-information-for-methods/index.js
  client/components/deposits-overview/next-deposit.tsx
  client/components/deposits-overview/recent-deposits-list.tsx
  client/components/deposits-overview/style.scss
  client/components/deposits-overview/suspended-deposit-notice.tsx
  client/components/deposits-overview/test/__snapshots__/index.tsx.snap
  client/components/error-boundary/index.js
  client/components/inline-notice/index.tsx
  client/components/inline-notice/style.scss
  client/components/inline-notice/styles.scss
  client/components/inline-notice/tests/__snapshots__/index.test.tsx.snap
  client/components/inline-notice/tests/index.test.tsx
  client/onboarding/restored-state-banner.tsx
  client/onboarding/steps/personal-details.tsx
  client/onboarding/style.scss
  client/order/index.js
  client/order/style.scss
  client/payment-details/dispute-details/dispute-notice.tsx
  client/payment-details/dispute-details/index.tsx
  client/payment-details/dispute-details/style.scss
  client/settings/disable-upe-modal/index.js
  client/settings/express-checkout-settings/payment-request-button-preview.js
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/cvc-verification.test.tsx.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/international-ip-address.test.tsx.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/order-items-threshold.test.tsx.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/purchase-price-threshold.test.tsx.snap
  client/settings/fraud-protection/advanced-settings/rule-card-notice.tsx
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/allow-countries-notice.test.tsx.snap
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/index.test.tsx.snap
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/rule-card-notice.test.tsx.snap
  client/settings/fraud-protection/components/protection-levels/index.tsx
  client/settings/fraud-protection/components/protection-levels/test/__snapshots__/index.test.tsx.snap
  client/settings/fraud-protection/style.scss
  client/settings/survey-modal/index.js
Labels: pr: needs review

#7084 Fix Multi-currency exchange rate date formatting when using custom date or time settings
  changelog/fix-6183-exchange-date
  client/multi-currency/single-currency-settings/index.js
  client/multi-currency/single-currency-settings/test/__snapshots__/index.test.js.snap
Labels: pr: ready to merge

#7081 Migrate Woopay item to TypeScript
  changelog/imp-7052-migrate-to-ts-woopay
  client/settings/express-checkout/interfaces.ts
  client/settings/express-checkout/woopay-item.tsx
  client/settings/wcpay-settings-context.js
Labels: pr: ready to merge

#7080 Migrate link-item to typescript
  changelog/imp-7052-migrate-to-ts
  changelog/imp-7052-migrate-to-ts-woopay
  client/settings/express-checkout/interfaces.ts
  client/settings/express-checkout/link-item.tsx
  client/settings/express-checkout/style.scss
  client/settings/express-checkout/woopay-item.tsx
  client/settings/wcpay-settings-context.js
  tsconfig.json
Labels: pr: ready to merge

#7101 Modify title in task to continue with onboarding
  changelog/fix-title-task-continue-onboarding
  client/overview/task-list/tasks/update-business-details-task.tsx
  client/overview/task-list/test/tasks.js
Labels: pr: ready to merge

#7096 Remove reference to the v1 experiment from the code.
  changelog/dev-remove-v1-experiment
  includes/class-wc-payments-utils.php
Labels: pr: ready to merge

#7083 Fix AED and SAR currencies format
  changelog/fix-6633-sar-aed-currencies-formatting
  i18n/currency-info.php
  i18n/locale-info.php
Labels: pr: needs review

#7051 Add support for kanji and kana statement descriptors
  changelog/add-6874-add-kanji-kana
  client/data/settings/actions.js
  client/data/settings/hooks.js
  client/data/settings/selectors.js
  client/settings/transactions/index.js
  client/settings/transactions/style.scss
  client/settings/transactions/test/index.test.js
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  includes/core/server/request/class-update-account.php
Labels: pr: needs review

#7091 Add/5669 add further payment metadata
  changelog/add-5669-add-further-payment-metadata
  includes/class-wc-payment-gateway-wcpay.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
  tests/unit/payment-methods/test-class-upe-split-payment-gateway.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge

#7103 Fall back to site logo when no custom WooPay logo defined
  changelog/add-use-site-logo-when-no-woopay-logo-defined
  includes/woopay/class-woopay-session.php
Labels: pr: ready to merge

#7086 Migrate DetailsLink component to TS to improve code quality
  changelog/dev-details-link-ts-migration
  client/components/details-link/index.js
  client/components/details-link/index.tsx
  client/components/details-link/test/__snapshots__/index.test.tsx.snap
  client/components/details-link/test/index.test.tsx
Labels: pr: ready to merge, type: task, category: refactor

#7089 Use client-side routing for the transaction details `ch_` → `pi_` redirect
  changelog/fix-improve-transaction-details-redirect
  client/payment-details/charge-details/index.tsx
  client/payment-details/test/index.test.tsx
Labels: type: enhancement, pr: ready to merge, component: transaction details, category: core
