Repository Automattic/woocommerce-payments, pull requests merged in 2023-02, with the labels that each got.

#5499 Add Feature Flag for Development of Progressive Onboarding
  changelog/dev-5486-po-feature-flag
  includes/class-wc-payments-features.php
  tests/unit/test-class-wc-payments-features.php
Labels: pr: needs review

#5432 Use order currency API when overriding currency for a subscription switch to support HPOS
  changelog/fix-5424-hpos-support-for-multi-currency-switch-subscription
  includes/multi-currency/Compatibility/WooCommerceSubscriptions.php
  tests/unit/multi-currency/compatibility/test-class-woocommerce-subscriptions.php
Labels: pr: needs review, component: customer multi-currency, category: projects, component: wc subscriptions integration, custom order tables

#5509 Merge progressive onboarding prototype under a feature flag
  changelog/prototype-progressive-onboarding
  client/index.js
  client/onboarding-experiment/hooks.ts
  client/onboarding-experiment/index.tsx
  client/onboarding-experiment/requirements/company.tsx
  client/onboarding-experiment/requirements/group.tsx
  client/onboarding-experiment/requirements/index.tsx
  client/onboarding-experiment/requirements/individual.tsx
  client/onboarding-experiment/requirements/keymap.tsx
  client/onboarding-experiment/requirements/strings.tsx
  client/onboarding-experiment/requirements/style.scss
  client/onboarding-experiment/requirements/test/__snapshots__/company.tsx.snap
  client/onboarding-experiment/requirements/test/__snapshots__/individual.tsx.snap
  client/onboarding-experiment/requirements/test/company.tsx
  client/onboarding-experiment/requirements/test/individual.tsx
  client/onboarding-experiment/requirements/test/keymap.tsx
  client/onboarding-experiment/strings.ts
  client/onboarding-experiment/style.scss
  client/onboarding-experiment/tasks/add-business-info-task/index.tsx
  client/onboarding-experiment/tasks/add-business-info-task/required-verification-info.tsx
  client/onboarding-experiment/tasks/add-business-info-task/test/__snapshots__/index.tsx.snap
  client/onboarding-experiment/tasks/add-business-info-task/test/__snapshots__/required-verification-info.tsx.snap
  client/onboarding-experiment/tasks/add-business-info-task/test/index.tsx
  client/onboarding-experiment/tasks/add-business-info-task/test/required-verification-info.tsx
  client/onboarding-experiment/tasks/setup-complete-task/index.tsx
  client/onboarding-experiment/tasks/setup-complete-task/test/__snapshots__/index.tsx.snap
  client/onboarding-experiment/tasks/setup-complete-task/test/index.tsx
  client/onboarding-experiment/test/__snapshots__/index.tsx.snap
  client/onboarding-experiment/test/index.tsx
  client/onboarding-experiment/translations/descriptions.tsx
  client/onboarding-experiment/translations/structures.tsx
  client/onboarding-experiment/translations/types.tsx
  client/onboarding-experiment/types.d.ts
  client/onboarding-prototype/index.tsx
  client/onboarding-prototype/onboarding-form.js
  client/onboarding-prototype/regular-onboarding-notice.tsx
  client/onboarding-prototype/strings.tsx
  client/onboarding-prototype/utils.tsx
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-account.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: needs review

#5471 Add support phone and email in the admin settings page
  changelog/add-3981-support-phone-number
  client/card-readers/settings/index.tsx
  client/card-readers/settings/sections/business-details.js
  client/card-readers/settings/sections/contacts-details.js
  client/card-readers/settings/sections/test/index.test.js
  client/settings/phone-input/style.scss
  client/settings/settings-manager/index.js
  client/settings/support-email-input/index.js
  client/settings/support-email-input/test/support-email-input.test.js
  client/settings/support-phone-input/index.js
  client/settings/support-phone-input/test/support-phone-input.test.js
  client/settings/transactions/index.js
  client/settings/transactions/style.scss
  client/settings/transactions/test/index.test.js
Labels: pr: ready to merge

#5522 Trigger translations after the GitHub release is created in post-release workflow
  .github/workflows/post-release-updates.yml
  changelog/fix-5398-trigger-translations
Labels: pr: ready to merge

#5529 Remove payment methods listing on the My Account Add Payment Method page
  changelog/fix-4543-payment-method-display
  includes/class-wc-payments-checkout.php
  includes/class-wc-payments-upe-checkout.php
Labels: pr: needs review

#5553 Update woopay shortcode CTA text
  changelog/update-woopay-shortcode-cta
  client/components/platform-checkout/save-user/checkout-page-save-user.js
  client/components/platform-checkout/save-user/test/checkout-page-save-user.test.js
Labels: component: platform checkout

#5571 Declare HPOS compatibility in WC Payments
  changelog/fix-5570-declare-hpos-compatibility
  woocommerce-payments.php
Labels: pr: ready to merge

#5511 Added learn more URL to deposits page once
  changelog/5370-payment-overview-deposit-improvements
  client/components/deposits-information/test/__snapshots__/index.js.snap
  client/deposits/utils/index.js
  client/settings/settings-manager/index.js
Labels: pr: ready to merge

#5597 Update GitHub workflow runner images from Ubuntu 18.04 to 20.04
  .github/workflows/compatibility.yml
  .github/workflows/coverage.yml
  .github/workflows/js-lint-test.yml
  .github/workflows/php-compatibility.yml
  .github/workflows/php-lint-test.yml
  bin/run-ci-tests.bash
  changelog/update-gh-workflow-ubuntu-image
Labels: pr: ready to merge, category: devops, type: developer experience

#5550 Add TTP fees information to timeline view
  changelog/add-5376-ttp-timeline-view
  client/payment-details/timeline/map-events.js
  client/payment-details/timeline/test/__snapshots__/map-events.js.snap
  client/payment-details/timeline/test/map-events.js
Labels: pr: ready to merge

#5423 Ensure WCPay JS loaded on Checkout page for zero order totals
  changelog/fix-4764-load-js-zero-cart
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-checkout.php
  includes/payment-methods/class-upe-payment-gateway.php
  includes/payment-methods/class-upe-split-payment-gateway.php
Labels: pr: ready to merge

#5602 Add an alert notice for Norwegian merchants on WooCommerce 7.4 and below
  changelog/add-norway-notice-wcpay
  includes/class-wc-payments.php
Labels: pr: needs review, Component: International Expansion

#5607 Fix WooPay settings warning visibility
  changelog/fix-woopay-settings-notice
  client/settings/express-checkout-settings/general-payment-request-button-settings.js
  client/settings/express-checkout-settings/test/payment-request-settings.test.js
  client/settings/index.js
Labels: component: settings

#5608 WCPay Platform Phase 1 Docs
  README.md
  includes/class-wc-payments.php
  includes/core/CONTRIBUTING.md
  includes/core/README.md
  includes/core/server/CONTRIBUTING.md
  includes/core/server/README.md
  includes/core/server/request/TEMPLATE.md
  includes/core/service/README.md
  includes/core/service/class-wc-payments-customer-service-api.php
  includes/core/service/customer-service.md
  includes/core/services/README.md
  tests/unit/core/service/test-class-wc-payments-customer-service-api.php
Labels: pr: needs review

#5621 Prevent auto-scroll on the checkout page on page load when WooPay is enabled
  changelog/as-prevent-auto-scroll-woopay-checkout
  client/checkout/platform-checkout/email-input-iframe.js
Labels: pr: needs review

#5645 Add fraud and risk tools feature flag
  changelog/add-3046-add-fraud-and-risk-tools-feature-flag
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-features.php
  tests/unit/test-class-wc-payments-features.php
Labels: pr: needs review
