Repository Automattic/woocommerce-payments, pull requests merged in 2023-04, with the labels that each got.

#5938 Fraud & Risk tools improvements from feedback
  changelog/update-fraud-rules-demo-round-2
  client/components/fraud-risk-tools-banner/components/banner-actions/index.js
  client/components/fraud-risk-tools-banner/components/banner-actions/test/__snapshots__/index.test.js.snap
  client/components/fraud-risk-tools-banner/components/banner-body/index.js
  client/components/fraud-risk-tools-banner/components/banner-body/test/__snapshots__/index.test.js.snap
  client/components/fraud-risk-tools-banner/test/__snapshots__/index.test.js.snap
  client/components/transaction-status-chip/index.tsx
  client/deposits/declarations.d.ts
  client/settings/fraud-protection/advanced-settings/cards/avs-mismatch.js
  client/settings/fraud-protection/advanced-settings/cards/cvc-verification.js
  client/settings/fraud-protection/advanced-settings/cards/international-ip-address.js
  client/settings/fraud-protection/advanced-settings/cards/ip-address-mismatch.js
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/avs-mismatch.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/cvc-verification.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/international-ip-address.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/ip-address-mismatch.js.snap
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/index.test.js.snap
  client/settings/fraud-protection/style.scss
  client/settings/settings-manager/index.js
  includes/fraud-prevention/class-order-fraud-and-risk-meta-box.php
  tests/unit/test-class-experimental-abtest.php
Labels: pr: needs review

#5852 Storing transaction fee in order metadata
  changelog/add-3257-store-transaction-fee-meta
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-order-service.php
  includes/class-wc-payments-webhook-processing-service.php
  includes/payment-methods/class-upe-payment-gateway.php
  tests/unit/test-class-wc-payments-order-service.php
Labels: pr: needs review

#5008 Remove `_wcpay_feature_custom_deposit_schedules` feature flag
  changelog/update-4856-remove-deposits-feature-flag
  client/account-status-settings/test/__snapshots__/index.js.snap
  client/account-status-settings/test/index.js
  client/components/deposits-status/index.js
  client/components/deposits-status/test/__snapshots__/index.js.snap
  client/components/deposits-status/test/index.js
  client/deposits/utils/index.js
  client/deposits/utils/test/index.js
  client/globals.d.ts
  includes/class-wc-payments-features.php
  tests/unit/test-class-wc-payments-features.php
Labels: pr: ready to merge, component: deposits, type: technical debt

#5904 Fix typo found in a heading on the new Deposits Overview component
  changelog/typo-next-deposit-overview-heading-title
  client/components/deposits-overview/strings.ts
  client/components/deposits-overview/test/__snapshots__/index.tsx.snap
Labels: pr: needs review

#5936 Fix the changelog entries generation in readme.txt
  .github/actions/process-changelog/action.yml
  .github/workflows/release-changelog.yml
  .github/workflows/release-pr.yml
  changelog/fix-5647-changelog-entries-format-in-readme
Labels: pr: ready to merge

#5762 Added phone number length validation on client
  changelog/fix-4433-improve-error-message-on-invalid-phone
  includes/class-wc-payment-gateway-wcpay.php
  includes/payment-methods/class-upe-payment-gateway.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
Labels: pr: ready to merge

#5950 Revert "Remove fraud and risk tools feature flag"
  changelog/remove-3026-fraud-and-risk-tools-feature-flag
  client/components/fraud-risk-tools-banner/test/index.test.js
  client/data/fraud-outcomes/hooks.ts
  client/data/fraud-outcomes/test/hooks.ts
  client/data/transactions/resolvers.js
  client/globals.d.ts
  client/index.js
  client/overview/index.js
  client/overview/test/index.js
  client/payment-details/order-details/test/__snapshots__/index.test.tsx.snap
  client/payment-details/summary/test/index.tsx
  client/payment-details/timeline/map-events.js
  client/settings/settings-manager/index.js
  client/settings/settings-manager/test/index.test.js
  client/transactions/index.tsx
  client/transactions/test/index.tsx
  client/utils/charge/index.ts
  client/utils/charge/test/index.js
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-features.php
  includes/class-wc-payments.php
  includes/fraud-prevention/class-fraud-risk-tools.php
  includes/fraud-prevention/class-order-fraud-and-risk-meta-box.php
  tests/e2e/specs/wcpay/merchant/merchant-payment-settings-manual-capture.spec.js
  tests/e2e/utils/flows.js
  tests/unit/test-class-wc-payments-features.php
Labels: pr: needs review

#5940 Add payment_method_types array returned from Stripe payment_intent into WC_Payments_API_Intention object
  changelog/add-5939-add-payment-method-types-in-wc-payments-api-intention
  includes/wc-payment-api/class-wc-payments-api-client.php
  includes/wc-payment-api/models/class-wc-payments-api-intention.php
  tests/unit/helpers/class-wc-helper-intention.php
Labels: pr: needs review

#5949 Cooldown – Prevent `moment` bundling
  changelog/dev-prevent-moment-bundling
  client/overview/modal/update-business-details/index.tsx
Labels: type: enhancement, category: core

#5934 Allow the `process-changelog` composite action to proceed even without any significant changes
  .github/actions/process-changelog/action.yml
  changelog/.gitkeep
  changelog/fix-5230-changelog-action-without-significant-entries
Labels: pr: ready to merge

#5924 Bump WP and PHP versions and unpin composer version in GH workflows
  .github/actions/setup-repo/action.yml
  .github/workflows/compatibility.yml
  .github/workflows/coverage.yml
  .github/workflows/e2e-test.yml
  .github/workflows/php-compatibility.yml
  .github/workflows/php-lint-test.yml
  changelog/update-php-compatibility-workflow-and-php-version
  composer.json
  composer.lock
  phpcs-compat.xml.dist
  phpcs.xml.dist
  readme.txt
  woocommerce-payments.php
Labels: pr: ready to merge

#5890 Updates our `<Pill />` component to use WooCommerce Core's Pill component
  changelog/issue-5872-use-wc-pill-component
  client/components/fraud-risk-tools-banner/components/new-pill/test/__snapshots__/index.test.js.snap
  client/components/fraud-risk-tools-banner/style.scss
  client/components/fraud-risk-tools-banner/test/index.test.js
  client/components/payment-methods-checkboxes/payment-method-checkbox.scss
  client/components/payment-methods-checkboxes/test/index.js
  client/components/payment-methods-list/payment-method.scss
  client/components/pill/index.js
  client/components/pill/index.tsx
  client/components/pill/style.scss
  client/components/pill/test/__snapshots__/index.test.js.snap
  client/components/pill/test/index.test.js
  client/payment-methods/style.scss
  client/payment-methods/test/index.js
Labels: pr: needs review

#5902 Add notice to next deposit card indicating capital loan funds
  changelog/add-5728-estimated-deposit-loan-notice
  client/components/deposits-overview/next-deposit.tsx
  client/components/deposits-overview/strings.ts
  client/components/deposits-overview/style.scss
  client/components/deposits-overview/test/index.tsx
  client/components/deposits-overview/utils.ts
  client/data/deposits/hooks.ts
Labels: pr: ready to merge

#5891 Simplify deposits UI - Add billing schedule section heading
  changelog/issue-5699-display-billing-schedule
  client/components/account-balances/test/index.test.tsx
  client/components/banner-notice/index.tsx
  client/components/banner-notice/styles.scss
  client/components/banner-notice/tests/__snapshots__/index.test.tsx.snap
  client/components/deposits-overview/deposit-schedule.tsx
  client/components/deposits-overview/index.tsx
  client/components/deposits-overview/next-deposit.tsx
  client/components/deposits-overview/section-heading.tsx
  client/components/deposits-overview/strings.ts
  client/components/deposits-overview/style.scss
  client/components/deposits-overview/suspended-deposit-notice.tsx
  client/components/deposits-overview/test/__snapshots__/index.tsx.snap
  client/components/deposits-overview/test/index.tsx
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/avs-mismatch.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/cvc-verification.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/international-ip-address.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/order-items-threshold.test.js.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/purchase-price-threshold.test.js.snap
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/allow-countries-notice.test.js.snap
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/index.test.js.snap
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/rule-card-notice.test.js.snap
  client/types/account-overview.d.ts
Labels: pr: ready to merge

#5805 Add tooltips to each balance title in the account balances card
  changelog/add-5724-account-balances-tooltips
  client/components/account-balances/balance-block.tsx
  client/components/account-balances/balance-tooltip.tsx
  client/components/account-balances/balances-tab-panel.tsx
  client/components/account-balances/strings.ts
  client/components/account-balances/style.scss
  client/components/account-balances/test/__snapshots__/index.test.tsx.snap
  client/components/account-balances/test/index.test.tsx
  client/components/tooltip/style.scss
  client/components/tooltip/tooltip-base.tsx
Labels: pr: needs review, category: projects

#5850 [Simplifying Deposits UI] Adds the recent deposits table
  changelog/issue-5700-recent-deposits-table
  client/components/deposits-overview/hooks.ts
  client/components/deposits-overview/index.tsx
  client/components/deposits-overview/recent-deposits-list.tsx
  client/components/deposits-overview/strings.ts
  client/components/deposits-overview/test/__snapshots__/index.tsx.snap
  client/components/deposits-overview/test/index.tsx
Labels: pr: ready to merge

#5861 New account period notice in Simplify Deposits UI
  changelog/add-5727-new-account-period
  client/components/deposits-overview/index.tsx
  client/components/deposits-overview/next-deposit.tsx
  client/components/deposits-overview/style.scss
  client/components/deposits-overview/test/__snapshots__/index.tsx.snap
  client/components/deposits-overview/test/index.tsx
  client/globals.d.ts
  client/overview/style.scss
Labels: pr: ready to merge

#5842 Add progressive onboarding mode choice
  assets/images/icons/lightbulb.svg
  changelog/patch
  client/components/icons/lightbulb.tsx
  client/components/radio-card/index.tsx
  client/components/radio-card/style.scss
  client/components/radio-card/test/__snapshots__/index.tsx.snap
  client/components/radio-card/test/index.tsx
  client/components/tip-box/index.tsx
  client/components/tip-box/style.scss
  client/components/tip-box/test/__snapshots__/index.tsx.snap
  client/components/tip-box/test/index.tsx
  client/connect-account-page/index.js
  client/connect-account-page/style.scss
  client/connect-account-page/test/__snapshots__/index.js.snap
  client/onboarding-prototype/index.tsx
  client/onboarding-prototype/steps/mode-choice.tsx
  client/onboarding-prototype/steps/test/mode-choice.tsx
  client/onboarding-prototype/strings.tsx
  client/onboarding-prototype/style.scss
  client/onboarding-prototype/types.ts
  client/stylesheets/abstracts/_variables.scss
  includes/class-wc-payments-account.php
  includes/class-wc-payments-onboarding-service.php
  tests/unit/test-class-wc-payments-onboarding-service.php
Labels: pr: ready to merge

#5946 [Simplifying Deposits UI] Update the deposit status chip to use our new WC Pay Pill
  changelog/issue-5892-update-deposit-status-chip
  client/components/deposit-status-chip/index.tsx
  client/components/deposit-status-chip/strings.ts
  client/components/deposit-status-chip/style.scss
  client/components/deposit-status-pill/index.tsx
  client/components/deposit-status-pill/test/index.test.tsx
  client/components/deposits-overview/next-deposit.tsx
  client/components/deposits-overview/recent-deposits-list.tsx
  client/components/deposits-overview/test/__snapshots__/index.tsx.snap
  client/components/deposits-overview/test/index.tsx
Labels: pr: needs author reply

#5956 Use the new Deposit Status Pill on the Deposits table
  changelog/issue-5893-deposit-status-table
  client/deposits/list/index.tsx
  client/deposits/list/test/__snapshots__/index.tsx.snap
Labels: pr: needs review

#5822 Share selected currency state across account overview page components
  changelog/add-5753-overview-selected-currency-data-store
  client/components/account-balances/balances-tab-panel.tsx
  client/components/account-balances/test/index.test.tsx
  client/components/deposits-overview/index.tsx
  client/components/deposits-overview/next-deposit.tsx
  client/components/deposits-overview/recent-deposits-list.tsx
  client/components/deposits-overview/test/index.tsx
  client/overview/hooks.ts
Labels: pr: ready to merge

#5839 Issue/5697 add deposit business day delay notice
  changelog/issue-5697-add-deposit-business-day-delay-notice
  client/components/deposits-overview/recent-deposits-list.tsx
  client/components/deposits-overview/strings.ts
  client/components/deposits-overview/style.scss
  client/components/deposits-overview/test/__snapshots__/index.tsx.snap
Labels: pr: ready to merge

#5895 Add/Update required components for progressive onboarding
  changelog/add-4744-po-required-component
  client/components/custom-select-control/style.scss
  client/components/grouped-select-control/index.tsx
  client/components/grouped-select-control/style.scss
  client/components/grouped-select-control/test/index.test.tsx
  client/components/load-bar/index.tsx
  client/components/load-bar/style.scss
  client/components/phone-number-control/index.tsx
  client/components/phone-number-control/style.scss
  client/components/phone-number-control/test/index.test.tsx
  client/hooks/use-unique-id.ts
  client/onboarding-prototype/steps/business-details.tsx
  client/onboarding-prototype/steps/loading.tsx
  client/onboarding-prototype/steps/personal-details.tsx
Labels: pr: needs review

#5888 Add additional fraud meta box types and messages
  changelog/add-5878-additional-fraud-meta-box-statuses
  docs/metadata.md
  includes/class-wc-payments-order-service.php
  includes/class-wc-payments-webhook-processing-service.php
  includes/constants/class-fraud-meta-box-type.php
  includes/fraud-prevention/class-order-fraud-and-risk-meta-box.php
  tests/unit/fraud-prevention/test-class-order-fraud-and-risk-meta-box.php
  tests/unit/test-class-wc-payments-order-service.php
  tests/unit/test-class-wc-payments-webhook-processing-service.php
Labels: pr: needs review

#6007 Update task-list to use the TIME.DAY_IN_MS from constants file
  changelog/5843-update-task-list-to-use-time-constant
  client/overview/task-list/index.js
Labels: pr: ready to merge

#5955 Use WordPress `CardBody` and `CardDivider` components for standard padding in deposits card
  changelog/fix-use-cardbody-component-for-standard-padding
  client/components/deposits-overview/next-deposit.tsx
  client/components/deposits-overview/recent-deposits-list.tsx
  client/components/deposits-overview/section-heading.tsx
  client/components/deposits-overview/style.scss
  client/components/deposits-overview/test/__snapshots__/index.tsx.snap
Labels: pr: needs review

#5676 Update readme.txt with better links, accurate info
  changelog/fix-5675
  readme.txt
Labels: pr: needs review

#6009 Post-onboarding test mode UX
  changelog/add-5481-builder-post-onboarding-ux
  client/components/icons/block-embed.tsx
  client/components/icons/block-post-author.tsx
  client/globals.d.ts
  client/overview/index.js
  client/overview/setup-real-payments.tsx
  client/overview/style.scss
  client/overview/test/index.js
  client/overview/test/setup-real-payments.test.tsx
  client/stylesheets/abstracts/_mixins.scss
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-onboarding-service.php
  tests/unit/test-class-wc-payments-onboarding-service.php
Labels: pr: ready to merge

#5978 Improve PHP code coverage
  changelog/dev-5977-php-coverage
  includes/core/server/request/class-list-fraud-outcome-transactions.php
  tests/unit/admin/tasks/test-class-wc-payments-task-disputes.php
  tests/unit/admin/test-class-wc-rest-payments-readers-controller.php
  tests/unit/core/server/request/test-class-list-fraud-outcome-transactions-request.php
  tests/unit/core/server/request/test-trait-order-info.php
  tests/unit/fraud-prevention/models/test-class-check.php
  tests/unit/fraud-prevention/models/test-class-rule.php
  tests/unit/subscriptions/test-class-wc-payments-subscriptions-onboarding-handler.php
  tests/unit/wc-payment-api/models/test-class-wc-payments-api-charge.php
Labels: pr: needs review

#6019 Simplify Deposits UI – Refactor AccountBalancesTabPanel loading state to ensure tooltips remain open
  changelog/fix-account-balances-loading-state-rerender
  client/components/account-balances/balance-block.tsx
  client/components/account-balances/balances-tab-panel.tsx
Labels: pr: ready to merge

#6022 Simplify deposit UI: rearrange next deposit notices and style them consistently
  changelog/issue-6002-rearrange-next-deposit-notices-for-consistency
  client/components/deposits-overview/index.tsx
  client/components/deposits-overview/next-deposit.tsx
  client/components/deposits-overview/recent-deposits-list.tsx
  client/components/deposits-overview/style.scss
  client/components/deposits-overview/test/__snapshots__/index.tsx.snap
Labels: pr: ready to merge

#6012 Prefill Stripe KYC data for test accounts with hardcoded data
  changelog/add-2935-prefill-test-mode-stripe-kyc
  includes/class-wc-payments-account.php
Labels: pr: ready to merge

#5879 Migrate get_account_data API to the core Request class
  changelog/update-migrate-account-apis-to-request-class
  includes/class-wc-payments-account.php
  includes/class-wc-payments.php
  includes/core/server/request/class-get-account.md
  includes/core/server/request/class-get-account.php
  includes/core/server/request/trait-use-test-mode-only-when-dev-mode.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/admin/test-class-wc-rest-payments-accounts-controller.php
  tests/unit/core/server/request/test-class-core-get-account-request.php
  tests/unit/test-class-wc-payments-account.php
Labels: pr: needs review

#5967 Refunds API request classes
  changelog/dev-refunds-api-request-classes
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments.php
  includes/core/server/request/class-list-charge-refunds.md
  includes/core/server/request/class-list-charge-refunds.php
  includes/core/server/request/class-refund-charge.md
  includes/core/server/request/class-refund-charge.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/core/server/request/test-class-core-list-charge-refunds-request.php
  tests/unit/core/server/request/test-class-core-refund-charge-request.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-refund.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-payment-request-button-handler.php
  tests/unit/test-class-wc-payments-platform-checkout-button-handler.php
Labels: pr: ready to merge

#5948 Migrate login_links, capital_links, tos_agreement to use the core Request class
  changelog/dev-migrate-apis-login-data-capital-links-add-tos
  client/overview/style.scss
  includes/admin/class-wc-rest-payments-tos-controller.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments.php
  includes/core/server/class-request.php
  includes/core/server/request/class-add-account-tos-agreement.md
  includes/core/server/request/class-add-account-tos-agreement.php
  includes/core/server/request/class-get-account-capital-link.md
  includes/core/server/request/class-get-account-capital-link.php
  includes/core/server/request/class-get-account-login-data.md
  includes/core/server/request/class-get-account-login-data.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/admin/test-class-wc-rest-payments-tos-controller.php
  tests/unit/core/server/request/test-class-add-account-tos-agreement.php
  tests/unit/core/server/request/test-class-core-get-account-capital-link.php
  tests/unit/core/server/request/test-class-core-get-account-login-data.php
  tests/unit/test-class-wc-payments-account-capital.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: needs review

#6045 Transactions - Increase the size of the Capture action button on the Authorizations list
  changelog/fix-increase-capture-button-size
  client/transactions/uncaptured/index.tsx
  client/transactions/uncaptured/test/__snapshots__/index.test.tsx.snap
Labels: pr: ready to merge

#6004 Add Instant deposit button in Simplify deposit UI.
  changelog/add-5889-instant-deposit
  client/components/account-balances/balances-tab-panel.tsx
  client/components/account-balances/style.scss
  client/components/account-balances/test/index.test.tsx
  client/deposits/instant-deposits/button-and-modal.js
Labels: pr: ready to merge

#6036 Fix fraud transactions list filtering
  changelog/update-6018-fraud-transactions-filtering
  client/data/transactions/hooks.ts
  client/data/transactions/resolvers.js
  client/settings/fraud-protection/advanced-settings/cards/address-mismatch.js
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/address-mismatch.test.js.snap
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/index.test.js.snap
  client/transactions/blocked/columns.tsx
  client/transactions/blocked/index.tsx
  client/transactions/blocked/test/__snapshots__/columns.test.tsx.snap
  client/transactions/blocked/test/columns.test.tsx
  client/transactions/risk-review/columns.tsx
  client/transactions/risk-review/test/columns.test.tsx
  client/utils/charge/index.ts
  includes/admin/class-wc-rest-payments-orders-controller.php
  includes/core/server/request/class-list-fraud-outcome-transactions.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/core/server/request/test-class-list-fraud-outcome-transactions-request.php
Labels: pr: needs review

#6021 Simplify deposits UI - Don't show deposits history for stores that have 0 recent deposits
  changelog/issue-6001-new-accounts-hide-deposits-history
  client/components/deposits-overview/index.tsx
  client/components/deposits-overview/recent-deposits-list.tsx
  client/components/deposits-overview/style.scss
  client/components/deposits-overview/test/index.tsx
Labels: pr: needs review

#5957 Display a deposits paused notice when the account has a negative available balance
  changelog/fix-5730-negative-balance-deposits-paused-notice
  client/components/deposits-overview/next-deposit.tsx
  client/components/deposits-overview/recent-deposits-list.tsx
  client/components/deposits-overview/strings.ts
  client/components/deposits-overview/test/index.tsx
  client/overview/style.scss
Labels: pr: in progress

#6041 Transactions - Use Pill component to display risk levels in transactions list
  changelog/update-6038-use-pill-for-risk-level-in-transactions-table
  client/components/risk-level/index.js
  client/components/risk-level/index.tsx
  client/components/risk-level/strings.ts
  client/components/risk-level/test/__snapshots__/index.tsx.snap
  client/components/risk-level/test/index.tsx
  client/transactions/uncaptured/test/__snapshots__/index.test.tsx.snap
Labels: pr: ready to merge

#6058 Dev - Add tests to cover using user tokens for some recently added WCPay core request classes.
  changelog/update-add-tests-using-user-token-for-account-releated-requests
  tests/unit/core/server/request/test-class-add-account-tos-agreement.php
  tests/unit/core/server/request/test-class-core-get-account-capital-link.php
  tests/unit/core/server/request/test-class-core-get-account-login-data.php
  tests/unit/core/server/request/test-class-core-update-account-request.php
Labels: pr: needs review

#6039 Simplify Deposits UI - Turn on new deposits overview UI by default
  changelog/issue-6016-set-feature-flag-on-by-default
  includes/class-wc-payments-features.php
  tests/unit/test-class-wc-payments-features.php
Labels: pr: needs review

#6059 Update Dependabot to tag team Harmony for reviews
  .github/dependabot.yml
  changelog/dev-update-depenabot-reviewers
Labels: pr: needs review

#6065 Update fraud protection discoverability banner action buttons
  changelog/update-6064-update-fraud-protection-banner-buttons
  client/components/fraud-risk-tools-banner/components/banner-actions/index.tsx
  client/components/fraud-risk-tools-banner/components/banner-actions/test/__snapshots__/index.test.tsx.snap
  client/components/fraud-risk-tools-banner/components/banner-actions/test/index.test.tsx
  client/components/fraud-risk-tools-banner/test/__snapshots__/index.test.tsx.snap
  client/components/fraud-risk-tools-banner/test/index.test.tsx
  client/overview/test/index.js
Labels: pr: needs review, component: fraud & risk tools

#6102 Update subscriptions-core to 5.6.0
  changelog/subscriptions-core-5.6.0
  changelog/subscriptions-core-5.6.0-1
  changelog/subscriptions-core-5.6.0-2
  changelog/subscriptions-core-5.6.0-3
  changelog/subscriptions-core-5.6.0-4
  composer.json
  composer.lock
Labels: pr: ready to merge

#5897 Improve authorization capture notification message in payment details page
  changelog/update-5192-improve-capture-notification-details
  client/payment-details/summary/index.tsx
  client/payment-details/summary/test/__snapshots__/index.tsx.snap
  client/payment-details/summary/test/index.tsx
Labels: pr: ready to merge

#6113 Update `@wordpress/url` to v3.7.1
  changelog/update-wordpress-date-dependency
  docs/dependencies.md
  package-lock.json
  package.json
Labels: pr: needs review

#6099 Update `@woocommerce/currency` to v4.2.0
  changelog/update-woocommerce-currency-dependency
  client/components/account-status/account-fees/index.js
  client/components/account-status/account-fees/test/__snapshots__/index.js.snap
  client/components/account-status/test/__snapshots__/index.js.snap
  client/components/deposits-information/test/__snapshots__/index.js.snap
  client/payment-details/timeline/test/__snapshots__/map-events.js.snap
  client/utils/currency/declarations.d.ts
  client/utils/currency/index.js
  client/utils/currency/test/index.js
  docs/dependencies.md
  package-lock.json
  package.json
Labels: pr: ready to merge

#6138 Remove duplicate constant. Remove unused Use statements.
  changelog/fix-minor-code-cleanup-of-fraud-code
  includes/admin/class-wc-rest-payments-fraud-outcomes-controller.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: needs review

#6143 Update `@wordpress/data` to v6.6.1
  changelog/update-wordpress-data-dependency
  docs/dependencies.md
  package-lock.json
  package.json
Labels: pr: ready to merge

#6160 Update `@wordpress/i18n` to v4.6.1
  changelog/update-wordpress-i18n-dependency
  docs/dependencies.md
  package-lock.json
  package.json
Labels: pr: ready to merge

#6145 Update @wordpress/api-fetch dependency to version 6.3.1
  changelog/update-dependency-wordpress-api-fetch
  docs/dependencies.md
  package-lock.json
  package.json
Labels: pr: ready to merge, dependencies, category: devops

#6144 Update @woocommerce/date dependency to version 4.2.0
  changelog/update-dependency-woocommerce-date
  docs/dependencies.md
  package-lock.json
  package.json
Labels: pr: needs review, dependencies, category: devops

#6137 Update @wordpress/date to v4.5.0
  changelog/update-wordpress-date-dependency
  changelog/update-wordpress-url-dependency
  client/external-declarations.d.ts
  docs/dependencies.md
  package-lock.json
  package.json
Labels: pr: needs review

#6055 Progressive onboarding full page design
  changelog/add-4746-po-full-page-design
  client/components/custom-select-control/index.tsx
  client/components/custom-select-control/style.scss
  client/components/custom-select-control/test/__snapshots__/index.tsx.snap
  client/components/form/fields.tsx
  client/components/form/test/fields.tsx
  client/components/grouped-select-control/index.tsx
  client/components/grouped-select-control/style.scss
  client/components/phone-number-control/index.tsx
  client/components/phone-number-control/style.scss
  client/components/phone-number-control/test/index.test.tsx
  client/components/radio-card/style.scss
  client/components/stepper/index.tsx
  client/components/stepper/test/test.tsx
  client/onboarding-experiment/tasks/add-business-info-task/test/__snapshots__/index.tsx.snap
  client/onboarding-prototype/context.tsx
  client/onboarding-prototype/form.tsx
  client/onboarding-prototype/index.tsx
  client/onboarding-prototype/step.tsx
  client/onboarding-prototype/steps/loading.tsx
  client/onboarding-prototype/steps/mode-choice.tsx
  client/onboarding-prototype/steps/personal-details.tsx
  client/onboarding-prototype/steps/test/loading.tsx
  client/onboarding-prototype/steps/test/personal-details.tsx
  client/onboarding-prototype/strings.tsx
  client/onboarding-prototype/style.scss
  client/onboarding-prototype/test/form.tsx
  client/onboarding-prototype/types.ts
  client/onboarding-prototype/validation.ts
  client/stylesheets/abstracts/_mixins.scss
  includes/class-wc-payments-onboarding-service.php
  tests/unit/test-class-wc-payments-onboarding-service.php
Labels: pr: needs review
