Repository Automattic/woocommerce-payments, pull requests merged in 2024-04, with the labels that each got.

#8507 Reporting: Payment activity widget wrapper - Remove unwanted CSS classes
  changelog/refactor-8389-remove-unwanted-css-classes
  client/components/payment-activity/index.tsx
  client/components/payment-activity/test/__snapshots__/index.tsx.snap
Labels: pr: needs review

#8517 TotalPaymentActivity component scaffolding as per figma design
  changelog/feat-8516-total-payment-activity
  client/components/payment-activity/index.tsx
  client/components/payment-activity/payments-activity-data.tsx
  client/components/payment-activity/payments-data-highlights.tsx
  client/components/payment-activity/style.scss
  client/components/payment-activity/test/__snapshots__/index.tsx.snap
  client/components/payment-activity/test/index.tsx
  client/components/payment-activity/total-payments-volume.tsx
Labels: pr: ready to merge

#8524 Change IP country fraud rule after selling country settings change on WC settings
  changelog/fix-8134-update-ip-ruleset-after-core-country-change
  includes/class-wc-payment-gateway-wcpay.php
  includes/fraud-prevention/class-fraud-risk-tools.php
  tests/unit/fraud-prevention/test-class-fraud-risk-tools.php
Labels: pr: needs review

#8462 Fix Stripe Billing checkout with different currencies
  changelog/2024-03-30-01-19-36-005298
  client/settings/advanced-settings/stripe-billing-toggle.tsx
  includes/class-wc-payments.php
  includes/exceptions/class-cannot-combine-currencies-exception.php
  includes/subscriptions/class-wc-payments-subscription-service.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: needs design

#8565 Update Decline button loading state when Accept button is click on ToS modal
  changelog/fix-7866-tos-decline-busy
  client/tos/modal/index.js
Labels: pr: ready to merge

#8576 Fix payment methods on the connect page (Klarna, Afterpay)
  assets/images/payment-methods/afterpay-logo.svg
  changelog/fix-8567-connect-page-payment-methods
  client/connect-account-page/payment-methods.tsx
  client/connect-account-page/test/__snapshots__/index.test.tsx.snap
Labels: pr: ready to merge

#8572 Fix Payment Activity card Safari padding bug
  changelog/fix-8571-payment-activity-card-safari-visual-bug
  client/overview/index.js
Labels: pr: ready to merge

#8558 Reporting: Add Empty state screen UI on Payments Activity widget
  assets/images/payment-activity-empty-state.svg
  changelog/add-8557-empty-state-payment-widget
  client/components/payment-activity/index.tsx
  client/components/payments-activity/index.tsx
  client/components/payments-activity/payments-activity-data.tsx
  client/components/payments-activity/payments-data-highlights.tsx
  client/components/payments-activity/style.scss
  client/components/payments-activity/test/__snapshots__/index.tsx.snap
  client/components/payments-activity/test/index.tsx
  client/components/payments-activity/total-payments-volume.tsx
  client/globals.d.ts
  client/overview/index.js
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-account.php
Labels: pr: needs review

#8584 Jetpack Connection Manager Updates
  changelog/dev-4256-jetpack-connection-updates
  includes/wc-payment-api/class-wc-payments-http.php
Labels: pr: needs review

#8564 Reporting: Add UI for Payment Data Highlights tiles in Payment Activity widget
  changelog/add-payment-data-highlight-block
  client/components/payments-activity/index.tsx
  client/components/payments-activity/payments-activity-data.tsx
  client/components/payments-activity/payments-data-highlights-tooltips.tsx
  client/components/payments-activity/payments-data-highlights.tsx
  client/components/payments-activity/payments-data-tile.tsx
  client/components/payments-activity/style.scss
  client/components/payments-activity/test/__snapshots__/index.test.tsx.snap
  client/components/payments-activity/test/__snapshots__/index.tsx.snap
  client/components/payments-activity/test/__snapshots__/payments-data-tile.test.tsx.snap
  client/components/payments-activity/test/index.test.tsx
  client/components/payments-activity/test/payments-data-tile.test.tsx
  client/components/payments-activity/total-payments-volume.tsx
Labels: pr: ready to merge, pr: needs author reply

#8623 Track Account Management events
  changelog/dev-track-account-management-links
  client/components/account-status/index.js
  client/components/deposits-overview/deposit-notices.tsx
  client/deposits/index.tsx
  client/overview/modal/update-business-details/index.tsx
  client/overview/task-list/tasks/update-business-details-task.tsx
  client/settings/deposits/index.js
  client/tracks/event.d.ts
Labels: pr: ready to merge

#8619 Refactor: Flatten out tooltips in Payments activity widget UI.
  changelog/refactor-payments-activity-tiles-ui
  client/components/payments-activity/payments-activity-data.tsx
  client/components/payments-activity/payments-data-highlights-tooltips.tsx
  client/components/payments-activity/payments-data-tile.tsx
Labels: pr: ready to merge

#8622 Update Discover and Diners logos
  assets/images/cards/diners.svg
  assets/images/cards/discover.svg
  changelog/update-8580-discover-and-diners-logos
  client/connect-account-page/payment-methods.tsx
  client/connect-account-page/test/__snapshots__/index.test.tsx.snap
Labels: pr: ready to merge

#8596 Sync discount display with server processing
  changelog/fix-8583-sync-discount-calculation-with-server-processing
  client/utils/account-fees.tsx
  client/utils/test/__snapshots__/account-fees.tsx.snap
Labels: pr: needs review

#8631 Reduce overview sandbox mode notice footprint
  changelog/update-8449-change-overview-sandbox-mode-notice
  client/components/account-status/account-tools/index.tsx
  client/components/test-mode-notice/index.tsx
  client/components/test-mode-notice/test/__snapshots__/index.tsx.snap
  client/overview/index.js
  client/overview/modal/reset-account/index.tsx
Labels: pr: ready to merge

#8633 Add tracking for the `Finish setup` and `Start receiving deposits` buttons.
  changelog/add-8615-account-management-track-events
  client/components/account-status/account-tools/index.tsx
  client/overview/task-list/tasks/po-task.tsx
Labels: pr: ready to merge

#8521 Remove extra WooPay icon on connect page
  changelog/fix-connect-page-double-woopay-logo
  client/connect-account-page/payment-methods.tsx
  client/connect-account-page/test/__snapshots__/index.test.tsx.snap
Labels: focus: woopay

#8635 Tweak "Proceed to checkout" event tracking
  changelog/update-proceed-to-checkout-tracking
  client/cart/index.js
Labels: type: technical debt, component: telemetry

#7407 Add more TypeScript guidelines
  changelog/add-more-typescript-guidelines
  docs/typescript/README.md
  docs/typescript/general-conventions.md
Labels: pr: ready to merge, type: documentation

#8643 Hide Fraud info banner until first transaction happens
  changelog/8279-fix-fraud-banner-display-transaction
  client/components/fraud-risk-tools-banner/index.tsx
  client/components/fraud-risk-tools-banner/test/__snapshots__/index.test.tsx.snap
  client/components/fraud-risk-tools-banner/test/index.test.tsx
  client/overview/test/index.js
Labels: pr: ready to merge

#7671 Add Playwright e2e test suite ready for incremental migration and visual regression testing
  .github/actions/e2e-pw/run-log-tests/action.yml
  .github/workflows/e2e-pw-pull-request.yml
  .gitignore
  changelog/try-playwright-e2e-tests
  package-lock.json
  package.json
  tests/e2e-pw/README.md
  tests/e2e-pw/config/default.ts
  tests/e2e-pw/docker-compose.yml
  tests/e2e-pw/playwright.config.ts
  tests/e2e-pw/specs/auth.setup.ts
  tests/e2e-pw/specs/basic.spec.ts
  tests/e2e-pw/specs/merchant/__snapshots__/merchant-admin-deposits.spec.ts/Merchant-deposits-Select-deposits-list-advanced-filters-1.png
  tests/e2e-pw/specs/merchant/__snapshots__/merchant-disputes-view-details-via-order-notice.spec.ts/Disputes-View-dispute-details-via-disputed-o-f9e9d-ils-when-disputed-order-notice-button-clicked-1.png
  tests/e2e-pw/specs/merchant/merchant-admin-deposits.spec.ts
  tests/e2e-pw/specs/merchant/merchant-disputes-view-details-via-order-notice.spec.ts
  tests/e2e-pw/specs/merchant/merchant-payment-gateways-confirmation.spec.ts
  tests/e2e-pw/specs/shopper/shopper-checkout-purchase.spec.ts
  tests/e2e-pw/test-e2e-pw-ui.sh
  tests/e2e-pw/test-e2e-pw.sh
  tests/e2e-pw/utils/helpers.ts
  tests/e2e-pw/utils/merchant.ts
  tests/e2e-pw/utils/shopper.ts
  tests/e2e/env/docker-compose.yml
Labels: type: enhancement, pr: ready to merge, category: e2e

#8673 (Client) Remove obsolete `version` key from `docker-compose.yml` files
  changelog/fix-8672-remove-obsolete-docker-compose-version
  docker-compose.yml
  tests/e2e/env/docker-compose.yml
Labels: pr: ready to merge

#8613 REST client: add extra headers to track network latency.
  changelog/add-monitoring-related-headers
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: ready to merge

#8659 Reporting: Add tooltips to each Payment activity widget tile
  changelog/add-8511-add-payment-activity-data-tooltip
  client/components/payment-activity/payment-activity-data.tsx
  client/components/payment-activity/style.scss
Labels: pr: ready to merge, pr: needs author reply

#8682 Improve survey controller validation and remove upe from route path
  changelog/update-survey-controller-validation
  client/components/payment-activity/survey/context.tsx
  includes/admin/class-wc-rest-payments-survey-controller.php
  tests/unit/admin/test-class-wc-rest-payments-survey-controller.php
Labels: pr: ready to merge, category: projects, focus: reporting

#8694 Update payment activity survey key
  changelog/update-payment-activity-survey-key
  includes/admin/class-wc-rest-payments-survey-controller.php
  tests/unit/admin/test-class-wc-rest-payments-survey-controller.php
Labels: pr: ready to merge

#8668 Add source param to onboarding and complete KYC links
  changelog/update-server-5133-add-source-to-onboarding-and-complete-kyc-links
  client/components/account-status/account-tools/index.tsx
  client/components/account-status/account-tools/test/__snapshots__/index.test.tsx.snap
  client/components/account-status/index.js
  client/components/account-status/test/__snapshots__/index.js.snap
  client/components/deposits-overview/deposit-notices.tsx
  client/components/deposits-overview/test/__snapshots__/index.tsx.snap
  client/deposits/index.tsx
  client/onboarding/steps/loading.tsx
  client/overview/task-list/tasks/po-task.tsx
  client/overview/task-list/tasks/update-business-details-task.tsx
  includes/class-wc-payments-account.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: ready to merge

#8698 Remove risk review references from the transactions page
  changelog/fix-8697-remove-transactions-review
  client/settings/fraud-protection/advanced-settings/test/rule-toggle.test.tsx
  client/transactions/blocked/index.tsx
  client/transactions/index.tsx
Labels: pr: ready to merge

#8696 Fix issue with transient check related to fraud protection settings
  changelog/fix-8695-fraud-protection-settings-api-calls
  includes/class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge

#8712 Add more points to the Compatibility service
  changelog/add-more-compatibility-points
  includes/class-compatibility-service.php
  tests/unit/test-class-compatibility-service.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: ready to merge

#8536 Treat AVS mismatch errors as fraud blocks if the advanced fraud rule is enabled
  changelog/fix-8340-avs-mismatch-risk-meta-box
  client/payment-details/timeline/mappings.ts
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-utils.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge

#8725 tweak emoji survey prompt - "these", was "those"
  changelog/fix-8724-are-these-metrics
  client/components/payment-activity/survey/index.tsx
  client/components/payment-activity/survey/test/__snapshots__/index.test.tsx.snap
  client/components/payment-activity/survey/test/index.test.tsx
  client/components/payment-activity/test/__snapshots__/index.test.tsx.snap
  client/components/payment-activity/test/index.test.tsx
Labels: pr: ready to merge

#8701 Use correct currency in Payment Activity Card
  changelog/fix-8700-payment-activity-card-default-account-currency
  client/components/payment-activity/payment-activity-data.tsx
  client/components/payment-activity/payment-data-tile.tsx
  client/components/payment-activity/test/__snapshots__/index.test.tsx.snap
  client/components/payment-activity/test/__snapshots__/payment-data-tile.test.tsx.snap
  client/components/payment-activity/test/index.test.tsx
  client/components/payment-activity/test/payment-data-tile.test.tsx
  client/data/payment-activity/resolvers.ts
  client/data/payment-activity/selectors.ts
  client/data/payment-activity/test/hooks.test.ts
  client/data/payment-activity/test/reducer.test.ts
  client/data/payment-activity/types.d.ts
Labels: pr: ready to merge
