Repository Automattic/woocommerce-payments, pull requests merged in 2024-02, with the labels that each got.

#8084 Fix losing cart contents during the login at checkout
  changelog/fix-7992-lost-cart-content
  includes/class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge

#8091 chore: remove isOrderPage return value
  changelog/chore-remove-unused-isOrderPage-return-value
  client/checkout/api/index.js
  client/checkout/blocks/confirm-card-payment.js
  client/checkout/classic/3ds-flow-handling.js
  client/checkout/classic/test/3ds-flow-handling.test.js
  client/payment-request/event-handlers.js
Labels: type: technical debt

#8078 chore: remove unused gateway class methods
  changelog/chore-delete-unused-gateway-class-methods
  includes/class-wc-payment-gateway-wcpay.php
Labels: type: technical debt

#7997 Added ENUM class for currency codes
  changelog/dev-7887-add-currency-codes-enum
  includes/class-wc-payments-account.php
  includes/class-wc-payments-utils.php
  includes/class-wc-payments.php
  includes/constants/class-currency-code.php
  includes/fraud-prevention/class-fraud-risk-tools.php
  includes/in-person-payments/class-wc-payments-printed-receipt-sample-order.php
  includes/multi-currency/CountryFlags.php
  includes/multi-currency/MultiCurrency.php
  includes/payment-methods/class-affirm-payment-method.php
  includes/payment-methods/class-afterpay-payment-method.php
  includes/payment-methods/class-bancontact-payment-method.php
  includes/payment-methods/class-becs-payment-method.php
  includes/payment-methods/class-eps-payment-method.php
  includes/payment-methods/class-giropay-payment-method.php
  includes/payment-methods/class-ideal-payment-method.php
  includes/payment-methods/class-klarna-payment-method.php
  includes/payment-methods/class-link-payment-method.php
  includes/payment-methods/class-p24-payment-method.php
  includes/payment-methods/class-sepa-payment-method.php
  includes/payment-methods/class-sofort-payment-method.php
Labels: pr: needs review

#8115 Update WPORG plugin title
  changelog/update-8099-change-plugin-title-for-wporg-seo
  readme.txt
Labels: pr: needs review

#8100 Expose charge id so merchant can use it to submit duplicate dispute evidence
  changelog/add-5141-dispute-evidence-charge-id-2
  client/payment-details/order-details/test/__snapshots__/index.test.tsx.snap
  client/payment-details/summary/index.tsx
  client/payment-details/summary/style.scss
  client/payment-details/summary/test/__snapshots__/index.test.tsx.snap
  client/payment-details/summary/test/index.test.tsx
  client/payment-details/test/__snapshots__/index.test.tsx.snap
Labels: pr: ready to merge

#8050 Remove Woo plugin header
  changelog/update-translations-loading
  includes/class-wc-payments.php
  src/Internal/DependencyManagement/ServiceProvider/GenericServiceProvider.php
  src/Internal/PluginManagement/TranslationsLoader.php
  woocommerce-payments.php
Labels: pr: ready to merge

#7710 Render a notice when the available balance is below the minimum deposit threshold
  changelog/fix-6774-deposit-minimum-threshold-ui
  client/components/deposits-overview/deposit-notices.tsx
  client/components/deposits-overview/index.tsx
  client/components/deposits-overview/test/index.tsx
  client/components/inline-notice/styles.scss
  client/globals.d.ts
Labels: pr: ready to merge

#8117 Negative balance deposit notice will only show when total balance is below 0
  changelog/fix-6941-warning-for-negative-balance
  client/components/deposits-overview/index.tsx
  client/components/deposits-overview/test/index.tsx
Labels: pr: ready to merge

#8124 Bump WC tested up to version to 8.5.2
  changelog/dev-bump-wc-version-8-5-2
  woocommerce-payments.php
Labels: pr: needs review

#8149 Format fee descriptions for iDeal payment method without percentage rate
  changelog/fix-6531-display-zero-percentage-rate-in-fee-pill
  client/utils/account-fees.tsx
Labels: type: enhancement, pr: ready to merge

#8159 Skip the log file life extension unit test on WC after v8.6.0
  changelog/fix-issue-8131
  tests/unit/subscriptions/test-class-wc-payments-subscription-migration-log-handler.php
Labels: pr: needs review

#8127 New Tracking events and passing more tracking parameters
  changelog/dev-client-tracking-events
  client/connect-account-page/index.tsx
  client/globals.d.ts
  client/onboarding/steps/test/mode-choice.tsx
  client/onboarding/tracking.ts
  client/overview/task-list/tasks/dispute-task.tsx
  client/payment-gateways/payment-gateways-confirmation.js
  client/settings/deposits/index.js
  client/settings/general-settings/index.js
  client/tracks/events.ts
  client/tracks/index.ts
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-account.php
  includes/multi-currency/SettingsOnboardCta.php
  tests/js/jest-test-file-setup.js
  tests/unit/admin/test-class-wc-payments-admin.php
  tests/unit/test-class-wc-payments-account.php
Labels: pr: needs review

#8153 Fix WooPayments overriding a WooCommerce analytics style
  changelog/fix-5622-wcpay-overriding-analytics-style
  client/deposits/details/style.scss
  client/style.scss
Labels: pr: ready to merge

#8165 Track Source in the onboarding flow start event
  changelog/add-4650-source-param-for-onboarding-start-event
  client/onboarding/index.tsx
  client/onboarding/tracking.ts
  includes/class-wc-payments-account.php
  includes/class-wc-payments-onboarding-service.php
  tests/unit/test-class-wc-payments-onboarding-service.php
Labels: pr: needs review

#8107 Improved Payment Details Handling for Partial Captures
  changelog/fix-6721-fee-applied-to-authorized-amount
  client/payment-details/timeline/map-events.js
  client/payment-details/timeline/test/index.js
  client/payment-details/timeline/test/map-events.js
  includes/class-wc-payments-captured-event-note.php
  includes/class-wc-payments-order-service.php
  tests/fixtures/captured-payments/discount.json
  tests/fixtures/captured-payments/foreign-card.json
  tests/fixtures/captured-payments/fx-decimal.json
  tests/fixtures/captured-payments/fx-foreign-card.json
  tests/fixtures/captured-payments/fx-partial-capture.json
  tests/fixtures/captured-payments/fx-with-capped-fee.json
  tests/fixtures/captured-payments/fx.json
  tests/fixtures/captured-payments/jpy-payment.json
  tests/fixtures/captured-payments/only-base-fee.json
  tests/fixtures/captured-payments/partial-capture.json
  tests/fixtures/captured-payments/subscription.json
Labels: pr: ready to merge

#8142 Fix fraud prevention token not showing up on checkout pages created via the site editor
  changelog/fix-8141-fraud-prevention-token-site-editor-problem
  client/checkout/blocks/generate-payment-method.js
  client/checkout/blocks/payment-processor.js
  client/checkout/blocks/saved-token-handler.js
  client/checkout/classic/payment-processing.js
  client/checkout/utils/upe.js
  client/payment-request/utils/normalize.js
  includes/class-wc-payments-blocks-payment-method.php
  includes/class-wc-payments-checkout.php
  includes/class-wc-payments-payment-request-button-handler.php
  includes/fraud-prevention/class-fraud-prevention-service.php
  tests/unit/test-class-wc-payments-checkout.php
Labels: pr: needs review

#8180 Fix typo "Loan Dispersement" to "Loan disbursement"
  changelog/fix-5979-loan-typo
  client/transactions/filters/test/__snapshots__/index.tsx.snap
  client/transactions/strings.ts
Labels: pr: ready to merge

#8178 Remove unused client data-fetching code for`/deposits/overview`
  changelog/fix-8047-remove-unused-deposits-overview-code
  client/data/deposits/action-types.js
  client/data/deposits/actions.js
  client/data/deposits/hooks.ts
  client/data/deposits/reducer.js
  client/data/deposits/resolvers.js
  client/data/deposits/selectors.js
  client/data/deposits/test/reducer.js
  client/data/deposits/test/resolvers.js
  client/data/deposits/test/selectors.js
Labels: pr: ready to merge

#8189 Updates GitHub actions to support NodeJS 20
  .github/actions/e2e/atomic-prepare-and-run/action.yml
  .github/actions/e2e/env-setup/action.yml
  .github/actions/e2e/run-log-tests/action.yml
  .github/actions/setup-repo/action.yml
  .github/workflows/build-zip-and-run-smoke-tests.yml
  .github/workflows/bundle-size.yml
  .github/workflows/check-changelog.yml
  .github/workflows/compatibility.yml
  .github/workflows/coverage.yml
  .github/workflows/create-pre-release.yml
  .github/workflows/deploy-api-docs.yml
  .github/workflows/e2e-pull-request.yml
  .github/workflows/e2e-test.yml
  .github/workflows/e2e-tests-atomic.yml
  .github/workflows/i18n-weekly-release.yml
  .github/workflows/js-lint-test.yml
  .github/workflows/php-compatibility.yml
  .github/workflows/php-lint-test.yml
  .github/workflows/post-release-updates.yml
  .github/workflows/pr-build-live-branch.yml
  .github/workflows/release-changelog.yml
  .github/workflows/release-code-freeze.yml
  .github/workflows/release-pr.yml
  changelog/github-actions-update-to-node20
Labels: pr: ready to merge, category: devops

#8169 [Cooldown] Add confirmation modals on order status change with pending authorization
  changelog/cooldown-6126-confirmation-modal-on-order-status-change-with-authorization
  client/order/cancel-authorization-confirm-modal/index.tsx
  client/order/cancel-confirm-modal/index.js
  client/order/index.js
  client/order/order-status-change-strategies/index.tsx
  client/order/order-status-confirmation-modal/index.tsx
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-order-service.php
Labels: pr: ready to merge

#8151 Update status chip to WooCommerce pill component for transaction status
  changelog/update-6060-blocked-txs-status-use-pill-component
  client/components/transaction-status-chip/__snapshots__/index.test.tsx.snap
  client/components/transaction-status-pill/__snapshots__/index.test.tsx.snap
  client/components/transaction-status-pill/index.test.tsx
  client/components/transaction-status-pill/index.tsx
  client/components/transaction-status-pill/mappings.ts
  client/transactions/blocked/columns.tsx
  client/transactions/blocked/test/__snapshots__/columns.test.tsx.snap
  client/transactions/risk-review/columns.tsx
  client/transactions/risk-review/test/__snapshots__/columns.test.tsx.snap
Labels: pr: ready to merge

#8205 fire dispute row click from click on any cell, not just button
  changelog/fix-8204-consistently-track-dispute-table-clicks
  client/disputes/index.tsx
Labels: pr: ready to merge

#8182 Alert when user tries to leave without saving changed advanced fraud settings
  changelog/add-3378-fraud-settings-dirty-notification
  client/settings/fraud-protection/advanced-settings/cards/order-items-threshold.tsx
  client/settings/fraud-protection/advanced-settings/cards/purchase-price-threshold.tsx
  client/settings/fraud-protection/advanced-settings/index.tsx
  client/utils/use-confirm-navigation.js
Labels: pr: ready to merge

#8213 Add hosting provider Tracks events
  changelog/add-server-4532-tracking-info
  client/globals.d.ts
  client/tracks/index.ts
  includes/admin/class-wc-payments-admin.php
  includes/class-database-cache.php
  includes/class-wc-payments-account.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/test-class-wc-payments-account.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: needs review

#8184 Fix/8175 show tooltip instead of deposit guesstimate
  changelog/fix-8175-show-tooltip-instead-of-deposit-guesstimate
  client/components/deposits-overview/deposit-schedule.tsx
  client/components/deposits-overview/index.tsx
  client/components/deposits-overview/test/__snapshots__/index.tsx.snap
  client/components/tooltip/style.scss
  client/deposits/utils/index.ts
  client/deposits/utils/test/index.ts
Labels: pr: ready to merge

#8207 Remove unused deposits/overview API endpoint
  changelog/fix-8179-remove-deposits-api
  docs/rest-api/source/includes/wp-api-v3/deposits.md
  includes/admin/class-wc-rest-payments-deposits-controller.php
Labels: pr: ready to merge

#8160 Use Docker container for running Playwright e2e tests locally to make visual comparisons more robust
  .github/actions/e2e-pw/run-log-tests/action.yml
  .github/workflows/e2e-pw-pull-request.yml
  package.json
  tests/e2e-pw/README.md
  tests/e2e-pw/playwright.config.ts
  tests/e2e-pw/test-e2e-pw-ui.sh
  tests/e2e-pw/test-e2e-pw.sh
  tests/e2e/env/docker-compose.yml
Labels: pr: ready to merge, category: e2e

#8223 Klarna E2E Tests - Fix failures + set browser language
  tests/e2e/config/jest.setup.js
  tests/e2e/specs/wcpay/shopper/shopper-klarna-checkout.spec.js
Labels: category: e2e, category: devops

#8181 Multiple small fixes for i18n issues
  changelog/i18n-fixes
  client/banner/wcpay-logo.js
  client/card-readers/preview-receipt/previewer.tsx
  client/checkout/woopay/connect/woopay-connect-iframe.js
  client/checkout/woopay/email-input-iframe.js
  client/checkout/woopay/express-button/use-express-checkout-product-handler.js
  client/components/active-loan-summary/index.tsx
  client/disputes/info/index.tsx
  client/overview/modal/reset-account/index.tsx
  client/payment-details/payment-method/card-present/index.js
  client/payment-details/payment-method/card/index.js
  client/payment-details/payment-method/eps/index.js
  client/payment-details/payment-method/giropay/index.js
  client/payment-details/payment-method/ideal/index.js
  client/payment-details/payment-method/p24/index.js
  client/payment-details/payment-method/sepa/index.js
  client/payment-details/payment-method/sofort/index.js
  client/payment-details/summary/index.tsx
  client/settings/fraud-protection/advanced-settings/cards/avs-mismatch.tsx
  client/settings/fraud-protection/components/protection-levels/index.tsx
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-payment-request-button-handler.php
  includes/class-wc-payments-token-service.php
  includes/core/server/class-request.php
Labels: pr: ready to merge

#8255 Rename log title to woopayments
  changelog/fix-7927-rename-log-title-to-woopayments
  src/Internal/Logger.php
Labels: pr: needs review

#8244 Adjustments to the wording of confirmation modals on the order and transaction details pages
  changelog/update-8243-multiple-modals-alignment-on-used-wording
  client/order/order-status-change-strategies/index.tsx
  client/payment-details/summary/refund-modal/index.tsx
  client/settings/transactions/manual-capture-control.tsx
Labels: pr: needs review

#8264 Generate RTL CSS assets
  assets/css/admin.rtl.css
  assets/css/success.rtl.css
  changelog/dev-6943-rtl-css-assets
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-order-success-page.php
  package.json
Labels: pr: ready to merge

#8285 Skip check-changelog worklfow if PR changes are only related to `.github` directory
  .github/workflows/check-changelog.yml
Labels: pr: needs review, category: devops

#8263 Add deposit schedule help tooltip to deposits list screen so it's consistent with Payments Overview
  changelog/fix-8026-deposit-schedule-notice-add-tooltip
  client/components/deposits-overview/deposit-schedule.tsx
  client/components/deposits-overview/index.tsx
  client/components/deposits-overview/test/index.tsx
  client/deposits/index.tsx
  client/deposits/list/style.scss
  client/deposits/utils/index.ts
Labels: pr: ready to merge

#8290 E2E setup – don't install deprecated WooCommerce Blocks plugin
  .github/workflows/e2e-test.yml
  tests/e2e/env/setup.sh
Labels: pr: ready to merge

#8293 E2E setup – don't install deprecated WooCommerce Blocks plugin (#8290)
  .github/workflows/e2e-test.yml
  tests/e2e/env/setup.sh
Labels: pr: needs review

#8140 Show total balance (pending + available) instead of pending balance
  changelog/update-8070-total-balance
  client/components/account-balances/balance-block.tsx
  client/components/account-balances/balance-tooltip.tsx
  client/components/account-balances/index.tsx
  client/components/account-balances/strings.ts
  client/components/account-balances/style.scss
  client/components/account-balances/test/__snapshots__/index.test.tsx.snap
  client/components/account-balances/test/index.test.tsx
  client/components/tooltip/index.tsx
  client/components/tooltip/style.scss
Labels: pr: ready to merge
