Repository Automattic/woocommerce-payments, pull requests merged in 2024-12, with the labels that each got.

#9828 Update inquiry order notes to use inquiry specific content
  changelog/fix-9612-inquiry-order-note
  includes/class-wc-payments-order-service.php
  includes/class-wc-payments-webhook-processing-service.php
  tests/unit/test-class-wc-payments-order-service.php
  tests/unit/test-class-wc-payments-webhook-processing-service.php
Labels: pr: ready to merge

#9847 Prevent browser error on dispute evidence submission
  changelog/fix-9830-browser-error-on-dispute-submission
  client/disputes/evidence/index.js
Labels: pr: ready to merge

#9790 Fix styling on payment details page in mobile view.
  changelog/fix-7230-payments-details-mobile-view
  client/components/dispute-status-chip/index.tsx
  client/components/payment-status-chip/index.js
  client/payment-details/dispute-details/dispute-notice.tsx
  client/payment-details/dispute-details/style.scss
  client/payment-details/order-details/test/__snapshots__/index.test.tsx.snap
  client/payment-details/summary/index.tsx
  client/payment-details/summary/style.scss
  client/payment-details/summary/test/__snapshots__/index.test.tsx.snap
  client/payment-details/test/__snapshots__/index.test.tsx.snap
Labels: pr: ready to merge

#9812 Remove payout timing notice and update the help tooltip.
  changelog/update-7900-payout-notice
  client/components/deposits-overview/deposit-notices.tsx
  client/components/deposits-overview/deposit-schedule.tsx
  client/components/deposits-overview/index.tsx
  client/components/deposits-overview/test/__snapshots__/index.tsx.snap
Labels: pr: ready to merge

#9780 chore: PRB references to ECE
  changelog/chore-prb-references-in-ece-docs-and-logs
  includes/express-checkout/class-wc-payments-express-checkout-button-display-handler.php
  includes/express-checkout/class-wc-payments-express-checkout-button-handler.php
  includes/express-checkout/class-wc-payments-express-checkout-button-helper.php
Labels: size: x-small

#9871 Use `type_is_in` filter from the client to filter by multiple transaction types.
  changelog/fix-use-type-is-in-filter
  client/components/payment-activity/payment-activity-data.tsx
  client/components/payment-activity/test/__snapshots__/index.test.tsx.snap
  client/data/transactions/hooks.ts
  client/data/transactions/resolvers.js
  client/transactions/declarations.d.ts
  client/transactions/filters/config.ts
  includes/core/server/request/class-list-transactions.php
Labels: pr: ready to merge

#9719 Fix/php 8 compatibility errors warnings
  .github/workflows/php-compatibility.yml
  changelog/fix-php-8-compatibility-errors-warnings
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-payment-information.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-customer-service.php
  includes/class-wc-payments-explicit-price-formatter.php
  includes/class-wc-payments-utils.php
  includes/class-wc-payments.php
  includes/core/server/request/class-generic.php
  includes/fraud-prevention/class-buyer-fingerprinting-service.php
  includes/fraud-prevention/class-fraud-prevention-service.php
  includes/multi-currency/MultiCurrency.php
  includes/payment-methods/class-afterpay-payment-method.php
  includes/payment-methods/class-cc-payment-method.php
  includes/payment-methods/class-upe-payment-method.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  lib/packages/League/Container/Argument/LiteralArgument.php
  lib/packages/League/Container/Container.php
  lib/packages/League/Container/DefinitionContainerInterface.php
  lib/packages/League/Container/Inflector/Inflector.php
  lib/packages/League/Container/Inflector/InflectorAggregate.php
  lib/packages/League/Container/Inflector/InflectorAggregateInterface.php
  phpcs-compat.xml.dist
  src/Container.php
  src/Internal/Payment/PaymentContext.php
  src/Internal/Payment/PaymentRequest.php
  src/Internal/Service/OrderService.php
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
  tests/unit/admin/test-class-wc-rest-payments-tos-controller.php
  tests/unit/express-checkout/test-class-wc-payments-express-checkout-button-display-handler.php
  tests/unit/express-checkout/test-class-wc-payments-express-checkout-button-helper.php
  tests/unit/payment-methods/test-class-upe-payment-gateway.php
  tests/unit/payment-methods/test-class-upe-split-payment-gateway.php
  tests/unit/test-class-wc-payment-gateway-wcpay-payment-types.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-refund.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-payment-method-order-note.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay-subscriptions.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-payment-request-button-handler.php
  tests/unit/test-class-wc-payments-woopay-button-handler.php
Labels: pr: ready to merge, focus: devops

#9893 fix: undefined `$cart_contains_subscription`
  changelog/frosso-patch-1
  includes/class-wc-payments.php
Labels: size: x-small

#9825 Implement gateway method to retrieve recommended PMs
  changelog/add-9690-recommended-pm
  includes/class-database-cache.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-onboarding-service.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-account.php
Labels: pr: needs review

#9890 Fix error log messages incorrecty categorized as info
  changelog/fix-9889-log-level
  includes/class-logger.php
Labels: pr: ready to merge

#9913 fix: console warning for useEffect on plugins page
  changelog/fix-use-effect-console-warning
  client/plugins-page/index.js
Labels: size: x-small

#9900 Payouts: Rename 'Bank reference key' to 'Bank reference ID' for consistency
  changelog/update-1-5316-rename-bank-reference-id
  client/deposits/list/index.tsx
  client/deposits/list/test/__snapshots__/index.tsx.snap
  client/deposits/list/test/index.tsx
  client/types/deposits.d.ts
Labels: pr: ready to merge

#9931 Adjust go-live modal and notice to the latest design
  changelog/update-9916-go-live-modal-and-notice
  client/components/sandbox-mode-switch-to-live-notice/index.tsx
  client/components/sandbox-mode-switch-to-live-notice/modal/index.tsx
  client/components/sandbox-mode-switch-to-live-notice/modal/style.scss
  client/components/sandbox-mode-switch-to-live-notice/modal/test/index.test.tsx
  client/components/sandbox-mode-switch-to-live-notice/style.scss
Labels: pr: ready to merge

#9935 chore: remove ECE error assignment on loaderror
  changelog/chore-remove-ece-error-assignment-on-loaderror
  client/express-checkout/index.js
  client/tokenized-express-checkout/index.js
Labels: size: x-small

#9911 Reports: Update Transaction ID column label
  changelog/update-9910-transaction-id-label
  client/transactions/list/index.tsx
  client/transactions/list/test/index.tsx
Labels: pr: ready to merge

#9922 Fix issue where order status and data are not updated when an order is in the processing state and being captured.
  changelog/fix-5671-handle-error-on-refund-during-manual-capture
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-order-service.php
  tests/unit/test-class-wc-payments-order-service.php
Labels: pr: needs review

#9928 Migrate capabilities from test-drive to live account
  changelog/add-6924-migrate-test-drive-capabilities
  includes/class-wc-payments-account.php
  includes/class-wc-payments-onboarding-service.php
Labels: pr: needs review

#9881 Remove temporary transaction table search field CSS that was used for Payment Activity Card report filtering
  changelog/fix-9736-remove-temporary-payment-activity-transaction-search-css
  client/transactions/list/style.scss
Labels: pr: ready to merge

#9906 Performance improvements for disputes reminder task list
  changelog/fix-9716-disputes-api-requests
  includes/admin/class-wc-payments-admin.php
  includes/admin/tasks/class-wc-payments-task-disputes.php
  includes/class-wc-payments-tasks.php
  tests/unit/admin/tasks/test-class-wc-payments-task-disputes.php
Labels: pr: needs review

#9979 fix: tokenized cart w/ multiple variations
  changelog/fix-tokenized-cart-multiple-variations
  client/tokenized-express-checkout/index.js
  client/tokenized-express-checkout/transformers/wc-to-stripe.js
Labels: size: x-small

#9937 Improve message shown to merchants when there is an error capturing/cancelling pending authorizations
  changelog/update-5002-authorizations-improve-message-shown-to-merchants-when-there-is-an-error-capturing-authorizations
  client/data/authorizations/actions.ts
  client/data/authorizations/test/actions.test.ts
Labels: pr: ready to merge

#9984 Load checkout scripts when they are not previously loaded on checkout page
  changelog/load-checkout-scripts-on-checkout-if-not-loaded
  includes/class-wc-payments-checkout.php
Labels: pr: needs review

#9980 Add failure reason to failed timeline events
  changelog/update-5713-failed-orders-should-include-more-info-on-transaction-details-page
  client/payment-details/timeline/map-events.js
  client/payment-details/timeline/mappings.ts
  client/payment-details/timeline/test/__snapshots__/index.js.snap
  client/payment-details/timeline/test/__snapshots__/map-events.js.snap
  client/payment-details/timeline/test/map-events.js
Labels: pr: needs review

#9991 Fix rounding problems with Level 3 data
  changelog/fix-9114-level3-rounding
  src/Internal/Service/Level3Service.php
  tests/unit/src/Internal/Service/Level3ServiceTest.php
Labels: pr: needs review

#9992 Remove hooks from customer service constructor
  changelog/dev-7264-remove-hooks-from-customer-service-constructor
  dev/phpcs/WCPay/ruleset.xml
  includes/class-wc-payments-customer-service.php
  includes/class-wc-payments-token-service.php
  includes/class-wc-payments.php
Labels: pr: needs review

#9934 Add seller_message to failed order notes
  changelog/feat-9810-add-seller-message
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments.php
  includes/compat/subscriptions/trait-wc-payment-gateway-wcpay-subscriptions.php
  includes/exceptions/class-api-merchant-exception.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: needs review

#9988 Use the filter param in server-side disputes CSV export
  changelog/fix-9987-filter-csv-disputes
  client/data/disputes/hooks.ts
  client/data/disputes/resolvers.js
  client/disputes/index.tsx
Labels: pr: ready to merge

#9995 Enhance Embedded Components and MOX to support custom width and paddings
  changelog/update-9919-embedded-components-width
  client/onboarding/style.scss
Labels: pr: needs review

#9997 Hide transaction fee on admin order view screen when transaction is not captured
  changelog/fix-9418-hide-transaction-fees-when-transaction-is-not-captured
  includes/admin/class-wc-payments-admin.php
Labels: pr: ready to merge

#9994 fix: tokenized ECE item compatibility w/ product bundles
  changelog/fix-tokenized-ece-product-bundles-totals
  client/tokenized-express-checkout/compatibility/__tests__/wc-product-bundles.test.js
  client/tokenized-express-checkout/compatibility/wc-product-bundles.js
  client/tokenized-express-checkout/index.js
  client/tokenized-express-checkout/transformers/wc-to-stripe.js
Labels: size: x-small

#10004 Translate hard coded strings in the fees tooltip breakdown
  changelog/fix-8620-fee-types-in-fees-brakedown-tooltip-are-not-internationalised
  client/utils/account-fees.tsx
Labels: pr: ready to merge

#10015 Invalidate transactions store when transaction is captured
  changelog/fix-9735-render-transactions-correctly-on-capture
  client/data/authorizations/actions.ts
  client/data/authorizations/test/actions.test.ts
Labels: pr: needs review

#10014 Reduce API impact from test drive setup
  changelog/update-s6837-reduce-api-impact-for-test-drive-setup
  client/connect-account-page/index.tsx
Labels: pr: needs review

#10020 Fix blank Overview page when WC onboarding is disabled
  changelog/fix-9742-blank-overview-page-without-wc-features
  client/onboarding/utils.ts
Labels: pr: ready to merge

#10018 Enable Payment Methods preselected by NOX after onboarding accounts
  changelog/add-9973-enable-pms-from-capabilities
  includes/class-wc-payments-account.php
  includes/class-wc-payments-onboarding-service.php
Labels: pr: needs review

#10019 fix: tokenized ECE do not show button when missing billing email
  changelog/fix-tokenized-ece-pay-for-order-without-billing-email
  includes/express-checkout/class-wc-payments-express-checkout-button-helper.php
  tests/unit/express-checkout/test-class-wc-payments-express-checkout-button-helper.php
Labels: size: x-small

#10008 Add TS type assertion for disputes CSV export API response to fix type safety
  changelog/fix-10007-disputes-csv-export-response-type-assertion
  client/disputes/index.tsx
Labels: pr: ready to merge

#10028 Upgrade `@woocommerce/csv-export` to v1.10.0 – fixes unnecessary escaping of negative values in CSV exports
  changelog/fix-9303-upgrade-woocommerce-csv-export-package
  package-lock.json
  package.json
Labels: pr: ready to merge

#10035 Remove unused useEffect import to fix GH linter warning
  changelog/dev-10034-linter-warning-useeffect-unused-import
  client/overview/modal/progressive-onboarding-eligibility/index.tsx
Labels: pr: needs review

#10030 Add TS type assertion for payout CSV export code for type safety and prevent TypeScript errors
  changelog/dev-10029-export-deposit-type-assert
  client/deposits/list/index.tsx
Labels: pr: ready to merge

#10036 Consistently format the order notes for refunds and charges
  changelog/feature-consistent-note-formatting
  includes/class-wc-payments-order-service.php
  includes/multi-currency/MultiCurrency.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-refund.php
  tests/unit/test-class-wc-payments-webhook-processing-service.php
Labels: pr: ready to merge

#10041 Reporting: Fix transaction list sort by payout currency
  changelog/fix-10038-payout-currency-sort
  client/transactions/list/index.tsx
Labels: pr: needs review

#10040 Reporting: Overview - improve mobile view of Balances card
  changelog/fix-8599-balances-card-layout
  client/components/account-balances/index.tsx
  client/components/account-balances/style.scss
  client/components/account-balances/test/__snapshots__/index.test.tsx.snap
Labels: pr: ready to merge
