Repository Automattic/woocommerce-payments, pull requests merged in 2024-08, with the labels that each got.

#9203 Disable Direct Checkout When WooPayments Gateway Is Disabled
  changelog/fix-disable-woopay-dc-when-woopayments-disabled
  includes/class-wc-payments-features.php
  tests/unit/test-class-wc-payments-features.php
Labels: type: bug, focus: woopay

#9212 Replace `docker-compose` with `docker compose` to ensure GH actions continue to run
  CONTRIBUTING.md
  bin/check-test-coverage.sh
  bin/cli.sh
  bin/run-tests.sh
  changelog/fix-9205-use-docker-compose-v2-commands
  package.json
  tests/README.md
  tests/e2e/env/down.sh
  tests/e2e/env/setup.sh
  tests/e2e/env/up.sh
Labels: pr: ready to merge

#9198 Handle IPP failure webhooks
  changelog/add-ipp-missing-failure-webhooks
  includes/class-wc-payments-webhook-processing-service.php
Labels: pr: ready to merge

#8881 Update URLs to prevent redirects and missing anchors
  changelog/Update URLs and anchors.
  client/bnpl-announcement/index.js
  client/payment-methods/capability-request/capability-request-map.ts
  client/utils/account-fees.tsx
  includes/notes/class-wc-payments-notes-set-https-for-checkout.php
Labels: pr: ready to merge

#9227 Replace `docker-compose` with `docker compose` to ensure GH actions continue to run
  CONTRIBUTING.md
  bin/check-test-coverage.sh
  bin/cli.sh
  bin/run-tests.sh
  package.json
  tests/README.md
  tests/e2e/env/down.sh
  tests/e2e/env/setup.sh
  tests/e2e/env/up.sh
Labels: pr: ready to merge, type: task, focus: devops

#9229 Revert "Handle IPP failure webhooks (#9198)"
  changelog/add-ipp-missing-failure-webhooks
  changelog/revert-ipp-missing-failure-webhooks
  includes/class-wc-payments-webhook-processing-service.php
Labels: pr: ready to merge

#9231 Added better error message when mandate is wrong.
  changelog/fix-3075-add-better-error-message-when-mandate-is-wrong
  includes/class-wc-payments-webhook-processing-service.php
Labels: pr: needs review

#9241 Do not enqueue Cart scripts if WooPayments is not enabled
  changelog/as-fix-track-event
  includes/class-wc-payments.php
Labels: pr: needs review

#9242 Remove unnecessary console.warn statements added in #9121
  changelog/fix-remove-console-warns
  tests/e2e/config/jest.setup.js
  tests/e2e/specs/subscriptions/merchant/merchant-subscriptions-renew-subscription.spec.js
  tests/e2e/specs/wcpay/merchant/merchant-disputes-submit-winning.spec.js
  tests/e2e/specs/wcpay/merchant/merchant-orders-full-refund.spec.js
  tests/e2e/specs/wcpay/merchant/merchant-orders-partial-refund.spec.js
  tests/e2e/specs/wcpay/merchant/merchant-orders-refund-failures.spec.js
  tests/e2e/specs/wcpay/shopper/shopper-klarna-checkout.spec.js
Labels: pr: ready to merge

#9023 Add Playwright e2e test for merchant account balance overview critical flows
  changelog/e2e-add-merchant-account-balance-overview-pw-tests
  package.json
  tests/e2e-pw/specs/merchant/merchant-admin-account-balance.spec.ts
  tests/e2e-pw/test-e2e-pw.sh
Labels: pr: ready to merge

#9109 Introduce a test drive mode into the onboarding process
  changelog/add-test-drive-mode
  client/components/account-status/index.js
  client/components/account-status/test/__snapshots__/index.js.snap
  client/components/account-status/test/index.js
  client/components/deposits-overview/deposit-notices.tsx
  client/connect-account-page/index.tsx
  client/connect-account-page/style.scss
  client/deposits/index.tsx
  client/globals.d.ts
  client/overview/index.js
  client/overview/task-list/tasks/update-business-details-task.tsx
  client/overview/test/index.js
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-utils.php
  package-lock.json
  package.json
  tests/unit/test-class-wc-payments-account.php
  tests/unit/test-class-wc-payments-utils.php
Labels: pr: needs review

#9258 Adjust spacing on Express Checkout buttons
  changelog/as-fix-ece-spacing
  client/checkout/express-checkout-buttons.scss
  client/checkout/woopay/express-button/index.js
  client/express-checkout/blocks/components/express-checkout-component.js
  client/express-checkout/blocks/components/express-checkout-container.js
  client/express-checkout/blocks/components/express-checkout-preview.js
  client/express-checkout/blocks/express-checkout-element.scss
  client/express-checkout/utils/index.ts
  client/settings/express-checkout-settings/index.scss
  includes/express-checkout/class-wc-payments-express-checkout-button-display-handler.php
  tests/unit/test-class-wc-payments-express-checkout-button-display-handler.php
Labels: pr: needs review

#9272 Updates test mode instructions copy for card
  assets/images/icons/copy.svg
  changelog/fix-checkout-floating-labels-and-test-mode-copy
  client/checkout/blocks/style.scss
  client/checkout/classic/style.scss
  includes/class-wc-payments-checkout.php
  includes/payment-methods/class-cc-payment-method.php
  tests/unit/test-class-wc-payments-checkout.php
Labels: priority: high, focus: checkout payments

#9277 Update cache after persisting the User session
  changelog/as-fix-woopay-data-mismatch
  includes/woopay/class-woopay-store-api-session-handler.php
Labels: pr: needs review

#9284 E2E: Fix the dispute save draft challenge failing due to redirect race condition
  changelog/fix-9281-e2e-dispute-save-challenge
  tests/e2e/specs/wcpay/merchant/merchant-disputes-save-draft-challenge.spec.js
Labels: pr: ready to merge

#9319 Hot Fix Payments > Settings test mode disable with test drive account
  changelog/fix-9296-payments-settings-test-mode-disable-with-test-drive-account
  client/components/account-status/account-tools/index.tsx
  client/components/account-status/account-tools/strings.tsx
  client/components/account-status/account-tools/test/__snapshots__/index.test.tsx.snap
  client/components/account-status/account-tools/test/index.test.tsx
  client/components/account-status/test/index.js
  client/components/test-mode-notice/index.tsx
  client/connect-account-page/index.tsx
  client/data/settings/hooks.js
  client/data/settings/selectors.js
  client/globals.d.ts
  client/overview/connection-sucess-notice.tsx
  client/overview/index.js
  client/overview/modal/reset-account/strings.tsx
  client/overview/task-list/tasks.tsx
  client/settings/general-settings/index.js
  client/settings/general-settings/test/general-settings.test.js
  client/settings/support-phone-input/index.js
  client/settings/support-phone-input/test/support-phone-input.test.js
  client/settings/transactions/test/index.test.js
  client/utils/index.js
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-settings-controller.php
Labels: pr: ready to merge

#9316 Make correction to changelog entry for Docker compose v2 improvement (`Fix` → `Dev`)
  changelog.txt
  changelog/dev-correct-docker-compose-v2-changelog-entry
  readme.txt
Labels: pr: ready to merge, type: task, priority: low, category: trash pickup

#9315 Apply some fixes in the e2e tests scripts
  changelog/dev-fix-e2e-scripts
  tests/e2e-pw/README.md
  tests/e2e/env/down.sh
  tests/e2e/env/up.sh
Labels: category: e2e

#9349 Update Jetpack packages for ver 8.2.0
  changelog/update-jetpack-packages
  composer.json
  composer.lock
  woocommerce-payments.php
Labels: pr: needs review

#9346 Fix onboarding flows edge cases around onboarding mode
  changelog/fix-onboarding-flows-edge-cases-around-onboarding-mode
  client/components/sandbox-mode-switch-to-live-notice/modal/index.tsx
  client/overview/modal/reset-account/index.tsx
  client/settings/deposits/index.js
  client/settings/fraud-protection/components/fp-modal/index.tsx
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-accounts-controller.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-onboarding-service.php
  includes/core/README.md
  includes/core/class-mode.php
  tests/unit/core/server/request/test-class-core-get-account-login-data.php
  tests/unit/core/server/request/test-class-core-get-account-request.php
  tests/unit/core/service/test-class-wc-payments-customer-service-api.php
  tests/unit/core/test-class-mode.php
  tests/unit/src/Internal/Service/ExampleServiceWithDependenciesTest.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-onboarding-service.php
Labels: pr: needs review, pr: ready to merge

#9356 Maintain test drive backward compatibility with version 8.1.0
  changelog/fix-maintain-test-drive-backward-compatibility-with-8-1-0
  includes/class-wc-payments-onboarding-service.php
Labels: pr: needs review

#9343 Fix Connect page scrolls to top when the Enable Sandbox Mode button is clicked
  changelog/fix-9324-test-drive-onboarding-scoll
  client/connect-account-page/index.tsx
Labels: pr: ready to merge

#9369 Define WooPay URL for E2E setup
  changelog/update-e2e-setup-script
  tests/e2e/env/setup.sh
Labels: pr: needs review, category: e2e, focus: devops
