Repository Automattic/woocommerce-payments, pull requests merged in 2024-10, with the labels that each got.

#9510 Migrate WizardTaskItem and CollapsibleBody components to TS for improve code safety and clarity
  client/additional-methods-setup/wizard/collapsible-body.tsx
  client/additional-methods-setup/wizard/task-item.tsx
  client/multi-currency-setup/wizard/task-item.tsx
Labels: pr: ready to merge

#9157 add default (= null) for classNames prop so it's optional for `WizardTaskItem` and `CollapsibleBody`
  changelog/fix-9142-classname-optional-default-null
  client/additional-methods-setup/wizard/collapsible-body.tsx
  client/additional-methods-setup/wizard/task-item.tsx
  client/multi-currency-setup/wizard/task-item.tsx
  client/vat/form/tasks/company-data-task.tsx
  client/vat/form/tasks/vat-number-task.tsx
Labels: pr: ready to merge

#9473 Add style support for the WooPay button
  changelog/add-support-for-woo-button-controls
  client/checkout/woopay/express-button/woopay-express-checkout-payment-method.js
Labels: type: enhancement, component: WooPay, focus: woopay

#9541 Make experiment Payments task onboarding flow treatment final
  changelog/update-9540-payment-task-onboarding-flow
  client/overview/task-list/tasks.tsx
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-utils.php
  tests/unit/test-class-wc-payments-account.php
Labels: pr: needs review

#9549 Fix WooPay auto enable for new accounts
  changelog/fix-9548-woopay-auto-enable
  includes/admin/class-wc-rest-payments-onboarding-controller.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-onboarding-service.php
  tests/unit/admin/test-class-wc-rest-payments-onboarding-controller.php
  tests/unit/test-class-wc-payments-onboarding-service.php
Labels: pr: ready to merge

#9546 Rename 'Deposit' to 'Payout' in the transactions list component
  changelog/update-9543-transactions-list-deposit-to-payout-rename
  client/transactions/list/deposit.tsx
  client/transactions/list/index.tsx
  client/transactions/list/test/__snapshots__/deposit.tsx.snap
  client/transactions/list/test/__snapshots__/index.tsx.snap
  client/transactions/list/test/deposit.tsx
  client/transactions/list/test/index.tsx
Labels: pr: needs review, status: blocked

#9566 Prevent payment method deletion in local environment when using Stripe production account
  changelog/fix-5384-prevent-pm-detach-on-prod-when-user-is-deleted-on-localhost
  includes/class-wc-payments-token-service.php
Labels: pr: needs review

#9563 Update Playwright README with correct instructions for updating snapshots
  changelog/fix-9562-readme-correction-playwright-update-snapshots
  tests/e2e-pw/README.md
Labels: pr: ready to merge

#9571 Darken the color of links within click tooltips to improve color contrast and readability
  changelog/fix-9559-tooltip-link-color-contrast
  client/components/tooltip/style.scss
Labels: pr: ready to merge

#9532 Rename deposits to payouts on the settings screen
  changelog/fix-9527-payouts-rename-settings
  client/components/deposits-overview/deposit-notices.tsx
  client/components/deposits-overview/test/__snapshots__/index.tsx.snap
  client/components/deposits-overview/test/index.tsx
  client/settings/deposits/index.js
  client/settings/deposits/test/index.test.js
  client/settings/settings-manager/index.js
Labels: pr: ready to merge

#9554 rename "deposit" to "payout": instant deposit button & modal
  changelog/fix-9542-rename-payouts-instant-depost-modal-flow
  client/components/account-balances/index.tsx
  client/deposits/instant-payouts/index.tsx
  client/deposits/instant-payouts/modal.tsx
  client/deposits/instant-payouts/style.scss
  client/deposits/instant-payouts/test/__snapshots__/index.tsx.snap
  client/deposits/instant-payouts/test/index.tsx
Labels: pr: needs review

#9603 Remove unnecessary WC table css overrides to fix WC Analytics styling and a11y issues
  changelog/fix-9572-woococommerce-table-specificity
  client/style.scss
Labels: pr: ready to merge

#9565 Payouts: Rename 'deposit' to 'payout' in transaction details timeline
  changelog/update-9564-transaction-timeline-deposit-to-payout-rename
  client/payment-details/timeline/map-events.js
  client/payment-details/timeline/test/__snapshots__/index.js.snap
  client/payment-details/timeline/test/__snapshots__/map-events.js.snap
  includes/class-wc-payments-captured-event-note.php
  tests/fixtures/captured-payments/discount.json
  tests/fixtures/captured-payments/foreign-card.json
  tests/fixtures/captured-payments/fx-decimal.json
  tests/fixtures/captured-payments/fx-foreign-card.json
  tests/fixtures/captured-payments/fx-partial-capture.json
  tests/fixtures/captured-payments/fx-with-capped-fee.json
  tests/fixtures/captured-payments/fx.json
  tests/fixtures/captured-payments/jpy-payment.json
  tests/fixtures/captured-payments/only-base-fee.json
  tests/fixtures/captured-payments/partial-capture.json
  tests/fixtures/captured-payments/subscription.json
Labels: pr: ready to merge

#9528 Rename deposit to payout on the deposits list page.
  changelog/update-9524-deposit-payout-deposits-list
  client/components/deposits-overview/deposit-schedule.tsx
  client/components/deposits-overview/test/__snapshots__/index.tsx.snap
  client/components/test-mode-notice/index.tsx
  client/components/test-mode-notice/test/__snapshots__/index.tsx.snap
  client/deposits/filters/config.js
  client/deposits/filters/test/index.js
  client/deposits/index.tsx
  client/deposits/list/index.tsx
  client/deposits/list/test/__snapshots__/index.tsx.snap
  client/deposits/strings.ts
  client/index.js
  tests/e2e-pw/README.md
  tests/e2e-pw/specs/merchant/__snapshots__/merchant-admin-deposits.spec.ts/Merchant-deposits-Select-deposits-list-advanced-filters-1.png
  tests/e2e-pw/specs/merchant/merchant-admin-deposits.spec.ts
Labels: pr: needs review

#9544 npm script to update e2e-pw screenshots / snapshots
  changelog/update-npm-readme-update-e2e-pw-snapshots
  package.json
Labels: pr: ready to merge

#9515 Add risk level information to the Fraud & Risk meta box
  assets/css/admin.css
  changelog/add-1225-flag-elevated-risk-transactions
  includes/admin/class-wc-payments-admin-settings.php
  includes/class-wc-payments-order-service.php
  includes/fraud-prevention/class-order-fraud-and-risk-meta-box.php
  tests/unit/fraud-prevention/test-class-order-fraud-and-risk-meta-box.php
Labels: pr: ready to merge

#9521 Fix settings rendering on the Advanced Fraud Protection page
  changelog/fix-9520-advanced-fraud-protection-settings
  client/settings/fraud-protection/advanced-settings/allow-countries-notice.tsx
  client/settings/fraud-protection/advanced-settings/cards/order-items-threshold.tsx
  client/settings/fraud-protection/advanced-settings/cards/purchase-price-threshold.tsx
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/address-mismatch.test.tsx.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/international-ip-address.test.tsx.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/ip-address-mismatch.test.tsx.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/order-items-threshold.test.tsx.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/purchase-price-threshold.test.tsx.snap
  client/settings/fraud-protection/advanced-settings/cards/test/address-mismatch.test.tsx
  client/settings/fraud-protection/advanced-settings/cards/test/avs-mismatch.test.tsx
  client/settings/fraud-protection/advanced-settings/cards/test/cvc-verification.test.tsx
  client/settings/fraud-protection/advanced-settings/cards/test/international-ip-address.test.tsx
  client/settings/fraud-protection/advanced-settings/cards/test/ip-address-mismatch.test.tsx
  client/settings/fraud-protection/advanced-settings/cards/test/order-items-threshold.test.tsx
  client/settings/fraud-protection/advanced-settings/cards/test/purchase-price-threshold.test.tsx
  client/settings/fraud-protection/advanced-settings/context.ts
  client/settings/fraud-protection/advanced-settings/index.tsx
  client/settings/fraud-protection/advanced-settings/rule-toggle.tsx
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/index.test.tsx.snap
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/rule-toggle.test.tsx.snap
  client/settings/fraud-protection/advanced-settings/test/allow-countries-notice.test.tsx
  client/settings/fraud-protection/advanced-settings/test/rule-toggle.test.tsx
  client/settings/fraud-protection/interfaces.ts
Labels: pr: ready to merge

#9611 Rename deposit to payout in account messaging.
  changelog/fix-payout-rename-account-errors
  client/components/account-status/account-tools/strings.tsx
  client/components/account-status/account-tools/test/__snapshots__/index.test.tsx.snap
  client/components/account-status/test/__snapshots__/index.js.snap
  client/overview/modal/update-business-details/strings.tsx
  client/overview/modal/update-business-details/test/__snapshots__/index.tsx.snap
  client/overview/task-list/tasks/update-business-details-task.tsx
Labels: pr: ready to merge

#9610 Rename Deposit to Payout in TOS modal
  changelog/fix-9573-rename-payout-tos-modal
  client/tos/modal/index.js
  client/tos/modal/test/__snapshots__/index.js.snap
Labels: pr: ready to merge

#9530 changed the URL and menu from Deposits to Payouts
  changelog/fix-9525-menu-url-payouts-rename
  client/components/deposits-overview/index.tsx
  client/components/deposits-overview/recent-deposits-list.tsx
  client/components/deposits-overview/test/__snapshots__/index.tsx.snap
  client/components/details-link/index.tsx
  client/components/details-link/test/__snapshots__/index.test.tsx.snap
  client/components/details-link/test/index.test.tsx
  client/data/deposits/actions.js
  client/deposits/filters/index.js
  client/deposits/list/index.tsx
  client/deposits/list/test/__snapshots__/index.tsx.snap
  client/index.js
  client/payment-details/timeline/map-events.js
  client/payment-details/timeline/test/__snapshots__/index.js.snap
  client/payment-details/timeline/test/__snapshots__/map-events.js.snap
  client/transactions/list/deposit.tsx
  client/transactions/list/test/__snapshots__/deposit.tsx.snap
  client/transactions/list/test/__snapshots__/index.tsx.snap
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-onboarding-service.php
  tests/e2e-pw/specs/merchant/merchant-admin-deposits.spec.ts
  tests/e2e/utils/flows.js
  tests/unit/admin/test-class-wc-payments-admin.php
Labels: pr: ready to merge

#9622 Rename instant deposits to instant payouts
  changelog/fix-9585-rename-instant-payouts
  client/data/deposits/actions.js
  includes/notes/class-wc-payments-notes-instant-deposits-eligible.php
Labels: pr: ready to merge

#9624 Rename deposits to Payouts in error messages
  changelog/fix-9588-rename-payouts-error-messages
  client/data/deposits/resolvers.js
Labels: pr: ready to merge

#9623 Rename 'deposit' to 'payout' in 'Overview' section modals
  changelog/update-9578-79-rename-deposit-overview-modal
  client/overview/modal/progressive-onboarding-eligibility/index.tsx
  client/overview/modal/progressive-onboarding-eligibility/test/index.test.tsx
  client/overview/modal/reset-account/strings.tsx
  client/overview/modal/update-business-details/strings.tsx
  client/overview/modal/update-business-details/test/__snapshots__/index.tsx.snap
Labels: pr: needs review

#9637 Update cache key for composer dependencies
  .github/actions/e2e/env-setup/action.yml
  .github/actions/setup-repo/action.yml
  .github/workflows/check-changelog.yml
  .github/workflows/compatibility.yml
  .github/workflows/coverage.yml
  .github/workflows/i18n-weekly-release.yml
  .github/workflows/js-lint-test.yml
  .github/workflows/php-lint-test.yml
  changelog/gh-actions-e2e-optimize-composer-cache
Labels: pr: needs review, focus: devops, e2e: broken environment

#9638 Add unit test for Capital Loans page of WP Admin
  changelog/dev-add-unit-tests-for-capital-list
  client/capital/test/__snapshots__/index.test.tsx.snap
  client/capital/test/index.test.tsx
Labels: pr: needs review

#9632 Rename 'deposit' to 'payout' in order note for fund withdrawal
  includes/class-wc-payments-webhook-processing-service.php
  tests/unit/test-class-wc-payments-webhook-processing-service.php
Labels: pr: needs review

#9633 Rename 'deposit' to 'payout' in deposit details page
  client/deposits/details/index.tsx
  client/deposits/details/test/__snapshots__/index.tsx.snap
Labels: pr: needs review

#9640 Add unit tests for disputed order notices of WP Admin
  changelog/dev-add-unit-tests-for-diputed-order-notice
  client/components/disputed-order-notice/test/__snapshots__/index.test.js.snap
  client/components/disputed-order-notice/test/index.test.js
Labels: pr: needs review

#9592 Add support for allowedShippingCountries in Express Checkout Element
  changelog/9104-add-support-for-allowedshippingcountries-in-express-checkout-element
  client/express-checkout/blocks/hooks/use-express-checkout.js
  client/express-checkout/index.js
  includes/express-checkout/class-wc-payments-express-checkout-button-handler.php
Labels: pr: in progress

#9627 Rename 'deposit' to 'payout' across doc urls
  changelog/update-9587-doc-url-payout-rename
  client/components/account-balances/index.tsx
  client/components/account-balances/strings.ts
  client/components/account-balances/test/index.test.tsx
  client/components/deposits-overview/deposit-notices.tsx
  client/components/deposits-overview/deposit-schedule.tsx
  client/components/deposits-overview/test/__snapshots__/index.tsx.snap
  client/components/deposits-overview/test/index.tsx
  client/components/deposits-status/index.tsx
  client/components/deposits-status/test/__snapshots__/index.js.snap
  client/deposits/details/index.tsx
  client/deposits/instant-payouts/modal.tsx
  client/deposits/instant-payouts/test/__snapshots__/index.tsx.snap
  client/settings/deposits/index.js
  client/settings/settings-manager/index.js
  client/transactions/list/deposit.tsx
  docs/rest-api/source/includes/wp-api-v3/deposits.md
  includes/notes/class-wc-payments-notes-instant-deposits-eligible.php
  readme.txt
Labels: pr: ready to merge

#9645 Resolve compatibility issues with CustomSelectControl component styles for WordPress 6.7
  changelog/fix-9636-custom-select-control-styling
  client/components/custom-select-control/style.scss
Labels: pr: ready to merge

#8382 Introducing consistency in colors for deposits across pages
  changelog/fix-7761-align-deposit-colors
  client/components/deposit-status-chip/index.tsx
  client/deposits/details/style.scss
Labels: pr: ready to merge

#9642 Rename 'deposit' to 'payout' in onboarding tasklist
  changelog/update-9581-rename-deposit-onboarding-tasklist
  client/overview/task-list/strings.tsx
  client/overview/task-list/tasks/test/po-tasks.tsx
  client/overview/task-list/tasks/update-business-details-task.tsx
  client/overview/task-list/test/tasks.js
Labels: pr: ready to merge
