Repository Automattic/woocommerce-payments, pull requests merged in 2024-06, with the labels that each got.

#8890 Declare compatibility with the Cart and Checkout blocks
  changelog/update-declare-compatibility-width-cart-and-checkout-block
  woocommerce-payments.php
Labels: type: bug, pr: needs review

#8899 Skip flaky playwright e2e test: `payment gateways disable confirmation`
  changelog/dev-8875-disable-flaky-e2e-test-payment-gateways-disable-confirmation
  tests/e2e-pw/specs/merchant/merchant-payment-gateways-confirmation.spec.ts
Labels: pr: ready to merge

#8757 Add survey modal on WooPayments deactivation
  changelog/add-1527-survey-modal-on-deactivation
  client/plugins-page/deactivation-survey/index.js
  client/plugins-page/deactivation-survey/style.scss
  client/plugins-page/index.js
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments.php
  templates/plugins-page/plugins-page-wrapper.php
  webpack/shared.js
Labels: pr: needs review

#8864 Support payment activity widget fetching & displaying differnt deposit currencies
  changelog/add-deposit-currency-param-for-payment-widget
  client/components/payment-activity/index.tsx
  client/data/payment-activity/test/hooks.test.ts
  client/data/payment-activity/test/resolver.test.ts
  client/data/payment-activity/types.d.ts
  includes/admin/class-wc-rest-payments-reporting-controller.php
  includes/core/server/request/class-get-reporting-payment-activity.md
  includes/core/server/request/class-get-reporting-payment-activity.php
Labels: pr: needs review

#8915 Payment Activity data refreshes with currency selection
  changelog/add-8490-payment-activity-currency-selector
  client/components/payment-activity/index.tsx
  client/data/payment-activity/hooks.ts
Labels: pr: ready to merge

#8896 Add a new `InlineLabelSelect` component for WCPay admin filter select inputs (with inline label)
  changelog/add-8788-select-component-for-currency-switcher
  client/components/inline-label-select/index.tsx
  client/components/inline-label-select/style.scss
  client/components/inline-label-select/test/__snapshots__/index.test.tsx.snap
  client/components/inline-label-select/test/index.test.tsx
Labels: pr: ready to merge

#8791 Reorganise payments overview currency switcher, welcome message and balances card
  changelog/update-8765-payments-overview-currency-select
  client/components/account-balances/index.tsx
  client/components/account-balances/style.scss
  client/components/account-balances/test/__snapshots__/index.test.tsx.snap
  client/components/account-balances/test/index.test.tsx
  client/components/account-balances/utils.ts
  client/components/welcome/currency-select.tsx
  client/components/welcome/index.tsx
  client/components/welcome/style.scss
  client/components/welcome/test/index.test.tsx
  client/overview/index.js
  tests/e2e-pw/specs/basic.spec.ts
Labels: pr: ready to merge

#8901 Validate route params before making request
  changelog/update-route-param-validation
  includes/admin/class-wc-rest-payments-authorizations-controller.php
  includes/admin/class-wc-rest-payments-charges-controller.php
  includes/admin/class-wc-rest-payments-customer-controller.php
  includes/admin/class-wc-rest-payments-deposits-controller.php
  includes/admin/class-wc-rest-payments-disputes-controller.php
  includes/admin/class-wc-rest-payments-files-controller.php
  includes/admin/class-wc-rest-payments-fraud-outcomes-controller.php
  includes/admin/class-wc-rest-payments-orders-controller.php
  includes/admin/class-wc-rest-payments-payment-intents-controller.php
  includes/admin/class-wc-rest-payments-reader-controller.php
  includes/admin/class-wc-rest-payments-terminal-locations-controller.php
  includes/admin/class-wc-rest-payments-timeline-controller.php
  includes/admin/class-wc-rest-payments-transactions-controller.php
  includes/reports/class-wc-rest-payments-reports-authorizations-controller.php
  includes/reports/class-wc-rest-payments-reports-transactions-controller.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: ready to merge

#8934 Fix PM title for PRBs not displaying correctly due to ECE code
  changelog/fix-ece-payment-method-title
  includes/class-wc-payment-gateway-wcpay.php
Labels: focus: checkout payments

#8887 Improve code quality of `RecentDepositsList` component, including outdated `Next Deposit` references, complexity/nesting reduction
  changelog/dev-code-quality-recent-deposits-list
  client/components/deposits-overview/recent-deposits-list.tsx
Labels: pr: ready to merge

#8941 Payment Activity Widget: Select report currency when clicking "View report"
  changelog/fix-8938-payment-activity-view-report-currency
  client/components/payment-activity/payment-activity-data.tsx
  client/components/payment-activity/test/__snapshots__/index.test.tsx.snap
  client/components/payment-activity/test/index.test.tsx
Labels: pr: ready to merge

#8940 Adding adjustments to TPV Report
  changelog/add-adjustments-tpv-report
  client/components/payment-activity/payment-activity-data.tsx
  client/components/payment-activity/test/__snapshots__/index.test.tsx.snap
Labels: pr: ready to merge

#8927 Reporting: Add preset date selector to the Payment activity widget
  changelog/8734-add-date-selector
  client/components/payment-activity/hooks.ts
  client/components/payment-activity/index.tsx
  client/components/payment-activity/style.scss
  client/components/payment-activity/test/__snapshots__/index.test.tsx.snap
  client/components/payment-activity/types.ts
  client/data/payment-activity/actions.ts
  client/data/payment-activity/hooks.ts
  client/data/payment-activity/reducer.ts
  client/data/payment-activity/resolvers.ts
  client/data/payment-activity/selectors.ts
  client/data/payment-activity/test/reducer.test.ts
  client/data/payment-activity/test/resolver.test.ts
  client/data/payment-activity/types.d.ts
Labels: pr: needs review

#8900 Improve consistency of Manage button for different WooPayments KYC states
  changelog/fix-8813-consistency-of-woopayments-manage-settings-button
  includes/class-wc-payments-account.php
Labels: pr: ready to merge

#8952 Bump WooCommerce Tested To version to 8.9.3
  changelog/dev-bump-woocommerce-tested-up-to-8.9.3
  woocommerce-payments.php
Labels: pr: ready to merge

#8961 Reporting: Add test for date preset drowpdown in PaymentActivity component
  changelog/add-8943-test-for-date-selector-hook
  client/components/payment-activity/test/index.test.tsx
Labels: pr: ready to merge

#8935 Update compatibility data output
  changelog/fix-5532-fix-compatibility-data
  includes/class-compatibility-service.php
  tests/unit/test-class-compatibility-service.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: ready to merge

#8937 Implement payments via Express Checkout Element for Simple Products on the Product Page
  .eslintrc
  changelog/add-8870-ece-for-shortcode-cart-and-checkout
  changelog/as-8868-ece-product-page
  client/express-checkout/blocks/components/express-checkout-component.js
  client/express-checkout/blocks/hooks/use-express-checkout.js
  client/express-checkout/event-handlers.js
  client/express-checkout/index.js
  client/express-checkout/utils/index.js
  client/express-checkout/utils/index.ts
  client/express-checkout/utils/normalize.js
  includes/express-checkout/class-wc-payments-express-checkout-ajax-handler.php
Labels: pr: needs review

#8975 Improve the tooltip texts on Payment Activity Card data tiles.
  changelog/update-8973-payment-activity-tooltips
  client/components/payment-activity/payment-activity-data.tsx
  client/components/payment-activity/test/__snapshots__/index.test.tsx.snap
Labels: pr: ready to merge

#8982 Added Learn more link to Payment Activity Card Disputes tooltip
  changelog/update-payment-activity-disputes-tooltip
  client/components/payment-activity/payment-activity-data.tsx
Labels: pr: needs review

#8983 Save selected date preset into session
  changelog/update-8972-save-payment-activity-preset-session
  client/components/payment-activity/hooks.ts
  client/components/payment-activity/index.tsx
Labels: pr: ready to merge

#8995 GH Actions - Update direct usage of GitHub context in workflows + Update Code owners
  .github/CODEOWNERS
  .github/workflows/post-release-updates.yml
  .github/workflows/release-code-freeze.yml
  changelog/gh-actions-fix-script-injection-vulnerabilities
Labels: pr: ready to merge, category: devops

#9009 Revert route validation
  changelog/revert-8901-update-route-param-validation
  includes/admin/class-wc-rest-payments-authorizations-controller.php
  includes/admin/class-wc-rest-payments-charges-controller.php
  includes/admin/class-wc-rest-payments-customer-controller.php
  includes/admin/class-wc-rest-payments-deposits-controller.php
  includes/admin/class-wc-rest-payments-disputes-controller.php
  includes/admin/class-wc-rest-payments-files-controller.php
  includes/admin/class-wc-rest-payments-fraud-outcomes-controller.php
  includes/admin/class-wc-rest-payments-orders-controller.php
  includes/admin/class-wc-rest-payments-payment-intents-controller.php
  includes/admin/class-wc-rest-payments-reader-controller.php
  includes/admin/class-wc-rest-payments-terminal-locations-controller.php
  includes/admin/class-wc-rest-payments-timeline-controller.php
  includes/admin/class-wc-rest-payments-transactions-controller.php
  includes/reports/class-wc-rest-payments-reports-authorizations-controller.php
  includes/reports/class-wc-rest-payments-reports-transactions-controller.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: ready to merge

#9018 Speedup PHPUnit tests
  changelog/update-speedup-phpunit-tests
  tests/WCPAY_UnitTestCase.php
  tests/unit/test-data/ip-geolocation.json
  tests/unit/woopay/test-class-woopay-utilities.php
Labels: pr: ready to merge

#8988 Add support for button styling for ECE buttons
  changelog/add-8951-support-style-settings-with-ece-buttons
  client/express-checkout/blocks/components/express-checkout-container.js
  client/express-checkout/blocks/hooks/use-express-checkout.js
  client/express-checkout/index.js
  client/express-checkout/utils/index.ts
Labels: pr: needs design review, needs design

#8996 Fix transactions search view when it has too many search terms
  changelog/fix-8781-transaction-search-fields
  client/transactions/list/style.scss
Labels: pr: ready to merge

#9013 Fix transaction/document list advanced filter styling issue preventing dates to be input on mobile screens
  changelog/fix-8782-transaction-list-data-filters-mobile
  client/deposits/filters/index.js
  client/deposits/list/test/__snapshots__/index.tsx.snap
  client/disputes/filters/index.tsx
  client/disputes/test/__snapshots__/index.tsx.snap
  client/documents/filters/index.tsx
  client/documents/filters/style.scss
  client/style.scss
  client/transactions/filters/index.tsx
  client/transactions/filters/style.scss
Labels: pr: ready to merge

#8388 Change plugin WP.org author to WooCommerce
  changelog/update-8385-plugin-wporg-author
  woocommerce-payments.php
Labels: pr: ready to merge

#9015 Minor updates to Tracks onboarding events props
  changelog/update-tracks-onboarding-events-props
  client/connect-account-page/index.tsx
  includes/class-wc-payments-account.php
  includes/class-wc-payments-onboarding-service.php
  tests/unit/test-class-wc-payments-account.php
Labels: pr: ready to merge

#8590 Refactor redirects logic in payments
  changelog/dev-7654-refactor-redirects-logic-in-payments
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-redirect-service.php
  includes/class-wc-payments.php
  tests/unit/admin/test-class-wc-payments-admin.php
  tests/unit/test-class-wc-payments-account-capital.php
  tests/unit/test-class-wc-payments-account-link.php
  tests/unit/test-class-wc-payments-account.php
  tests/unit/test-class-wc-payments-redirect-service.php
Labels: pr: ready to merge
