Repository Automattic/woocommerce-payments, pull requests merged in 2024-09, with the labels that each got.

#9388 Bump required PHP version to 7.3
  changelog/update-required-php-version
  composer.json
  composer.lock
Labels: focus: devops

#9380 Update continue onboarding to use embedded component
  changelog/update-9357-continue-onboarding-links-in-embedded-component
  client/index.js
  client/onboarding/index.tsx
  client/onboarding/kyc/index.tsx
  client/onboarding/steps/embedded-kyc.tsx
  client/onboarding/steps/test/embedded-onboarding.tsx
  client/onboarding/types.ts
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-onboarding-controller.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-onboarding-service.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/admin/test-class-wc-rest-payments-onboarding-controller.php
  tests/unit/test-class-wc-payments-account.php
  tests/unit/test-class-wc-payments-onboarding-service.php
Labels: pr: ready to merge

#9394 Add Feature Flag for Embedded KYC
  changelog/dev-9252-feature-flag-embedded-kyc
  client/globals.d.ts
  client/index.js
  client/onboarding/index.tsx
  client/onboarding/steps/loading.tsx
  client/onboarding/steps/test/loading.tsx
  client/onboarding/types.ts
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-features.php
  tests/unit/test-class-wc-payments-account.php
  tests/unit/test-class-wc-payments-features.php
Labels: pr: needs review

#9400 Fix and improve admin child pages redirections logic
  changelog/fix-9395-account-data-force-refresh-on-wcpay-pages
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-account.php
  tests/unit/admin/test-class-wc-payments-admin.php
Labels: pr: ready to merge

#9383 Add ExPlat experiment: Payments task onboarding flow skips Connect page
  changelog/add-9382-explat-experiment-payments-task-onboarding-flow-skips-connect-page
  client/onboarding/index.tsx
  client/onboarding/step.tsx
  client/onboarding/steps/embedded-kyc.tsx
  client/onboarding/steps/loading.tsx
  client/onboarding/tracking.ts
  client/utils/index.js
  includes/class-wc-payments-account.php
  includes/class-wc-payments-redirect-service.php
  includes/class-wc-payments-utils.php
  tests/unit/test-class-wc-payments-account.php
Labels: pr: ready to merge

#9403 Add active incentive ID to Payments task data to use in Tracks props
  changelog/update-9401-woopayments-incentive-to-payments-task-tracks-props
  includes/class-wc-payments-incentives-service.php
Labels: pr: ready to merge

#9411 Improve PHP unit tests handling of WP filters
  changelog/dev-improve-unit-tests-handling-of-filters
  tests/unit/core/service/test-class-wc-payments-customer-service-api.php
  tests/unit/fraud-prevention/test-class-buyer-fingerprinting-service.php
  tests/unit/multi-currency/test-class-analytics.php
  tests/unit/multi-currency/test-class-geolocation.php
  tests/unit/test-class-compatibility-service.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payments-account.php
  tests/unit/test-class-wc-payments-customer-service.php
  tests/unit/test-class-wc-payments-express-checkout-button-display-handler.php
  tests/unit/test-class-wc-payments-express-checkout-button-helper.php
  tests/unit/test-class-wc-payments-features.php
  tests/unit/test-class-wc-payments-incentives-service.php
  tests/unit/test-class-wc-payments-localization-service.php
  tests/unit/test-class-wc-payments-order-service.php
  tests/unit/test-class-wc-payments-payment-request-button-handler.php
  tests/unit/test-class-wc-payments-session-service.php
  tests/unit/test-class-wc-payments-woopay-button-handler.php
  tests/unit/woopay/class-woopay-scheduler-test.php
  tests/unit/woopay/test-class-woopay-session.php
  tests/unit/woopay/test-class-woopay-utilities.php
Labels: pr: ready to merge

#9412 Add rate limiter to compatibility data updates
  changelog/add-server-6156-compatibility-data-rate-limiter
  includes/class-compatibility-service.php
  includes/class-wc-payments-action-scheduler-service.php
  includes/class-wc-payments.php
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
  tests/unit/admin/test-class-wc-rest-payments-tos-controller.php
  tests/unit/test-class-compatibility-service.php
  tests/unit/test-class-wc-payments-action-scheduler-service.php
Labels: pr: needs review

#9433 Update Dockerfile to allow for more Xdebug configs
  changelog/dev-update-dockerfile-to-allow-more-xdebug-config
  docker/wordpress_xdebug/Dockerfile
Labels: pr: needs review

#9435 Improve our job scheduling service for more resilience
  changelog/fix-9434-action-scheduler-service-schedule-job-init
  composer.json
  composer.lock
  includes/class-wc-payments-action-scheduler-service.php
  includes/class-wc-payments-webhook-reliability-service.php
  tests/unit/test-class-compatibility-service.php
Labels: pr: ready to merge

#9436 Fixes to enable using the new KYC for progressive onboarding.
  changelog/dev-9393-embedded-kyc-po
  client/onboarding/kyc/index.tsx
  client/onboarding/steps/embedded-kyc.tsx
  client/onboarding/tracking.ts
  client/onboarding/utils.ts
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-onboarding-controller.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-onboarding-service.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: ready to merge

#9423 Migrate e2e tests for dispute response flows to Playwright
  changelog/e2e-migrate-dispute-challenge-accept-flows-to-playwright
  tests/e2e-pw/specs/merchant/merchant-disputes-respond.spec.ts
  tests/e2e-pw/utils/helpers.ts
  tests/e2e-pw/utils/merchant-navigation.ts
  tests/e2e/specs/wcpay/merchant/merchant-disputes-save-draft-challenge.spec.js
  tests/e2e/specs/wcpay/merchant/merchant-disputes-submit-losing.spec.js
  tests/e2e/specs/wcpay/merchant/merchant-disputes-submit-winning.spec.js
  tests/e2e/specs/wcpay/merchant/merchant-disputes-view-details-via-order-notice.spec.js
Labels: pr: ready to merge

#9445 Removing feature flag for Embedded KYC
  changelog/dev-remove-feature-flag
  client/globals.d.ts
  client/index.js
  client/onboarding/index.tsx
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-features.php
  tests/unit/test-class-wc-payments-account.php
  tests/unit/test-class-wc-payments-features.php
Labels: pr: ready to merge

#9381 Design updates for Embedded Components
  assets/images/woo-logo.svg
  changelog/dev-i4-design-updates
  client/onboarding/kyc/appearance.ts
  client/onboarding/kyc/index.tsx
  client/onboarding/step.tsx
  client/onboarding/strings.tsx
  client/onboarding/style.scss
  client/stylesheets/abstracts/_colors.scss
Labels: pr: needs review, pr: needs design review

#9466 Fix progressive onboarding broken e2e test
  changelog/dev-fix-po-test
  tests/e2e/specs/wcpay/merchant/merchant-progressive-onboarding.spec.js
Labels: pr: ready to merge

#9461 Show UTC label in date time column header of transactions CSV
  changelog/add-8522-utc-list-page-csv
  client/transactions/blocked/columns.tsx
  client/transactions/list/index.tsx
  client/transactions/list/test/index.tsx
Labels: pr: needs review

#9482 Settings - Display erroring bank notice on Settings > Payments > Deposits
  changelog/fix-8331-bank-error-notice-settings-deposit
  client/settings/deposits/index.js
  client/settings/deposits/test/index.test.js
Labels: pr: ready to merge
