Repository Automattic/woocommerce-payments, pull requests merged in 2024-01, with the labels that each got.

#7959 Fix broken dispute details UI
  changelog/fix-7958-transaction-details-dispute-details-broken-ui
  client/payment-details/order-details/test/__snapshots__/index.test.tsx.snap
  client/payment-details/summary/index.tsx
  client/payment-details/summary/style.scss
  client/payment-details/summary/test/__snapshots__/index.test.tsx.snap
  client/payment-details/test/__snapshots__/index.test.tsx.snap
Labels: pr: ready to merge

#7962 Hide the transaction details refund menu for non-refundable disputes
  changelog/fix-7960-transaction-refund-eligible-disputes-only
  client/disputes/utils.ts
  client/payment-details/summary/index.tsx
  client/payment-details/summary/test/index.test.tsx
Labels: pr: ready to merge

#7972 Fix missing transaction error when viewing orders placed in mismatched test mode
  changelog/fix-7967-disputed-order-notice-test-mode-check
  client/order/index.js
  includes/admin/class-wc-payments-admin.php
Labels: pr: ready to merge

#7979 Fix the typo for transaction controls label
  changelog/fix-7964-typo-for-transaction-actions
  client/payment-details/summary/index.tsx
  client/payment-details/summary/test/__snapshots__/index.test.tsx.snap
  client/payment-details/summary/test/index.test.tsx
  client/payment-details/test/__snapshots__/index.test.tsx.snap
Labels: type: bug, pr: ready to merge, category: accessibility

#7932 Expose WCPay refund transaction id for refund endpoint
  changelog/add-transaction-id-to-refund-endpoint
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-order-service.php
  tests/unit/test-class-wc-payments-order-service.php
Labels: pr: needs review

#7965 Use shared dispute utility function `isRefundable` for disputed order notice to improve code quality
  changelog/dev-refactor-order-dispute-refundable-util
  client/components/disputed-order-notice/index.js
Labels: pr: ready to merge, type: technical debt, category: refactor

#7989 Update underlying jetpack dependencies
  changelog/update-jetpack-dependencies
  composer.json
  composer.lock
  includes/class-wc-payments-payment-request-button-handler.php
Labels: pr: needs review

#7988 Restock order items when refunding in full from transaction details page
  changelog/fix-7969-restock-items-when-refund-from-transaction-page
  includes/admin/class-wc-rest-payments-refunds-controller.php
Labels: pr: ready to merge, component: streamline refunds

#7952 Add theme name to compatibility service
  changelog/add-3943-send-blog-theme-to-sift
  includes/class-compatibility-service.php
  tests/unit/test-class-compatibility-service.php
Labels: pr: ready to merge

#7998 Verify that order exists before offering "Partial refund" option on transaction details page
  changelog/fix-transaction-refund-options-for-missing-order
  client/payment-details/summary/index.tsx
Labels: pr: ready to merge, component: streamline refunds

#7933 Add active plugin list to compatibility service
  changelog/add-server-3942-compatibility-service-include-active-plugins
  includes/class-compatibility-service.php
  tests/unit/test-class-compatibility-service.php
Labels: pr: ready to merge

#7976 Add e2e test for dispute flow: viewing dispute details via the order notice
  changelog/add-7397-e2e-disputed-order-notice
  tests/e2e/specs/wcpay/merchant/merchant-disputes-view-details-via-order-notice.spec.js
Labels: pr: ready to merge

#7922 Exploration: Playwright GH action workflow
  .github/actions/e2e-pw/run-log-tests/action.yml
  .github/workflows/e2e-pw-pull-request.yml
Labels: pr: needs author reply

#8007 Fix Dropdown menu border defect
  changelog/fix-7991-blank-square-in-the-upper-left-corner-of-basic-filter-dropdowns-on-analytics-pages
  client/payment-details/summary/index.tsx
  client/payment-details/summary/style.scss
  client/payment-details/summary/test/__snapshots__/index.test.tsx.snap
  client/payment-details/test/__snapshots__/index.test.tsx.snap
Labels: pr: ready to merge

#7828 Pass currency and do not pass transaction_ids parameter to create instant deposit
  changelog/add-7711-instant-deposit-currency
  client/components/account-balances/test/index.test.tsx
  client/components/deposits-overview/test/index.tsx
  client/data/deposits/actions.js
  client/data/deposits/hooks.ts
  client/data/deposits/test/overviews.fixture.json
  client/deposits/instant-deposits/index.tsx
  client/deposits/instant-deposits/test/index.tsx
  client/types/account-overview.d.ts
  includes/admin/class-wc-rest-payments-deposits-controller.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: ready to merge

#8000 Compatibility Service: Send the post type count
  changelog/add-server-3944-compatibility-service-include-post-types
  includes/class-compatibility-service.php
  tests/unit/test-class-compatibility-service.php
Labels: pr: ready to merge

#8013 Allow issue of zero amount refunds
  changelog/fix-7984-allow-zero-amount-refunds
  includes/class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-refund.php
Labels: pr: needs review, component: streamline refunds

#8041 Show Payments → Overview waiting period notice for new accounts that have completed one or more transactions
  changelog/fix-8040-new-account-waiting-period-notice
  client/components/deposits-overview/index.tsx
  client/components/deposits-overview/style.scss
  client/components/deposits-overview/test/index.tsx
Labels: pr: ready to merge

#7945 Store balance transaction ID in order metadata
  changelog/update-7856-add-charge-txn-id-to-order-meta
  includes/admin/class-wc-rest-payments-orders-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-order-service.php
  includes/subscriptions/class-wc-payments-invoice-service.php
  src/Internal/Service/OrderService.php
  tests/unit/admin/test-class-wc-rest-payments-orders-controller.php
  tests/unit/helpers/class-wc-helper-intention.php
  tests/unit/payment-methods/test-class-upe-split-payment-gateway.php
  tests/unit/src/Internal/Service/OrderServiceTest.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-payment.php
  tests/unit/test-class-wc-payments-order-service.php
Labels: pr: ready to merge, component: reporting

#8010 Improve disputed order notice so is more readable and actionable (and not all in bold)
  changelog/fix-7568-tidy-disputed-order-notice
  client/components/disputed-order-notice/index.js
Labels: pr: ready to merge

#8030 Show the correct number of days in the new account waiting period notices (Payments Overview and Settings)
  changelog/fix-7970-clarify-calendar-days-waiting-period-notice
  client/components/deposits-overview/deposit-notices.tsx
  client/components/deposits-overview/test/index.tsx
  client/settings/deposits/index.js
  client/settings/deposits/test/index.test.js
Labels: pr: ready to merge

#8042 Use consistent inline notice style for deposit settings notices
  changelog/fix-6424-update-settings-deposit-notice-ui
  client/settings/deposits/index.js
  client/settings/deposits/style.scss
Labels: pr: ready to merge

#8020 Add events for interactions with transactions page
  changelog/add-7961-track-transactions-search
  client/transactions/declarations.d.ts
  client/transactions/filters/index.tsx
Labels: pr: needs review

#8049 Fix incorrect test mode notice when left KYC early after going live from builder mode
  changelog/fix-7819-incorrect-test-mode-notice
  includes/class-wc-payments-account.php
Labels: pr: ready to merge

#8033 Fix reverse WPCOM url in Safe Mode
  changelog/8025-fix-safe-mode-message-reverse-host
  woocommerce-payments.php
Labels: pr: ready to merge

#7925 Add ENUM class for country codes
  changelog/dev-7886-add-country-codes-enum
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-features.php
  includes/class-wc-payments-payment-request-button-handler.php
  includes/class-wc-payments-utils.php
  includes/class-wc-payments.php
  includes/constants/class-country-code.php
  includes/constants/class-payment-request-button-states.php
  includes/multi-currency/CountryFlags.php
  includes/multi-currency/MultiCurrency.php
  includes/payment-methods/class-affirm-payment-method.php
  includes/payment-methods/class-afterpay-payment-method.php
  includes/payment-methods/class-klarna-payment-method.php
  tests/unit/admin/tasks/test-class-wc-payments-task-disputes.php
  tests/unit/admin/test-class-wc-rest-payments-accounts-controller.php
  tests/unit/admin/test-class-wc-rest-payments-customer-controller.php
  tests/unit/admin/test-class-wc-rest-payments-onboarding-controller.php
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
  tests/unit/contants/test-class-country-code.php
  tests/unit/core/server/request/test-class-list-transactions-request.php
  tests/unit/core/service/test-class-wc-payments-customer-service-api.php
  tests/unit/fraud-prevention/test-class-buyer-fingerprinting-service.php
  tests/unit/fraud-prevention/test-class-fraud-risk-tools.php
  tests/unit/helpers/class-wc-helper-order.php
  tests/unit/migrations/test-class-update-service-data-from-server.php
  tests/unit/multi-currency/test-class-country-flags.php
  tests/unit/multi-currency/test-class-frontend-prices.php
  tests/unit/multi-currency/test-class-geolocation.php
  tests/unit/multi-currency/test-class-multi-currency.php
  tests/unit/reports/test-class-wc-rest-payments-reports-authorizations-controller.php
  tests/unit/reports/test-class-wc-rest-payments-reports-transactions-controller.php
  tests/unit/src/Internal/Service/Level3ServiceTest.php
  tests/unit/test-class-wc-payments-customer-service.php
  tests/unit/test-class-wc-payments-incentives-service.php
  tests/unit/test-class-wc-payments-localization-service.php
  tests/unit/test-class-wc-payments-onboarding-service.php
  tests/unit/test-class-wc-payments-payment-request-button-handler.php
  tests/unit/wc-payment-api/models/test-class-wc-payments-api-charge.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
  tests/unit/woopay/class-woopay-scheduler-test.php
Labels: pr: needs review

#8005 Update PO success modal
  assets/images/illustrations/po-eligibility.svg
  changelog/update-7579-po-success-modal
  client/components/confetti-animation/index.tsx
  client/overview/modal/progressive-onboarding-eligibility/index.tsx
  client/overview/modal/progressive-onboarding-eligibility/style.scss
  client/overview/modal/progressive-onboarding-eligibility/test/index.test.tsx
  client/overview/test/index.js
  package-lock.json
  package.json
Labels: pr: needs design review

#8028 Updates to use centralised account status function
  changelog/dev-centralize-account-status-logic
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-account.php
  tests/unit/admin/test-class-wc-payments-admin.php
  tests/unit/test-class-wc-payments-account.php
Labels: pr: ready to merge

#8060 Address QIT security errors
  changelog/fix-8059-qit-security-test-failed-in-develop-branch
  includes/class-wc-payments.php
  includes/multi-currency/MultiCurrency.php
Labels: pr: needs review

#8072 chore: remove unused generate_* functions
  changelog/chore-remove-unused-settings-generate-functions
  includes/class-wc-payment-gateway-wcpay.php
Labels: type: technical debt

#8083 Update confetti animation
  changelog/update-confetti-animation
  client/components/confetti-animation/index.tsx
Labels: pr: ready to merge

#8068 remove unnecessary tracks events for acceptDispute submit success/fail
  changelog/fix-remove-dispute-accept-log-tracks-events
  client/data/disputes/actions.js
Labels: pr: ready to merge

#8071 chore: remove unused customGatewayTitle
  changelog/frosso-clean-unused-custom-gateway-title
  client/utils/checkout.js
Labels: type: technical debt

#8089 fix: pay-for-order compatibility with other gateways
  changelog/fix-pay-for-order-compatibility-with-other-gateways
  client/checkout/classic/event-handlers.js
Labels: type: bug

#7848 Update deposits REST API docs with decoupled deposit changes
  changelog/fix-7847-update-deposits-api-docs-estimated-deposits-rm
  docs/rest-api/source/includes/wp-api-v3/deposits.md
Labels: pr: ready to merge

#8057 Remove redundant estimated deposit code
  changelog/fix-7850-remove-redundant-estimated-deposits-code
  client/components/account-balances/test/index.test.tsx
  client/components/deposits-overview/hooks.ts
  client/components/deposits-overview/test/index.tsx
  client/data/deposits/hooks.ts
  client/data/deposits/selectors.js
  client/data/deposits/test/overviews.fixture.json
  client/data/deposits/test/reducer.js
  client/data/deposits/test/resolvers.js
  client/data/deposits/test/selectors.js
  client/payment-details/timeline/map-events.js
  client/transactions/list/deposit.tsx
  client/types/account-overview.d.ts
  tests/fixtures/captured-payments/foreign-card.json
  tests/fixtures/captured-payments/fx-decimal.json
  tests/fixtures/captured-payments/fx-foreign-card.json
  tests/fixtures/captured-payments/fx-with-capped-fee.json
  tests/fixtures/captured-payments/fx.json
  tests/fixtures/captured-payments/only-base-fee.json
  tests/fixtures/captured-payments/subscription.json
  tests/unit/reports/test-class-wc-rest-payments-reports-transactions-controller.php
Labels: pr: ready to merge

#7990 Add compatibility data when onboarding
  changelog/update-4423-add-compatibility-data-when-onboarding
  includes/class-compatibility-service.php
  tests/unit/test-class-compatibility-service.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: ready to merge
