Repository Automattic/woocommerce-payments, pull requests merged in 2024-07, with the labels that each got.

#9036 Updates to Tracks onboarding events props - Take 2
  changelog/update-tracks-onboarding-events-props-take2
  client/connect-account-page/index.tsx
  includes/class-wc-payments-account.php
  includes/class-wc-payments-onboarding-service.php
  includes/class-wc-payments-redirect-service.php
  tests/unit/test-class-wc-payments-redirect-service.php
Labels: pr: ready to merge

#9031 Remove printed receipts mentions from WooPayments - those are hanled by WooCommerce now.
  changelog/change-9025-no-printed-receipts-in-wcpay
  client/card-readers/preview-receipt/index.tsx
  client/card-readers/preview-receipt/previewer.tsx
  client/card-readers/preview-receipt/receipt.tsx
  client/card-readers/preview-receipt/style.scss
  client/card-readers/preview-receipt/test/__snapshots__/preview-receipt.test.tsx.snap
  client/card-readers/preview-receipt/test/__snapshots__/printed-receipt-previewer.test.tsx.snap
  client/card-readers/preview-receipt/test/preview-receipt.test.tsx
  client/card-readers/preview-receipt/test/printed-receipt-previewer.test.tsx
  client/card-readers/settings/index.tsx
  client/card-readers/settings/test/__snapshots__/index.test.tsx.snap
  client/index.js
  includes/admin/class-wc-payments-admin.php
Labels: pr: ready to merge

#9030 Update the API client to validate route params before making a request
  changelog/update-route-regex-validation
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: ready to merge

#9044 Add Docker support for local mu plugins
  .gitignore
  changelog/dev-add-docker-support-for-local-mu-plugins
  docker-compose.yml
  docker/README.md
  docker/mu-plugins/.gitkeep
Labels: pr: ready to merge, type: developer experience

#9010 [ECE] Add button radius support
  changelog/add-ece-button-radius-support
  client/checkout/woopay/express-button/woopay-express-checkout-button.js
  client/checkout/woopay/style.scss
  client/data/settings/actions.js
  client/data/settings/hooks.js
  client/data/settings/selectors.js
  client/express-checkout/blocks/hooks/use-express-checkout.js
  client/express-checkout/utils/index.ts
  client/globals.d.ts
  client/settings/express-checkout-settings/general-payment-request-button-settings.js
  client/settings/express-checkout-settings/index.scss
  client/settings/express-checkout-settings/payment-request-button-preview.js
  client/settings/express-checkout-settings/test/index.js
  client/settings/express-checkout-settings/test/payment-request-settings.test.js
  client/utils/express-checkout/index.js
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-wc-payments-features.php
  includes/class-wc-payments-woopay-button-handler.php
  includes/express-checkout/class-wc-payments-express-checkout-button-handler.php
  includes/express-checkout/class-wc-payments-express-checkout-button-helper.php
Labels: needs design

#8987 Add ECE support for multiple product types
  changelog/as-8871-ece-on-supported-product-types
  client/express-checkout/event-handlers.js
  client/express-checkout/index.js
  client/express-checkout/utils/index.ts
  includes/express-checkout/class-wc-payments-express-checkout-ajax-handler.php
  includes/express-checkout/class-wc-payments-express-checkout-button-handler.php
  includes/express-checkout/class-wc-payments-express-checkout-button-helper.php
  includes/fraud-prevention/class-fraud-prevention-service.php
  psalm-baseline.xml
Labels: pr: needs review

#9072 Reporting: Restore functioning of 'remove' button on last tag on transactions report search box
  changelog/fix-9071-transaction-search-tag-close-button
  client/transactions/list/style.scss
Labels: pr: ready to merge

#9097 Bump WC tested up to version to 9.1.2
  changelog/dev-bump-wc-version-9-1-2
  woocommerce-payments.php
Labels: pr: ready to merge

#9081 [ECE] Add ECE support for WooCommerce Deposits.
  changelog/as-ece-wc-deposits-support
  client/express-checkout/index.js
  includes/express-checkout/class-wc-payments-express-checkout-ajax-handler.php
  includes/express-checkout/class-wc-payments-express-checkout-button-helper.php
  psalm-baseline.xml
Labels: pr: needs review

#9120 Fix Payments Settings originated onboarding flow - for patch release 7.9.2
  changelog/fix-payments-settings-originated-onboarding-flow
  includes/class-wc-payments-account.php
  includes/class-wc-payments-onboarding-service.php
  readme.txt
Labels: pr: ready to merge

#9134 Allow the purchase of physical subscriptions using ECE if no shipping options are defined
  changelog/9106-ece-checkout-fails-for-physical-subscription-product-if-no-shipping-methods-are-configured
  includes/express-checkout/class-wc-payments-express-checkout-button-handler.php
  tests/unit/test-class-wc-payments-express-checkout-button-helper.php
Labels: pr: needs review

#9147 Disable WooPay if WooPayments is not enabled as payment gateway
  changelog/as-disable-dc-if-woopayments-disabled
  includes/class-wc-payments-features.php
  tests/unit/test-class-wc-payments-features.php
Labels: pr: needs review

#9152 Fix Jetpack Sync config
  changelog/fix-9151-jeptack-sync-config
  woocommerce-payments.php
Labels: pr: needs review

#9171 Reorder onboarding wizard business types options to have company first
  changelog/update-reorder-business-types-with-company-first
  client/onboarding/steps/business-details.tsx
Labels: pr: needs review

#9179 Update bundle size checker version to support node v20
  .github/workflows/bundle-size.yml
  changelog/dev-update-bundle-size-check-node-version
Labels: pr: ready to merge

#9162 Reporting - Match Payment widget numbers to the totals seen in reports
  changelog/fix-server-5934-payment-widget-data-mismatch
  client/components/payment-activity/payment-activity-data.tsx
  client/components/payment-activity/test/index.test.tsx
  client/globals.d.ts
  includes/admin/class-wc-rest-payments-reporting-controller.php
Labels: pr: needs review

#9182 Translate hardcoded untranslated strings on the Connect page
  changelog/fix-connect-page-untranslated-strings
  client/connect-account-page/index.tsx
  client/connect-account-page/strings.tsx
Labels: pr: ready to merge, component: onboarding, focus: account lifecycle

#9190 Match the Node version in nvm with the minimum version in package.json
  .nvmrc
  changelog/update-nvm-node-version
Labels: pr: ready to merge
