Repository Automattic/woocommerce-payments, pull requests merged in 2024-05, with the labels that each got.

#8687 Reporting: Track events for `View report` links on Payment activity widget
  changelog/add-8686-track-events-payment-activity-widget
  client/components/payment-activity/payment-activity-data.tsx
  client/components/payment-activity/payment-data-tile.tsx
  client/tracks/event.d.ts
Labels: pr: needs review

#8739 Allow non-account-owner admin users to submit the payment activity survey
  changelog/fix-8710-payment-activity-survey-all-admin-users
  includes/admin/class-wc-rest-payments-survey-controller.php
  includes/wc-payment-api/class-wc-payments-http.php
  tests/unit/admin/test-class-wc-rest-payments-survey-controller.php
Labels: pr: ready to merge

#8726 Reporting: Fix the `View report` link URL on Total payment volume tile, within Payment activity widget
  changelog/fix-8706-tpv-view-report-link
  client/components/payment-activity/payment-activity-data.tsx
  client/components/payment-activity/test/__snapshots__/index.test.tsx.snap
  client/transactions/list/style.scss
Labels: pr: ready to merge

#8756 Split Payment Activity Empty State to separate component to clarify logic and prevent erroneous network call
  client/components/payment-activity/index.tsx
Labels: pr: ready to merge

#8766 Update View Report link of Charges data highlight tile.
  changelog/fix-8705-charges-view-report
  client/components/payment-activity/payment-activity-data.tsx
  client/components/payment-activity/test/__snapshots__/index.test.tsx.snap
Labels: pr: ready to merge

#8759 Reporting: Fix the `View report` link on the Refunds tile of Payment activity widget
  changelog/fix-8702-fix-refunds-view-report-link
  client/components/payment-activity/payment-activity-data.tsx
  client/components/payment-activity/test/__snapshots__/index.test.tsx.snap
Labels: pr: ready to merge

#8390 Terminal In-Person Payments auto-renewing subscription support
  changelog/terminal-payment-subscription-support
  includes/admin/class-wc-rest-payments-orders-controller.php
  includes/class-wc-payments-token-service.php
  includes/class-wc-payments.php
  psalm-baseline.xml
  tests/unit/admin/test-class-wc-rest-payments-orders-controller.php
  tests/unit/helpers/class-wc-helper-subscriptions.php
Labels: pr: needs review, category: engineering, component: card present, category: projects, component: wc subscriptions integration, php, focus: subscriptions

#8762 Add notice and notification in Advanced Fraud Settings page
  changelog/fix-6497-advanced-fraud-settings-empty
  client/settings/fraud-protection/advanced-settings/index.tsx
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/index.test.tsx.snap
  client/settings/fraud-protection/advanced-settings/test/index.test.tsx
  client/settings/fraud-protection/style.scss
Labels: pr: ready to merge

#8767 Updated requests classes documentation to link to correct README
  changelog/fix-update-request-classes-docs
  includes/core/server/request/class-add-account-tos-agreement.md
  includes/core/server/request/class-cancel-intention.md
  includes/core/server/request/class-capture-intention.md
  includes/core/server/request/class-create-and-confirm-intention.md
  includes/core/server/request/class-create-and-confirm-setup-intention.md
  includes/core/server/request/class-create-intention.md
  includes/core/server/request/class-create-setup-intention.md
  includes/core/server/request/class-get-account-capital-link.md
  includes/core/server/request/class-get-account-login-data.md
  includes/core/server/request/class-get-account.md
  includes/core/server/request/class-get-charge.md
  includes/core/server/request/class-get-intention.md
  includes/core/server/request/class-get-request.md
  includes/core/server/request/class-get-setup-intention.md
  includes/core/server/request/class-list-authorizations.md
  includes/core/server/request/class-list-charge-refunds.md
  includes/core/server/request/class-list-deposits.md
  includes/core/server/request/class-list-disputes.md
  includes/core/server/request/class-list-documents.md
  includes/core/server/request/class-list-fraud-outcome-transactions.md
  includes/core/server/request/class-list-transactions.md
  includes/core/server/request/class-refund-charge.md
  includes/core/server/request/class-update-account.md
  includes/core/server/request/class-update-intention.md
  includes/core/server/request/class-woopay-create-and-confirm-intention.md
  includes/core/server/request/class-woopay-create-and-confirm-setup-intention.md
  includes/core/server/request/class-woopay-create-intent.md
Labels: pr: ready to merge

#8743 Pass merchant timezone to Reporting Payment Activity API
  changelog/fix-8742-merchant-timezone-payment-activity
  client/components/payment-activity/payment-activity-data.tsx
  client/data/payment-activity/test/hooks.test.ts
  client/data/payment-activity/test/resolver.test.ts
  client/data/payment-activity/types.d.ts
  includes/core/server/request/class-get-reporting-payment-activity.md
  includes/core/server/request/class-get-reporting-payment-activity.php
Labels: pr: ready to merge

#8763 Upgrade jetpack sync package version
  changelog/fix-update-jetpack-sync-package
  composer.json
  composer.lock
Labels: pr: needs review

#8780 Fix/5223 payment activity adjustment
  changelog/fix-5223-payment-activity-adjustment
  client/components/payment-activity/payment-activity-data.tsx
  client/components/payment-activity/test/__snapshots__/index.test.tsx.snap
Labels: pr: ready to merge

#8792 Reporting: Fix `View report` link on Disputes tile in Payment activity widget
  changelog/fix-8704-fix-disputes-view-report-link
  client/components/payment-activity/payment-activity-data.tsx
  client/components/payment-activity/test/__snapshots__/index.test.tsx.snap
Labels: pr: needs review

#8789 Parameterize Xdebug remote host in Dockerfile.
  changelog/update-parameterize-xdebug-host-dockerfile
  docker/wordpress_xdebug/Dockerfile
Labels: focus: devops

#8777 Remove auto redirect to WooPay on page load
  changelog/as-remove-auto-redirect
  client/checkout/woopay/email-input-iframe.js
  client/checkout/woopay/express-button/test/woopay-express-checkout-button.test.js
  client/components/woopay/save-user/test/checkout-page-save-user.test.js
  client/tracks/event.d.ts
Labels: pr: needs review

#8755 Re-removed deprecated depositsStatus key from account status
  changelog/delete-4710-remove-deposit_status
  client/globals.d.ts
  includes/class-wc-payments-account.php
Labels: pr: ready to merge

#8785 Add unit test for Get_Reporting_Payment_Activity.
  changelog/add-8779-unit-test-get-reporting-payment-activity
  tests/unit/core/server/request/test-class-core-get-reporting-payment-activity-request.php
Labels: pr: ready to merge

#8805 WooPayment REST: conditional initialization.
  changelog/add-8797-conditional-rest-apis-init
  includes/class-wc-payments.php
  includes/multi-currency/MultiCurrency.php
Labels: pr: ready to merge

#8751 Move `usePaymentActivityData()` to `PaymentActivity` because filters will need it
  changelog/update-8733-move-payment-activity-data-fetching
  client/components/payment-activity/index.tsx
  client/components/payment-activity/payment-activity-data.tsx
  client/components/payment-activity/test/__snapshots__/index.test.tsx.snap
Labels: pr: ready to merge

#8848 Update sandbox mode notice tooltip copy
  changelog/update-sandbox-mode-notice-tooltip-copy
  client/overview/index.js
Labels: pr: ready to merge

#8859 Update to not open in new tab if onboarding not complete
  changelog/dev-finish-setup-cta
  client/components/account-status/account-tools/index.tsx
  client/components/account-status/account-tools/test/__snapshots__/index.test.tsx.snap
  client/components/account-status/test/__snapshots__/index.js.snap
  client/overview/task-list/tasks/update-business-details-task.tsx
Labels: pr: ready to merge
