Repository Automattic/woocommerce-payments, pull requests merged in 2024-03, with the labels that each got.

#8273 Added small separator line between converted currency and the next line item
  changelog/fix-7504-ui-fix-transaction-details
  client/payment-details/summary/index.tsx
  client/payment-details/summary/style.scss
Labels: pr: ready to merge

#8274 Reduce multiple urgent dispute signals
  client/payment-details/dispute-details/dispute-due-by-date.tsx
  client/payment-details/dispute-details/dispute-steps.tsx
Labels: pr: ready to merge

#8308 Prevent sending shopper emails when disputes are closed
  changelog/fix-7928-prevent-sending-order-complete-emails
  includes/class-wc-payments-order-service.php
Labels: pr: ready to merge

#8312 Refactor - `isInquiry` utility function to accept only dispute status as param
  changelog/refactor-7085-pass-only-dispute-status-as-param
  client/components/disputed-order-notice/index.js
  client/disputes/test/utils.test.ts
  client/disputes/utils.ts
  client/payment-details/dispute-details/dispute-awaiting-response-details.tsx
  client/payment-details/dispute-details/dispute-notice.tsx
Labels: pr: ready to merge, component: disputes, category: refactor

#8313 Load deposit overview only when deposit is present
  changelog/fix-7785-non-exisiting-deposit
  client/deposits/details/index.tsx
  client/deposits/details/test/__snapshots__/index.tsx.snap
  client/deposits/details/test/index.tsx
Labels: pr: ready to merge

#8315 Hide Refund in Full option when a partial refund has already happened
  changelog/fix-8210-error-when-attempting-to-fully-refund-remaining-amount-after-partial-refund
  client/payment-details/summary/index.tsx
  client/payment-details/summary/test/index.test.tsx
Labels: pr: ready to merge

#8323 Inform hard blocked merchants they're under review
  changelog/fix-server-4691-inform-merchants-about-under-review
  client/components/account-status/status-chip.js
  client/components/account-status/test/__snapshots__/index.js.snap
  client/components/account-status/test/index.js
  client/components/deposits-status/index.tsx
  client/overview/index.js
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-account.php
Labels: pr: ready to merge

#8343 E2E: apply fix for`merchant-orders-status-change` in `trunk`
  tests/e2e/specs/wcpay/merchant/merchant-orders-status-change.spec.js
Labels: pr: ready to merge

#8200 Handle refunded webhook event
  changelog/update-8085-refunds-revisit-events-handling-externally-sourced-refunds-are-not-changing-order-state-not-rtacked-in-order-notes
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-order-service.php
  includes/class-wc-payments-webhook-processing-service.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-refund.php
  tests/unit/test-class-wc-payments-order-service.php
  tests/unit/test-class-wc-payments-webhook-processing-service.php
Labels: pr: needs review

#8341 Fix: Only Apply Woopay Direct Checkout Flow to the “Proceed to Checkout” Button, in Classic Cart
  changelog/fix-classic-cart-direct-checkout-button-click
  client/checkout/woopay/direct-checkout/woopay-direct-checkout.js
Labels: type: bug, component: WooPay

#8355 E2E: skip failing test suite `shopper-bnpls-checkout`
  tests/e2e/specs/wcpay/shopper/shopper-bnpls-checkout.spec.js
Labels: pr: ready to merge

#8358 E2E: skip failing test suite `shopper-bnpls-checkout` (#8355)
  changelog/e2e-skip-broken-test-shopper-bnpls-checkout-develop
  tests/e2e/specs/wcpay/shopper/shopper-bnpls-checkout.spec.js
Labels: pr: needs review

#8336 Reset onboarding stored test mode when reonboarding without URL param
  changelog/fix-8334-leftover-onboarding-sandbox-mode
  includes/class-wc-payments-account.php
Labels: pr: ready to merge

#8320 Validate deposit id before fetching deposit in `getDeposit()`
  changelog/update-deposit-details-validate-user-input
  client/data/deposits/resolvers.js
  client/data/deposits/test/resolvers.js
Labels: pr: needs review

#8337 Implement a feature flag for the Payment Overview widget
  changelog/add-8242-payment-overview-widget-feature-flag
  client/globals.d.ts
  includes/class-wc-payments-features.php
Labels: pr: needs review

#8371 Disputes: Update a more clear order note for dispute fund withdrawn event
  changelog/fix-6380-edit-dispute-order-note
  includes/class-wc-payments-webhook-processing-service.php
  tests/unit/test-class-wc-payments-webhook-processing-service.php
Labels: pr: ready to merge

#8369 Set background-size: cover to fix PM icon styling issue
  assets/css/admin.css
  assets/css/admin.rtl.css
  changelog/fix-7183-pm-icon-styling-issue-in-transaction-details-page
Labels: pr: ready to merge

#8338 Add WC Blocks webpack-rtl-plugin implementation to the project
  changelog/chore-use-a8c-webpack-rtl-plugin
  package-lock.json
  package.json
  webpack/shared.js
  webpack/webpack-rtl-plugin.js
Labels: pr: needs review

#8321 Added notice to inform merchant that their bank account has an error
  changelog/add-6294-deposit-account-error-notice
  client/components/account-balances/test/index.test.tsx
  client/components/deposits-overview/deposit-notices.tsx
  client/components/deposits-overview/index.tsx
  client/components/deposits-overview/test/__snapshots__/index.tsx.snap
  client/components/deposits-overview/test/index.tsx
  client/types/account-overview.d.ts
Labels: pr: ready to merge

#8374 Deposits: Clean up remnant code from past A/B Experiment on Deposit List
  assets/css/admin.css
  changelog/update-6224-clean-up-old-experiment-code
  includes/admin/class-wc-payments-admin.php
Labels: pr: ready to merge

#8376 Removed deprecated deposit_status key from account status
  changelog/dev-4710-remove-deposit-status
  client/globals.d.ts
  includes/class-wc-payments-account.php
Labels: pr: ready to merge

#8364 Updated the rest api docs for `deposits/overview-all`
  changelog/add-8346-deposits-overview-docs
  docs/rest-api/source/includes/wp-api-v3/deposits.md
Labels: pr: ready to merge

#8375 Client side routing to improve the navigation times for "View Deposit History"
  changelog/fix-6527-improved-navigation-time
  client/components/deposits-overview/index.tsx
  client/components/deposits-overview/test/__snapshots__/index.tsx.snap
Labels: pr: ready to merge

#8347 Adds notice that deposits are paused to Deposits Listing screen
  changelog/add-8332-deposits-list-failure-notice
  client/deposits/index.tsx
Labels: pr: ready to merge

#8422 Allow WooPay button preview on settings page
  changelog/fix-woopay-button-preview-style
  includes/class-wc-payments-blocks-payment-method.php
Labels: focus: woopay

#8425 Allow Sandbox accounts to be deleted at any moment of the account lifecycle
  changelog/add-account-reset-for-sandboxes
  client/components/account-status/account-tools/index.tsx
  client/components/account-status/account-tools/strings.tsx
  client/components/account-status/index.js
  client/overview/modal/reset-account/strings.tsx
  includes/class-wc-payments-account.php
Labels: pr: ready to merge

#8431 Make cursor disabled when hovering over disabled checkboxes
  changelog/fix-cursor-pointer-for-disabled-logging
  client/settings/advanced-settings/style.scss
Labels: pr: needs review

#8432 Revert removing depositsStatus key from account request.
  changelog/dev-4710-remove-deposit-status
  changelog/revert-8376-removed-depositsstatus
  client/globals.d.ts
  includes/class-wc-payments-account.php
Labels: pr: ready to merge

#8420 Create e2e test report issue template
  .github/ISSUE_TEMPLATE/e2e_test_report.md
  changelog/chore-e2e-test-report-template
Labels: category: e2e

#8410 Minor copy improvements on the Settings page
  changelog/update-7299-general-settings-desc
  client/components/payment-methods-list/payment-method.tsx
  client/payment-methods/delete-modal.tsx
  client/settings/settings-manager/index.js
Labels: pr: ready to merge

#8430 Move test notice for transactions to the top
  assets/css/admin.rtl.css
  changelog/fix-7733-minor-test-mode-notice-adjustments-for-transactions
  client/transactions/index.tsx
  client/transactions/style.scss
Labels: pr: ready to merge

#8441 Bump WC tested up to 8.7.0 and set Requires Plugins header.
  changelog/2024-03-22-10-13-01-959432
  woocommerce-payments.php
Labels: pr: ready to merge

#8442 Update/jetpack sync options
  changelog/update-jetpack-sync-options
  woocommerce-payments.php
Labels: pr: ready to merge

#8378 Update the Payments Connect page design and logic
  assets/images/cards/cb.svg
  assets/images/cards/diners.svg
  assets/images/payment-methods/afterpay-logo.svg
  changelog/update-8310-redesign-payments-connect-page
  client/components/banner-notice/style.scss
  client/components/tip-box/index.tsx
  client/components/tip-box/style.scss
  client/connect-account-page/index.tsx
  client/connect-account-page/info-notice-modal.tsx
  client/connect-account-page/payment-methods.tsx
  client/connect-account-page/strings.tsx
  client/connect-account-page/style.scss
  client/connect-account-page/test/__snapshots__/index.test.tsx.snap
  client/connect-account-page/test/index.test.tsx
  client/connect-account-page/test/info-notice-modal.test.tsx
  client/onboarding/index.tsx
  client/onboarding/steps/mode-choice.tsx
  client/onboarding/steps/test/mode-choice.tsx
  client/onboarding/strings.tsx
  client/onboarding/tracking.ts
  client/onboarding/types.ts
  client/payment-methods-icons.tsx
  client/tracks/event.d.ts
  includes/class-wc-payments-account.php
Labels: pr: ready to merge

#8433 Added empty check on meta key and meta value getting order id from meta values
  changelog/fix-4393-fix-quering-order-by-empty-metakey
  includes/class-wc-payments-db.php
  tests/unit/test-class-wc-payments-db.php
Labels: pr: needs review

#8426 Reduce Amount of Steps in the MOX
  changelog/dev-8311-reduce-mox
  client/components/custom-select-control/style.scss
  client/components/form/fields.tsx
  client/components/form/test/fields.tsx
  client/components/grouped-select-control/style.scss
  client/components/inline-notice/index.tsx
  client/components/inline-notice/styles.scss
  client/connect-account-page/style.scss
  client/globals.d.ts
  client/onboarding/context.tsx
  client/onboarding/form.tsx
  client/onboarding/index.tsx
  client/onboarding/restored-state-banner.tsx
  client/onboarding/step.tsx
  client/onboarding/steps/business-details.tsx
  client/onboarding/steps/loading.tsx
  client/onboarding/steps/personal-details.tsx
  client/onboarding/steps/test/business-details.tsx
  client/onboarding/steps/test/personal-details.tsx
  client/onboarding/strings.tsx
  client/onboarding/style.scss
  client/onboarding/test/context.tsx
  client/onboarding/test/form.tsx
  client/onboarding/test/validation.ts
  client/onboarding/types.ts
  client/onboarding/utils.ts
  client/onboarding/validation.ts
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-onboarding-controller.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-onboarding-service.php
  tests/unit/admin/test-class-wc-rest-payments-onboarding-controller.php
  tests/unit/test-class-wc-payments-onboarding-service.php
Labels: pr: needs review

#8399 remove redundant text
  changelog/fix-8278-remove-redundant-text
  client/overview/connection-sucess-notice.tsx
Labels: pr: needs review

#8444 Fix Incorrect Warning Notice for Puerto Rico and auto-select United States in onboarding
  changelog/fix-puerto-rico-incorrect-warning
  client/onboarding/steps/business-details.tsx
  includes/class-wc-payments-utils.php
  includes/constants/class-country-code.php
Labels: pr: needs review

#8458 Remove discount terms and conditions link from payment method fees pill
  changelog/fix-8448-remove-payment-method-fees-discount-tc-link
  client/utils/account-fees.tsx
Labels: pr: ready to merge

#8473 Fix WordPress.Security phpcs report in Check model
  changelog/fix-8470-phpcs-report
  includes/fraud-prevention/models/class-check.php
Labels: pr: needs review

#8478 Disputes: Address new PHPCS error
  changelog/fix-8465-fix-phpcs-new-disputes-errors
  includes/core/server/request/class-list-disputes.php
Labels: pr: ready to merge

#8463 Add way to prepopulate MCC on MOX
  changelog/8446-woo-core-verticals
  client/globals.d.ts
  client/onboarding/index.tsx
  client/onboarding/steps/test/business-details.tsx
  client/onboarding/utils.ts
Labels: pr: needs review

#8479 Update MOX cancellation to consistently redirect back to the payment connect page
  changelog/update-8447-always-redirect-to-payment-connect
  client/onboarding/index.tsx
Labels: pr: ready to merge

#8412 Reporting: Add a parent wrapper component for Payment Activity
  changelog/add-8389-create-payment-activity-wrapper
  client/components/payment-activity/index.tsx
  client/components/payment-activity/style.scss
  client/components/payment-activity/test/__snapshots__/index.tsx.snap
  client/components/payment-activity/test/index.tsx
  client/overview/index.js
Labels: pr: ready to merge

#8508 Fix merchant onboarding e2e tests after recent changes
  changelog/fix-merchant-onboarding-e2e-tests
  tests/e2e/specs/wcpay/merchant/merchant-progressive-onboarding.spec.js
Labels: pr: needs review

#8450 Remove ToS acceptance copy from all entrypoints in MOX
  changelog/add-8167-remove-tos-links-that-are-not-needed-anymore
  client/connect-account-page/strings.tsx
  includes/class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge

#8400 Resolve collision between WooPayments header and Woo Express survey banner
  changelog/fix-8093-onboarding-collides-with-jitm-banners
  client/onboarding/style.scss
Labels: pr: ready to merge

#8509 Fix/8465 fix phpcs reports
  changelog/fix-8465-fix-phpcs-reports
  includes/class-payment-information.php
  includes/class-wc-payments-order-service.php
  includes/class-wc-payments-status.php
  includes/core/server/class-request.php
  includes/core/server/request/class-create-and-confirm-setup-intention.php
  includes/in-person-payments/class-wc-payments-in-person-payments-receipts-service.php
  src/Container.php
  src/Internal/DependencyManagement/DelegateContainer/LegacyContainer.php
  src/Internal/DependencyManagement/ExtendedContainer.php
  src/Internal/Payment/PaymentRequest.php
  src/Internal/Payment/State/AbstractPaymentState.php
  src/Internal/Payment/State/InitialState.php
  src/Internal/Payment/State/StateFactory.php
  src/Internal/Proxy/LegacyProxy.php
  src/Internal/Service/MinimumAmountService.php
  src/Internal/Service/OrderService.php
Labels: pr: needs review
