Repository Automattic/woocommerce-payments, pull requests merged in 2024-11, with the labels that each got.

#9639 Add in-memory cache to DB cache to deal with DB write failures
  changelog/update-add-in-memory-cache-to-db-cache-to-deal-with-db-write-failures
  includes/class-database-cache.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-customer-service.php
  includes/class-wc-payments-incentives-service.php
  tests/unit/admin/test-class-wc-rest-payments-accounts-controller.php
  tests/unit/core/service/test-class-wc-payments-customer-service-api.php
  tests/unit/test-class-database-cache.php
Labels: pr: ready to merge

#9643 Rename deposit to payout in browser downloaded CSV filename and header.
  client/deposits/list/index.tsx
  client/deposits/list/test/index.tsx
Labels: pr: ready to merge

#9665 Rename anchor link to the deposit schedule section of the payments settings
  client/components/deposits-overview/index.tsx
  client/components/deposits-overview/test/__snapshots__/index.tsx.snap
  client/settings/settings-manager/index.js
Labels: pr: ready to merge

#9653 Rename 'deposit' to 'payout' on account connect / pre-onboarding page.
  client/connect-account-page/strings.tsx
  client/connect-account-page/test/__snapshots__/index.test.tsx.snap
  client/connect-account-page/test/info-notice-modal.test.tsx
Labels: pr: needs review

#9662 Avoid PHP warning when checking for StoreAPI requests
  changelog/fix-9661-avoid-php-warning
  includes/class-wc-payments-utils.php
  multi-currency/src/Utils.php
  tests/unit/test-class-wc-payments-utils.php
Labels: pr: ready to merge

#9674 Use @stripe/connect-js/pure
  changelog/fix-stripe-connect-breaks-underscore
  client/onboarding/steps/embedded-kyc.tsx
  client/onboarding/steps/test/embedded-onboarding.tsx
Labels: pr: needs review

#9669 Rename 'deposit' to 'payout' in dev docs
  changelog/dev-1-9601-rename-deposit-dev-docs
  docs/dependencies.md
  docs/rest-api/source/includes/wp-api-v3/payouts.md
  docs/rest-api/source/includes/wp-api-v3/reports.md
  docs/rest-api/source/index.html.md
Labels: pr: ready to merge

#9678 Enqueue order scripts for all available payment methods
  changelog/fix-8423-klarna-cant-undo-manual-refunds-and-process-refunds-again-via-woopayments
  client/order/refund-confirm-modal/index.js
  includes/admin/class-wc-payments-admin.php
Labels: pr: ready to merge

#9652 Record a tracks event when a merchant is redirected to a Stripe Capital loan offer
  changelog/fix-9651-record-tracks-event-capital-view-offer-redirect
  includes/class-wc-payments-redirect-service.php
Labels: pr: ready to merge

#9680 Add dismissable Notice to message the rename of Deposits to Payout
  changelog/add-9673-payouts-rename-notice
  client/deposits/details/index.tsx
  client/deposits/index.tsx
  client/deposits/rename-notice/header-image.svg
  client/deposits/rename-notice/index.tsx
  client/deposits/rename-notice/style.scss
  client/deposits/rename-notice/test/__snapshots__/index.tsx.snap
  client/deposits/rename-notice/test/index.tsx
  client/globals.d.ts
  client/overview/index.js
  client/overview/test/index.js
  composer.lock
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-features.php
  includes/class-wc-payments.php
Labels: pr: needs review

#9694 Fix e2e test for 8.5.0 release
  changelog/fix-e2e-test-8.5.0-release
  tests/e2e/specs/wcpay/merchant/merchant-admin-deposits.spec.js
Labels: pr: ready to merge

#9689 fix: E_DEPRECATED on BNPL empty PMME
  changelog/fix-deprecated-message-on-empty-pmme
  includes/class-wc-payments.php
Labels: size: x-small

#9701 Payouts: Change spotlight notice illustration
  changelog/fix-9700-payout-spotlight-illustration
  client/deposits/rename-notice/header-image.svg
Labels: pr: ready to merge

#9705 Handle IPP failure webhooks
  changelog/add-ipp-missing-failure-webhooks
  includes/class-wc-payments-webhook-processing-service.php
Labels: pr: needs review

#9706 Rename 'deposit' to 'payout' in readme.txt.
  changelog/update-9600-readme
  readme.txt
Labels: pr: ready to merge

#9712 Update E2E PW screenshots
  changelog/dev-update-pw-screenshots
  tests/e2e-pw/specs/merchant/__snapshots__/multi-currency-on-boarding.spec.ts/Multi-currency-on-boarding-Geolocation-feature-83665-tch-by-geolocation-correctly-with-USD-and-GBP-1.png
  tests/e2e-pw/specs/merchant/__snapshots__/multi-currency.spec.ts/Multi-currency-page-load-without-any-errors-1.png
Labels: size: x-small

#9691 Check that cart total is not zero before rendering express checkout
  changelog/fix-9687-express-checkout-visible-for-zero-amount-after-coupon-discount
  client/express-checkout/index.js
Labels: pr: needs review

#9715 chore: rename tokenized prb flag to ece
  changelog/chore-rename-tokenized-prb-flag-to-tokenized-ece
  client/checkout/blocks/index.js
  client/tokenized-payment-request/button-ui.js
  includes/class-wc-payments-blocks-payment-method.php
  includes/class-wc-payments-checkout.php
  includes/class-wc-payments-features.php
  includes/class-wc-payments-payment-request-button-handler.php
  includes/express-checkout/class-wc-payments-express-checkout-button-display-handler.php
  tests/unit/test-class-wc-payments-express-checkout-button-display-handler.php
  woocommerce-payments.php
Labels: size: x-small

#9729 fix: WooPay direct checkout docblock name
  changelog/fix-woopay-direct-checkout-docblock-name
  includes/class-wc-payments-woopay-direct-checkout.php
Labels: size: x-small

#9731 chore: rename wrapper from payment-request to ECE
  changelog/chore-payment-request-to-express-checkout-wrapper-name
  client/checkout/express-checkout-buttons.scss
  client/tokenized-payment-request/button-ui.js
  includes/express-checkout/class-wc-payments-express-checkout-button-display-handler.php
  tests/unit/test-class-wc-payments-express-checkout-button-display-handler.php
Labels: size: x-small

#9743 Update `upload-artifact` action to v4
  .github/actions/e2e-pw/run-log-tests/action.yml
  changelog/gh-update-actions-to-v4
Labels: pr: ready to merge, focus: devops

#9744 refactor: ECE utility for button UI interactions
  changelog/refactor-express-checkout-button-ui-utility
  client/express-checkout/button-ui.js
  client/express-checkout/index.js
Labels: size: x-small

#9754 chore: remove args from ece handlers
  changelog/chore-remove-arguments-passed-to-ece-handlers
  client/express-checkout/blocks/hooks/use-express-checkout.js
  client/express-checkout/index.js
  client/tokenized-express-checkout/blocks/hooks/use-express-checkout.js
  client/tokenized-express-checkout/index.js
Labels: size: x-small

#9741 Prevent challenging Klarna inquiries
  changelog/fix-9703-klarna-inquiries
  client/payment-details/dispute-details/dispute-awaiting-response-details.tsx
  client/payment-details/dispute-details/dispute-steps.tsx
  client/payment-details/summary/index.tsx
Labels: pr: needs review

#9758 chore: ECE phpunit test location fix
  changelog/chore-ece-php-tests-location
  tests/unit/express-checkout/test-class-wc-payments-express-checkout-button-display-handler.php
  tests/unit/express-checkout/test-class-wc-payments-express-checkout-button-helper.php
Labels: size: x-small

#9745 refactor: express checkout initialization page checks
  changelog/refactor-express-checkout-initialization-page-location
  client/express-checkout/index.js
  client/express-checkout/utils/index.ts
  client/tokenized-express-checkout/index.js
  client/tokenized-express-checkout/utils/index.ts
  includes/express-checkout/class-wc-payments-express-checkout-button-handler.php
Labels: size: x-small

#9763 Show "Download" label on documents list view table
  changelog/fix-7014-documents-list-view-table-download-label
  client/documents/list/index.tsx
  client/documents/list/style.scss
  client/documents/list/test/__snapshots__/index.tsx.snap
Labels: pr: ready to merge

#9783 feat: add filter to override rich payment method label
  changelog/feat-add-gateway-label-filter-override
  includes/class-wc-payment-gateway-wcpay.php
Labels: size: x-small

#9788 Ensure dispute urls in order notes are encoded correctly
  changelog/fix-7399
  includes/class-wc-payments-order-service.php
  tests/unit/test-class-wc-payments-order-service.php
Labels: pr: ready to merge

#9697 Update phpcompatibility to develop version to get sniffs for PHP 8
  .github/workflows/php-compatibility.yml
  changelog/update-phpcompatibility-latest
  composer.json
  composer.lock
  package.json
  phpcs-compat.xml.dist
  phpcs.xml.dist
Labels: focus: devops

#9761 Enforce proper return types for methods get_order_from_event_body
  changelog/dev-4293-enforce-proper-return-types-for-methodsfunctions-get_order_from_event_body_intent_id
  includes/class-wc-payments-webhook-processing-service.php
  tests/unit/test-class-wc-payments-webhook-processing-service.php
Labels: pr: needs review

#9813 Remove redundant stripe payment elements mount for pay for order
  changelog/chore-remove-redundant-init-for-payfororder
  client/checkout/classic/event-handlers.js
Labels: size: x-small

#9815 Fix return types in DocBlocks
  changelog/dev-4293-address-additional-union-types
  includes/admin/class-wc-rest-payments-customer-controller.php
  includes/admin/class-wc-rest-payments-onboarding-controller.php
  includes/admin/class-wc-rest-payments-payment-intents-create-controller.php
  includes/admin/class-wc-rest-payments-reader-controller.php
  includes/class-wc-payments-token-service.php
  includes/reports/class-wc-rest-payments-reports-authorizations-controller.php
  includes/reports/class-wc-rest-payments-reports-transactions-controller.php
Labels: pr: needs review

#9838 Update references to woocommerce_payments_server (#9824)
  .github/workflows/e2e-pull-request.yml
  .github/workflows/e2e-pw-pull-request.yml
  .github/workflows/e2e-test.yml
  changelog/update-server-container-name
  tests/e2e/README.md
  tests/e2e/env/down.sh
  tests/e2e/env/setup.sh
  tests/e2e/env/shared.sh
  tests/e2e/env/up.sh
Labels: pr: needs review, focus: devops

#9827 Allow redirect to the settings page from WCPay connect
  assets/images/illustrations/setup.svg
  changelog/dev-allow-redirect-to-settings-page-from-wcpay-connect
  client/connect-account-page/index.tsx
  client/connect-account-page/style.scss
  includes/class-wc-payments-account.php
  includes/class-wc-payments-redirect-service.php
  tests/unit/test-class-wc-payments-account.php
  tests/unit/test-class-wc-payments-redirect-service.php
Labels: pr: needs review

#9832 Payouts: Add payout bank reference key to payout reports and CSV
  changelog/add-5316-payout-trace-id
  client/deposits/list/index.tsx
  client/deposits/list/test/__snapshots__/index.tsx.snap
  client/deposits/list/test/index.tsx
  client/types/deposits.d.ts
Labels: pr: ready to merge
