Repository Automattic/woocommerce-payments, pull requests merged in 2025-01, with the labels that each got.

#10039 Remove payouts rename notice overlay.
  changelog/update-9704-remove-payouts-rename-overlay
  client/deposits/details/index.tsx
  client/deposits/index.tsx
  client/deposits/rename-notice/header-image.svg
  client/deposits/rename-notice/index.tsx
  client/deposits/rename-notice/style.scss
  client/deposits/rename-notice/test/__snapshots__/index.tsx.snap
  client/deposits/rename-notice/test/index.tsx
  client/globals.d.ts
  client/overview/index.js
  client/overview/test/index.js
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-features.php
  includes/class-wc-payments.php
Labels: pr: ready to merge

#10055 Changed the term "VAT" on Documents Listing Page to "Tax" to be applicable to all countries
  changelog/fix-9923-replace-VAT-term
  client/documents/filters/test/__snapshots__/index.tsx.snap
  client/documents/list/index.tsx
  client/documents/list/test/__snapshots__/index.tsx.snap
  client/documents/strings.ts
Labels: pr: ready to merge

#10017 Add Payment Method to Transactions advanced filters
  changelog/add-9490-filter-txns-by-payment-method
  client/data/transactions/hooks.ts
  client/data/transactions/resolvers.js
  client/transactions/declarations.d.ts
  client/transactions/filters/config.ts
  client/transactions/filters/index.tsx
  client/transactions/filters/test/__snapshots__/index.tsx.snap
  client/transactions/filters/test/index.tsx
  client/transactions/list/index.tsx
  includes/admin/class-wc-rest-payments-transactions-controller.php
  includes/core/server/request/class-list-transactions.php
Labels: pr: ready to merge

#10090 E2E Playwright Migration: convert Payment Gateways Confirmation spec
  changelog/dev-9966-e2e-convert-payment-gateways-confirmation-spec
  tests/e2e-pw/specs/merchant/merchant-payment-gateways-confirmation.spec.ts
  tests/e2e/specs/wcpay/merchant/merchant-payment-gateways-confirmation.spec.js
Labels: pr: ready to merge

#10118 Convert the Payment Settings Manual Capture spec to Playwright
  changelog/dev-9967-convert-merchant-payment-settings-manual-capture-spec
  tests/e2e-pw/specs/merchant/merchant-payment-settings-manual-capture.spec.ts
  tests/e2e/specs/wcpay/merchant/merchant-payment-settings-manual-capture.spec.js
Labels: pr: ready to merge

#10119 fix: ECE add-to-cart race condition
  changelog/fix-tokenized-ece-applepay-delay
  client/express-checkout/index.js
  client/tokenized-express-checkout/index.js
Labels: size: x-small

#10114 Update PHP and Xdebug in E2E Dockerfile
  changelog/dev-10113-bump-e2e-dockerfile-php-xdebug-versions
  tests/e2e/env/wordpress-xdebug/Dockerfile
Labels: pr: ready to merge

#10104 Convert the Shopper Pay for Order spec to Playwright
  changelog/dev-10071-convert-shopper-pay-for-order-e2e-spec
  tests/e2e-pw/specs/shopper/shopper-pay-for-order.spec.ts
  tests/e2e-pw/utils/devtools.ts
  tests/e2e/specs/wcpay/shopper/shopper-pay-for-order.spec.js
Labels: pr: ready to merge

#10126 Fix WooCommerce hook comment phpcs errors in misc files
  changelog/fix-8549-phpcs-errors-woocommerce-commenting
  includes/admin/class-wc-payments-admin.php
  templates/emails/customer-ipp-receipt.php
  templates/emails/plain/customer-ipp-receipt.php
  tests/unit/admin/test-class-wc-payments-admin-sections-overwrite.php
Labels: pr: ready to merge

#10003 CSV Exports: Simplify localization by setting export language to that in user profile settings
  changelog/update-9971-simplify-localization-csv-export
  client/components/csv-export-modal/index.tsx
  client/components/csv-export-modal/styles.scss
  client/components/csv-export-modal/test/__snapshots__/index.test.tsx.snap
  client/components/csv-export-modal/test/index.test.tsx
  client/data/deposits/resolvers.js
  client/data/disputes/resolvers.js
  client/data/settings/actions.js
  client/data/settings/hooks.js
  client/data/settings/selectors.js
  client/data/transactions/resolvers.js
  client/deposits/list/index.tsx
  client/deposits/list/test/index.tsx
  client/disputes/index.tsx
  client/disputes/test/index.tsx
  client/globals.d.ts
  client/settings/reporting-settings/components/export-language/index.tsx
  client/settings/reporting-settings/components/index.ts
  client/settings/reporting-settings/index.tsx
  client/settings/reporting-settings/interfaces.ts
  client/settings/reporting-settings/style.scss
  client/settings/reporting-settings/test/__snapshots__/index.test.js.snap
  client/settings/reporting-settings/test/index.test.js
  client/settings/settings-manager/index.js
  client/transactions/list/index.tsx
  client/transactions/list/test/index.tsx
  client/transactions/test/index.tsx
  client/utils/index.js
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-settings-controller.php
Labels: pr: ready to merge

#10057 Fixes to multiple failing E2E tests
  bin/docker-setup.sh
  changelog/fix-failing-e2e-tests
  tests/e2e/env/setup.sh
  tests/e2e/specs/wcpay/shopper/shopper-checkout-failures.spec.js
  tests/e2e/specs/wcpay/shopper/shopper-multi-currency-widget.spec.js
  tests/e2e/utils/flows.js
Labels: pr: needs review, focus: devops

#10129 Remove DateFormatNotice
  changelog/update-10021-remove-dateformatnotice
  client/capital/index.tsx
  client/capital/test/__snapshots__/index.test.tsx.snap
  client/components/date-format-notice/index.tsx
  client/components/date-format-notice/style.scss
  client/deposits/details/index.tsx
  client/deposits/index.tsx
  client/disputes/index.tsx
  client/disputes/test/__snapshots__/index.tsx.snap
  client/documents/index.tsx
  client/globals.d.ts
  client/overview/index.js
  client/payment-details/order-details/test/__snapshots__/index.test.tsx.snap
  client/payment-details/payment-details/index.tsx
  client/payment-details/readers/index.js
  client/payment-details/test/__snapshots__/index.test.tsx.snap
  client/transactions/index.tsx
  includes/admin/class-wc-payments-admin.php
Labels: pr: ready to merge

#10052 Persist reporting table column visibility in user preferences
  changelog/add-545-persist-reporting-table-column-visibility
  client/capital/index.tsx
  client/deposits/list/index.tsx
  client/deposits/list/test/index.tsx
  client/disputes/index.tsx
  client/disputes/test/index.tsx
  client/documents/list/index.tsx
  client/documents/list/test/index.tsx
  client/hooks/use-persisted-table-column-visibility.ts
  client/transactions/blocked/columns.tsx
  client/transactions/blocked/index.tsx
  client/transactions/declarations.d.ts
  client/transactions/list/index.tsx
  client/transactions/list/test/index.tsx
  client/transactions/risk-review/columns.tsx
  client/transactions/risk-review/index.tsx
  client/transactions/test/index.tsx
  client/transactions/uncaptured/index.tsx
  client/transactions/uncaptured/test/index.test.tsx
  includes/class-wc-payments.php
Labels: pr: ready to merge

#10144 Migrate the Shopper Renew Subscription E2E test to Playwright
  changelog/dev-10084-shopper-myaccount-renew-subscription-e2e-test
  tests/e2e-pw/config/default.ts
  tests/e2e-pw/specs/shopper/shopper-myaccount-renew-subscription.spec.ts
  tests/e2e-pw/utils/constants.ts
  tests/e2e-pw/utils/helpers.ts
  tests/e2e-pw/utils/rest-api.ts
  tests/e2e-pw/utils/shopper-navigation.ts
  tests/e2e-pw/utils/shopper.ts
  tests/e2e/specs/subscriptions/shopper/shopper-myaccount-renew-subscription.spec.js
Labels: pr: ready to merge

#10130 Convert the Progressive Onboarding spec to Playwright
  changelog/dev-9968-convert-merchant-progressive-onboarding-spec
  tests/e2e-pw/specs/merchant/merchant-progressive-onboarding.spec.ts
  tests/e2e-pw/utils/devtools.ts
  tests/e2e-pw/utils/merchant-navigation.ts
  tests/e2e/specs/wcpay/merchant/merchant-progressive-onboarding.spec.js
Labels: pr: ready to merge

#10127 Port admin analytics E2E tests from Puppeteer to Playwright
  changelog/update-9957-playwright-migration-admin-order-analytics
  tests/e2e-pw/specs/merchant/__snapshots__/merchant-admin-analytics.spec.ts/Admin-order-analytics-should-load-without-any-errors-1.png
  tests/e2e-pw/specs/merchant/merchant-admin-analytics.spec.ts
  tests/e2e-pw/utils/helpers.ts
  tests/e2e-pw/utils/merchant-navigation.ts
  tests/e2e-pw/utils/merchant.ts
  tests/e2e/env/setup.sh
  tests/e2e/specs/wcpay/merchant/merchant-admin-analytics.spec.js
Labels: pr: ready to merge

#10155 Port merchant subscription settings spec to Playwright
  changelog/dev-10083-playwright-migration-merchant-subscriptions-settings
  tests/e2e-pw/specs/merchant/merchant-subscriptions-settings.spec.ts
  tests/e2e-pw/utils/merchant-navigation.ts
  tests/e2e/specs/subscriptions/merchant/merchant-subscriptions-settings.spec.js
Labels: pr: ready to merge

#10162 Update the copy of the set up live payments task
  changelog/fix-wc-54302-fix-set-up-live-payments-task-copy
  client/overview/task-list/strings.tsx
Labels: pr: ready to merge

#10160 Convert Shopper Subscriptions Purchase Sign Up Fee spec to Playwright
  changelog/dev-10089-convert-shopper-subscriptions-purchase-sign-up-fee-spec
  tests/e2e-pw/specs/shopper/shopper-subscriptions-purchase-sign-up-fee.spec.ts
  tests/e2e-pw/utils/merchant-navigation.ts
  tests/e2e-pw/utils/shopper.ts
  tests/e2e/specs/subscriptions/shopper/shopper-subscriptions-purchase-sign-up-fee.spec.js
Labels: pr: ready to merge

#10163 Update sandbox to test mode copy
  changelog/update-10116-sandbox-to-test-mode-copy
  client/components/account-status/account-tools/strings.tsx
  client/components/sandbox-mode-switch-to-live-notice/index.tsx
  client/overview/modal/reset-account/index.tsx
  client/overview/modal/reset-account/strings.tsx
Labels: pr: needs review

#10153 Port merchant subscription renewal E2E test to Playwright
  changelog/add-10082-playwright-migration-merchant-subscriptions-renew-spec
  tests/e2e-pw/specs/merchant/merchant-subscriptions-renew.spec.ts
  tests/e2e-pw/utils/merchant-navigation.ts
  tests/e2e-pw/utils/merchant.ts
  tests/e2e-pw/utils/shopper-navigation.ts
  tests/e2e-pw/utils/shopper.ts
  tests/e2e/specs/subscriptions/merchant/merchant-subscriptions-renew-subscription.spec.js
Labels: pr: ready to merge

#10123 E2E Playwright Migration: convert Admin Disputes spec
  changelog/dev-9959-pw-admin-disputes-view-spec
  tests/e2e-pw/specs/merchant/merchant-admin-disputes.spec.ts
  tests/e2e/specs/wcpay/merchant/merchant-admin-disputes.spec.js
Labels: pr: ready to merge

#10136 Improve loading experience in embedded KYC
  assets/images/icons/close.svg
  changelog/update-9821-improve-loading-experience-in-embedded-kyc
  client/components/stripe-spinner/index.tsx
  client/components/stripe-spinner/style.scss
  client/onboarding/index.tsx
  client/onboarding/kyc/index.tsx
  client/onboarding/step.tsx
  client/onboarding/steps/business-details.tsx
  client/onboarding/steps/embedded-kyc.tsx
  client/onboarding/steps/loading.tsx
  client/onboarding/steps/store-details.tsx
  client/onboarding/steps/test/business-details.tsx
  client/onboarding/steps/test/store-details.tsx
  client/onboarding/strings.tsx
  client/onboarding/style.scss
Labels: pr: ready to merge

#10171 Add environment variables to playwright.config.ts
  changelog/dev-playwright-config-import-e2e-env-vars
  tests/e2e-pw/playwright.config.ts
Labels: pr: ready to merge

#10165 Branding updates to the WooPayments plugin
  assets/images/logo.svg
  assets/images/payment-method-icons/woopay.svg
  assets/images/payment-methods/woo.svg
  assets/images/payment-methods/woopay.svg
  assets/images/woo-logo.svg
  assets/images/woopay.svg
  assets/images/woopayments.svg
  changelog/update-10128-branding-updates
  client/card-readers/list/index.tsx
  client/card-readers/settings/index.tsx
  client/onboarding/strings.tsx
  client/onboarding/style.scss
  client/onboarding/test/form.tsx
  client/settings/express-checkout-settings/test/index.js
  client/settings/fraud-protection/advanced-settings/index.tsx
  client/settings/settings-layout/index.js
Labels: pr: ready to merge

#10175 Restore activated currencies after all E2E test that deactivates the existing ones
  changelog/dev-playwright-fix-multi-currency-tests
  tests/e2e-pw/specs/merchant/multi-currency-on-boarding.spec.ts
  tests/e2e-pw/specs/merchant/multi-currency-setup.spec.ts
  tests/e2e-pw/specs/merchant/multi-currency.spec.ts
  tests/e2e-pw/utils/merchant.ts
Labels: pr: ready to merge

#10138 Added currency code to fee breakdown when currency symbol is same
  changelog/fix-10006-add-currency-to-fee-details-in-order-note
  client/payment-details/timeline/map-events.js
  client/payment-details/timeline/test/captured-event-strings.js
  includes/class-wc-payments-captured-event-note.php
  includes/multi-currency/client/utils/currency/index.js
  tests/fixtures/captured-payments/foreign-card.json
  tests/fixtures/captured-payments/fx-same-currency-symbol.json
Labels: pr: needs review

#10154 Replace connection success notice with a success modal
  changelog/add-9936-connection-success-modal
  client/globals.d.ts
  client/overview/connection-sucess-notice.tsx
  client/overview/index.js
  client/overview/modal/connection-success/index.tsx
  client/overview/modal/connection-success/strings.tsx
  client/overview/modal/connection-success/style.scss
  client/overview/modal/connection-success/test/index.test.tsx
  client/overview/style.scss
  client/overview/test/index.js
  includes/admin/class-wc-payments-admin.php
  includes/class-wc-payments-onboarding-service.php
  includes/class-wc-payments.php
Labels: pr: needs review

#10167 Add a popover to WooPayments to present all possible payment methods
  assets/images/cards/cartes_bancaires.svg
  assets/images/cards/diners.svg
  assets/images/cards/eftpos.svg
  assets/images/cards/unionpay.svg
  assets/images/payment-method-icons/jcb.svg
  assets/images/payment-methods/bancontact.svg
  assets/images/payment-methods/becs.svg
  assets/images/payment-methods/ideal.svg
  assets/images/payment-methods/przelewy24.svg
  changelog/add-popover-extra-pms
  client/components/payment-method-logos/index.tsx
  client/components/payment-method-logos/style.scss
  client/connect-account-page/index.tsx
  client/connect-account-page/test/__snapshots__/index.test.tsx.snap
Labels: pr: needs review

#10174 Convert merchant admin transactions E2E tests to Playwright
  changelog/dev-9960-playwright-migration-admin-transactions
  tests/e2e-pw/specs/merchant/__snapshots__/merchant-admin-transactions.spec.ts/Admin-transactions-page-should-load-without-errors-1.png
  tests/e2e-pw/specs/merchant/merchant-admin-transactions.spec.ts
  tests/e2e-pw/utils/merchant-navigation.ts
  tests/e2e/specs/wcpay/merchant/merchant-admin-transactions.spec.js
Labels: pr: ready to merge

#10178 Convert shopper applies coupon on cart E2E tests to Playwright
  changelog/dev-10062-playwright-migration-shopper-checkout-free
  tests/e2e-pw/specs/shopper/shopper-checkout-cart-coupon.spec.ts
  tests/e2e-pw/utils/shopper-navigation.ts
  tests/e2e/specs/wcpay/shopper/shopper-checkout-free-cart.spec.js
Labels: pr: ready to merge

#10177 Convert Shopper BNPL Checkout spec
  changelog/dev-10060-convert-shopper-bnpls-checkout-spec
  tests/e2e-pw/specs/shopper/shopper-bnpls-checkout.spec.ts
  tests/e2e-pw/specs/shopper/shopper-checkout-failures.spec.ts
  tests/e2e-pw/specs/shopper/shopper-myaccount-renew-subscription.spec.ts
  tests/e2e-pw/specs/shopper/shopper-pay-for-order.spec.ts
  tests/e2e-pw/utils/shopper.ts
  tests/e2e/specs/wcpay/shopper/shopper-bnpls-checkout.spec.js
Labels: pr: ready to merge

#10143 E2E Playwright Migration: convert merchant-subscriptions-renew-action-scheduler spec
  changelog/dev-10081-e2e-convert-merchant-subscriptions-renew-action-scheduler-spec
  tests/e2e-pw/specs/merchant/merchant-subscriptions-renew-action-scheduler.spec.ts
  tests/e2e-pw/utils/constants.ts
  tests/e2e/specs/subscriptions/merchant/merchant-subscriptions-renew-action-scheduler.spec.js
Labels: pr: needs review

#10198 Convert Shopper Checkout Purchase spec to Playwright
  changelog/dev-10177-convert-shopper-checkout-purchase-spec
  tests/e2e-pw/specs/shopper/shopper-checkout-purchase.spec.ts
  tests/e2e/specs/wcpay/shopper/shopper-checkout-purchase.spec.js
Labels: pr: needs review

#10180 E2E Playwright Migration: convert Order Manual Capture spec
  changelog/dev-9962-pw-order-manual-capture-spec
  tests/e2e-pw/specs/merchant/merchant-orders-manual-capture.spec.ts
  tests/e2e-pw/utils/merchant.ts
  tests/e2e/specs/wcpay/merchant/merchant-orders-manual-capture.spec.js
Labels: pr: ready to merge

#10112 Add specific type and min supported amount in error response for the payments below min supported amount
  changelog/add-10092-add-specific-type-and-min-supported-amount-in-error-response-for-the-payments-below-min-supported-amount
  client/data/authorizations/actions.ts
  client/data/authorizations/test/actions.test.ts
  docs/rest-api/source/includes/wp-api-v3/order.md
  includes/admin/class-wc-rest-payments-orders-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  tests/unit/admin/test-class-wc-rest-payments-orders-controller.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: ready to merge

#10216 Optimise memory usage when formatting logger entries
  changelog/dev-10021-logging-memory-optimisations
  src/Internal/LoggerContext.php
Labels: pr: ready to merge

#10215 Update the loader image for test account creation
  assets/images/illustrations/setup.svg
  changelog/fix-replace-setup-image
Labels: pr: needs review

#10192 Convert the Shopper Subscriptions Manage Payments E2E spec to Playwright
  changelog/dev-10085-convert-shopper-subscriptions-manage-payments-spec
  tests/e2e-pw/specs/shopper/shopper-subscriptions-manage-payments.spec.ts
  tests/e2e-pw/utils/constants.ts
  tests/e2e/specs/subscriptions/shopper/shopper-subscriptions-manage-payments.spec.js
Labels: pr: ready to merge

#10159 Migrate shopper free trial subscription purchase to Playwright
  changelog/dev-10086-playwright-migration-shopper-subscriptions-purchase-free-trial
  tests/e2e-pw/specs/shopper/shopper-subscriptions-purchase-free-trial.spec.ts
  tests/e2e/specs/subscriptions/shopper/shopper-subscriptions-purchase-free-trial.spec.js
Labels: pr: ready to merge

#10213 Fix incorrect payment method logos used on WooPayment Settings
  assets/images/payment-methods/bancontact.svg
  assets/images/payment-methods/ideal.svg
  changelog/fix-pms-logos
Labels: pr: needs review

#10151 Convert the Order Full Refund spec to Playwright
  changelog/dev-9961-convert-merchant-orders-full-refund-spec
  tests/e2e-pw/specs/merchant/merchant-orders-full-refund.spec.ts
  tests/e2e/specs/wcpay/merchant/merchant-orders-full-refund.spec.js
Labels: pr: needs review

#10204 Convert Shopper Multi Currency Widget spec to Playwright
  changelog/dev-10067-convert-shopper-multi-currency-widget-spec
  tests/e2e-pw/specs/shopper/multi-currency-checkout.spec.ts
  tests/e2e-pw/specs/shopper/shopper-bnpls-checkout.spec.ts
  tests/e2e-pw/specs/shopper/shopper-multi-currency-widget.spec.ts
  tests/e2e-pw/utils/merchant.ts
  tests/e2e-pw/utils/rest-api.ts
  tests/e2e/specs/wcpay/shopper/shopper-multi-currency-widget.spec.js
Labels: pr: needs review

#10161 Port shopper subscriptions purchase with no signup fee E2E test to Playwright
  changelog/dev-10088-playwright-migration-shopper-subscriptions-no-sign-up-fee
  tests/e2e-pw/specs/shopper/shopper-subscriptions-purchase-no-signup-fee.spec.ts
  tests/e2e-pw/utils/merchant-navigation.ts
  tests/e2e/specs/subscriptions/shopper/shopper-subscriptions-purchase-no-sign-up-fee.spec.js
Labels: pr: ready to merge

#10203 Convert shopper checkout purchase with UPE tests to Playwright
  changelog/dev-10064-playwright-migration-shopper-checkout-purchase-with-upe-methods
  tests/e2e-pw/config/default.ts
  tests/e2e-pw/specs/shopper/shopper-checkout-purchase-with-upe-methods.spec.ts
  tests/e2e-pw/specs/shopper/shopper-myaccount-saved-cards.spec.ts
  tests/e2e-pw/specs/shopper/shopper-subscriptions-purchase-free-trial.spec.ts
  tests/e2e-pw/utils/merchant.ts
  tests/e2e-pw/utils/shopper-navigation.ts
  tests/e2e-pw/utils/shopper.ts
  tests/e2e/specs/wcpay/shopper/shopper-checkout-purchase-with-upe-methods.spec.js
  tests/e2e/specs/wcpay/shopper/shopper-myaccount-payment-methods-add-delete-success.spec.js
  tests/e2e/specs/wcpay/shopper/shopper-myaccount-save-card-and-checkout.spec.js
Labels: pr: ready to merge

#10208 Convert shopper checkout save card and purchase test to Playwright
  changelog/dev-10066-playwright-migration-shopper-checkout-save-card-and-purchase
  tests/e2e-pw/specs/shopper/shopper-checkout-save-card-and-purchase.spec.ts
  tests/e2e-pw/utils/shopper.ts
  tests/e2e/specs/wcpay/shopper/shopper-checkout-save-card-and-purchase.spec.js
Labels: pr: ready to merge

#10218 Refactoring of snackbar checks in Playwright e2e tests
  changelog/dev-10210-fix-saving-woopayments-settings
  tests/e2e-pw/utils/merchant.ts
Labels: pr: needs review

#10230 Prevent duplicate order failure by selling different products on saved card E2E tests
  changelog/fix-playwright-saved-card-flakiness
  tests/e2e-pw/specs/shopper/shopper-myaccount-saved-cards.spec.ts
  tests/e2e-pw/utils/shopper.ts
Labels: pr: ready to merge, focus: devops

#10214 Design improvements related to the overview page
  changelog/update-9811-design-improvements-overview-page
  client/components/deposits-status/index.tsx
  client/components/deposits-status/test/__snapshots__/index.js.snap
  client/overview/index.js
Labels: pr: ready to merge

#10226 E2E Playwright Migration: convert shopper-myaccount-payment-methods-add-fail spec
  changelog/dev-10069-e2e-convert-shopper-myaccount-payment-methods-add-fail-spec
  tests/e2e-pw/specs/shopper/shopper-myaccount-payment-methods-add-fail.spec.ts
  tests/e2e/specs/wcpay/shopper/shopper-myaccount-payment-methods-add-fail.spec.js
Labels: pr: ready to merge

#10250 Remove the subscriptions spec for Puppeteer
  changelog/fix-10249-remove-subscriptions-jest-spec
  tests/e2e/config/jest.config.js
Labels: pr: needs review

#9945 Reporting: Show bank reference ID on Payout details page
  changelog/add-9878-bank-ref-key-payout-details
  client/components/copy-button/index.tsx
  client/components/copy-button/style.scss
  client/components/copy-button/test/__snapshots__/index.test.tsx.snap
  client/components/copy-button/test/index.test.tsx
  client/deposits/details/index.tsx
  client/deposits/details/style.scss
  client/deposits/details/test/__snapshots__/index.tsx.snap
Labels: pr: needs review

#10195 Convert shopper checkout using a site editor theme E2E tests to Playwright
  changelog/dev-10063-playwright-migration-shopper-checkout-purchase-site-editor
  tests/e2e-pw/specs/shopper/shopper-checkout-purchase-site-editor.spec.ts
  tests/e2e-pw/utils/devtools.ts
  tests/e2e-pw/utils/shopper.ts
  tests/e2e/specs/wcpay/shopper/shopper-checkout-purchase-site-editor.spec.js
Labels: pr: ready to merge

#10244 Playwright migration: Implement cleanup with customer recreation via WC REST API
  changelog/dev-create-new-customer-for-each-pw-test
  tests/e2e-pw/config/default.ts
  tests/e2e-pw/specs/merchant/merchant-subscriptions-renew-action-scheduler.spec.ts
  tests/e2e-pw/specs/merchant/multi-currency-widget.spec.ts
  tests/e2e-pw/specs/merchant/multi-currency.spec.ts
  tests/e2e-pw/specs/shopper/shopper-checkout-purchase-with-upe-methods.spec.ts
  tests/e2e-pw/specs/shopper/shopper-checkout-save-card-and-purchase.spec.ts
  tests/e2e-pw/specs/shopper/shopper-multi-currency-widget.spec.ts
  tests/e2e-pw/specs/shopper/shopper-myaccount-renew-subscription.spec.ts
  tests/e2e-pw/specs/shopper/shopper-myaccount-saved-cards.spec.ts
  tests/e2e-pw/specs/shopper/shopper-subscriptions-manage-payments.spec.ts
  tests/e2e-pw/specs/shopper/shopper-subscriptions-purchase-free-trial.spec.ts
  tests/e2e-pw/specs/shopper/shopper-subscriptions-purchase-multiple-subscriptions.spec.ts
  tests/e2e-pw/specs/shopper/shopper-subscriptions-purchase-no-signup-fee.spec.ts
  tests/e2e-pw/specs/shopper/shopper-subscriptions-purchase-sign-up-fee.spec.ts
  tests/e2e-pw/utils/helpers.ts
  tests/e2e-pw/utils/merchant.ts
  tests/e2e-pw/utils/rest-api.ts
Labels: pr: ready to merge, category: e2e, focus: devops

#10173 Convert merchant side refund from order screen failures E2E tests to Playwright
  changelog/dev-9964-playwright-migration-order-refund-failures
  tests/e2e-pw/specs/merchant/merchant-orders-refund-failures.spec.ts
  tests/e2e/specs/wcpay/merchant/merchant-orders-refund-failures.spec.js
Labels: pr: ready to merge

#10232 Convert Shopper Blocks Checkout Failures spec to Playwright
  changelog/dev-10073-convert-shopper-wc-blocks-checkout-failures-spec
  tests/e2e-pw/specs/shopper/shopper-wc-blocks-checkout-failures.spec.ts
  tests/e2e/specs/blocks/shopper/shopper-wc-blocks-checkout-failures.spec.js
Labels: pr: ready to merge

#10263 Fix Flaky PW test: Multi-currency widget setup
  changelog/dev-10262-flaky-mccy-test
  tests/e2e-pw/specs/merchant/merchant-multi-currency-widget.spec.ts
Labels: pr: needs review

#10234 E2E Playwright Migration: convert shopper-wc-blocks-checkout-purchase spec
  changelog/dev-10074-pw-shopper-blocks-checkout-purchase
  tests/e2e-pw/specs/shopper/shopper-multi-currency-widget.spec.ts
  tests/e2e-pw/specs/shopper/shopper-myaccount-saved-cards.spec.ts
  tests/e2e-pw/specs/shopper/shopper-wc-blocks-checkout-purchase.spec.ts
  tests/e2e/specs/blocks/shopper/shopper-wc-blocks-checkout-purchase.spec.js
Labels: pr: ready to merge

#10275 Add support for `WP_DEVELOPMENT_MODE`
  changelog/add-6850-wp-dev-mode
  includes/core/class-mode.php
  tests/unit/core/test-class-mode.php
Labels: pr: ready to merge

#10278 Temp update the pull request workflow for testing
  .github/workflows/e2e-pull-request.yml
  changelog/dev-temp-update-e2e-pull-request-workflow
Labels: pr: ready to merge

#10269 Enable `card_reader_fee` type filter for transactions
  changelog/add-9422-enable-card-reader-fee-filter
  client/data/transactions/hooks.ts
  client/transactions/filters/config.ts
  client/transactions/filters/test/__snapshots__/index.tsx.snap
  client/transactions/list/index.tsx
Labels: pr: needs review
