Repository Automattic/woocommerce-payments, pull requests merged in 2025-02, with the labels that each got.

#10293 Update handling for 0 feeAmount to be consistent with details page.
  changelog/update-remove-NA-for-zero-amounts
  client/transactions/list/index.tsx
Labels: pr: ready to merge

#10231 Cache get WC orders for incentives
  changelog/add-cache-wc-orders
  includes/class-database-cache.php
  includes/class-wc-payments-incentives-service.php
  tests/unit/test-class-wc-payments-incentives-service.php
Labels: pr: ready to merge

#10294 Remove the receipt details tab in the card readers page.
  changelog/update-remove-card-reader-receipt-details
  client/card-readers/index.tsx
  client/card-readers/settings/file-upload.tsx
  client/card-readers/settings/index.tsx
  client/card-readers/settings/sections/address-details.js
  client/card-readers/settings/sections/branding-details.js
  client/card-readers/settings/sections/business-details.js
  client/card-readers/settings/sections/contacts-details.js
  client/card-readers/settings/sections/test/index.test.js
  client/card-readers/settings/test/__snapshots__/index.test.tsx.snap
  client/card-readers/settings/test/index.test.tsx
  client/card-readers/test/index.test.tsx
Labels: pr: needs review

#10322 Disables the tokenised cart for ECE integration by default
  changelog/patch-disable-tokenised-carts-by-default
  includes/class-wc-payments-features.php
Labels: focus: checkout payments, size: x-small

#10313 Add handling for insufficient funds during refund processing
  bin/run-tests.sh
  changelog/update-add-handling-for-low-refund-balance
  includes/admin/class-wc-rest-payments-refunds-controller.php
  includes/class-wc-payments-order-service.php
  includes/class-wc-payments-webhook-processing-service.php
  tests/unit/test-class-wc-payments-webhook-processing-service.php
Labels: pr: ready to merge

#10290 Fix the E2E Tests Atomic workflow
  .github/actions/e2e/atomic-prepare-and-run/action.yml
  .github/actions/e2e/run-log-tests/action.yml
  .github/workflows/e2e-tests-atomic.yml
  package-lock.json
  package.json
  tests/e2e-pw/config/default.ts
  tests/e2e-pw/docker-compose.yml
  tests/e2e-pw/playwright.config.ts
  tests/e2e-pw/specs/auth.setup.ts
  tests/e2e-pw/specs/subscriptions/merchant/merchant-subscriptions-renew-action-scheduler.spec.ts
  tests/e2e-pw/specs/subscriptions/merchant/merchant-subscriptions-renew.spec.ts
  tests/e2e-pw/specs/subscriptions/shopper/shopper-subscriptions-manage-payments.spec.ts
  tests/e2e-pw/specs/subscriptions/shopper/shopper-subscriptions-purchase-free-trial.spec.ts
  tests/e2e-pw/specs/subscriptions/shopper/shopper-subscriptions-purchase-multiple-subscriptions.spec.ts
  tests/e2e-pw/specs/subscriptions/shopper/shopper-subscriptions-purchase-no-signup-fee.spec.ts
  tests/e2e-pw/specs/subscriptions/shopper/shopper-subscriptions-purchase-sign-up-fee.spec.ts
  tests/e2e-pw/specs/wcpay/merchant/merchant-admin-transactions.spec.ts
  tests/e2e-pw/specs/wcpay/merchant/merchant-disputes-respond.spec.ts
  tests/e2e-pw/specs/wcpay/merchant/merchant-disputes-view-details-via-order-notice.spec.ts
  tests/e2e-pw/specs/wcpay/merchant/merchant-multi-currency-widget.spec.ts
  tests/e2e-pw/specs/wcpay/merchant/merchant-orders-partial-refund.spec.ts
  tests/e2e-pw/specs/wcpay/merchant/multi-currency-setup.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/klarna-checkout-purchase.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-bnpls-checkout.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-checkout-cart-coupon.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-checkout-failures.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-checkout-purchase-site-editor.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-checkout-purchase-with-upe-methods.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-checkout-purchase.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-checkout-save-card-and-purchase.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-multi-currency-widget.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-myaccount-payment-methods-add-fail.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-myaccount-renew-subscription.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-myaccount-saved-cards.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-pay-for-order.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-wc-blocks-checkout-failures.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-wc-blocks-checkout-purchase.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-wc-blocks-saved-card-checkout-and-usage.spec.ts
  tests/e2e-pw/utils/constants.ts
  tests/e2e-pw/utils/helpers.ts
  tests/e2e-pw/utils/merchant.ts
  tests/e2e-pw/utils/rest-api.ts
  tests/e2e-pw/utils/shopper-navigation.ts
  tests/e2e-pw/utils/shopper.ts
Labels: pr: ready to merge

#10315 Update permissions settings and project names for E2E test setup
  changelog/dev-e2e-pw-setup-script-permissions-and-project
  tests/e2e-pw/README.md
  tests/e2e-pw/specs/merchant/__snapshots__/merchant-admin-transactions.spec.ts/Admin-transactions-page-should-load-without-errors-1.png
  tests/e2e/env/down.sh
  tests/e2e/env/setup.sh
  tests/e2e/env/shared.sh
  tests/e2e/env/up.sh
Labels: pr: ready to merge

#10211 Transactions Download functionality Improvements
  changelog/update-9969-poll-async-job
  client/components/download-button/index.tsx
  client/components/download-button/test/__snapshots__/index.tsx.snap
  client/data/transactions/resolvers.js
  client/deposits/list/test/__snapshots__/index.tsx.snap
  client/deposits/list/test/index.tsx
  client/disputes/test/__snapshots__/index.tsx.snap
  client/disputes/test/index.tsx
  client/hooks/test/use-report-export.test.ts
  client/hooks/use-report-export.ts
  client/payment-details/readers/test/__snapshots__/index.js.snap
  client/payment-details/readers/test/index.js
  client/transactions/blocked/columns.tsx
  client/transactions/list/index.tsx
  client/transactions/list/test/__snapshots__/index.tsx.snap
  client/transactions/list/test/index.tsx
  includes/admin/class-wc-rest-payments-transactions-controller.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: needs review

#10273 Extract the Account Session logic from Embedded components onboarding into a reusable utility hook
  changelog/update-10256-extract-account-settings-logic
  client/onboarding/steps/embedded-kyc.tsx
  client/onboarding/steps/test/embedded-onboarding.tsx
  client/onboarding/utils.ts
  client/utils/embedded-components/account-session.ts
  client/utils/embedded-components/appearance.ts
  client/utils/embedded-components/kyc-account-session.ts
  client/utils/embedded-components/utils.ts
  includes/admin/class-wc-rest-payments-accounts-controller.php
  includes/class-wc-payments-account.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: needs review

#10340 Fix flakiness while creating a page with the checkout block
  changelog/dev-10339-wcb-checkout
  tests/e2e-pw/specs/wcpay/shopper/shopper-myaccount-renew-subscription.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-pay-for-order.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-wc-blocks-checkout-failures.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-wc-blocks-checkout-purchase.spec.ts
  tests/e2e-pw/utils/devtools.ts
  tests/e2e-pw/utils/merchant.ts
  tests/e2e-pw/utils/shopper.ts
Labels: pr: needs review

#10338 Add the critical tag to E2E tests that are part of critical flows
  changelog/dev-10237-e2e-critical-flow-tag
  tests/e2e-pw/specs/subscriptions/merchant/merchant-subscriptions-renew-action-scheduler.spec.ts
  tests/e2e-pw/specs/subscriptions/merchant/merchant-subscriptions-renew.spec.ts
  tests/e2e-pw/specs/subscriptions/shopper/shopper-subscriptions-manage-payments.spec.ts
  tests/e2e-pw/specs/subscriptions/shopper/shopper-subscriptions-purchase-free-trial.spec.ts
  tests/e2e-pw/specs/subscriptions/shopper/shopper-subscriptions-purchase-multiple-subscriptions.spec.ts
  tests/e2e-pw/specs/subscriptions/shopper/shopper-subscriptions-purchase-no-signup-fee.spec.ts
  tests/e2e-pw/specs/subscriptions/shopper/shopper-subscriptions-purchase-sign-up-fee.spec.ts
  tests/e2e-pw/specs/wcpay/merchant/merchant-multi-currency-widget.spec.ts
  tests/e2e-pw/specs/wcpay/merchant/merchant-orders-full-refund.spec.ts
  tests/e2e-pw/specs/wcpay/merchant/merchant-orders-manual-capture.spec.ts
  tests/e2e-pw/specs/wcpay/merchant/merchant-orders-partial-refund.spec.ts
  tests/e2e-pw/specs/wcpay/merchant/merchant-orders-refund-failures.spec.ts
  tests/e2e-pw/specs/wcpay/merchant/merchant-orders-status-change.spec.ts
  tests/e2e-pw/specs/wcpay/merchant/merchant-payment-settings-manual-capture.spec.ts
  tests/e2e-pw/specs/wcpay/merchant/merchant-progressive-onboarding.spec.ts
  tests/e2e-pw/specs/wcpay/merchant/multi-currency-on-boarding.spec.ts
  tests/e2e-pw/specs/wcpay/merchant/multi-currency-setup.spec.ts
  tests/e2e-pw/specs/wcpay/merchant/multi-currency.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/klarna-checkout-purchase.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-bnpls-checkout.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-checkout-failures.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-checkout-purchase-with-upe-methods.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-checkout-purchase.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-checkout-save-card-and-purchase.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-multi-currency-widget.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-myaccount-payment-methods-add-fail.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-myaccount-renew-subscription.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-myaccount-saved-cards.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-pay-for-order.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-wc-blocks-checkout-failures.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-wc-blocks-checkout-purchase.spec.ts
  tests/e2e-pw/specs/wcpay/shopper/shopper-wc-blocks-saved-card-checkout-and-usage.spec.ts
Labels: pr: ready to merge

#10287 Integrate Account Management component into the Settings Page
  changelog/add-9129-account-management-component
  client/settings/account-management/index.tsx
  client/settings/account-management/style.scss
  client/settings/settings-manager/index.js
Labels: pr: needs review, pr: needs design review

#10349 Update handling for PR as a country for terminal locations
  changelog/update-terminal-controller-PR-country-handling
  includes/admin/class-wc-rest-payments-terminal-locations-controller.php
  tests/unit/admin/test-class-wc-rest-payments-terminal-locations-controller.php
Labels: pr: ready to merge

#10300 Download Disputes CSV from service
  changelog/update-7188-immediate-csv-download-for-disputes
  client/data/disputes/resolvers.js
  client/disputes/index.tsx
  client/disputes/test/index.tsx
  includes/admin/class-wc-rest-payments-disputes-controller.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: ready to merge

#10359 CSV Export - Improve the appearance and message of export notice
  changelog/fix-10356-update-export-snackbar
  client/transactions/list/index.tsx
Labels: pr: ready to merge

#10360 Update disputes CSV download notice.
  changelog/update-disputes-csv-download-notice
  client/disputes/index.tsx
Labels: pr: ready to merge

#10362 Add Slack integration to Playwright E2E
  .github/workflows/e2e-pull-request.yml
  .github/workflows/e2e-pw-pull-request.yml
  .github/workflows/e2e-test.yml
  .github/workflows/e2e-tests-atomic.yml
  changelog/dev-10355-playwright-slack-integration
  package-lock.json
  package.json
  tests/e2e/README.md
  tests/e2e/playwright.config.ts
  tests/e2e/reporters/slack-reporter.ts
  tests/e2e/utils/slack.ts
Labels: pr: ready to merge

#10314 Add Stripe embedded account notifications component on the Overview page
  changelog/add-9128-account-notifs-component-on-overview-page
  client/overview/index.js
  client/overview/style.scss
  client/overview/task-list/tasks.tsx
  client/overview/test/index.js
Labels: pr: needs review, pr: needs design review

#10346 Improve CSV download experience for Payouts
  changelog/update-deposits-server-export
  client/data/deposits/resolvers.js
  client/deposits/list/index.tsx
  client/deposits/list/test/index.tsx
  client/disputes/test/index.tsx
  client/transactions/list/test/index.tsx
  includes/admin/class-wc-rest-payments-deposits-controller.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: needs review, pr: ready to merge

#10396 Revert "Integrate Account Management component into the Settings Page"
  changelog/add-9129-account-management-component
  client/settings/account-management/index.tsx
  client/settings/account-management/style.scss
  client/settings/settings-manager/index.js
Labels: pr: needs review

#10351 Add JSON-formatted minimum amount details to Amount_Too_Small_Exception error message
  changelog/update-add-min-amount-to-capture-error
  client/data/authorizations/actions.ts
  client/data/authorizations/test/actions.test.ts
  docs/rest-api/source/includes/wp-api-v3/order.md
  includes/admin/class-wc-rest-payments-orders-controller.php
  includes/class-wc-payment-gateway-wcpay.php
  tests/unit/admin/test-class-wc-rest-payments-orders-controller.php
Labels: pr: needs review

#10397 Update copy in the Woopayments Reset account modal
  changelog/update-10317-change-reset-account-modal-copy
  client/overview/modal/reset-account/strings.tsx
  client/overview/modal/reset-account/test/index.test.tsx
Labels: pr: ready to merge

#10316 Fixed Woo colors during Stripe KYC
  assets/images/payment-methods/woopay.svg
  bin/wcpay-live-branches/wcpay-live-branches.user.js
  changelog/fix-missed-woo-colors
  client/components/fraud-risk-tools-banner/style.scss
  client/utils/embedded-components/appearance.ts
  docs/rest-api/source/stylesheets/_lang-selector.scss
  docs/rest-api/source/stylesheets/_variables.scss
Labels: pr: ready to merge

#10374 Add E2E tests to ensure non-admin users can log to wp-admin with no errors
  changelog/dev-5101-add-e2e-test-non-admin-users-can-login-to-wp-admin
  tests/e2e/config/default.json
  tests/e2e/config/default.ts
  tests/e2e/config/users.json
  tests/e2e/env/setup.sh
  tests/e2e/env/shared.sh
  tests/e2e/specs/auth.setup.ts
  tests/e2e/specs/wcpay/merchant/non-admin-wp-admin-access.spec.ts
  tests/e2e/utils/helpers.ts
Labels: pr: ready to merge

#10398 Add loader indication for Stripe notifications banner component
  changelog/add-10390-stripe-notifications-component-loader
  client/overview/index.js
  client/overview/style.scss
Labels: pr: ready to merge

#10417 Add a notice indicating that overview page needs to be reloaded after completing the requirements in the embedded component
  changelog/update-10391-snackbar-when-user-updates-kyc-on-overview-page
  client/overview/index.js
Labels: pr: ready to merge

#10423 Update the size of Woo logo on the test drive onboarding page
  changelog/fix-10379-woo-logo-size-test-drive-onboarding
  client/connect-account-page/style.scss
Labels: pr: ready to merge

#10416 Handle fatal errors when subscription plugin gets deactivated due to outdated version
  changelog/fix-5623-handle-fatal-errors-on-wc-subscriptions-deactivated-due-outdated-version
  includes/compat/subscriptions/trait-wc-payments-subscriptions-utilities.php
  includes/subscriptions/class-wc-payments-product-service.php
Labels: pr: needs review

#10422 chore: remove unused strings file
  changelog/chore-remove-unused-strings-file
  client/overview/strings.tsx
Labels: size: x-small

#10411 Create a Tracks event for tracking CSV exports of Transactions, Disputes and Payouts.
  changelog/update-10172-csv-export-tracks-event
  client/deposits/list/index.tsx
  client/disputes/index.tsx
  client/tracks/event.d.ts
  client/transactions/list/index.tsx
Labels: pr: needs review

#10435 fix: Manual capture fails in the transaction detail screen with a customized order number
  changelog/fix-10395-order-number-manual-capture
  client/data/payment-intents/actions.ts
  client/data/payment-intents/test/hooks.ts
  client/payment-details/order-details/test/__snapshots__/index.test.tsx.snap
  client/payment-details/order-details/test/index.test.tsx
  client/payment-details/summary/index.tsx
  client/payment-details/summary/test/__snapshots__/index.test.tsx.snap
  client/payment-details/summary/test/index.test.tsx
  client/transactions/list/test/__snapshots__/index.tsx.snap
  client/transactions/list/test/index.tsx
  client/types/orders.d.ts
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: ready to merge

#10449 chore: remove unnecessary useEffect on settings toggle
  changelog/chore-remove-unneeded-useeffect-in-settings
  client/settings/advanced-settings/multi-currency-toggle.js
  client/settings/advanced-settings/wcpay-subscriptions-toggle.js
Labels: size: x-small

#10459 chore: port ECE changes into tokenized ECE
  changelog/chore-port-express-checkout-changes-to-tokenized-ece
  client/tokenized-express-checkout/blocks/index.js
  client/tokenized-express-checkout/utils/checkPaymentMethodIsAvailable.js
Labels: size: x-small

#10437 update: Change WooPayments "Channel" to "Sales Channel" and other channel names
  changelog/fix-10245-update-texts
  client/payment-details/order-details/test/__snapshots__/index.test.tsx.snap
  client/payment-details/summary/__tests__/__snapshots__/index.test.js.snap
  client/payment-details/summary/index.tsx
  client/payment-details/test/__snapshots__/index.test.tsx.snap
  client/transactions/filters/config.ts
  client/transactions/filters/test/__snapshots__/index.tsx.snap
  client/transactions/filters/test/index.tsx
  client/transactions/list/index.tsx
  client/transactions/list/test/__snapshots__/index.tsx.snap
  client/transactions/strings.ts
  client/utils/charge/index.ts
  client/utils/charge/test/index.js
Labels: pr: ready to merge

#10472 dev - Fix the flaky test in WC_Payments_Incentives_Service_Test
  changelog/dev-fix-unstable-test-WC_Payments_Incentives_Service_Test
  tests/unit/test-class-wc-payments-incentives-service.php
Labels: pr: ready to merge
