Repository Automattic/woocommerce-payments, pull requests merged in 2025-03, with the labels that each got.

#10370 Add the prompt "Are you satisfied with WooPayments?" for eligible merchants, behind feature flag
  changelog/add-10326-add-prompt-for-review
  client/capital/index.tsx
  client/deposits/details/index.tsx
  client/deposits/index.tsx
  client/disputes/index.tsx
  client/documents/index.tsx
  client/globals.d.ts
  client/merchant-feedback-prompt/index.tsx
  client/merchant-feedback-prompt/style.scss
  client/merchant-feedback-prompt/test/index.test.tsx
  client/overview/index.js
  client/payment-details/payment-details/index.tsx
  client/tracks/event.d.ts
  client/transactions/index.tsx
  includes/class-wc-payments-account.php
  includes/class-wc-payments-features.php
Labels: pr: needs review

#10444 Persist prompt dismissal in user preferences
  changelog/update-10329-persist-user-prompt-dismiss
  client/capital/test/index.test.tsx
  client/merchant-feedback-prompt/hooks.ts
  client/merchant-feedback-prompt/index.tsx
  client/merchant-feedback-prompt/test/index.test.tsx
  client/payment-details/order-details/test/index.test.tsx
  client/payment-details/test/index.test.tsx
  includes/class-wc-payments.php
Labels: pr: ready to merge

#10487 chore: update google pay test mode notice text
  changelog/2025-03-05-08-56-32-729035
  client/settings/__tests__/google-pay-test-mode-compatibility-notice.test.js
  client/settings/google-pay-test-mode-compatibility-notice.tsx
Labels: size: x-small

#10464 Removes 60 day survey
  changelog/update-10325-remove-60-day-survey
  includes/class-wc-payments.php
Labels: pr: ready to merge

#10486 Add the positive feedback modal to encourage merchants to leave a .org review
  changelog/add-10327-merchant-feedback-prompt-positive-modal
  client/merchant-feedback-prompt/index.tsx
  client/merchant-feedback-prompt/positive-modal.tsx
  client/merchant-feedback-prompt/style.scss
  client/merchant-feedback-prompt/test/index.test.tsx
Labels: pr: ready to merge

#10462 Payouts - Show failure message in payout details for failed payouts
  changelog/add-8203-payout-failure-notice
  client/deposits/details/index.tsx
  client/deposits/details/test/index.tsx
  client/deposits/strings.ts
  client/types/deposits.d.ts
Labels: pr: ready to merge

#10494 update: tokenized ECE log on session mismatch
  changelog/update-tokenized-ece-session-mismatch-logs
  includes/class-wc-payments-payment-request-session-handler.php
Labels: size: x-small

#10499 chore: remove unused useApiFetch util
  changelog/chore-remove-unused-useApiFetch-util
  client/hooks/use-api-fetch.ts
Labels: size: x-small

#10497 chore: remove unused prevStep
  changelog/chore-remove-unused-prevStep
  client/onboarding/step.tsx
Labels: size: x-small

#10495 chore: remove unused greetingStrings in account-balances
  changelog/chore-remove-unused-account-balances-greetingStrings
  client/components/account-balances/strings.ts
Labels: size: x-small

#10510 Update Jetpack packages in composer
  changelog/update-jetpack-composer-packages
  composer.json
  composer.lock
Labels: pr: needs review

#10500 chore: remove unused settings hooks from data store
  changelog/chore-remove-unused-hooks-and-selectors
  client/data/settings/actions.js
  client/data/settings/hooks.js
  client/data/settings/selectors.js
  client/data/settings/test/reducer.js
  client/data/settings/test/selectors.js
  client/settings/buy-now-pay-later-section/__tests__/buy-now-pay-later-section.test.js
  client/settings/payment-methods-section/__tests__/payment-methods-section.test.js
Labels: size: x-small

#10507 fix: Alipay logo size in settings
  assets/images/payment-methods/alipay-logo.svg
  changelog/fix-alipay-logo-size-and-alignment
Labels: size: x-small

#10421 Add Negative feedback modal for 2025 Feedback campaign
  changelog/add-10328-prompt-negative-feedback
  client/merchant-feedback-prompt/index.tsx
  client/merchant-feedback-prompt/negative-modal.tsx
  client/merchant-feedback-prompt/style.scss
  client/merchant-feedback-prompt/test/index.test.tsx
Labels: pr: ready to merge

#10512 Send the store's URL to Stripe when the coming soon flag is removed
  changelog/add-inform-stripe-when-site-goes-live
  includes/admin/class-wc-payments-admin.php
Labels: pr: needs review

#10506 Exclude playwright-report from eslint
  .eslintrc
  changelog/dev-exclude-playwright-report-eslint
Labels: size: x-small

#10520 Remove annoying merchant feedback prompt animation on navigation
  changelog/fix-10482-remove-merchant-feedback-prompt-animations
  client/merchant-feedback-prompt/style.scss
Labels: pr: ready to merge

#10333 Include transaction ID with reader charges summary request
  changelog/add-10332-include-transaction-id-with-reader-charges-summary-request
  includes/admin/class-wc-rest-payments-reader-controller.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/admin/test-class-wc-rest-payments-readers-controller.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: needs review

#10511 Fix: Update Safe Mode notice to be consistent with new changes from Jetpack
  changelog/fix-9614-jetpack-safemode-notice
  composer.json
  composer.lock
  woocommerce-payments.php
Labels: pr: needs review

#10533 Fix alignment of the merchant feedback prompt on small mobile screens
  changelog/fix-10532-merchant-feedback-prompt-mobile-screen-alignment
  client/merchant-feedback-prompt/style.scss
Labels: pr: ready to merge

#10521 Handle insufficient_balance_for_refund when in the admin order management
  changelog/fix-10425-process_refund
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-order-service.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: ready to merge

#10547 Update merchant feedback prompt text to emphasise a 5-star review request
  changelog/add-10544-merchant-feedback-prompt-explicit-5-star-wording
  client/merchant-feedback-prompt/positive-modal.tsx
  client/merchant-feedback-prompt/test/index.test.tsx
Labels: pr: ready to merge

#10545 Add link to contact support in merchant feedback "No" modal
  changelog/add-10543-merchant-feedback-negative-modal-support-link
  client/merchant-feedback-prompt/negative-modal.tsx
Labels: pr: needs review, pr: ready to merge

#10550 Fix docblock and class description comment
  changelog/fix-10518-fix-docblock-comment-class-description
  includes/notes/class-wc-payments-notes-qualitative-feedback.php
Labels: pr: ready to merge

#10546 Increase merchant feedback prompt button label underline offset
  changelog/fix-10542-merchant-feedback-prompt-label-underline-offset
  client/merchant-feedback-prompt/style.scss
Labels: pr: ready to merge

#10529 Launch the merchant feedback prompt to all eligible merchants
  changelog/add-10458-launch-merchant-feedback-prompt
  client/globals.d.ts
  client/merchant-feedback-prompt/hooks.ts
  client/merchant-feedback-prompt/test/index.test.tsx
  includes/class-wc-payments-features.php
Labels: pr: ready to merge

#10557 Fix fraud settings modal styles causing prompt for review modal UI bugs.
  changelog/fix-10556-scope-fraud-settings-modal-styles
  client/settings/fraud-protection/style.scss
Labels: pr: ready to merge

#10534 Fix validation for support phone numbers for Singapore
  changelog/fix-10373-singapore-phone-number-validation
  client/settings/phone-input/index.tsx
  client/settings/support-phone-input/test/support-phone-input.test.js
Labels: pr: needs review

#10283 Transaction breakdown component for the Payment Details page
  changelog/add-1342-transaction-breakdown-block
  client/data/index.ts
  client/data/timeline/types.d.ts
  client/payment-details/payment-details/index.tsx
  client/payment-details/transaction-breakdown/fees-breakdown/index.tsx
  client/payment-details/transaction-breakdown/fees-breakdown/tests/index.test.tsx
  client/payment-details/transaction-breakdown/hooks.ts
  client/payment-details/transaction-breakdown/index.tsx
  client/payment-details/transaction-breakdown/style.scss
  client/payment-details/transaction-breakdown/tests/hooks.test.ts
  client/payment-details/transaction-breakdown/tests/index.test.tsx
  client/payment-details/transaction-breakdown/tests/utils.test.ts
  client/payment-details/transaction-breakdown/types.ts
  client/payment-details/transaction-breakdown/utils.ts
  includes/multi-currency/client/utils/currency/index.js
Labels: pr: ready to merge

#10563 Revert "Transaction breakdown component for the Payment Details page"
  changelog/add-1342-transaction-breakdown-block
  client/data/index.ts
  client/data/timeline/types.d.ts
  client/payment-details/payment-details/index.tsx
  client/payment-details/transaction-breakdown/fees-breakdown/index.tsx
  client/payment-details/transaction-breakdown/fees-breakdown/tests/index.test.tsx
  client/payment-details/transaction-breakdown/hooks.ts
  client/payment-details/transaction-breakdown/index.tsx
  client/payment-details/transaction-breakdown/style.scss
  client/payment-details/transaction-breakdown/tests/hooks.test.ts
  client/payment-details/transaction-breakdown/tests/index.test.tsx
  client/payment-details/transaction-breakdown/tests/utils.test.ts
  client/payment-details/transaction-breakdown/types.ts
  client/payment-details/transaction-breakdown/utils.ts
  includes/multi-currency/client/utils/currency/index.js
Labels: pr: needs review

#10565 Update payout failure messages for clarity and accuracy
  changelog/fix-10564-payout-failure-messagin-improvements
  client/deposits/details/test/index.tsx
  client/deposits/strings.ts
Labels: pr: ready to merge

#10540 Fix Dispute Notice for Klarna Inquiry.
  changelog/fix-9918-dispute-notice-klarna-inquiry
  client/payment-details/dispute-details/dispute-awaiting-response-details.tsx
  client/payment-details/dispute-details/dispute-notice.tsx
Labels: pr: ready to merge

#10566 Add merchant feedback prompt event names to event union type for improved type safety
  changelog/dev-define-merchant-feedback-prompt-tracks-events-in-event-union-type
  client/tracks/event.d.ts
Labels: pr: ready to merge, category: projects, type: developer experience

#10561 Refactors and updates to the embedded components
  changelog/dev-embedded-component-updates
  client/embedded-components/appearance.ts
  client/embedded-components/hooks.tsx
  client/embedded-components/index.tsx
  client/embedded-components/test/index.tsx
  client/embedded-components/types.ts
  client/onboarding/steps/embedded-kyc.tsx
  client/onboarding/steps/test/embedded-kyc.tsx
  client/onboarding/steps/test/embedded-onboarding.tsx
  client/onboarding/utils.ts
  client/overview/index.js
  client/overview/test/index.js
  client/utils/embedded-components/account-session.ts
  client/utils/embedded-components/kyc-account-session.ts
  client/utils/embedded-components/utils.ts
Labels: type: technical debt, component: onboarding, focus: account lifecycle

#10573 Improve handling for HTTPs errors.
  changelog/dev-error-handling-updates
  client/embedded-components/index.tsx
  client/onboarding/steps/embedded-kyc.tsx
  client/onboarding/style.scss
  client/overview/index.js
  package-lock.json
  package.json
Labels: pr: ready to merge

#10570 Update return type in docblock of class-wc-rest-payments-orders-controller.php to not include null.
  changelog/dev-10569-qit-update-return-type-in-docblock
  includes/admin/class-wc-rest-payments-orders-controller.php
Labels: pr: needs review

#10584 Change self assessment data url key name
  changelog/dev-10580-change-self-assessment-url-key-name
  client/onboarding/index.tsx
  includes/admin/class-wc-rest-payments-onboarding-controller.php
  includes/class-wc-payments-onboarding-service.php
Labels: pr: ready to merge

#10592 chore: tokenized ECE tests for product page
  changelog/chore-add-tokenized-express-checkout-unit-tests
  client/tokenized-express-checkout/__tests__/tokenized-express-checkout--product-page.test.js
  package-lock.json
  package.json
Labels: size: x-small

#10591 Update WeChat Pay countries and currencies
  includes/payment-methods/class-wechatpay-payment-method.php
Labels: component: checkout, focus: checkout payments

#10558 Remove fraud protection discoverability and update tour
  changelog/remove-9726-fraud-protection-discoverability
  client/components/fraud-risk-tools-banner/components/banner-actions/index.tsx
  client/components/fraud-risk-tools-banner/components/banner-actions/test/__snapshots__/index.test.tsx.snap
  client/components/fraud-risk-tools-banner/components/banner-actions/test/index.test.tsx
  client/components/fraud-risk-tools-banner/components/banner-body/index.tsx
  client/components/fraud-risk-tools-banner/components/banner-body/test/__snapshots__/index.test.tsx.snap
  client/components/fraud-risk-tools-banner/components/banner-body/test/index.test.tsx
  client/components/fraud-risk-tools-banner/components/index.tsx
  client/components/fraud-risk-tools-banner/components/new-pill/index.tsx
  client/components/fraud-risk-tools-banner/components/new-pill/test/__snapshots__/index.test.tsx.snap
  client/components/fraud-risk-tools-banner/components/new-pill/test/index.test.tsx
  client/components/fraud-risk-tools-banner/index.tsx
  client/components/fraud-risk-tools-banner/style.scss
  client/components/fraud-risk-tools-banner/test/__snapshots__/index.test.tsx.snap
  client/components/fraud-risk-tools-banner/test/index.test.tsx
  client/overview/index.js
  client/overview/test/index.js
  client/settings/fraud-protection/components/protection-levels/index.tsx
  client/settings/fraud-protection/components/protection-levels/test/__snapshots__/index.test.tsx.snap
  client/settings/fraud-protection/index.tsx
  client/settings/fraud-protection/style.scss
  client/settings/fraud-protection/test/__snapshots__/index.test.tsx.snap
  client/settings/fraud-protection/test/index.test.tsx
  client/settings/fraud-protection/tour/__snapshots__/index.test.tsx.snap
  client/settings/fraud-protection/tour/index.test.tsx
  client/settings/fraud-protection/tour/index.tsx
  client/settings/fraud-protection/tour/steps.tsx
  tests/e2e/env/setup.sh
Labels: pr: needs review

#10602 Add net amount after deducting fees to meta data
  changelog/update-add-net-in-metadata
  includes/class-wc-payments-webhook-processing-service.php
  tests/unit/test-class-wc-payments-webhook-processing-service.php
Labels: pr: ready to merge

#10609 Add rest api endpoints for NOX in-context flows
  changelog/dev-10535-add-rest-api-endpoints-for-nox-in-context
  includes/admin/class-wc-rest-payments-onboarding-controller.php
  includes/class-wc-payments-onboarding-service.php
Labels: pr: ready to merge

#10605 Update tracks event documentation to clarify and distinguish shopper/merchant prefix behavior
  changelog/dev-10604-tracks-event-prefix-code-comments
  client/tracks/event.d.ts
  client/tracks/index.ts
Labels: pr: ready to merge

#10603 Fix errors in WooCommerce email settings preview
  changelog/fix-10436-wcpay-emails-produce-errors-in-woocommerce-email-settings-preview
  includes/compat/subscriptions/class-wc-payments-email-failed-authentication-retry.php
  includes/emails/class-wc-payments-email-ipp-receipt.php
  templates/emails/customer-ipp-receipt.php
  templates/emails/email-ipp-receipt-compliance-details.php
  templates/emails/email-ipp-receipt-store-details.php
Labels: pr: needs review

#10622 Implement proper square braces for checks in shell
  .husky/post-merge
  changelog/dev-fix-post-merge-script
Labels: pr: ready to merge

#10632 Update the progressive parameter in the KYC session creation API to use a boolean type
  changelog/fix-session-creation-eligibility-type
  includes/admin/class-wc-rest-payments-onboarding-controller.php
Labels: pr: needs review

#10600 Add pending refund notes
  changelog/fix-1195-pending-refund
  includes/class-wc-payment-gateway-wcpay.php
  includes/class-wc-payments-order-service.php
  includes/class-wc-payments-webhook-processing-service.php
  includes/class-wc-payments.php
  includes/constants/class-refund-status.php
  tests/unit/test-class-wc-payment-gateway-wcpay-process-refund.php
  tests/unit/test-class-wc-payments-order-service.php
  tests/unit/test-class-wc-payments-webhook-processing-service.php
Labels: pr: ready to merge

#10562 Add stripe account id to the product id metadata to fix the issue when stripe account id changes.
  changelog/fix-3269-add-account-id-to-product-id-metadata
  includes/subscriptions/class-wc-payments-invoice-service.php
  includes/subscriptions/class-wc-payments-product-service.php
  includes/subscriptions/class-wc-payments-subscription-service.php
  includes/subscriptions/class-wc-payments-subscriptions.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/subscriptions/test-class-wc-payments-invoice-service.php
  tests/unit/subscriptions/test-class-wc-payments-product-service.php
  tests/unit/subscriptions/test-class-wc-payments-subscription-service.php
Labels: pr: needs review

#10640 Check the array type the dismissed notices for duplicated payment methods
  changelog/chore-add-array-type-checking
  client/components/duplicate-notice/index.tsx
Labels: size: x-small

#10636 Fix PHP Deprecated: Hook woocommerce_rest_api_option_permissions
  changelog/fix-7864-deprecated-woocommerce_rest_api_option_permissions
  client/components/account-balances/index.tsx
  client/components/duplicate-notice/index.tsx
  client/components/duplicate-notice/tests/index.test.tsx
  client/data/settings/actions.js
  client/deposits/index.tsx
  client/overview/modal/connection-success/index.tsx
  client/overview/modal/connection-success/test/index.test.tsx
  client/overview/modal/progressive-onboarding-eligibility/index.tsx
  client/overview/modal/progressive-onboarding-eligibility/test/index.test.tsx
  client/overview/task-list/index.js
  client/plugins-page/index.js
  client/settings/fraud-protection/tour/index.tsx
  client/settings/payment-methods-list/capability-request/capability-request-notice.tsx
  includes/admin/class-wc-payments-admin.php
  includes/admin/class-wc-rest-payments-settings-option-controller.php
  includes/class-wc-payments.php
  includes/multi-currency/client/data/actions.js
  includes/multi-currency/client/setup/tasks/setup-complete-task/index.js
  includes/multi-currency/client/setup/tasks/setup-complete-task/test/index.test.js
  tests/unit/admin/test-class-wc-rest-payments-settings-option-controller.php
  tests/unit/bootstrap.php
Labels: pr: needs review

#10578 Update Settings page as per the new design
  changelog/add-10559-design-update-setttings-page
  client/settings/express-checkout/style.scss
  client/settings/payment-methods-section/__tests__/payment-methods-section.test.js
  client/settings/payment-methods-section/index.js
  client/settings/settings-layout/style.scss
  client/settings/settings-manager/index.js
  client/settings/settings-manager/style.scss
  client/settings/settings-section.scss
  includes/admin/class-wc-payments-admin.php
Labels: pr: needs review, pr: needs design review

#10656 Fix multicurrency e2e test failing with WooCommerce beta version
  changelog/fix-10551-multicurrency-e2e-test-for-wc-beta-version
  tests/e2e/specs/wcpay/shopper/multi-currency-checkout.spec.ts
Labels: pr: ready to merge

#10655 Implement notifications about Stripe Billing and manual capture incompatibility
  changelog/add-5677-conflict-notices-for-stripe-billing-and-manual-capture
  client/settings/advanced-settings/stripe-billing-section.tsx
  client/settings/transactions/manual-capture-control.tsx
  client/settings/transactions/test/index.test.js
Labels: pr: needs review
