Repository Automattic/woocommerce-payments, pull requests merged in 2025-08, with the labels that each got.

#10997 Fix Google/Apple Pay State / County is required error during checkout for HR customers
  changelog/fix-woopmnt-5240-google-pay-giving-state-county-is-required-error-for-certain
  includes/constants/class-express-checkout-element-states.php
Labels: pr: needs review

#11013 E2E - Fix failures for Shopper: Subscription
  changelog/fix-e2e-test-subscriptions-shopper
  tests/e2e/specs/subscriptions/shopper/shopper-subscriptions-purchase-free-trial.spec.ts
  tests/e2e/specs/subscriptions/shopper/shopper-subscriptions-purchase-no-signup-fee.spec.ts
Labels: pr: ready to merge

#11025 Revert "Amend changelog entries for release 9.9.0"
  changelog.txt
  changelog/dev-fix-e2e-due-to-woosub-7-8-1
  changelog/dev-update-js-packages
  changelog/fix-WOOPMNT-5223-activate-payments-notice-on-live-account
  changelog/fix-afterpay-affirm-order-pay-flow
  changelog/fix-e2e-test-subscriptions-shopper
  changelog/fix-fix-phone-input-styling
  changelog/fix-prevent-link-on-card-form
  changelog/fix-run-id-for-github-action
  changelog/fix-some-missing-i18n-wrappers
  changelog/fix-woopay-terms-and-conditions-blocks-default-texts
  changelog/update-WOOPMNT-5258-business-details-task-link-to-nox
  changelog/update-settings-page-design-audit
  changelog/update-support-phone-input-label-text-in-test-mode
  changelog/update-wp-components-after-react-18
  changelog/woopmnt-5248-checkout-optimization-avoid-multiple-payment-method-details
  changelog/woopmnt-5262-payments-transactions-report-link-to-order-id-if-order
  changelog/woopmnt-5274-tax-setup-modal-should-not-display-for-unsupported-merchants
  readme.txt
Labels: pr: needs review

#11024 E2E: Fixed addSavedCard and Rate Limit adding card too soon with 3DS cards
  changelog/fix-flaky-e2e-addSavedCard
  tests/e2e/specs/wcpay/shopper/shopper-myaccount-saved-cards.spec.ts
  tests/e2e/utils/shopper.ts
Labels: pr: needs review, category: e2e, needs demo, e2e: broken test
