Repository Automattic/woocommerce-payments, pull requests merged in 2025-09, with the labels that each got.

#11031 Do not ask for shipping info for digital products
  changelog/dispute-evidence-for-digital-products-has-no-shipping-info
  client/disputes/new-evidence/index.tsx
Labels: pr: needs review

#11032 Fix: Set `link` wallets option for Stripe Payment Element based on isLinkEnabled
  changelog/fix-conditionally-link-options-in-checkout-form
  client/checkout/classic/payment-processing.js
  client/checkout/utils/__tests__/upe.test.js
  client/checkout/utils/upe.js
Labels: pr: ready to merge

#11034 Fix item data assertions in WooCommerce Product Add-Ons tests
  changelog/fix-wc-compat-beta-product-addons-test
  tests/unit/multi-currency/compatibility/test-class-woocommerce-product-add-ons.php
Labels: pr: ready to merge

#11038 Fix Google/Apple Pay "State / County is required" error during checkout for Saudi Arabia
  changelog/fix-woopmnt-5302-apple-pay-state-county-is-required-error-for-saudi-arabia
  includes/constants/class-express-checkout-element-states.php
Labels: pr: needs review

#11035 [E2E][CI] Ensure version coverage for WooCommerce and PHP
  .github/actions/e2e/run-log-tests/action.yml
  .github/actions/setup-php/action.yml
  .github/scripts/README.md
  .github/scripts/generate-wc-matrix.sh
  .github/workflows/e2e-pull-request.yml
  .github/workflows/e2e-test.yml
  changelog/dev-woopmnt-5249-e2e-ensure-version-coverage-for-woocommerce-and-php
  tests/e2e/README.md
  tests/e2e/env/setup.sh
  tests/e2e/playwright.config.ts
Labels: pr: needs review

#11009 Add feature flag for the dynamic Google/Apple pay button and setttings on the admin
  changelog/add-feature-flag-for-incremental-work-dynamic-checkout-place-order
  client/data/settings/__tests__/actions.test.js
  client/data/settings/__tests__/hooks.test.js
  client/data/settings/__tests__/selectors.test.js
  client/data/settings/actions.js
  client/data/settings/hooks.js
  client/data/settings/selectors.js
  client/globals.d.ts
  client/settings/express-checkout-settings/__tests__/index.test.js
  client/settings/express-checkout-settings/__tests__/payment-request-settings.test.js
  client/settings/express-checkout-settings/payment-request-settings.js
  includes/admin/class-wc-rest-payments-settings-controller.php
  includes/class-wc-payments-features.php
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
Labels: pr: needs author reply

#11036 [E2E] Stabilize flaky specs and helpers
  changelog/dev-woopmnt-5249-e2e-fixes
  tests/e2e/specs/wcpay/merchant/merchant-disputes-respond.spec.ts
  tests/e2e/specs/wcpay/shopper/shopper-checkout-purchase-with-upe-methods.spec.ts
  tests/e2e/specs/wcpay/shopper/shopper-myaccount-payment-methods-add-fail.spec.ts
  tests/e2e/specs/wcpay/shopper/shopper-myaccount-saved-cards.spec.ts
  tests/e2e/utils/shopper.ts
Labels: pr: ready to merge

#11005 [E2E] Re-enable Woocommerce Blocks e2e tests
  .github/workflows/e2e-pull-request.yml
  .github/workflows/e2e-test.yml
  changelog/dev-woopmnt-5251-e2e-investigate-and-re-enable-woocommerce-blocks-e2e-tests
  tests/e2e/README.md
  tests/e2e/playwright.config.ts
  tests/e2e/specs/wcpay/shopper/shopper-wc-blocks-checkout-failures.spec.ts
  tests/e2e/specs/wcpay/shopper/shopper-wc-blocks-checkout-purchase.spec.ts
  tests/e2e/specs/wcpay/shopper/shopper-wc-blocks-saved-card-checkout-and-usage.spec.ts
Labels: pr: ready to merge

#11040 Bump WC tested up to version to 10.2.0
  changelog/dev-bump-wc-version-10-2-0
  woocommerce-payments.php
Labels: 10.0.0

#11037 [Disputes] Introduce a loading state to the “Challenge dispute” (new evidence) flow
  changelog/dev-woopmnt-5249-disputes-ui
  client/disputes/new-evidence/index.tsx
  tests/e2e/specs/wcpay/merchant/merchant-disputes-respond.spec.ts
Labels: pr: ready to merge

#11050 Replace BOTWOO_TOKEN in pr-build-live-branch workflow with github-actions bot
  .github/workflows/pr-build-live-branch.yml
  changelog/fix-botwoo-in-pr-live-branch-workflow
Labels: pr: needs review, focus: devops

#11048 Implement AccountDetails component with server data
  changelog/woopmnt-5282-implement-all-elements-with-data-from-the-server
  client/components/account-details/__tests__/index.test.tsx
  client/components/account-details/banner.tsx
  client/components/account-details/header-title.tsx
  client/components/account-details/index.tsx
  client/components/account-details/payout-status-wrapper.tsx
  client/components/account-details/style.scss
  client/components/account-details/utils.ts
  client/components/chip/index.tsx
  client/components/chip/style.scss
  client/overview/index.js
  client/types/account/account-details.d.ts
Labels: pr: ready to merge

#11066 Handle dispute counts for menu items between live and test mode
  changelog/woopmnt-5346-disputes-menu-item-badged-in-live-mode-for-test-disputes
  includes/admin/class-wc-payments-admin.php
  includes/class-database-cache.php
  includes/class-wc-payments-webhook-processing-service.php
  includes/wc-payment-api/class-wc-payments-api-client.php
Labels: pr: ready to merge

#11067 Fix _load_textdomain_just_in_time error when loading a non-existing payment method settings
  changelog/woopmnt-5293-function-_load_textdomain_just_in_time-was-called
  includes/class-wc-payment-gateway-wcpay.php
  tests/unit/admin/test-class-wc-rest-payments-settings-controller.php
  tests/unit/express-checkout/test-class-wc-payments-express-checkout-button-helper.php
  tests/unit/test-class-wc-payments-woopay-button-handler.php
Labels: pr: ready to merge

#11063 Fix edge case when shipping information is added by mistake for digital products
  changelog/fix-edge-case-when-shipping-information-is-added-by-mistake
  client/disputes/new-evidence/index.tsx
  client/disputes/new-evidence/types.ts
Labels: pr: needs review
