Repository Automattic/woocommerce-payments, pull requests merged in 2025-04, with the labels that each got.

#10634 Update breadcrumbs back link to wc_back_header / wc_back_link for tertiary+ level pages in WooPayments settings
  changelog/update-add-wc-back-links-in-woopayments-settings
  client/settings/express-checkout-settings/__tests__/index.test.js
  client/settings/express-checkout-settings/index.js
  includes/class-wc-payment-gateway-wcpay.php
  tests/unit/test-class-wc-payment-gateway-wcpay.php
Labels: pr: needs review

#10661 fix: ECE display on pay-for-order pages
  changelog/fix-ece-not-displayed-on-pay-for-order
  client/tokenized-express-checkout/__tests__/tokenized-express-checkout--order-pay-page.test.js
  client/tokenized-express-checkout/index.js
Labels: size: x-small

#9914 HACK week: Improve express checkout layout for better experience
  changelog/improve-ece-loading-experience
  client/checkout/express-checkout-buttons.scss
  client/express-checkout/button-ui.js
  client/tokenized-express-checkout/__tests__/tokenized-express-checkout--product-page.test.js
  client/tokenized-express-checkout/button-ui.js
  includes/express-checkout/class-wc-payments-express-checkout-button-display-handler.php
  includes/express-checkout/class-wc-payments-express-checkout-button-handler.php
Labels: focus: checkout payments

#10672 Remove level3 retry logic and legacy request_with_level3_data method
  changelog/woopmnt-4896-cleanup-remove-level3-retries
  includes/wc-payment-api/class-wc-payments-api-client.php
  tests/unit/test-class-wc-payment-gateway-wcpay-payment-types.php
  tests/unit/wc-payment-api/test-class-wc-payments-api-client.php
Labels: pr: ready to merge

#10441 Fix WooPay enabled during NOX onboarding despite being disabled in recommended payment methods
  changelog/fix-10440-woopay-capability-disable
  includes/class-wc-payments-account.php
  includes/class-wc-payments-onboarding-service.php
  tests/unit/test-class-wc-payments-account.php
Labels: pr: ready to merge

#10679 Retrieve error message for the Stripe Billing subscription renewal failure
  changelog/woopmnt-4601-stipe-billing-when-a-renewal-invoice-fails-fetch-the-reason
  includes/subscriptions/class-wc-payments-subscriptions-event-handler.php
Labels: pr: ready to merge

#10684 Fix potential fatal errors in the subscriptions code
  changelog/woopmnt-4914-fatal-errors-with-is_duplicate_site-and
  includes/multi-currency/Compatibility/WooCommerceSubscriptions.php
  includes/subscriptions/class-wc-payments-subscriptions.php
Labels: pr: needs review

#10683 Simplify logger overrides and place response/request body in the context
  changelog/woopmnt-4899-update-logging-format-to-be-more-compatible-with-woo-core
  includes/class-logger-context.php
  includes/class-logger.php
  includes/class-wc-payments-webhook-processing-service.php
  includes/wc-payment-api/class-wc-payments-api-client.php
  src/Internal/Logger.php
  src/Internal/LoggerContext.php
  tests/unit/src/Internal/LoggerContextTest.php
  tests/unit/src/Internal/LoggerTest.php
  tests/unit/test-class-wc-payments-webhook-processing-service.php
Labels: pr: ready to merge

#10691 Remove the referrer check to update the fraud protection settings
  changelog/fix-10673-fraud-protection-settings-referer-check
  includes/admin/class-wc-rest-payments-settings-controller.php
Labels: pr: needs review

#10677 Improve refund failure handling with detailed error messages
  changelog/woopmnt-4892-handle-more-refund-failure-reason-codes-in-refund-notes
  includes/class-wc-payments-order-service.php
  includes/class-wc-payments-webhook-processing-service.php
  includes/class-wc-payments.php
  includes/constants/class-refund-failure-reason.php
  tests/unit/contants/test-class-refund-failure-reason.php
  tests/unit/test-class-wc-payments-order-service.php
  tests/unit/test-class-wc-payments-webhook-processing-service.php
Labels: pr: needs review

#10704 Update to check for at least one field of the self assessment data being set
  changelog/dev-fix-account-session
  client/embedded-components/hooks.tsx
Labels: pr: ready to merge

#10703 Improve styling of the Embedded components to be consistent and closer to WPDS
  changelog/fix-woopmnt-4909-tweak-embedded-components-style
  client/embedded-components/appearance.ts
Labels: pr: ready to merge

#10706 Advanced fraud protection settings redesign
  changelog/update-woopmnt-4905-fraud-settings-redesign
  client/globals.d.ts
  client/index.js
  client/settings/fraud-protection/advanced-settings/cards/address-mismatch.tsx
  client/settings/fraud-protection/advanced-settings/cards/avs-mismatch.tsx
  client/settings/fraud-protection/advanced-settings/cards/cvc-verification.tsx
  client/settings/fraud-protection/advanced-settings/cards/international-ip-address.tsx
  client/settings/fraud-protection/advanced-settings/cards/ip-address-mismatch.tsx
  client/settings/fraud-protection/advanced-settings/cards/order-items-threshold.tsx
  client/settings/fraud-protection/advanced-settings/cards/purchase-price-threshold.tsx
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/address-mismatch.test.tsx.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/avs-mismatch.test.tsx.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/cvc-verification.test.tsx.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/international-ip-address.test.tsx.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/ip-address-mismatch.test.tsx.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/order-items-threshold.test.tsx.snap
  client/settings/fraud-protection/advanced-settings/cards/test/__snapshots__/purchase-price-threshold.test.tsx.snap
  client/settings/fraud-protection/advanced-settings/index.tsx
  client/settings/fraud-protection/advanced-settings/rule-card.tsx
  client/settings/fraud-protection/advanced-settings/rule-toggle.tsx
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/index.test.tsx.snap
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/rule-card.test.tsx.snap
  client/settings/fraud-protection/advanced-settings/test/__snapshots__/rule-toggle.test.tsx.snap
  client/settings/fraud-protection/advanced-settings/test/index.test.tsx
  client/settings/fraud-protection/advanced-settings/test/rule-card.test.tsx
  client/settings/fraud-protection/advanced-settings/test/rule-toggle.test.tsx
  client/settings/fraud-protection/style.scss
  client/utils/index.js
  client/utils/test/index.js
Labels: pr: ready to merge

#10714 Fix express checkout container spacing on product pages
  changelog/woopmnt-4919-express-checkout-container-spacing
  client/checkout/express-checkout-buttons.scss
Labels: pr: needs review

#10719 Add disable test drive account REST API endpoint
  changelog/update-disable-test-mode-account-api
  includes/admin/class-wc-rest-payments-onboarding-controller.php
  includes/class-wc-payments-account.php
  includes/class-wc-payments-onboarding-service.php
Labels: pr: ready to merge

#10717 fix: assign new blog to e2e tests
  .github/workflows/e2e-pull-request.yml
  .github/workflows/e2e-pw-pull-request.yml
  .github/workflows/e2e-test.yml
  changelog/fix-e2e-tests-new-blog
  includes/class-wc-payment-gateway-wcpay.php
  tests/e2e/README.md
  tests/e2e/docker-compose.yml
  tests/e2e/env/setup.sh
  tests/e2e/reporters/slack-reporter.ts
  tests/e2e/specs/wcpay/merchant/merchant-payment-gateways-confirmation.spec.ts
  tests/e2e/specs/wcpay/shopper/shopper-bnpls-checkout.spec.ts
  tests/e2e/specs/wcpay/shopper/shopper-myaccount-saved-cards.spec.ts
  tests/e2e/utils/devtools.ts
  tests/e2e/utils/shopper-navigation.ts
  tests/e2e/utils/slack.ts
Labels: pr: needs review

#10729 Integrate QIT security and malware into PR checks
  .github/workflows/qit.yml
  changelog/WOOPMNT-4936
  package.json
  tests/qit/malware.sh
Labels: pr: ready to merge
